### ISSUE TITLE
ArgumentError: uncaught throw :warden

### ISSUE THREAD

**Issue by felix** [plataformatec/devise#1029]
This could well be just me but...

since 1.3.1 I am getting this error consistently throughout an app which had all tests working on 1.3.0. It happens in each release up to 1.3.3.

In my functional tests I have been logging in via a `sign_in @user` call and the uncaught exception thrown from warden occurs while in the call to `authenticate_user!` in the actual controller(s).

**Comment by jeffdill2** [comment]
Where should `include Devise::TestHelpers` be declared if you're using RSpec instead of the default tests?

Sorry for opening up such an old thread, but it's proved insufferably hard to find almost *any* resources on this subject matter.

Thanks!

**Comment by carlosantoniodasilva** [comment]
@jeffdill2 you must also set the devise mapping, [like shown in this wiki](https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-(and-RSpec)). Hope that helps.

**Comment by jeffdill2** [comment]
@carlosantoniodasilva yep, I have that set

```
describe SessionsController do
  before do
    @request.env["devise.mapping"] = Devise.mappings[:user]
  end

  ...
```

**Comment by mjtko** [comment]
@jeffdill2 I've just encountered this -- in my case I was requiring my support files and thereby performing the `config.include Devise::TestHelpers, type: :controller` *before* I was doing `require 'rspec/rails'`.  That meant the inheritance hierarchy was in the wrong (unexpected) order, and causing it break with the uncaught throw.

HTH!

**Comment by lboix** [comment]
@jeffdill2 I faced exactly the same situation than you, and @mjtko is right (thank you so much man!)

All worked perfectly once I moved this include line (*config.include Devise::TestHelpers, :type => :controller*) elsewhere (I chose spec/rails_helper.rb)

**Comment by bogdanvlviv** [comment]
require 'devise' # in spec_helper.rb
include Devise::TestHelpers 
# in (your)_spec.rb
# example
require 'rails_helper'

RSpec.describe ProjectsController, type: :controller do
  include Devise::TestHelpers
  # ...
  describe "GET #index" do
    # ...
  end
  # ...
end
