### ISSUE TITLE
Allow omniauth configuration to come from database at login time

### ISSUE THREAD

**Issue by tylergannon** [plataformatec/devise#1034]
Hi, I am creating a multi-tenant application platform and would like to be able to host multiple facebook apps from the same rails application.  I am more than happy to write the code to enable this feature (especially if it hasn't already been written), but wanted to ask for any pointers that could make the task easier to get started.  If you could offer some hints as to where in the stack (and how, and when) the facebook app id and app secret key are loaded and used, that would be really helpful.

thanks!  
Tyler Gannon

**Comment by theodorton** [comment]
For anyone else looking for a solution to this problem:
https://github.com/intridea/omniauth/wiki/Setup-Phase
