### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by bhellman1** [plataformatec/devise#1038]
Devise does a great job when: An unauthenticated users hits a site with a URL:

http://www.site.com/groups/1

The user is redirected to sign in. After signing in, the user is redirect to their first url request: http://www.site.com/groups/1

Problem is if the site is ajax/deep linked with anchor tags, devise ignores the URL. Example:

http://www.site.com/#/groups/1

Devise is ignoring everything after the hash... Why?

**Comment by prateekkish** [comment]
It is because the deeplinks (the hash code) doesn't get sent to the server. However when the user is sent to sign in page, the deep link stays there and only disappears after the redirect.
