### ISSUE TITLE
Cannot PUT to update a Devise registration with token authentication

### ISSUE THREAD

**Issue by wtn** [plataformatec/devise#1059]
When I `PUT` to `/users` with a JSON request and a `token_authenticatable` token, I get a 401 error and the following response:

`{"error":"You need to sign in or sign up before continuing."}`

Here's my `curl` request. I can successfully `PUT` with my token to other Rails controllers that require authentication. I can `POST` to the registrations controller to create a new user and it returns JSON—thanks a lot for supporting JSON responses in edge Devise!

I tried using `POST` along with setting the `_method` parameter to `put` but that did not work—Rails thought I was creating a new user. I also tried including the token in the header as HTTP Basic Auth or as a URL-encoded parameter.

> curl -H 'Content-Type: application/json' \
> -H 'Accept: application/json' \
> -X PUT http://localhost:3000/users \
> -d '{"auth_token": "QxaH4wF2g4nS0B0vwH5O", "user": {"birthday": "1918-01-01", "country": "United States", "email": "user@example.com", "first_name": "Jason", "gender": "m", "last_name": "Filbert", "postal_code": "93111", "username": "jf"}}'

I am using edge Devise (ref `e763f843c436e0cdc426` from 2011-05-04), Ruby 1.9.2p180, Warden 1.0.3, OrmAdapter 0.0.5, OAuth2 0.4.1, Faraday 0.6.1, and Rails 3.0.7.

This issue is similar to a problem discussed on the mailing list last October:
http://groups.google.com/group/plataformatec-devise/browse_thread/thread/a80f266e5dd83f67/ed33e5d01064c8a2?lnk=gst&q=json#ed33e5d01064c8a2

**Comment by jurajpaulo** [comment]
I'm experiencing the same issue with devise 4.3.1, rails 4.1.10
Getting 401 on PUT request to /users with auth_token
