### ISSUE TITLE
Devise & Omniauth Sessions lost

### ISSUE THREAD

**Issue by ened** [plataformatec/devise#1065]
I'm having a problem that omniauth sessions are somehow not persisted for some users, while others have no problems.

The description can be found here: http://stackoverflow.com/questions/5816294/omniauthfacebook-lost-session

I read / heard about problematic session behavior with the Omniauth Module, i.e. the callback in users/omni.. is being handled outside the regular session scope. 

Right now I just feel this is a bug in Devise or the Omniauth integration, as it's very weird and looks like by chance. The outcome of this ticket is hopefully to shine a light for others too.

Thanks for any hints.

**Comment by sergeygolubev** [comment]
katgironpe, thanks dude, it helped
