### ISSUE TITLE
undefined method `user_signed_in?' 

### ISSUE THREAD

**Issue by bonyiii** [plataformatec/devise#1078]
Rails 3 devise authentication produces the error in the title, in development mode for the first run, in prdouction mode all the times.

In my case, the root of the problem is that i use "clear_helpers" in application_controller.rb. 
If i remove "clear_helpers" everything works just as expected. I guess clear_helpers removes devise helpers, strange thing is, it does only for first run.

Backtrace:
ActionView::Template::Error (undefined method `user_signed_in?' for #<#<Class:0xbe60720>:0xbe5f2e4>):
    2: <% if user_signed_in? %>
    3: 
    4: <%= ("Signed in as") %>&nbsp;<%= link_to current_user.login, edit_user_registration_path %>.&nbsp;<%= ("Not you?") %>&nbsp;<%= link_to ("Sign out"), destroy_user_session_path %>
    5: <% else %>  app/views/shared/_user_info_bar.html.erb:2:in`_app_views_shared__user_info_bar_html_erb__628171672_99462210_603149262'
  app/views/layouts/house.html.erb:28:in `_app_views_layouts_house_html_erb__161627738_99790620__616475931'

Rendered /home/boni/.rvm/gems/ruby-1.9.2-p180@rails3/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/_trace.erb (5.0ms)
Rendered /home/boni/.rvm/gems/ruby-1.9.2-p180@rails3/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (34.5ms)
Rendered /home/boni/.rvm/gems/ruby-1.9.2-p180@rails3/gems/actionpack-3.0.7/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (55.7ms)

gems:
warden (1.0.4, 1.0.3)
devise (1.3.4, 1.3.0)
activemodel (3.0.7)
activerecord (3.0.7)
activeresource (3.0.7)
activesupport (3.0.7)
actionmailer (3.0.7)
actionpack (3.0.7)

**Comment by jackson-sandland** [comment]
Dude. Thank you! @ambethia
