### ISSUE TITLE
warden uses outdated remote_ip implementation

### ISSUE THREAD

**Issue by fredv** [plataformatec/devise#1186]
Hi there,

thank you for this great gem. Used it a lot during the last year. 

Since our setup is behind a HAProxy which preserves the external request ip through a HTTP_X_FORWARDED_FOR header, we need this as remote_ip in the Trackable last/current_sign_in_ip . Rails latest ActionController::AbstractRequest does provide this in its implementation of remote_ip. Warden.request does however not.

This can either be adjusted in warden or devise trackable. The implementation is usable (to not have to require action_controller): http://ap.rubyonrails.org/classes/ActionController/AbstractRequest.html#M000223).

We fixed this (ugly for now) in an update on the after_sign_in_path method. Is there a more fitting spot/hook?

Best Regards,
Fred

**Comment by 501st-alpha1** [comment]
This also happens for me. I'm running `unicorn` behind `nginx`, with `devise 3.4.1` on `rails 4.0.13`. The logged in IP is always recorded as `127.0.0.1`.

**Comment by 501st-alpha1** [comment]
I solved this by adding `proxy_set_header CLIENT_IP $remote_addr;` to my `nginx.conf`. (I didn't have the `X-Real-IP` or `X-Client-IP` headers that @quark-zju does.) I found this solution at [this StackOverflow post](http://stackoverflow.com/a/12432842/2747593).

**Comment by tonydm** [comment]
Here's the solution I found after reviewing the actiondispatch.. remote_ip.rb source.  Now I get proper IP my devise/warden process as well as any other routine I'm looking at request.remote_ip

My config...
Ruby 2.2.1 - Rails 4.2.1 - NGINX v1.8.0 - Unicorn v4.9.0 - Devise v3.4.1

nginx.conf
HTTP_CLIENT_IP vs CLIENT_IP
```
  location @unicorn {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header HTTP_CLIENT_IP $remote_addr;  <-----
    proxy_redirect off;
    proxy_pass http://unicorn;
  }
```
Source actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb
