### ISSUE TITLE
How to authenticate the user with warden/devise in a customized way?

### ISSUE THREAD

**Issue by millisami** [plataformatec/devise#1230]
This is a Rails 3.0 app with Mongoid as ODM. Following is the user model in which the devise is installed.

```
class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  field :email
  field :username
  field :loginable_token

end
```

I'm building an API. So, for authentication I wanted to authenticate the users with :email and :password. From the GUI, its fine and working. 

Now, I want to implement it via API, so I ve created a separate route `/api_login.json` that hits the `login` action with params `{"username"=>"kapil@gmail.com", "password"=>"sachin", "action"=>"login", "controller"=>"api/v1/accounts", "format"=>"json"}`

When I try to authenticate with the `warden.authenticate!(:scope => :user)` method before `sign_in`, it blows up with the following backtrace.

```
(rdb:1) l
[3, 12] in /Users/sts-151sts-151/Dev/cloudfactory/app/controllers/api/v1/accounts_controller.rb
  3      respond_with(@current_account)    
  4    end
  5    
  6    def login
  7      debugger
=> 8      resource = warden.authenticate!(:scope => :user)
  9       sign_in(:user, resource)
  10      if user == nil
  11        
  12        respond_with(User.account.apps.first)
(rdb:1) p params
{"username"=>"kapil@gmail.com", "password"=>"sachin", "action"=>"login", "controller"=>"api/v1/accounts", "format"=>"json"}
(rdb:1) rs = warden.authenticate!(:scope => :user)
*** Unknown command: "rs = warden.authenticate!(:scope => :user)".  Try "help".
(rdb:1) p rs = warden.authenticate!(:scope => :user)

 1) /api/v1/lines POST send back the default app
    Failure/Error: last_response.status.should eql(200)

expected 200
    got 401

(compared using eql?)

    # ./spec/api/v1/accounts_spec.rb:46:in `block (3 levels) in <top (required)>'
```

The test is via default `rack-test` way.

What is correct way to authenticate?

**Comment by habitullence** [comment]
Was a solution ever found for this? I'm having the same problem trying to use the following JSON-API schema to authenticate:

```json
{
  "data" => {
    "type" => "user-session",
    "attributes" => {
      "email" => user.email,
      "password" => user.password
    }
  }
}
```

I'll have another go at trying to dig into Devise code tomorrow (maybe I'm missing something obvious, but already spent half a day trying to figure this out).

**Comment by RyanRusnak** [comment]
@habitullence I cannot remember what I was working on when I got this working but did you try the before filter allow_params_authentication?

prepend_before_filter :allow_params_authentication!, only: :create

**Comment by habitullence** [comment]
Thanks @RyanRusnak, AFAIK this doesn't allow the format to be changed.

**Comment by StevenXL** [comment]
Yea i know this issue was opened in 2011, but for what is worth, this completely solved the problem I was having, which was that I was not sending the data in the right shape - i.e. `{email: email, password: password}` is wrong; `{user: {email: email, password: password}}` is correct.

**Comment by lalit-nga** [comment]
I will going to summary the solution for beginner. Nothing else :) Thanks everyone :)

```
user = User.find_by(email: params[:email].downcase)

if  user && user.valid_password?(params[:password])
   
   {token: access_token}
else
   error!('Unauthorized.', 401)
end
```

**Comment by pierrea** [comment]
@StevenXL You saved me! Thanks

**Comment by shlima** [comment]
@lalit-nga your solution does not cover `confirmable`, `lockable` and similar modules.

The correct way for doing this in my mind the following:

```ruby
class User < ApplicationRecord
  def self.find_and_validate_for_authentication(params)
    user = find_for_database_authentication(params.except(:password)) || new(params)

   if user.new_record?
     user.errors.add(:email, :invalid_email_or_password)
   elsif !user.valid_password?(params[:password])
     user.errors.add(:email, :invalid_email_or_password)
   elsif !user.active_for_authentication?
     user.errors.add(:email, user.inactive_message)
   end
    
    user
  end
end
```

**Comment by shubham045** [comment]
I think this may solve your problem
self.user = warden.authenticate!(auth_options)

**Comment by audsull** [comment]
@shlima @lalit-nga, I was able to solve this for `lockable` with replacing `user && user.valid_password?(params[:password])` in @lalit-nga solution with `user.valid_for_authentication? { user.valid_password?(params[:password]) }` found here: https://stackoverflow.com/questions/23147889/lockable-is-not-working-in-devise/43102777#43102777
