### ISSUE TITLE
Trim whitespace from username on login

### ISSUE THREAD

**Issue by thomax** [plataformatec/devise#1243]
The problem: When a user attempts to log in and accidentally hits space at the beginning or end, login will fail with "Invalid email or password". Debugging the reason for the failed login will not be easy for the user.

Suggested solution: Trim whitespace(s) from the username before looking up the user to which it belongs.

This solution would effectively disallow a username to begin or end with whitespace(s), but that is probably a very minor nuisance?

**Comment by zhuangbifanisme** [comment]
plz,strip_whitespace_keys can use for  password to stirp whitespace?
