### ISSUE TITLE
parse_authentication_key_values doesn't work for multiple authentication keys

### ISSUE THREAD

**Issue by rclements** [plataformatec/devise#1255]
So I've configured devise to allow either email or login authentication.  I know I've seen this work before, but I'm having a problem with it, and I can even track down explicitly why I'm having the problem.

```
  # Parse authentication keys considering if they should be enforced or not.
  def parse_authentication_key_values(hash, keys)
    keys.each do |key, enforce|
      value = hash[key].presence
      if value
        self.authentication_hash[key] = value
      else
        return false unless enforce == false
      end
    end
    true
  end
```

If the first key is not present in a request, then this will return false (and never check for the second key).  Wouldn't it make sense to check for all possible authentication keys before returning false from this method?

Maybe I'm misunderstanding something.  Thanks for any help.

**Comment by leonsp** [comment]
Sorry for comment necromancy, but is it possible for `enforce` to ever be `true`? `authentication_keys` are an array in all examples I can see, not a hash, so `enforce` would always be `false`
