### ISSUE TITLE
RoR devise: sign_in always returns invalid email/password

### ISSUE THREAD

**Issue by dickyblue** [plataformatec/devise#1333]
I already had a user model, but followed the instructions to AddDevise migration and everything seems to be going well, except...

Every time I log in, I get the error msg that the email/password is invalid.

routes:

```
devise_for :users

devise_scope :users do
  get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  post '/users/sign_in' => 'devise/sessions#create', :as => :user_session
end

resources :users
```

user model:

```
devise :database_authenticatable, :confirmable, :recoverable, :rememberable, :trackable

attr_accessor :password
attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :gender, :remember_me
```

view:

```
<% if signed_in?(:user) %>
   Hi <%= current_user.first_name %>. | Not you? <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<% else %>
   <%= link_to 'Sign up', signup_path %> or <%= link_to 'Sign in', user_session_path, :method => :create %>
<% end %>
```

I tried changing the routes to:

```
get '/users/sign_in' => 'devise/sessions#new', :as => :new_user_session
```

and changing the respective paths, but that didn't change anything.

I even changed the code in the view from: 

```
if signed_in?(:user)
```

to:

```
if user_signed_in?
```

and did a combination of these things and nothing is working.  

I did ask devise to handle the confirmation as well, which I did by copying the generated link to the browser and it signs me in as the user the first time.  It also allows me to change the password via the email confirmation link, which also signs me in upon changing the password.  But once I sign out and sign back in, it tells me that the email/password is invalid again.

It shows the "invalid email or password" error message even if I just click on the "Sign in" link from the home page before I even put in an email or password.  It's almost like it's part of the template.

I even tried uninstalling and reinstalling it and I have the same issue.  When I create a whole new app that did not require confirmations, it works fine.  Could that be the issue?

Or is it because it's not compatible with other gems I have?

I am using rails 3.0.7, devise 1.4.5, capybara 1.1.1, cucumber 1.0.6, mysql2 0.2.6 and rake 0.8.7 if that helps anyone.

Thanks

**Comment by ravistm** [comment]
im also having same issue in AWS Rails server, not able to login. If anybody has the solution. pls suggest
