### ISSUE TITLE
Devise, Heroku and the Asset Pipeline

### ISSUE THREAD

**Issue by bradleypriest** [plataformatec/devise#1339]
I'm not sure if this has been mentioned before, and I'm not sure where to even start fixing it. 
When deploying a Rails 3.1 app to Heroku, it runs the asset compilation rake task during the deploy.
However in an app with devise in it this compilation fails because the devise_for route helper causes the rake task to need to talk to the database, which doesn't exist yet.

Is this something that can be changed on Devise's end? 

Any thoughts?
Cheers,
Brad

**Comment by moustafasamir** [comment]
it was fixed for me by adding attr_accessor :terms_of_service

**Comment by travisjtodd** [comment]
Thanks @moustafasamir Works!
