### ISSUE TITLE
Can you give a tutorial to use devise login using ajax?

### ISSUE THREAD

**Issue by naveedtariq** [plataformatec/devise#1342]
I have been trying to log the users in through ajax. I have tried to follow this article to attain this:

http://jessehowarth.com/2011/04/27/ajax-login-with-devise.

It all goes well except that now if I submit the form empty it gives me the error that is "'You need to sign in or sign up before continuing.'" instead of saying "Email can't be blank" and "Password can't be blank".

If youcan add a HOW TO that would great.

Thanks

**Comment by oarod** [comment]
This stackoverflow post helped me figure out the `:js` responses: http://stackoverflow.com/questions/22689877/devise-ajax-login-sessionscreate-only-render-create-js-erb-when-it-succeed/31713225#31713225
