### ISSUE TITLE
about config.sign_out_via = :delete

### ISSUE THREAD

**Issue by krzkrzkrz** [plataformatec/devise#1351]
Ive got:

```
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
```

Routes says:

```
destroy_user_session DELETE /users/sign-out(.:format)     {:action=>"destroy", :controller=>"users/sessions"} 
```

But when I click this link, I get:

```
Routing error
No route matches [GET] "/users/sign-out"
```

So I did a bit of research and found out that Devise recently added something in their initializers/config file. Specifically `config.sign_out_via = :delete`.

So it should be working, but its not. 

I read somewhere else that changing `config.sign_out_via = :delete` to `config.sign_out_via = :get` should work. I tried that and it did!

However, my link_to still looks like: `<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>`, which is inconsistent since my Devise initializer file has `config.sign_out_via = :get`.

Running on Rails 3.1, Devise 1.4.7.

Is this a bug?

**Comment by mices** [comment]
You have to use button_on with method :delete, otherwise rails routes to the show view

**Comment by polyglotdev** [comment]
@mices Where did you find the information that denotes that `link_to` implies a `GET` request because I looked [the API docs](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to) and I can't find that. Your suggestion did fix the issue though so thanks for that!

**Comment by abubakarfarooq123** [comment]
@mices  thanks alot i have stuck on this since 3 days but didn't get the answer and now today just found your comment thanks....!
By the way where you studied that link_to generates GET request????

**Comment by toppyc4** [comment]
@mices i used button_on and get an error, so i used button_to instead and able to run my code thanks
