### ISSUE TITLE
undefined method `new_registration_path' in rails 3.1 and devise 1.4.7

### ISSUE THREAD

**Issue by Keardo** [plataformatec/devise#1358]
In older versions i see this issue, but now in devise version 1.4.7 it's again.

NoMethodError in Devise/sessions#new

Showing /usr/local/lib/ruby/gems/1.9.1/gems/devise-1.4.7/app/views/devise/shared/_links.erb where line #6 raised:

undefined method `new_registration_path' for #<#Class:0xb3c20ebc:0xb3c1b14c>

Extracted source (around line #6):

3: <% end -%>
4: 
5: <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
6:   <%= link_to "Sign up", new_registration_path(resource_name) %><br />
7: <% end -%>
8: 
9: <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>

**Comment by wellington1993** [comment]
Thanks!

**Comment by aneilwebber** [comment]
Cool!! It works!

**Comment by promiseverma** [comment]
Thanks,
Restart worked.

**Comment by isidrolv** [comment]
Thanks,
I was struggling with that, 

yeah! restart worked!

**Comment by Forison** [comment]
thanks,it worked forme as too
