### ISSUE TITLE
Force user to change password

### ISSUE THREAD

**Issue by alexey** [plataformatec/devise#1449]
Would be nice when admin create & notify user, add module like ":forceable" to force user change password when he login first time.

**Comment by TheAshwanik** [comment]
> Hi,
> 
> i already created that before creating "issue" :) , just come to my mind as
> idea for devise !
> 
> 2011/11/20 Carlos Antonio da Silva <
> [reply@reply.github.com](mailto:reply@reply.github.com)
> 
> > You could create that easily in your application with either a Warden hook
> > or a before_filter, to check if that was the 1st time the user was signing
> > in, and then redirect to a proper url to change user password. Shouldn't be
> > hard, but I believe it's not something we should add to Devise itself.
> > Thanks.
> > 
> > Reply to this email directly or view it on GitHub:
> > [#1449 (comment)](https://github.com/plataformatec/devise/issues/1449#issuecomment-2803595)
> 
> _Alexey Z.,_ :_skype_ _::_ _cat_of_duty_

Any chance we could refer your solution?

**Comment by jrochkind** [comment]
I am also interested in functionality for "force password reset after first login with password", that isn't necessarily limited to first login to the account.  Setting a temporary password that can only be used once, and after that requires a password change, is a common "enteprisey" feature.

**Comment by swedishpotato** [comment]
I think having a flag to force password reset (for whatever reason) on next user login should be a critical function of Devise (which is excelent by the way), as this is a great way of blocking suspect accounts or even resetting the entire user database passwords.
