### ISSUE TITLE
Making remember_me configurable to be turned on by default

### ISSUE THREAD

**Issue by bittersweet** [plataformatec/devise#1513]
I came across [this](https://groups.google.com/group/plataformatec-devise/browse_thread/thread/4b69ac4df0133563/7e5fc93a9e51c797?lnk=gst&q=remember_me#7e5fc93a9e51c797) google group message that was asking if it was possible to turn the remember me functionality on by default, so you won't have to check a checkbox. 

That was exactly what I was looking for so I was wondering if you are still open for a patch that makes this configurable? And if so, do you have any notes before I start working on it? :-)

**Comment by akz92** [comment]
+1 to asiniy's solution. After testing many alternatives and none of them working this one works like a charm.

**Comment by hunainkapadia** [comment]
@asiniy , where you would put that function?

**Comment by akz92** [comment]
@hunainkapadia you put that function in your resource (usually 'User') model.

**Comment by alexcorremans** [comment]
I'm using Ruby version 2.7.4, and asiniy's solution didn't work. I don't have time to check when this changed but I think `nil` doesn't evaluate to `false` anymore for this Ruby version, and therefore `super == nil` will return `false` instead of `true` as intended. 

The below works for me: 

```ruby
def remember_me
    super ? super : true
end
```
