### ISSUE TITLE
Routes error in Devise 1.1.pre - undefined method `new_user_registration_path' for #<Class>

### ISSUE THREAD

**Issue by tricomsol** [plataformatec/devise#152]
Today i updated my bundle for latest rails which fetches latest rails 3 and latest devise from their git hub repositories. When i ran my cucumber features i started getting errors like

 undefined method `new_user_registration_path' for #<Class>

in my routes i am using

devise_for :users

and on the user model
devise :registerable, :authenticatable, :confirmable, :recoverable,
         :rememberable, :trackable, :validatable

it seems that the helper method for registrations are not being added somehow

**Comment by devanoivn** [comment]
Furniture Bali = pilarbalifurnitures.com
