### ISSUE TITLE
confirmation_url strips subdomains from request host (1.5.2)

### ISSUE THREAD

**Issue by mehayden** [plataformatec/devise#1567]
I am running 2 instances of the same app one on mydomain.com and one on dev.mydomain,com. A confirmation email is sent from the app on the dev server will try to confirm on the other server since the subdomain is stripped. Is this the desired behavior  which would disallow running multiple apps from the same domain?

A possible workaround would be to specify the host in the template:

confirmation_url(@resource, :host=>request.host,  :confirmation_token => @resource.confirmation_token)

**Comment by folubode** [comment]
sorry am not sure there is a recent link but I have same problem and none of these options has helped. my confirmation_url is not having www so there is error in the welcome page when user click on link to activate account. Any help please?
