### ISSUE TITLE
[Registration] No Automatic Sign In after Sign Up

### ISSUE THREAD

**Issue by fabioquixada** [plataformatec/devise#1619]
I've seen a solution where the RegistrationsController was overridden (specifically, the create action) and a single line (https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L19) should be changed. There were other similar solutions on the net, but I didn't find any clear/working one.

Help?

**Comment by Sanra9** [comment]
I have got same issue, i wouldn't like that user isn't sign in when he makes sign up, i'm using confirm token with gmail, so i would like that user has to go into his email and to make click in confirm link and then that user can make sign in.
