### ISSUE TITLE
Skip validation for some members in Devise model during password reset

### ISSUE THREAD

**Issue by rahul** [plataformatec/devise#1623]
My User (Devise) model also has name, city, nation, phone members.

In the create registration page - I `validates_presence_of :city, :nation, :phone, :name, :email, :on => :create`
In the edit registration page - I `validates_presence_of :city, :nation, :phone, :name, :on => :update`

Now when I set a new password on forgot_password_page, it asks for the presence of city, nation, phone, name inside `Devise::PasswordsController#update`

How can I handle selective validations?

I am guessing it should be something like,

```
validates_presence_of :city, :nation, :phone, :name, :on => :update, :if => :not_recovering_password

def not_recovering_password
  # what goes here
end
```

Posted in [Stackoverflow](http://stackoverflow.com/questions/9153251/skip-validation-for-some-members-in-devise-model-during-password-reset)

**Comment by adesurirey** [comment]
I had the same issue today, passed around it by adding `if: "!encrypted_password_changed?"` on validations I don't want running when changing password. Hope it will help.

**Comment by lucasmncastro** [comment]
My model also have a lot of validations and older users could't reset their password.

I think password reset should not validate nothing beyound password and password_confirmation.

Here is my workaround:
I overrided `reset_password` in my User class in order to consider only password and password_confirmation validations.

```ruby
def reset_password(new_password, new_password_confirmation)
  if new_password.present?
    self.password = new_password
    self.password_confirmation = new_password_confirmation
    return true if save

    password_valid = (errors.messages.keys & [:password, :password_confirmation]).blank?
    if password_valid
      errors.clear
      save(validate: false)
    end
  else
    errors.add(:password, :blank)
    false
  end
end
```
