### ISSUE TITLE
Manually confirm existing account

### ISSUE THREAD

**Issue by bcackerman** [plataformatec/devise#1626]
I'm still running my app locally and I have my test account I created before.  I just added the :confirmable feature to my database and now I can't login using my test account.  Is there a way to manually confirm that account?

The fields for that entry say: confirmation_token: nil, confirmed_at: nil, confirmation_sent_at: nil, unconfirmed_email: nil

**Comment by feliperaul** [comment]
In my tests `.confirm!` returns `undefined method `confirm!'`, but `.confirm` does the trick.

**Comment by wiskirz** [comment]
Try the [Letter Opener](https://github.com/ryanb/letter_opener) gem for testing mailers locally.
