### ISSUE TITLE
Writing specs for routes defined with authenticated

### ISSUE THREAD

**Issue by rafael** [plataformatec/devise#1670]
Greetings, 

I'm trying to use the method "authenticated" when defining a route only for authenticated users and is working. I'm having something like this in my routes:

authenticated :users do
   resources :client-leads, :controller => 'authenticated/coach_match_leads'
 end

However, I'm trying to write test for these routes and is not working. The test is the following:

  {:get => "/client-leads"}.should route_to("authenticated/coach_match_leads#index")

But I'm getting I'm exception:

NoMethodError Exception: undefined method `authenticate?' for nil:NilClass

Do you have any ideas why is this happening? Is important to notice that this is happening only for the routes defined with authenticated. All the other specs for the routes are working properly (even the ones for other devise routes).

Thanks in advanced for your help.

**Comment by seanknox** [comment]
@waterlink stubbing methods on `NilClass` is a bad idea—you can easily break something later and your tests might be green where an object or logic was missing/bad.

**Comment by waterlink** [comment]
@seanknox Yes, you are right. That was a very bad workaround. Stubbing methods on `NilClass` can be compared to switching to dark side of force. Powerful but comes with a huge price.

I highly don't recommend using my workaround from 1 year ago.

**Comment by ClayShentrup** [comment]
This worked for me, @seanknox.

```ruby
  let(:warden) do
    instance_double('Warden::Proxy').tap do |warden|
      allow(warden).to receive(:authenticate!).with(scope: :user)
        .and_return(authenticated?)
      allow(warden).to receive(:user).with(:user).and_return(user)
    end
  end
  let(:user) { instance_double(User) }
  let(:authenticated?) { true }

  def simulate_running_with_devise
    stub_const(
      'Rack::MockRequest::DEFAULT_ENV',
      Rack::MockRequest::DEFAULT_ENV.merge('warden' => warden),
    )
  end
```

**Comment by nerakdon** [comment]
I had to change ":authenticate!" in @ClayShentrup 's answer to ":authenticate?" to get it working, like this:

    let(:warden) do
        instance_double('Warden::Proxy').tap do |warden|
            allow(warden).to receive(:authenticate?).with(scope: :user)
                .and_return(authenticated?)
            allow(warden).to receive(:user).with(:user).and_return(user)
        end
    end
    let(:user) { instance_double(User) }
    let(:authenticated?) { true }

    def simulate_running_with_devise
        stub_const(
            'Rack::MockRequest::DEFAULT_ENV',
            Rack::MockRequest::DEFAULT_ENV.merge('warden' => warden),
        )
    end

**Comment by kucaahbe** [comment]
this kinda helped me:
```ruby
module DeviseRoutingHelpers
  # workaround for this issue https://github.com/plataformatec/devise/issues/1670
  def mock_warden_for_route_tests!
    warden = double
    allow_any_instance_of(ActionDispatch::Request).to receive(:env).
      and_wrap_original { |orig, *args|
      env = orig.call(*args)
      env['warden'] = warden
      env
    }
    allow(warden).to receive(:authenticate!).and_return(true)
  end
end

RSpec.configure do |config|
  config.include DeviseRoutingHelpers, type: :routing

  config.before(:each, type: :routing) do
    mock_warden_for_route_tests!
  end
end
```
