### ISSUE TITLE
edit_user_password route causes 'You are already signed in' message

### ISSUE THREAD

**Issue by benhamill** [plataformatec/devise#1712]
I have a Rails app that started as a 3.1 rc with Devise 2.0.0. I've upgraded recently to Rails 3.2.2 and Devise 2.0.4. I have noticed that a logged in user can't go to the `edit_user_password` page and is shown the flash message "You are already signed in". I can't figure out what I might be doing that would cause Devise not to realize that, yes, that's cool and you _should_ be signed in to change your own password.

Am I missing something key?

**Comment by ericboehs** [comment]
It would be nice to avoid for admins that want to send users a reset email without logging out, select reset password and pasting the users email.

**Comment by carlosantoniodasilva** [comment]
@ericboehs that's a different and very specific feature, which is not devise's purpose, but can be easily implemented with the methods it gives us :).

**Comment by ericboehs** [comment]
@carlosantoniodasilva Yeah but instead of being a simple link_to, now I have to override the passwords controller and change the routes just to skip a before filter which doesn't seem to be necessary.
