### ISSUE TITLE
Flash Messages Persist

### ISSUE THREAD

**Issue by mrrooijen** [plataformatec/devise#1743]
Hi.

I came back to an app after a long time to perform some minor updates and I noticed that for some reason flash messages are persisting between requests and are never cleared.

For example, on the sign in screen when typing in a wrong user/password it says "Incorrect user/password". Then when i log in with the correct credentials, I get two flash messages (notice and alert) "successfully logged in" and again the "incorrect user/password". Even if I hit refresh 10 times both flash messages just stay there, even if I navigate to other pages they are still there. Then when I log out and go back to the login screen there are now 3 messages: "you are now logged out", "you have successfully logged in" and "incorrect user/password".

Not sure when this happened. I don't recall seeing these messages back when I initially developed the app. I'm currently running Rails 3.0.7 and Devise 1.1.5.

I have overwritten the sessions controller with:

``` ruby

# encoding: utf-8

class Devise::SessionsController < ApplicationController
  layout 'sign_in'

  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  include Devise::Controllers::InternalHelpers

  # GET /resource/sign_in
  def new
    clean_up_passwords(build_resource)
    render_with_scope :new
  end

  # POST /resource/sign_in
  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => "new")
    set_flash_message :notice, :signed_in
    sign_in_and_redirect(resource_name, resource)
  end

  # GET /resource/sign_out
  def destroy
    set_flash_message :notice, :signed_out if signed_in?(resource_name)
    sign_out_and_redirect(resource_name)
  end
end
```

Not entirely sure why, it's been I think 1 to 1.5 years since I developed the app, haven't touched it since. I'm using two resources: Admin and Participant of which their sessions are handled by this controller.

Anyone know if this is Devise or Rails related? I just don't understand why the flash messages persist after more than 1 request since being set.

Thanks!

**Comment by briancicutti** [comment]
I am having this same issue and am inheriting from Devise::SessionsController  and Devise::RegistrationsController

Is there a known best practice to debug if another gem is causing this issue?
