### ISSUE TITLE
undefined method `registration_path' 

### ISSUE THREAD

**Issue by cpatil** [plataformatec/devise#1773]
Using devise 2.0.4 with Rails 3.2.2 and hitting /users/sign_up (development mode) , I get

undefined method `registration_path' for #&lt;#&lt;Class:0x007f936ab09c08&gt;:0x007f936b049088&gt;

Extracted source (around line #3):

1: &lt;h2&gt;Sign up&lt;/h2&gt;
2: 
3: &lt;%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %&gt;
4:   &lt;%= devise_error_messages! %&gt;
5: 
6:   &lt;div&gt;&lt;%= f.label :email %&gt;&lt;br /&gt;

more info at - https://gist.github.com/2295672

**Comment by tamiki-** [comment]
thank you!!!

**Comment by vamsipavanmahesh** [comment]
Yes server re start worked me, but anyone would like to help me out with .. what caused the issue in the first place?

**Comment by alliesground** [comment]
I had run `rails generate devise:views -v registrations` to customise the view, later my decision changed and I removed the views/devise/registration folder and started to get the above mentioned error.

seems like Running `rails destroy devise:views -v registrations`  solved the issue for me.

**Comment by nezirz** [comment]
Now I have problem within:  ```

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end
```

Trying to log in as facebook user and all the time I am redirected to  devise sign up page.
Everything was okay last few months omniauth worked fine, today I just delete my user from db and tried to login/register again.  
Here are my code:
https://stackoverflow.com/questions/47905428/rails-devise-omniauth-new-user-registration-url

**Comment by nezirz** [comment]
I found the reason in user.rb model I had one association belongs_to:somemodel and that I was put there for testing some model relations.

So commenting this line I am logged in by facebook!

**Comment by KingsleyMcSimon** [comment]
I had the same issue as others had and restarting the rails server fixed the problem for me.
