### ISSUE TITLE
Timeoutable timeouts causing Rails to flash[:timedout] as "true"

### ISSUE THREAD

**Issue by nbibler** [plataformatec/devise#1777]
I know this has been mentioned [in](https://github.com/plataformatec/devise/issues/193) [other](https://github.com/plataformatec/devise/issues/219) tickets, but it appears to still be an issue, as of 2.0.4.  From the current, master's [failure_app.rb](https://github.com/plataformatec/devise/blob/3cbced4e4e644d18c8a5a7043d8fefde9829087a/lib/devise/failure_app.rb#L80):

``` ruby
def redirect_url
  if warden_message == :timeout
    flash[:timedout] = true
    attempted_path || scope_path
  else
    scope_path
  end
end
```

The third line there is causing the Rails `Flash::FlashHash` object instance to carry a flash[:timedout] whose value is of TrueClass.  For generalized flash implementations, such as the [one generated](https://github.com/plataformatec/devise/blob/3cbced4e4e644d18c8a5a7043d8fefde9829087a/test/rails_app/app/views/layouts/application.html.erb) and recommended by this gem:

``` erb
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>
```

The following HTML is being generated and displayed to visitors:

``` html
<div id="flash_timedout">true</div>
```

Obviously, this is non-ideal. :)  Is this `:timedout` flash message actually used for anything?  I see that the failure_app is [explicitly keeping](https://github.com/plataformatec/devise/blob/3cbced4e4e644d18c8a5a7043d8fefde9829087a/lib/devise/failure_app.rb#L57) the :timedout flash message, even though it's simply a `true` statement:

``` ruby
def redirect
  store_location!
  if flash[:timedout] && flash[:alert]
    flash.keep(:timedout)
    flash.keep(:alert)
  else
    flash[:alert] = i18n_message
  end
  redirect_to redirect_url
end
```

Based on a cursory reading of this code, it seems to me that a simple instance variable, which is set to true/false and nilified with each Rack `call` request, would provide the same functionality and work significantly better.

And, yes, I did see @josevalim's [comment on the use of Flash](https://github.com/plataformatec/devise/commit/275c480f89f814af7135093a507ab57397729faf#commitcomment-925730)... I just wonder if either the README and example application layout should be updated to reflect the check for String-iness or the surprising usage of Flash for non-user messages should be removed.

**Comment by deivid-rodriguez** [comment]
@josevalim Would you be willing to accept a PR that moves this to the session hash? It seems like a more appropriate place than using flash messages, right?

**Comment by josevalim** [comment]
@deivid-rodriguez no because it is a fine use of flash. :) Flash is not only about messages but temporary storage.

**Comment by deivid-rodriguez** [comment]
@josevalim Alright. I just happened to read the code handling this and it seemed like a code smell (https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L58-64). It's not clear what it does, it's not commented, it's not tested, there's quite a lot of issues linking here, and that use of `keep` doesn't intuitively suggest temporary storage...

**Comment by josevalim** [comment]
We don't have unit tests but we do have integration tests. The flash is an implementation detail to how the feature works. Also, notice we also keep the alert, that's more of a bug of how flash behaves in Rails because it doesn't survive redirects...

**Comment by deivid-rodriguez** [comment]
Really? I thought they survived a single action... regardless of it being a redirect or not.

**Comment by ginolon** [comment]
Excuse me, how to exclude ":timedout" flash messages from this code:

"flash.each do |msg_type, message|"

that I have in an helper?

**Comment by tonycchung** [comment]
@ginolon a bit late but perhaps something like this:

    unless msg_type == :timedout

**Comment by ginolon** [comment]
@tonycchung If I use the `except` way, I got this:

`undefined method 'except' for #<ActionDispatch::Flash::FlashHash:0x0000000d3df308>`

```ruby
def flash_messages(opts = {})
    flash.except(:timedout).each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible text-center fade in", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
```

**Comment by thiagotonon** [comment]
@ginolon Something like this inside your each block should do the trick

`next unless value.is_a? String`

**Comment by tanelsuurhans** [comment]
At least in Rails 4.2.4 ActionDispatch::Flash::FlashHash does not extend from Hash and does not have an #except method. So it's not really a viable option. 

While I agree this is a good use of the flash hash, I think its a little stubborn to keep that as a justification when clearly its causing heartburn for people. I mean the intended use of the flash has is clearly messaging, with default methods for :notice and :alert keys and so forth.
