### ISSUE TITLE
Authentication fail with multiple models and authentication keys

### ISSUE THREAD

**Issue by umerkulovb** [plataformatec/devise#1818]
I have 2 devise models in my app: User and Moderator

User uses 2 keys for database authentication - so I have in my initializers/devise.rb

``` ruby
config.authentication_keys = [:email, :account]
```

But Moderator uses only email for authentication.

When I'm trying to authenticate with moderator, it fails with 401, incorrect username or password. But if I remove second authentication key in my initializers, everything is ok.

Am I doing something wrong???

**Comment by rbngzlv** [comment]
If someone gets here from google, the option is now called `authentication_keys` instead of `authenticatable_keys`.

```ruby
class Teacher < ApplicationRecord
  devise :database_authenticatable, <other modules>, authentication_keys: [:identification]
end

class Student < Applicationrecord
  devise :database_authenticatable, <other modules>, authentication_keys: [:email]
end
```
