### ISSUE TITLE
Does not work properly with STI (single table inheritance)

### ISSUE THREAD

**Issue by bkirby** [plataformatec/devise#195]
I'm using rails 3 beta2, and I've tried both the master branch, and 1.1.rc0. When I use devise_for in my routes, the routes are never created. 'rake routes' never shows any session/devise related routes, just those that I've created.

It doesn't throw any errors or break anything, the routes just don't come through. I have to manually set them for them to work.

**Comment by zia-mking** [comment]
> Yep exactly. In order for the STI models to work, you have to re-declare the devise method in your child models.
> 
> Heres a better explanation:
> 
> http://pastie.org/915925

Link not working
