### ISSUE TITLE
Undefined method 'confirmation_url' when creating User from console

### ISSUE THREAD

**Issue by bouchard** [plataformatec/devise#200]
On Rails Edge, and Devise 'edge' (git repo). This issue seems to only occur when creating the model instance directly (from the console). Apparently Pierre over at [Railsplugins.org](http://www.railsplugins.org/plugins/13-devise) is having the same issue.

<code>

> > User.create!(:username => 'test', :email => 'test@test.com', :password => 'testtest', :password_confirmation => 'testtest')
> > ActionView::Template::Error: 
> > ActionView::Template::Error (undefined method `confirmation_url' for #<#Class:0x10352cb60:0x103526490>) on line #5 of /Users/Crash/test.com/app/views/devise/mailer/confirmation_instructions.html.erb:
> > 2: 
> > 3: <p>You can confirm your account through the link below:</p>
> > 4: 
> > 5: <p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token) %></p>

```
app/views/devise/mailer/confirmation_instructions.html.erb:5:in `_render_template_1419737382_2175365820_0'


from On line #5 of /users/crash/test.com/app/views/devise/mailer/confirmation_instructions.html.erb

2: 
3: <p>You can confirm your account through the link below:</p>
4: 
5: <p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token) %></p>

app/views/devise/mailer/confirmation_instructions.html.erb:5:in `_render_template_1419737382_2175365820_0'
```

</code>

**Comment by tilo** [comment]
@josevalim what is the suggested work-around for this? It still happens on 3.5.9 from the command line

**Comment by masylum** [comment]
It happens to me also on the `seeds.rb`...
