### ISSUE TITLE
Unexpected reconfirmable behaviors especially trying to re-send confirmation email

### ISSUE THREAD

**Issue by mcbsys** [plataformatec/devise#2060]
I'm testing the reconfirmable feature with Rails 3.2.8 with Devise 2.1.2, upgraded from 1.5.3. I've come across a few unexpected behaviors:
1. When the user changes his email, the confirmation email is sent to the `unconfirmed_email`, but the email body greets the user with the old `email`: `Welcome <%= @resource.email %>!`. I can fix that in views/devise/mailer/confirmation_instructions (see below).
2. If the user doesn't get the instructions, he may try the "Resend confirmation instructions" link with his new email address. He will get the message, "[new email] not found". The WHERE clause here should be something like `WHERE "users"."email" = [form_email] OR "users"."unconfirmed_email" = [form_email]`. Assuming that will work that way someday, I guess that means I should index `unconfirmed_email` in my migration.
3. On the Resend confirmation page, maybe the user will think to enter his old email address to get it to send confirmation instructions to his new email address. He will get the message, "[old email] was already confirmed. Please try signing in." Maybe `confirmed_at` should be set to nil when a (re-)confirmation is pending?
4. So the user finally tries signing in using his old email address. This works. In my app, he can now go to the Edit User screen, where he will see his old email address. "What? I thought I changed that!" But if he changes it again, he will get another confirmation email.
5. Some of this wouldn't be so confusing if the user was informed of the flow. Is there a built-in message I should be displaying? If not, I will to add some code to the Users controller so that when the user changes his email, the flash message tells him, "A confirmation email has been sent to [new email]. Until you confirm the new email, you can continue to log in as [old email]." And maybe I'll #show the user `unconfirmed_email` as "New email (pending confirmation)".

Here is my updated confirmation_instructions.html.erb:

```
<% if @resource.unconfirmed_email %>
  <p>Welcome <%= @resource.unconfirmed_email %>!</p>
  <p>Please confirm your new email address by clicking on the link below:</p>
<% else %>
  <p>Welcome <%= @resource.email %>!</p>
  <p>Please confirm your account by clicking on the link below:</p>
<% end %>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token) %></p>
```

**Comment by redbar0n** [comment]
This might be related: https://github.com/plataformatec/devise/issues/3457
