### ISSUE TITLE
Add captcha verify on login there may be has a bug!

### ISSUE THREAD

**Issue by huacnlee** [plataformatec/devise#2106]
I want add a captcha feature on my login page. So I follow [this page](https://github.com/plataformatec/devise/wiki/How-To:-Use-Recaptcha-with-Devise) to do.

``` ruby
# coding: utf-8
class SessionsController < Devise::SessionsController
  def new
    session[:return_url] = params[:return] if !params[:return].blank?
    super
  end

  def create
    if verify_recaptcha
      super
    else
      build_resource
      # clean_up_passwords(resource)
      flash[:error] = "Captcha has wrong, try a again."
      respond_with_navigational(resource) { render :new }
    end    
  end
end
```
## And then, I found an issue:

When I first submit with a bad captcha code, will got `Captcha has wrong, try a again.` message, but when I refresh that page again, the devise will auto login.
## Rails logger show:

``` bash
Started POST "/account/sign_in" for 127.0.0.1 at 2012-10-17 22:33:09 +0800
Creating scope :recent. Overwriting existing method User.recent.
Creating scope :exclude_ids. Overwriting existing method User.exclude_ids.
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"zqnzxilphdasnIGkHqRH1saD4a4w/Eee/ef3OaWRyT8=", "user"=>{"email"=>"monster@gmail.com", "password"=>"[FILTERED]", "captcha"=>"WWW", "remember_me"=>"0"}, "commit"=>"登录"}
MONGODB (2ms) movieso_dev['system.namespaces'].find({})
MONGODB (0ms) movieso_dev['users'].find({:_id=>2923}).limit(-1).sort([[:_id, :asc]])
Redirected to http://127.0.0.1:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 5ms (Search: 0.0ms)
```

Looks like `require_no_authentication` has did login and redirect the page. 

https://github.com/plataformatec/devise/blob/master/app/controllers/devise_controller.rb#L122

---

So, I add a `skip_before_filter` to disable that feature, and verify logic will be work fine!

```
class SessionsController < Devise::SessionsController
  skip_before_filter :require_no_authentication, :only => [ :new, :create]

  .....
end
```

**Comment by michelgrootjans** [comment]
I've encountered the exact same issue
``
skip_before_filter :require_no_authentication, :only => [ :new, :create]
prepend_before_filter :captcha_valid, :only => [ :create] 
``

I can't be the only one having this problem, right?

using ruby 1.9.3p547 and rails 3.2.21

**Comment by guapolo** [comment]
Using @chinacheng's idea and this [post](http://stackoverflow.com/questions/20423868/verify-captcha-validation-if-a-user-fails-to-login-twice-using-cookies-coding) on RoR 4, is as simple as:

```ruby
class Users::SessionsController < Devise::SessionsController
  prepend_before_action :captcha_valid, only: [:create]
  layout "login"
  
  private
    def captcha_valid
      if verify_recaptcha
        true
      else
        self.resource = resource_class.new(sign_in_params)
        respond_with_navigational(resource) { render :new }
      end 
    end
end
```

**Comment by penne12** [comment]
@guapolo Added this to the wiki
