### ISSUE TITLE
How to update JSON Unauthorized error

### ISSUE THREAD

**Issue by jmonteiro** [plataformatec/devise#2108]
Hey guys,

I'm building an API using Rails 3.2.8 and Devise 2.1.2, and, for that matter, I'd like to update the JSON unauthorized error. Currently, when I do an unauthorized request, I am getting this:

```
curl "http://0.0.0.0:3000/v1/robots?auth_token=wrongtoken"
{
  "error":"Invalid authentication token."
}
```

As well as:

```
curl -u "user:wrongpassword" "http://0.0.0.0:3000/v1/robots"
{
  "error":"Invalid email or password."
}
```

It isn't simply a matter of updating the strings (which I can do on the locales files). I want to return something like this:

```
{
  "status":"401",
  "message":"Invalid authentication token.",
  "more_info":"http://developers.example.com/401"
}
```

I'm trying to find where the "error" is defined, but I'm not having so much luck...

**Comment by Feuda** [comment]
Custom Devise 401 unauthorized response http://stackoverflow.com/a/35299936/642616
