### ISSUE TITLE
Setting allow_unconfirmed_access_for to nil

### ISSUE THREAD

**Issue by Ajedi32** [plataformatec/devise#2275]
As you're probably aware, Devise's `:confirmable` module has a setting called `allow_unconfirmed_access_for` that determines how long a user can access their account for before they are forced to confirm its email address. Currently, there's no way to remove this restriction entirely like there is for `confirm_within`. I can work around this by setting `allow_unconfirmed_access_for` to some ridiculous value like 1000.years, but that feels like a rather dirty solution. I'd prefer to just set it to nil and have that remove the restriction, but currently doing that yields the following error:

```
undefined method `ago' for nil:NilClass
devise (2.2.2) lib/devise/models/confirmable.rb:162:in `confirmation_period_valid?'
```

**Comment by Lucasosf** [comment]
Nice! =D

**Comment by r-a-o** [comment]
Please mention the use of `nil` for `allow_unconfirmed_access_for` in docs. 

I read docs, then googled, then found a StackOverflow answer mentioning the use of value nil.

**Comment by jarosan** [comment]
I'm with @r-a-o. I've just spend a lot more time that i want to admit to figure out my problem was solved by `config.allow_unconfirmed_access_for = nil`
