### ISSUE TITLE
Omniauth with Rails 4 action error

### ISSUE THREAD

**Issue by akashkamboj** [plataformatec/devise#2313]
I am converting a Rails 3.2.11 app to Rails 4 beta and using omniauth-facebook. 

There's a strange problem happening. After login with facebook the page says: The action 'facebook' could not be found for Devise::OmniauthCallbacksController. While the controller has the facebook action. 

Routes

``` ruby
  devise_for :users, :controllers => { :registrations => 'registrations',
                                       :omniauth_callbacks => 'services' }
```

ServicesController

``` ruby
class ServicesController < Devise::OmniauthCallbacksController

  def facebook
    render :text => 'hello'
  end

  def failure
    render :text => '<script>window.close();</script>'
  end

end
```

The failure action working fine, but somehow the facebook action isn't called
It's working fine in Rails 3.2.11 but not in Rails 4 beta. Anyone faced this issue or have any solution for it?

**Comment by ndvbd** [comment]
@agnellvj So how can this be solved?
