### ISSUE TITLE
ActionController::Live and authenticate_user! fails to catch :warden

### ISSUE THREAD

**Issue by jamilbk** [plataformatec/devise#2332]
Calling authenticate_user! in a controller that has included ActionController::Live causes `ArgumentError (uncaught throw :warden)`

Can be reproduced simply with:

``` ruby
class FooController < ApplicationController
  include ActionController::Live
  before_action :authenticate_user!
  def foo; render text: ""; end
end
```

And then GET'ing foo from the rails console. Example backtrace:

```
ArgumentError (uncaught throw :warden):
  warden (1.2.1) lib/warden/proxy.rb:128:in `throw'
  warden (1.2.1) lib/warden/proxy.rb:128:in `authenticate!'
  /Users/jamil/.rvm/gems/ruby-2.0.0-p0@tmp/bundler/gems/devise-d29b744d92a3/lib/devise/controllers/helpers.rb:48:in `authenticate_user!'
  activesupport (4.0.0.beta1) lib/active_support/callbacks.rb:407:in `_run__624670321848815552__process_action__callbacks'
  activesupport (4.0.0.beta1) lib/active_support/callbacks.rb:78:in `run_callbacks'
  actionpack (4.0.0.beta1) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.0.beta1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.0.beta1) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.0.beta1) lib/active_support/notifications.rb:158:in `block in instrument'
  activesupport (4.0.0.beta1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.0.beta1) lib/active_support/notifications.rb:158:in `instrument'
  actionpack (4.0.0.beta1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.0.beta1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.0.beta1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.0.beta1) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.0.beta1) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.0.beta1) lib/action_controller/metal/live.rb:118:in `block in process'


  Rendered /Users/jamil/.rvm/gems/ruby-2.0.0-p0@tmp/gems/actionpack-4.0.0.beta1/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.5ms)
  Rendered /Users/jamil/.rvm/gems/ruby-2.0.0-p0@tmp/gems/actionpack-4.0.0.beta1/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.9ms)
  Rendered /Users/jamil/.rvm/gems/ruby-2.0.0-p0@tmp/gems/actionpack-4.0.0.beta1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
  Rendered /Users/jamil/.rvm/gems/ruby-2.0.0-p0@tmp/gems/actionpack-4.0.0.beta1/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (15.7ms)
 => 500 
```

Using:

Rails 4.0.0.beta1
Devise rails4 branch
Warden 1.2.1

I've created a simple example app to highlight the issue: https://github.com/jamillion/devise_bug_demo

I'm guessing ActionController::Live is doing something weird with the Rack middleware that causes a `catch :warden` call to be bypassed in Devise / Warden?

**Comment by mattclar** [comment]
still having this issue

**Comment by kirantpatil** [comment]
I am having this issue when I try to logout.

Started DELETE "/users/sign_out" for 127.0.0.1 at 2015-07-10 19:55:45 +0530
Processing by Users::SessionsController#destroy as HTML
  Parameters: {"authenticity_token"=>"uUfMPrkHrYmjg71rBl+G6OHduEbxYytme6Xi3UCY3MyHf23WrzDcBEChbPt/cqfgVu+6/SjajZ+HUE0lpAiXKw=="}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
Redirected to http://localhost:3000/
Completed 302 Found in 5ms (ActiveRecord: 0.3ms)

Started GET "/" for 127.0.0.1 at 2015-07-10 19:47:44 +0530
Processing by ParkController#index as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

UncaughtThrowError (uncaught throw :warden):
  warden (1.2.3) lib/warden/proxy.rb:128:in `throw'
  warden (1.2.3) lib/warden/proxy.rb:128:in `authenticate!'
  devise (3.4.1) lib/devise/controllers/helpers.rb:112:in `authenticate_user!'
  activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'

[kpatil@dhcppc21 svg_nload]$ bundle | grep devise
Using devise 3.4.1
[kpatil@dhcppc21 svg_nload]$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
[kpatil@dhcppc21 svg_nload]$ rails -v
Rails 4.2.1
