### ISSUE TITLE
Send multipart emails

### ISSUE THREAD

**Issue by tmaier** [plataformatec/devise#2341]
Since #1326 devise has markerb support, which is great.

Unfortunately, it just sends the HTML email, as the call to `mail` at https://github.com/plataformatec/devise/blob/master/lib/devise/mailers/helpers.rb#L16 does not have a block, like 

``` ruby
    mail(:to => @recipient, :from => "john.doe@example.com") do |format|
      format.text
      format.html
    end
```

https://github.com/plataformatec/markerb

**Comment by arturoherrero** [comment]
How about [create a custom mailer for devise][1] like this:

```
class MyMailer < Devise::Mailer
  default parts_order: [ "text/plain", "text/html" ]
end
```

[1]: https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer
