### ISSUE TITLE
update_with_password does NOT apply password presence/length validation

### ISSUE THREAD

**Issue by mlilley** [plataformatec/devise#2349]
Devise validates password presence and minimum password length (8 chars) when creating a new user registration.

However, it does not apply these validations when using update_with_password() and the password is an empty string.

Ex: Devise will permit the following update:

```
user.update_with_password({
  current_password:      'some_old_password',
  password:              '',
  password_confirmation: ''
});
>> ok
```

but wont permit:

```
user.update_with_password({
  current_password:      'some_old_password',
  password:              'abc',
  password_confirmation: 'abc'
});
>> validation error "password is too short (minimum 8 characters)"
```

(user model has :validatable applied)

**Comment by antonshevchenko** [comment]
@HatemMahmoud's solution worked for me. Thanks!

**Comment by Emerson2017** [comment]
você incluiu isso em que local ?

**Comment by paulodeon** [comment]
@HatemMahmoud is following instructions from https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-edit-their-password
