### ISSUE TITLE
devise.skip_trackable ignored ?

### ISSUE THREAD

**Issue by ouranos** [plataformatec/devise#2374]
I have an app which uses `database_authenticatable` and `token_authenticable`. 
`token_authenticable` is only used for API requests (which are all on a specific controller)

As mentionned in #1959 and in the doc, I'm trying to use `devise.skip_trackable` to not update the user at every API requests.
It doesn't seem to be working... After some debugging it appears that this check https://github.com/plataformatec/devise/blob/master/lib/devise/hooks/trackable.rb#L6 is called before the `before_filter`.

I've build a demo app to reproduce the problem here (with a failing test):
https://github.com/ouranos/test-devise-skip-trackable

Did I get something wrong ?

**Comment by iseessel** [comment]
@ourano Thanks for the help! lol
