### ISSUE TITLE
changing oauth passthru route does nothing

### ISSUE THREAD

**Issue by rweng** [plataformatec/devise#2386]
I am trying to setup a redirect_back when signing in w/ omniauth. Therefore, I tried to overwrite `Devise::OmniauthCallbacksController#passthru` with

``` ruby
def passthru
  binding.pry
  super
end
```

This does not get triggered, through my routes seem to be correct:

```
user_omniauth_authorize GET|POST /users/auth/:provider(.:format)          oauth_callbacks#passthru
```

I tried renaming the method to `passthru2` and adding the following lines to `routes.rb`

``` ruby
devise_scope :user do
    get '/users/auth/:provider' => 'oauth_callbacks#passthru2'
end
```

Which still results in

```
user_omniauth_authorize GET|POST /users/auth/:provider(.:format)          oauth_callbacks#passthru
```

Appending `as: user_omniauth_authorize` has no effect either.

Now I am confused because according to the wiki and SO, this is how it should work. Am I missing s.th. ( again ;) )?

**Comment by MCodyB** [comment]
So just FYI I'm using devise 4.3 and I have this "omniauth_callbacks#passthru" in my routes so I'm guessing it's still here.

**Comment by sanemat** [comment]
devise 4.6.2 shows `user_blahblah_omniauth_authorize	GET|POST	/users/auth/blahblah(.:format)	users/omniauth_callbacks#passthru`

**Comment by dmz006** [comment]
user_XXX_omniauth_authorize GET|POST   /users/auth/XXX(.:format)                                                           users/omniauth_callbacks#passthru

passthru still there in 4.7.1
