### ISSUE TITLE
Use password reset mechanisms with JSON-only communication

### ISSUE THREAD

**Issue by sebastianwr** [plataformatec/devise#2405]
We are developing a backend with pure JSON communication in Rails and use Devise for user authentication. Unfortunately, the password reset functions don't seem to support JSON at all. I've tried to implement the following in a custom controller.

```
    def create
      @user = User.send_reset_password_instructions(params[:user])
      if successfully_sent?(@user)
        head :status => 200
      else
        render :status => 422, :json => { :errors => @user.errors.full_messages }
      end
    end
```

Route used for this:

```
scope '/api/v1' do
    devise_for :users, :skip => :sessions, :controllers => { :passwords => 'api/v1/users/passwords' }
end
```

The `successfully_sent` method was copy&pasted from the `DeviseController` but still, instead of printing just status 200, it renders `devise/mailer/reset_password_instructions.html.erb` which confuses the JSON client.

Is there any way to make the password workflow support JSON?

**Comment by oamado** [comment]
https://github.com/plataformatec/devise/wiki/API-Mode-Compatibility-Guide
