### ISSUE TITLE
Error Not found. Authentication passthru. follow step-step Tutorial

### ISSUE THREAD

**Issue by overallduka** [plataformatec/devise#2492]
Hi,

Im follow step by step of this tutorial to use the Devise whit Omniauth and Facebook: `https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview`

So, im have a problem search and search but nobody have response, i dont know if this is the place to post this, im post because have hours i search and no have response to my problem.

I configure all how say this tutorial, the routes im try this:

`
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
`

and whitout the get how say the tutorial, but when i click in 

`user_omniauth_authorize_path(:facebook)`

redirect to `http://0.0.0.0:3000/usuarios/auth/facebook`

whit this phrase:

`Not found. Authentication passthru.`

im run `rake routes` appear this

`user_omniauth_authorize_pt_br GET|POST /usuarios/auth/:provider(.:format)                      users/omniauth_callbacks#passthru {:provider=>/facebook/, :locale=>"pt-BR"}
         user_omniauth_authorize_en GET|POST /en/users/auth/:provider(.:format)                      users/omniauth_callbacks#passthru {:provider=>/facebook/, :locale=>"en"}`

Please someone can help me please, i dont know what i make, i use Ruby 2.0 and Rails 3.2.

Also update my Gems but nothing happen.

**Comment by hallmatt** [comment]
does omniauth work for ruby 2 and rails 4.x? seems like this passthru error is a popular one
