### ISSUE TITLE
Cant login: ActiveModel::ForbiddenAttributesError in Devise::SessionsController#create

### ISSUE THREAD

**Issue by mjacobus** [plataformatec/devise#2493]
I just cant login. When I try to login (/users/sign_in), filling my email and password i get the error **ActiveModel::ForbiddenAttributesError in Devise::SessionsController#create**

The submited params are:

``` ruby
{"utf8"=>"✓",
 "authenticity_token"=>"FStzEFoCuWZA4SJuURxHr5ZmPnc5JlyZPiJDzTsoWRY=",
 "user"=>{
   "email"=>"admin@example.com",
   "password"=>"[FILTERED]",
   "remember_me"=>"0"
},
"commit"=>"Sign in"}
```

Either I am doing something very stupid (most likely) or rails 4 database authentication is not well resolved yet, due to the strong parametes.

This is a pretty standart authentication. I had no user model and ran `rails generate devise User`. 
# rails version == 4.0.0

app/routes.rb

``` ruby
devise_for :users
```

app/models/user.rb

``` ruby

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable,
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end
```

The migration

``` ruby
class DeviseCreateUsers < ActiveRecord::Migration
  def self.up
    create_table(:users) do |t|
      t.database_authenticatable :null => false
      t.recoverable
      t.rememberable
      t.trackable

      # t.encryptable
      # t.confirmable
      # t.lockable :lock_strategy => :failed_attempts, :unlock_strategy => :both
      # t.token_authenticatable


      t.timestamps
    end

    add_index :users, :email,                :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    # add_index :users, :unlock_token,         :unique => true
    # add_index :users, :authentication_token, :unique => true
  end

  def self.down
    drop_table :users
  end
end
```

**Comment by JonKernPA** [comment]
This might help, @mjacobus ...

I got a similar error:

    ActiveModel::ForbiddenAttributesError - ActiveModel::ForbiddenAttributesError:

And the offending line of code:

`resource.update_attributes(params[resource_name].except(:confirmation_token))`

I solved it by changing the code to use "strong parameters" as follows:

    ...
    resource.update_attributes(resource_params)
    ...

    private

    def resource_params
      params[resource_name].except(:confirmation_token).permit(:password, :password_confirmation)
    end
