### ISSUE TITLE
Reconfirmation is broken if you use an email_confirmation field

### ISSUE THREAD

**Issue by brycesenz** [plataformatec/devise#2499]
This is somewhere between a bug and just a heads up for future developers - 

In my User model, in addition to the `email` attribute, I have an `email_confirmation` field as well.  Very simple validation - it doesn't save a User record with the email attribute unless it has a confirmation as well.

Anyway, where this presents a problem is when you're trying to make a model reconfirmable.  The logic in the `confirm!` action will actually fail in this case (lack of an `email_confirmation` field).  My solution was to take this bit of code from that action:

```
if self.class.reconfirmable && unconfirmed_email.present?
  skip_reconfirmation!
  self.email = unconfirmed_email
  self.unconfirmed_email = nil

  # We need to validate in such cases to enforce e-mail uniqueness
  save(:validate => true)
else
  save(:validate => false)
end 
```

And change it to this:

```
if self.class.reconfirmable && unconfirmed_email.present?
  skip_reconfirmation!
  self.email = unconfirmed_email
  self.email_confirmation = unconfirmed_email
  self.unconfirmed_email = nil

  # We need to validate in such cases to enforce e-mail uniqueness
  save(:validate => true)
else
  save(:validate => false)
end 
```

Do you guys think that this issue is potentially common enough that it warrants checking if an `email_confirmation` field exists, and then setting it?

**Comment by jmschp** [comment]
Hey

What about if we want to enforce confirmation?

As stated in [Rails validation guides](https://guides.rubyonrails.org/active_record_validations.html#confirmation)

> This check is performed only if email_confirmation is not nil. To require confirmation, make sure to add a presence check for the confirmation attribute

```ruby
class Person < ApplicationRecord
  validates :email, confirmation: true
  validates :email_confirmation, presence: true
end
```

It will not be possible to use ` config.reconfirmable = true`
