### ISSUE TITLE
Sign Out and In on Rails 4

### ISSUE THREAD

**Issue by Darwinium** [plataformatec/devise#2518]
Hi,

I have a problem with devise (3.0.0) and rails 4.

application.html.erb

``` erb
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
```

routes.rb

``` ruby
get 'omniauth_callbacks/facebook'
devise_for :users, 
      :controllers => { 
        :omniauth_callbacks => 'users/omniauth_callbacks'},
      :path_names => {
        :sign_in => '/login', 
        :sign_out => '/sign_out'}
```

But if I click to signout link my app show me this error:
**Couldn't find User with id=sign_out**
Screenshot
![2013-07-20 19 56 52](https://f.cloud.github.com/assets/52569/830478/190d7c78-f155-11e2-991c-11eb0cc175e1.png)

I search this problem in google, but not found. Can you help me?

P.S. Sorry for my bad english. I can only fix my problem.

Thank you!

**Comment by Ruby4Life** [comment]
I had the same issue

I noticed that I had java script disabled on my browser!

I enabled JS on my browser

And all is well

**Comment by ravistm** [comment]
You gotto add it like this to make logout work in mobile devices also:
`devise_scope :user do
    get "login", :to => "users/sessions#new"
    get '/logout' => 'users/sessions#destroy'
  end`
