### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by brahmadpk** [plataformatec/devise#2554]
Hi,

I am using devise in my rails 4 app. In my gem file like so:

gem 'devise', github: 'plataformatec/devise'

When I run 

rails generate devise:install 

I get the below errors:

Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = '-- secret key --'

However I can't see any devise.rb file in the initializers folder.

How to solve this?

**Comment by sl-codenine** [comment]
Why is this still not working? I can be wrong, though in my case it works only in development (i assume it takes `secret_key_base`) but in production i'm getting error about secret key not being set.

Is there anything special to do to make it work on production too?

**Comment by kalkin** [comment]
So still no proper solution besides some hacks? I remember there were a task `generate_secrets` for `Capistraion 2` floating around. It did it job pretty well.  So why not provide something similliar by default? (And yes i know how i come up with my own sollution, but i hate to not have a proper way of doing it)

**Comment by makwanahemant** [comment]
generate key by

_bundle exec rake secret_

and then copy secret from console log to devise.rb, which would be something like

_config.secret_key = '4fce3c1c860216b8......' _
