### ISSUE TITLE
ActionController::InvalidAuthenticityToken Error on Heroku Deploy

### ISSUE THREAD

**Issue by jamilabreu** [plataformatec/devise#2586]
Locally everything works great, however I'm getting the following error when deploying a clean app to Heroku, then trying to register:

https://gist.github.com/jabreu52/6304494

**Comment by bahamallama** [comment]
same problem. still not fixed? I would assume people log in with devise from IOS devices? Nothing here fixed that for me. 

d

**Comment by canda** [comment]
@anazar do you remember how you were able to solve it?

**Comment by sfandrew** [comment]
http://stackoverflow.com/questions/20875591/actioncontrollerinvalidauthenticitytoken-in-registrationscontrollercreate

**Comment by shivabhusal** [comment]
Hey, I have my production and staging in heroku. `staging.rb` and `production.rb` in `config/environments` are exact copies. However, I could replicate the error in `production` but not in `staging`.

**Comment by bahamallama** [comment]
I'm assuming this is a Heroku issue. I'm using my own production server instead of Heroku and the problem went away. I can now log in from any device. 

d

**Comment by shklnrj** [comment]
I saw this error today in production on 10th April 2017.

After some debugging, I figured that force_ssl was not working for my app in production. I am using nginx and puma for the Rails application. The page was served via http only, not https.

As long as I had force_ssl in the production.rb file, I was getting the error.

I removed the force_ssl from the production.rb file and moved the redirection of http to https to nginx itself. Now I am not seeing the errors. Hope this helps.

**Comment by danielricecodes** [comment]
I run all my apps on Heroku and I've seen this happen A LOT.

I think this has to do with Heroku's containerization and has been exacerbated by Heroku's semi-recent introduction of daily restarts for all dynos.  A reboot on Heroku has the effect of invaliding all Devise sessions I believe.  I'm trying out `protect_from_forgery with: :reset_session` to see if it helps to alleviate the exception message.  If a session has been invalidated, it seems ok to send the user back to the login page.  IMHO - YOU SHOULD NOT NOT NOT NOT NOT remove `protect_from_forgery` from your app.  There is a reason the rails generator includes it!!!  

There is no way to get away from Heroku's behavior (other than rehost on your own platform of course).  Multiple dynos reduces the odds that a session will invalidate, but eventually all dynos will restart every 24 hours - whether you deploy or not.
