### ISSUE TITLE
Devise does not throw validation error during failed login

### ISSUE THREAD

**Issue by jpartogi** [plataformatec/devise#259]
Even though an devise_error_messages! is already inserted in the login views, devise still does not throw validation error during failed login. 

It would be great if this is built in from devise, rather than implemented by user.

**Comment by Rupinderwadali** [comment]
Hello Developer,
I am using devise for authentication. When the user entered the wrong information in sign in form, it just refreshes the page instead of flashing error message. Please tell me which files need to change.

**Comment by n5ken** [comment]
Same here, I got no message even I entered the wrong user name or password.

**Comment by Herz3h** [comment]
Same issue here, whats the solution to this ?
