### ISSUE TITLE
require_no_authentication is using prepend_before_filter so there is no chance to set locale in ApplicationController

### ISSUE THREAD

**Issue by donnykurnia** [plataformatec/devise#2591]
I had a project where the default locale is :es and handling locale switch using route_translator gem, so the url for en locale will be like:
`http://site/en/users/sign_in`

However, I notice that the devise message is still in :es, even when I request sign_in page using /en/. I look around the devise code and found that in SessionController, it is using prepend_before_filter
`prepend_before_filter :require_no_authentication, :only => [ :new, :create ]`

I debug my code and found that require_no_authentication will be executed before :set_locale that I put as before_action in ApplicationController.

Right now I'm still scratching my head to try overriding require_no_authentication method without changing devise code.

Any suggestion on how do I make require_no_authentication call set_locale first?

As far as I concern, this is a bugs, because even if in require_no_authentication using translation, it is showing a wrong message because it always using default_locales, not locale set via params/route.

**Comment by woto** [comment]
https://github.com/heartcombo/devise/issues/4084
