### ISSUE TITLE
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_users_on_email"

### ISSUE THREAD

**Issue by daraosn** [plataformatec/devise#2594]
We have an app using Devise. When sending two or more simultaneous requests trying to register an account using the same email _sometimes_ we get the following error from PostgreSQL:

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_users_on_email" DETAIL: Key (email)=(foo@bar.com) already exists.
```

We already have tests for avoiding duplicated emails on Rails side (and Devise already implements validates_uniqueness_of :email), but it seems like when two requests are sent simultaneously, the first requests writes a new record on database after the upcoming request verifies if the email already exists, so then the second check passes and tries to write again and raises the PG exception, as it's not caught by the Rails app.

I wonder if Devise is using [Transactions](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html) and if so is there a way to activate it?

Thanks in advance.

**Comment by SixArm** [comment]
Same issue on a brand new Rails 4.2 app, Ruby 2.2, using minitest, with all current gems.


    1) Error:
    HomeControllerTest#test_should_get_index:
    ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  
     duplicate key value violates unique constraint "index_users_on_email"
    DETAIL:  Key (email)=() already exists.
    : INSERT INTO "users" ("name", "created_at", "updated_at", "id") 
    VALUES ('MyString', '2015-01-14 23:48:24', '2015-01-14 23:48:24', 298486374)

    Error:
    HomeControllerTest#test_should_get_index:
    NoMethodError: undefined method `each' for nil:NilClass

     1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

**Comment by dwbutler** [comment]
I solved this problem in my application using an [advisory lock](https://github.com/mceachen/with_advisory_lock).

```ruby
User.with_advisory_lock(email) do
  # Registration logic moves into here
end
```

The first request will be granted the lock and proceed to create the account. The second request will wait for the lock, and only gets the lock after the first request is finished. The second request can then correctly find that the user account already exists.

The user might still see an error like "Account already exists". But at least the two requests won't interfere with each other and possibly cause bad side effects.

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am facing same issue on production and I am sure there is only one request is being sent.

Please note here that I have used `first_or_create!` method to create user only if not found for give params.

**Comment by bbnnt** [comment]
Hello; 
'was batch importing some users on a fresh database with the piece of code below. Got stuck the whole day with this pg::index error.

```
after_save :check_mail
def check_mail
   @user =  ( User.exists?(email: self.email) ? User.find_by_email(self.email) : User.create(email: self.email, password: pwd, password_confirmation: pwd) ) if self.email.presence
  end
```

I could only solve it (e.g. getting the expected rails behavior) by downcasing the emails that were passed in this method (the email causing problem was a duplicate of an existing one, but only uppercased)… which seemed a weird workaround. Is this normal that the email case has such impact ?

**Comment by SixArm** [comment]
@bbnnt Yes, it's normal that the email case matters for the search. The case matters for string comparisons in general, by default, and that's what you're seeing happen. (As far as I can tell, your issue is actually not related to the Devise issue that is on this page, i.e. the race condition, and advisory lock, and minitest collision. The issue that is on this page is describing something that happens even when the case is identical.)
