### ISSUE TITLE
'Confirmation token is invalid' when confirming after registering

### ISSUE THREAD

**Issue by delner** [plataformatec/devise#2615]
When registering `User` who utilizes `:confirmable`, when the user clicks on the e-mail confirmation link, they receive an "Invalid confirmation token" error message.

This issue is present using:
- **Devise 3.1.0** (`041fcf90807df5efded5fdcd53ced80544e7430f`)
- **Rails 4.0.0**
#### Code sample

_user.rb_

``` ruby
class User
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  # Attributes
  # ----------
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
  ...
  ## Confirmable
  field :confirmed_at,          type: DateTime
  field :confirmation_token,    type: String
  field :confirmation_sent_at,  type: DateTime
  field :unconfirmed_email,     type: String
```
#### Possible explanation

After registering, but before confirming, the `User.confirmation_token` is equal to `778fb` (truncated for readability.) This token exactly matches the confirmation email's link (i.e. `?confirmation_token=778fb`.)

However, after [reading this post](http://stackoverflow.com/questions/18390080/devise-confirmation-token-is-invalid) it appears that these tokens _shouldn't_ match, because Devise uses the email token to generate the matching `User.confirmation_token` with which to confirm them by.

Digging deeper into _[confirmable.rb](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb)_...

The code that generates the `User.confirmation_token`:

``` ruby
# Generates a new random token for confirmation, and stores
# the time this token is being generated
def generate_confirmation_token
  raw, enc = Devise.token_generator.generate(self.class, :confirmation_token)
  @raw_confirmation_token   = raw
  self.confirmation_token   = enc
  self.confirmation_sent_at = Time.now.utc
end
```

The code that confirms a user:

``` ruby
# Find a user by its confirmation token and try to confirm it.
# If no user is found, returns a new user with an error.
 # If the user is already confirmed, create an error for the user
# Options must have the confirmation_token
def confirm_by_token(confirmation_token)
  original_token     = confirmation_token
  confirmation_token = Devise.token_generator.digest(self, :confirmation_token, confirmation_token)

  confirmable = find_or_initialize_with_error_by(:confirmation_token, confirmation_token)
  confirmable.confirm! if confirmable.persisted?
  confirmable.confirmation_token = original_token
  confirmable
end
```

From this code, it appears that the token, say `778fb`, is persisted to `User.confirmation_token`, then sent out in the confirmation e-mail. When the user clicks the confirmation link, `778fb` is passed into `confirm_by_token`, which generates another token (i.e. `945ac`) which it searches the `User` table for finding nothing, thus invalid token.

It seems like in this case, `User.confirmation_token` should actually store `945ac` but still send out `778fb` in the confirmation link. I ran a simple test through my console, which seemed to confirm (no pun intended) this hypothesis:

``` ruby
new_token = Devise.token_generator.digest(User, :confirmation_token, '778fb')
u = User.first # The already registered, but unconfirmed user
u.confirmation_token = new_token
u.save
User.confirm_by_token('778fb') # Succeeds
```
#### Last thoughts...

Can someone explain why this is happening? It seems a little too obvious of a 'bug' to be true, but I haven't been able to work around it any other way.

See the following related links:
- [My StackOverflow question](http://stackoverflow.com/questions/18626544/devise-confirmation-token-is-invalid-when-user-signs-up)
- [Devise confirmation_token is invalid](http://stackoverflow.com/questions/18390080/devise-confirmation-token-is-invalid)
- [Devise 3.1: Now with more secure defaults](http://blog.plataformatec.com.br/2013/08/devise-3-1-now-with-more-secure-defaults/)
- [GitHub Issue - Devise confirmation_token invalid](https://github.com/plataformatec/devise/issues/2587)

**Comment by yaneeka** [comment]
Just a note that when I changed my after_create to just after_commit, I got into some kind of loop.  Needed to change to after_commit :method_name, on: :create

**Comment by luanau** [comment]
I think the send_reset_password_instructions below is done after the record is created in the database (without the hashed reset_password_token) . When the user subsequently clicked on the "Change my password" link in the email to change his password, there's nothing in the database to compare with token in the email so error "Reset password token is invalid" is returned.
    after_create { |admin| admin.send_reset_password_instructions }

I am a newbie with rails and ruby so don't really know how to fix it. Hope someone else can.

**Comment by anthonylebrun** [comment]
@andrewpthorp I had the same issue, thanks for the fix :+1:

**Comment by legkvla** [comment]
@andrewpthorp, thank you vm!

**Comment by zedtux** [comment]
Thank you @andrewpthorp, I have exactly the same issue and you saved me hours of investigation !

**Comment by ryana** [comment]
The original breakdown of this issue was awesome. Thank you very much for that @delner (Ha! And I just realized I commented on your SO thread too).

I have a question that is related, but I feel like should be answered here for posterity:

How do I create `@token` on my own? I'm trying to do a `visit user_confirmation_path(confirmation_token: token)` from a Capybara test, but I'm currently using `@user.confirmation_token` which as @delner pointed out was wrong.

Is my only option really to find the link in the email body that gets pushed into the `ActionMailer::Base.deliveries` array?

**Comment by ryana** [comment]
Ah ok I figured it out. It's ugly as sin, but:

```
u = User.where(email: email).first
u.send :generate_confirmation_token
email_token = u.instance_variable_get(:@raw_confirmation_token)
u.save!
visit user_confirmation_path(confirmation_token: email_token)
```

**Comment by josevalim** [comment]
If you are using `visit`, it is an integration test. If you don't check the e-mail, there is no guarantee you are actually sending the code via e-mail nor that the code is correct. The only way to be sure is by parsing it out of the e-mail which can honestly be done with a simple regex match on the body.

**Comment by nicnilov** [comment]
FWIW I'm using the confirmation token in a scenario where I give it out to a third-party email platform where it gets inserted into a confirmation email template. For that reason I have to extract it  while in `RegistrationsController#create` using the hacky approach of `instance_variable_get(:@raw_confirmation_token)`. Would be nice to have a proper accessor for that purpose.

**Comment by kimonoso** [comment]
I've gone through a plethora of answers that mentions the @token to have the confirmations module work. It still doesn't. Even with a new application, @token doesn't work.
