### ISSUE TITLE
Devise 3.1.1 won't authenticate 

### ISSUE THREAD

**Issue by Adam0964** [plataformatec/devise#2670]
We're using the last version and we've been having an issue with it: 

  A user can register but can't sign in. We don't get any errors, of any kind, in the   logs or anywhere else.

Any clue, anyone?

Regards,
--Adam.

**Comment by allicn03** [comment]
Hi,  I'm having this same problem and have tried everything I can think of, with no success.  This is my log:

Started GET "/users/sign_in?utf8=%E2%9C%93&authenticity_token=0M3bFGtRmnCpMXsBMVUapuK4ydXouI2JfTSvlWlXX5funOrnQFlXvguDOBiezXhkX7iQ2ROAh8uUYWj8nNI24A%3D%3D&user%5Bemail%5D=mackey%40example.com&user%5Bpassword%5D=[FILTERED]&user%5Bremember_me%5D=0&commit=Log+in" for 127.0.0.1 at 2018-10-23 15:25:30 -0400
Processing by Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"0M3bFGtRmnCpMXsBMVUapuK4ydXouI2JfTSvlWlXX5funOrnQFlXvguDOBiezXhkX7iQ2ROAh8uUYWj8nNI24A==", "user"=>{"email"=>"mackey@example.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
  Rendering devise/sessions/new.html.erb within layouts/application
  Rendered devise/shared/_links.html.erb (2.6ms)
  Rendered devise/sessions/new.html.erb within layouts/application (125.5ms)
  Rendered layouts/_alerts.html.erb (0.6ms)
Completed 200 OK in 1333ms (Views: 1175.2ms | ActiveRecord: 0.0ms)

I'm fairly new to Ruby, and I see above that perhaps it should be making a post request at this point, but I'm not sure how to correct that.  Thanks for your assistance!
