### ISSUE TITLE
User can't change the password : reset password token is invalid

### ISSUE THREAD

**Issue by apellizzn** [plataformatec/devise#2699]
I' am trying use the password reset function of devise, i set up an account on mandrill for sending emails.
So when i go on /users/password/new and click on send instructions i receive an email with a link "Change my password" , here is the link ref :
http://mandrillapp.com/track/click.php?u=30099686&id=bc6ced2b3ac34c9f93f7cd95b1ea1106&url=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fpassword%2Fedit%3Freset_password_token%3Dd8c12b50e66069b5d8b22e9b054af3441ced62e6ab3648392960823373db1524&url_id=c142395039d4f32dd19fa3b6a6f18291971049fc

when i click on it, it  sends me to /users/password/edit?reset_password_token=XXX.
But if i change the password the following flash message appears in the page: Reset password token invalid.
I am not overriding any devise controllers.
Anyone can help me?
![change](https://f.cloud.github.com/assets/4499167/1393288/d2809f2a-3c17-11e3-8211-c7ee0709c709.png)
![error](https://f.cloud.github.com/assets/4499167/1393289/da4bc70c-3c17-11e3-8dfe-264b4bebe189.png)

**Comment by luanau** [comment]
I have the same problem as <a href="https://github.com/cderche" class="user-mention">@cderche</a> using the following:

Rails 4.2.0
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
activeadmin-1.0.0.pre1

Thanks ahead for any pointers!

**Comment by mistrikushal** [comment]
I am using,
Rails 3.2.13
Devise 3.1.0

also changed @resource.*_token to @token but still it says '... token is invalid'

**Comment by andertecinc** [comment]
I was able to resolve this through overriding authentication method of devise. below is my override function.

`class User
  ...
  def self.find_first_by_auth_conditions warden_conditions
    conditions = warden_conditions.dup
    if (email = conditions.delete(:email)).present?
      where(email: email.downcase).first
    elsif conditions.has_key?(:reset_password_token)
      where(reset_password_token: conditions[:reset_password_token]).first
    end
  end

end
`

It worked then after.

**Comment by mistrikushal** [comment]
I was able to resolve this through overriding authentication method of devise. below is my override function.

`class User
...
def self.find_first_by_auth_conditions warden_conditions
conditions = warden_conditions.dup
if (email = conditions.delete(:email)).present?
where(email: email.downcase).first
elsif conditions.has_key?(:reset_password_token)
where(reset_password_token: conditions[:reset_password_token]).first
end
end
end
`

It worked then after.

**Comment by akhil-gautam** [comment]
I am using devise 4.2
Rails 4.2.8
Ruby 2.3.4
I don't know how to setup devise forgot password with my Gmail. Can anyone help me?
