### ISSUE TITLE
undefined method `confirmation_url' 

### ISSUE THREAD

**Issue by g8d3** [plataformatec/devise#2704]
Hi,

I read #200 #1365 and #2012.

I am using devise (3.1.0), warden (1.2.3), rails (4.0.0) and mongoid (4.0.0).

I think the answer to all this issue is http://stackoverflow.com/questions/7461332/rails3-devise-undefined-method-confirmation-url, but I was wondering if there is a solution that does not make me to generate views.

This is what I did:

\1. `rails g devise:install`.
\2. Wrote `config.action_mailer.default_url_options = { :host => 'localhost:3000' }` in `config/environments/development.rb`.
\3. `app/models/user/devise_stuff.rb`:

``` ruby
module User::DeviseStuff

  def self.included(base)
    base.class_eval do
      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable and :omniauthable
      devise :database_authenticatable, :registerable, :confirmable,
        :recoverable, :rememberable, :trackable, :validatable

      ## Database authenticatable
      field :email,              :type => String, :default => ""
      field :encrypted_password, :type => String, :default => ""

      ## Recoverable
      field :reset_password_token,   :type => String
      field :reset_password_sent_at, :type => Time

      ## Rememberable
      field :remember_created_at, :type => Time

      ## Trackable
      field :sign_in_count,      :type => Integer, :default => 0
      field :current_sign_in_at, :type => Time
      field :last_sign_in_at,    :type => Time
      field :current_sign_in_ip, :type => String
      field :last_sign_in_ip,    :type => String

      ## Confirmable
      field :confirmation_token,   :type => String
      field :confirmed_at,         :type => Time
      field :confirmation_sent_at, :type => Time
      field :unconfirmed_email,    :type => String # Only if using reconfirmable

     end
  end

end
```

\4. `app/models/user.rb`

``` ruby
class User
    include Mongoid::Document
    include Mongoid::Timestamps
    include User::DeviseStuff
end
```

\5. `config/routes.rb`

``` ruby
MyApp::Application.routes.draw do

  devise_for :users
```

\6. In my form I am POSTING to `users_path` which is the same as `user_registration_path`, in rake routes appears as:

```
          user_registration POST   /users(.:format)             devise/registrations#create
```

\7. I get this after that POST:

![screen shot 2013-10-24 at 4 08 08 pm](https://f.cloud.github.com/assets/671721/1403241/6a8d4696-3cf0-11e3-8414-1d155d1f82aa.png)

Thanks in advance.

**Comment by ariejan** [comment]
For posterity: if you run into this issue running `rake db:see`, be sure to restart (e.g. kill) spring.
