### ISSUE TITLE
Confirmable breaks when after_create callback is used on new User

### ISSUE THREAD

**Issue by Bazm0** [plataformatec/devise#2706]
after_create callback on User model causes the confirmation_token to be regenerated and updated after the initial user has been saved. This results in an "invalid token" error on confirmation as the original confirmation_token was overwritten subsequent to email delivery.

Hope this makes sense.

**Comment by yaneeka** [comment]
See further discussion on this issue at the bottom of this thread. 

https://github.com/plataformatec/devise/issues/2615

Workaround is to use after_commit instead of after_create.
