### ISSUE TITLE
Flash messages being set with Rails API

### ISSUE THREAD

**Issue by rsiddle** [plataformatec/devise#2775]
I'm using the Rails API (doesn't use Flash Middleware). I'm finding that when I try CURL'ing to the reset password the response appears to be in HTML format which is an error that says. 

```
 <h2>undefined local variable or method `flash&#39; for #&lt;PasswordsController:0x007fbb11fcf598&gt;</h2>
```

HTML format has been disabled too which is why its a little strange that its trying to respond this way.

``` ruby
curl -X POST 'http://localhost:3001/users/password.json' -d 'user[email]=ryan@example.com'
```

``` ruby
class PasswordsController < Devise::PasswordsController

  respond_to :json
  respond_to :html, only: []
  respond_to :xml, only: []

end
```

Any thoughts as to why this might be happening?

**Comment by jonlemmon** [comment]
Defining the format as json in the routes worked well for me:

```devise_for :users, defaults: { format: :json }```
