### ISSUE TITLE
Devise v3.1.0 requires config.secret_key on asset precompilation, but Heroku precompiles without environmental variables

### ISSUE THREAD

**Issue by rringler** [plataformatec/devise#2795]
Forgive me if this is has already been answered,

It's common open-source security practice to store sensitive data (eg., security keys) in environmental variables to prevent them from being checked into source control.  A nice Ruby example of this is the figaro gem.  Upon updating Devise from a ~v3.0 version to v3.1.1, when I try to deploy my app to Heroku, when Heroku tries to precompile my assets Devise complains that config.secret_key is not set in my devise initializer.  My devise initializer DOES set the config.secret_key variable, but it sets it to a Heroku config:variable that is not present during asset precompilation.  Is there any work around this?

**Comment by spotscale** [comment]
I have this problem on a non heroku machine. I'm deploying using capistrano and This same problem prevents my deploy. I Think this should be fixed.
