### ISSUE TITLE
OmniAuth with Locale

### ISSUE THREAD

**Issue by kot-begemot** [plataformatec/devise#2813]
Hey. I am developing [rails-localization](https://github.com/kot-begemot/rails-localization) gem. Everything went pretty well, until I tried to use Devise + OmniAuth inside localized scope.
### tldr

The solution I found is to use `devise_for :user` two times inside routes.rb

```
MyApp::Application.routes.draw do
  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  localized({...}) do
    devise_for :users, path: '', skip: [:omniauth_callbacks]
  end
end
```

But I am not sure that this is a good practice and I would like to hear a better option.
### The problem

Point is, this scope yields content like that

```
scope("(:locale)", ...) { yield }
```

All other URL are happy with that, but not if you use omniauth with devise_for

```
localized({"en" => "English", "ru" => "Русский"}) do
  devise_for :users, path: '', :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end
```

Then, Rails will fail on initialization with [that error](https://github.com/plataformatec/devise/blob/master/lib/devise/rails/routes.rb#L399).
So far so good. I tried to implement it like that

```
localized({"en" => "English", "ru" => "Русский"}) do
  devise_for :users, path: '', skip: [:omniauth_callbacks]
end

match "/users/auth/:provider",
  :constraints => { :provider => /facebook|vkontakte/ },
  :to => "users/omniauth_callbacks#passthru",
  :as => :user_omniauth_authorize,
  :via => [:get, :post]

match "/users/auth/:action/callback",
  :constraints => { :action => /facebook|vkontakte/ },
  :to => "users/omniauth_callbacks",
  :as => :user_omniauth_callback,
  :via => [:get, :post]
```

It failed with [that error](https://github.com/plataformatec/devise/blob/master/app/controllers/devise_controller.rb#L58).
Next attempt was that one

```
localized({"en" => "English", "ru" => "Русский"}) do
  devise_for :users, path: '', skip: [:omniauth_callbacks]
end

devise_scope :user do
  match "/users/auth/:provider",
    :constraints => { :provider => /facebook|vkontakte/ },
    :to => "users/omniauth_callbacks#passthru",
    :as => :user_omniauth_authorize,
    :via => [:get, :post]

  match "/users/auth/:action/callback",
    :constraints => { :action => /facebook|vkontakte/ },
    :to => "users/omniauth_callbacks",
    :as => :user_omniauth_callback,
    :via => [:get, :post]
end
```

And test failed =(. Here is its output

```
1) Authentication click login with facebook
   Failure/Error: page.should have_content('Successfully authenticated from Facebook account.')
     expected to find text "Successfully authenticated from Facebook account." in "Not found. Authentication passthru."
   # ./spec/features/registration_spec.rb:37:in `block (3 levels) in <top (required)>'
```

And here is test file content

```
# encoding: utf-8
require "spec_helper"

feature 'Authentication' do
  background do
    visit root_path
    OmniAuth.config.test_mode = true
    OmniAuth.config.mock_auth[:facebook] = OmniAuth::AuthHash.new(OAuthHelper.facebook)
  end

  scenario 'click login with facebook' do
    visit "/users/auth/facebook"

    page.should have_content('Successfully authenticated from Facebook account.')
  end
end
```

Just to mention, that this test IS PASSING if I am defining `devise_for` outside of `localized` scope

```
localized({...}) do; ....; end

devise_for :users, path: '', :controllers => {
  omniauth_callbacks: "users/omniauth_callbacks"
}
```
### Some of my playing arounds

I thought that root of that `Not found. Authentication passthru.` problem is that Devise.mappings[:user] is missing those things

```
#<Devise::Mapping:0x000000072959d0 
  ...
  @controllers=
    {...
     :omniauth_callbacks=>"users/omniauth_callbacks"},
  ...
  @used_routes=[..., :omniauth_callback]>
```

And the black magic, somewhere inside `Devise::OmniauthCallbacksController` is checking for those things, so I tried to insert those things into Mapping instance manually

```
def append_omniauth_to_devise(scope)
  mapping = Devise.mappings[scope]
  mapping.controllers.merge!({omniauth_callbacks: "users/omniauth_callbacks"})
  mapping.used_routes << :omniauth_callback
end

MyApp::Application.routes.draw do
  localized({...}) do
    devise_for :users, path: '', skip: [:omniauth_callbacks]
  end

  append_omniauth_to_devise(:user)
  devise_scope :user do
    match "/users/auth/:provider",
      :constraints => { :provider => /facebook|vkontakte/ },
      :to => "users/omniauth_callbacks#passthru",
      :as => :user_omniauth_authorize,
      :via => [:get, :post]

    match "/users/auth/:action/callback",
      :constraints => { :action => /facebook|vkontakte/ },
      :to => "users/omniauth_callbacks",
      :as => :user_omniauth_callback,
      :via => [:get, :post]
  end
end
```

And the did not worked out =(

**Comment by jefvlamings** [comment]
@gurix 

I used your solution for a while, but seem to bump into one issue lately.
When authentication via OmniAuth fails, the wrong controller is chosen.
This only occurs if you have your devise routes namespaced and localized.

Apparently you cannot call `devise_for` twice in the routes file, without side effects.
Only the routes of the last `devise_for` statement are added to the Devise mapping.
When Devise (in lib/devise/omniauth.rb) tries to match the failure redirect with the right controller, the namespaced controller is not picked up. 

A solution to this problem is to redeclare the omniauth controller in the second `devise_for` statement. 

If you want to namespace all controllers under `/user`, you should declare the routes like this:
```ruby
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  localized do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        unlocks: 'users/unlocks',
        confirmations: 'users/confirmations',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }
  end 
end
```
Also, skipping all controllers in the first `devise_for`, doesn't provide any benefit. 
Nothing seems to go wrong when they are omitted like in the example above.
