### ISSUE TITLE
Devise controllers should be extended of ActionController::Base not ApplicationController

### ISSUE THREAD

**Issue by sigerello** [plataformatec/devise#282]
I use Admin::ApplicationController class as base class for my admin side and ApplicationController class as base class for client side.
There are some different filter methods specific for admin and client sides.
That's why I add :admin namespace to separate base classes:
    #app/controllers/admin/
    class Admin::ApplicationController < ActionController::Base
      # some special code for beckend...
    end

```
#app/controllers/
class ApplicationController < ActionController::Base
  # some other code for frontend...
end
```

But all Devise controllers are extended of ApplicationController class.
I think they should be extended of ActionController::Base because it's a base for both ApplicationController and Admin::ApplicationController classes and it doesn't have any filters or namespace specific things.

Will be even better if there are some methods to include appropriate functionality directly to any controller that you want without extending them of Devise controllers.
I mean something like you have in your inherited_resources gem:
    class Admin::UsersController < Admin::ApplicationController
      inherit_resources
    end
It migth be like:
    class Admin::UsersController < Admin::ApplicationController
      devise :sessions
    end

**Comment by ibrahim-saifee** [comment]
devise configuration `config.parent_controller` can be used to configure the parent controller which devise uses to extend its controllers.
