### ISSUE TITLE
Devise Error after integrating versioning - "Authentication required for Sign In action"

### ISSUE THREAD

**Issue by tacticiankerala** [plataformatec/devise#2824]
We integrated 'versionist' gem for path based versioning for our APIs. After integrating versionist we found that only default sign in/ sign up/password reset urls(Eg: /users/sign_in) are working. The same actions for different versions were giving issues(Eg: /v1/users/sign_in).

We were able to identify that this issue was caused because of the scope. For example, if we are using v1 API then the scope received in Sessions#create is found to be v1_user.

Here is the set up we used,

Routes

``` ruby
 api_version(:module => "v1", :path => {:value => "v1"}) do
   devise_for :users, :controllers => { 
      :registrations => 'v1/registrations',
      :sessions => 'v1/sessions',
      :passwords => 'v1/passwords'
    }   
end
```

And we got the auth_options inside Sessions#create as

``` ruby
{:scope => :v1_user, :recall => "sessions#new"}
```

We tried overriding the scope to :user and everything started working.

Similar issues we faced in registrations and passwords controller, where the devise parameters found to be nil for constructing the resource.

Here is our dependencies,

```
rails (3.2.13)
devise (2.2.3)
versionist (1.2.1)
```

Right now we have overridden all the required devise actions, is there a better solution to this problem?

**Comment by Genkilabs** [comment]
For posterity... I found this while trying to use Devise with Versionist and custom strategies.
Here is the Gist for my solution https://gist.github.com/Genkilabs/587fab4214798c87c3aa97bb06280f43

**Comment by twnaing** [comment]
@tacticiankerala , how did you override the scope to :user? 

I tried in controller to override `auth_options` and `resource_name` methods but failed

**Comment by twnaing** [comment]
`api_version` with `path` strategy [use](https://github.com/bploetz/versionist/blob/3a8e21c90bb4767f8b3e5519d1b803cb3aeeb6b5/lib/versionist/routing.rb#L55) Rails' `namespace` method with `as` option and hence `DatabaseAuthenticatable` expects the name accordingly `:v1_user`

API versioning using header works.
