### ISSUE TITLE
sign_in_and_redirect() not using url's in after_sign_in_path_for()

### ISSUE THREAD

**Issue by ghost** [plataformatec/devise#2828]
While using Omniauth, if the `OmniauthCallbacksController` calls `sign_in_and_redirect(user)`, it doesn't not use the paths defined in the Session controller's overridden `after_sign_in_path_for`

**Comment by AmitPatel-BoTreeConsulting** [comment]
I placed below method in `ApplicationController` but it doesn't get called  all

```
def after_sign_in_path_for(resource)
    binding.pry
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
```

```
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
  ...
   sign_in_and_redirect @user, event: :authentication
  ...
  end
end
```

**Comment by josevalim** [comment]
After_sign_in_path customizes it only for the sessions controller.

On Wednesday, December 2, 2015, Amit Patel <notifications@github.com> wrote:

> I placed below method in ApplicationController but it doesn't get called
> all
>
> def after_sign_in_path_for(resource)
>     binding.pry
>     request.env['omniauth.origin'] || stored_location_for(resource) || root_path
>   end
>
> class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
>   def twitter
>   ...
>    sign_in_and_redirect @user, event: :authentication
>   ...
>   end
> end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/devise/issues/2828#issuecomment-161233083>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by AmitPatel-BoTreeConsulting** [comment]
`after_sign_in_path_for` gets called only in if user sign in with email/password. But it doesn't get called with omniauth sign in even if it is placed in `SessionsController`

```
class SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    binding.pry
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end
```

BTW I followed [wiki](https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in#redirect-back-to-current-page-after-oauth-signin) which suggests to add `after_sign_in_path_for` in `ApplicationController`

**Comment by josevalim** [comment]
Sorry, that is what I meant: if you customize it in the sessions controller, it will be applied only there. If you set it in ApplicationController, it should work generally. You can also set it in your omniauth controller.

**Comment by Kani999** [comment]
What is the preffered way to use in `after_sign_in_path_for` when using OmniAuth then?

**Comment by carlosantoniodasilva** [comment]
@Kani999 you should be able to define it in your ApplicationController.
