### ISSUE TITLE
Devise STI ActionController::UnknownFormat

### ISSUE THREAD

**Issue by jtomasrl** [plataformatec/devise#2834]
I have an account model and submodels that inherits from that. Those model are managers and employees, managers in order to register have to confirm their accounts using devise. The email is sent and i had to change confirmation_url to manager_confirmation_url inside confirmation_instructions.html.erb. The first thing is that i had to use views/devise/email/confirmation_instructions, couse views/managers/email/confirmation_instructions didnt work. After the email was send i got this URL 

```
http://localhost:3000/managers/confirmation.52cee9bf4d6163cb9a010000?confirmation_token=JagtokszN59SiagSwSBC
```

and this error message:

```
ActionController::UnknownFormat in Devise::ConfirmationsController#show
```

my routes

```
  devise_for :accounts,  skip: [ :registrations ]
  devise_for :admins,    skip: [ :sessions, :registrations ]
  devise_for :managers,  skip: :sessions, controllers: { registrations: "accounts/registrations" }
  devise_for :employees, skip: :sessions, controllers: { registrations: "accounts/registrations" }
```

**Comment by lifeBalance** [comment]
Use this link instead:
```ruby
<p><%= link_to 'Confirm my account',  user_confirmation_url(confirmation_token: @token) %></p>
```
