### ISSUE TITLE
devise_for vs devise_scope routes

### ISSUE THREAD

**Issue by michaelirey** [plataformatec/devise#2840]
```
Using devise (3.2.2)
Using rails (4.0.2)
```

Working on developing an API which only has the need for only certain routes. I have the following in my `routes.rb`:

```
devise_for :users, path: '/users', controllers: {
  sessions: 'v1/custom_devise/sessions',
  passwords: 'v1/custom_devise/passwords'
}
```

Great! Now we have all these routes:

```
              Prefix Verb    URI Pattern                    Controller#Action
    new_user_session GET     /users/sign_in(.:format)       v1/custom_devise/sessions#new
        user_session POST    /users/sign_in(.:format)       v1/custom_devise/sessions#create
destroy_user_session DELETE  /users/sign_out(.:format)      v1/custom_devise/sessions#destroy
       user_password POST    /users/password(.:format)      v1/custom_devise/passwords#create
   new_user_password GET     /users/password/new(.:format)  v1/custom_devise/passwords#new
  edit_user_password GET     /users/password/edit(.:format) v1/custom_devise/passwords#edit
                     PATCH   /users/password(.:format)      v1/custom_devise/passwords#update
                     PUT     /users/password(.:format)      v1/custom_devise/passwords#update
```

But I do not want or need these routes:

```
    new_user_session GET     /users/sign_in(.:format)       v1/custom_devise/sessions#new
   new_user_password GET     /users/password/new(.:format)  v1/custom_devise/passwords#new
  edit_user_password GET     /users/password/edit(.:format) v1/custom_devise/passwords#edit
```

So I thought I will just create my own routes as per the documentation. So I changed my `routes.rb`:

```
devise_scope :user do
  post   '/users/sign_in'  => 'custom_devise/sessions#create',  as: :user_session
  delete '/users/sign_out' => 'custom_devise/sessions#destroy', as: :destroy_user_session

  post  '/users/password'  => 'custom_devise/passwords#create', as: :user_password
  put   '/users/password'  => 'custom_devise/passwords#update', as: nil
  patch '/users/password'  => 'custom_devise/passwords#update', as: nil
end
```

Now my routes look perfect, just the way I want them:

```
              Prefix Verb    URI Pattern                   Controller#Action
        user_session POST    /users/sign_in(.:format)      v1/custom_devise/sessions#create
destroy_user_session DELETE  /users/sign_out(.:format)     v1/custom_devise/sessions#destroy
       user_password POST    /users/password(.:format)     v1/custom_devise/passwords#create
                     PUT     /users/password(.:format)     v1/custom_devise/passwords#update
                     PATCH   /users/password(.:format)     v1/custom_devise/passwords#update
```

But now my requests fail, with:

```
 AbstractController::ActionNotFound:
   Could not find devise mapping for path "/users/sign_in".
   This may happen for two reasons:

   1) You forgot to wrap your route inside the scope block. For example:

     devise_scope :user do
       get "/some/route" => "some_devise_controller"
     end

   2) You are testing a Devise controller bypassing the router.
      If so, you can explicitly tell Devise which mapping to use:

      @request.env["devise.mapping"] = Devise.mappings[:user]
```

After debugging for some reason `Devise.mappings[:user]` is nil when using devise_scope, but is not nil when using devise_for.

I have tried many variations, to no avail.

**Comment by pamio** [comment]
@beauby I'm using rails-api to generate json apis so when I add `devise_for :users skip: :all` I get the following error

    => Booting WEBrick
    => Rails 4.2.1 application starting in development on http://localhost:3000 
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    Exiting
    /home/pamio/.rvm/gems/ruby-2.1.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `ensure in   with_devise_exclusive_scope': undefined method `merge!' for #<ActionDispatch\
    ::Routing::Mapper::Scope:0x000000071ce380> (NoMethodError)
        from /home/pamio/.rvm/gems/ruby-2.1.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in  `with_devise_exclusive_scope'
        from /home/pamio/.rvm/gems/ruby-2.1.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:246:in `block  (2 levels) in devise_for'
         from /home/pamio/.rvm/gems/ruby-2.1.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:349:in `block in devise_scope'

Any ideas ??

**Comment by carlosantoniodasilva** [comment]
@pamio please update your devise version, official support for Rails 4.2 was [released on v3.4](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#340---2014-10-03).

**Comment by pamio** [comment]
@carlosantoniodasilva thanks for the update. It solved my problem.

**Comment by andela-sdamian** [comment]
this should help solve your problem

**Comment by andela-sdamian** [comment]
This should help solve your problems http://stackoverflow.com/questions/22063026/how-do-i-override-devise-controller-and-devise-routes-at-the-same-time

**Comment by zhoplocal** [comment]
anyone still facing this issue even after doing

`devise_for :users, skip: :all`
`devise_scope :user do`
`end`

please refer to this issue https://github.com/plataformatec/devise/issues/2496#issuecomment-20645182 if you're calling `devise_scope` inside a namespace.

**Comment by kartikupadhyay90** [comment]
yes I am also facing the same issue

**Comment by rbf** [comment]
For reference, this is how I solved the issue about `Could not find devise mapping for path...`, which is a bit different to the solution referenced in https://github.com/plataformatec/devise/issues/2840#issuecomment-295402383 by @zhoplocal.

In my case I'm exposing Devise within an API and everything is namescoped into `/api/v1`. The problem was that I called `devise_for :users` also within the namescope, which didn't work: 

```ruby
namespace :api do
  namespace :v1 do
    devise_for :users, skip: :all
    devise_scope :user do
      post 'users', to: 'registrations#create', as: nil
    end
  end
end
```

Moving the `devise_for :users` call outside of the namespacing, allowed my custom controllers to work:

```ruby
# DOC: https://github.com/plataformatec/devise/blob/v4.3.0/lib/devise/rails/routes.rb#L33
devise_for :users, skip: :all

namespace :api do
  namespace :v1 do
    devise_scope :user do
      post 'users', to: 'registrations#create', as: nil
    end
  end
end

# Used in the signup email by devise to confirm the signup.
get '/signup/confirm', to: 'custom_controller#some_action', as: :user_confirmation
```

Note that the corresponding controller `registrations` will be expected under the according namespace, i.e. `class Api::V1::RegistrationsController < Devise::RegistrationsController` in the file `/app/controllers/api/v1/registrations_controller.rb`. Also, I had to manually provide a route prefixed `user_confirmation`, so that the default confirmation email can be generated.

For what is worth, this was working for me as in the first example, i.e. with the `devise_for :users` call _inside_ of the namespacing and with the confirm path prefixed as `as: :api_v1_user_confirmation`. Sadly I'm not sure what I did change that broke this setup and I had to move the `devise_for :users` call outside of the namespacing. Maybe it's related to the fact that I'm using Doorkeeper as well within the same namescope, but I was unable to isolate the cause.

Thanks to all the commenters above! 👍

**Comment by widergy** [comment]
@rbf Thanks for your solution! Moving the `devise_for :users` call outside of the namespacing worked for me. I also have a Rails API project. *This configuration should be documented by Devise!*

My `routes.rb` file looks like this now:
```
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # API Endpoints
  api_version(module: 'api/v1', path: { value: 'api/v1' }, defaults: { format: :json }) do
    ...
    namespace :users do
      resource :profile, only: [:show, :update]
      ...
    end
    resources :users, only: [:create] do
      collection do
        resources :notifications, only: [:index, :update]
        resources :sessions, only: [:create]
        ... 
        get :show
        put :update
      end
    end

    devise_scope :user do
      post 'users/password', to: 'users/passwords#create'
      put 'users/password', to: 'users/passwords#update'
      post 'users/confirmation', to: 'users/confirmations#create'
      get 'users/client_auth/google', to: 'users/omniauth_client#google'
      get 'users/client_auth/facebook', to: 'users/omniauth_client#facebook'
      get 'users/client_auth/microsoft', to: 'users/omniauth_client#microsoft'
      get 'users/client_auth/twitter_callback', to: 'users/omniauth_client#twitter_callback'
      post 'users/client_auth/twitter_callback', to: 'users/omniauth_client#twitter_callback'
      get 'users/client_auth/twitter_request_token', to: 'users/omniauth_client#twitter_request_token'
      post 'users/client_auth/twitter_request_token', to: 'users/omniauth_client#twitter_request_token'
    end
  end

  devise_for :users, skip: :all, path_prefix: 'api/v1', controllers: {
    omniauth_callbacks: 'api/v1/users/omniauth_callbacks'
  }
end
```
