### ISSUE TITLE
edit_user_password_url returns wrong url in reset_password_instructions.html.erb

### ISSUE THREAD

**Issue by n-studio** [plataformatec/devise#2848]
Hi!
I don't have the correct URL in my reset password instruction email.

The routes.rb file specifies

```
# edit_user_password GET    /users/password/edit(.:format)    {:controller=>"devise/passwords", :action=>"edit"}
```

But in reset_password_instructions.html.erb we've got:

```
<%= link_to 'Change my password', edit_user_password_url(@resource, :reset_password_token => @token) %>
```

So it prints: http://localhost:3000/users/password/edit.1?reset_password_token=EQggsfpz8UpCqjauwnxk

Shouldn't it be
`<%= link_to 'Change my password', edit_user_password_url(:reset_password_token => @token) %>` ?
Or am I missing something?

**Comment by trejkaz** [comment]
In reverse, I'm finding that it is generating:

    edit_password_url(@resource, reset_password_token: @token)

But the actual routes have edit_user_password, so it should be edit_user_password_url.
