### ISSUE TITLE
Devise not authenticating users after upgrade

### ISSUE THREAD

**Issue by ramza1** [plataformatec/devise#2861]
My rails app fails to authenticate users. It was initially on devise 1.4 and i upgraded the app to rails 4 and the latest devise gem. after taking the app to production and loading the initial users their accounts fails to sign in. i am getting the following error

A BCrypt::Errors::InvalidHash occurred in sessions#create:

How can i make my users that registered with devise 1.4 sign in with the latest devise. There are over 1000 existing users unable to sign in to the app. only new users can sign in. Any help thanks

**Comment by divyang9389** [comment]
hello @ramza1 

I face the same issue. can you help me to fix encriptor?

**Comment by entersoftapps** [comment]
Hello @divyang9389 
add a gem
`gem "devise-encryptable"` gem 

add below config in devise.rb

`config.encryptor = :sha512`
