### ISSUE TITLE
Reset password token is invalid

### ISSUE THREAD

**Issue by jimiguru** [plataformatec/devise#2871]
I'm having a devil of a time with this one.

Rails 4
Devise 3.2.2
Postgres 9.3.2

Using @token, not @reset_password_token

Token is being set properly in the DB as is remember_password_sent_at timestamp.

I can query on the command line for users = @token and get the desired result.

No matter what, when attempting to reset the PW I get Reset password token invalid.

**Comment by michaelmittermayr** [comment]
Same here. Although the reset token from the reset password instructions email matches with the reset token from the database it returns an invalid token error on the changing password form. Database query expose that devise looks for a different token in the database.

**Comment by nadeemja** [comment]
Experiencing this issue as well.

**Comment by nadeemja** [comment]
This commit works:
1094ba65aac1d37713f2cba71f9edad76b5ca274

**Comment by Kagetsuki** [comment]
Same issue but I don't have any info to contribute that hasn't already been stated.
age⤴

**Comment by zeitnot** [comment]
I have the same problem.

**Comment by zeitnot** [comment]
When I upgrade devise from `3.4.1` to latest commit, the problem has gone away. It seems that it fixed.

**Comment by amitdotagarwal** [comment]
i faced the similar issue, solution is 
change:
edit_password_url(@resource, reset_password_token: @resource.reset_password_token) 
to 
edit_password_url(@resource, reset_password_token: @token)

**Comment by calderson** [comment]
Had the same issue. Thanks @amitdotagarwal. That fixed it for me as well

**Comment by asimisoft** [comment]
In my case `reset_tokan` in database and token in url for reset password are same

       > User.last.reset_password_token
       "deb8e7fcaef019273e04288c685205ac40eb37e92d91e52e39b06225cc0d8803"

      URL: http://lvh.me:3000/users/password/edit?reset_password_token=deb8e7fcaef019273e04288c685205ac40eb37e92d91e52e39b06225cc0d8803

Now, when I submit that reset password form, it said `Reset password token is invalid`.

This Stackoverflow link can elaborate my issue more http://stackoverflow.com/questions/33823735/devise-reset-password-token-invalid

**Comment by przbadu** [comment]
In my case `reset_tokan` in database and token in url for reset password are same

       > User.last.reset_password_token
       "deb8e7fcaef019273e04288c685205ac40eb37e92d91e52e39b06225cc0d8803"

      URL: http://lvh.me:3000/users/password/edit?reset_password_token=deb8e7fcaef019273e04288c685205ac40eb37e92d91e52e39b06225cc0d8803

Now, when I submit that reset password form, it said `Reset password token is invalid`.

This Stackoverflow link can elaborate my issue more http://stackoverflow.com/questions/33823735/devise-reset-password-token-invalid

**Comment by przbadu** [comment]
Well, I found the solution. I was completely doing wrong solution. The solution is pretty simple to use devise's `send_reset_password_instructions` something like: 

    @user.send_reset_password_instructions

and it solved my problem

**Comment by neeraji2it** [comment]
thanks

**Comment by jontyjont** [comment]
concur with @amitdotagarwal  - the reason is that the token is now encrypted in the model so in order to present the token it needs to be the unencrypted one - that should be what is in the email hence putting @token in it
I followed that advice and it worked for me - i had not noticed the change in policy to encrypt the token in the model - where was the news?

**Comment by roya-anane** [comment]
I still don't get it. How can I get the token from the email and not the one from the db?
