### ISSUE TITLE
Timeoutable doesn't work with rails 4.1.0.pre1

### ISSUE THREAD

**Issue by lejoko** [plataformatec/devise#2930]
Hi,

I built the rails 4.1.0 example application "Devise and Rails" that is on https://github.com/plataformatec/devise/wiki/Example-Applications

If I add :timeoutable to the user model of this app, log in the app and try to navigate, I get an "ArgumentError comparison of String with ActiveSupport::TimeWithZone failed"

Apparently in lib/devise/hooks/timeoutable.rb around line 28:

last_request_at = warden.session(scope)['last_request_at']

returns a string instead of a Time.

Have a nice day.

**Comment by reggieb** [comment]
Updating to Devise 3.3 fixed the issue for me. Thank you. :+1:
