### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by pvdev** [plataformatec/devise#2940]
Hi,

I upgraded from 2.2.3 to 2.2.8 in Rails 3.2.13 and I get a the following warning on my "Bad User" test or if I attempt login with bad email (i.e., not in db)

DEPRECATION WARNING: an empty resource was given to Devise::Strategies::DatabaseAuthenticatable#validate. Please ensure the resource is not nil. (called from require at script/rails:6)

Bad email or password notice still appears and form renders with previously attempted bad email.  Test still passes.  The deprecation warning is just bothering me.

Did I miss a manual change step between minor versions?  What's being deprecated that I need to fix?

Help appreciated,
Perry

**Comment by janraasch** [comment]
@johvet did you ever get around to firing that pr?
@josevalim what is your opinion on @johvet suggestion, i.e.

```ruby
def authenticate!
  resource  = valid_password? && mapping.to.find_for_database_authentication(authentication_hash)
  encrypted = false
  if resource
   ... old behavior ...
  end
  fail(:not_found_in_database) unless resource
end
```

The problems seems to persist. I think we should get this fixed.

**Comment by atz** [comment]
Encountering this problem in legacy codebase today...
