### ISSUE TITLE
RegistrationsController#create does not indicate email confirmation possibility when allow_unconfirmed_access_for is nil

### ISSUE THREAD

**Issue by dpehrson** [plataformatec/devise#2941]
In my application I set `allow_unconfirmed_access_for` to `nil`. I allow access, but restrict functionality until they get around to confirming.

While writing some cucumber features for my app, I had an expectation that in my scenario on registration the message displayed to the user would be `devise.registrations.signed_up_but_unconfirmed` when in fact it uses `devise.registrations.signed_up`

The reason for this is because when `allow_unconfirmed_access_for` is set to allow access the resource is `active_form_authentication?`:

``` ruby
if resource.active_for_authentication?
  set_flash_message :notice, :signed_up if is_flashing_format?
  ...
else
  set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
  ...
end
```

Looking at the current keys/language, the current behavior is MORE correct because `signed_up_but_unconfirmed` indicates they MUST activate their account, but really neither are correct. `signed_up` doesn't let the user know that they have the ability to confirm their email or what they are missing out on if they don't and `signed_up_but_unconfirmed` (by default) incorrectly indicates that their account is not yet active at all.

I see three possible fixes:
1. I change the language of `signed_up`. Downside here is it won't react dynamically if I later change `allow_unconfirmed_access_for` but maybe that's my problem.
2. Use `signed_up_but_unconfirmed` instead of `signed_up_but_unconfirmed` when `allow_unconfirmed_access_for` is set to `nil` or a non-zero positive integer.
3. Introduce more fine-grained language keys to cover more possible scenarios:
- `devise.registrations.signed_up_but_unconfirmed_days.singular`: "A message with a confirmation link has been sent to your email address. Please open the link within one day to activate your account."
- `devise.registrations.signed_up_but_unconfirmed_days.plural`: "A message with a confirmation link has been sent to your email address. Please open the link within %{count} days to activate your account."
- `devise.registrations.signed_up_but_unconfirmed_days.forever`: "A message with a confirmation link has been sent to your email address. Please open the link to confirm your address and unlock full functionality."

I just made the language up as an example obviously, the defaults can be worked out.

Thoughts? I am perfectly willing to accept that the solution is the first one which is on me.

**Comment by jgonzalezd** [comment]
I just hit this problem. Just wonder how did you worked around this one.

**Comment by jgonzalezd** [comment]
Ok, just for the record, in Users::RegistrationsController I Added the sent email message

def create
    super
    flash[:alert] = t('devise.registrations.signed_up_but_unconfirmed') unless resource.confirmed?
  end
