### ISSUE TITLE
Update Password Succeeds Without Password Confirmation

### ISSUE THREAD

**Issue by joelcdoyle** [plataformatec/devise#2942]
I have created an API using devise. When creating a user, it is required that a password and a password_confirmation be provided, and that they match. However, I can't replicate this behavior when updating a user's password. 

When updating a user's password, I would like a valid current_password, password, and password_confirmation to be provided

I'm whitelisting :current_password, :password, and :password_confirmation with strong params in my controller, and using update_with_password to update the password attribute on my user instance.

I have a gist here:
https://gist.github.com/joelcdoyle/9747192

**Comment by TomasBarry** [comment]
Hi @josevalim,

Is there a way other than using `validates_presence_of :password_confirmation, :if => :password_changed?` to force Devise to require a password confirmation on all updates and to fail if the `password_confirmation` is `nil`?
