### ISSUE TITLE
devise + mongoid 

### ISSUE THREAD

**Issue by eddiefisher** [plataformatec/devise#2949]
application successful working with mongoid, after install devise I try to login in application but got error

The operation: #<Moped::Protocol::Query @length=124 @request_id=2 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="ereader_development.users" @skip=0 @limit=-1 @selector={"$query"=>{"_id"=>{"$oid"=>BSON::ObjectId('5333276a6d6163c871000000')}}, "$orderby"=>{:_id=>1}} @fields=nil> failed with error 10068: "invalid operator: $oid" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.

**Comment by dimidev** [comment]
@rjurado01 thx it works for me too

**Comment by rdetert** [comment]
I'm using Rails 4.1.8. I got it working by:

1) Commenting out `Rails.application.config.action_dispatch.cookies_serializer = :json` as others have mentioned
2) Deleting cookies and restarting server
3) Added random string to the `key` in the `session_store.rb`

**Comment by andreicristianpetcu** [comment]
thank you @ArthurCamara and @fransstudio2 Your solutions worked for me. I needed to delete the old cookies and then it worked.

**Comment by pencilcheck** [comment]
@adrpac thanks that works

**Comment by ReyLitch** [comment]
Thanks @rjurado01. That works for me with rails 4.1.6, devise 3.4.1 and mongoid 4.0.1. However I have to modify your method adding "as_json" because I always obtain an error when try to access to "$oid":

    ...
    def self.serialize_from_session(key, salt)
      record = to_adapter.get(key[0].as_json["$oid"])
      record if record && record.authenticatable_salt == salt
    end
    ...
