### ISSUE TITLE
failsafe response: uncaught throw :warden in development and production, custom 404

### ISSUE THREAD

**Issue by gkulasik** [plataformatec/devise#3010]
Hi,

I am using Rails 3.2 and Devise. i wanted custom error pages (404, 500, etc.) to display so that the error pages looked the same as my regular site (to keep things consistent). I used this guide to set up the custom error routes: http://wearestac.com/blog/dynamic-error-pages-in-rails  (using the basic implementation). So I have a errors controller and views for 404, 500, and 422. The issue is with warden when I am signed in my error pages in development and production work fine. When I am signed out however I get the 'failsafe response: uncaught throw :warden" error and a nasty "500 Internal Server Error: If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong" text page. All the issues I could find online deal with tests but I am not testing I am in development or in production on Heroku. Is there any fix around this? I know the issues stems from the authenticate_user! method  I just do not know how to fix this. Any help is appreciated.

**Comment by micadschmidt** [comment]
```
class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!

  def not_found
    render status: :not_found
  end

  def internal_server_error
    render status: :internal_server_error
  end
end
```


This worked for me
