### ISSUE TITLE
sign_out doesn't properly clear cookie-based sessions

### ISSUE THREAD

**Issue by trianglegrrl** [plataformatec/devise#3031]
We have a Rails 4.0.5 app with Devise 3.2.4. 

For some reason, when we call `SessionsController#destroy`, it correctly logs the current user out, but it does not correctly destroy the session when the `OurApp::Application.config.session_store` is set to `:cookie_store`. Installing the new `activerecord-session_store` gem and changing `session_store` to `active_record_store` resolves the issue. 

Here's the order of what happens:
1. We `DELETE /users/sign_out`.
2. `#destroy` gets called, and does seem to nuke the session. `current_user` becomes `nil`, and Warden doesn't know about any users. However, the session cookie is not removed from the browser.
3. `after_sign_out_path_for` returns the `new_user_session_url`, just like we asked it to.
4. The page redirects to the `new_user_session_url`.
5. We hit `SessionsController#new`. However, Devise somehow thinks the user is still logged in, and treats them as such, by moving on to 6:
6. `after_sign_in_path_for` gets called. This is the step that we know shouldn't be happening, but we can't figure out how it's getting here. It should never get called, because the user was logged out in step 2 above.

With the `:cookie_store`, if we manually delete the session cookie from the browser and then hit the `#destroy` endpoint, it works. If we use the active_record_store, none of this happens. It behaves as expected.

I've tried reverting to several previous Devise versions to see when it was introduced, but the behaviour is the same all the way back to 3.

If I can provide any more information to help in troubleshooting, please let me know. We've tried stepping into and all the way through the Devise code and nothing is jumping out at us.

**Comment by arvinddoraiswamy** [comment]
Isn't this bad though? Shouldn't this be fixed so cookies are invalidated on the server instead?

1. Log in.
2. Get a _app_session cookie. Copy this cookie.
3. Work
4. Log out
5. Cookie is destroyed in the browser
6. Do NOT log in but replay an old request with the cookie in Step 2
7. I can access the feature and its data

IMO this is *not* good at all. Have I missed something completely? Or is devise still expected to behave this way.

Yes, I know I can write my own stuff and store sessions in the DB or whatever but ideally Devise should handle this seamlessly. :)

**Comment by josevalim** [comment]
No, we cannot handle this. This is the whole trade-off of using cookie-based sessions. They are replayable. Just use another storage if you don't want this behaviour.

**Comment by arvinddoraiswamy** [comment]
Okay thanks :)

**Comment by kinnrot** [comment]
There is no way to make this cookie  invalid when user logs out?

**Comment by josevalim** [comment]
There is, use another session store instead of cookies.

**Comment by jamesfzhang** [comment]
I am experiencing a similar problem, but with session store https://github.com/rails/activerecord-session_store/issues/80

**Comment by fatosmorina** [comment]
I found an [article](https://makandracards.com/makandra/53562-devise-invalidating-all-sessions-for-a-user) demonstrating a solution without having to change the storage:

You can add a session_token column to your devise model (e.g. User) and override Devise #authenticatable_salt method to contain your session token:

```
class User < ApplicationRecord

  devise :database_authenticatable, :recoverable, :rememberable
         
  def authenticatable_salt
    "#{super}#{session_token}"
  end

  def invalidate_all_sessions!
    self.session_token = SecureRandom.hex
  end
  
  ...
end
```
Now you need to invalidate the session cookie by resetting the _session_token_ of a user on logout:

```
class Users::SessionsController < Devise::SessionsController
  
  def destroy
    current_user.invalidate_all_sessions!
    super
  end

end
```
I hope that helps.

**Comment by ueharajohji** [comment]
Hi @fatosmorina , I tried the solution you posted but whenever I log out I still can't go to the login page.

**Comment by GruLab** [comment]
> 
> 
> I found an [article](https://makandracards.com/makandra/53562-devise-invalidating-all-sessions-for-a-user) demonstrating a solution without having to change the storage:
> 
> You can add a session_token column to your devise model (e.g. User) and override Devise #authenticatable_salt method to contain your session token:
> 
> ```
> class User < ApplicationRecord
> 
>   devise :database_authenticatable, :recoverable, :rememberable
>          
>   def authenticatable_salt
>     "#{super}#{session_token}"
>   end
> 
>   def invalidate_all_sessions!
>     self.session_token = SecureRandom.hex
>   end
>   
>   ...
> end
> ```
> 
> Now you need to invalidate the session cookie by resetting the _session_token_ of a user on logout:
> 
> ```
> class Users::SessionsController < Devise::SessionsController
>   
>   def destroy
>     current_user.invalidate_all_sessions!
>     super
>   end
> 
> end
> ```
> 
> I hope that helps.

Added following into "/opt/diaspora/apps/diaspora/htdocs/app/models/user.rb"
class User < ApplicationRecord
devise :database_authenticatable, :recoverable, :rememberable
def authenticatable_salt
"#{super}#{session_token}"
end
def invalidate_all_sessions!
self.update_attribute(:session_token, SecureRandom.hex)
end
end

Added following into "/opt/diaspora/apps/diaspora/htdocs/app/controllers/sessions_controller.rb"
class Users::SessionsController < Devise::SessionsController
def destroy
current_user.invalidate_all_sessions!
super
end
end

Application not working then onward, am I doing right steps?
Kindly suggest.

**Comment by sandipsubedi** [comment]
> I found an article demonstrating a solution without having to change the storage:

> You can add a session_token column to your devise model (e.g. User) and override Devise #authenticatable_salt method to contain your session token:

Anyone had luck with this? For some reason, it's not working for me.

**Comment by ibraheemdev** [comment]
I know this is an old issue, but isn't using a cookie store like this a huge security concern? Why is it still the default?

**Comment by PhilippeChab** [comment]
Maybe I'm wrong, but I don't think this is true. It also depends on what you exactly mean by "logs in".

> `authenticatable_salt` is only used when user logs in and when `rememberable` module refreshes user session.

Devise mainly uses the `authenticate` method in warden [here](https://github.com/wardencommunity/warden/blob/88d2f59adf5d650238c1e93072635196aea432dc/lib/warden/proxy.rb#L109), which proceeds in this order:
- Tries to serialize the user from the session [here](https://github.com/wardencommunity/warden/blob/88d2f59adf5d650238c1e93072635196aea432dc/lib/warden/proxy.rb#L334). This part uses the authenticatable_salt in devise [here](https://github.com/heartcombo/devise/blob/8b0b849a67c46b10827743aa0ccb0679d69e5396/lib/devise/models/authenticatable.rb#L243).
- Performs any candidate strategies to try and sign in the user [here](https://github.com/wardencommunity/warden/blob/88d2f59adf5d650238c1e93072635196aea432dc/lib/warden/proxy.rb#L335).

Am I missing something?
