### ISSUE TITLE
Devise authorize a User and unauthorizes it right after

### ISSUE THREAD

**Issue by oliviermilla** [plataformatec/devise#3059]
Hello, I'm posting here after over 6 hours going circle

I use rails 4.1.1 with Devise 3.2.4 + mongoid@master.

I have a `User` signing in properly:

```
Started POST "/users/sign_in" for 212.194.198.62 at 2014-06-05 15:18:08 +0000
Processing by Devise::SessionsController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"zObTwp85xx+YFcSuY/d4fPcCHp7sDiYvNWlCFjf81gg=", "user"=>{"email"=>"olivier.milla@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}
```

that gets properly redirected to the after_sign_in route:

```
Redirected to http://www.white.eu.com/dashboard
Completed 302 Found in 1220ms
Started GET "/dashboard" for 212.194.198.62 at 2014-06-05 15:18:09 +0000
Processing by DashboardController#index as HTML
```

which unauthorizes the User right after:

```
Completed 401 Unauthorized in 1ms
```

I've tried enabling / disabling each and every devise option. I have no access control gem (`CanCan` and such).

I did not override `Devise#SessionsController`. I removed `protect_from_forgery` from `ApplicationController` to be sure that csrf_token gets not in the way.

`DashboardController` is as simple as it gets:

```
class DashboardController < ApiController
  helper :all
  def index
  end    
end
class ApiController < ApplicationController
    before_filter :authenticate_user!
end
```

The request is plain HTML out of Firefox.

The form is the one generated by devise generator to which I simply added the `:authenticity_token => form_authenticity_token`option (even though `protect_from_forgery` is off).

The layout is a 4 liners:

```
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>
```

and my `User` model is

```
class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :rememberable

## Database authenticatable
  field :email,              :type => String, :default => ''
  field :encrypted_password, :type => String, :default => ''
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time
  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable
  ## Rememberable
  field :remember_created_at, type: Time
  ## Lockable
  field :failed_attempts, :type => Integer, :default => 0
  field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  field :locked_at,       :type => Time
  index({:email => 1}, {:unique => true})
  index({:reset_password_token => 1})
  end
```

`sign_in_count` gets properly incremented every time sign_in redirects.

I run out of options/ideas/strength. 

Any help is much appreciated.

**Comment by gocoolkris** [comment]
@muichkine : you saved me a whole bunch of time.

**Comment by NiteshKaradwall** [comment]
@muichkine , @josevalim 

I am using rails 4.2.6 and devise 3.4.1 and all the remaining things are same, Still can't login after successfully sign in, like after sign in got the "Completed 401 Unauthorized in 1ms" when move to dashboard controller. 

I have "Rails.application.config.session_store :active_record_store, key: 'key_name', domain: :all" setting into session_store.rb file.

What should I do with above file, can you please suggest me something on this. 

Thanks in advance !!

**Comment by marcelamiach** [comment]
@NiteshKaradwall 
Any updates on that? I'm facing the same problem and can't get rid of that

**Comment by abhilashak** [comment]
Thank you so much @muichkine  You saved my Time!
I have exact same issue, and I am using
**Rails 4.2.7.1 & Devise 3.5.10   With MongoDB, MongoId 5.0.2**

Always After login I am getting 

    `ActionController::InvalidAuthenticityToken in SessionsController#create
ActionController::InvalidAuthenticityToken`

and I have 

   `before_filter :authenticate_user!`

this code in my dashboard_controller.rb

And session_store.rb has

`Rails.application.config.session_store :cookie_store, key: '_my_appname', secure: true`

I changed that into

`Rails.application.config.session_store :cookie_store, key: '_my_appname'`

and it works! Great!

**Comment by NielsKSchjoedt** [comment]
I seem to have the exact same problem, however secure: false does not seem to solve it. Any ideas?

**Comment by FikriRNurhidayat** [comment]
Same problem here, so I just succesfully signed in, and after I tried to get my protected endpoint, it returned "Completed 401 Unauthorized", and redirected me to login screen again, so on.

**Comment by NielsKSchjoedt** [comment]
Okay, I think I found out what was going on in my case. It was actually a user behaviour causing this: https://stackoverflow.com/questions/51917046/devise-some-users-on-ios-keeps-getting-signed-out-when-they-leave-the-browser/55277413#55277413
