### ISSUE TITLE
Devise Confirmable token invalid the first time. Maybe double validation issue.

### ISSUE THREAD

**Issue by dfrancisc** [plataformatec/devise#3124]
The first time we create a new user (its hard to say, within a day maybe), once we click on the confirmable link we get an error saying that the token is invalid, but it results that the user its confirmed. So, I supposed, devise is trying to confirm the token twice. It's hard to get  a log, because it just happen sometimes. Does anybody experienced this?

**Comment by branch14** [comment]
We had the same happening and found out that the cause was a `after_create` callback which triggered a subsequent `save`.
