### ISSUE TITLE
Navigating to edit_user_registration_path sometimes logs users out in production

### ISSUE THREAD

**Issue by jurre** [plataformatec/devise#3138]
So I'm breaking my head trying to figure this out: When users navigate to the `edit_user_registration_path` they sometimes are signed out. This only happens in production (we're running on heroku with 2 dyno's currently, I've tried scaling back to one but that didn't help). We're using subdomains for multi tenancy and using SSL on production. In development this has never happened and specs checking this are also passing.

We're on `Rails 4.1.4`, `Devise 3.2.4` and `Warden 1.2.3`

Our app is open source, the repo is over at https://github.com/DefactoSoftware/Hours but some small snippets of things we've customized:

```ruby
    devise_for :users, :controllers => { registrations: "users/registrations" }
```
```ruby
class Users::RegistrationsController < Devise::RegistrationsController

  def destroy
    redirect_to root_url
  end

  protected

  def build_resource(hash=nil)
    user = super(hash)
    user.organization = current_account
  end
end
```

```erb
<div class="outer">
  <div class="container">
    <h2> <%= t('registration.edit', resource_name: resource.class.model_name.human) %></h2>
    <%= gravatar_image_tag(resource.email, gravatar: { secure: true }, class: "image-circle", title: resource.full_name) %>
    <p><%= t("registration.gravatar_instructions_html") %></p>
    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs edit-user">
        <%= f.input :email, required: true, autofocus: true %>

        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <p><%= t('registration.pending_information', unconfirmed_email: resource.unconfirmed_email) %></p>
        <% end %>

        <%= f.input :password, autocomplete: "off", hint: t('registration.hint.blank'),required: false %>
        <%= f.input :password_confirmation, required: false %>
        <%= f.input :current_password, hint: t('registration.hint.current_password'), required: true %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, t('registration.update_button') %>
      </div>
    <% end %>
    <%= link_to t('back'), :back %>
  </div>
</div>
```

I've tried searching for people with similar issues but I couldn't find anyone having issues with just opening `edit_user_registration_path`.

The issue on our repo is here:
https://github.com/DefactoSoftware/Hours/issues/139

Hope anyone can point me in the right direction, thanks!

**Comment by josevalim** [comment]
Are there any news here? We were unable to reproduce the issue. :(

**Comment by jurre** [comment]
This isn't an issue for us anymore (since we've rewritten those pages) and if it's only happening to us it has to be something specific to our setup (maybe something to do with multi tenancy or subdomains?). I'd say let's close this for now. Thanks for your help!
