### ISSUE TITLE
recall method is not being called in warden.authenticate!

### ISSUE THREAD

**Issue by lcguida** [plataformatec/devise#3142]
Hi, 

I searched around, posted in stackoverflow, but I got no solution so far. 

I'm trying to give a custom json response in case of failed login. I want the json to be in this format:

```
{success: false, errors: [<error_message>]}
```

So I overrode the SessionsContoller, as following:

``` ruby
class SessionsController < Devise::SessionsController
  respond_to :json

  def create 
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    render json: { :success => true }, status: 200
  end

  def failure   
    warden.custom_failure!
    render json: { success: false, errors: ["Login Credentials Failed"] }, status: 401
  end

  protected
  def auth_options
    {:scope => resource_name, :recall => "#{controller_path}#failure"}
  end
end
```

routes.rb:

``` ruby
devise_for :users, controllers: {sessions: 'sessions'}
```

devise.rb:

``` ruby
config.navigational_formats = ["*/*", :html, :json]
```

Login is working just fine, I'm just not being able to override the failure response. I'm just posting this here to check if it's not a bug, since this same code is presented in various blog posts in the internet.

**Comment by reconstructions** [comment]
Wow, looking at the Devise `session_controller.rb` I can see why skinny controller/fat model is so important.  The Rails 4 (or even Rails 3) way, it should be question of specifying a format and you're done.  All this logic should be in the model.  That it is so hard to override this controller to implement AJAX login (which should be standard Devise by now in any case) shows why.  Scary to consider that overriding the other controllers to get AJAX in the rest of the framework will probably be just as hard...
