### ISSUE TITLE
Remember me confusion

### ISSUE THREAD

**Issue by jonathanng** [plataformatec/devise#3150]
There seems to be some confusion on how to get remember me working with Omniauth.

According to this [wiki](https://github.com/plataformatec/devise/wiki/Omniauthable,-sign-out-action-and-rememberable), you need to have the following in your OmniauthCallbacksController:

```
remember_me(user)
```

On the other hand, according to this [issue](https://github.com/plataformatec/devise/issues/776), you just need to do this:

```
user.remember_me = true
```

In addition, making remember_me default to true according to [this](http://dev.mensfeld.pl/2013/12/rails-devise-and-remember_me-rememberable-by-default/), you just need to add the following to your User.rb

```
def remember_me
  true
end
```

Not sure which one is the official answer, and all three doesn't work for me. It only works for Chrome on Mac, but doesn't for Firefox Mac & Chrome Windows. Not sure what is going on.

My code looks like this:

```
# -*- encoding : utf-8 -*-
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

    include Devise::Controllers::Rememberable

    def all
        omniauth = request.env["omniauth.auth"]
        auth = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
        if auth

            auth.update_with_omniauth omniauth
            auth.save!

            # ???
            remember_me auth.user
            auth.user.remember_me = true

            if user_signed_in?
                redirect_back_or settings_path(current_user)
            else
                sign_in_and_redirect auth.user, event: :authentication
            end
        else
            if user_signed_in?
                current_user.build_auth(omniauth).save!
                redirect_back_or settings_path(current_user)
            else
                session["devise.omniauth"] = omniauth.except('extra')
                redirect_to new_user_registration_url
            end
        end
    end

    alias_method :facebook, :all
    alias_method :twitter, :all

end
```

**Comment by anpa** [comment]
I have the same issue as @taddgiles and @krnjn.

I noticed that the cookie is created when signing up with omni-auth but it disappears when closing/opening the browser.

So far, I solved this problem by setting `config.expire_all_remember_me_on_sign_out = false`, but I get the feeling that this is not a good practice/solution (although everything works fine: both login and logout).

Is there any other way to do this?

**Comment by krzcho** [comment]
it works for me but I do have remember_token in model's table

**Comment by agorf** [comment]
I had issues with this as well. It turns out I was blindly setting the secure flag, which means the cookie is not available in development. The solution was to edit `config/initializers/devise.rb`, changing `config.rememberable_options = { secure: true }` to `config.rememberable_options = { secure: Rails.env.production? }` After that, it's working like a charm. I only used `remember_me(@user)` in my OmniAuth callbacks controller. No remember token is needed.

**Comment by Rabin-Kalikote** [comment]
> I had issues with this as well. It turns out I was blindly setting the secure flag, which means the cookie is not available in development. The solution was to edit `config/initializers/devise.rb`, changing `config.rememberable_options = { secure: true }` to `config.rememberable_options = { secure: Rails.env.production? }` After that, it's working like a charm. I only used `remember_me(@user)` in my OmniAuth callbacks controller. No remember token is needed.

**It raises the following error without remember token.**
"authenticatable_salt returned nil for the User model. In order to use rememberable, you must ensure a password is always set or have a remember_token column in your model or implement your own rememberable_value in the model with custom logic."
