### ISSUE TITLE
devise_for don't work with rails 4.2

### ISSUE THREAD

**Issue by Fudoshiki** [plataformatec/devise#3151]
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/devise-6e95b66b5446/lib/devise/rails/routes.rb:457:in `ensure in with_devise_exclusive_scope': undefined method`merge!' for #ActionDispatch::Routing::Mapper::Scope:0x00000003fedaf0 (NoMethodError)

rails 4.2, mongoid 4, devise 3.3 && master branch

**Comment by tonyobiora** [comment]
i am new to ruby and going through a tutorial adding devise was used for the login and it seems like it doesn't work with the version of rails am running 4.2.x if i change the devise_for command in routes.rb to resources it works but does not update my db wen i run db migrate. i need help to go pass this stage . thanks
