### ISSUE TITLE
Issue with Rails 4.2 (beta)

### ISSUE THREAD

**Issue by trinode** [plataformatec/devise#3159]
Hi there,

I'm not sure what has changed / will be changing in 4.2 but it looks like merge! is no longer available on some objects:-

if I have 
devise_for :users
I get the following errors:-

```
NoMethodError: undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x000000062cded0>
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `ensure in with_devise_exclusive_scope'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `with_devise_exclusive_scope'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:248:in `block (2 levels) in devise_for'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:351:in `block in devise_scope'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:932:in `block in constraints'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:808:in `scope'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/mapper.rb:932:in `constraints'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:350:in `devise_scope'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:247:in `block in devise_for'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `devise_for'
```

**Comment by nextbase** [comment]
Still doesn't work for me.

**Comment by jaythaceo** [comment]
Add this to gem file instead. run bundle install, rake db:migrate.. worked for me
 " USE IN PRODUCTION at OWN RISK"
gem 'devise', :git => 'https://github.com/plataformatec/devise.git', :branch => 'lm-rails-4-2'

**Comment by rafaelfranca** [comment]
@jaythaceo or you can just use  devise 3.4.1

**Comment by jaythaceo** [comment]
Thanks a lot

**Comment by tunsmart** [comment]
wow, thanks @rafaelfranca , 3.4.1 worked perfectly

**Comment by amritdeep** [comment]
Thanks Guys, It help me lot. Devise 3.4.1 work perfectly for rails 4.2.5.2.

**Comment by swzensar8** [comment]
Hi All, has any one deleted "lm-rails-4-2" this branch from devise gem?.
Because I am using " gem 'devise', :git => 'https://github.com/plataformatec/devise.git', :branch => 'lm-rails-4-2' " devise from this branch and its giving me this error "  Revision lm-rails-4-2 does not exist in the repository https://github.com/plataformatec/devise.git. Maybe you misspelled it? "
If removed please tell me how to use devise with Rails-4.2.8 and Ruby-2.3.3
Thanks in advance.
