### ISSUE TITLE
Add responders gem as a dependency in Rails 4.2

### ISSUE THREAD

**Issue by Sjors** [plataformatec/devise#3160]
The following error message, when trying `/users/sign_up` had me confused for a while:

`ActionController::RoutingError (undefined local variable or method `mimes_for_respond_to' for DeviseController:Class):` 

This went away as soon as I added the [responders](https://github.com/plataformatec/responders) gem.

**Comment by archonic** [comment]
@chulkilee another :+1:

**Comment by Muzzja** [comment]
@chulkilee thx

**Comment by dinglixiang** [comment]
@chulkilee  thanks

**Comment by raphaelduartepinheiro** [comment]
@chulkilee solutions didn't worked for me.

I needed to include de MimeResponds in ApplicationController

    class ApplicationController < ActionController::API
      include ActionController::MimeResponds
    end

**Comment by mabdelfattah** [comment]
@raphaelduartepinheiro  I'm using rails-api gem and your solution worked with me.

**Comment by zmwuqi** [comment]
@chulkilee +1
