### ISSUE TITLE
authenticate_user!  filter doesn't redirect to sign-in with locale parameter

### ISSUE THREAD

**Issue by ghost** [plataformatec/devise#3161]
when trying to reach a protected url, with a locale parameter like /backoffice/devices?locale=fr
the user is redirected to the signin page BUT the requested  locale parameter ("fr") seems to be lost ( or not having precedence)as the signin form is still in the default language (:en)

should I insert another filter to set the locale with the locale param ??

Started GET "/backoffice/devices?locale=fr" for 127.0.0.1 at 2014-08-20 17:50:47 +0200
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT `schema_migrations`.\* FROM `schema_migrations`
Processing by Backoffice::DevicesController#index as HTML
  Parameters: {"locale"=>"fr"}
Completed 401 Unauthorized in 996ms

Started GET "/users/sign_in" for 127.0.0.1 at 2014-08-20 17:50:49 +0200
Processing by Users::SessionsController#new as HTML
  Rendered devise/shared/_links.haml (4.8ms)
  Rendered devise/sessions/new.html.haml within layouts/application (236.0ms)
  Rendered layouts/_head.html.haml (176.1ms)
  Rendered layouts/_navbar.html.haml (15.4ms)
  Rendered shared/_flash_messages.html.erb (0.7ms)
  Rendered layouts/_footer.html.haml (15.6ms)
Completed 200 OK in 933ms (Views: 876.7ms | ActiveRecord: 17.4ms)

**Comment by monxela** [comment]
Try saving the current locale in session

```
# ApplicationController

before_action :set_locale

def set_locale
  I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
  session[:locale] = I18n.locale
end

def default_url_options(options = {})
  { locale: I18n.locale }.merge options
end
```
