### ISSUE TITLE
Can't verify CSRF Token authenticity - 422 Unprocessable Entity

### ISSUE THREAD

**Issue by wolvz** [plataformatec/devise#3200]
Hello,

I'm working on a project that consists of a client side angularjs app and server side rails app.
The users need to authenticate to access the app contents, so I chose devise to deal with the authentication.
I followed the installation instructions on github's readme, and I think everything is set up properly.
In my angularjs app login function i do $http.post('/users/sign_in.json', { "email": 'test@test.com', "password": '987654321'}) and i get
POST http://localhost:3000/users/sign_in.json 422  (Unprocessable Entity). 

On the server side, I get this error message:

Started POST "/users/sign_in.json" for 127.0.0.1 at 2014-09-09 17:30:18 +0100
Processing by Devise::SessionsController#create as JSON
  Parameters: {"email"=>"test@test.com", "password"=>"[FILTERED]", "session"=>{"
email"=>"test@test.com", "password"=>"[FILTERED]"}}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms

I also tried with CURL and i get the same error messages.

Can you guys please help me? I'm stuck with this for almost 3 days... I can't find a working solution anywhere... I think I tried everything!

**Comment by fullofcaffeine** [comment]
To further documents my findings, I had a similar issue with `ember-cli` and didn't find an obvious answer. This post helped me: https://www.adibsaad.com/blog/setting-up-ember-cli-with-a-rails-back-end-and-token-authentication-authorization
