### ISSUE TITLE
wrong error message in case of custom authentication_keys

### ISSUE THREAD

**Issue by timoschilling** [plataformatec/devise#3201]
Setup:

``` ruby
Devise.setup do |config|
  config.authentication_keys = [ :username ]
end
```

Bug:
If the user types in wrong credentials, devise shows the I18n key `'devise.failure.invalid' => 'Invalid email or password.'`. It should be `Invalid credentials.` or `Invalid username and password.`

**Comment by alexkravets** [comment]
This seems to be close but there is a scenario when it doesn't work:

1. In ```devise.rb```: ```config.authentication_keys = [ :username ]```
2. In second auth model ```Admin``` (the first one is ```User```): ```devise :database_authenticatable, :rememberable, :trackable, :authentication_keys => [ :email ]```

So when admin fails to login, the error message says: ```Invalid username or password.``` — while ```email``` should be used instead of ```username```.

**Comment by timoschilling** [comment]
Yes, @carlosantoniodasilva found already found that problem in https://github.com/plataformatec/devise/pull/3218#discussion_r17965071. But I don't have the time to work on that.
