### ISSUE TITLE
redirects from api domain to sign-in domain and back to api domain

### ISSUE THREAD

**Issue by mreinsch** [plataformatec/devise#3226]
We're using different domains for our API and web UI. For the API we're using the doorkeeper gem. So an external app will redirect users to /oauth/authorize on the API domain for authentication.

Thanks to a change in 3.3.0, users who aren't logged in will get redirected to the correct URL on the web UI domain. But after login, they get redirected to the /oauth/authorize URL on the web UI domain instead of the API domain.

This is because store_location (https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/store_location.rb#L38) only stores the the relative path and query params, not the complete URL, probably as an optimisation? Could this be changed to store the complete URL instead? I'd send you a pull request if that's OK.

**Comment by josevalim** [comment]
We should only store paths because storing URLs is vulnerable to attacks. In case you want to store URLs, go ahead, but you will need to validate them.
