### ISSUE TITLE
after_database_authentication callback doesn't fire after sign in via Forget Password

### ISSUE THREAD

**Issue by bogdanovich** [plataformatec/devise#3240]
Devise 3.3.0
Warden 1.2.3
Rails 4.1.6

When I change password via Forget Password i get signed in automatically, but after_database_authentication doesn't fire. This issue makes impossible to use this callback for after sign in initializations

**Comment by reedloden** [comment]
`after_password_reset` is deprecated now, for some reason?

https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/models/recoverable.rb#L48
