### ISSUE TITLE
Update_with_password deletes associated objects

### ISSUE THREAD

**Issue by plamena** [plataformatec/devise#3245]
Rails: 4.1.4  Devise: 3.4.0  Warden: 1.2.3
Hello.
I have a  model User which is similiar to:

class User < ActiveRecord::Base
  has_one :profile,     inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :profile
  validate :profile, presence: true
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

The edit form updates the user and the profile at the same time. I noticed that when the update fails (blank current password or invalid profile inputs) and I leave the edit page, the profile is deleted. I found that the problem is from the method update_with_password (update_without_password works fine). After removing these two lines everything works Ok again:
self.assign_attributes(params, *options)
self.valid?

**Comment by josevalim** [comment]
Closing as it looks like a bug in Rails.
