### ISSUE TITLE
  NoMethodError: undefined method `to_i' - Devise Model

### ISSUE THREAD

**Issue by mzaragoza** [plataformatec/devise#3249]
https://github.com/michaeldv/awesome_print/issues/165

Throwing this error in rails c when I try to look up a devise model. Is there a way around this?

User.all # works as intended
User.last # NoMethodError: undefined method `to_i'

**Comment by miamiruby** [comment]
basically awesome print cannot handle inet fields.... hi moe!

**Comment by maurogeorge** [comment]
@asharma-ror as @miamiruby this was a bug on the awesome_print, this was fixed on the 1.6.0 if you guys got any issue please post here https://github.com/michaeldv/awesome_print/issues/165
