### ISSUE TITLE
Stuck in vile loop when user tries to confirm / verify email address - Going Crazy! Please Help.

### ISSUE THREAD

**Issue by lsinspired** [plataformatec/devise#3271]
I'm an owner of a web app - not the developer - so please bear with me and excuse my ignorance if you can. The web app with which I'm having problems with that uses Devise is at www.equibbly.com . It's Rails 4.0.9 and Devise 3.2.4

Please see screenshot attached.  My developer (the second developer trying to find a solution) is having difficulties figuring out how to configure devise correctly to avoid the problems we keep having with email verification, showing a successful verification message, and then being able to log in afterwards. 

Before my developer made a change - that has not been deployed-  whenever someone signed up for an account on my site, they had/have a couple days to verify their email. If they signed out of their account first and then clicked on the link in the email verification, they were being given a successful verification flash message, take to the sign in page, and shown a message that they have to sign in. When they tried to sign in, they were taken to the page attached  -  the 'resend confirmation' page - 'confirmation token doesn't exist' message on (because they had already used the confirmation token and they can't use it twice).  When they clicked on the "sign in" or "sign up" or "forget your password?" or "didn't receive unlock instructions" links below the error message, it was just redirecting back to the confirmation page with an error message that the token had already been used.  And there was no way to get back to the sign in page - they got stuck in a loop. 

My developer thought it was a result of my app always taking the user to the page they were looking at before they logged in. So it was getting stuck in a loop since they were on the confirmation page before being taken to the sign in page and when it failed to sign the user in, taking them to the 'resend confirmation instructions' page where clicking the sign in just basically reloaded the page.

He changed the following in the file app/controllers/confirmations_controller.rb, so instead of:

def after_confirmation_path_for(resource_name, resource)
     if current_user
         dashboard_path
     else
        new_session_path(resource_name)
     end

He now has:

def after_confirmation_path_for(resource_name, resource)
	dashboard_path
end

But now there is no flash "successful verification" message being given - the only message shown is on the sign-in page  in red and says "you must sign in to continue" (if there were also a successful verification message here in green, there would be less likelhood of the user thinking it didn't verify). And if the user thinks that verification didn't work, because there is no successful verification message, and then tries to click on the verification link again in the email, it takes them to the "resend confirmation instructions" page with an error message that the token no longer exists and they should resend it or log in because it might have been confirmed already. When the user tries to click on the "sign in" link below the message, it just redirects to the same page they're already on. Stuck in the same loop as noted above. So they cannot log in.

Could you please suggest a way to fix this so if a person is not logged into their account when they click the verification link, they see a success message and then they can sign in to their account without getting stuck in a loop?

I would appreciate any help as this has been a problem for a long time and I'm running out of options.

Thank you in advance to any who can figure this nightmare out,

Lance 

![screen shot 2014-10-22 at 5 42 05 pm](https://cloud.githubusercontent.com/assets/1523912/4754942/c6345f6c-5ac1-11e4-989a-b85154dda136.png)

**Comment by josevalim** [comment]
Thank you @M7! This does not seem to be a Devise issue but an application issue, so I am closing it!

**Comment by M7** [comment]
No problem @josevalim. Would've liked to see this fixed, but hopefully it was resolved on their side.
