### ISSUE TITLE
Possible confusion in the docs

### ISSUE THREAD

**Issue by clozach** [plataformatec/devise#3283]
Quick aside: I'm not quite at a comfort level where I can make changes to the wiki docs without fear that I'm doing something wrong...otherwise I'd just fix this without adding noise to the Issues list.

**tl;dr** - The first sentence on this page makes it unclear which of two documents should be followed in setting up gradual engagement: https://github.com/plataformatec/devise/wiki/How-To:-Email-only-sign-up/_history#

Points of confusion:

* The [first how-to](https://github.com/plataformatec/devise/wiki/How-To:-Email-only-sign-up/_history#) and the [second how-to](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation) seem to overlap. It's unclear in reading them which one should be followed, and why.
* The words, "For Rails 4, check..." in the [first how-to](https://github.com/plataformatec/devise/wiki/How-To:-Email-only-sign-up/_history#) seem to imply that the only difference is that one doc is for Rails 2/3, and that the other is for Rails 4. However, both pages include instructions for all versions of Rails+Devise.

Again, I'd fix it if I could be sure what the right fix *is*, but I don't. Cheers. :)

**Comment by josevalim** [comment]
Unfortunately we don't have a lot of time to put into the wiki, leaving it up to the community, so thank you for looking into it. Can we please advise you to ask into the mailing list instead and ask for feedback? Thanks!

**Comment by clozach** [comment]
Ah, wish I could, but I've moved back into iOS development and don't even remember what this was about anymore. Thanks for your work on devise, though...it's an excellent project!
Best. -C
