### ISSUE TITLE
Keep getting " NoMethodError in Admin::WelcomeController#index undefined method `authenticate_admin!' for #<Admin::WelcomeController:0x47bb228>"

### ISSUE THREAD

**Issue by bajalovic** [plataformatec/devise#3291]
I just started a new project and I have this problem with Devise. The odd thing is that it works for a while and then just brakes and I keep getting this error. What is the problem?!

I am using Ruby 2.1.4 and rails 4.1.6.
Devise version: 3.4.1

**Comment by kalyansagar** [comment]
create a new file  will_paginate in # config /initializers /will_paginate .rb
add dis code into the will_paginate.rb 

if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        alias_method :per, :per_page
        alias_method :num_pages, :total_pages
      end
    end
  end
end

module ActiveRecord
  class Relation
    alias_method :total_count, :count
  end
end

restart the server   .......its work

**Comment by kalyansagar** [comment]
(OR) add code in will_paginate.rb   

 if defined?(WillPaginate)
   ActiveSupport.on_load :active_record do
     module WillPaginate
       module ActiveRecord
         module RelationMethods
           def per(value = nil) per_page(value) end
           def total_count() count end
         end
       end
       module CollectionMethods
         alias_method :num_pages, :total_pages
       end
     end
   end
 end

dis code also will works

**Comment by prat11** [comment]
thank you

**Comment by saydulk** [comment]
I added that code into will_paginate.rb file still not work 
![Screenshot from 2019-05-06 02-58-52](https://user-images.githubusercontent.com/1058663/57200211-e6dedf00-6faa-11e9-948e-7af622178456.png)


![Screenshot from 2019-05-06 02-58-17](https://user-images.githubusercontent.com/1058663/57200207-cf9ff180-6faa-11e9-8b7b-2bf78cea3354.png)
