### ISSUE TITLE
Add config option for length of token

### ISSUE THREAD

**Issue by bikezilla** [plataformatec/devise#3305]
Hi!
In the [```friendly_token```](https://github.com/plataformatec/devise/blob/8e5c098e3aa53d6a72faadd8b929abaf2bb6d496/lib/devise.rb#L478) method definition I see a hard coded 15 byte token length option which results in 20 chars raw tokens.

My client's use case is that many of his users use e-mail on a mobile device only, so they might need to enter their tokens in the desktop/laptop browser (e.g. confirmation tokens) by hand, so he wants shorter tokens. 

I achieved that by overriding the ```friendly_token``` method, but thought it might make sense to contribute to the project by adding a new config option for the token length.

1. Is this a good idea, would it be accepted by the project maintainers? If yes I'm happy to sign myself up for this.
2. Is ```token_size``` a good name for the option (with a proper comment that it is actually bites, not chars)? Suggestions for better?

Thanks for your feedback!

**Comment by josevalim** [comment]
You can simply monkey patch friendly_token. :)
