### ISSUE TITLE
Failing redirects after requesting password recovery token and changing password

### ISSUE THREAD

**Issue by cschoene** [plataformatec/devise#3306]
I recently upgraded from Rails 3.2 and I am using attribute_accessible. I did not override the passwords controller in my app - only the form POSTing the email address.  

Errors occur when 
1) I request a password reset token (after successfully sending the email with the token) 
2) I update the password with the generated token (after successfully updating the password)

Any ideas what might be causing this ?

----------------------------------------------------------------------------------------------------------------------
1) I request a password reset token (after successfully sending the email with the token) 
----------------------------------------------------------------------------------------------------------------------
NoMethodError - protected method `redirect_to' called for #<Devise::PasswordsController:0x007fe9f2b420b0>:
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:140:in `redirect_to'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:198:in `navigation_behavior'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:167:in `rescue in to_html'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:165:in `to_html'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:158:in `respond'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:151:in `call'
  actionpack (4.1.7) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
  devise (3.4.1) app/controllers/devise/passwords_controller.rb:17:in `create'
  actionpack (4.1.7) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.7) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.7) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.7) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.7) lib/action_dispatch/routing/mapper.rb:45:in `call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:678:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.7) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.7) lib/rails/engine.rb:514:in `call'
  railties (4.1.7) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  faye-websocket (0.7.5) lib/faye/adapters/thin.rb:40:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  faye-websocket (0.7.5) lib/faye/adapters/thin.rb:44:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.7) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.7) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `<main>'

-------------------------------------------------------------------------------------------------------------------
2) after updating the password with the generated token:
-------------------------------------------------------------------------------------------------------------------
NoMethodError - protected method `redirect_to' called for #<Devise::PasswordsController:0x007fe9f28810d8>:
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:140:in `redirect_to'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:198:in `navigation_behavior'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:167:in `rescue in to_html'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:165:in `to_html'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:158:in `respond'
  actionpack (4.1.7) lib/action_controller/metal/responder.rb:151:in `call'
  actionpack (4.1.7) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
  devise (3.4.1) app/controllers/devise/passwords_controller.rb:39:in `update'
  actionpack (4.1.7) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.7) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.7) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.7) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.7) lib/action_dispatch/routing/mapper.rb:45:in `call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:678:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.7) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.7) lib/rails/engine.rb:514:in `call'
  railties (4.1.7) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  faye-websocket (0.7.5) lib/faye/adapters/thin.rb:40:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  faye-websocket (0.7.5) lib/faye/adapters/thin.rb:44:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.7) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.7) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `<main>'

**Comment by deependersingla** [comment]
@josevalim  Any update? similar issue:
NoMethodError: protected method `redirect_to' called for #<Api::V1::UserSessionsController:0x007fec43e0d2b0>
from /Users/deependersingla/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/actionpack-4.1.0/lib/action_controller/metal/responder.rb:140:in `redirect_to'

**Comment by josevalim** [comment]
Can you please reproduce this issue in a new application? Because I can't locally. I think some external gem that you are using is making `redirect_to` become a private method.

**Comment by deependersingla** [comment]
@josevalim The applications which I am working is using rails_api gem (rather than full rails) and the gem which started giving this problem is rails admin and also with active admin, same issue.

Not sure if reproduction will be easy, But I will definitely give try. 

Just wondering Is there any faster for way for me to check if some external gem is making the method private , I can remove gem one by one and check? Will document it here, if issue resolved some other people can take lead in future.

thanks

**Comment by josevalim** [comment]
You can do this:

     # Check if it is public, private or what not
     Api::V1::UserSessionsController.public_instance_methods.include?(:redirect_to)
     Api::V1::UserSessionsController.protected_instance_methods.include?(:redirect_to)
     Api::V1::UserSessionsController.private_instance_methods.include?(:redirect_to)

     # Try to find its location
     Api::V1::UserSessionsController.instance_method(:redirect_to).source_location

If that doesn't work, checking the source should do it!

**Comment by deependersingla** [comment]
@josevalim 

Works, I made the method public in this file:
2.0.0-p451/lib/ruby/gems/2.0.0/gems/actionpack-4.1.0/lib/action_controller/metal/flash.rb

Any specific reason for this not working, it hasn't changed in recent past:
https://github.com/rails/rails/commits/master/actionpack/lib/action_controller/metal/flash.rb

So why this error suddenly? I am just curious this might break something in future.

**Comment by josevalim** [comment]
Nice, thanks!

> So why this error suddenly? I am just curious this might break something in future.

I am not sure. If we have a way to reproduce the issue, I can take a further look. :)

**Comment by deependersingla** [comment]
@josevalim  thanks, I will also give it a try on coming weekend.
