### ISSUE TITLE
Devise::Mapping::find_scope! should support resource wrappers

### ISSUE THREAD

**Issue by scottjacobsen** [plataformatec/devise#3307]
`Devise::Mapping::find_scope!` will only work if the resource object is an instance of or a child of the class specified in a `devise_for` block.

I have a situation where my resource is a decorator of the User class - something like this:

```ruby
class NewUser < DelegateClass(User)
  # validations that only apply to a new user
end
```
`find_scope!(new_user)` raises an exception because new_user is not an instance of User.

`find_scope` could be made to support wrappers with a simple change. It could test if the passed in object responds to `devise_scope` and if so use that value as the key to find the scope:

```ruby
def self.find_scope!(obj)
  obj = obj.devise_scope if obj.respond_to?(:devise_scope)
  case obj
  when String, Symbol
    return obj.to_sym
  when Class
     Devise.mappings.each_value { |m| return m.name if obj <= m.to }
  else
    Devise.mappings.each_value { |m| return m.name if obj.is_a?(m.to) }
  end
  raise "Could not find a valid mapping for #{obj.inspect}"
end
```

`NewUser` could implement `devise_scope` as:

```ruby
def devise_scope
  :user
end
```

**Comment by josevalim** [comment]
@scottjacobsen this would be a good change. A pull request is welcome!
