### ISSUE TITLE
run rake assets:precompile without db connection

### ISSUE THREAD

**Issue by sahilsk** [plataformatec/devise#3327]
Hi,

First, thank a billion for writing such a awesome gem. I really like it.

Now here goes my problem statement:

I"m trying to precompile my assets to create docker image file. Image building process is on the server that doesn't have access to the database.
It used to work fine before adding devise gem. I see some post on google saying devise initialize and required db connection in precompile task.
Could you please let me know how to avoid this devise init during precompile assets rake task run?

I am on rails 4. So, solution given on net to set ` config.assets.initialize_on_precompile = false` didn't work for me.

Here is the error i gets:

``` ruby
E:\SONU_WKSPC\Projects\xyz\xyz-manager_app\xyz-manager>rake assets:precompile
rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'stackmanager_production'Run `$ bin/rake db:create db:migrate` to create your database
E:/SONU_WKSPC/Projects/xyz/xyz-manager_app/xyz-manager/app/models/user.rb:21:in `<class:User>'
E:/SONU_WKSPC/Projects/xyz/xyz-manager_app/xyz-manager/app/models/user.rb:18:in `<top (required)>'
E:/SONU_WKSPC/Projects/xyz/xyz-manager_app/xyz-manager/config/routes.rb:2:in `block in <top (required)>'
E:/SONU_WKSPC/Projects/xyz/xyz-manager_app/xyz-manager/config/routes.rb:1:in `<top (required)>'
C:in `execute_if_updated'
E:/SONU_WKSPC/Projects/xyz/xyz-manager_app/xyz-manager/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)

```

looking forward to hearing from you soon.

**Comment by josevalim** [comment]
Thanks @rubyrider! Your help is really appreciated!
