### ISSUE TITLE
Two password reset emails being sent (custom PasswordsController)

### ISSUE THREAD

**Issue by davidcpell** [plataformatec/devise#3329]
I'm having an issue in production where users are requesting pw resets and getting two emails instead of one. It has caused confusion because each time at least one of the pw reset tokens conveyed in the multiple emails is of course invalid and users who don't realize that more than one was sent and try the wrong one get an `invalid token` error when trying to use the link in the email.

I customized the Devise::PasswordsController to respond both to a normal html request as well as an Ajax request for use on a different login form that I didn't want the user to be redirected away from. I'm assuming this customization introduced the problem but I have been reviewing my code and it isn't clear to me what I would've done to cause this behavior. 

Here are my server logs from a normal HTML request that is generating two emails: 

```
Started POST "/users/password" for 174.xx.xx.xxx at 2014-11-20 20:18:46 -0500
Processing by PasswordsController#create as HTML
Parameters: {"utf8"=>"✓",  "authenticity_token"=>"grk1shn96l4fHhKxzhuVDmala4FYbMhHRjrESTxdhZg=", "user"=>{"email"=>"me@gmail.com"}, "commit"=>"Send me reset password instructions"}

Rendered users/mailer/reset_password_instructions.html.haml (0.4ms)
Sent mail to me@gmail.com (5586.8ms)
Rendered users/mailer/reset_password_instructions.html.haml (0.4ms)
Sent mail to me@gmail.com (342.2ms)
Redirected to http://myapp.com/users/sign_in`
```

As you can see, two emails were sent before the redirect took place. Now here is a log from when I made the pw reset request as JS from the other form:

```
Started POST "/users/password" for 174.xx.xx.xxx at 2014-11-20 20:33:10 -0500
Processing by PasswordsController#create as JS
Parameters: {"utf8"=>"✓",   "authenticity_token"=>"PASKZu73jiKs7+9NpNZLLL8W63vBOmsq36FRWFn4hVE=", "user"=>    {"email"=>"me@gmail.com"}, "commit"=>"Email reset instructions"}

Rendered users/mailer/reset_password_instructions.html.haml (0.3ms)
Sent mail to me@gmail.com (6673.2ms)
Rendered passwords/new_job_pw_reset.js.erb (0.3ms)`
```

With the JS request, only one pw reset email was generated. Here is my controller:

```
class PasswordsController < Devise::PasswordsController
def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    respond_to do |format|
        if successfully_sent?(resource)
            format.js   { render template: "passwords/new_job_pw_reset" } 
            format.html { super }
        else
            format.js { render template: "passwords/new_job_pw_reset_fail" } 
            format.html { super }
        end
    end
end
end
```

I used the standard controller here at Devise's GitHub as a template. The part I changed is everything after the line `yield resource if block_given?`.

Can anyone help me figure out what I've done here that causes two emails to be sent from an HTML request?

Rails 3.2.18
Devise 3.2.4

**Comment by pritycdn** [comment]
I am also facing same problem.
Here is my PasswordsController.
class PasswordsController< Devise::PasswordsController
	layout 'admin_dashboard'

	respond_to :json, only: [:create]
	prepend_before_filter :require_no_authentication
	# Render the #edit only if coming from a reset password email link
	append_before_filter :assert_reset_token_passed, only: :edit
	# GET /resource/password/new
	def new
		self.resource = resource_class.new
	end
	# POST /resource/password
	def create
		user = resource_class.where(resource_params).first
	 	if user
	 		data = { status: 200, email: user.email}
	 		resource_class.send_reset_password_instructions(user)
	 		render json: data
		else
			data = { status: 400,errors: "Email not found"}
			render json: data	
		end
	end
	# # GET /resource/password/edit?reset_password_token=abcdef
	def edit
		self.resource = resource_class.new
		set_minimum_password_length
		resource.reset_password_token = params[:reset_password_token]
	end
	# # PUT /resource/password
	def update
		self.resource = resource_class.reset_password_by_token(resource_params)
		yield resource if block_given?
		if resource.errors.empty?
			if Devise.sign_in_after_reset_password
				flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
				set_flash_message(:notice, flash_message) if is_flashing_format?
				sign_in(resource_name, resource)
			else
				set_flash_message(:notice, :updated_not_active) if is_flashing_format?
			end
			respond_with resource, location: bvadmin_dashboard_path
		else
			respond_with resource
		end
	end

	protected

	def after_resetting_password_path_for(resource)
		Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_admin_session_path(resource_name)
	end
	# # The path used after sending reset password instructions

	# def after_sending_reset_password_instructions_path_for(resource_name)
	# 	admin_session_path(resource_name) if is_navigational_format?
	# end

	# # Check if a reset_password_token is provided in the request
	def assert_reset_token_passed
		if params[:reset_password_token].blank?
		set_flash_message(:alert, :no_token)
		redirect_to new_admin_session_path(resource_name)
		end
	end

	def translation_scope
	'devise.passwords'
	end

	def resource_params
		params.require(:user).permit(:email,:reset_password_token, :password, :password_confirmation)
	end
end
