### ISSUE TITLE
Sessions#destroy doesnt work properly with Rspec+Capybara

### ISSUE THREAD

**Issue by pluff** [plataformatec/devise#3339]
Hello everyone. After upgrading to latest devise version I've issues a problem with some integration tests.
Here is my simplified test code
```ruby
  user  = FactoryGirl.create :user
  visit new_user_session_path
  within("form#new_user") do
    fill_in 'user_email', with: user.email
    fill_in 'user_password', with: user.password
  end
  click_button 'Sign in'
  #User is successfully signed in.

  page.click_link 'Sign Out'
  #User is still signed in!
```
After quick dig into sessions controller `Devise::SessionsController#verify_signed_out_user` before_filter halts execution of "destroy" action because `Devise::SessionsController#all_signed_out?` returns true. At the same time calling `user_signed_in?` returns true, so there is a conflict between `all_signed_out?` and `user_signed_in?` methods.

Rails 4.1.6, devise 3.4.1, rspec 2.14, capybara 2.3.0

**Comment by josevalim** [comment]
Ping! :)

**Comment by jono-tt** [comment]
having the same issue, @rubyrider did you find out any more?
