### ISSUE TITLE
undefined method `user_signed_in?'

### ISSUE THREAD

**Issue by rubytastic** [plataformatec/devise#3348]
Using Rails 4.2 beta 2.
May we request some instructions on how to get Devise work nice with this rails release?

Gemfile:
gem 'rails', '~> 4.2.0.beta2'
gem 'devise'

I tried the 2 month old rails 4.2 branch but that one fails with same problem.
Seems the devise helpers are not loaded.

I did not upgrade devise config files after upgrading rails. Is this needed?

**Comment by viniciusgati** [comment]
i'm having this with a simple rails 4.2.5.1
