### ISSUE TITLE
before_action :authenticate_user! not working

### ISSUE THREAD

**Issue by stevejc** [plataformatec/devise#3349]
I am unable to get `before_action :authenticate_user!` to work in my controllers which inherit from Devise.

```
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  def hello_world
    redirect_to pricing_path
  end
end
```

`before_action :authenticate_user!` works as expected in the other controllers.

**Comment by jmuheim** [comment]
> It *only* applies to devise controllers. :)

@josevalim, can you explain why?

I'd like to extend my `RegistrationsController` from `Devise::RegistrationsController` so I can just add to the existing files and folders (e.g. `app/views/devise/registrations/show.html` or `spec/features/user/registration/show_spec.rb`). But as written above, `before_filter :authenticate_user!` won't have any effect this way.

**Comment by ce07c3** [comment]
Ran into the same issue. It's not obvious why the user does not get authenticated. Overriding a `!`-method to not raise an exception is a big surprise.

**Comment by jmuheim** [comment]
Still a problem on my side. Didn't find a way to make authentication enforcement work.

**Comment by alexisraca** [comment]
I'm overriding an action in a devise controller and adding an after_action, it is also ignoring the after_action. Is there a reason for this behaviour?

**Comment by brycedarling** [comment]
@ce07c3  @jmuheim @alexisraca I ran in to this today as well. The following worked for me (the trick is `force: true`):

```
class RegistrationsController < Devise::RegistrationsController
  before_action ->{ authenticate_user!(force: true) }

  ...
end
```

**Comment by njcameron** [comment]
Looking at the [controller code](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L2) we can see that it states:

```ruby
class Devise::RegistrationsController < DeviseController
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]
```

Therefore we can override that in our class like this:

```ruby
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :authenticate_scope!, only: [:new, :create, :edit, :update, :destroy]
```

**Comment by mbaev** [comment]
I found one more solution which is worked for me:
```ruby
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :authenticate_scope!

  ...
end
```

**Comment by alexisraca** [comment]
https://github.com/plataformatec/devise/blob/e3a00b27d19ba995891d7dd92394fe2900a789c2/app/controllers/devise/registrations_controller.rb#L132

This seems to be conflicting the customization of the controller. I haven't tried to debug it but an override could fix this instead of layering forced `before_actions` because we could be triggering multiple undesired `authenticate_resource` calls

**Comment by ApoorvChandurkar** [comment]
> I found one more solution which is worked for me:
> 
> ```ruby
> class RegistrationsController < Devise::RegistrationsController
>   prepend_before_action :authenticate_scope!
> 
>   ...
> end
> ```

This Worked like a charm for me!

**Comment by chamox** [comment]
> I found one more solution which is worked for me:
> 
> ```ruby
> class RegistrationsController < Devise::RegistrationsController
>   prepend_before_action :authenticate_scope!
> 
>   ...
> end
> ```

Worked for me! thank you :heart:
