### ISSUE TITLE
Yield resource before save in registrations controller?

### ISSUE THREAD

**Issue by thejchap** [plataformatec/devise#3360]
Because the save is called before yielding the resource, if you are building a parent model and validating that the foreign key for that relationship is present on the resource, save ends up being called twice (once in the original controller, and then it needs to be called again after persisting the parent)....not a huge deal, just wanted to see if I was missing something or there was a better way to do this

https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L20

Example:

``` ruby
class Something
  has_many :users
end

class User
  belongs_to :something
  accepts_nested_attributes_for :something
  validates_presence_of :something_id
end

class CustomRegistrationController < Devise::RegistrationsController
  #....
  def create
    super do |resource|
      something = resource.build_something sign_up_params[:something_attributes] 

      if something.save
        resource.something = something
        resource_saved = resource.save # Calling here again after the original resource.save
      end
    end
  end
end
```

**Comment by Ekkstein** [comment]
That was unintended.
