### ISSUE TITLE
Add support for setting KeyGenerator iterations

### ISSUE THREAD

**Issue by koleksiuk** [plataformatec/devise#3363]
I've noticed during tests, that Devise is taking long time for generating new confirmation token for the first time (took around 20 seconds), then it was cached. Not sure why there is no way to define it except redefining whole Devise.token_generator

This pull request adds an option to configure number of iterations for generating Tokens (with default staying the same as previous).

**Comment by josevalim** [comment]
No, thats the way to do it. :)

**Comment by cbliard** [comment]
I just identified the same kind of test slowness and cause. I wanted to create a pull request to make iteration be 0 if `Rail.env.test?`, similar to how it is done for bcrypt stretches in devise initializer:

```
config.stretches = Rails.env.test? ? 1 : 11
```

So, is redefining `Devise.token_generator` the way to make token generation fast? Having a configuration option would enable to make it fast in all tests by default.

**Comment by cbliard** [comment]
I realized that the performance penalty is only at the first computation of a token, then the same key is used to compute subsequent tokens, so the performance gain is insignificant, especially with a large test suite.
