### ISSUE TITLE
Make multiple emails confirmable

### ISSUE THREAD

**Issue by karellm** [plataformatec/devise#3386]
I'm trying to tweak Devise to handle multiple emails. I would have a primary email and secondary emails. 
Emails don't need to be reconfirmable (you would add a new one, confirm it and make it primary). But all emails must be confirmable.

I found this [page](https://github.com/plataformatec/devise/wiki/Confirmable-with-many-emails) in the wiki. But it didn't work for me. I would like to have all the email logic in a single table/model and handled one way. I have something similar to [this](http://lorefnon.me/2014/09/07/devise-multiple-emails.html) in place but it doesn't handle confirmation just yet.

I have something like that:

``` ruby
class Email < ActiveRecord::Base
  devise :confirmable
  belongs_to :user
end

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable
  belongs_to :primary_email, class_name: "Email"
  has_many :emails
end
```

The problem I have is that when I create an email, I get the following error: `Could not find a valid mapping for #<Email>` which seems to be related to the fact I didn't define a scope for emails. But I'm a little confused why I'd need to do that altogether.

Any idea how I should implement this design? Am I getting in too much trouble trying to use Devise mechanism here and should I manually handle confirmation in the model?

Thanks for your help!

**Comment by allenwq** [comment]
https://github.com/allenwq/devise-multi_email

I have the same requirements, so that I wrote a gem for letting devise support multiple emails. hope this helps !
