### ISSUE TITLE
Devise Flash Messages

### ISSUE THREAD

**Issue by Dinuz** [plataformatec/devise#3387]
Dear @josevalim,

I notice that if I set the classic options from rails for the i18n.t like the scope for example, them are completely ignored by devise. After further investigation I saw that:

(1) The  set_flash_message(key, kind, options = {}) of devise accept an hash of options, and it pass the options to the method find_message(kind, options)

(2) The method find_message unfortunately has hard coded the options[:scope] :

    def find_message(kind, options = {})
        options[:scope] = "devise.#{controller_name}"
        options[:default] = Array(options[:default]).unshift(kind.to_sym)
        options[:resource_name] = resource_name
        options = devise_i18n_options(options)
        I18n.t("#{options[:resource_name]}.#{kind}", options)
    end

The fact that options[:scope] is hard coded with the devise, imply that the only place where devise is looking for the translation is the devise locale file. If instead I want organize my locales in different way, and let's say don't use the devise locale, i cannot do it.

What do you think if we modify that line in the following way:

    options[:scope] =  "devise.#{controller_name}" unless options[:scope]

This should still keep the devise lookup in the case that a customed scope is not passed as option, but if instead the custom scope is passed, then the find_message method will use it.

This is kind of useful, if i don't want overwrite the devise locale, and use different locale files, but keeping still the fallback of my devise locale.

**Comment by lucasmazza** [comment]
closed by #3405
