### ISSUE TITLE
Manually define routes (skip devise_for)

### ISSUE THREAD

**Issue by karellm** [plataformatec/devise#3388]
If using devise for an API, there are many routes that are defined yet not used and it feels dirty. I saw #3235 so I guess there is no configuration for `devise_for` other than controllers and paths. 

I started playing with manually declaring the routes but it doesn't work. After skimming Devise's code, the `mapping` thing is pretty obscure. 

Is it possible to define the route by hand altogether, skipping `devise_for`? If so, a little help would be greatly appreciated! Thanks.

UPDATE: I forgot to mention that the other reason I want to define routes manually is because I want to define routes in a method and call them multiple times. But the `devise_for` method fails in that use case:

```
Rails.application.routes.draw do

  def routes
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions:      'users/sessions'
    }
  end

  scope format: true, defaults: { format: 'json' } do
    routes
  end

  scope '/v:api_version', defaults: {format: 'json'} do
    routes
  end

end
```

Will throw:

```
/usr/local/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:430:in `add_route': Invalid route name, already in use: 'new_user_session'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
