### ISSUE TITLE
Adding 'devise' prefix to every controller in link_to

### ISSUE THREAD

**Issue by bishisht** [plataformatec/devise#3395]
I have 
						<li>
              <%= link_to('Home', :controller =>'site', :action=> 'home') %>              
						</li>

in my navbar partial. and when i try to access my site as localhost:3000/users/sign_in 

it shows me error 
No route matches {:action=>"home", :controller=>"devise/site"}

My routes.rb looks like:
Rails.application.routes.draw do
  
  get 'site/about'
  get 'site/help'
  get 'admin/index'

  resources :categories
  resources :businesses
  
  devise_for :users

  root :to=> 'site#home'
end

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by bishisht** [comment]
should I upload whole app to github
