### ISSUE TITLE
Not all texts in templates are in locale file

### ISSUE THREAD

**Issue by ozziash** [plataformatec/devise#3397]
When using an existing template for various emails and such, I often dealt with the localization problem. Not all projects I create are in English which means  that if I want to translate headings, I must copy the template to my repository and change it directly in the html. This may be a minor issue but when creating multiple confirmation emails, logins, registration it can get quite annoying.
It would be much easier if all the headings and untranslated pieces of text were taken from the locale file. That way I could edit the locale files not needing to copy the whole template. 

Example <a href="https://github.com/plataformatec/devise/blob/master/app/views/devise/registrations/new.html.erb">here</a>. I can't leave the "Sign up" title in a non-english project. 

Is there reason why all labels and texts aren't in locale file? If not, I would be happy to fix this issue right away.

**Comment by carlosantoniodasilva** [comment]
Thank you, but we've intentionally decided not to internationalise any of the devise views, see #2820 and the related comments and other issues/PRs for more context.
