### ISSUE TITLE
issue when logout - scoped routes with multitenant app

### ISSUE THREAD

**Issue by fmh** [plataformatec/devise#3399]
hi,

when logout the devise redirection is not correct, 

routes.rb
````ruby
Rails.application.routes.draw do

  scope "/apps" do

    scope "/(:ref)/(:locale)" , :path_prefix => "/:ref/:locale" do
      mount RailsAdmin::Engine => '/adminapp'

      get "readfiles/showfile/:securekey/:style"  , to: 'readfiles#showfile', as: 'showfile'
      get "autocomplete/get_attributes/:model" , to: "autocomplete#get_attributes" , as: 'get_attributes'

      devise_for :users, path: "whois",
          path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
      root :to => 'application#welcome'
    end

  end
`````

example url : http://localhost:3000/apps/params_to_get_current_tenant/DE/adminapp
devise ignore the params_to_get_current_tenant and redirect_to http://localhost:3000/apps/DE/adminapp

method to get the current tenant is in applicationcontroller 
```ruby
prepend_before_filter :scope_current_tenant
````

Is that somthing wrong in my routes.rb ? or must do anything other to tell devise keep current url ?

thx

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
