### ISSUE TITLE
What's the difference between 'after_sign_up_path_for' and 'after_inactive_sign_up_path_for'?

### ISSUE THREAD

**Issue by harrychenca** [plataformatec/devise#3402]
What's the difference between `after_sign_up_path_for` and `after_inactive_sign_up_path_for`?

`After authenticating a user and in each request, Devise checks if your model is active by calling model.active_for_authentication?. This method is overwritten by other devise modules. For instance, :confirmable overwrites .active_for_authentication? to only return true if your model was confirmed.`

What do we mean by `check if Model is active`? 

Thanks!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
