### ISSUE TITLE
Testing issue with a CustomFailureApp

### ISSUE THREAD

**Issue by Emerson** [plataformatec/devise#3409]
Howdy,

Before I get started, here are the relevant versions of the libraries I'm using:

* `Rails 4.2.0`
* `Devise 3.4.1`
* `Warden 1.2.3` _(required by Devise)_

I'm writing a brand new app with Devise _(first time using Devise...)_ and trying to build out a custom JSON API for all of the standard Devise endpoints. So far everything's been going well, but I think I've found a small issue that I think merits reporting. Sorry in advance if it's a simple answer, I'll make sure to update the wiki accordingly once things are resolved.

-------------------------------------

So I'm trying to create a custom Devise::FailureApp that will respond with proper JSON. The custom app is located in at `lib/custom_devise_failure_app.rb` and looks like:

```ruby
class CustomDeviseFailureApp < Devise::FailureApp

  def respond
    if request.format == :json or request.content_type == 'application/json'
      json_failure
    else
      super
    end
  end

  def json_failure
    self.status = 401
    self.content_type = 'application/json'
    self.response_body = {success: false, message: 'You are not authenticated'}.to_json
  end

end
```

If I run the server in development and do a manual `curl` request from the command line everything works perfectly, but if I make an unauthenticated request in my tests, my custom failure app is not used and I instead see: `ArgumentError: uncaught throw :warden`.

The test I have is very basic and looks like:

```ruby
  def test_unauthenticated_update
    user = users(:default)
    put :update, id: user.id, user: {
      name:             'New Name',
      current_password: 'password'
    }, format: :json
    assert_response :unauthorized
  end
```

I've setup the `devise.rb` file properly and am including the `include Devise::TestHelpers` in my `test_helper.rb`.

Any thoughts on how I should get this working?

**Comment by josevalim** [comment]
Your controller tests are not going through the middleware stack, so you will always get the uncaught warden thing. If you want to actually test your failure app, you need to use integration tests.

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
