### ISSUE TITLE
Passwords with "," or "." fail login with ruby 2.2.0

### ISSUE THREAD

**Issue by OmniBus** [plataformatec/devise#3415]
There is a problem between `devise` and `ruby 2.2.0` when password with punctuation like full stop `"."` and comma `","`.

Tested under
```
devise 3.4.1, 3.1.2, 3.0.4
ruby 2.2.0, 2.1.5
rails 4.0.13
pg 0.18.1
```

Using `ruby 2.2.0`
Password set to `'abcd,1234'`
Testing in a custom session controller

```ruby
password = 'abcd,1234'
user = User.find('abc@example.com').first

(password == params[:user][:password]) #=> true
user.valid_password?(params[:user][:password]) #= false
user.valid_password?(password) #= true
```

* Result incorrect.

Using `ruby 2.2.0`
Password set to `'abcd_1234'``, namely problematic punctuation removed

```ruby
password = 'abcd_1234'
user = User.find('abc@example.com').first

(password == params[:user][:password]) #=> true
user.valid_password?(params[:user][:password]) #= true
user.valid_password?(password) #= true
```
* Result correct.

Downgrade to `ruby 2.1.5` and test again
Password set to `'abcd,1234'`

```ruby
password = 'abcd,1234'
user = User.find('abc@example.com').first

(password == params[:user][:password]) #=> true
user.valid_password?(params[:user][:password]) #= true
user.valid_password?(password) #= true
```

* Result correct.

The ruby tells that the given `"params[:user][:password]"` and hardcoded `"password"` are the same but it yields different results when validation on some punctuations under version `ruby 2.2.0`.

Further testing with strings, in all case ruby say they are with both same encoding and same length.
```ruby
"#{password.encoding}" #=> "UTF-8"
password.length #=> 9
"#{params[:user][:password]}" #=> "UTF-8"
params[:user][:password].length #=> 9
```

**Comment by glebm** [comment]
This is caused by https://github.com/codahale/bcrypt-ruby/issues/106.

**Comment by davestevens** [comment]
I am also have this issue. I had a dig into `bcrypt-ruby` and I found out that `key` which is being sent through to `_bc_crypt` is not terminated correctly when it goes through the `mri` layer.

Another problem I have had with `2.2.0` was with a change to the way that `params` are handled and this seems to be a similar issue with how the params (only with /,. characters?) seem to be passed around.

We're using `Doorkeeper` in our app and adding `.dup` to `request.params[:password]`, eg:
from
```
  resource_owner_from_credentials do |routes|
    request.params[:user] = {
      email: request.params[:username],
      password: request.params[:password]
    }
    request.env["devise.allow_params_authentication"] = true
    request.env["warden"].authenticate(scope: :user, store: false)
  end
```
to
```
  resource_owner_from_credentials do |routes|
    request.params[:user] = {
      email: request.params[:username].dup,
      password: request.params[:password].dup
    }
    request.env["devise.allow_params_authentication"] = true
    request.env["warden"].authenticate(scope: :user, store: false)
  end
```
allows me to log in with my password again.

**Comment by josevalim** [comment]
Definitely a bcrypt-ruby bug. Thanks for reporting.

**Comment by davestevens** [comment]
After some more digging I've made an issue on the bcrypt-ruby page.
codahale/bcrypt-ruby#109
