### ISSUE TITLE
running the install command just hangs

### ISSUE THREAD

**Issue by Jordan4jc** [plataformatec/devise#3419]
After running `bundler` and then trying to run `rails g devise:install` the terminal just hangs.

After some time I just hit `ctrl + c` I see this show up in my terminal window

```
/Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/run.rb:54:in `gets': Interrupt
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/run.rb:54:in `verify_server_version'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/run.rb:25:in `call'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/rails.rb:23:in `call'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/client.rb:26:in `run'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/bin/spring:48:in `<top (required)>'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `load'
	from /Users/jordanriser/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/jordanriser/workspace/castr/bin/spring:16:in `require'
	from /Users/jordanriser/workspace/castr/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

```
I can't get devise to install because of this, hoping someone maybe knows a little of what is happening.

**Comment by josevalim** [comment]
Can you install any other gem? Also, can you try running `gem install devise`? It is very likely this is not a Devise issue, so something is interfering with your gems installation. :)

**Comment by Jordan4jc** [comment]
Okay well I had some other problems with some gems apparently not being pristine what ever the hell that means, so fixing those seems to maybe have fixed this issue because I just ran the install generator again and all is well. Thank you so much for the quick reply though, that's awesome!

**Comment by destinf** [comment]
I just ran into this problem now and for anybody who runs into this in the future, it turns out it's a spring issue https://github.com/rails/spring/issues/265
From the other thread, just restarting spring works
`$ spring stop`
`$ bin/spring`
