### ISSUE TITLE
current_user in after_sign_out_path_for no longer available in devise 3.4.1

### ISSUE THREAD

**Issue by hampei** [plataformatec/devise#3420]
The following code worked in devise 3.2, but stopped working in 3.4.1, because current_member is now nil at this point. Can't find anything about it in the changelog. Is this intentional?
Looking at the code for sign_out_and_redirect, the path is still explicitly retrieved before signing out, so it feels like it should be available.

```ruby
  def after_sign_out_path_for(resource_or_scope)
    if (resource_or_scope == :member || resource_or_scope.is_a?(Member)) && current_member && current_member.from_sso?
        rmunify_logout_url
    else
      super
    end
  end
```

ruby '2.1.5'
rails '4.1.8'

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by daninfpj** [comment]
I think this is a valid question. There’s currently no way of identifying the user that logged out, which apparently there was in 3.2.

**Comment by tscholz** [comment]
:+1:
