### ISSUE TITLE
Validatable module requires `email` column to exist, should it be configurable?

### ISSUE THREAD

**Issue by bf4** [plataformatec/devise#3421]
Our email column is called `email_address`, so in the config I set it to use `:email_address` everywhere it used `:email`

```ruby
 config.authentication_keys = [:email_address]
 config.case_insensitive_keys = [:email_address]
 config.strip_whitespace_keys = [:email_address]
 config.confirmation_keys = [:email_address]
 config.unlock_keys = [:email_address]
 config.reset_password_keys = [:email_address]
 config.email_regexp = /\A[^@]+@[^@]+\z/
```

But, the [Validatable module hard-codes the requirement of having an `email` column](https://github.com/plataformatec/devise/blob/v3.2/lib/devise/models/validatable.rb#L29-L31)

```ruby
          validates_presence_of   :email, if: :email_required?
          validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
          validates_format_of     :email, with: email_regexp, allow_blank: true, if: :email_changed?
```

My question, then, is if this is a bug/missing feature in the configuration options for devise, or if it's a bug/missing feature in the `assert_validations_api!(base)` that should disallow this, or if Devise should make it clear that using columns for email other than `email` are not well-supported, and **strongly** recommends etc.  (Yes, I did try forwarding the method calls but got a different failure `can't call .limit on nil` and decided to create an issue, rather than dig deeper)

I'm happy to make a PR for whichever is the desired behavior

(The assumption of an `email` column also affects view templates e.g. https://github.com/plataformatec/devise/blob/v3.2/app/views/devise/registrations/new.html.erb#L6 )
(looks like this first such config was added in https://github.com/plataformatec/devise/commit/b70b29369 )

**Comment by josevalim** [comment]
Our recommendation in those cases is to simply not use validatable and roll your own. The same for views. We allow configuration for the other keys not because users may configure the e-mail but because they may want to add other keys *besides* the e-mail one. :) So at maximum we could document validatable requires an e-mail field and mention that you should roll your own if you have other fields.

**Comment by josevalim** [comment]
Thanks for the report!

**Comment by bf4** [comment]
@josevalim So, I can make a PR (with tests) to specify that Devise requires an `email` column for `validatable` and views?

**Comment by josevalim** [comment]
@bf4 We already have tests for those. I don't think we need a test to show that it fails for other inputs. Or do you have something else in mind? Improvements to docs are always welcome though!

**Comment by bf4** [comment]
Ok, I'll work on a PR for that.
