### ISSUE TITLE
Using current_user or user_signed_in? in application_controller.rb before_action causes ActiveRecord::ConnectionTimeoutError 

### ISSUE THREAD

**Issue by toymachiner62** [plataformatec/devise#3422]
I'm running into an issue that i've nailed down to very specific lines of code. When I use either `current_user` or `user_signed_in?` in a `before_action` in `application_controller.rb`, my database connections are not getting released and i'm getting `ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):`.

I'm currently running rails 4.1.8, ruby 2.0.0p481, puma, 2.10.2, and devise 3.4.1.

Here's a simple snippet that causes this problem:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, get_new_messages
  
  # Gets the unread messages for the logged in user
  def get_new_messages
    @num_new_messages = 0 # Initially set to 0 so login page, etc works
    # If the user is signed in, fetch the new messages
    if user_signed_in?
      @num_new_messages = Message.where(:created_for => current_user.id).where(:viewed => false).count
    end
  end
...
end
```

Here's a full stacktrace:
```sh
F, [2015-01-15T12:03:49.922826 #14613] FATAL -- : 
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
  /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `acquire_connection'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /usr/local/rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
  activerecord (4.1.8) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.1.8) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.1.8) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.1.8) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:32:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  dragonfly (1.0.7) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  puma (2.10.2) lib/puma/configuration.rb:74:in `call'
  puma (2.10.2) lib/puma/server.rb:492:in `handle_request'
  puma (2.10.2) lib/puma/server.rb:363:in `process_client'
  puma (2.10.2) lib/puma/server.rb:254:in `block in run'
  puma (2.10.2) lib/puma/thread_pool.rb:101:in `call'
  puma (2.10.2) lib/puma/thread_pool.rb:101:in `block in spawn_thread'
```

**Comment by josevalim** [comment]
Thank you! Can you reproduce this issue in a blank application and push it to Github? It would help us guarantee the bug is in Devise/Warden rather than a particular gem in your app.

**Comment by toymachiner62** [comment]
Absolutely. Here's a simple project which reproduces the error https://github.com/toymachiner62/devise-connection-failure. 

I've learned that by having custom error handling routes, I get this error. If you comment out this line https://github.com/toymachiner62/devise-connection-failure/blob/master/config/environments/production.rb#L84 the error goes away.

**Comment by josevalim** [comment]
Awesome, thanks! One last question, do you also get this error if you are *not* using Devise? At first, it looks like a Rails or Rack bug.

**Comment by josevalim** [comment]
And by that, I mean by raising any other error in your controller, as I am assuming you are seeing those issues when there is no user signed in (and therefore Devise is raising).

**Comment by toymachiner62** [comment]
I don't think so. If i uncomment out this line, https://github.com/toymachiner62/devise-connection-failure/blob/master/app/controllers/application_controller.rb#L9 I get the error 
```sh
Error during failsafe response: undefined method `exception' for #<ErrorsController:0x007fdace8617e8>
  /Users/m089269/Sites/devise-connection-failure/app/controllers/application_controller.rb:9:in `get_current_user'
```

**Comment by josevalim** [comment]
I think that is the issue.

In order to render the failure page, it is going back to the application
controller, which is then failing when fetching the user again. Imagine
this:

1. authenticate_user! fails
2. The error goes up to the Rails exception handling
3. You set the exception handling to invoke the router
4. The router triggers a controller that trigger authenticate_user! fail
again
5. Everything goes havroc

The exception app documentation is very clear that you should avoid doing
any work when rendering an error page, except because it can trigger
scenarios like this.

Thoughts?

**Comment by toymachiner62** [comment]
Can you point me to the exception app documentation? 

So are you suggesting that my error_controller needs a `skip_before_filter: get_current_user`?

**Comment by toymachiner62** [comment]
ok so that seemed to work. I guess the piece that i'm still struggling to understand from your scenario though is if step #1 fails, it should just redirect you to the login page. Why does it go to the rails exception handler? Is that the way that devise works? Does a failed authenticate_user! throw an exception which gets caught and redirects to the login page?

**Comment by josevalim** [comment]
> So are you suggesting that my error_controller needs a skip_before_filter: get_current_user?

Exactly. It should not try to the authenticate the user nor get the user because, if the error happens exactly when authenticating, how are you going to show the error if the user can't authenticate?

**Comment by josevalim** [comment]
> ok so that seemed to work. I guess the piece that i'm still struggling to understand from your scenario though is if step #1 fails, it should just redirect you to the login page. Why does it go to the rails exception handler? Is that the way that devise works? Does a failed authenticate_user! throw an exception which gets caught and redirects to the login page?

Yes, when you can't authenticate, Devise raises an error.
