### ISSUE TITLE
Custom login fails with ajax!

### ISSUE THREAD

**Issue by zeitnot** [plataformatec/devise#3423]
I am using the confirmable module. It works as expected except if the account is unconfirmed. If the account is unconfirmed it sends the folowing json. This fails only when the respond type is json. If it is html it works as expected and it sends `You have to confirm your account before continuing.` error message. 

```json
{
"login": null,
"password": null
}
```

This is my custom session controller.

```ruby
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  skip_before_filter :verify_authenticity_token

  def create 
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    render json: { success: true, redirect:  ''}, status: 200
  end

  def failure   
    warden.custom_failure!

    render json: { success: false, error: I18n.t("devise.failure.#{env['warden'].message.to_s}") }, status: 401
  end

  protected
  def auth_options
    {:scope => resource_name, :recall => "#{controller_path}#failure"}
  end
```

end

These are needed configs

```ruby
  config.http_authenticatable_on_xhr = false
  config.navigational_formats = [:"*/*", "*/*", :html, :json]
```

**Comment by zeitnot** [comment]
I did find the real problem. When the user is unconfirmed and credentials are true it is redirected from `Devise::SessionsController` with `401` status code. With this hook I stopped the redirection when the request format is `json`. I think it needs a fix. 
```ruby
  before_filter :handle_redirect, :if => Proc.new { |c| c.request.format == :json }
```

**Comment by josevalim** [comment]
Well, you asked to treat :json a navigional format, that is exactly what will happen. JSON is a format for APIs and should be used as such. It doesn't make sense to have session for JSON too, one should rather use tokens.

**Comment by FunkyloverOne** [comment]
Seriuosly guys, I even cannot achieve some correct respond from the server if sign in with ajax fails in this case. I'm getting a rendered html view as a result instead of some nice json. :disappointed:
