### ISSUE TITLE
Multiple Devise User Models not routing correctly.

### ISSUE THREAD

**Issue by BornALegend** [plataformatec/devise#3424]
I generated both a User and BizUser model with controller and views separated from each other. Neither are routing to the views and paths defined for them.

 new_user_session GET    /users/sign_in(.:format)                     users/sessions#new
                 user_session POST   /users/sign_in(.:format)                     users/sessions#create
         destroy_user_session DELETE /users/sign_out(.:format)                    users/sessions#destroy
                user_password POST   /users/password(.:format)                    devise/passwords#create
            new_user_password GET    /users/password/new(.:format)                devise/passwords#new
           edit_user_password GET    /users/password/edit(.:format)               devise/passwords#edit
                              PATCH  /users/password(.:format)                    devise/passwords#update
                              PUT    /users/password(.:format)                    devise/passwords#update
     cancel_user_registration GET    /users/cancel(.:format)                      users/registrations#cancel
            user_registration POST   /users(.:format)                             users/registrations#create
        new_user_registration GET    /users/sign_up(.:format)                     users/registrations#new
       edit_user_registration GET    /users/edit(.:format)                        users/registrations#edit
                              PATCH  /users(.:format)                             users/registrations#update
                              PUT    /users(.:format)                             users/registrations#update
                              DELETE /users(.:format)                             users/registrations#destroy
         new_biz_user_session GET    /biz_users/sign_in(.:format)                 bizusers/sessions#new
             biz_user_session POST   /biz_users/sign_in(.:format)                 bizusers/sessions#create
     destroy_biz_user_session DELETE /biz_users/sign_out(.:format)                bizusers/sessions#destroy
            biz_user_password POST   /biz_users/password(.:format)                devise/passwords#create
        new_biz_user_password GET    /biz_users/password/new(.:format)            devise/passwords#new
       edit_biz_user_password GET    /biz_users/password/edit(.:format)           devise/passwords#edit
                              PATCH  /biz_users/password(.:format)                devise/passwords#update
                              PUT    /biz_users/password(.:format)                devise/passwords#update
 cancel_biz_user_registration GET    /biz_users/cancel(.:format)                  bizusers/registrations#cancel
        biz_user_registration POST   /biz_users(.:format)                         bizusers/registrations#create
    new_biz_user_registration GET    /biz_users/sign_up(.:format)                 bizusers/registrations#new
   edit_biz_user_registration GET    /biz_users/edit(.:format)                    bizusers/registrations#edit
                              PATCH  /biz_users(.:format)                         bizusers/registrations#update
                              PUT    /biz_users(.:format)                         bizusers/registrations#update
                              DELETE /biz_users(.:format)                         bizusers/registrations#destroy

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
