### ISSUE TITLE
Stupid question: where email_changed? is defined?

### ISSUE THREAD

**Issue by Dinuz** [plataformatec/devise#3426]
I cannot find where is defined in the whole code.

I know @josevalim this is not a bug and should not be, but I also think that I cannot ask this question on stakeoverflow:)

Forgive me:)

**Comment by lucasmazza** [comment]
`email_changed?` is defined by the `ActiveModel::Dirty` API, and the method is defined dynamically when there is an `email` column in your model.

**Comment by Dinuz** [comment]
Thank you...Honestly I googled it, but didn't come out nothing about dirty:(
