### ISSUE TITLE
devise form with remote:true returning 200 when validations fail

### ISSUE THREAD

**Issue by jgrannas** [plataformatec/devise#3434]
Rails (4.1.5)
devise (3.3.0)

I ran rails g devise:views. In the registration form I added remote:true

When i submit the registration form, in my browser console it returns a 200 OK, and the response is the HTML of the entire new.html.erb form which has my validation errors in the response.

I thought i read that Devise out of the box supports ajax by simply putting remote:true on forms? Or did i miss something?

**Update:** I added an override controller, and at the top put **respond_to :js** in order to get my create.js.erb file to work... but i was under the impression creating a controller was not necessary

![screen shot 2015-01-19 at 7 11 44 pm](https://cloud.githubusercontent.com/assets/2011886/5810125/1ba21d62-a00f-11e4-9560-47e68b7cb2f2.png)

**Comment by josevalim** [comment]
We inherit the respond_to :js from your application controller, so theoretically you could put it there or add respond_to :js as part of a to_prepare hook in your app initializer:

    config.to_prepare { DeviseController.respond_to :js }
