### ISSUE TITLE
Have you considered remembering more reset_password_tokens than just the last one?

### ISSUE THREAD

**Issue by oboxodo** [plataformatec/devise#3435]
Resetting passwords works just fine. But sometimes SMTP servers take a while to deliver the email with the link to reset the password... and modern users are impatient, then ask for a new reset password, then the first email arrives and the token is not valid anymore, and then they complain.

I fully understand this is a UX problem and not a bug in Devise. But this might be solved by saving a history of reset tokens and still validating their valid period. Once the password gets reset then all remaining reset tokens for that user would be deleted so they can't be used.

I'm considering coding something for this but wanted to ask first:
1. Do you know of any already existing devise plugins for this? I couldn't find any.
2. Can you think if any security problems this might bring?

**Comment by josevalim** [comment]
We could do this and, if I was starting Devise today I would likely keep separate tables for tokens and emails for this reason. But that's exactly the issue: this feature requires a drastic change in the schema and the gains are too low to justify doing such a big change to Devise. :(
