### ISSUE TITLE
Editorial Changes to Wiki Page

### ISSUE THREAD

**Issue by gcortes** [plataformatec/devise#3436]
These comments are for the page: https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

First of all, thanks for writing the instructions. They were easy to follow and I got it to work. I have the following editorial comments on the content. My apologies if this isn't the right way to address the issue. If not please let me know how to do so in the future.

## Comment 1

The paragraph right after "For Active Record:" is as follows:

"MySQL users: the use of the SQL lower function below is most likely unnecessary and will cause any index have on the email column to be ignored."

The grammar isn't right at the end of the sentence.

## Comment 2

In the second example it shows ":format => { …} # etc.

I was pretty sure the ellipsis wasn't valid syntax, but I tried it any way. When it didn't work, I deleted the clause as I don't know what it is and everything appears to work without it. I'm sure I can figure it out by referring to the Rails documentation and wouldn't expect an explanation here. If it's not absolutely necessary, you might consider removing it as programmers love to cut and paste examples into there code as is.

## Comment 3

In the "Modify the views" section, your example shows
```
   -  <p><%= f.label :email %><br />
   -  <%= f.email_field :email %></p>
   +  <p><%= f.label :login %><br />
   +  <%= f.text_field :login %></p>
```
Mine had:
```
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>
```
The same holds true for the other examples. This is a minor difference. I chose to keep the autofocus attribute

## Comment 4

The instructions on changing the devise.en.ml file say to replace

    invalid: "Invalid email or password."
    ... 
    not_found_in_database: "Invalid email or password."

I have the following in  my file which I installed on 19 Jan 2015:

    invalid: "Invalid %{authentication_keys} or password."
    …
    not_found_in_database: "Invalid %{authentication_keys} or password."

Is it still necessary to change these lines given that the word "email" in no longer present?

**Comment by josevalim** [comment]
Thank you @gcortes! The wiki is open so you can contribute your changes any time. Sometimes the examples get outdated and contributions like yours are very welcome to bring them up to date. (and yes, we no longer need the step in Comment 4). :)

**Comment by gcortes** [comment]
I wasn't sure you wanted me to make the changes. I see it hasn't changed so I'll go ahead and make them. I'm glad to contribute.

**Comment by josevalim** [comment]
Yes, please go ahead and make them! Sorry I was not clear!

**Comment by gcortes** [comment]
It took me forever to get back to make the change It's done now.
