### ISSUE TITLE
Custom registration controller results in undefined local variable or method `set_minimum_password_length'

### ISSUE THREAD

**Issue by jasper502** [plataformatec/devise#3437]
I created a custom registration controller to allow params from a nested form in my view and to add some additional logic in the create action.

This results in a `undefined local variable or method 'set_minimum_password_length'` error once you submit the form.  I went as far as to paste the entire original controller code into to test it and it still fails.  All the other calls seem to work fine.

As a last resort I just copied the 'set_minimum_password_length' method from the main devise controller into my custom controller and that works.  My only concern is that if the code gets updated in the gem my override will be outdated when I inevitable forget I did this.

**Comment by carlosantoniodasilva** [comment]
Have you inherited from the existing `Devise::RegistrationsController`, or at least from `DeviseController`? The last one is the one that actually contains this method, it seems weird you're getting this error if you did inherit. Can you show us the related code? Thanks.

**Comment by jasper502** [comment]
Here is my current controller:

https://github.com/jasper502/stackexchange/blob/master/28039893/registrations_controller.rb

and the relevant part of my routes.rb file:

https://github.com/jasper502/stackexchange/blob/master/28039893/routes.rb

If I delete the 'set_minimum_password_length' method from it the error appears.  It is weird as 'clean_up_passwords' is in the devise controller also and it seems to work.

**Comment by carlosantoniodasilva** [comment]
Ok I see it. `set_minimum_password_length` is on master only, the last released version has logic to set the required variables on the related actions, [like this](https://github.com/plataformatec/devise/blob/v3.4.1/app/controllers/devise/registrations_controller.rb#L6-L13) for instance.

Which devise version are you using? Make sure you copy over the code from the same version as yours based on the tags in github, and you should have no problem.

**Comment by jasper502** [comment]
Yup - that was it.  I blindly copied the master code.  As a GitHub newbie I didn't realize I needed to select the version tag.  You learn something everyday.  Thanks for pointing me in the right direction.

**Comment by carlosantoniodasilva** [comment]
Glad to know it worked now :)

Carlos Antonio da Silva - via celular

Closed #3437 <https://github.com/plataformatec/devise/issues/3437>.

—
Reply to this email directly or view it on GitHub
<https://github.com/plataformatec/devise/issues/3437#event-223921930>.
