### ISSUE TITLE
SSL Client Authentication

### ISSUE THREAD

**Issue by szechyjs** [plataformatec/devise#3438]
I'm in the process of creating an extension for authenticating using X509 SSL client certificates. The extension is able to detect the HTTP headers just fine and associate the certificate with a user, however I'm having a bit of a design problem implementing the proper user flow.

Ideally I'd like for users to be able to authenticate using their certificate and if they don't have a valid certificate fall back to username and password database authentication. This currently works, however, not as desired.  If a user has a valid cert, the browser will ask the user to load it when the SSL connection is established, this is default browser behavior. Now that the cert is loaded, all the headers that reach rails will contain certificate information. This is then used by my extensions strategy to authenticate the user. The only problem is this should not set a session. Each request to the server should recheck for these headers.

I can't quite figure out how to make devise re-evaluate the authentication strategy on each request rather than doing it once and storing it in the session.

A common use case is the user has a certificate/key on a smart card. They login to the website using this certificate. When they remove the smart card from the computer they should no longer be signed into the website. With my current implementation of this, the user would have to manually logout/destroy their session, rather than it happening automatically on the next request since valid headers would no longer exist.

There are ways I've implemented this in the past using just rails, however I think this has a better place as a devise extension. Do you have any suggestions on how to implement this properly?

**Comment by szechyjs** [comment]
I should note that the other problem I have is that I have to currently submit a login for for it to authenticate using the SSL cert. I'd like for it check the headers when authenticate_user! is called. From what I can tell it checks the session first, and if the user isn't set it redirects to the sign_in page. From here it then actually calls my authenticate! method i've implemented. Is there a way to evaluate my authenticate! prior to the redirect to sign_in?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by micapam** [comment]
@szechyjs Did you end up writing that extension ? :)

**Comment by szechyjs** [comment]
@micapam I had a 90% solution somewhere, I'll see if I can find it.

**Comment by aaronlippold** [comment]
Hi, any updates on this, my team is also using devise and has to support x509 auth, thanks

**Comment by szechyjs** [comment]
I started an extension but never finished it.

https://github.com/szechyjs/devise_ssl_authenticatable

I believe all that was left was making it easier to configure for different web servers (puma, nginx, apache, etc).

I welcome any PRs to help finish it.
