### ISSUE TITLE
Devise within Devise?!

### ISSUE THREAD

**Issue by HatStephens** [plataformatec/devise#3439]
So I have Devise log in working for dev_user (basically a wrapper around a prototype I'm building).
Once in the actual site, there is an option to sign up which I have called business_user (with a different user/email).
The log in for business_user is working fine, however, when they log out, they are also logged out at the top level (dev_user).

Anyone know a way around this? I have adjusted the log out link to destroy_business_user_session_path, :method => :delete
which I thought would be enough, but clearly I am missing something.

Any help greatly appreciated!

**Comment by lucasmazza** [comment]
Please check the `[sign_out_all_scopes](https://github.com/plataformatec/devise/blob/6dd444458258c27ad08f56151e74fe9998713818/lib/devise.rb#L223-L225)` option.

 Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by HatStephens** [comment]
Thanks for this @lucasmazza I'm new to development so getting 'inside' of things is still not second nature yet. This has really helped. Have a good day!
