### ISSUE TITLE
Remove responders gem

### ISSUE THREAD

**Issue by zedtux** [plataformatec/devise#3441]
Since Rails 4.2 the `respond_with` method has been extracted within the responders gem.

Devise is using it right now but should do the migration by replacing `respond_with( ... )` by:

```ruby
  respond_to do |format|
    # ...
  end
```

**Comment by josevalim** [comment]
We have no plans to remove the responders gem. :)

**Comment by zedtux** [comment]
Well this issue could stay open and have someone else doing it for you. I don't like gems adding too much dependencies. Really it's useless and Devise is not using `respond_with` so often.

Why not keeping this open and see what happen ?

**Comment by josevalim** [comment]
We don't have plans even to remove if someone does the work. There is no way we can implement Devise in a way people can add custom formats later on without reimplementing half of the responders gem. If we use respond_to, which formats should we choose? html and js? What if someone else wants xml? Or a custom json? Or something for mobile? We don't like extra dependencies too and responders has a very specific purpose.

**Comment by zedtux** [comment]
It make sense ... but I still don't like it. :(

Anyway thank you for your answer :)
