### ISSUE TITLE
Weird behavior in registration controller

### ISSUE THREAD

**Issue by Dinuz** [plataformatec/devise#3444]
Why if the update action in the registration controller fails, I am re-route to a show page?!?
There is no show action in the routing system.
I would expect to be re-routed back to the edit page and see there the form errors.

Note I am using my controllers(but are the same as the decise default, I didn't change nothing except the path after update(that is the edit page), and the method to update(update with or without password depending on the presence of the password parameter)!

I just don't get it...in the controller there is a respond_with(resource) that should just bring up the errors if they are present!

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Dinuz** [comment]
@josevalim I am so sorry yesterday I wrote from my phone and didn't use the search field for issues (it doesn't work from mobile on github). Today I looked around and I found a similar question (at least the issue is very similar to mine), that was partially answered by @lucasmazza.

I am refering to the issue https://github.com/plataformatec/devise/issues/3186 .

I don't think this is a bug, but would be eventually very nice explain it, and eventually we can just add a brief explanation in the Readme section of Devise gem.

Looking forward to hearing from you.
Best
Dinuz

**Comment by Dinuz** [comment]
@josevalim ok what I did is simply the following:

(1) Using the scope user for devise

(2) created my scoped controller for the user resource using the devise generate (the controllers are the devise default controllers).

(3) generated the scoped views

(4) Updated the routes (I am reporting here just the registrations scope, but I have all the rest setup right and working):

    devise_for :users,  controllers: { registrations: 'users/registrations',
                                     sessions: 'users/sessions',
                                     confirmations: 'users/confirmations',
                                     passwords: 'users/passwords',
                                     unlocks:  'users/unlocks',
                                     omniauth_callbacks: 'users/ominauth_callbacks'
                                   },
                      skip: [:registrations, :sessions, :confirmations, :passwords, :unlocks, :invitations]

      devise_scope :user do
         get 'cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
         get 'sign_up', to: 'users/registrations#new', as: 'new_user_registration'
         post 'users', to: 'users/registrations#create', as: 'user_registration'
         get 'users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_registration'
         patch 'users/:id', to: 'users/registrations#update', as: 'update_user_registration'
         delete 'users', to: 'users/registrations#destroy', as: 'destroy_user_registration'
     end

(5) In my devise user model I have two extra parameters first and last name (I added them in the strong parameters), and they works because if the update action doesn't have errors it update the parameters.

(6) I overwritten the following two methods in the registration controller:

    def update_resource(resource, params)
        if params[:password].present?
          resource.update_with_password(params)
        else
          params.delete(:current_password)
          resource.update_without_password(params)
        end
    end

    def after_update_path_for(resource)
        flash[:notice] = "Account successfully updated"
        edit_user_registration_path(resource)
    end


The issue that I am having it's really pretty simple:

(A) NO ERRORS IN THE FORM
In this case the models are update without issue, and I am rerouted where the after_update_path_for says (in my case the edit page for example http://localhost:3000/users/1/edit).

(B) ERRORS IN THE FORM
I would image to have the same behaviour of no errors, then be re-routed to the edit page, but the form will show the errors.
This instead doesn't happen and what happen is that I am re-routed to the following page: http://localhost:3000/users/user

This page doesn't exist in my routes and I don't know why I am getting it or hitting it.

Note the only thing that I changed in the actions is that i used the verb patch(as rails suggest) instead of put but I accordly changed the form as well.

Is this more clear now?

Thanks a lot for your patience
Dinuz

**Comment by Dinuz** [comment]
@josevalim I am really sorry, this isn't a bug at all.
My fault that I missed the mistake, devise works like a charm, and it was in my code:(

I have had restricted some view with an if controller_name == 'registrations' && action_name =='edit', and obvy when i was hitting the error in the update action, the rendered view was pretty empty. Removing the specificity on the action name, allow the normal rendering.

The routing url are still not the nicer (users/user for example), but that change in users/1 if instead of using resource in the form I use @user.
Would be nice understanding better how modify the routes in order to don't have a users/user.

Anyway thanks!!!

Your work is amazing!
