### ISSUE TITLE
NoMethodError: undefined method `permit' for ["a", "b"]:Array

### ISSUE THREAD

**Issue by nyku** [plataformatec/devise#3445]
happens here
https://github.com/plataformatec/devise/blob/master/lib/devise/parameter_sanitizer.rb#L66

form params:

```ruby
{
  "action" => "create",
  "authenticity_token" => "FILTERED",
  "client" => ["a", "b"],
  "commit" => "Log in",
  "controller" => "clients/sessions",
  "utf8" => "✓"
}
```

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by nyku** [comment]
@josevalim  let's try this again more explicitly:

1) There is a Sign in form with 2 fields: username, password
```html
...
<input type="email" name="client[email]">
<input type="password" name="client[password]">
...
```

2) Fill email field with "a" and password field with "b"
3) Change both input names to `client[]` and submit the form from browser's console:
```jquery
$('form').submit();
```
Now you'll get params i described above and a server error.
