### ISSUE TITLE
current_user.provider throwing method not found error

### ISSUE THREAD

**Issue by daao87** [plataformatec/devise#3446]
Hi!

I was trying to make possible editing a user profile when it logged in using oauth, like facebook, for instance. In this case, since the user doesn't have a password, the update without providing current password should be allowed (via resource.update_without_password(params)). The problem is that in order to know if the user logged in through facebook, I have to check if current_user.provider == "facebook". But I'm getting an error there, saying that the provider method doesn't exist. How can I get the provider from the current_user?

Thanks!

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
