### ISSUE TITLE
Updated translations for Spanish and Catalan to current version (3.2)

### ISSUE THREAD

**Issue by jordigg** [plataformatec/devise#3450]
Updated translations for Spanish and Catalan to current version (3.2). Removed unused keys and added the new ones. Didn't know how to update the wiki so I'm posting here :smile: 
es: https://gist.github.com/jordigg/f3d8c313e9e9361cac75
ca: https://gist.github.com/jordigg/bee12ca7cb6900c86ea1

**Comment by josevalim** [comment]
You should be able to edit in the wiki directly. But thanks for posting anyway!

**Comment by jordigg** [comment]
Now I see the edit button. I'll update now. Thanks! :+1:
