### ISSUE TITLE
Does using devise without SSL/TLS mean users are sending cleartext passwords in forms on login?

### ISSUE THREAD

**Issue by jmhertlein** [plataformatec/devise#3453]
I do have SSL set up on my site now, but I've been logging into it with plain HTTP for a while. Have I been sending my plaintext password over the network every time?

I'm using the default devise views/controllers.

**Comment by josevalim** [comment]
Yes. Use Rails config.force_ssl to enforce SSL. ALso,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
