### ISSUE TITLE
Adding not null unique columns to devise user table causes insert errors

### ISSUE THREAD

**Issue by wins32767** [plataformatec/devise#3455]
Migration1:
class DeviseCreateUsers < ActiveRecord::Migration
  def change
    create_table(:users) do |t|
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at

      t.timestamps
    end

    add_index :users, :email,                unique: true
    add_index :users, :reset_password_token, unique: true
    # add_index :users, :confirmation_token,   unique: true
    # add_index :users, :unlock_token,         unique: true
  end
end

Migration2:
class AddUsernameToUsers < ActiveRecord::Migration
  def change
    add_column :users, :username, :string, null: false, default: ''
    add_index :users, :username, unique: true
  end
end

Test:
require 'test_helper'

class UserTest < ActiveSupport::TestCase

  def setup
    @user = User.new email:'test@example.com', username:'test', password:'password'
    @other_user = User.new email:'test2@example.com', username:'test2', password:'password'
  end

  test 'username saves' do
    @user.save
    assert @user.username, 'test'
    @other_user.save
    assert @other_user.username, 'test2'
  end

end

Error message:
Minitest::UnexpectedError: ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: column username is not unique: INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at") VALUES (?, ?, ?, ?)
    test/models/user_test.rb:13:in `block in <class:UserTest>'
test/models/user_test.rb:13:in `block in <class:UserTest>'

Removing 
null: false, default: '' 
from the username column definition allows the test to pass.  However, the insert should include the username column (and any other added columns) to support not null, unique fields rather than populating them by updates.

**Comment by wins32767** [comment]
Sorry about the formatting, not sure how to fix it.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by DavidMMelin** [comment]
The issue is with :validatable. It validates email by default
