### ISSUE TITLE
Custom registration routes breaks nested attributes / validations

### ISSUE THREAD

**Issue by jasper502** [plataformatec/devise#3456]
Here is a Gist link with all the gory details: https://gist.github.com/065a63fde266fac1fbf5.git

To summarize I customized the default user registration page to add a few more User attributes and some nested attributes for two associated models (Role and Company).  There is a custom registration controller to set some Role attributes in the background etc.  It worked with the default registration routes (/user etc)  i.e. I was only skipping the session routes which I had changed to something more user friendly.  The nested attributes validations worked and all was good.

So next I set out to clean up the sign_up routes.  I wanted to have the sign_up route to change to register so I added this:

```get "/register" => "devise/registrations#new"```
```post "/register" => "devise/registrations#create" ```

The problem is that now when posting to /register the nested validations are not triggered and the user validations all fail regardless if the data is valid.  I have tested this many different ways and although I am new to Devise I think I am taking the right approach.  I hope that someone can quickly either confirm this is in fact a bug or I am just missing something here.

**Comment by jasper502** [comment]
I think I figured it out.  I stumbled across this:

https://gist.github.com/6dd44fc841e80bbc2265.git

I switched my routes to "user/..." from "devise/..." and that seemed to do the trick.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
