### ISSUE TITLE
BUG: Resend confirmation page shows old email address

### ISSUE THREAD

**Issue by redbar0n** [plataformatec/devise#3457]
If the user does not click the confirmation link within the confirm_within time period, he is taken to a resend confirmation page. On that page, actually the old email address is shown, and not the new one.

Here's a screenshot:
![screenshot 2015-02-07 15 56 14](https://cloud.githubusercontent.com/assets/459282/6092494/e9fd15fa-aee1-11e4-9e91-048f55b381c7.png)

It is a potential security risk, since it will leak the user's old email address to any new user that might have gotten the confirmation email when the original user was trying to change his email (and did a typo).

Besides, the error message devise shows makes no sense in that context, because it presumes the new email is the one being shown.

**Comment by josevalim** [comment]
Thanks. Which Devise version? Also, are you using custom views?

**Comment by redbar0n** [comment]
Never mind.. I just found out that the error was in a custom view we had used. To my defense I didn't code it. I will double double check before posting next time. Thanks for quick reply though. For future reference:

We had used:

    <div class="form-inputs">
      <%= f.input :email, :required => true %>
    </div>

Instead of the correct one:

    <div class="form-inputs">
      <%= f.input :unconfirmed_email, :required => true %>
    </div>

**Comment by redbar0n** [comment]
Actually, I just found that the devise error message isn't being shown when I changed to displaying :unconfirmed_email instead of :email . Any ideas why?

**Comment by redbar0n** [comment]
And actually, I just discovered the original bug persisted even after deleting our custom view, so I guess it is in fact a bug in devise.

**Comment by redbar0n** [comment]
My current workaround, setting the email field explicitly in code, and disallowing the user from editing it:

```ruby

<%= simple_form_for(resource, :as => resource_name, :url => confirmation_path(resource_name), :html => { :method => :post }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, :required => true, readonly: true, input_html: { value: resource.unconfirmed_email } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t("devise.confirmations.new.resend_confirmation_instructions") %>
  </div>
<% end %>
```

```css
.form-inputs .readonly {
	color: grey;
}
```

PS: I'm using the simple_form gem.

**Comment by redbar0n** [comment]
I'm on devise version:     devise (3.4.1)

**Comment by josevalim** [comment]
@redbar0n the issue is that we show the same view for confirming both email and unconfirmed_email, so you would need to do `unconfirmed_email || email` or something. Also, can you please send a pull request?

**Comment by redbar0n** [comment]
Ah, I see. We had to change this line to:

```ruby
<%= f.input :email, :required => true, readonly: true, input_html: { value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) } %>
```

Pull request sent. NB: I haven't had a chance to test the pull request code explicitly in our app, since we're using simple_form and devise is using standard rails forms. So you might want to have a look at that one line of code to make sure it looks correct. Maybe the Travis CI test suite will catch it if anything is wrong..

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by redbar0n** [comment]
:-)
