### ISSUE TITLE
4.2.0 compability bug again?

### ISSUE THREAD

**Issue by Mirkz** [plataformatec/devise#3459]
Hi guys,

I just stumbled upon the `ensure in with_devise_exclusive_scope': undefined method `merge!' error.
As I could see this was fixed with the pull request of the branch 'lm-rails-4-2' .
However after including devise in the Gemfile, installing it, generating the views and the user model I got this error on running rake db:migrate.
Did I overlook something?

**Comment by josevalim** [comment]
Which Devise version are you using? Are you sure the version you are using includes the fix you mention? Can you link to the commit?

**Comment by Mirkz** [comment]
Hi José,

Thanks for your fast answer!
I am using Devise 3.4.1 and as far as I can see it, a fix should have been merged with this commit: https://github.com/plataformatec/devise/pull/3153, no?
As far as I can see, the branch was merged on Oct. 3rd 2014, while 3.4.1 was released on Oct. 29 2014.

**Comment by bitcoder** [comment]
same here.

/vendor/ruby/2.1.0/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `ensure in with_devise_exclusive_scope': undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x007ffa22271c20> (NoMethodError)
	from /Users/sergio/work/xx/sofa2/vendor/ruby/2.1.0/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `with_devise_exclusive_scope'

**Comment by josevalim** [comment]
Can you provide a sample application that reproduces the error? I am unable to reproduce it locally.
