### ISSUE TITLE
Devise confirmable and subdomains: Can't change the confirmation_instructions.html.erb to generate a confirmation_url with a subdomain url in it.

### ISSUE THREAD

**Issue by userium** [plataformatec/devise#3460]
I'm using Rails 4, ruby 2.1.5 and Devise (3.4.1). I have a problem with the email confirmation link, when using devise confirmable. When a user creates an account, they get an email: 

    You can confirm your account email through the link below:

    http://lvh.me:3000/users/confirmation?confirmation_token=xsTNUw5oQYTPf_CBwZXD

However, it doesn't work since the user's subdomain is not on the link, it should be e.g. 

    http://mysubdomain.lvh.me:3000/users/confirmation?confirmation_token=xsTNUw5oQYTPf_CBwZXD

If I manually add the subdomain link on the browser, it does confirm the account. 

How could I change the confirmation_instructions.html.erb link_to to generate a confirmation_url with the subdomain in front of it? For example:

    <p>Welcome <%= @email %>!</p>

    <p>You can confirm your account email through the link below:</p>

    <p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token, :subdomain => @resource.subdomain) %></p>

I tried e.g. https://github.com/plataformatec/devise/wiki/How-To:-Send-emails-from-subdomains and https://github.com/fortuity/rails3-subdomain-devise/wiki/Tutorial-%28Walkthrough%29 But neither worked for me, I got an error if I use :subdomain => @resource.subdomain in the confirmation_url:

     "NoMethodError in Accounts#create, undefined method `subdomain' for #<User:0x...>"

Here is the create action in my AccountsController:

    def create
      @account = Account.new(account_params)
        if @account.valid? && verify_recaptcha
           Apartment::Tenant.create(@account.subdomain)
           Apartment::Tenant.switch(@account.subdomain)
           @account.save
           @account.create_default_lists
           redirect_to new_user_session_url(subdomain: @account.subdomain)
        else
           render action: 'new'
        end
    end

Here are my routes:

    user_confirmation     POST   /users/confirmation(.:format)                         devise/confirmations#create
    new_user_confirmation GET    /users/confirmation/new(.:format)                   devise/confirmations#new
                          GET    /users/confirmation(.:format)                       devise/confirmations#show

In development.rb I have set, should I somehow add a subdomain setting in front of the host? 

    config.action_mailer.default_url_options = { host: "lvh.me:3000" }

In ApplicationController I have:
  
    protect_from_forgery
    before_filter :authenticate_user!, :set_mailer_host
    
    private

    def current_account
       @current_account ||= Account.find_by(subdomain: request.subdomain)
    end

    helper_method :current_account

    def set_mailer_host
       subdomain = current_account ? "#{current_account.subdomain}." : ""
       ActionMailer::Base.default_url_options[:host] = "#{subdomain}lvh.me:3000"
    end

    end

And here is the error on the console, which I get if I use :subdomain => @resource.subdomain in the confirmation_url. I also tried @resource.account.subdomain, which didn't work either.

    ActionView::Template::Error (undefined method `subdomain' for #<User:0x007fbfcc27e5a0>):
        2: 
        3: <p>You can confirm your account email through the link below:</p>
        4: 
        5: <p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token, **:subdomain => @resource.subdomain**) %></p>
      app/views/devise/mailer/confirmation_instructions.html.erb:5:in `_app_views_devise_mailer_confirmation_instructions_html_erb___2999600516167812245_702'
      app/controllers/accounts_controller.rb:14:in `create'

**Comment by josevalim** [comment]
This is a Rails issue, not a Devise one, since we are simply relying on Rails to send the e-mails.  :) Therefore, you can simply look up for Rails solutions for sending subdomains in e-mails and adapt them with Devise. Here is one for example:

http://stackoverflow.com/questions/19307994/rails-4-actionmailer-subdomain-urls

In case you make it work, we would love if you could take a couple minutes and update the wiki too! Thanks for writing!

**Comment by userium** [comment]
Thanks for your reply @josevalim! I'm using the apartment gem, so I managed to solve this by using 'subdomain: Apartment::Tenant.current'. So I put the following in my confirmation_instructions.html.erb:

<p><%= link_to 'Confirm my account', user_confirmation_url(confirmation_token: @token, subdomain: Apartment::Tenant.current) %></p>
