### ISSUE TITLE
Automatically logging a user in after a password reset

### ISSUE THREAD

**Issue by borski** [plataformatec/devise#3466]
It's fine for this to remain the default, but there should be a configurable option to turn this off. For some, this is a security issue, and they end up having to override the controller and simply remove the one line. Is there a reason this isn't a configurable option? :)

**Comment by josevalim** [comment]
Users that want to customize this behaviour can just provide their own controllers. Devise already has too many options and we cannot provide an option around every behaviour that an action goes about. :)

**Comment by borski** [comment]
josevalim, while normally I would agree with you, I would pose the argument that options for secure defaults should be prioritized over other options. Given that this can be insecure (for example, if using two-factor-authentication) I would argue this is an important option to have. Thoughts?

**Comment by josevalim** [comment]
Good point, I forgot about two-factor auth. A pull request would be welcome! :D Thank you!

**Comment by borski** [comment]
No problem - we wrote the gem and are about to modify the readme with [this](https://github.com/tinfoil/devise-two-factor/pull/20/files) but it's ugly and shouldn't be necessary, which was why this was important to me. :)

Mind re-opening the issue so I can be reminded to pull req?

**Comment by borski** [comment]
Pull req merged, so closing this issue now.
