### ISSUE TITLE
Confirm_by_token as instance method

### ISSUE THREAD

**Issue by artmees** [plataformatec/devise#3469]
I think confirm by token should also be an instance method

In my API users are authenticated by request headers but there is this case

1- `User 1` is not confirmed
2- `User 2` is not confirmed
3- `User 1` clicks on User 2 confirmation link
4- `User 2` is confirmed
5- `User 1` is still not confirmed

this is due to in the confirmation action I'm using
```rb
@user = User.confirm_by_token(params[:confirmation_token])
```
instead of
```rb
@current_user.confirm_by_token(params[:confirmation_token])
```

I think this should be in the scope of current user, since ( it's almost all the time) that the user is required to be signed in to confirm his email...

**Comment by josevalim** [comment]
`confirm_by_token` would be welcome in the instance. A pull request would be welcome!

**Comment by artmees** [comment]
will work on that next weekend (or if I became free before that) :+1:
