### ISSUE TITLE
Possible to put same resource in two namespaces?

### ISSUE THREAD

**Issue by trobrock** [plataformatec/devise#3470]
I'm not sure if this is possible or how. I am trying to do something like the following:

```ruby
scope :api do
  scope :v0 do
    devise_for :users
  end

  scope :v1 do
    devise_for :users
  end
end
```

The problem is that this causes a route name conflict error, I tried adding 'as: :v#' to the scopes, which works, but then causes the current_user helper to be generated as current_v#_user, and I would like those helpers to remain what they were as current_user.

Any help would be appreciated.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
