### ISSUE TITLE
Template path and template name parameter does not work for Devise::Mailer.confirmation_instructions

### ISSUE THREAD

**Issue by datnt** [plataformatec/devise#3472]
Why this code throws error:

    Devise::Mailer.confirmation_instructions(
      @store_user, "",
      {
          template_path: "/app/views/shared/users/mailer",
          template_name: "mytest.html.erb"
      }
      ).deliver

Error content:
Missing template /app/views/shared/users/mailer/mytest.html.erb with "mailer". Searched in:
  * "/app/views/shared/users/mailer"

Although we had created this template at that place already.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by datnt** [comment]
Dear josevalim,

Thank you for your response.

I thought the issue was a bug.

At least you could help by pointing out whether the method I used is supported by devise?

Anyway, you guys did great job.
