### ISSUE TITLE
Overriding registrations_controller and passing a block to new action doesn't eval the block

### ISSUE THREAD

**Issue by smnplk** [plataformatec/devise#3474]
Hi, I am using devise  3.4.1 with rails 4.2. I have created a custom registrations_controller and when I override a method, in my example a new method and pass a block to it, that block is never evaluated. Looking at the source here https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L9, I see that you can pass a block to new method, which is called with yield, but for some reason it doesn't work.. 

    class CustomDevise::RegistrationsController < Devise::RegistrationsController
      def new
           super do |resource|
              puts "I never get called"
            end
       end
    end

My routes are set up correctly, so this is  the correct action that gets fired when I go to /users/sing_up

**Comment by smnplk** [comment]
I just noticed in version 3.4.1 in registrations controller the methods don't accept additional block, https://github.com/plataformatec/devise/blob/v3.4.1/app/controllers/devise/registrations_controller.rb 

So should I use devise from master, or are there better ways to upgrade the behaviour of devise controller actions with code reuse ?

**Comment by josevalim** [comment]
You can use master until we push a new version. :)

**Comment by smnplk** [comment]
This is the route I took. Thanks @josevalim.
