### ISSUE TITLE
mongoid 'authenticate' problem

### ISSUE THREAD

**Issue by bartes** [plataformatec/devise#3477]
I'm not sure yet why but this 

https://github.com/plataformatec/devise/commit/d2658c6e3559d53541f7b69838f9e8fd596dfff9

breaks authenticate_user!(warden.authenticate) at my end (Rails 4.1.x & Mongoid 4.0.1(latest) & devise master, mongo_session_store gem latest)

**Comment by josevalim** [comment]
We need this patch so it works with mongoid in the first place. Given mongoid 4.0.2 will be released soon, I think we will be able to revert it.

**Comment by josevalim** [comment]
Thanks for the report btw!

**Comment by josevalim** [comment]
Reverted, thanks
