### ISSUE TITLE
Question regarding Account Activation

### ISSUE THREAD

**Issue by HatStephens** [plataformatec/devise#3479]
More of a question than a issue. I'm new to development and have used Devise for logins on a few projects now (thank you!).
I am just reading a tutorial about Account Activation (sending an email to confirm the user owns that email address). Will it be possible for me to build in this functionality to Devise or am I missing the point of the simplicity of Devise?
Thanks - and thanks for creating and maintaining such a great gem!

**Comment by josevalim** [comment]
Hey @HatStephens, you are welcome! Thanks for the nice words!

Could you  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by HatStephens** [comment]
No problem @josevalim. Thank you for directing me.
