### ISSUE TITLE
Why Validatable#required_password? checks on nil? instead of blank?

### ISSUE THREAD

**Issue by nicolasblanco** [plataformatec/devise#3482]
Hi there,
this issue is just a question for the Devise mainteneurs.

I would like to know why Validatable#required_password? checks on password nil? instead of blank? ?
https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L54

I'm asking this question just to know the specific reason(s) behind this choice and maybe to write the answer in a comment in the source code.

A common use case in the Rails world is to have the same form to update some user details and password. The behaviour is to update the user details and check for required password only if !blank? not !nil? Because of that, the workaround is to manually delete params in the controller.

Why did you prefer to put the password requirement on nil? ?

Thanks for your answer.

**Comment by josevalim** [comment]
We do this so we only check for a password in case something was actually sent by a form. If you haven't sent anything from a form, we won't trigger it. Deleting the parameters are a necessary workaround (and we do it in update_with_password). Our recommendation is to only update your password with `update_with_password` which would take care of this for you.
