### ISSUE TITLE
Default/preffered way to teach Devise to respond to JSON?

### ISSUE THREAD

**Issue by bikezilla** [plataformatec/devise#3483]
Hi,

I had  an issue with my angular + rails app, where after upgrading to rails 4.2 Devise stopped responding to JSON. 

After some research/debugging I have fixed that by adding
``` ruby
config.navigational_formats = ['*/*', :html, :json]
```
in initializers/devise.rb

However, I have seen many blog posts / SO answers and none mentions this approach. People recommend vairous things such as:
```ruby
config.to_prepare do
  DeviseController.respond_to :html, :json
end
```
or
```ruby
class RegistrationsController < Devise::RegistrationsController  
    respond_to :json
end  
```
and the like.

Questions:
1. What is the preffered way to teach Devise to respond to JSON?
2. Do you think it's a good idea to add this to the readme (it's quite popular these days). If yes I could sign up to contribute it.

**Comment by josevalim** [comment]
Your code is not teaching Devise how to handle JSON. In fact, it is sending
the wrong information because JSON is not a navigational format.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by josevalim** [comment]
The two mentioned solutions are fine, but you can simply call respond_to in your application controller. In any case,  :) Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by bikezilla** [comment]
Yep, I realized my mistake shortly after. Thanks anyways!

**Comment by ratneshnavlakhe** [comment]
What is the solution, facing the same issue...

**Comment by aruprakshit** [comment]
[this blogpost](https://blog.andrewray.me/how-to-set-up-devise-ajax-authentication-with-rails-4-0/) worked for me.

**Comment by sonianand11** [comment]
@bikezilla This [blog works for me](http://www.artechspot.com/blog/customize-devise-sing-in-and-sign-up-to-respond-in-json)
