### ISSUE TITLE
recoverable should be configurable to not expose whether an email exist as user

### ISSUE THREAD

**Issue by fwolfst** [plataformatec/devise#3484]
When recoverable is "activated", and email-addresses are used as users account names, visitors to the page can find out information about who is a potential user of the page by filling in known email addresses to the "Reset Password" form.

When an email address is entered that belongs to a User (I assume defaults here), the messages between "valid email" and "invalid email" differ.

For my application I want to protect users privacy as much as possible. I do not want parents or colleagues (or companies, goverments, hackers ...) to be able to find out whether somebody with a given email address registered for my service or not (although the service itself is not illegal or whatever).

I would like to be able to let the devise controller behave the same irrespective of the presence of a given email address (redirect to login page with a flash notice ~ "If that email is registered, password reset instructions will be mailed to it within the next minutes").

**Comment by josevalim** [comment]
Isn't that what config.paranoid mode is for? :)

**Comment by fwolfst** [comment]
Oh thanks josevalim and god, it is :)
