### ISSUE TITLE
Possible bug with devise running under a namespace?

### ISSUE THREAD

**Issue by Advocation** [plataformatec/devise#3485]
First off, apologies if this isn't a bug and I'm just missing something.

I have a User model, with the `devise` declaration.
My routes file looks like this:
```
namespace 'app', path: '', constraints: { subdomain: 'app' } do
    devise_for :users, :skip => [:registrations, :confirmations]
    devise_scope :user do
      get 'login' => 'users/sessions#new'
    end
    ...
end
```

`rake routes` returns this:
```
app_login GET    /login(.:format)                   app/users/sessions#new {:subdomain=>"app"}
```

but when I visit the `/login` page in my browser, I get the following error:
```
Could not find devise mapping for path "/login".
This may happen for two reasons:

1) You forgot to wrap your route inside the scope block. For example:

  devise_scope :user do
    get "/some/route" => "some_devise_controller"
  end

2) You are testing a Devise controller bypassing the router.
   If so, you can explicitly tell Devise which mapping to use:

   @request.env["devise.mapping"] = Devise.mappings[:user]
```

Now, as you can see I'm already wrapping the route inside of the devise_scope, and this isn't a test.. so I'm rather confused! Is this an issue with running it inside of a namespace?

**Comment by georgeguimaraes** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by emilford** [comment]
@Advocation Were you able to figure this out? I've run up against the same behavior.

**Comment by bilouw** [comment]
Hello ! Someone know how to handle this case ? (devise_for in a namespace)

I have the same issue, and it's seems to be a pretty old one !
