### ISSUE TITLE
"Email can't be blank" in password reset

### ISSUE THREAD

**Issue by mikeki** [plataformatec/devise#3488]
I have no idea how to fix this, I tried adding email with the strong params suggestions, no luck....

I can't seem to figure out why this is happening and this is making me crazy :(

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by therise3107** [comment]
this is just an example 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password,:password_confirmation)}
  end
you are missing :email, add it and it will work fine

**Comment by mikeki** [comment]
I did added email, it is not working and that's why I opened this issue :/

**Comment by mike0416** [comment]
Did you change your form method to put?  That route has a get method, which is invoked unless specified.
