### ISSUE TITLE
How to prevent clearing data in registration form in rails 4

### ISSUE THREAD

**Issue by melsatar** [plataformatec/devise#3490]
All data cleared, If one of sign up entry is wrong. Any solution to prevent this?

**Comment by melsatar** [comment]
Any idea please

**Comment by Sivan1525** [comment]
@melsatar the easiest approach for this can be use of client side validations to check for validations like http://jqueryvalidation.org/ for this.

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
