### ISSUE TITLE
Couldn't make changes in users/session/new file in rails used with devise.

### ISSUE THREAD

**Issue by rajkiran** [plataformatec/devise#3491]
I installed devise in my application and signup, signin and all the actions are working fine. 
I just replaced my heading from "Log in" to "sign in", it is not affected in the application. 
Please help me out.

This is the command i run after installing  devise

**$ rails generate devise User**

users/sessions/new:

**<h2> Sign in </h2>**

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true %>
      </div>
    
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
    
      <div class="actions">
        <%= f.submit "Log in" %>
      </div>
    <% end %>
    
    <%= render "users/shared/links" %>

routes.rb:

      devise_for :users

And i haven't created any controllers for devise.

**Comment by therise3107** [comment]
what exactly is the error? everything seems fine , i guess you mean you want to add additional field in your login page 
for this you have to add this code in your application_controller.rb after generating migration to your user model 
by 
    rails g migration add_usename_to_users username

now add this code to application_controller.rb 
    before_action :configure_permitted_parameters, if: :devise_controlller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_in) << :username(or any custom field)
    end

**Comment by h1k3n** [comment]
Did you generate views right after that using 'rails g devise:views users'?  This creates the views in app/views/users folder insted of the default /app/views/devise/users.  Any changes you make to this file won't be seen in your app, you maybe generate them in the default folder?

**Comment by Sivan1525** [comment]
@rajkiran As @h1k3n told generate views for devise using **rails g devise:views** so that you will be generating *app/views/devise/sessions/new.html.erb* file and any changes you make here will be reflected on the browser .
