### ISSUE TITLE
Resetting session after login

### ISSUE THREAD

**Issue by ncri** [plataformatec/devise#3494]
I read claims that devise resets the session after logging in to prevent session fixation. 
Can someone point me to the place in the source, or to a page documenting this? Or both? ;-) 
Thanks!

**Comment by josevalim** [comment]
The code is in the warden project. It sets :renew true in the session store every time someone signs in.

Btw,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ncri** [comment]
okay, thanks!
