### ISSUE TITLE
Custom mailer doesn't works

### ISSUE THREAD

**Issue by rusikf** [plataformatec/devise#3497]
I tried [this instruction from wiki](https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer) with the latest devise release gem version and git version
In config/02_devise.rb I have
```ruby 
class CustomMailer < Devise.parent_mailer.constantize
  def confirmation_instructions(record, token, opts={})
    binding.pry
  end
  helper :application # gives access to all helpers defined within `application_helper`.
  include Devise::Controllers::UrlHelpers # Optional. eg. `confirmation_url`
  default template_path: 'devise/mailer' # to make sure that your mailer uses the devise views
end  
Devise.setup do |config|
 config.mailer = 'CustomMailer'
 ...
end
```
A am also creating for debuging ```app/mailers/devise.mailer.rb``` like this
( i am tryied as described in wiki ```class Devise::Mailer < Devise::Mailer```   too )
```ruby
require 'pry'
if defined?(ActionMailer)
  class Devise::Mailer < Devise.parent_mailer.constantize
    include Devise::Mailers::Helpers

    def confirmation_instructions(record, token, opts={})
      binding.pry
      super
      @token = token
      devise_mail(record, :confirmation_instructions, opts)
    end
    
  end
end
```
So , when i restart rails server and run in console something like this:
```
User.last.send_confirmation_instructions

```
Letter is sended and i have binding in ```app/mailers/devise.mailer.rb``` , i run exit and **custom mailer doesn't binding**
I have rails 3.2.13

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by rusikf** [comment]
@josevalim , thanks for response! I find the problem : i have in application rb 
```ruby
module Wrapper
  class Application < Rails::Application
  ...
  end
end
```
That why , initialzers doesn't work, i added something like this( or wrap devise config in Wrapper namespace in seperate config)
```ruby
module Wrapper
   Devise.setup do |config|
    config.mailer = 'CustomMailer'
  end  
  class Application < Rails::Application
  ...
  end
end
```
And it works!
