### ISSUE TITLE
Rotating secret_key

### ISSUE THREAD

**Issue by theuri** [plataformatec/devise#3498]
I'd like to rotate our devise secret_key on a regular basis, and can't seem to find any documentation about whether key rotation is supported or will break core Devise functionality. Is it ok to rotate our secret_key regularly or is this not recommended?

**Comment by josevalim** [comment]
It is ok except it expire all existing sessions.  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by theuri** [comment]
Thanks for the quick response, Jose. I didn't know there was a mailing list - I'll use this in the future. Thanks!
