### ISSUE TITLE
Undefined method user_url when checking if a user is valid

### ISSUE THREAD

**Issue by Linuus** [plataformatec/devise#3499]
Hi!

I know the `Undefined method user_url` issue has been discussed several times before, see https://github.com/plataformatec/devise/issues/3186, https://github.com/plataformatec/devise/issues/3444

I found the source of MY issues today I believe. I'm not sure if this should be fixed in Devise though or if it is a limitation of Rails. But at least it gets documented here and may help someone else.

I have my own `RegistrationsController` which inherits from `Devise::RegistrationsController`. I got the error `Undefined method user_url` sometimes and finally found that it occurs when the user is updated but the password is wrong.

The issue is that I override the `update` action in my controller and run super with a block. In this block I, among other things, check if the user is valid. Something like this

```ruby
class Users::RegistrationsController < Devise::RegistrationsController
  # stuff...

  def update
    super do |user|
       # do stuff to user
       user.valid?
     end
  end
end

# more stuff
````

The issue here lies in the `.valid?` method call.

When a user is updated, devise calls the `update_with_password` method. It checks the passwords and adds an error for it.
See: https://github.com/plataformatec/devise/blob/65700b22bab0746a40358dacb32197280acf2888/lib/devise/models/database_authenticatable.rb#L84

So, when I call `.valid?` in my block above, ALL validation errors are cleared (because that's how ActiveModel does it...). Hence, the password error is lost, which makes us end up here:
https://github.com/plataformatec/devise/blob/394d69d9584fea1d9cceb3930be833cbc4425f4c/app/controllers/devise/registrations_controller.rb#L60

```ruby
respond_with resource
```
Which, since there are no errors, tries to redirect to `user_url` which does not exist.

To avoid loosing the password error it must be added in a validation, so it is executed when you call `.valid?`.

1. Do you consider this as something to fix in Devise?
2. Is it possible to move the password validation thing into a validation?

**Comment by josevalim** [comment]
No, we cannot fix it in Devise. :) You shouldn't call `user.valid?`, exactly because of what you have found out. Instead, simply check `user.errors.empty?`. Thanks for the report!

**Comment by Linuus** [comment]
Yes, that's what I ended up doing.

Well, hopefully this issue will help someone else :)

Cheers!

**Comment by reiz** [comment]
I'm getting the same error and I'm not using devise.
