### ISSUE TITLE
Recoverable - Can I supply my own recovery strategy: i.e. sending a verification code/new password to user's cellphone, instead of using email?

### ISSUE THREAD

**Issue by x-ji** [plataformatec/devise#3501]
It seems that `devise` is heavily built around email. However in some developing countries, a lot of users don't use emails at all and prefer to do the verification by SMS verification codes. It seems to be possible to allow users to sign in using something other than email address. However is it possible for the user to recover his/her password by cellphone as well?(i.e. just sending the new password to his/her phone by a SMS service).

Also, it is not clear to me from https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address whether I can ditch email field in the sign up form altogether, or just make it *not mandatory*, but still there?

If the above cannot be achieved, then probably the better solution for me would to build my own authentication system instead of using `devise`?

Thanks!

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
