### ISSUE TITLE
current_user nil after successful sign_in while using mongoid and devise

### ISSUE THREAD

**Issue by claudeomusic** [plataformatec/devise#3506]
for context, i'm using devise 3.4.1, mongoid 4.0.0, rails 4.1.7

when i sign in (successfully), i am redirected to the root path as dictated by my after_sign_in_path_for. from here, i assume my user is signed in. however, once i navigate to another page that references current_user in a controller method, i get an error like so:
```
undefined method `searches' for nil:NilClass
Extracted source (around line #6):

@current_search = current_user.searches.build

if(params[:role].present?)
  @current_search.add_condition(role: "#{params[:role]}")
```
to try to further understand the problem i debugged the session and everything seems to be okay:

```
{"session_id"=>"bbae2e07d3d3e506ad662410b23cefb7",    
"warden.user.user.key"=>[["54f787e0636c612b75ba0000"], 
"$2a$10$xvDkF6vFs.bHAa3rjsvPR."], 
"flash"=>{"discard"=>[], "flashes"=>{"notice"=>"Signed in 
successfully."}}, 
"_csrf_token"=>"/OVXffT6+er8OipE47/gOs0w9mbK9s/XqgwFOyiSumA="}
```

earlier on i had an issue with mongoid/devise that was fixed with the serialization hack.. this is not the same problem, i don't think? 

some other's who seemed to have a similar problem seemed to just be able to fix it with a call to before_action :authenticate_user!, but in my case it just generates a 401 Unauthorized error and redirects the user to the login page again with the dialog of You need to sign in or sign up before continuing.

**Comment by carlosantoniodasilva** [comment]
Can you please provide a sample app that reproduces the problema? Thanks.

**Comment by claudeomusic** [comment]
actually, solved it! 

the problem/solution lied in the hack... so for awhile i'd been using this successfully:

def self.serialize_from_session(key, salt)
    record = to_adapter.get(key[0]["$oid"])
    record if record && record.authenticatable_salt == salt
  end

but i had to replace it with

def self.serialize_into_session(record)
    [record.id.to_s, record.authenticatable_salt]
end

would love to better understand what's going on here? i don't actually understand what's going on

**Comment by josevalim** [comment]
Mongoid broke ActiveModel/Devise compaibility a while ago and it seems they have restored it back. The previous hack was relying on internals which likely changed again. You can likely get rid of this method altogether.

**Comment by claudeomusic** [comment]
Thanks for the help!

**Comment by claudeomusic** [comment]
Thanks!

Christopher Changchien
Singer/Songwriter, Music Production
chris.changchien@gmail.com
(805) 312-6521
http://www.claudeo.com
