### ISSUE TITLE
Overwrite the 'you need to confirm' message

### ISSUE THREAD

**Issue by qwel3** [plataformatec/devise#3509]
This devise error message say:
You have to confirm your email address before continuing.

I don't like the wording and would like to change it. I went to the source code and changed it to what I want, but for some reason the changes were not made. I don't want that approach anyways because it's not suitable. How do I overwrite the message in Rails and write the message I want? Thank you

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
