### ISSUE TITLE
Rememberable compatibility with Mongoid 4.0.2

### ISSUE THREAD

**Issue by ethan605** [plataformatec/devise#3510]
When using RailsAdmin (`~> 0.6.5`) with Devise (`~> 3.1.4`) and Mongoid (`4.0.2`), there is a glitch at Devise's Rememberable module (`lib/devise/controllers/rememberable.rb` : `37`): the return result of `resource.class.serialize_into_cookie(resource)` method:

* instead of being something like this `[[{"$oid"=>"5461d6a6646562737c030000"}], "$2a$10$n7p24ua6BaObTfmo3Ky1Ju"]`
* but now returned by Mongoid `4.0.2` like this: `[["5461d6a6646562737c030000"], "$2a$10$n7p24ua6BaObTfmo3Ky1Ju"]`

This mismatch of data leads to `cookies.signed[remember_key(resource, scope)]` is set be `nil` all the way and users can not log-in to RailsAdmin system (`remember_#{scope}_token` in cookies is not created)

**Comment by josevalim** [comment]
The glitch is in mongoid which changes how its id was represented due to an earlier bug. You can likely provide your own customization of the method that works around this error by suporting both values temporarily: https://github.com/plataformatec/devise/blob/master/lib/devise/models/rememberable.rb#L124-L128

**Comment by ethan605** [comment]
Hi, the problem doesn't end here.

As what @josevalim mentioned above, I've added these lines into `config/initializers/devise.rb` to bypass `Mongoid 4.0.2` changes. Of course it works and I can login to my RailsAdmin again.

```
# Workaround due to issue https://github.com/plataformatec/devise/issues/3510
module Devise
  module Models
    module Rememberable
      module ClassMethods
        # Create the cookie key using the record id and remember_token
        def serialize_into_cookie(record)
          # Old
          # [record.to_key, record.rememberable_value]

          # New
          [[record.id], record.rememberable_value]
        end
      end
    end
  end
end
```

But the weird thing is, I can't login without checking `Remember me` option. Further more, sometimes RailsAdmin can't save properly because of the CMS is unauthorized in the middle, as logged here:

```
INFO -- : Started PUT "/cms/my_model/54d4ceac4574683f54d42100/edit" for x.x.x.x at 2015-03-24 10:33:41 +0700
INFO -- : Processing by RailsAdmin::MainController#edit as HTML
INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"7R691K7Mnw7waoo6gMXGLr5htziLIfHvYMguxp2pbvE=", ...}
WARN -- : Can't verify CSRF token authenticity
INFO -- : Completed 401 Unauthorized in 1ms
INFO -- : Started GET "/admins/sign_in" for x.x.x.x at 2015-03-24 10:33:41 +0700
INFO -- : Processing by Devise::SessionsController#new as HTML
INFO -- : Redirected to http://my.domain.com/
INFO -- : Filter chain halted as :require_no_authentication rendered or redirected
INFO -- : Completed 302 Found in 14ms
INFO -- : Started GET "/" for x.x.x.x at 2015-03-24 10:33:41 +0700
INFO -- : Started GET "/cms" for x.x.x.x at 2015-03-24 10:33:41 +0700
```
When I try to update `my_model` via `PUT` method, I can't authorize the system. It redirects to the home page, and because I was remembered before, I'm advanced to the RailsAdmin dashboard.

When I try to downgrade Mongoid to `4.0.0`, the problem's gone.

Anyone have any idea?
