### ISSUE TITLE
Asking for email when generating confirmation instructions?

### ISSUE THREAD

**Issue by fabrouy** [plataformatec/devise#3514]
Hey guys,

Is there a reason for asking the user to input his email when trying to resend confirmation instructions that I am not seeing?

The user needs to be authenticated in order to be able to ask the system to resend confirmation instructions right? So why not sending the confirmation instructions to the logged in user's email?

Is there a way then to remove the user_email field and resend confirmation instructions just clicking the button?

Cheers,

**Comment by teknull** [comment]
I can't speak for the team as to why this decision was made, but you can easily override this in the view by passing in `current_user.email` and hide the div with the form.  This can also be passed into the controller but it may get a bit messy. 

I'm curious to see why the email field is displayed considering the user has already been authenticated.  I could see it from a security-oriented standpoint but from a UX view it's a bit unnecessary, I think.

**Comment by josevalim** [comment]
> The user needs to be authenticated in order to be able to ask the system to resend confirmation instructions right? 

No, that's the wrong assumption here. Many times websites expect user to confirm their account before being able to use it. :)

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
