### ISSUE TITLE
Warden, devise and active record session store updated_at routine 

### ISSUE THREAD

**Issue by phlegx** [plataformatec/devise#3515]
Hi!

I use Warden, Devise and ActiveRecord-Session-Store. I try to understand where the ```updated_at``` database session table attribute gets updated after a Rails request. I cannot find the begin of this routine. Is this done in Warden or Devise? Any idea? I want to add ```updated_at``` value to the session variable.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
