### ISSUE TITLE
Create user from data base

### ISSUE THREAD

**Issue by pedrohandcom** [plataformatec/devise#3516]
How can I create a user Devise from MySql Stored Procedure?
Ty!

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by pedrohandcom** [comment]
http://stackoverflow.com/questions/29101859/create-user-from-data-base-using-devise-rails

for those who want to follow
