### ISSUE TITLE
helper methods only when devise_for defined in root

### ISSUE THREAD

**Issue by AntonTrapp** [plataformatec/devise#3521]
```
devise_for :user
```

must be defined in root, if you use it unter /api/v123 you get no access to the authenticate_user! and other helpers.

**Comment by josevalim** [comment]
If you define it under /api/v123 or inside a namespace, it will have that namespace options. For example, it will be authenticate_api_user! and so on. Please check the generated routes with rake routes.

**Comment by AntonTrapp** [comment]
Thank you for your fast answer. But isn't it very ugly and un-DRY to define the API version number anywhere outside the routes.rb?

**Comment by josevalim** [comment]
@AntonTrapp you can pass the :as option when calling devise_for or path to make things easier. We behave as any Rails helper, the options are there for you to customize it.

**Comment by AntonTrapp** [comment]
*lol* - I should get more sleep - do you have a paypal email address for a virtual beer?

**Comment by josevalim** [comment]
Thank you for the offer! If you are willing to compensate us somehow we would love if you could donate to a charity then, charity:water is a common one for Rails projects: https://donate.charitywater.org/donate

Thank you!

**Comment by AntonTrapp** [comment]
done!

Am 18.03.2015 um 08:55 schrieb José Valim <notifications@github.com>:

**Comment by rafaelfranca** [comment]
@AntonTrapp  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
