### ISSUE TITLE
Password reset always sent to first user

### ISSUE THREAD

**Issue by alex88** [plataformatec/devise#3522]
Hello,

I'm using devise 3.4.1 on rails 4.2, it seems that the recovery email is always sent to the first user,

e.g. I've 2 users, second one has email `alessandro@visup.it`, this is the log from rails server when requesting password reset email:

```
Started POST "/users/password/" for 127.0.0.1 at 2015-03-18 10:56:49 +0100
Processing by Devise::PasswordsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"6L3XinmHHceIKXz5nO2FzMmb5Mb0TBk7TbSi7hVQZMYYi+xwsEiHe6WiYcBwMzzw28HUjM0FdzXIpn4Y95n87w==", "user"=>{"email"=>"alessandro@visup.it"}, "commit"=>"Reset my password"}
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["reset_password_token", "f54d11486dd562b8fc544c64af36718fb7e4ec3ca3fc0ce7144b3688313f255b"]]
   (0.1ms)  BEGIN
  SQL (0.2ms)  UPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4  [["reset_password_token", "f54d11486dd562b8fc544c64af36718fb7e4ec3ca3fc0ce7144b3688313f255b"], ["reset_password_sent_at", "2015-03-18 09:56:49.732271"], ["updated_at", "2015-03-18 09:56:49.733089"], ["id", 1]]
   (0.3ms)  COMMIT
Redirected to http://localhost:3000/users/sign_in/
```

it seems it's not loading the user correctly since it's not searching it by email, trying to debug inside the passwords controller these are the variables set:

```
resource_params = {"email"=>"alessandro@visup.it"}
resource_class = User
```

I haven't overridden the password controller, just using the default ones

Update: I've tried to manually set `config.reset_password_keys = [ :email ]` but nothing changed

`User.find_or_initialize_with_errors` is called with arguments [:email], { 'email': 'alessandro@visup.it' }

**Comment by josevalim** [comment]
This is very weird.  Can you please provide a sample application that reproduces the error?

**Comment by alex88** [comment]
@josevalim I'm actually debugging with byebug inside calls to find the user, give me a second and if it's not a configuration issue on my side I'll create a sample app

**Comment by alex88** [comment]
Ok found the issue, is on my own side, `find_first_by_auth_conditions` method has been implemented this way:

```
  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
  # Permit login via both email and username
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
```

With conditions like `{ 'email': 'alessandro@visup.it' }` it becomes `{}` when using `.to_h` in the else line

So it's an issue on my own code, sorry for opening it! :wink:

**Comment by alex88** [comment]
Changing to just `conditions` I get `ActiveModel::ForbiddenAttributesError` but that's another issue I've to solve
