### ISSUE TITLE
Authenticate with attributes from associated model (User belongs to Client)

### ISSUE THREAD

**Issue by robotex82** [plataformatec/devise#3524]
I have following models:

    # app/models/user.rb
    User < ActiveRecord::Base
      belongs_to :client
    end 

    # app/models/client.rb
    Client < ActiveRecord::Base
      has_many :users
      validates :identifier, presence: true
    end

I've overridden the session controller to use a different view with the suiting form inputs:

    # new.html.erb
    ...
    <div class="form-inputs">
      <%= f.fields_for :client do |c| %>
        <%= c.input :identifier, :required => true, :autofocus => true %>
      <% end %>
      <%= f.input :email, :required => false %>
      <%= f.input :password, :required => false %>
      <%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
    </div>
    ...

What would the correct way to get the user to authenticate with a client identifier in addition to the email address?

Thanks in advance!

Best regards
Roberto

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by robotex82** [comment]
Ok, thank you!
