### ISSUE TITLE
Unable to login in to Active Admin

### ISSUE THREAD

**Issue by michaelstokes** [plataformatec/devise#3528]
Hello,

Since modifying Devise, I seem to no longer be able to login to Active Admin with the default 
email: admin@example.com and password: password. 

I get the error: Invalid login or password.

I followed this guide to add username to users:
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

Thank you for all your help :)

Michael

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by josevalim** [comment]
Also, if you have any questions,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
