### ISSUE TITLE
undefined method `to_key' for {:store=>false}:Hash when using sign_in helper

### ISSUE THREAD

**Issue by razasayed** [plataformatec/devise#3532]
I have the following code in my spec 

```ruby
  describe "DELETE #destroy" do

    before(:each) do
      @user = FactoryGirl.create :user
      sign_in @user, store: false
      delete :destroy
    end

    it { should respond_with 204 }

  end
```

This gives me the error ```undefined method `to_key' for {:store=>false}:Hash```. I have added ```config.include Devise::TestHelpers, :type => :controller``` in my spec/rails_helper.rb file.

**Comment by carlosantoniodasilva** [comment]
The sign in helpers accepts no options, [it's either the resource or the scope + resource](https://github.com/plataformatec/devise/blob/master/lib/devise/test_helpers.rb#L42=L45). Which means `store: false` is understood as the user object, thus the error. You can just remove it and it should work.

Just wondering, is there any particular reason for you to try to use that?

**Comment by seanoshea** [comment]
Following along with http://apionrails.icalialabs.com/book/chapter_five, it appears that the `store:false` param is unnecessary. Perhaps this could be the root of this?

**Comment by MattSPalmer** [comment]
It's certainly the root of it for me. In general I've found multiple places where the book is pretty out-of-date.
