### ISSUE TITLE
extracting password encryption to separate gem

### ISSUE THREAD

**Issue by equivalent** [plataformatec/devise#3534]
I'm in middle of extracting out Devise and replacing it with custom solution in one application I'm maintaining (due to variouse business rules, and stupid security concerns that I cannot fight) 

One thing I'll (obviously) have to keep is the way how passwords are crypted. That's why I'm extracting some core devise features to little gem [devise_password_encrypter](https://github.com/equivalent/devise_password_encrypter) (still in progress) so I'll just build my busines logic around way how Devise was storing password.

After I'm done with the application I'm planing to create a PR to Devise gem so that the way how Devise encrypts and compare password would be just injected dependency. So teoretically developers can create custom engines build upon other libraries not just BCrypt.

My question is: will you find this feature helpfull ...or should I save time and not to do that.

I'm planing to do that on:

https://github.com/plataformatec/devise/blob/65700b22bab0746a40358dacb32197280acf2888/lib/devise/models/database_authenticatable.rb

* `Devise::DeviseAuthenticable#valid_password?`
* `Devise.bcrypt(raw)`

anything else related to `bcrypt` I've not discovered yet

I'm also thinking about including also secure token generating (maybe part of this or diferent gem)
`raw, enc = Devise.token_generator.generate(self.class, :invitation_token)`

**Comment by josevalim** [comment]
Question: wouldn't using devise_encryptable solve your issues? It already abstracts what you want to abstract. :)

**Comment by equivalent** [comment]
ah ok, bit different from what I wanted to introduce but I can use it :) 
thx
