### ISSUE TITLE
confirmation token always invalid

### ISSUE THREAD

**Issue by aldajulian** [plataformatec/devise#3535]
i use devise version 3.4.1 and i also read this wiki https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users

but when i test it, i always get invalid token.
i try to devise method http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Confirmable/ClassMethods:confirm_by_token,
and this is what i get:

original_token     = params[:confirmation_token] "2e9a6a4d505e2c7b225fdec6a3fa524d63105618674333e0ebc64edcd87c0c8f"

confirmation_token = Devise.token_generator.digest(self, :confirmation_token, params[:confirmation_token])

"f42574d98aaa3455e3999e546504c61be7fe6a4888ee4f095fff144800534aef"

confirmable = User.find_or_initialize_with_error_by(:confirmation_token, confirmation_token)

User id: nil, name: nil, about: nil, created_at: nil, updated_at: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "f42574d98aaa3455e3999e546504c61be7fe6a4888ee4f095f...", confirmed_at: nil, confirmation_sent_at: nil, unconfirmed_email: nil, authentication_token: nil, image: nil, location: nil, username: nil, invitation_token: nil, invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil

User.last

User id: 14, name: "Alda Julian", about: "", created_at: "2015-03-24 20:05:51", updated_at: "2015-03-24 20:25:42", email: "aldajulian@xxxxx.com", encrypted_password: "$2a$10$Jlg5oL3jeG3vfxhrQmmYvebnKf.c5FPIvpzUcxY3VJo...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "2e9a6a4d505e2c7b225fdec6a3fa524d63105618674333e0eb...", confirmed_at: "2015-03-24 20:14:09", confirmation_sent_at: "2015-03-24 20:25:42", unconfirmed_email: nil, authentication_token: nil, image: "black-logo.png", location: "", username: "aldajuli", invitation_token: nil, invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil

The registered user token with params token is same but why?

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by LTe** [comment]
Hi @aldajulian!

I have the same problem as you! Since devise 3.1.0 (https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#310---2013-09-05) tokens are not stored directly in database. Because of that mailer templates changed as well (https://github.com/plataformatec/devise/commit/143794d701bcd7b8c900c5bb8a216026c3c68afc#diff-6909b6f56fb271baaecf5e7ef68425d9L5).

You need to delete old templates (probably `app/views/devise/mailer`) or re-generate them by `rails generate devise:views`.

**Comment by aldajulian** [comment]
Hi @LTe thanks for your help!

my bad i generate double devise view, i change on another view.
