### ISSUE TITLE
Overridden devise views render with the wrong layout

### ISSUE THREAD

**Issue by peterept** [plataformatec/devise#3536]
I have generated a custom view for sessions. And a custom sessions controller:

class SessionsController < Devise::SessionsController
..
end

When that controller is rendered it uses my main application layout, instead of the default devise one. Other devices views/controllers I have not overriden still render with devises layout.

**Comment by carlosantoniodasilva** [comment]
They render with devise layouts because Rails defaults the rendering to the current namespace, ie `devise` in that case, before falling back to `application`. Since you've overridden the controller and it's not under the same namespace anymore, it won't pick `devise` as the layout, but you can just do it by adding to your controller:

```ruby
layout 'devise'
```

That should work, hope that helps.

**Comment by peterept** [comment]
Hi, I did try that, and it fails because it is still looking for it in the layouts folder:

` ActionView::MissingTemplate (Missing template layouts/devise with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:`

I also tried adding a namespace to my overriden controller:

`class Devise::MySessionsController < Devise::SessionsController
  layout "devise"`

But same error, still looking in layouts.

(I ended up creating my own layout for all my devise views)

**Comment by carlosantoniodasilva** [comment]
Hm but shouldn't it be looking in `layouts/devise`? That's the correct place to look for layouts, right? Devise does not provide any specific layout by itself, it's up to the app to define it. I think I might be missing something, sorry, maybe you can give a bit more context on what's going on, or create a sample app that demonstrates the problem?
