### ISSUE TITLE
`config.password_length` max is being ignored

### ISSUE THREAD

**Issue by jonathansimmons** [plataformatec/devise#3538]
Had a user recently complain about our 20 character password limit. Thing is our `password_length` in the config/initializers/devise.rb config is set to `config.password_length = 6..128`.

Seeing [this](https://github.com/plataformatec/devise/pull/3319) pull request made me try reducing it to `config.password_length = 6..72` but that didn't make a difference. After some testing in the ruby console it appears that regardless of what I set the config to I get an error on any password over 20 characters. 

====

Rails: 4.2.0
Ruby: 2.1.2
Devise: 3.4.1

```
Loading development environment (Rails 4.2.0)
2.1.2 :001 > u=User.new(firstname: "fake", lastname: "user", email: "fake@email.com", password: "1111-1111-1111-1111-1111")
 => #<User id: nil, uid: nil, email: "fake@email.com", current_company_id: nil, firstname: "fake", lastname: "user", current_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_at: nil, last_sign_in_ip: nil, encrypted_password: "$2a$10$qdE7k2TZ4lvFKiAn.3CleuA7NeV7wJ5Cio8VVbgo5M/...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, authentication_token: nil, confirmation_token: nil, confirmed_at: nil, confirmation_sent_at: nil, client_columns: {}, community_email: nil, failed_attempts: 0, unlock_token: nil, created_at: nil, updated_at: nil, locked_at: nil, sidebar_collapsed: false, per_page: 50, time_zone: nil> 
2.1.2 :002 > u.valid?
  User Exists (2.5ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'fake@email.com' LIMIT 1
 => false 
2.1.2 :003 > u.errors.messages
 => {:password=>["is too long (maximum is 20 characters)"]} 
2.1.2 :004 > 

```

While the min_length can't be set lower than 6 I am able to change it. i.e. increasing it to 10..72 correctly errored on passwords less than 10 characters.

**Comment by josevalim** [comment]
Are you using validatable or do you have your own validations?

**Comment by jonathansimmons** [comment]
Using validatable.

**Comment by josevalim** [comment]
This is very weird, we definitely use the configuration (https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L35) and we also have tests.

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jonathansimmons** [comment]
I'll try to put something together later today.

**Comment by jonathansimmons** [comment]
And as it turns out there in fact was a customer model validator that I missed. Sorry for the trouble.
