### ISSUE TITLE
paranoid + registration

### ISSUE THREAD

**Issue by ninja-** [plataformatec/devise#3540]
Documentation says that paranoid doesn't affect registration.
Does it 'leak' emails? Does the registration form allow to check if email is already registered?
Are there no 'you have been registered, if you wasn't registered before' kind of message?

**Comment by ninja-** [comment]
"email has already been taken" that makes whole paranoid mode useless

**Comment by ninja-** [comment]
so...I have a nice way to solve it.
we could display "Thanks for registration. Please check your e-mail inbox to activate your account!" and a different e-mail template when user is already registered saying like, "You have requested registration but you are already registered. If you don't remember your password, please use the password reset option. If you haven't confirmed your registration, please request a new activation link." 

the second message would need a limit to avoid spam, for example one every 10 minutes, with date stored in DB.

@josevalim

**Comment by josevalim** [comment]
The validatable module is just a convenience. If you want a custom
validation ir behavior for uniqueness, just don't use it, and provide your
own validations. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by ninja-** [comment]
@josevalim I think you missed my point :/

**Comment by monfresh** [comment]
:100:  for allowing paranoid to work with registerable. I don't agree with the Wiki saying that it's not possible to make paranoid work with registerable. In a project I'm working on, we've come up with a workaround that sounds very much like what @ninja- is proposing. It would be great to have Devise do this by default.

Here's what we are doing:

1. Check to see if the resource has errors and if the error was that the email is already taken
2. If so, we invoke a UserMailer to send an email that says something like "Someone attempted to sign up with your email, but your email is already in use. If you tried to sign up, click here to sign in. If you didn't attempt to sign up, ignore this message."
3. Show a flash notice that the email hasn't been confirmed yet
4. Redirect to root_path

**Comment by josevalim** [comment]
Thanks @monfresh for the write up! The wiki is maintained by the community, so your additions on the topic would be very welcome.

Your comments prove exactly my point: Devise ships with a default registration + validation flow but they are conveniences. You are supposed to customize and extend it to whatever makes most sense to your application. There are only a finite amount of configuration knobs we can provide in Devise without going insane.

**Comment by monfresh** [comment]
Understood. Given that more and more people are concerned about security and privacy these days, I was just suggesting that perhaps Devise might want to take a "secure and private by default" stance and turn on paranoid mode by default, including compatibility with registerable.

I suppose I could write up instructions in the Wiki or create a gem, but I thought it would benefit the community for Devise to do this by default. If I had to guess, I would think that most people would want paranoid mode on versus off.

**Comment by josevalim** [comment]
@monfresh I do not agree with your conclusion. :) It is hard to make everything secure and usable at the same time and paranoid mode is walking on this very line.

The benefit of paranoid mode is when revealing that you belong to a particular site in itself is harmful. For example, I may not want online gambling websites to reveal I am part of them. But for the huge majority other services, including intranets, such confirmation poses no risks and being able to give useful and clear messages to users is preferable: it is more important to tell the users they already have an account in contrast to telling them to check their e-mail.

I know that not everyone agrees here though and more education around paranoid certainly doesn't hurt, but I wouldn't toggle the defaults.

**Comment by garyfoster** [comment]
Seems like with just a little more effort, the paranoid mode could seal up this last hole and actually make it do what is intended. I'm about to override the registrations controller to implement monfresh's idea, would be awesome to see the code to save a few minutes.
