### ISSUE TITLE
add the line:  devise for :users in routes.rb, after rake db:migrate, will appear the problem

### ISSUE THREAD

**Issue by rackjun** [plataformatec/devise#3546]
the tip of problem is like this:
NoMethodError: undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x00000002daa118>

.rvm/gems/ruby-2.2.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `ensure in with_devise_exclusive_scope'
.rvm/gems/ruby-2.2.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `with_devise_exclusive_scope'
.rvm/gems/ruby-2.2.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:246:in `block (2 levels) in devise_for'
.rvm/gems/ruby-2.2.1/gems/devise-3.2.4/lib/devise/rails/routes.rb:349:in `block in devise_scope'

my environment is ruby 2.2.1, rails 4.2.1
thanks!

**Comment by josevalim** [comment]
This has been fixed in more recent devise versions.
