### ISSUE TITLE
CustomFailure and mount (sidekiq), bad redirect

### ISSUE THREAD

**Issue by allaire** [plataformatec/devise#3548]
Hi guys,

I'm using a CustomFailure like shown in the doc to redirect to our sign in page when someone is unauthenticated:

```ruby
class CustomFailure < Devise::FailureApp
  include Localization

  def redirect_url
    url_for(controller: "/public/sessions", action: :new, locale: locale_to_params(I18n.locale))
  end

  # You need to override respond to eliminate recall
  def respond
    if http_auth?
      http_auth
    else
      redirect
    end
  end
end
```

So this normally redirects to `http://www.acmecorp.com/en/signin`, but with the Sidekiq panel in `routes.rb`:

```ruby
  authenticate :user, lambda { |u| u.super_admin? } do
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end
```

I get redirected to `http://www.acmecorp.com/sidekiq/en/signin` instead of `http://www.acmecorp.com/en/signin`. Any reason why the redirect does not get rid of the `/sidekiq` part?

Thanks!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by allaire** [comment]
@josevalim My bad, still a bit early here! Went ahead and asked on SO:

http://stackoverflow.com/questions/29392091/customfailure-and-mount-in-routes-bad-redirect

Thanks for all your hard work in the community by the way :)
