### ISSUE TITLE
login_as helper not working with capybara-webkit

### ISSUE THREAD

**Issue by collimarco** [plataformatec/devise#3553]
I don't know if this bug is more related with Devise or capybara-webkit.

Certainly **your wiki suggests something that isn't correct** (as it only partially works).

In practice you can't navigate through pages as a logged in user if you use login_as helper.

See https://github.com/thoughtbot/capybara-webkit/issues/751

**Comment by collimarco** [comment]
Oops, sorry it's my fault. The same issue seems to occur with Selenium (probably with Selenium I had tested a slightly different version). The problem is with the **documented** transactional fixtures. Maybe I'll investigate further, but for now I close this issue as it seems to be my fault.

**Comment by Aluma** [comment]
Hello,

I have a request everyone. Please do not click/tap "reply all" in your
email replies. I'm getting lots of emails that I'm not a part of.

Thank You,
Jimmy
