### ISSUE TITLE
Updating authentication_token when log out from another browser

### ISSUE THREAD

**Issue by dharajoshi** [plataformatec/devise#3554]
Hello,

I'm using token_authenticable, and recognize user via authentication_token. 
Now, suppose I'm logged in to two browsers with same credentials, and log out from one, devise'll update the authentication_token and another browser can't identify the user.

Thanks

**Comment by josevalim** [comment]
Devise no longer provides authentication_token, you are likely using an old Devise version and this bug no longer applies.

**Comment by dharajoshi** [comment]
@josevalim I'm using 3.0.4 version.
