### ISSUE TITLE
Users can spam one another with :confirmable

### ISSUE THREAD

**Issue by arcwhite** [plataformatec/devise#3556]
One of our security researchers at Bugcrowd.com pointed this out in our own app; it's a low-priority issue, and a bit specific, but could be an issue regardless.

As a user (user+1@bugcrowd.com)
Given I try to change my email address to user+2@bugcrowd.com
And I don't click the confirmation link
And another user creates an account with the email user+2@bugcrowd.com (and confirms it)
And I'm still logged in as user+1@bugcrowd.com
When I resend confirmation instructions
Then user+2@bugcrowd.com will receive a 'change email confirmation' email
And the link inside will be useless
And I can keep sending it as many times as I want (spamming user+2@bugcrowd.com and possibly annoying them slightly)

When a new user signs up with a given email address, any pending email changes on any other users that reference that email address should be wiped.

We've set up a background task to do this, which is one option. We could update the documentation to encourage developers using devise to do this too - or we could add this behaviour to Devise by default?

**Comment by josevalim** [comment]
There is a devise_async project. Maybe that would be a good place to add such recomendation? Maybe even do it by default htere?

**Comment by arcwhite** [comment]
I think I'd like to see the base Devise library address this one, because I think it's easy enough - but also doing it in devise-async would make sense.

Happy to write up a patch for both ;)

**Comment by josevalim** [comment]
In order to do it in Devise we would need to store when the last e-mail was sent and I am not sure it is worth adding a new column.

**Comment by arcwhite** [comment]
Hmmm, if a user signs up using some email address, I think it's fair to say nobody else should be using that email address - so we can clear the unconfirmed_email field to fix the case I outline above.

That doesn't stop users spamming non-users with sign up confirmation links though...

**Comment by josevalim** [comment]
> Hmmm, if a user signs up using some email address, I think it's fair to say nobody else should be using that email address - so we can clear the unconfirmed_email field to fix the case I outline above.

If the e-mail is unconfirmed we need to allow other people to use it... otherwise someone can take your e-mail as unconfirmed and you won't be able to use it because someone set up it as their unconfirmed e-mail.

**Comment by arcwhite** [comment]
Ah yeah, I meant "after I sign up and confirm"

If I've signed up to your site, and confirmed my email address as part of that process, my email address should not be in anyone else's unconfirmed_email field (e.g. it's now been "used", they can't complete a "change email" action to have he same email as me, and they shouldn't be able to re-send confirmation links to my email address)

**Comment by josevalim** [comment]
Ah yes, I see. We could add those checks but again, there is still multiple ways of spamming an e-mail account, even more know that the majority of providers support a random "+foo" added to the e-mail. :( The best option is indeed api limiting or sanity checking the e-mail delivery, all of them would be too much work to integrate with Devise.

**Comment by arcwhite** [comment]
Agree! Can I suggest a note added to the documentation that this should be
considered? Happy to write it up.

**Comment by josevalim** [comment]
Sounds like a good trade-off! Please send a pull request, thank you!
