### ISSUE TITLE
What's the reason to delete password and password_confirmation fields in update_with_password

### ISSUE THREAD

**Issue by youroff** [plataformatec/devise#3557]
I'm trying to build a little form to let users change their password. However, I found that `password` and `password_confirmation` keys get deleted if empty, which clearly breaks validation of presence. And update passes successfully without telling user anything.

https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb#L74-L77
Any reason to keep this piece of code?

**Comment by carlosantoniodasilva** [comment]
I think [the comments there explain the reasons behind the code](https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb#L67-70), in case you need different functionality I'd recommend building your own update method that takes the current password into account as well.

Thanks.
