### ISSUE TITLE
user.valid_password? returns a "false" false when called in JSON API in production mode

### ISSUE THREAD

**Issue by DaKaZ** [plataformatec/devise#3558]
We have a rails 4.1.6 application running devise 3.4.1 which is working great for web authentications and manually checking user passwords via the console.  We use a custom JSON API to service our mobile app so after checking a device token and looking up the user by their email address, we would then call:

    if user.valid_password?(params[:password])
      # handle valid user/password
    else 
      #handle invalid password

In development mode with the Thin server, this works perfectly.  In production with unicorn/nginx, it would not work with all passwords.  For example, the password "chimp123" works (valid_password? returns true) but "chimp1232" or "chimp1233a" do not.  I know its stored in the DB correctly because we can call valid_password? from the console on the selected user and it works.

We temporarily fixed our API by using this in replacement of valid_password?

     if BCrypt::Engine.hash_secret(params[:password],user.encrypted_password) ==  user.encrypted_password

I am happy to help trouble shoot this.  As I said, it only affects JSON params.  My full session controller where the problem was happening is here: https://gist.github.com/DaKaZ/f5693752317d14335f0b

Thanks

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
