### ISSUE TITLE
devise_omniauth_callback suggested documentation deprecated for Rails 4.2 

### ISSUE THREAD

**Issue by kroky** [plataformatec/devise#3560]
When you use `devise_for` inside a dynamic scope, devise brings a great suggestion on how to work around by using custom omniauth route matchers. However, the suggested code gives a deprecated warning in Rails 4.2 because the to: value of a route does not contain an action. Can you update the raised error message with the necessary `#:action` part like the actual code in the method does or I can also submit a pull request?

Relevant line: https://github.com/plataformatec/devise/blob/master/lib/devise/rails/routes.rb#L417

Actual error message:
```ruby
match "/users/auth/:action/callback",
  constraints: { action: /google|facebook/ },
  to: "devise/omniauth_callbacks",
  as: :omniauth_callback,
  via: [:get, :post]
```
Suggested change that works in Rails 4.2:
```ruby
match "/users/auth/:action/callback",
  constraints: { action: /google|facebook/ },
  to: "devise/omniauth_callbacks#:action",
  as: :omniauth_callback,
  via: [:get, :post]
```

**Comment by carlosantoniodasilva** [comment]
Please feel free to send a pull request if you can, we'd gladly merge it, otherwise we may handle it later. Thanks!
