### ISSUE TITLE
TypeError: can't clone Symbol when logging in via mobile vs desktop

### ISSUE THREAD

**Issue by Buildzzz** [plataformatec/devise#3564]
I am having an issue with the latest version of my code where users can't login via mobile, but they can log in on their desktop.

I'm using devise(v3.4.1) as my active record manager and the error is occurring when delayed_job(v4.0.6) and delay_job_active_record(v4.0.3) trys to send a message after devise login. See stacktrace:

…/gems/delayed_job-4.0.6/lib/delayed/message_sending.rb:  37:in `clone'
…/gems/delayed_job-4.0.6/lib/delayed/message_sending.rb:  37:in `block in handle_asynchronously'
…2.0.0/gems/devise-3.4.1/lib/devise/models/trackable.rb:  33:in `update_tracked_fields!'
…/2.0.0/gems/devise-3.4.1/lib/devise/hooks/trackable.rb:   7:in `block in <top (required)>'
…undle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/hooks.rb:  14:in `call'
…undle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/hooks.rb:  14:in `block in _run_callbacks'
…undle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/hooks.rb:   9:in `each'
…undle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/hooks.rb:   9:in `_run_callbacks'
…dle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:  53:in `_run_callbacks'
…undle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/proxy.rb: 179:in `set_user'

The issue happens through the 'create' method in devise:
def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
end

When I "puts auth_options" I get the following whether it's desktop or mobile so I'm stuck on how to debug further.
14:12:57 web.1    | auth_options =
14:12:57 web.1    | {:scope=>:user, :recall=>"devise/sessions#new"}

The delay job message_sending.rb method that's throwing the error. Line 37 is 'curr_opts = opts.clone':

module ClassMethods
  def handle_asynchronously(method, opts = {})
    aliased_method, punctuation = method.to_s.sub(/([?!=])$/, ''), $1 # rubocop:disable PerlBackrefs
    with_method, without_method = "#{aliased_method}_with_delay#{punctuation}", "#{aliased_method}_without_delay#{punctuation}"
    define_method(with_method) do |*args|
      curr_opts = opts.clone
      curr_opts.each_key do |key|
        next unless (val = curr_opts[key]).is_a?(Proc)
        curr_opts[key] = if val.arity == 1
          val.call(self)
        else
          val.call
        end
      end
      delay(curr_opts).__send__(without_method, *args)
    end
    alias_method_chain method, :delay
  end

Does anyone have any suggestions on how to debug further or understand the difference in params that is passed on a mobile vs desktop?

Thx!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
