### ISSUE TITLE
Devise  3.4.1 and Rails 4.2.1, remote forms throw InvalidAuthenticityToken

### ISSUE THREAD

**Issue by miskolc** [plataformatec/devise#3567]
I'm trying to submit a form using AJAX and data-remote unfortunately I receive an InvalidAuthenticityToken error. It seems that the authentication token is not added to the form when using remote: true so  I did some research and found out the following options for solving the problem:
- adding the following line in the Controller
  skip_before_action :verify_authenticity_token, :only => :create
-  adding the following line inside the form_for block
 <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
- adding :authenticity_token => true to the form_for params
- setting config.action_view.embed_authenticity_token_in_remote_forms to true in development.rb

I tried using all the above and each of them helped me get rid of the InvalidAuthenticityToken error, however, even though I still had the remote: true option, the request doesn't seem to be performed using AJAX since the page reloads and renders another view template.

**Comment by josevalim** [comment]
Do you have <%= csrf_meta_tags %> in your html header? This is not a devise issue per-se because we simply use the rails structure. Also, remember that you need to refresh the token after login.

**Comment by miskolc** [comment]
Yes, Jose, I do have the <%= csrf_meta_tags %> in my head element.
The only thing that I'm doing a bit differently is that the form is not submited when the user clicks on a button but it's submited using jQuery ( like $form.submit()). 
I suspect that the authenticity_token present in the head section is not sent when I use this approach.
