### ISSUE TITLE
How to use Devise both in the site and in the Admin Pages

### ISSUE THREAD

**Issue by serifmehmet** [plataformatec/devise#3568]
Hi,

I asked this question on SO. Can you help me about it? I'm so new to RoR and Devise and mixed up everything.

http://stackoverflow.com/questions/29697004/how-to-use-devise-both-in-the-site-and-in-the-admin-pages

Thanks

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
And please don't repost the questions here. There are folks constantly checking those!
