### ISSUE TITLE
Locale being carried over between requests

### ISSUE THREAD

**Issue by gaurish** [plataformatec/devise#3569]
Our app uses multiple locales. we have a `prepend_before_action` in our ApplicationController. like this

```ruby
class ApplicationController < ActionController::Base
  prepend_before_action :set_locale
  def set_locale
   18n.locale = params[:locale] || I18n.default_locale
  end
end
```
Now, these works just fine except sometimes the flash message("`devise.failure.already_authenticated`)  sometimes gets displays in spanish when it should be been in english which is weird because:

params[:locale] not being passed, so it should take locale as english. As its a default locale set for our own but instead `I18n.locale` was set to spanish. 

After we isolated the issue to combination of following things
1. In `Devise::SessionsController#require_no_authentication`, it executed with `prepend_before_filter`. Meaning `require_no_authentication` executed before `set_locale`, so we are not able to set an locale. 
2. In Unicron, same thread get reused. so if last request has `params[:locale] = :es #spanish`. the next request will also have `I18n.locale` set to spanish, unless explicitly overridden to default or other locale. 

The way we worked around this bug is this is following
we overrode SessionsController & registration controller 

```ruby
class Devise::SessionsController < DeviseController
  prepend_before_action :require_no_authentication, :only => [ :new, :create ]
  prepend_before_action :allow_params_authentication!, :only => :create
  prepend_before_action { request.env["devise.skip_timeout"] = true }
  prepend_before_action :set_locale
end
````
As the last `prepend_before_action` gets executed first. this ensures that locale is first. further, we also set locale to default after the request was executed like this:

```ruby
class ApplicationController < ActionController::Base
  after_action :reset_locale

  def reset_locale
    I18n.locale = I18n.default_locale
  end
end
```

I am wondering what will be the proper fix for this bug?

**Comment by josevalim** [comment]
The best fix would be a middleware that sets the locale that you can use in your application. This way you guarantee it is set way before any controller code is executed.
