### ISSUE TITLE
Issue or may I miss something ?

### ISSUE THREAD

**Issue by lbstephane** [plataformatec/devise#3572]
Hi,

I'm trying to customise SessionsControllers, I've got One for the API part of my projet, the other one for websessions.

Here my routes.rb file

devise_for :users, :controllers => {:sessions => 'websessions'}
resource :dashboard  
root :to => "dashboard#index"

namespace :api,  defaults: {format: 'json'} do
   devise_for :users, :controllers => {:sessions => "api/apisessions"}
end

It seems to work fine.

Now got a problem for my websessions_controller. I need to check a database flag (boolean) to check if my user is activated or not (FlgEnbl). Here my code

def create
      resource = User.find_for_database_authentication(:email => params[:user][:email])
      return failure unless resource
      
      if resource.valid_password?(params[:user][:password])

	    logger.info 'Flag value' => resource.FlgEnbl
	    
        if resource.FlgEnbl == true

			sign_in('user', resource)
	    	redirect_to root_url

	    else 
	    	return failure
	    end
	  else
	  	return failure
      end
    end

protected
    
    def failure
  	warden.custom_failure!
      return redirect_to new_user_session_path, alert: 'Invalid email/password, or account disabled !'
    end

So, if I try to log with a valid user and a wrong password, the failure message appear on my login page, valid user and password and bool set to true redirect to my dashboard page, but valid user and password with my bool set to false redirect to my dashboard page with a message 'You are already signed in.' instead of displaying the error message.

Same code with a render json on my api controller work.

Did I miss something or is it an issue ?

Thanks

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by lbstephane** [comment]
That the reason why my Title is Issue with ? :)

**Comment by josevalim** [comment]
I am sorry but we cannot be responsible for verifying if all issues actually belong to Devise. If you think this is an issue, please read the contribuding file on proper bug reports and please provide a sample application that reproduces the error so we can debug it.
