### ISSUE TITLE
Flash support in warden failures

### ISSUE THREAD

**Issue by alex88** [plataformatec/devise#3574]
I'm using json as the only endpoint and rails-api gem.
I'm getting exception `undefined method 'flash'` in login error responses, looking at the code like https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L52 it seems it's not conditionally use flash as in controllers https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L18 only when the format is navigational, maybe it should be checked too in the failure_app?

**Comment by josevalim** [comment]
Indeed. Please do send a pull request!

**Comment by alex88** [comment]
Closing this in favour of the PR
