### ISSUE TITLE
Add custom field from foreign table and validate it.

### ISSUE THREAD

**Issue by frerotg** [plataformatec/devise#3576]
Hello, I am writing today because I am facing a problem that I can not find the solution. I look all day without success.

Here's the situation:

I have two model, a user model and an agent model. A User have one/zero Agent. Each agent have a "code" like a promo code if you want.

When a user signs up, I give possibility to enter a agent code. When checking the form, if the user does not return code, it becomes part but if it has returned an agent code I have to check it based on the table "agents." If the code is wrong, the form is not validated and an error appears, if the code is correct I record information for the user with id of the agent.

### User model (*user.rb*)
    class User < ActiveRecord::Base
      enum role: [:user, :vip, :admin]
      after_initialize :set_default_role, :if => :new_record?
    
      has_one :agent
    
      def set_default_role
        self.role ||= :user
      end
      
      devise :database_authenticatable,
             :registerable,
             :recoverable,
             :rememberable,
             :trackable,
             :validatable,
             :confirmable,
             :lockable
    end

### Agent model (*agent.rb*)

    class Agent < ActiveRecord::Base
      belongs_to :user
    end

### Migration between user and agent
    class AddAgentToUsers < ActiveRecord::Migration
        def change
            add_reference :users, :agent, index: true
            add_foreign_key :users, :agents
        end
    end

### User DB
 - id
 - email
 - password,encrypted_password,...
 - sign_in information (time,ip,...)
 - agent_id

### Agent DB
 - id
 - code
 - name

**I spent all day to find a solution by recreating the "registration_controller" but nothing works and I feel that a more simple way exists. I do not think being the first to have this kind of question.**

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
