### ISSUE TITLE
Separate Password reset / update into a module.

### ISSUE THREAD

**Issue by ciroque** [plataformatec/devise#3577]
The change password functionality should not be a part of the registration module. Having it in it's own module would ease the task of making custom workflows for password change.

This would also allow password updates to not require sending of an email. If I am a logged in user and wish to change my password I should be able to do so in place and not have to wait for an email with a link to do so.

**Comment by josevalim** [comment]
We don't have plans to separate it. It is just an action, most of the logic already is in the module, which you can easily reuse.
