### ISSUE TITLE
`verify_signed_out_user` doesn't work well with :rememberable strategy

### ISSUE THREAD

**Issue by tobiashm** [plataformatec/devise#3578]
https://github.com/plataformatec/devise/pull/2968 introduced a `verify_signed_out_user` filter that checks if warden has a user set.
But if you are using the `:rememberable` strategy, there might not be a user in the session, but you'll be automatically signed in afterwards.
This is not what I would expect.

**Comment by josevalim** [comment]
Yes, this is a bug because users may be signed out lazily. We need to check for something like the lack of current_user and so on.

**Comment by chrismhilton** [comment]
We're falling foul of this issue with users attempting to sign out and the `all_signed_out?` method clearly returning true. This results in the `verify_signed_out_user` method redirecting to them using the `after_sign_out_path_for`, which in our case is the `sign_in_path`, and then the `require_no_authentication` method detects that they are indeed authenticated so they are redirected back to the application's `root_path` with a "You are already signed in" flash message displayed.

Our application uses multi-tenancy with the subdomain providing access to different systems. We have been able to recreate this by signing into two systems (using remember me) on different chrome tabs and then attempting to sign out of the first system. However, we have users in production with access to only one system who have reported the problem.

Do you have any suggestions on how the `all_signed_out?` method could be changed to prevent this?

**Comment by pcg79** [comment]
I've recently run into a similar issue.  It appears that `Warden::Proxy#set_user` isn't called until after the `verify_signed_out_user` before_filter is called.  So, as @chrismhilton said above, `all_signed_out?` returns `true` even though a user could be found eventually.

Right now it seems our only recourse is to skip the `verify_signed_out_user` filter in our SessionsController.

I know this isn't very helpful as it's not code.  But I threw debug logging into my app, the Warden gem, and the Devise gem.

With before_filter as coded:

```
*** MyApp Test - Signing In
*** Warden::Proxy#set_user

*** MyApp Test - Signing out
*** Devise::SessionsController#verify_signed_out_user
```

Commenting out verify_signed_out_user before filter:

```
*** MyApp Test - Signing In
*** Warden::Proxy#set_user

*** MyApp Test - Signing out
*** Devise::SessionsController#verify_signed_out_user (internal code commented out)
*** Warden::Proxy#set_user
*** MyApp - SessionsController#destroy
```

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
