### ISSUE TITLE
reset password page redirecting to homepage without showing form

### ISSUE THREAD

**Issue by quantumpotato** [plataformatec/devise#3580]
I'm following a reset password link from my email.
I'm taken straight to the home page without shown the form. Why is this happening?

**Comment by josevalim** [comment]
Which devise version? We may require the user to be signed out to reset her
password.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by quantumpotato** [comment]
from Gemfile.lock: Devise 3.4.1. Is there a way to disable the requirement to be signed out?

**Comment by josevalim** [comment]
You can inherit from this controller and skip this before filter:

https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L2

Check the router documentation on how to tell devise to use your own controllers.

**Comment by carlosantoniodasilva** [comment]
Also I'm wondering: why a user would "reset a password" if they are already signed in?

The reset password logic is not for signed in users to change their password, they are for users that forgot them to get a way to enter a new one. If you want a signed in user to change their password, you might be better off writing a separate controller for that I think (or if you have registration enabled you might use that as well).

Hope that helps.

**Comment by quantumpotato** [comment]
Thanks @josevalim . @carlosantoniodasilva because the user signs in on a mobile app. They are redirected to the web for reset password, where their session gets stored.

**Comment by carlosantoniodasilva** [comment]
I see. It still looks like a different scenario than the one reset password was initially created for. In any case it might work initially.
