### ISSUE TITLE
Cant generate devise user

### ISSUE THREAD

**Issue by mzaragoza** [plataformatec/devise#3581]
I have been having a problem creating a devise user 

  $ rails generate devise user
        invoke  active_record
        create    db/migrate/20150424115858_devise_create_users.rb
        create    app/models/user.rb
        invoke    rspec
        create      spec/models/user_spec.rb
        invoke      fabrication
  /Users/moiseszaragoza/.rvm/gems/ruby-2.1.5@app_name/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::UndefinedTable: ERROR:  relation "users" does not exist (ActiveRecord::StatementInvalid)
  LINE 5:                WHERE a.attrelid = '"users"'::regclass
                                            ^
  :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                  FROM pg_attribute a LEFT JOIN pg_attrdef d
                    ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                 WHERE a.attrelid = '"users"'::regclass
                   AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum

**Comment by carlosantoniodasilva** [comment]
It looks like it might be exploding on `invoking fabrication`, since you don't have the users table yet at this point. Can you try it without this plugin and see if it works? This doesn't seem to be related to devise, though. Thanks.

**Comment by mzaragoza** [comment]
Thanks @carlosantoniodasilva 
I removed **gem 'fabrication-rails'** from my gem file  and then 

$ rails generate devise user
      invoke  active_record
      create    db/migrate/20150424130126_devise_create_users.rb
      create    app/models/user.rb
      invoke    rspec
      create      spec/models/user_spec.rb
      invoke      factory_girl
      create        spec/factories/users.rb
      insert    app/models/user.rb
       route  devise_for :users

**Comment by carlosantoniodasilva** [comment]
Great :+1:

**Comment by kris** [comment]
I know this is closed, but for anyone else that runs into it, this was fixed in paulelliott/fabrication#248
