### ISSUE TITLE
Getting unauthorized with Devise

### ISSUE THREAD

**Issue by pepibumur** [plataformatec/devise#3582]
Hello
I'm trying to setup **Rails_admin** with devise in order to force authentication to go into the admin panel but I'm getting  **unauthorized** messages and being redirected to the login page.

I've done this kind of integration between Devise and Rails_Admin before and didn't have any problem but this time I'm getting a lot of troubles with it. Any idea of what might be happening? 

Thanks in advance

```ruby
  config.authenticate_with do
    warden.authenticate! scope: :user
  end
  config.current_user_method(&:current_user)
```

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
