### ISSUE TITLE
define_helpers is not considering config.parent_controller 

### ISSUE THREAD

**Issue by coezbek** [plataformatec/devise#3583]
When changing `config.parent_controller` the setting of `helper_methods` in [helpers.rb#L128](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb#L128) is broken. Changing parent_controller happens for instance when using `Rails-api`.

Consequence: `helper_methods` such as `user_signed_in?` are not exposed to views.

Another problem comes when `ActionController` is not the base of the inheritance hierarchy.

**Comment by wdas03** [comment]
![12257](https://cloud.githubusercontent.com/assets/13899670/10708114/4c259f86-79cb-11e5-9afc-a05d906f8348.png)
Test comment

**Comment by atwoodjw** [comment]
Are you sure you created a corresponding layout for the new parent controller?

**Comment by lucasmazza** [comment]
IIRC currently the `on_load` hook is triggered for both `AC::API` and `AC::Base`, so the helpers are exposed accordingly for each possible inheritance chain - API and non API controllers.

I'm closing this one due the lack of activity and info, but if there is still an issue regarding the helpers we can reopen this and dig deeper.
