### ISSUE TITLE
Does devise eager load rails app?

### ISSUE THREAD

**Issue by maksimf** [plataformatec/devise#3584]
I'm using devise-3.4.1 in my rails app and when I'm trying to do `rake db:migrate` I get error that `Relation doesn't exist` on one of the relations I'm about to migrate. I googled that issue and it [turned out
(https://rails.lighthouseapp.com/projects/8994/tickets/802-eager-load-application-classes-can-block-migration) that some of my gems eager load my app when I invoke rails tasks. When I disabled devise gem from my Gemfile, migration worked just fine.

**Comment by josevalim** [comment]
Devise does not eager load. However, using Devise, may end-up loading some model (likely the User model) early on and, when loading that module, its relationships and so on. This is not specific to Devise but to any Ruby code you end-up using early on, for example in your initializers. I would report this is a bug to Rails.
