### ISSUE TITLE
Prevent hidden changes to user model from Confirmable

### ISSUE THREAD

**Issue by adacosta** [plataformatec/devise#3590]
Confirmable includes a before_update method which changes email to email_was without this being made obvious, https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L238 . In my case, I had a list of users to import changes for, where I wanted to simply update the user email and persist the change. Devise wouldn't allow the email attribute modification to persist. The value was always persisted in unconfirmed_email. No warns or object errors were displayed. This behavior was unexpected. 

After spending time looking at the confirmable module, it's obvious the intent of Confirmable is to first set the user email in the unconfirmed_email attribute, then move the value to the email attribute after confirmation.

I suggest a better pattern might be to only allow ```unconfirmed_email=```, and add an error for the email attribute if the object attempts to call ```email=```. Being explicit has benefits:
- It prevents the end user (like me) from trying to make a change which is incompatible with Devise/Confirmable.
- It notifies the end user when at attempt to set the email field takes place (record invalid).
- It saves the postpone_email_change_until_confirmation_and_regenerate_confirmation_token method from having to do 
```
self.unconfirmed_email = self.email
self.email = self.email_was
```

If a change in the API isn't desired for email/confirmation_email use, maybe a warn can be displayed when email is being overridden by Confirmable#postpone_email_change_until_confirmation_and_regenerate_confirmation_token ?

Thoughts?

**Comment by josevalim** [comment]
Unfortunately there are no plans to change the API. The best you can do is to call `skip_reconfirmation!` that will allow you to proceed without triggering Devise's logic.

**Comment by adacosta** [comment]
For the sake of having examples.

**Current behavior**
```
> user = User.create email: 'a@a.com'
=> #<User email: 'a@a.com'>
...
> user.email = 'b@b.com'
> user.save
=> true
> user
=> #<User email: 'a@a.com', unconfirmed_email: 'b@b.com' >
# zoinks! It saved but the email attribute isn't the email attribute I set!
```

**Behavior with less side effects (I like)** [API change]
```
> user = User.create email: 'a@a.com'
=> #<User email: 'a@a.com'>
...
> user.email = 'b@b.com'
> user.save
=> false
> user.errors.full_messages
=> ["Email must be set as unconfirmed_email"]
```

**Behavior that might be a nice consolation** [No API change]
```
> user = User.create email: 'a@a.com'
=> #<User email: 'a@a.com'>
...
> user.email = 'b@b.com'
> user.save
# The following is warn output
[Devise::Confirmable] Attribute email: 'b@b.com' persisted to :unconfirmed_email 
=> true
> user
=> #<User email: 'a@a.com', unconfirmed_email: 'b@b.com' >
# zoinks! It persisted the email attribute to email_confirmation but at least it told me.
```

Given API changes aren't desired, do you think the No API change behavior would be acceptable, or something similar? It'd be nice to have some type of signifier.

**Comment by josevalim** [comment]
The issue is that this warning would then be triggered for everyone
updating an email through a view, which doesn't really make sense and also
cause confusion.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by adacosta** [comment]
Ok. Thanks for your time.
