### ISSUE TITLE
Confirmable can set confirmation_sent_at without being sent

### ISSUE THREAD

**Issue by adacosta** [plataformatec/devise#3591]
A before_create in Confirmable https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L36 calls generate_confirmation_token, which as a side effect sets confirmation_sent_at without sending the confirmation https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L224 .

An after_create in Confirmable https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L37 calls send_on_create_confirmation_instructions if: send_confirmation_notification? . send_confirmation_notification? could have @skip_confirmation_notification set to true, yet we still have a confirmation_sent_at value from the generate_confirmation_token in before_create .

The behavior I expect is, confirmation_sent_at only gets set when the confirmation is sent.

Maybe confirmation_token_generated_at would be a more appropriate attribute to store the token generation time. This would be in line with the comment @ https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L223 .

**Comment by josevalim** [comment]
Yes, this issue has been opened in the past but we can't fix it without being very, very backwards incompatible. :( It is indeed poorly name. Can you send a pull request that at least documents this behaviour and explain why it stays as is?

**Comment by adacosta** [comment]
will do.

**Comment by adacosta** [comment]
https://github.com/plataformatec/devise/pull/3592

**Comment by adacosta** [comment]
After documenting the Confirmable columns, it didn't seem necessary to explain why the confirmation_sent_at behavior won't be changed; it is what it is. Let me if you'd like a specific addition.
