### ISSUE TITLE
Using store location with activerecord session store

### ISSUE THREAD

**Issue by phlegx** [plataformatec/devise#3593]
Hi!

Any idea how i can use store location with activerecord session store (https://github.com/rails/activerecord-session_store)? I have read the code in https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/store_location.rb but I have problems to use it with ```after_sign_out_path_for(resource_or_scope)``` in my application controller.

**The problem**

The session row of the authenticated user gets deleted if I call ```/logout``` and a new session row is generated for the unauthenticated user after the logout. So, the information ```return_to``` in the session is nil.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by phlegx** [comment]
**Here the question on stackoverflow:** http://stackoverflow.com/questions/30077584/using-devise-store-location-scope-return-to-with-activerecord-session-store
