### ISSUE TITLE
Safe to upgrade?

### ISSUE THREAD

**Issue by enrichit** [plataformatec/devise#3604]
I've inherited an existing app and I need to make some changes to it. Basically I need to trigger a call to a method when a user logs in. I'm guessing that you would do this by generating a controller using `rails generate devise:controllers`. Unfortunately the version that is currently in production is `3.0.2` and that generator was added in in `3.4.0`.

So I have a couple of questions.

* Is there anyway I can trigger that call without generating this custom controller?
* If not, how dangerous would it be to update the gem we are running in production? Are there any large breaking changes between minor versions?

**Comment by josevalim** [comment]
It is recommended to upgrade so you are on par with the latest security practices. Check the changelog for more info: https://github.com/plataformatec/devise/blob/master/CHANGELOG.md

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
