### ISSUE TITLE
Bug with confirmable

### ISSUE THREAD

**Issue by kevin-madhu** [plataformatec/devise#3608]
When a user is currently logged in on a system, maybe in an internet cafe or something and someone else tries to confirm their email through the confirmation link, without knowing that someone else has their account open, the confirmation token becomes used, and he won't be able to confirm his account even after logging out of the previous account.

**Comment by josevalim** [comment]
Can you provide an application that reproduces the error? The account confirmed is always the one in the link. If you are signed in on another account, then you will continue signed in on the other account, but the proper account will be confirmed and you should be able to sign in by signing out.
