### ISSUE TITLE
Bug with confirmable

### ISSUE THREAD

**Issue by kevin-madhu** [plataformatec/devise#3609]
When the confirmation link is clicked after confirming the account, the message "E-mail is already verified comes up". But the confirmation token url stays though and causes no such route exists error for the login(because confirmation is through PATCH i think). Currently I handled the problem like this,

    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_flashing_format?
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ redirect_to root_path }
    end

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
