### ISSUE TITLE
How to specify a different root route when logged in/out?

### ISSUE THREAD

**Issue by andrewhavens** [plataformatec/devise#3610]
I did not see this mentioned in the readme and did not see this anywhere in the wiki. How can I configure my root route so that, when logged out, there is a different home page than when logged in?

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by andrewhavens** [comment]
Found the answer. This works in Rails 4:

    authenticated :user do
      root 'feed#index', as: :authenticated_root
    end

    root "home#index"

I'll create a FAQ wiki page for this.

**Comment by georgeguimaraes** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by teknull** [comment]
Excellent solution.  I've been wanting to do this exact thing.  Thanks for coming up with this.
