### ISSUE TITLE
When the user's account is locked, http response redirects instead of returning a JSON output with 401

### ISSUE THREAD

**Issue by rooseveltrp** [plataformatec/devise#3611]
Hi,

I am trying to get Devise working well with JSON. I think I know what's going on in here but I'm not sure how to remedy the situation. Here's the situation without any code:

1. User enters invalid info. JSON response from Devise returns 401 with {"error":"Invalid email or password."} :+1: 
2. User enters valid info. JSON response from Devise is 201 with full user object. :+1: 
3. User enters valid info. But his account is locked. /users/sign_in.json has the status 302 and ends up loading the contents of the home page. :-1:  This is where the problem is because jQuery is expecting a JSON response and not HTML.

Anyhow, here are my codes:

### jQuery AJAX Call

    $.ajax({
        headers: {
            'X-Transaction': 'POST Session',
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        url: "/users/sign_in.json",
        type: "POST",
        dataType: 'json',
        data: {
            "user" : {
                "email" : $("#user_email").val(),
                "password" : $("#user_password").val()
            }
        },

        success: function (resp) {
            console.log("Success");
            console.log(resp);

            // redirect the user
            window.location.href = "/"
        },

        error: function (resp) {
            resp_json = $.parseJSON(resp.responseText);
            bootbox.alert(resp_json.error);
        }

    });

### Custom SessionsController

    class SessionsController < Devise::SessionsController

      protect_from_forgery with: :null_session

      respond_to :json

      layout "login"

    end

### Custom RegistrationsController

    class RegistrationsController < Devise::RegistrationsController
      clear_respond_to
      respond_to :json
    end

### Routes

    MyApp::Application.routes.draw do

      root "pages#home"

      devise_for :users, :controllers => {
        sessions: 'sessions',
        registrations: 'registrations'
      }

    end

**Comment by josevalim** [comment]
Why do you say his account is locked? What do you see on the screen? I am asking because if they entered valid info, it shouldn't be locked, right?

**Comment by rooseveltrp** [comment]
@josevalim Your question intrigued me. My assumption was that Devise is responsible for creating the "locked" column in the users table. After scanning through the controllers, I noticed that my ApplicationController has the reject_locked! before filter. That method was doing a redirect instead of returning a 401 with JSON. After updating that method, everything is back to normal. That being said, Devise is working fine! :+1: 

	class ApplicationController < ActionController::Base
			before_filter :reject_locked!, if: :devise_controller?

			# Auto-sign out locked users
			def reject_locked!
			if current_user && current_user.locked?
				sign_out current_user
				user_session = nil
				current_user = nil
				flash[:alert] = "Your account is locked."
				flash[:notice] = nil

				respond_to do |format|
					format.html { redirect_to root_url }
					format.json { render :status => 401, :json => {:error => "Your account is locked."}}
				end

			end
			end

	end
