### ISSUE TITLE
allow store_location_for after_sign_out_path_for

### ISSUE THREAD

**Issue by cmar** [plataformatec/devise#3612]
We are using the `stored_location_for(resource_or_scope)` to set the return path for `after_sign_in_path_for`. We'd also like to use `stored_location_for(resource_or_scope)` for `after_sign_out_path_for`.  We had to implement this in our ApplicationController but thought it might useful in the default implementation.

Is this something that would be considered for the default implementation of `after_sign_out_path_for`?

I'd be glad to submit a PR if you would like to add this feature to the default implementation.

default `after_sign_in_path_for` https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb#L211

default `after_sign_out_path_for`
https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb#L221

**Comment by josevalim** [comment]
Please can always customize it but I would change Devise defaults. They
have been working well for us and changing it would also be backwards
incompatible. :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by cmar** [comment]
@josevalim  thank you for responding. I understand your concerns. Feel free to close this issue.  I'll provide an example of the change below in case someone else brings this up:


```
  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || begin
      scope = Devise::Mapping.find_scope!(resource_or_scope)
      router_name = Devise.mappings[scope].router_name
      context = router_name ? send(router_name) : self
      context.respond_to?(:root_path) ? context.root_path : "/"
    end
  end
```

**Comment by josevalim** [comment]
Thanks for the code snippet!
