### ISSUE TITLE
 ActionController::UrlGenerationError in Devise::Registrations#new

### ISSUE THREAD

**Issue by razy69** [plataformatec/devise#3621]
Hi, i've got an error while trying to access http://localhost/users/sign_up

## Error

> ActionController::UrlGenerationError in Devise::Registrations#new
> Showing /Volumes/Data/Projets/RubyOnRails/Bonbet973/app/views/layouts/_header.html.erb where line #15 raised:
> No route matches {:action=>"about", :controller=>"devise/pages"}

## Full Trace 

> actionpack (4.2.1) lib/action_dispatch/journey/formatter.rb:46:in `generate'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:727:in `generate'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:758:in `generate'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:801:in `url_for'
> actionpack (4.2.1) lib/action_dispatch/routing/url_for.rb:156:in `url_for'
> actionview (4.2.1) lib/action_view/routing_url_for.rb:94:in `url_for'
> turbolinks (2.5.3) lib/turbolinks/xhr_url_for.rb:12:in `url_for_with_xhr_referer'
> actionview (4.2.1) lib/action_view/helpers/url_helper.rb:181:in `link_to'
> app/views/layouts/_header.html.erb:15:in `_app_views_layouts__header_html_erb__3766288369248635217_70273739098320'
> actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
> activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
> actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
> actionview (4.2.1) lib/action_view/template.rb:143:in `render'
> actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
> actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
> actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
> activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
> activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
> actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
> actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
> actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
> actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
> app/views/layouts/application.html.erb:12:in  `_app_views_layouts_application_html_erb__2095949132227586617_70273715438640'
> actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
> activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
> actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
> actionview (4.2.1) lib/action_view/template.rb:143:in `render'
> actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
> actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
> actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
> actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
> actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
> actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
> actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
> actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
> actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
> actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
> actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
> actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
> activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
> /Users/razy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
> activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
> activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
> actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
> responders (2.1.0) lib/action_controller/responder.rb:236:in `default_render'
> responders (2.1.0) lib/action_controller/responder.rb:170:in `to_html'
> responders (2.1.0) lib/action_controller/responder.rb:163:in `respond'
> responders (2.1.0) lib/action_controller/responder.rb:156:in `call'
> responders (2.1.0) lib/action_controller/respond_with.rb:203:in `respond_with'
> devise (3.5.1) app/controllers/devise/registrations_controller.rb:10:in `new'
> actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
> actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
> actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
> actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
> activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
> activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
> activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
> activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
> actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
> actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
> activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
> activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
> actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
> actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
> activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
> actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
> actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
> actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
> actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
> actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
> actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
> actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
> actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
> actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
> actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
> warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
> warden (1.2.3) lib/warden/manager.rb:34:in `catch'
> warden (1.2.3) lib/warden/manager.rb:34:in `call'
> rack (1.6.1) lib/rack/etag.rb:24:in `call'
> rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
> rack (1.6.1) lib/rack/head.rb:13:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
> rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
> rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
> activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
> activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
> activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
> activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
> activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
> activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
> actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
> web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
> railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
> railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
> activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
> activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
> railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
> rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
> rack (1.6.1) lib/rack/runtime.rb:18:in `call'
> activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> rack (1.6.1) lib/rack/lock.rb:17:in `call'
> actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
> rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
> railties (4.2.1) lib/rails/engine.rb:518:in `call'
> railties (4.2.1) lib/rails/application.rb:164:in `call'
> rack (1.6.1) lib/rack/lock.rb:17:in `call'
> rack (1.6.1) lib/rack/content_length.rb:15:in `call'
> rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
> /Users/razy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
> /Users/razy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
> /Users/razy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

## config/routes.rb

```ruby
Rails.application.routes.draw do

  devise_for :users
  resources :annonces

  root 'pages#index'

  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'

end
```

## app/controllers/pages_controller.rb

```ruby
class PagesController < ApplicationController

  def about
  end

  def contact
  end

  def index
  end

end
```

## _header.html.erb

``` erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Annonces", {:controller => "annonces", :action => "index"} %></li>
        <li><%= link_to "S'enregistrer", {:controller => "devise/registrations", :action => "new"} %></li>
        <li><%= link_to "A Propos", {:controller => "pages", :action => "about"} %></li>
        <li><%= link_to "Contact", {:controller => "pages", :action => "contact"} %></li>
     </ul>
</div>
```

Thanks for your help :)

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by razy69** [comment]
Here is the app : https://github.com/razy69/bonbet973

**Comment by nashby** [comment]
@razy69 not sure if it's a bug or not but using [named routes](http://api.rubyonrails.org/classes/ActionDispatch/Routing.html#module-ActionDispatch::Routing-label-Named+routes) should fix your issues I guess.

**Comment by razy69** [comment]
@nashby thanks, it works now ! Using new_user_registration_path and named routes !! You rock, and sorry for this issue !

**Comment by sergiovilar** [comment]
@razy69 I'm with the same problems, could you describe how did you fixed please?
