### ISSUE TITLE
implementing access codes or tokens

### ISSUE THREAD

**Issue by watsonchang** [plataformatec/devise#3628]
Hello - was wondering if there is a way to integrate access codes or tokens into Devise. Here is my dilemma - some end-users are VIP and the site administrators will be registering their accounts on their behalf. Therefore, these accounts will not have e-mails and would not have passwords (since e-mails are blank, there would need to be a way to circumvent the unique e-mail validations as well as password requirements). Therefore, my goal is to implement some kind of access code or token, where once they register via the token/access code, it will link their login information to the user account we had already pre-registered for them. Guidance would be greatly appreciated.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
