### ISSUE TITLE
Add callback for password changes

### ISSUE THREAD

**Issue by reedloden** [plataformatec/devise#3631]
I'd like to perform certain actions on a successful password change. A callback would be nice. There's `after_password_reset`, but that's [been deprecated](https://github.com/plataformatec/devise/commit/31901bc862db60878130fcd9cbf9c4895d41b2d2#diff-fa817bf486c518644016136465d914b2R43) and doesn't cover all my use cases anyway.

**Comment by josevalim** [comment]
You can do this in two ways:

1. Have a before_save callback that checks if the encrypted password changed and work based on that

2. Override reset_password in your model and call super in there

**Comment by rcanand** [comment]
I overrode reset_password in my user model, but a byebug call does not come there when I reset the password from registrations/edit page.
