### ISSUE TITLE
Add option to clear sessions on password change

### ISSUE THREAD

**Issue by reedloden** [plataformatec/devise#3632]
It would be a good security enhancement to have an option (default setting to be debated) to clear active sessions on password change.

**Comment by josevalim** [comment]
We already do this too. The authentication salt is stored in the session as well.

**Comment by reedloden** [comment]
Is this a recent change (within the last year or so)? We had to implement it ourselves because it wasn't working like this. I was just going through all our custom changes and comparing against master, so apologies.

**Comment by josevalim** [comment]
No need to apologize. Your suggestions are great. It believes like this for a good while, definitely more than a year ago. Here is the code:

https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/models/authenticatable.rb#L207-L210
