### ISSUE TITLE
Clear remember me token for a user on password reset

### ISSUE THREAD

**Issue by reedloden** [plataformatec/devise#3633]
When a user changes his/her password, any existing remember me token should be cleared. This is a security best practice, so would be a nice enhancement for Devise.

**Comment by josevalim** [comment]
It is already done by Devise as resetting your password changes the authentication salt which is used to verify the remember token validity.

**Comment by reedloden** [comment]
Is this a recent change (within the last year or so)? We had to implement it ourselves because it wasn't working like this. I was just going through all our custom changes and comparing against master, so apologies.

**Comment by josevalim** [comment]
We have changed somewhere along the road the remember token to be the encrypted authentication salt. This is at least since Devise 2.1.0.

**Comment by reedloden** [comment]
Ok, thanks. I'll undo my local changes and re-test with latest Devise release.
