### ISSUE TITLE
reset_password

### ISSUE THREAD

**Issue by dan987** [plataformatec/devise#3638]
'devise', '3.4.1'
'rails', '4.1.8'
ruby '2.1.2'

Reset password works with most users but a few will not save reset_password_sent_at time. 
Making reset password not possible and locking out users.

**Comment by carlosantoniodasilva** [comment]
You need to give us more information or a way to reproduce the issue (like an example app or minimal script), otherwise it is impossible for us to help. We'll gladly reopen if we get more/enough information. Thanks!
