### ISSUE TITLE
Email regexp failing on invalid address

### ISSUE THREAD

**Issue by solanoluz** [plataformatec/devise#3639]
!!('teste@gmail..com' =~ Devise.email_regexp)
> true

**Comment by carlosantoniodasilva** [comment]
The email regexp is not supposed to cover everyone's cases / validations, it's a simple/basic filter. Please check #3537 and #3376 for more information (there might be other related issues as well). Thanks.

**Comment by solanoluz** [comment]
Thanks!


The alternative regexp posted at issue #3537 seems to cover this case.



2015-06-16 13:39 GMT-03:00 Carlos Antonio da Silva <notifications@github.com
