### ISSUE TITLE
Redirect loop when using `authenticate` in routes.rb (plus pull request that caused it)

### ISSUE THREAD

**Issue by stevenmilton58** [plataformatec/devise#3643]
Rails 4.2.2, Devise 3.5.1, Warden 1.2.3

**Note**: If  I revert the changes made in this pull request, things work as expected: https://github.com/plataformatec/devise/pull/3452/files

**Description**
I have an Admin model and am trying to use it to authenticate access to Sidekiq with Devise's "authenticate" method in Rails routes.

routes.rb :

    devise_for :admins

    authenticate :admin do
      require 'sidekiq/web'
      mount Sidekiq::Web => "/admin/sidekiq"
    end

I get a "redirect loop" error.

Upon visiting `http://localhost:3000/admin/sidekiq` I get redirected to 
`http://localhost:3000/admin/sidekiq/admins/sign_in` instead of being redirected
to `http://localhost:3000/admins/sign_in`.

Not sure how to fix this.

I see that the route being generated in `def scope_url` in failure_app.rb (https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L129)
is `http://localhost:3000/admin/sidekiq/admins/sign_in` instead of the expected
`http://localhost:3000/admins/sign_in`.

**Comment by abevoelker** [comment]
I'm having the same problem. According to git bisect this is the commit that broke it: af8d38e45b24ad06f89af254c4c0dc4c6c39f723

**Comment by josevalim** [comment]
Can someone please send a pull request? Apparently we will need to detect the Rails version because the fix is required for Rails 4.2.

**Comment by pragmaticivan** [comment]
I'm having the same problem with Rails 4.2.3. Is there any plans for accepting the last PR?

**Comment by sloops77** [comment]
The fix doesnt apply to rails below 4.2 but is an issue on our app with 4.1.12 (and is fixed by the above commit simply by changing the minimum minor_version to 1.
