### ISSUE TITLE
Can't translate "Invalid email or password.". Always in default language.

### ISSUE THREAD

**Issue by vizo** [plataformatec/devise#3647]
When i try to login, it always show message in default language of i18n "Invalid email or password.".

Message is generated in https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L88.

I set other I18n.locale in appliaction_controler.rb in before_action (where `* Locale set to 'sl'` is printed in log).
But i see in console log that "before_action" is called twice. I guess there is redirect in devise?

Log file:
```
Started POST "/sl/user/sign-in" for 192.168.1.100 at 2015-06-22 04:49:54 +0200
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"09Axw5uYvkRJgUts4aIFCf37oArR8zs2O0mG+2BC/XUQAcSbUfCoRk+YEa9k6FBkw9GLcVHraje1kO2on2Gypw==", "user"=>{"email"=>"", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Prijava", "locale"=>"sl"}
* Locale set to 'sl'
Completed 401 Unauthorized in 213ms

en <------- This is printed out from /lib/devise/failure_app.rb#L88, so here translation message is generated.

Processing by Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"09Axw5uYvkRJgUts4aIFCf37oArR8zs2O0mG+2BC/XUQAcSbUfCoRk+YEa9k6FBkw9GLcVHraje1kO2on2Gypw==", "user"=>{"email"=>"", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Prijava", "locale"=>"sl"}
* Locale set to 'sl'

```

Did i miss something? Where should i set i18n.locale to see "Invalid email or password." in right locale?

Versions:
rails (4.2.0)
warden (1.2.3)
devise (3.5.1)
devise_invitable (1.5.1)

**Comment by vizo** [comment]
Ok i finally figured it out.

By looking at source i see devise is using `prepend_before_filter`. So i set I18n.locale in appliaction_controler.rb in `prepend_before_filter` and now it works. Yey! :)

**Comment by josevalim** [comment]
A pull request to update the docs or README will be very appreciated, thank you!
