### ISSUE TITLE
Omniauth and dynamic route segments: proposed solution doesn't work

### ISSUE THREAD

**Issue by Envek** [plataformatec/devise#3651]
I am currently upgrading from Devise 3.1 to Devise 3.5.1 and getting next error:

    Devise does not support scoping OmniAuth callbacks under a dynamic segment (RuntimeError)
    and you have set "/:locale/users". You can work around by passing
    `skip: :omniauth_callbacks` and manually defining the routes. Here is an example:

        match "/users/auth/:provider",
          constraints: { provider: /google|facebook/ },
          to: "devise/omniauth_callbacks#passthru",
          as: :omniauth_authorize,
          via: [:get, :post]

        match "/users/auth/:action/callback",
          constraints: { action: /google|facebook/ },
          to: "devise/omniauth_callbacks#:action",
          as: :omniauth_callback,
          via: [:get, :post]

But solution proposed in error message isn't working for me.

What I'm trying:

```ruby
devise_scope :user do
  providers_regexp = Regexp.new(User.omniauth_providers.join('|'))
  match '/users/auth/:provider',
        constraints: { provider: providers_regexp },
        to: 'users/omniauth_callbacks#passthru',
        as: :user_omniauth_authorize,
        via: [:get, :post]

  match '/users/auth/:action/callback',
        constraints: { action: providers_regexp },
        to: "users/omniauth_callbacks##{providers_regexp}",
        as: :user_omniauth_callback,
        via: [:get, :post]
end

scope '/:locale', locale: Regexp.new(I18n.available_locales.join('|')) do
  devise_for :users, skip: :omniauth_callbacks
end
```

I'm getting next error when trying to authenticate using any provider:

    Not found. Authentication passthru.

What IS working for me is the @rafaltrojanowski solution (thanks!) from discussion in #2227

```ruby
devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

scope '/:locale', locale: Regexp.new(I18n.available_locales.join('|')) do
  devise_for :users, skip: :omniauth_callbacks
end
```

I think that error message should be changed including some working solution.

**Comment by josevalim** [comment]
Can you please send a PR? :)
