### ISSUE TITLE
passwords#new and passwords#edit is not protected against format

### ISSUE THREAD

**Issue by pwen** [plataformatec/devise#3652]
```
# GET /resource/password/new
def new
  self.resource = resource_class.new
end

# GET /resource/password/edit?reset_password_token=abcdef
def edit
  self.resource = resource_class.new
  resource.reset_password_token = params[:reset_password_token]
end
```

When requested with unintended format, these endpoints should raise UnknownFormat instead of Missing Template.

**Comment by kurenn** [comment]
Are you requesting it with json format for example?

**Comment by SimonDKnight** [comment]
Hey, I will look into this issue and see if I can come up with a solution.

**Comment by lucasmazza** [comment]
Handled by plataformatec/responders#153 - we might enable this by default on future Devise versions but developers can try it out when overriding Devise controllers.
