### ISSUE TITLE
email_changed? returns false when updating email.

### ISSUE THREAD

**Issue by daslicious** [plataformatec/devise#3654]
I'm using Rails 4.0.5 and Devise 3.4.1
In `postpone_email_change?` which runs before update in the `confirmable` module..
It checks if the email has been changed with `email_changed?`  This returns `false` when it has in fact been changed.

`email_change` returns `["old@email.com", "new@email.com"]`

The affect is that the email is updated without being confirmed.

I'm making a sample app...

**Comment by daslicious** [comment]
This was a conflict with devise_token_auth which hard coded `email_changed?` to `false`

**Comment by cs0511** [comment]
thanks @daslicious , same issue, and good to know.
