### ISSUE TITLE
Lockable and two factor authentication co-operation

### ISSUE THREAD

**Issue by mmustala** [plataformatec/devise#3655]
Hi,

In our project we use lockable and devise-two-factor gem. Lockable seems to increase the failed_attempts counter by one before each authentication and then rely on the successful login to reset the counter later in the SessionController#create call. This is somewhat counter intuitive already by it self.

When two factor authentication is used this comes more troublesome because the failed_attempts is increased even before the user has really tried to sign in. If the user has some trouble with receiving the two factor authentication token and he initiates the login process several times the account may get locked even before the user has finished a single login process.

Shouldn't the lockable increase the failed_attempts counter only after the login really fails?

**Comment by mmustala** [comment]
Further investigation showed that it was a call to user_signed_in? that caused the failed_attempts counter to increase. Also calling current_user does the same. We have before filters using both of those.

Is there a way to find out if a user has been signed in without the devise trying to look for signed in user from the request?

**Comment by josevalim** [comment]
Well, Devise does not provide two factor authentication, so you should really discuss it with the gem you are using to provide it or provide the appropriate code samples if it is hand-rolled. `user_signed_in?` will always try to sign the user in, you can look into warden for mechanisms to check if the user is signed in without executing any of the callbacks.
