### ISSUE TITLE
change active_record.default_timezone

### ISSUE THREAD

**Issue by anklos** [plataformatec/devise#3658]
Hi there,

I am seeing a strange issue in  my app (rails 4.1.0, devise 3.2.4). 

If I set the `config.active_record.default_timezone` in my `applicaiton.rb` like this: `config.active_record.default_timezone = 'Sydney'` and restart the server, then I cannot sign in any more. It returns the error message `You have to confirm your account before continuing.` on the page.

But if I remove that config, it all works fine.

I have got no clue why this is happening, any suggestion? Thanks!

**Comment by lsylvester** [comment]
`config.active_record.default_timezone` determines how ActiveRecord reads times from the database, this should be `:utc` or `:local`. With `config.active_record.default_timezone = 'Sydney'` all times retrieved from the database appear to be nil, which is possibly the cause of the session failing, so I don't think that this is a device issue,

The config you are probably after is `config.time_zone = "Sydney"`

**Comment by anklos** [comment]
Thanks a lot @lsylvester, it makes sense to me.
