### ISSUE TITLE
Scope Specific Links

### ISSUE THREAD

**Issue by Arbolista** [plataformatec/devise#3660]
It seems like it's increasingly advised as best practice to authenticate users through OAuth2 with minimum permissions upfront, and subsequently request additional permissions within the context of where those permissions will be used (ie maybe you have a page to connect to your friends on your platform - links to request permissions from Facebook, etc should be on that page).

I've searched all over and this does not seem supported here. I've started writing my own manual library to do this for the platforms I use, but if I'm going to go through that effort, I figure I may as well build it into Devise (which we are using elsewhere).

Is anyone working on this? Is there a reason it is not supported? Would the community support me if I fork it and send a pull request?

**Comment by josevalim** [comment]
@Arbolista Devise is already quite big as is and we don't plan to make it even bigger. :) So thank you for the offer but we wouldn't add such feature to Devise itself, even more since Devise has just a very thin wrapper around OAuth2.
