### ISSUE TITLE
 Multi-Tenant Engine & Devise - NameError: uninitialized constant Use

### ISSUE THREAD

**Issue by bradpotts** [plataformatec/devise#3664]
Not sure if this is an issue I should bring to devise's attention. I already posted on SO but would like your guys opinion and see if anybody is having the same problems.

Engine & devise all configured with rspec tests passing. 
https://github.com/CoastDigitalGroup/cdg-subengine

Example Starter App I'm trying establish.
https://github.com/CoastDigitalGroup/cdg-substarter

As soon as I attach the engine w/ devise (using github) in the gemfile the starter app starts giving: NameError: uninitialized constant User on rake commands.

 I went w/  through the engine several times, including re-install & reconfiguring devise to work within the engine. Seems to pass rspec tests fine but can't actually implement it in an app.

** Invoke routes (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant User
/home/nitrous/code/cdg-substarter/.bundle/bundler/gems/cdg-subengine-2af76555ad4c/app/models/subengine/user.rb:26:in `<module:Subengine>'
/home/nitrous/code/cdg-substarter/.bundle/bundler/gems/cdg-subengine-2af76555ad4c/app/models/subengine/user.rb:25:in `<top (required)>'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb:263:in `const_get'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb:263:in `block in constantize'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb:259:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb:259:in `inject'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb:259:in `constantize'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise.rb:290:in `get'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/mapping.rb:81:in `to'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/mapping.rb:76:in `modules'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/mapping.rb:93:in `routes'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/mapping.rb:160:in `default_used_route'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/mapping.rb:70:in `initialize'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise.rb:324:in `new'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise.rb:324:in `add_mapping'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/rails/routes.rb:224:in `block in devise_for'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/rails/routes.rb:223:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/devise-3.5.1/lib/devise/rails/routes.rb:223:in `devise_for'
/home/nitrous/code/cdg-substarter/.bundle/bundler/gems/cdg-subengine-2af76555ad4c/config/routes.rb:17:in `block in <top (required)>'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:601:in `instance_exec'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:601:in `block in with_default_scope'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:600:in `with_default_scope'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/home/nitrous/code/cdg-substarter/.bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:412:in `draw'
/home/nitrous/code/cdg-substarter/.bundle/bundler/gems/cdg-subengine-2af76555ad4c/config/routes.rb:3:in `<top (required)>'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `call'
/home/nitrous/code/cdg-substarter/.bundle/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `execute'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/home/nitrous/code/cdg-substarter/config/environment.rb:5:in `<top (required)>'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/home/nitrous/code/cdg-substarter/.bundle/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/nitrous/code/cdg-substarter/.bundle/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
.bundle/binstubs/rake:16:in `load'
.bundle/binstubs/rake:16:in `<main>'
Tasks: TOP => routes => environment

**Comment by josevalim** [comment]
Do you have a particular commit we can checkout to try things out?

**Comment by bradpotts** [comment]
Sorry been messing around with the starter app. 
https://github.com/CoastDigitalGroup/cdg-substarter
Commit: 2677e5e is the last known good one

https://github.com/CoastDigitalGroup/cdg-subengine
The latest commit on the engine 2af7655 has all the changes, been fully tested, the last one before that failed.

**Comment by bradpotts** [comment]
My problem seems specific, but for anybody else having this problem.

https://github.com/CoastDigitalGroup/cdg-substarter
The last commit 4f38bee2e8 seems to have fixed my immediate error, but haven't further tested anything else.

Add user.rb file to app/models directory than add:
include Subengine::UserStorage
