### ISSUE TITLE
find_scope! fails when comparing if user.is_a?(User)

### ISSUE THREAD

**Issue by andrewhavens** [plataformatec/devise#3665]
I'm running a Rails 4.2 application, using the latest version of `devise` (3.5.1), latest version of `devise-neo4j` (2.0.0), and latest version of `neo4j` (5.0.2). As explained in neo4jrb/devise-neo4j#16, I am unable to call `sign_in user` because [`Devise.ref.name` does not return `User`](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L285-L303). Instead, it returns something that looks like this:

```
User(authentication_token: Object, confirmation_sent_at: DateTime, confirmation_token: Object, confirmed_at: DateTime, created_at: DateTime, current_sign_in_at: DateTime, current_sign_in_ip: Object, email: Object, encrypted_password: Object, facebook_token: Object, first_name: Object, last_name: Object, last_sign_in_at: DateTime, last_sign_in_ip: Object, remember_created_at: DateTime, reset_password_sent_at: DateTime, reset_password_token: Object, sign_in_count: Object, tos: Object, unconfirmed_email: Object, updated_at: DateTime)
```

It seems this has something to do with class caching. But I don't really understand how this works. So I'm having trouble trying to find a solution (or even identify how it is supposed to work). [These lines](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L285-L303) seem to be the source of my issues:

```ruby
ActiveSupport::Dependencies::reference(User)
ActiveSupport::Dependencies.constantize(User)
```

It's possible that this is a bug with the `neo4j` gem. However, if you know how this `ActiveSupport::Dependencies::reference` stuff is supposed to work and what I need to do to fix it, that would help.

Otherwise, as a workaround, if you could help me find a way of signing in a user and avoid those lines of code that are failing, that would be helpful too.

I'm really just trying to figure out how to move forward.

Thanks!

**Comment by josevalim** [comment]
You need to give us a way to reproduce the issue, otherwise there isn't much we can do.
