### ISSUE TITLE
after_resetting_password_path_for should work for Devise.sign_in_after_reset_password=false case

### ISSUE THREAD

**Issue by fengye87** [plataformatec/devise#3668]
I was trying to avoid signing in users after they reset their passwords. So I set `Devise.sign_in_after_reset_password = false` in config, and overrides `def after_resetting_password_path_for(source)` in my PasswordsController, but it redirects to `new_session_path` rather than what I set in the `after_resetting_password_path_for` function.

I checked out the [code](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L44) here and found out why. Is there any rationale behind this design or it's open to discuss and change?

**Comment by josevalim** [comment]
Good catch, let's change it. Let's check for `Devise.sign_in_after_reset_password ` in `after_resetting_password_path_for(source)` and redirect accordingly. Can you please send a PR?

**Comment by fengye87** [comment]
Good to know it's open change. I'll send a PR, but before that, I've got one more question.

So previously, I was trying to provide password forgot/reset feature on my website using devise, but do not plan to provide user sign in/up in the upcoming version. So there's no `SessionsController` or `RegistrationsController`, neither are their routes. That's why I wanted to disable `Devise.sign_in_after_reset_password` and change `after_resetting_password_path_for(source)` to `root_path`.

But as it turns out later, `new_session_path` is also used [here](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L65), which redirects user to sign in when no `password_reset_token` is given. So now I realize that this may involve more work than just simply patch `update()`. To the extend that devise is really about user authentication, it's perfectly reasonable to assume `new_session_path` being defined. So it leaves the question that: *should devise take care of this sign-in/up disabled situation or should this kind of customization kept out of devise's scope?*

**Comment by josevalim** [comment]
@fengye87 then you don't need to have the controller :) as long as you define a new_user_session_path that redirects to whatever makes sense to your app, you will be fine.

**Comment by fengye87** [comment]
Sorry for a newbie question, but to define a sensible `new_user_session_path`, I suppose need to include routes related to `SessionsController` right? That's what I was trying to avoid at the first place. But if you are suggesting switching/overriding `new_user_session_path`, I'm more than happy to know how :)

**Comment by josevalim** [comment]
No problem asking. You don't need to define a sessions controller, you may as well do in your ApplicationController:

    def new_user_session_path
      "/"
    end

If you need it in the views, also add:

    helper_method :new_user_session_path

**Comment by fengye87** [comment]
Never occurred to me that this would work, but it does! Just need one slight change though.

```ruby
# This overriding would not work, it never get called from devise controllers.
def new_user_session_path
  "/"
end

# But this one will get called and work perfectly.
def new_session_path(resource_name)
  "/"
end
```

Thanks for the help! So for the original issue, does it still require a fix. Since `new_session_path` can be overrided easily this way, I think the existing design makes sense in its own way. If it still does, I would send a PR. It should be a line or two if I'm not misunderstanding :)

**Comment by josevalim** [comment]
Awesome! Yes, please do send a PR. I am closing this and waiting for the PR. :)
