### ISSUE TITLE
Recoverable flash notice

### ISSUE THREAD

**Issue by mr-koww** [plataformatec/devise#3669]
Hello! I'm using devise v3.2. When I try reset the password with empty or not exists email after that there is flash notice: "User could not be created." It does not seem strange for you? I want message: "Email is not exists or empty". Can I change that and how?

**Comment by rubyrider** [comment]
check devise.yml and update your message there on appropriate keys

**Comment by mr-koww** [comment]
devise.yml doesn't have these keys

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
