### ISSUE TITLE
Use deliver_later instead of deliver_now when possible?

### ISSUE THREAD

**Issue by sbull** [plataformatec/devise#3674]
This is related to https://github.com/plataformatec/devise/issues/3550, and the README documentation about ActiveJob integration.

Would you consider using deliver_later when possible (when the record is already persisted), rather than deliver_now? That would seem to make integration with ActiveJob built-in out-of-the-box, without much drawback - deliver_later seems equivalent to deliver_now unless an ActiveJob adapter is configured (http://guides.rubyonrails.org/active_job_basics.html#job-execution).

``` ruby
def send_devise_notification(notification, *args)
  message = devise_mailer.send(notification, self, *args)
  # Remove once we move to Rails 4.2+ only.
  if persisted? && message.respond_to?(:deliver_later)
    message.deliver_later
  elsif message.respond_to?(:deliver_now)
    message.deliver_now
  else
    message.deliver
  end
end
```

Are there drawbacks to this default behavior that I don't see?

**Comment by superacidjax** [comment]
deliver_later should always be the default. With ActiveJob, there's no logical reason to use deliver_now since ActiveJob handles the fallback already

**Comment by sbull** [comment]
@superacidjax I believe devise has a few instances when it sends emails that depend on the user object as a parameter before that particular user object has been saved. So `deliver_now` would need to be used for non-persisted users, as there's no built-in way for ActiveJob to deal with model objects that aren't persisted. See https://github.com/plataformatec/devise/issues/3550

**Comment by guigs** [comment]
Even if user is persisted I think there is a risk that other user attributes that were updated in current transaction and are used by mailer are stale. So, maybe the deliver_later should only be called after transaction commit.

**Comment by cseelus** [comment]
Cumbersome, but in the meantime: http://devise.plataformatec.com.br/#activejob-integration
