### ISSUE TITLE
AuthHash does not have FB email

### ISSUE THREAD

**Issue by ejvalmores** [plataformatec/devise#3677]
Hi, 

I followed the instructions on how to use devise to connect/login to FB ( https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview ) step-by-step.  

I am stuck in the creating the user part because somehow request.env['omniauth.auth'] doesn't provide the email address.  I already set the scope correctly and FB also verified the scope during the login process.  

Somehow all I'm getting in the returned AuthHash is the 'name' and 'image'. 
```
#<OmniAuth::AuthHash::InfoHash image="http://graph.facebook.com/10206351368318413/picture" name="Elmar John N. Valmores">
```
I already verified the email im using in FB.  

Not sure if this is a bug.  Please help.  thanks!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by jsanders67** [comment]
+1 for this problem
