### ISSUE TITLE
Question not issue: How config devise modules dynamically

### ISSUE THREAD

**Issue by fmh** [plataformatec/devise#3682]
I want to allow admin user to set the devise module from user interface and store it in db.
In model like this: 
`````ruby
devise `:database_authenticatable , :trackable , current_user.options_from_db` 
```````
How can I do it ?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
