### ISSUE TITLE
Devise redirects to wrong place when using non default login controller AND using user who is not active

### ISSUE THREAD

**Issue by moger777** [plataformatec/devise#3683]
Right now we have a default login controller for normal users. We have another login controller with a different controller which uses a different layout and redirects to a different point on success but other than that it's the same controller (both inherit from devise sessions controller). When using a bad username and password with the non default controller, it will remain on the non default controller and work as expected. Likewise, using a good username and password will hit non default controller and redirect as appropriate. When using a correct username and password with a user that is not active, it will redirect them to the "default" login controller instead. Attached are my routes:

```ruby
app/views/users/walgreens_registrations/new.html.haml
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions" # this is the default
  }

devise_scope :user do
    get "user/special_sessions" => "users/special_sessions#new", as: "new_special_session"
    post "user/special_sessions" => "users/special_sessions#create", as: "create_special_session"
end
```

**Comment by josevalim** [comment]
The user activation is not part of the login process. It is a validation that happens afterwards so if you have a single resource then it can indeed only redirect to one of those places. You could, however, store something in session and configure the proper Devise helpers to redirect to the proper place.
