### ISSUE TITLE
Improving database_authenticatable.rb

### ISSUE THREAD

**Issue by j15e** [plataformatec/devise#3688]
I got two concerns/bugs that I would like to address but I would need more knowledge from maintainers :

- The `fail(:not_found_in_database)` is returned even if the account exist when there is no password provided. I have read previous issue #3021, but I do not understand why it should not be fixed in an other way that would prevent the strategy to run, ex :

```ruby
      def authenticate!
        # Remove `valid_password? && ` from here
        resource  = mapping.to.find_for_database_authentication(authentication_hash)
        encrypted = false

        # Move logic here to avoid running strategy there
        if password.present? && validate(resource){ encrypted = true; resource.valid_password?(password) }
          remember_me(resource)
          resource.after_database_authentication
          success!(resource)
        end

        mapping.to.new.password = password if !encrypted && Devise.paranoid
        fail(:not_found_in_database) unless resource
      end
```

- I don't really get what this code does : `mapping.to.new.password = password if !encrypted && Devise.paranoid`? Was it intended to keep the submitted password filled in the form if we are not in paranoid mode maybe? I am lost here, hint appreciated!

**Comment by josevalim** [comment]
1. The logic is correct. The atom `:not_found_in_database` is poorly named. It means: :not_found_in_database_matching_email_and_password

2. It is related to timing attacks. We need to ensure the password is always encrypted, otherwise it can be used to find if emails exist in the database or not

**Comment by j15e** [comment]
Ok I get that `not_found_in_database` is like the specific `not_found` message for the `database` strategy, it it pretty clear in fact. I wrongly thought there was a feature to let user know that no account was existing.

Regarding the timing attack prevention, why is it only on with `Devise.paranoid`? Is it suppose to affect the behaviour for the end user?

**Comment by josevalim** [comment]
Because without Devise.paranoid people can already discover e-mails on the reset password session. No need for fancy timing attacks.
