### ISSUE TITLE
Rails 5 API: undefined method `helper_method' for ActionController::API:Class (NoMethodError)

### ISSUE THREAD

**Issue by ballPointPenguin** [plataformatec/devise#3690]
See also:
https://github.com/rails-api/rails-api/issues/6
https://github.com/rails/rails/issues/21067

**Comment by jeffdill2** [comment]
@ballPointPenguin have you found any resolution or workaround for this issue?

**Comment by ballPointPenguin** [comment]
@jeffdill2 this is working for me https://github.com/rails/rails/pull/21151

**Comment by FanaHOVA** [comment]
@ballPointPenguin Just used your Rails 5 fork and it works perfectly, thanks a lot for the fix.

**Comment by ballPointPenguin** [comment]
@FanaHOVA glad I could help :smile:

**Comment by nahaylo** [comment]
@ballPointPenguin, checked your fix. And yes, now, `helper_method` doesn't appear, but still devise doesn't work, because devise defines a lot of methods which behave as a helper method, for e.g.: authenticate_user!, current_user. 
Any ideas, how it could be fixed/done?
Thanks

**Comment by ballPointPenguin** [comment]
@nahaylo unfortunately, no. I haven't spent the effort getting devise working this way, beyond just clearing the initial failure addressed here.
IMO, more work could be done on devise to make it "api-friendly", so to speak.

**Comment by jeffdill2** [comment]
@ballPointPenguin @nahaylo if you guys need another solution, I've been using https://github.com/simplabs/rails_api_auth and it's working very well. Very lightweight - i.e. well-suited for an API-only application.

**Comment by betesh** [comment]
PR #3732 fixes the helper_method issue.

Also, I have made devise work with Sinatra before, with surprisingly little monkey-patching, but it would still have been nicer if this was supported from the start.  If anyone is planning on overhauling devise to be more RailsApi friendly, I strongly encourage you to focus on a more generalized approach of making it more friendly to Rack-based applications in general.  Please let me know if I can help out, specifically in identifying where it needed to be tweaked for Sinatra.

**Comment by lucasmazza** [comment]
Closed by #3732.

**Comment by dizo1** [comment]
Having the same issue could someone help?

**Comment by dizo1** [comment]
2017-06-04 03:19:52 +0000: Rack app error handling request { GET / }
#<NoMethodError: undefined method `helper_method' for ActionController::API:Class>
/usr/local/rvm/gems/ruby-2.3.3/gems/google-webfonts-rails-0.0.1/lib/google-webfonts/rails/helpers.rb:7:in `block in <module:Helpers>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/concern.rb:120:in `class_eval'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/concern.rb:120:in `append_features'
/usr/local/rvm/gems/ruby-2.3.3/gems/google-webfonts-rails-0.0.1/lib/google-webfonts-rails.rb:9:in `include'
/usr/local/rvm/gems/ruby-2.3.3/gems/google-webfonts-rails-0.0.1/lib/google-webfonts-rails.rb:9:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:49:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/api.rb:145:in `<class:API>'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/api.rb:88:in `<module:ActionController>'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/api.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/jbuilder-2.6.4/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:49:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/base.rb:269:in `<class:Base>'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/base.rb:164:in `<module:ActionController>'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_controller/base.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/middleware/static.rb:77:in `ext'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/middleware/static.rb:33:in `match?'
/usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-5.0.3/lib/action_dispatch/middleware/static.rb:130:in `call'
/usr/local/rvm/gems/ruby-2.3.3/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-5.0.3/lib/rails/engine.rb:522:in `call'
/usr/local/rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
/usr/local/rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
/usr/local/rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
/usr/local/rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
/usr/local/rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by abadfish** [comment]
I had this working (  helper_method :authenticate_token!, :current_user ) and then swapped out jbuilder for active_model_serializers. I got the error noted above so I added back jbuilder and now my api is working as expected with JWT.
