### ISSUE TITLE
Undefined method 'devise' (OmniauthCallbasksController)

### ISSUE THREAD

**Issue by mkralik** [plataformatec/devise#3692]
Hello, today I have tried to move my application to heroku for the first time, but when I want to open the page I get the following error. I am not using oauth functionality yet. 

/app/app/controllers/users/omniauth_callbacks_controller.rb:3:in `<class:OmniauthCallbacksController>': undefined method `devise' for Users::OmniauthCallbacksController:Class (NoMethodError)
2015-07-30T14:35:17.790120+00:00 app[web.1]: 	from /app/app/controllers/users/omniauth_callbacks_controller.rb:1:in `<top (required)>'

It works just well on my locale environment.
Any idea what I have missed? 

Thanks a lot, 
Miroslav

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
