### ISSUE TITLE
Transient uninitialized constant Devise::Encryptor error

### ISSUE THREAD

**Issue by thinkalike-dev** [plataformatec/devise#3693]
Hey there,

We started seeing the uninitialized constant Devise::Encryptor error intermittently after upgrading devise to 3.5.1. We see it when we create a new user with a password. Any thoughts  ?

Thanks!

**Comment by josevalim** [comment]
We need to release a bug fix. I will try to do it tomorrow.

**Comment by lucasmazza** [comment]
@josevalim given d9939d1ea01e53a53023511f48491544821bea3d  we can close this one, right?

**Comment by thinkalike-dev** [comment]
Yup. Thanks @josevalim and @lucasmazza.
