### ISSUE TITLE
current_user return hash instead of object

### ISSUE THREAD

**Issue by TangMonk** [plataformatec/devise#3694]
I am using `* devise (3.5.1)`

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by sb1752** [comment]
I'm experiencing this issue. @TangMonk did you figure it out?

**Comment by TangMonk** [comment]
@sb1752 sorry, I cannot help you. I forget

**Comment by sb1752** [comment]
No worries. Looks like clearing the browser solves it.

**Comment by TangMonk** [comment]
@sb1752 :+1:

**Comment by hamzaaltaf** [comment]
@sb1752  hey did you find solution to this issue?

**Comment by sg552** [comment]
I met the same problem!  

at beginning, Rails's devise helper method ( `current_account` ) just return an `hash`, but not an `object`

and then, when I restarted the Rails server, it throw error, `wrong number of arguments (given 6, expected 2)`  

and I switched to another browser ( from firefox to chrome) then everthing goes well. 

really wired.
