### ISSUE TITLE
Omniauth with multiple models

### ISSUE THREAD

**Issue by rizalmuthi** [plataformatec/devise#3696]
Hi I have look into this wiki
https://github.com/plataformatec/devise/wiki/OmniAuth-with-multiple-models

the thing is, it did not tell how do we know the outh for which model?

Let say I have User and Employee classes.
If both directed to this `get "/auth/:provider/callback" => "autenthications#create"`

How do we know whether a client/user register for User or Employee?

Hope there is a clear explanation about this.

Thanks

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
