### ISSUE TITLE
DatabaseAuthenticatable strategy not connecting to database?

### ISSUE THREAD

**Issue by bitops** [plataformatec/devise#3700]
Hello, I am integrating Devise into a Rails 4.0.5 application. I have followed the installation instructions and also tested out Devise on a bare-bones Rails application.

I have generated a ```Staff``` model and added all the proper directives to the model to ensure that it participates in database authentication. I have the database migrated and everything appears to be set up properly.

However, when I attempt to log in, I continually get a 401. I've dug in and it appears that the problem is in  ```warden-1.2.3/lib/warden/proxy.rb```.

Context:

```ruby
    337: def _run_strategies_for(scope, args) #:nodoc:
    338:   self.winning_strategy = @winning_strategies[scope]
    339:   return if winning_strategy && winning_strategy.halted?
    340: 
    341:   # Do not run any strategy if locked
    342:   return if @locked
    343: 
    344:   if args.empty?
    345:     defaults   = @config[:default_strategies]
    346:     strategies = defaults[scope] || defaults[:_all]
    347:   end
    348: 
    349:   (strategies || args).each do |name|
    350:     strategy = _fetch_strategy(name, scope)
   => 351:     next unless strategy && !strategy.performed? && strategy.valid?
    352: 
    353:     self.winning_strategy = @winning_strategies[scope] = strategy
    354:     strategy._run!
    355:     break if strategy.halted?
    356:   end
    357: end
```

The issue is the ```strategy.valid?``` call. It always returns false. I've tried force-evaluating the ```strategy._run!``` call and it returns ```:not_found_in_database```. However, in the Rails logs it appears that the database is never actually queried! There are no SQL traces (which there are in my bare-bones application). 

I can't tell if this is a problem in my configuration or a legitimate bug in Devise/Warden. All insight is appreciated!

**Comment by josevalim** [comment]
Well, if you think this is a bug, you  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by bitops** [comment]
@josevalim thank you for the quick feedback. I looked at CONTRIBUTING.md so let me be a good citizen by first stating:

Rails = 4.0.5
Devise = 3.5.1
Warden = 1.2.3 

In response to your message: I guess that's partly my issue - I'm not sure what further information I can really provide? All I've done so far is add devise to my Gemfile, bundle installed it, then run the 'devise install' command followed by the model generation steps. 

The only non-standard step is in my routes:

```ruby
  devise_for :staffs, controllers: { sessions: "sessions" }
```

The SessionsController just looks like this:

```ruby
class SessionsController < Devise::SessionsController
end
```

Beyond that, everything else is vanilla Devise as far as I can tell. On StackOverflow I found one person who seems to have the same issue: http://stackoverflow.com/questions/22933966/warden-not-accessing-the-database-devise but the question was never resolved.

It sure *seems* like a bug that DatabaseAuthenticatable is not connecting to the database, but maybe I'm doing something wrong. If this line of inquiry is still inappropriate for the bug tracker let me know.

If you let me know what possible information could help you investigate the problem let me know and I'll be happy to provide. Thank you!

**Comment by josevalim** [comment]
Can you provide a sample application that reproduces the issue? The reason I am skeptical this is happening with vanilla Devise as we would have gotten reports like this right after Devise 3.5.1 would be out. So there is probably a detail somewhere that is the cause. :)

**Comment by bitops** [comment]
Sure thing - I'll see if I can put something together. Stay tuned! :)

**Comment by bitops** [comment]
@josevalim I was able to reproduce the issue in this simple Rails app: https://github.com/bitops/devise-issue-3700

I think I've figured out the cause of the problem, but I'm not sure if it's a bug or perhaps a scenario where Devise could alert the implementer that they're about to have a bad time.

The issue is having a custom SessionsController and a corresponding new.html.erb for the login page. This is the same scenario as in the original app that is having the problem (which I can't share publicly). We are migrating from a different auth mechanism to Devise but we already had a ```SessionsController``` place. So having that view there is causing some problems.

If you tell me that this is not a bug I'll definitely be sympathetic to that point of view but wanted to share with you my findings. Thanks!

**Comment by josevalim** [comment]
Ah, I think the issue is not that you have the new.html.erb page but that the new.html.erb page is wrong in that it won't set the data in the format that Devise expects. As such, then it indeed will never do a query because it doesn't even see the parameters. So it is not a devise bug. :)

**Comment by josevalim** [comment]
Goob job! I am glad you found this out!

**Comment by bitops** [comment]
@josevalim me too! I was definitely ready to turn in my badge on Friday. :smile_cat:
