### ISSUE TITLE
ActionController::InvalidAuthenticityToken with Google Omni-auth2

### ISSUE THREAD

**Issue by simkessy** [plataformatec/devise#3704]
I'm getting this error 

```
Started DELETE "/user/sign_out" for 10.0.2.2 at 2015-08-11 15:06:41 -0400
Processing by Users::SessionsController#destroy as HTML
  Parameters: {"authenticity_token"=>"+cSPLRSfkdoBSQRyktSQnWUsWMRFg0B2eE/s4quTZwPlbXQQr9zVEt4QMZcwEoauASwPJ5bzvT6xQcAD3KrLBw=="}
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 49]]
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 85ms (ActiveRecord: 1.2ms)

ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken:
```

I'm not sure what's causing the issue. It was never a problem with Facebook authentication

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by fabn** [comment]
@simkessy I'm getting the same error on valid requests. Did you ever solve this issue. Maybe it's an issue with omniauth-google-oauth2 gem.

@rafaelfranca sorry to bother with this, it's just to be sure that this is not a devise issue.

**Comment by rafaelfranca** [comment]
It is a CSRF token authenticity problem so it seems to be a problem with the form that is sending the wrong token.
