### ISSUE TITLE
Devise rails session ID and first redirection

### ISSUE THREAD

**Issue by nakwa** [plataformatec/devise#3706]
It turns out that getting the session ID (with session[:session_id]) after login with Devise (authentication gem) (either in session_controller or in after_sign_in_path_for) does not return the same thing before and after redirecting for the first time, after logging-in.

Is anyone able to explain me why ? Is there any way to get the final session ID before redirecting ?

**Comment by Gee-Bee** [comment]
> Is anyone can explain me why ?
I'll try. In short:
* `Devise` has nothing to do with it
* `Warden` has something to do with it -  it's setting `:renew` option on session, after setting user ([proxy](https://github.com/hassox/warden/blob/74162f2bf896b377472b6621ed1f6b40046525f4/lib/warden/proxy.rb#L174), [spec](https://github.com/hassox/warden/blob/74162f2bf896b377472b6621ed1f6b40046525f4/spec/warden/proxy_spec.rb#L196))
* Actual action takes place in in `Rake::Session::Abstract[#commit_session](https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L332)` which updates session_id (by calling [destroy_session](https://github.com/rails/rails/blob/e20dd73df42d63b206d221e2258cc6dc7b1e6068/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb#L63) and [set_session](https://github.com/rails/rails/blob/e20dd73df42d63b206d221e2258cc6dc7b1e6068/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb#L103) implementented in `ActionDispatch::Session::CookieStore`)

> Is there any way to get the final session ID before redirecting ?
Sure it is. Bear in mind that `Warden` is changing session_id after authentication to prevent [session fixation](https://en.wikipedia.org/wiki/Session_fixation) attacks, so in overriden devise controller you should manually change session_id in addition to disabling `:renew` session option. This will do:
```ruby
session.options[:id] = session.instance_variable_get(:@by).generate_sid
session.options[:renew] = false
```

**Comment by ndvbd** [comment]
How can we get the new session id after authentication? session.options[:id] shows the old value
