### ISSUE TITLE
iOS “Bookmark to Homescreen” removes cookies and session?

### ISSUE THREAD

**Issue by karlingen** [plataformatec/devise#3709]
When I open my webapp on my iOS device, login and restart Safari, I am still logged in.

But when I add this Page with "Add to Home Screen", each Time i click the Icon for that page, I have to login again.

Is there a workaround for this nasty issue?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
