### ISSUE TITLE
unlock_access_by_token not working - invalid token

### ISSUE THREAD

**Issue by dayweek** [plataformatec/devise#3711]
Hi guys,

when I run `User.unlock_access_by_token '1e3f9c8987aaaa28318ec853031a0072860a163cc9a577efe424b289bf0034d1'` it does not unlocks the user even if the user has unlock_token equal to `1e3f9c8987aaaa28318ec853031a0072860a163cc9a577efe424b289bf0034d1`

Even if I click the link in the unlock email it tells me: invalid token.

It looks like I'm doing something wrong because this functionality has been here for quiet some time.

devise (3.5.2)
rails (4.2.3)

Thanks

**Comment by josevalim** [comment]
The tokens are encrypted. You need to use `@token` when sending e-mails instead of accessing the token directly.

**Comment by dayweek** [comment]
thanks @josevalim I probably had outdated version of email template.
