### ISSUE TITLE
sign_in() after user sign in

### ISSUE THREAD

**Issue by MarkMT** [plataformatec/devise#3716]
No response to this in the google group, and this is potentially a code issue, so...

In the `create` action of the Devise's default `SessionsController`, after calling `warden.authenticate!`, a call is made to the method `sign_in`:

    def create
      self.resource = warden.authenticate!(auth_options)
      ...
      sign_in(resource_name, resource)
      ...
    end

Reading the code for these methods, it seems that the main purpose of `sign_in` is to add the user to the session by calling `warden.set_user`. But `warden.authenticate!` also seems to do this via `_perform_authentication`, so in practice the call to `sign_in` doesn't seem to be required here apart from serving to call `expire_data_after_sign_in!`

Is there in fact a use case in which the call to `sign_in` is necessary? Or could this be removed from the default implementation of `SessionsController#create`?

**Comment by josevalim** [comment]
That seems to be mostly it. And potentially to run callbacks to.

**Comment by MarkMT** [comment]
I don't think callbacks are a factor here. As far as I can see they're run in `warden.set_user`, but my point was that that method doesn't actually get called by `sign_in` if we got through `authenticate!` successfully. 

`sign_in` does store the user in the session directly (rather than using `set_user`) if you pass the `:bypass` option. But there is no option passed to it from the `SessionsController#create` action.

So it seems that we're left with `expire_data_after_sign_in!`, which removes any data from the session with a key starting with `devise.`. But it's not clear to me what that data is. I checked my own app and `session.keys.grep(/^devise\./)` is empty. Is this just anticipating the possibility that an app developer might choose to save something that needs to be expired?

**Comment by josevalim** [comment]
The expire_data_after_sign_in! is used, I believe, in a bunch of omniauth callbacks. For example, you can keep metadata there, and it is automatically cleared oncee you sign in (or you can cancel signed in). It can also be used by 3rd party plugins.

**Comment by MarkMT** [comment]
Thanks for clarifying.
