### ISSUE TITLE
OmniAuth with multiple models

### ISSUE THREAD

**Issue by bigimot** [plataformatec/devise#3718]
Hi, I'm trying to set up OmniAuth with multiple models.

I've followed everything here: https://github.com/plataformatec/devise/wiki/OmniAuth-with-multiple-models but it seems like the OmniAuth routes are not being generated, so I'm getting 'user_omniauth_authorize_path' when trying to test it.

In the instructions the callback route is added manually. Shouldn't I add the authorize one as well?
I tried to do that, but ran into other errors, so figured I'll try to get some help here.

Since my code is exactly the same (fairly new app) I'm not sure if there is a point of adding a .gist, but I can do that if needed.

Thanks in advance.

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
