### ISSUE TITLE
Un-digested confirmation_token stored in database

### ISSUE THREAD

**Issue by trusche** [plataformatec/devise#3721]
Using version 3.5.2, I'm observing this behaviour:

```
Started POST "/users" for 127.0.0.1 at 2015-08-23 15:23:26 +0100
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Ou6rlp4aa4dxKXjku97NYqh7RIlko4G+KFiHg6VbeCANxtduSNM2LMo3q+TDXRmeUj247GWrbFIwTfW97ss/HA==", "user"=>{"email"=>"foo123123@bar.com", "name"=>"test", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
   (0.2ms)  BEGIN
  User Exists (0.8ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'foo123123@bar.com' LIMIT 1
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`confirmation_token` = '0915b87b8532caac67583ea97c3989f3057f4ade4b93fea68456fd3f36ec88ef'  ORDER BY `users`.`id` ASC LIMIT 1
  SQL (0.8ms)  INSERT INTO `users` (`email`, `encrypted_password`, `name`, `created_at`, `updated_at`, `confirmation_token`, `confirmation_sent_at`) VALUES ('foo123123@bar.com', '$2a$10$3g/Q0J0IoH3QCCVQMqcSneJUxQefFhRF76HxHyW7itWBAwLUNzQi.', 'test', '2015-08-23 14:23:26.499318', '2015-08-23 14:23:26.499318', 'xZsrymsxnG6EpCsgtnyr', '2015-08-23 14:23:26.729303')
  Rendered devise/mailer/confirmation_instructions.html.haml (7.6ms)
```
The SELECT query uses the digested confirmation_token for the existence test, but the INSERT then uses the **un-digested** token, which is (correctly) sent out in the email:

```
<p>
  Welcome test234@test.com!
</p>
<p>You can confirm your account email through the link below:</p>
<p><a href="http://localhost:3000/users/confirmation?confirmation_token=AwQz1g99Fx-DzAbLUNLj">Confirm my account</a></p>
```
 Is this a regression? Downgrading to 3.4.1 solves the issue for me.

**Comment by josevalim** [comment]
No, it is by design and still backwards compatible. We no longer send the encrypted token to improve usability. It is also not a security concern because confirmation does not autoamtically sign the user in.

**Comment by trusche** [comment]
Hmmm. Ok, but then the existence test is wrong, no? Or what's the second SELECT query above for?

**Comment by josevalim** [comment]
@trusche isn't that checking for the e-mail uniqueness?

**Comment by trusche** [comment]
@josevalim That's the first one. The second one seems to check for uniqueness of one version of the confirmation_token:

```
User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`confirmation_token` = '0915b87b8532caac67583ea97c3989f3057f4ade4b93fea68456fd3f36ec88ef'  ORDER BY `users`.`id` ASC LIMIT 1
```

only to insert another (abbreviated):
```
SQL (0.8ms)  INSERT INTO `users` (... `confirmation_token`,...) VALUES (...'xZsrymsxnG6EpCsgtnyr'...,')
```

**Comment by josevalim** [comment]
When we generate tokens, we check they don't exist in the database, and generate a new one. better than letting it crash. We also can't show an error to the user.

**Comment by trusche** [comment]
I get that that's what it's intending to do - but I would expect the INSERT to use the same token that the previous SELECT just checked for (which didn't exist, so the check passed), instead of a different one? Or am I missing something?

**Comment by monfresh** [comment]
I believe this is the same issue I am running into in #3725. The change is definitely not backwards compatible.
