### ISSUE TITLE
Create/Update Fail Redirect Location Should be Overridable

### ISSUE THREAD

**Issue by thenadz** [plataformatec/devise#3722]
All of the other redirect paths in these methods allow overriding the location (eg: after_inactive_sign_up_path_for or after_update_path_for), but the failure paths for both do not allow this. This seems to arbitrarily not match functionality in other areas of the code and seems to be a trivial enhancement -- am I missing the reason why this is not supported?

I'm happy to develop the pull request if there is not a reason for the functionality not to exist.

**Comment by carlosantoniodasilva** [comment]
There's no actual redirect going on when the actions fail to [create](https://github.com/plataformatec/devise/blob/b12658782ff41cbd2e418a4974779f51e3675466/app/controllers/devise/registrations_controller.rb#L30-L32)/[update](https://github.com/plataformatec/devise/blob/b12658782ff41cbd2e418a4974779f51e3675466/app/controllers/devise/registrations_controller.rb#L59-L60), when the resource fails it by default should redisplay the page with any errors associated with the object (or respond with errors in case of an ajax request for example). Is that what you refer, or am I misunderstanding your question? Thanks

**Comment by brxue** [comment]
Hi @carlosantoniodasilva , how about the case when posting a user update form from a different controller other than RegistrationController? In this case, we may need to redirect to the link where the form is shown.

For example, we may have a user settings page, which include user profile form, account updating form and etc.

**Comment by CollinGraves** [comment]
^^ Sounds like something easily fixed with routing.

**Comment by jakehockey10** [comment]
I am having trouble finding information elsewhere that would help me with my situation: when the update through the `RegistrationsController` fails, the layout being applied to the `edit` action in the controller does not persist.  I end up losing my sidebar, navigation up-top, and everything else except for the inner most yield consisting of my form with errors.

Does anyone know how the failure of update can be patched on my side to continue using the layout I want?  Thanks
