### ISSUE TITLE
Upgrading to 3.5.2 is causing confirmation tokens to be invalid in some scenarios

### ISSUE THREAD

**Issue by monfresh** [plataformatec/devise#3725]
Hi. A change in 3.5.2 is breaking our app with regards to confirmation tokens in certain scenarios.

Here is an example of one edge case test in our app that is now failing after upgrading to 3.5.2:

In our app, we allow users to create an account with just an email address. Here are the steps:
1. User clicks the "Create Account" button
2. They enter a valid email address and submit the form
3. They receive a confirmation email and click on the link in the email to confirm their email. So far, so good. Their email is confirmed.
4. At this point, they are then prompted to choose their password. However, instead of entering a password, they go back to the home page, and click on "Forgot your password?"
5. They fill in their email and click "Send me reset password instructions"
6. They receive an email and click the link to reset their password

Expected Result: They are able to set their password
Actual Result: They get an error: "Confirmation token is invalid"

**Comment by monfresh** [comment]
My guess is that this change is causing the issue: https://github.com/plataformatec/devise/commit/eb640ed344fb5e227e82b1f3a914ca9fabb938e0

This is our code that finds the user based on their confirmation token:
```ruby
def with_unconfirmed_confirmable
  confirmation_token = Devise.token_generator.digest(
    User, :confirmation_token, params[:confirmation_token])

  @confirmable = User.find_or_initialize_with_error_by(:confirmation_token, confirmation_token)

  if @confirmable.confirmed?
    @confirmable = User.confirm_by_token(params[:confirmation_token])
  end

  yield
end
```
Specifically, it's this line that is now failing:
```ruby
@confirmable = User.find_or_initialize_with_error_by(:confirmation_token, confirmation_token)
```
With 3.5.1, `@confirmable` does not have any errors. With 3.5.2, `@confirmable.errors.full_messages` is `["Confirmation token is invalid"]`.

**Comment by monfresh** [comment]
Here's another very common scenario that is failing: when a user changes their email address and confirms the new one.

1. Existing confirmed user signs in
2. User goes to edit their profile
3. User fills in the email field with their new email address and enters their password to confirm the change
4. User receives an email with a confirmation link
5. User clicks the link to confirm their new email address

Expected Result: User sees "Your email address has been successfully confirmed."
Actual Result: User receives an error message: "Confirmation token is invalid"

**Comment by josevalim** [comment]
Thank you. I will investigate this tomorrow.

**Comment by monfresh** [comment]
Thanks! I copied over the 3.5.2 code to my machine and narrowed it down to the `generate_confirmation_token` method in `confirmable.rb`. If I restore it to the 3.5.1 code, everything works as it should.

**Comment by josevalim** [comment]
Do you have custom confirmation code by any chance? We definitely changed the generation but we should match on both.

**Comment by josevalim** [comment]
Ah, yes. The bug is in your code. Devise 3.5.2 no longer digests confirmation tokens.

However, the bug is my fault. I mistakenly assumed the change would be backwards compatible, because both old and new confirmation tokens are looked up (so it is compatible for end-users) but I completely forgot that folks using Devise may rely on the current token scheme.

I am sorry. I don't think there is much I can do at this point. If we revert in 3.5.3 it will only cause more confusion and be backwards incompatible for end-users. So you will have to update your code. :(

**Comment by tirdadc** [comment]
Found this thread after looking for a solution to this issue with the 3.5.2 upgrade. Just had to change:

`@confirmable = User.find_or_initialize_with_error_by(:confirmation_token, confirmation_token)`
to:
`@confirmable = User.find_or_initialize_with_error_by(:confirmation_token, original_token)`

and I removed the line where the original_token gets transformed into confirmation_token.

**Comment by rndstr** [comment]
I ran into the same issue after following the wiki [How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation)

It took me a while to realize but as you guys probably already know, Devise 3.5.2 went back to pre 3.1 where confirmation tokens are no longer encrypted in the db. So you should use [For Rails 3/4 & Devise 2.x-3.0, Devise 3.5.2+](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation#for-rails-34--devise-2x-30-devise-352) instead. I just updated the wiki to reflect this.
