### ISSUE TITLE
Anchor disappears after log in

### ISSUE THREAD

**Issue by Machiaweliczny** [plataformatec/devise#3727]
When user was not logged in devise `3.2.4` it redirected from url like this one `page_url#/some_spa_path#spa_anchor` into `page_url#/some_spa_path%23spa_anchor` which caused me  some bug, so I tried to update to newest version of devise `3.4.1` and now anchor is completly ignored. I get redirected from `page_url#/some_spa_path#spa_anchor` to `page_url` only :(

Is it bug on your side? I really need this functionality and don't know where it will be easiest to fix it. But it almost worked in 3.2.4 so I think I should remove this anchor encoding somehow and it will be fine. 

But I would like to know why you dropped this functionality at all?

**Comment by carlosantoniodasilva** [comment]
You need to give us more information or a way to reproduce the issue, like an example app that reproduces it, otherwise it's very complicated to help. Thanks!

**Comment by josevalim** [comment]
This information is kept by the client, often it is not received by the server.

**Comment by Machiaweliczny** [comment]
Ok, we had overriden `Devise::Controllers::SignInOut` in this project which does manipulation of anchors synchronised through cookies. So we had basically monkey patched devise a little bit, that's why at first I thought it was in original gem because it stopped working with version change. Everything is clear and working now. Thanks for your patience and sorry for missleading information at first.

**Comment by spacewaffle** [comment]
@Machiaweliczny can you go into some detail on how you modified the controller for this?
