### ISSUE TITLE
Can't finder user with email params.

### ISSUE THREAD

**Issue by skorecky** [plataformatec/devise#3729]
When I do something like 
`User.find_by_email("foo@bar.com") => #<User>`

But when I try to pass in the email from params
`User.find_by_email(params[:email]) => nil`

I don't understand why I can't get a user object back when I try passing it in with params. I can use ID and that works, but if I try it with email I get back nil.

**Comment by carlosantoniodasilva** [comment]
What value is in `params[:email]`?

**Comment by skorecky** [comment]
"foo@bar.com" when I log to console.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
