### ISSUE TITLE
Devise + Omniauth: CSRF Detected

### ISSUE THREAD

**Issue by jwg2s** [plataformatec/devise#3731]
Hi all,

We have a web application that uses devise for user authentication, and omniauth in order to connect social media accounts to a user's account - BUT not allow authentication into our application with those social media accounts.

We are running into a situation where an already-signed-up user (numerous) is attempting to add a social media account to their profile, but my theory is that devise is picking up on the presence of the omniauth params within the request and trying to authenticate.  The user is then redirected to the signin URL (without the omniauth params) and they are authenticated, but adding the social media account fails because of this.

FWIW, this behavior is inconsistent.  Sometimes users are successfully able to add an account and others they are not (even with the exact same account).

How do you recommend using devise + omniauth in this scenario?

I'm happy to provide additional info, but want to make sure the information I provide is relevant as to not inundate this ticket with unnecessary info.  Also have researched this extensively for days - I've determined that devise is definitely causing this redirect and thus is why I'm posting here.

#### Gems
```
devise (3.5.2)
omniauth-google-oauth2 (0.2.6)
omniauth-oauth2 (1.3.0)
```

**Comment by macbury** [comment]
+1

**Comment by georgeguimaraes** [comment]
@jwg2s Hi, have you solved this issue in your app?

**Comment by jwg2s** [comment]
We have, it ended up being a race condition between two requests where one request would sometimes clobber the session details that held the oauth info.

**Comment by georgeguimaraes** [comment]
How did you solve it? Was it related to devise?

**Comment by jwg2s** [comment]
We stopped making the second request entirely, it's still susceptible to race conditions wiping out the session data needed for Oauth unfortunately

**Comment by georgeguimaraes** [comment]
Tks for all the info @jwg2s. I'm gonna close this issue.

To future folks: if you get into something like this issue, please open up a new issue.
