### ISSUE TITLE
Session Hijacking?

### ISSUE THREAD

**Issue by Elyahou** [plataformatec/devise#3735]
When using Rememberable, remember token is always the same and is the encrypted password salt.

So, anyone that have access to another person computer connected to a devise application,  can very quickly, via chrome console for example, steal the remember_user_token, and set it in his own computer to immediately get connected to the other user account.

And more than that, even if the remember_token expires, the hacker could connect when the legitimate user sign in again at is own (since user.remember_created_at is resetted, and remember_token is the same)

Isn't that a serious security issue ?

**Comment by josevalim** [comment]
> anyone that have access to another person computer connected to a devise application

Once you have access to someone else's computer that is the least of your concerns. You can steal the session, any other cookie, install keyloggers or, easier than all of those, just visit the password tab of your browser and grab the application password.

If the assumption is computer access, then all bets are off.

>  (since user.remember_created_at is resetted, and remember_token is the same)

If we reset those, then you can effectively be remembered only on one device.

If you have a sensitive application, the best bet is to not remember tokens, or to do a schema where you have one token per device.
