### ISSUE TITLE
Rails 5 alpha : devise-40258bf100c0/lib/devise/failure_app.rb:9:in `<class:FailureApp>': uninitialized constant ActionController::RackDelegation (NameError)

### ISSUE THREAD

**Issue by chasik** [plataformatec/devise#3736]
In ActionPack with Rails 5 no module ActionController::RackDelegation

**Comment by carlosantoniodasilva** [comment]
Thanks, but we don't support Rails 5 yet - once a beta or release candidate is released, we will gladly add official support to it.

Meanwhile please feel free to send any pull request that might help us get closer to having devise working with Rails master. Thanks!

**Comment by jachenry** [comment]
RackDelegation was removed as part of this [commit](https://github.com/rails/rails/commit/d47438745e34d75e03347b54b604b71b7a92c3ac#diff-e7d3aaf1cb8ad2b300b3e1da6f318e50).

**Comment by grex84** [comment]
I'm having the same problem and removing `include ActionController::RackDelegation` gives me another error.  Was this all i needed to do jachenry?

**Comment by jachenry** [comment]
@grex84 That's all I had to to do for this particular issue. There was another issue I faced around routes and scopes but it was not related to this error.

**Comment by djsegal** [comment]
@carlosantoniodasilva: for future reference, this is resolved by #3714

**Comment by afstanton** [comment]
Now that Rails 5 Beta 1 is out, will we see some movement toward supporting it?

**Comment by josevalim** [comment]
Devise master supports Rails 5.

**Comment by afstanton** [comment]
Having just generated a Rails 5 Beta 1 app and installed Devise from the master branch, I can safely say that no, Devise master does not support Rails 5.

**Comment by josevalim** [comment]
Our test suite passes on Rails 5: https://travis-ci.org/plataformatec/devise/jobs/100575093. So if you are running into issues, please do a proper report or send pull requests. :) Be movement you want to see happening.

**Comment by afstanton** [comment]
The error I'm seeing is the one reported here. No need to file an additional report.

**Comment by wuatanabe** [comment]
Hello, devise master seems to work for me with rails 5.0.0.beta1 (installed on Ms Windows).

**Comment by afstanton** [comment]
I'm not sure what I was doing wrong, but I think you're right. My sincere apologies.

**Comment by ifokeev** [comment]
devise_token_auth doesn't work because of Devise 3.5.3 in dependencies (and it has ```include ActionController::RackDelegation``` in ```lib/devise/failure_app.rb```). 
Have no idea how to use it :(

**Comment by fuzzylizard** [comment]
Still seeing this error when using Devise 3.5.3, Rails 5.0.0beta1 and trying to start the server. 

`.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.3/lib/devise/failure_app.rb:9:in `<class:FailureApp>': uninitialized constant ActionController::RackDelegation (NameError)`

This is a brand new application. The only thing I have done to it is to remove turbolinks.

**Comment by josevalim** [comment]
You need to use Devise master for Rails 5.0.0 beta.

**Comment by fuzzylizard** [comment]
I got it working. For others that are experiencing this issue. Pull Devise from github and not rubygems.org. Although the version number is the same, the underlying code is not.

**Comment by stephanngamedev** [comment]
For others tha are using devise_token_auth gem.
I'm using:
```
gem 'omniauth', '>= 1.0.0'
gem 'devise', git: 'git@github.com:plataformatec/devise.git'
gem 'devise_token_auth', git: 'git://github.com/lynndylanhurley/devise_token_auth.git'
```
`gem 'devise', git: 'git@github.com:plataformatec/devise.git'` solves the problem.
`omniauth` is devise_token_auth dependency too.

**Comment by jeremyrajan** [comment]
+1 @stephanngamedev . That works (y)

**Comment by Ynnni** [comment]
@stephanngamedev Thanks! :star:

**Comment by saurabhh** [comment]
Thanks!!

**Comment by MaximAbramchuck** [comment]
@stephanngamedev Thanks! :+1:

**Comment by pavlo** [comment]
Thank you @stephanngamedev!

**Comment by kevinhofmaenner** [comment]
@stephanngamedev Thanks!

**Comment by nishimaki** [comment]
Thank you

**Comment by brunojppb** [comment]
@stephanngamedev Thanks a lot! 👍

**Comment by sunyanl** [comment]
@stephanngamedev thanks :)

**Comment by websumy** [comment]
You also can specify devise version 4.0.0.rc1

`gem 'devise', '4.0.0.rc1'`

**Comment by stimoshik** [comment]
@stephanngamedev Thanks a lot!

**Comment by bestori** [comment]
+1 here for

_gem 'devise', git: 'git@github.com:plataformatec/devise.git'_

**Comment by mohan999** [comment]
gem 'devise', '4.0.0.rc2'

**Comment by AzDarGee** [comment]
This worked for me --> killing my spring servers.

https://jasonplayne.com/web-dev/rails-generate-could-not-find-in-any-of-the-sources
