### ISSUE TITLE
Omniauth With Devise: Given URL is not permitted by the Application configuration

### ISSUE THREAD

**Issue by grouptable** [plataformatec/devise#3740]
We have configured our app following the tips stated here for version 2 of Facebook API.

In the initializers/Devise, we have as below:

config.omniauth :facebook, ENV['APP_ID'], ENV['APP_SECRET'], :scope => 'email,public_profile,user_friends', :display => 'popup' ,
:client_options => {:site => 'https://graph.facebook.com/v2.4',:authorize_url => "https://www.facebook.com/v2.4/dialog/oauth"}, token_params: { parse: :json }

The App itself is configured with callback URL as below:
www.domain.com/users/auth/facebook/callback.

Any amount of tweaking is doing nothing, but throw this error:
One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of
one of the App's domains.

Please help.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
