### ISSUE TITLE
Rubycritic Results

### ISSUE THREAD

**Issue by bparanj** [plataformatec/devise#3741]
Look at this report : 

https://drive.google.com/file/d/0BwPktlS0QfnNQlB1ZjFJVTZaWDA/view?usp=sharing

for the improvements that can be made.

**Comment by josevalim** [comment]
Thank you! I will close this issue as it is more of an enhancement but pull requests that improve the code are always welcome. :)

**Comment by bparanj** [comment]
Code is very clever. I cannot help you there.
