### ISSUE TITLE
ActionController::InvalidAuthenticityToken when login using two devise model (user and admin)

### ISSUE THREAD

**Issue by lechsa** [plataformatec/devise#3742]
Hi,

I create an app using two devise model, user and admin.

I'm following the devise wiki from this link, I'm using the option 1
https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role

So I open two page at the same time, the user login page and the admin login page.
When I login in the admin login page it succeed but when I login on the user page it raise an error ActionController::InvalidAuthenticityToken same goes with the other way.

But if I refresh the page first then I login it will succeed. 

Are they using the same AuthenticityToken? So when the admin logged in, the AuthenticityToken is changed so when I try to login with the user it raise an InvalidAuthenticityToken?

I'm still new to rails :)

Thanks.

**Comment by evertonts** [comment]
@lechsa Could you provide a sample application that reproduces this error?
