### ISSUE TITLE
devise doorkeeper sign_out @resource_owner return false

### ISSUE THREAD

**Issue by vishwasIref** [plataformatec/devise#3745]
Hi ,
       I'm having a doorkeeper application acting as login service,I'm having one other client app using this login service to authenticate users.So when I logout from client app (Not login service) . I send a call to login service with access_token to sign_out resource owner from login service but its not working and sign_out method return false.
Here is my code 
```destroy_session``` get called when I logout from client app

```ruby

  before_action :doorkeeper_authorize!

  def destroy_session
    @current_user = find_current_user
    if @current_user
      sign_out @current_user
      # redirect_to root_url
    end
  end


  private

  def find_current_user
    resource_owner_id = doorkeeper_token.resource_owner_id
    user  = nil
    if !resource_owner_id.nil?
      user = User.find(resource_owner_id)
    end
    user
  end
```

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
If you intended to provide a bug report,  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
