### ISSUE TITLE
facebook not completely logged out 

### ISSUE THREAD

**Issue by 1mrankhan** [plataformatec/devise#3746]
Hi, 

Once Clicking the logout link , facebook not completely logged out. Below is my code

    def facebook
    @admin = Admin.from_omniauth(request.env["omniauth.auth"])
    omniauth = request.env["omniauth.auth"]

    if @admin.persisted?
      sign_in_and_redirect @admin
      session[:fb_token] = omniauth["credentials"]["token"] if omniauth['provider'] == 'facebook'
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_admin_registration_url
    end
    end

and inside my application controller i have the function like 

    def facebook_logout
    split_token = session[:fb_token].split("|")
    fb_api_key = split_token[0]
    fb_session_key = split_token[1]
    redirect_to "http://www.facebook.com/logout.php?api_key=#{fb_api_key}&session_key=#fb_session_key}&confirm=1&next=#{destroy_admin_session_url}"
    end

Thanks.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
