### ISSUE TITLE
Rails.application.routes.recognize_path and authenticated route

### ISSUE THREAD

**Issue by harold-s** [plataformatec/devise#3747]
Hello,

I am trying to use Rails.application.routes.recognize_path on a Paper_trail routes.rb authenticated path (authenticate :user do in config/routes.rb) but I get an exception.

in config/routes.rb :
```ruby
authenticate :user do
  resources :authenticated_ressources
end
```
If I call
```ruby
Rails.application.routes.recognize_path('/authenticated_ressources/')
```
I get
```
NoMethodError: undefined method `authenticate!' for nil:NilClass
	from ruby-2.2.1/gems/devise-3.4.1/lib/devise/rails/routes.rb:459:in `block in constraints_for'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:41:in `call'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:41:in `block in matches?'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:39:in `each'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:39:in `all?'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:39:in `matches?'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:828:in `block in recognize_path'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:65:in `block in recognize'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:59:in `each'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:59:in `recognize'
	from ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:817:in `recognize_path'
	from (irb):22
	from ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from ruby-2.2.1/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `
```
Non authenticated routes work well :
```ruby
Rails.application.routes.recognize_path('/')
```
returns
```ruby
{:controller=>"home", :action=>"index"}
```

My basic problem is I would like to know if two users are currently watching the same page. (same controller, same action and same id). I am currently saving a :last_url adress on each user.
I could compare the strings but the url may have differents GET arguments.

Any idea how to use recognize_path without devise interfering ?

Thanks !

**Comment by lucasmazza** [comment]
`recognize_path` won't work as is with constraints that require request related objects (like the warden instance that Devise expects to be in the request env Hash). If you are doing this inside a controller code you might be able to pass the `warden` object from `request.env` to the `recognize_path` call, or try to pass down the object down the the class that is recognizing the path.

In the other hand, as `recognize_path` isn't a documented public API, I **strongly** suggest you to not use it and save pieces of the params `Hash` instead of the raw URL on your application.

I'm closing this as it isn't an issue on Devise.
