### ISSUE TITLE
Customize flash keys (again)

### ISSUE THREAD

**Issue by aried3r** [plataformatec/devise#3748]
[This](https://github.com/plataformatec/devise/issues/2051) has [been](https://github.com/plataformatec/devise/issues/2282) discussed [quite](https://github.com/plataformatec/devise/pull/748) often. And I'm sure I didn't pick up all discussions, but I still want to address this one more time, since some of these discussions are quite old.

First of all, I think some points are no longer 100% valid.
>You cannot do that. Just use :notice and :alert which are Rails conventions. Thanks. [*@josevalim*](https://github.com/plataformatec/devise/issues/2051#issuecomment-8192991)

It's true that even now, [only two flash types are predefined](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/metal/flash.rb#L10), but the ability to add custom flash types has existed since [July 2012](https://github.com/rails/rails/commit/238a4253bf229377b686bfcecc63dda2b59cff8f) which will also work just like [the regular ones](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/metal/flash.rb#L29-L30). So these two exist for convention but you are not limited in any way to stick to these.

One thing I cannot comment on, because I didn't study the code in-depth is
> Thanks for pinging us! However, this would make the code more complex and given Rails already picked up notice and alert as convention, I don't think the trade-offs are worthy in this case.

Why I think at least a third flash key would make sense, is because some messages aren't a success nor an alert but just an info. The best being the ["You're already logged in" message](https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/app/controllers/devise_controller.rb#L109). It's not an error, it's also not a success. You just *are* already logged in.

Since the code has changed quite a bit since 2010, 2012 and 2013 (where the linked discussions are from), I wanted to ask if this is still off the table and would add too much complexity? I'd welcome if it was optional at least, like the example above, let "You're already logged in" be an alert unless I've specified otherwise.

I hope you're not bothered by yet another issue about this, but it somewhat unnecessarily limits my styling capabilities and I felt it's wrong to apply and even duplicate devise code for a workaround. :)

**Comment by josevalim** [comment]
Thanks for opening the issue. I would say this is still off the table. Devise already has too many configuration options, I am definitely not looking forward to add at least two more.

**Comment by aried3r** [comment]
Ok, fair enough. Thanks, though. I'll use one of the workarounds then :)
