### ISSUE TITLE
Show a custom message after sign up that requires approval

### ISSUE THREAD

**Issue by nivla** [plataformatec/devise#3749]
I'm following the guide "How To: Require admin to activate account before sign_in"

Under the Model changes section, we create two message entries in the i18n file, :not_approved and :signed_up_but_not_approved.

After following the steps in the guide, the not_approved message shows up when I try to sign in with an unapproved account, so that works.

But the signed_up_but_not_approved message doesn't appear to show up anywhere. Instead, after sign up the unauthenticated message is shown: "You need to sign in or sign up before continuing." This happens because you're redirected to a page that requires authentication. Instead I want the signed_up_but_not_approved message to show up directly after a sign up.

What can I do?

Also this issue was  previously reported in https://groups.google.com/forum/#!topic/plataformatec-devise/-d17-v7abu0

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
