### ISSUE TITLE
Add option to prevent multiple models signed in at the same time

### ISSUE THREAD

**Issue by collimarco** [plataformatec/devise#3750]
I have two separate Devise models (Consumer and Shop).

I'm looking for a way to prevent a browser being logged in at the same time both as a Consumer and a Shop. For example, if he's logged in as a Consumer, he must first log out before logging in again as a Shop.

Is there an option to force mutual exclusion (one model logged in at a time)?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
(but there isn't anything builtin)
