### ISSUE TITLE
Bypass: true with active_for_authentication?

### ISSUE THREAD

**Issue by zach-taylor** [plataformatec/devise#3751]
I'm using Rails 4.2.3, Devise 3.5.2, and Warden 1.2.3.

I think this might be a bug, but I'm not sure. I'm attempting to log in as a user that is disabled (via `active_for_authentication?` in the `User` model by using `sign_in(@user, bypass: true)`, however it seems that `active_for_authentication?` is still being called even though (I think) [this callback](https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/hooks/activatable.rb) is supposed to be skipped.

I'm just hardcoding `false` into the `active_for_authentication?` method.

Any help would be appreciated. Thanks!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
If you think this is a bug,  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
