### ISSUE TITLE
a way to switch databases based on current_user with device?

### ISSUE THREAD

**Issue by rubytastic** [plataformatec/devise#3752]
I would like to have a mechanism where a seperate "demo" database will be used if devise current_user has a flag demo == true for example. 

Are there some devise internals I could hook into for this or has anyone an idea how to best implement this in devise, so im not re-inventing the wheel?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
