### ISSUE TITLE
current_user found before sign_in

### ISSUE THREAD

**Issue by forever-ram** [plataformatec/devise#3763]
Hi
I've override the create action of session controller in my app for write the my own code for sign in.
I've captcha validation code in my create action but if I provide an invalid captcha still I get signed in and got the current_user.

here is my controller code 

    class SessionsController < Devise::SessionsController
      def create
        if captcha_valid? params[:captcha]
          super
        else
          sign_out
          flash[:error] = "Captcha code is not valid."
          redirect_to new_user_session_path
        end
      end
    end

My User model 

    class User < ActiveRecord::Base
      acts_as_paranoid
      has_paper_trail :ignore => [:sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :confirmed_at]

      attr_accessor :current_step
      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable and :omniauthable
      devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    end

when my control come to the create action if I check for current_user I got the user who's email/ password I've provide in sign in form

I think the `create` action not override properly and it call the default `create` action first and than come to my local `create` action 
I don't know what exactly happening, please let me know what I'm doing wrong.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
