### ISSUE TITLE
ActionController::UnknownFormat in Devise::RegistrationsController#create

### ISSUE THREAD

**Issue by abdullah-abunada** [plataformatec/devise#3765]
Hi everybody,
I faced the following problem while using devise:
ActionController::UnknownFormat in Devise::RegistrationsController#create
ActionController::UnknownFormat in Devise::SessionsController#new
etc,,,

-- my route file
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults:	{	format:	:json	}, constraints:	{	subdomain:	'api'	},	path:	'/' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources	:sessions,	:only	=>	[:create,	:destroy]
    end
  end
end

best,
Abdullah

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
