### ISSUE TITLE
reset  password token gets lost after the form submit

### ISSUE THREAD

**Issue by AlexanderPavlenko** [plataformatec/devise#3772]
Steps to reproduce:

1. request password reset on `/users/password/new`
2. follow mailed link `/users/password/edit?reset_password_token=blabla`

(rendered html contains `<input type="hidden" name="user[reset_password_token]" id="user_reset_password_token" value="blabla" />`)

3. enter not matching password and confirmation 
4. submit form, observe "doesn't match Password" error on confirmation field

(rendered html contains `<input type="hidden" name="user[reset_password_token]" id="user_reset_password_token" />` without value!)

5. enter matching password and confirmation
6. submit form, observe "Reset password token can't be blank" error

devise (3.5.2)
warden (1.2.3)
rails (4.2.3)

**Comment by josevalim** [comment]
Thanks for the report. Can you reproduce it in a sample application? Because it works out of the box here. IF you can push a small app to github I would love to take a look at it.

**Comment by AlexanderPavlenko** [comment]
Sorry, it was a bug in the custom view.
