### ISSUE TITLE
rails generate devise User

### ISSUE THREAD

**Issue by luizamboni** [plataformatec/devise#3776]
using     
devise (3.2.0)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)

Rails 4.1.8 and  ruby 2.2.0p0

the command "rails generate devise User" generate a file wihtout ".rb" extension(without any extension realy), not identified when we run "rake db:migrate" after, is need change the extension for db:migrate recognize the migration.(no error is raised, what is bad)

**Comment by nashby** [comment]
I believe it was fixed in Devise 3.2.3+ can you please try to upgrade and see if it works?
