### ISSUE TITLE
Password hashing (bcrypt/scrypt)

### ISSUE THREAD

**Issue by milgner** [plataformatec/devise#3779]
Hello all,

I saw that there were a couple of advances in the past to get scrypt into devise which were rejected due to different reasons. The common solution for this still seems to be using the devise-encryptors and devise-scrypt gems which means a number of additional of moving parts.

I wonder whether this limitation is a fundamental decision or just lack of recent pull requests?
bcrypt has the non-obvious drawback of being limited to 72 characters (fewer in some implementations) which is not present in scrypt. Also the increased memory requirement of scrypt vs bcrypt makes it an attractive alternative.

Additionally I want to suggest increasing the default for `config.stretches` from 10 to something like 14 to account for CPU speed gains since the original implementation (which was around 6? years ago). Paranoid users are free to increase it to 15, 16 or even higher values but I think 10 has become somewhat dated.

**Comment by reedloden** [comment]
See also #3549 regarding increasing `config.stretches`.

**Comment by erdostom** [comment]
How about using Argon2?
https://github.com/P-H-C/phc-winner-argon2
https://hynek.me/articles/storing-passwords/

**Comment by chrishaum** [comment]
:+1: on Argon2. https://password-hashing.net/

**Comment by erdostom** [comment]
I took a stab at creating an encryptor to use with [devise-encryptable](https://github.com/plataformatec/devise-encryptable): [devise-argon2](https://github.com/erdostom/devise-argon2).

**Comment by josevalim** [comment]
Yes, Devise supports other encryptors via extensions, that's the way to go. Thank you for the new ones!

**Comment by steakknife** [comment]
Anyone else reading this from the future: In 10+ years, I've never seen devise-encryptable work. devise-scrypt and devise-argon2 are low effort/abandoned and inadequately tested so they're useless. Monkeypatching / refinements on `Devise::Encryptor` is the only reliable method. Save yourself time by no relying on poorly-maintained layers of unreliable abstractions.
