### ISSUE TITLE
Send instructions with my mail wrapper

### ISSUE THREAD

**Issue by seemsindie** [plataformatec/devise#3780]
I have madmimi wrapper that somebody wrote as a helper, andi i have to use it not matter what. So i was wondering how would i go about sending forgot password mail with reset link with my own wrapper.

My method works like this:

    MyApp::MadMimi.send! :forgot_password, @user, @link

How i can somehow override send_reset_password_instructions, generate a link and send it like this?

Thanks guys.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by seemsindie** [comment]
Ok, if anybody can help refer to http://stackoverflow.com/questions/33126052/devise-send-instructions-with-my-mail-wrapper
