### ISSUE TITLE
Send password verification email not sending

### ISSUE THREAD

**Issue by jsanders67** [plataformatec/devise#3782]
I currently have a set up (via devise and active admin) where Admin_users can create users, but users cannot sign up on their own. Through active admin the admin_user creates the user, and then the user should receive an email to change their password, thus completing their account. The only user attribute that the admin fills out is the email. My code is as follows

user.rb
```
  after_create { |user| user.send_reset_password_instructions }
 
  def password_required?
    new_record? ? false : super
  end
```

I receive the email to reset my password and I am redirected correctly, but when I try to enter my new password and password confirmation I get an invalid reset password token error even tho I have a reset_password_token in my url.
After looking at the model for the newly created user I see there is in fact no reset_password_token on the user. 
When I do this manually by logging in and clicking "forgot my passwod" everything works completely fine and I get the correct password token

I think this is a devise issue but im not 100% on that. Anyone had this same issue or know why this may be occurring?

**Comment by josevalim** [comment]
Can you please paste your email template?

On Thursday, October 15, 2015, jsanders67 <notifications@github.com> wrote:

> I currently have a set up (via devise and active admin) where Admin_users
> can create users, but users cannot sign up on their own. Through active
> admin the admin_user creates the user, and then the user should receive an
> email to change their password, thus completing their account. The only
> user attribute that the admin fills out is the email. My code is as follows
>
> user.rb
>
>   after_create { |user| user.send_reset_password_instructions }
>
>   def password_required?
>     new_record? ? false : super
>   end
>
> I receive the email to reset my password and I am redirected correctly,
> but when I try to enter my new password and password confirmation I get an
> invalid reset password token error even tho I have a reset_password_token
> in my url.
> After looking at the model for the newly created user I see there is in
> fact no reset_password_token on the user.
> When I do this manually by logging in and clicking "forgot my passwod"
> everything works completely fine and I get the correct password token
>
> I think this is a devise issue but im not 100% on that. Anyone had this
> same issue or know why this may be occurring?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/devise/issues/3782>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jsanders67** [comment]
```
<p>Hello <%= @resource.email %>!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

```

That is the code straight from devise for the reset_password_instructions.html.erb
Note: it is using @token. I noticed an issue in the past where people had a problem but they were using @resource.reset_password_token.

my url sent to the email: http://localhost:3000/users/password/edit?reset_password_token=dBv9hzwZ2QzQ3LqPTrV6

**Comment by jsanders67** [comment]
@josevalim  any idea?

**Comment by chrismacias** [comment]
this is similar to issue #3787 where the program detected an email change from an empty string to another value before the final commit. The "email_changed?" was used to discriminate whether or not to reset the token, which was true within the commit

**Comment by lucasmazza** [comment]
@jsanders67 @chrismacias does #3774 fixes this? You can try with Devise master and if it's enough I'll cut a new release.

**Comment by lucasmazza** [comment]
Closing due inactivity.
