### ISSUE TITLE
validates password presence on create not working

### ISSUE THREAD

**Issue by dimidev** [plataformatec/devise#3784]
i try to save user on update but cant because i get message that password cant be blank (on update action) i think this error raise because of devise... i dont know..

```ruby
validates_presence_of :password, on: :create
```

i try to use one more validation
```ruby
validates_presence_of :password, on: :update, allow_blank: true
```
but neither this solution works

please help!!!

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
