### ISSUE TITLE
production devise sign_in if not valid shows error but when valid goes to 500 error still on /users/sign_in page. 

### ISSUE THREAD

**Issue by sulmanhotmail** [plataformatec/devise#3785]
I am using devise for email login and also omniauth for social logins. Working perfectly in development. In production does not register new user gives 500 error on sign_up page. I put a user through console and same happens when try to log_in. I am using toasts so if wrong user entered then error shown on toast if right user then 500 error on /users/sign_in page and asks for refresh and comes back to login page.
I tried the google auth then it says no client_id and same is the case with facebook.
I am a newbie. Please help.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
