### ISSUE TITLE
Automatically pluralize scoped views generator

### ISSUE THREAD

**Issue by excid3** [plataformatec/devise#3790]
I ran into the same gotcha that these guys hit in #2536 where the generator accepts singular names and doesn't pluralize. Since the gem's configured to always look for the pluralized name, does it make sense to fix this generator to auto-pluralize the scoped views folders?

Happy to make a PR for this, just wanted to check and make sure that it wasn't intentional to not auto-pluralize.

**Comment by josevalim** [comment]
Pluralizing in the views generator? That sounds great, thank you!
