### ISSUE TITLE
Default Devise confirmable: Confirmation token is invalid

### ISSUE THREAD

**Issue by TrevorHinesley** [plataformatec/devise#3791]
I've read all of the other issues related to this, and I'm not sure if this is my fault or not, but I have another app set up almost identically that works fine. The only difference is it's a few Devise versions behind the one I'm having problems with (the properly working one is using Devise 3.4.1 as opposed to 3.5.2).

I have the `confirmable` module set up on my `User` model, with reconfirmable set to false. Email was made optional with the following changes to the model (outlined by your wiki, and this same setup works fine in my other app):

```ruby
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # DEVISE SPECIFIC FUNCTIONS
  # ==========================================
  # Everything below here is used for allowing
  # account creation without a password, and
  # for password to be added upon confirmation
  # ==========================================

  # New function to set the password without knowing the current password used in our confirmation controller. 
  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end

  # New function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # New function to provide access to protected method pending_any_confirmation
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end

  def password_required?
    # Password is required if it is being set, but not for new records
    if !persisted? 
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end
end
```

If I run `User.create(email: "blah@blah.com")` it will send the confirmation email, but the token in the email is the same value as the `confirmation_token` field on the aforementioned user, not a digested version. My devise mailer for `confirmation_instructions` is the default as well:

```erb
<p>Welcome <%= @email %>!</p>

<p>You can confirm your account email through the link below:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

```

**Comment by dinomite** [comment]
I've had this issue, too—the confirmation token stored in the DB with 3.4.1 was hashed, but the raw token is sent to the client.  Devise 3.5.2 stores the raw token in the DB (quoth the changelog, "Do not use digests for password confirmation token"), thus requiring a custom ConfirmationsController to be updated to respect this change.

For others who stumble across this, the changing commit is eb640ed which was in PR #3661
