### ISSUE TITLE
reset_password_keys as a hash

### ISSUE THREAD

**Issue by RutSzymon** [plataformatec/devise#3794]
Hi,
I noticed a problem with setting **reset_password_keys** option as a hash like this: `{ email: true, subdomain: false }`. I solved it for myself, but you may want to know that such a problem exists :)

Error:
```
NoMethodError - undefined method `[:email, true]=' for #<User:0x00000006f8a470>:
  activemodel (4.2.2) lib/active_model/attribute_methods.rb:433:in `method_missing'
  devise (3.5.2) lib/devise/models/authenticatable.rb:268:in `block in find_or_initialize_with_errors'
  devise (3.5.2) lib/devise/models/authenticatable.rb:266:in `find_or_initialize_with_errors'
  devise (3.5.2) lib/devise/models/recoverable.rb:127:in `send_reset_password_instructions'
  devise (3.5.2) app/controllers/devise/passwords_controller.rb:13:in `create'

```

My solution:
I just override `send_reset_password_instructions` class method:
```ruby
def self.send_reset_password_instructions(attributes = {})
  recoverable = find_for_authentication(attributes) || initialize_with_errors(attributes)
  recoverable.send_reset_password_instructions if recoverable.persisted?
  recoverable
end
```
where `find_for_authentication` is overwritten too, following this guide: https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain#override-devise-auth-finder-hook and `initialize_with_errors` is my own logic.

It seems to be ok, but I think it should work like **authentication_keys** option.

Rails: 4.2.2, Devise: 3.5.2, Warden: 1.2.3

Thanks :)

**Comment by josevalim** [comment]
Thank you! Given we were considerating deprecating the hash from authentication_keys, we should likely leave things as is. :)
