### ISSUE TITLE
User does not respond to 'devise' method. 

### ISSUE THREAD

**Issue by alcedo** [plataformatec/devise#3798]
i keep getting the below error randomly whenever im making code changes. 

```
User does not respond to 'devise' method. 
This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb'
```

Restarting rails server is the only possible fix for this, but it spuriously comes back every now and then whenever im making code changes. 

Hope someone here can help :)

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
