### ISSUE TITLE
uninitialized constant Devise::Encryptor in overriden RegistrationsController

### ISSUE THREAD

**Issue by rocketblr** [plataformatec/devise#3799]
Hi there,

It looks like I'm facing a really weird issue and it would be great if someone could help.
I have created a custom RegistrationsController which is inherited from the original devise controller. It contains only 2 methods: create and configure_sign_up_params. Also there is the following line which seems to cause the error:
protect_from_forgery with: :null_session
This is done in order to allow json API calls.

So steps to reproduce the issue:
1. Restart the server
2. Make a post request to registrations#create
3. Everything works as expected
4. Change any file in the project
5. Make a post request to registrations#create
6. uninitialized constant Devise::Encryptor

If I restart the server everything will work again until I change something.

Probably the issue has nothing connected with devise itself, but any help would be appreciated.

P. S. Using WEBrick 1.3.1, ruby 2.2.1 and rails 4.2.1

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rocketblr** [comment]
I hope this would be a devise issue.

**Comment by josevalim** [comment]
@rocketblr could you then please provide a sample application that reproduces the issue? From your description, it looks like the issue elsewhere:

> Probably the issue has nothing connected with devise itself, but any help would be appreciated.

But if you have a way to reproduce it, we can take a look!
