### ISSUE TITLE
Check for active_record / ORM support during devise:install

### ISSUE THREAD

**Issue by streetlogics** [plataformatec/devise#3800]
I have a rails app where I wasn't using active_record to start.  I installed devise, ran `rails g devise:install` and then `rails g devise:views`.  However, after running the command, I got an error saying "'require': cannot load such file -- devise/orm/false".  I found this issue - https://github.com/plataformatec/devise/issues/2764, which got me started in the right direction.  I got all my requires squared away, but was still getting the error.  I ended up finding the line in the autogenerated `config/intializers/devise.rb` had been set to `require 'devise/orm/false'`, which needed to be `require 'devise/orm/active_record'`.  

I know this was ultimately sort of my fault for not having active_record required up front, however, with that said, your package also obviously has a "false" value that it's working with to generate that file, so a check should be added to the generate method to make sure active_record or another ORM is loaded, and if not, throw an error during the install script, as otherwise, a developer might (and rightly assume) that a successful install script == a successful install.  :)  Thanks!

**Comment by georgeguimaraes** [comment]
if you remove the line `require 'devise/orm/false' The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by georgeguimaraes** [comment]
If you remove the line `require 'devise/orm/false'`, does the generator `rails g devise:views` run successfully?

**Comment by georgeguimaraes** [comment]
(sorry for the mistake on the first reply. I already deleted it)

**Comment by streetlogics** [comment]
This is what the progression looks like if I comment out that line:

```
$ rails g devise:views
      invoke  Devise::Generators::SharedViewsGenerator
      create    app/views/devise/shared
      create    app/views/devise/shared/_links.html.erb
      invoke  form_for
      create    app/views/devise/confirmations
      create    app/views/devise/confirmations/new.html.erb
      create    app/views/devise/passwords
      create    app/views/devise/passwords/edit.html.erb
      create    app/views/devise/passwords/new.html.erb
      create    app/views/devise/registrations
      create    app/views/devise/registrations/edit.html.erb
      create    app/views/devise/registrations/new.html.erb
      create    app/views/devise/sessions
      create    app/views/devise/sessions/new.html.erb
      create    app/views/devise/unlocks
      create    app/views/devise/unlocks/new.html.erb
      invoke  erb
      create    app/views/devise/mailer
      create    app/views/devise/mailer/confirmation_instructions.html.erb
      create    app/views/devise/mailer/reset_password_instructions.html.erb
      create    app/views/devise/mailer/unlock_instructions.html.erb

$ rails g devise Admin
      invoke  active_record
      create    db/migrate/20151027182510_devise_create_admins.rb
      create    app/models/admin.rb
      invoke    test_unit
      create      test/models/admin_test.rb
      create      test/fixtures/admins.yml
      insert    app/models/admin.rb
       route  devise_for :admins

$ rake db:migrate
rake aborted!
NoMethodError: undefined method `devise' for Admin (call 'Admin.connection' to establish a connection):Class
/sites/mysite/app/models/admin.rb:4:in `<class:Admin>'
/sites/mysite/app/models/admin.rb:1:in `<top (required)>'
/sites/mysite/config/routes.rb:2:in `block in <top (required)>'
/sites/mysite/config/routes.rb:1:in `<top (required)>'
/sites/mysite/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

When I uncomment the line and replace "false" with "active_record" (and have active_record properly required) the migration runs successfully:
```
$ rake db:migrate
== 20151027182510 DeviseCreateAdmins: migrating ===============================
-- create_table(:admins)
   -> 0.0078s
-- add_index(:admins, :email, {:unique=>true})
   -> 0.0018s
-- add_index(:admins, :reset_password_token, {:unique=>true})
   -> 0.0008s
== 20151027182510 DeviseCreateAdmins: migrated (0.0105s) ======================

```

**Comment by rubyrider** [comment]
What should the expected behaviour in case you require require 'devise/orm/false' ?

**Comment by lucasmazza** [comment]
I think that is better to raise somewhere in the `InstallGenerator` when the app doesn't have an ORM generator configured (https://github.com/plataformatec/devise/blob/master/lib/generators/templates/devise.rb#L24-L28), so we don't generate an initializer in a bad state like this.

**Comment by rubyrider** [comment]
(+1) Thanks, let me propose a pr to get feedback for this issue.

**Comment by lucasmazza** [comment]
@rubyrider do you still plan to work on this one? :)

**Comment by alexmalik** [comment]
@lucasmazza I'm going to to take a look at this and submit a PR for this issue seeing as how progress on this issue has slowed.

**Comment by rubyrider** [comment]
@lucasmazza sorry for being late. yes I am planning to work on this in this weekend.

**Comment by rubyrider** [comment]
ah, @alexmalik I think you would be faster, I am extremely busy but I was originally planning to work on this from this weekend.

**Comment by alexmalik** [comment]
@rubyrider Ok then I will start working on this issue.
