### ISSUE TITLE
Mountable engine routes

### ISSUE THREAD

**Issue by Adrxx** [plataformatec/devise#3801]
Im trying to create a a mountable engine with devise on it, I've followed this tutorial: https://github.com/plataformatec/devise/wiki/How-To:-Use-devise-inside-a-mountable-engine
And everything works fine, except the routes. My engine is mounted in the route admin like this:

     mount C4::Engine => "/admin"

but when devise redirects the user (like when it hasn't signed in) it redirects to a path without the '/admin' prefix and gives me the usual No route matches [GET] /users/sign_in because the correct route is admin/users/sign_in.

I'm kind of new to rails mountable engines so It could be just me, is this a devise issue?

**Comment by Adrxx** [comment]
Ok, It seems I wasn't using the correct devise version, devise 3.5.1 works fine.

**Comment by patricklindsay** [comment]
I think this should be reopened (?)

I am having the same problem using `3.5.6`, downgrading to `3.5.1` fixes the problem however opens my app up to [security issues](http://blog.plataformatec.com.br/2016/01/improve-remember-me-cookie-expiration-in-devise/)

**Comment by patricklindsay** [comment]
Reverting [this commit](https://github.com/plataformatec/devise/commit/aa675f7f6611de5d40114aa98153f3f0c0b3e8d5) solves the issue.
