### ISSUE TITLE
Passing block to super when calling Devise::RegistrationsController::update can give valid resource but not save

### ISSUE THREAD

**Issue by whomwah** [plataformatec/devise#3802]
Before I take this any further I wanted to make sure I wasn't missing anything. In this example code:

```
class RegistrationsController < Devise::RegistrationsController
  def update
    super do |resource|
      # doing something after updating
    end
  end
end
```

I am using the ability to pass a block in as provided [here](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L49). I found that ```resource``` could actually be valid in terms of the resource, but invalid in terms of the request completing because you are required to re-enter your password in order to complete the update. The check for this is actually done in line above:

```
....
resource_updated = update_resource(resource, account_update_params)
yield resource if block_given?
if resource_updated
...
```

I wonder if you also need to yield ```resource_updated```, so you would end up with:

```
yield resource, resource_updated if block_given?
```

so you would have access to the resource and know whether it was updated OK.

**Comment by josevalim** [comment]
You can always check `resource.errors.empty?`. I am already not a fan of the super with block syntax, so I am not really inclined to add even more params. :)

**Comment by whomwah** [comment]
@josevalim you're right ```resource.errors``` was what I needed, thanks.

**Comment by phylor** [comment]
For the search engine users: it is important not to call `resource.valid?`, because that potentially clears the errors devise has set previously. As @josevalim mentions, use `resource.errors.empty?` or `resource.errors.present?` instead.
