### ISSUE TITLE
Rake db:migrate fails after rails generate devise User

### ISSUE THREAD

**Issue by boyfunky** [plataformatec/devise#3804]
So i am following the process based on Devise read.me Getting Started. This is the process i did 
 - Created  my rails project
- Added gem 'devise' 
 - rake db:create
 - rails generate devise:install
 - Added home#index to routes
 - added action_mailer_deafult_url_options to development.rb 
 - rails generate devise User
 - rake db:migrate 
when i run rake db:migrate, it fails and gives me this error report 

rake aborted!
StandardError: An error has occurred, all later migrations canceled:

super: no superclass method `sanitize_for_mass_assignment' for #<ActiveRecord::SchemaMigration version: nil>
NoMethodError: super: no superclass method `sanitize_for_mass_assignment' for #<ActiveRecord::SchemaMigration version: nil>

Does anyone know any reason why this is happening

I am using rails - 4.2.3 and Devise 3.5.2

**Comment by rubyrider** [comment]
Did you install them  gem 'strong_parameters' ?

**Comment by georgeguimaraes** [comment]
Can you please provide a sample application that reproduces the error?
