### ISSUE TITLE
Account update successful but password is not updated

### ISSUE THREAD

**Issue by sulmanhotmail** [plataformatec/devise#3809]
I am using this guide https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-password and amniauth too... I change the password, The method commit in console but new password is not updated in db. Even the notification is account saved successfully

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
