### ISSUE TITLE
Different authentication keys in different devise models

### ISSUE THREAD

**Issue by Haseeb717** [plataformatec/devise#3811]
I am using devise for two models. I want to make authentication key of one is phone and other is email. How to manage it?

**Comment by josevalim** [comment]
You can set those as options when you call devise in the model. Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Haseeb717** [comment]
How to call it?
