### ISSUE TITLE
How to bypass confirmable for specific pages in my controller?

### ISSUE THREAD

**Issue by tarr11** [plataformatec/devise#3812]
I am using `:confirmable` and would like to ignore it for specific pages.  I know that I can override methods on my model, but this is not sufficient for my case as it is dependent on data that is only accessible to the controller (such as page or subdomain)

Here's an example of how I would want it to work:
```
class MyController
  skip_confirmable :show

  def show
    
  end
end
```

Does this exist?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
