### ISSUE TITLE
Question: generate url with token for login without password (for email campaigns)

### ISSUE THREAD

**Issue by feliperaul** [plataformatec/devise#3814]
Hi there guys,

I looked around and couldn't find an easy answer for this.

I want to generate a url to use in email campaigns that users can click and get logged in automatically, without having to provide neither email nor password.

Something in the lines of ```http://myapp.com/users/sign_in?token=```

The idea is not new: if users can reset their passwords by clicking a link in an e-mail address we send them, this means we could also allow for single click sign-on process.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
