### ISSUE TITLE
Custom Mailer View Not Being Used

### ISSUE THREAD

**Issue by ssalzberg** [plataformatec/devise#3815]
Hi, I created a Devise model, generated all the views, and updated my routes like so:

  devise_for :users, controllers: { registrations: "users/registrations",
                                        sessions: "users/sessions",
                                        passwords: "users/passwords",
                                        confirmations: "users/confirmations"}

All the custom views in app/views/users/registrations, app/views/users/sessions, etc work properly (i.e. when I update the view, the change is displayed in my browser), however the mailer templates in app/views/users/mailer are not being picked up (i.e. changes I make to them are not being used). I believe Devise is still using the mailer templates embedded in the gem. Searched Google a bunch and tried suggested fixes, but none work, so I believe this may be a bug with Devise.

Ruby 2.2.2
Rails 4.2.4
Devise 3.5.2
Warden 1.2.3

**Comment by josevalim** [comment]
To use the e-mail ones you need to use devise/mailer or set something like config.scoped_views. Please check your config file!
