### ISSUE TITLE
Custom routes and after_inactive_sign_up_path_for redirect not working

### ISSUE THREAD

**Issue by onslauth** [plataformatec/devise#3816]
Hi,

I have created the following routes
```
  # Devise routes
  devise_for :users, controllers: { registrations: "registrations" }, skip: [:session, :registrations]
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session

    get "/join" => "devise/registrations#new", :as => :new_user_registration
    post "/join" => "devise/registrations#create", :as => :user_registration
    get "/profile" => "devise/registrations#edit", :as => :edit_user_registration
    put "/profile/:id" => "devise/registrations#update", :as => :update_user_registration
  end
```

I am now trying to redirect the to the sign in page after sign up. I have created a custom registrations_controller.rb and overridden the necessary function
```
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    "/login"
  end

  def after_inactive_sign_up_path_for(resource)
    "/login"
  end
end
```

However, the overridden functions are not called. If I change "config/routes.rb" to the following:
```
  # Devise routes
  devise_for :users, controllers: { registrations: "registrations" }
```

Everything then works as expected.

**Comment by josevalim** [comment]
Yes, those are exactly the steps.

**Comment by josevalim** [comment]
:)

**Comment by onslauth** [comment]
Hi,

The problem still exists, following the above steps, the combination of custom url's and trying to redirect to a chosen page after sign_up does not work. 

As explained above, when trying to use custom urls and custom registration controller, the overridden functions in the custom registration controller are not called. Am I doing it correctly, or is the combination of the two not supported?
