### ISSUE TITLE
Devise rendering wrong views

### ISSUE THREAD

**Issue by txssseal** [plataformatec/devise#3819]
I have done a basic install of devise, and devise views for users.  Ive noticed Devise is not rendering views in my app/views path, instead it is rendering the default views within the gem.  Is this normal behavior?

routes:
devise_for :users

path it rendering views from:

/Users/c/.rvm/gems/ruby-2.2.1/gems/devise-3.5.2/app/views/devise/shared/_links.html.erb

**Comment by shakycode** [comment]
@txssseal Did you run `rails generate devise:views` ?

**Comment by txssseal** [comment]
Whats up @shakycode.  Ya ive already done that, thats why this is weird.

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by txssseal** [comment]
you have to set scoped views to true in devise config
