### ISSUE TITLE
Vanity urls and custom registration controller

### ISSUE THREAD

**Issue by onslauth** [plataformatec/devise#3821]
Hi,

In my previous issue that I opened ( #3816 ), I asked whether what I was doing was correct, and the code and configuration is all 100%? 

If it is correct, then I believe there is a bug as the functions defined in the custom registrations controller are not being called, and therefore the user is not being redirected to the sign in page after registering a new user.

If it is not correct, can you please then indicate what the correct method would be to use both custom url's and a custom registration controller, as I have created the code using the examples from the devise wiki.

**Comment by josevalim** [comment]
If you are using custom routes, they should point to your controller, not devise's. So this:

    get "/join" => "devise/registrations#new", :as => :new_user_registration

Should be this:

    get "/join" => "registrations#new", :as => :new_user_registration

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
