### ISSUE TITLE
Redirect user after signup with confirmation turned on

### ISSUE THREAD

**Issue by SylarRuby** [plataformatec/devise#3822]
I have followed this post to enable :confirmable to Users. But how to redirect to "x" with a notice that the user needs to confirm their email?

Link: https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
