### ISSUE TITLE
Call user_session inside of Rails (MiniTest) TestCases

### ISSUE THREAD

**Issue by AnomalousBit** [plataformatec/devise#3823]
Hello,

I am currently calling `user_session` in several of my Rails controllers and not only would like to assert that functionality inside of my test cases, I cannot get my test cases to pass (as planned) without adding data to `user_session`.

At present, `user_session` is not available from `ActionController::TestCase` even when adding the Devise TestHelpers using `include Devise::TestHelpers`. Maybe the example below will make more sense.

**rails_app/test/controllers/demo_controller_test.rb**
```
class DemoControllerTest < ActionController::TestCase
    include Devise::TestHelpers

    test "will fail because user_session raises NoMethodError" do
        # sign_in is only available because of Devise::TestHelpers, why not user_session?
        sign_in User.first

         # without my branch, this call to user_session is not possible, NoMethodError is raised.
        user_session['required_property'] = true

        # index requires user_sessions['required_property'] or the action will respond with failure
        get :index
        assert_response :success
    end

end
```

**rails_app/app/controllers/demo_controller.rb**
```
class DemoController < ActionController::Base

    def index
        if user_session['required_property'].nil?
            redirect_to error_path and return
        end
    end

end
```
Is there another way to populate `user_session` from a test case without having to basically implement integration testing to flow through my usual login and session initialization process? That seems very cumbersome when I can just set the `user_session` manually to provide accurate test coverage / mocks for my controllers.

PS - I created a pull request that exposes `user_session` to ``ActionController::TestCase`` via `Devise::TestHelpers`, but it was closed last week without much of a follow up ->  https://github.com/plataformatec/devise/pull/3817  

Much appreciated!
Jason

**Comment by lucasmazza** [comment]
It's been a while since I worked with controller tests with Devise in an existing app, so I'm not sure if the following would work: you can try to do `controller.user_session` instead of `user_session` in your test case (which a I think it was @josevalim suggestion), or implement the `user_session` in your test suite in the same fashion as you did in @ #3817.

I get it that it that the patch makes sense for you use case but I'm sure if this is a recurrent pattern in existing apps that is worth to push into Devise by default.

**Comment by AnomalousBit** [comment]
Thanks so much for your quick help @lucasmazza! I've tried your suggestion of using `@controller.user_session` and it worked perfectly in my test suite. My apologies for misunderstanding @josevalim's response - I'll update my pull request with this information. You guys are great!
