### ISSUE TITLE
Authenticate fails for some users, valid_password? returns nil

### ISSUE THREAD

**Issue by BenSwennen** [plataformatec/devise#3824]
I'm using Devise 3.5.2, along with Mongoid 4.0.2 and Warden 1.2.3 on Rails 4.2.4.

When trying to sign in some users, `warden.authenticate!` fails and goes into the failure path. I tried `user.valid_password?("password")` for these users, and it return `nil` instead of `true`or `false`. 

For debugging, I overrode the valid_password? method and added it directly into the user model (without changing anything, just the variables) and then suddenly it worked.. 

```ruby
class User
  ...
  require 'bcrypt'
  def valid_password?(password)
    return false if encrypted_password.blank?
    bcrypt   = ::BCrypt::Password.new(encrypted_password)
    if self.class.pepper.present?
      password = "#{password}#{self.class.pepper}"
    end
    password = ::BCrypt::Engine.hash_secret(password, bcrypt.salt)
    Devise.secure_compare(password, encrypted_password)
  end
  ...
end
```

Any idea of what the issue could be?

**Comment by josevalim** [comment]
No idea. However, it would help a lot if you  Can you please provide a sample application that reproduces the error?

**Comment by BenSwennen** [comment]
Ok, unfortunately, I don't have time for creating a sample application for that right now, but I'll do that as soon as I have some spare time.

**Comment by georgeguimaraes** [comment]
Closing for now until more details can be provided :)

**Comment by rmatesicZavy** [comment]
A bit late but came across this problem today and found this thread https://stackoverflow.com/questions/19599201/rails-devise-valid-password-method-returns-nil

Setting invitation_token to nil allows it to start working again. We are using;
devise (4.8.1)
devise_invitable (2.0.6)
