### ISSUE TITLE
Improved inline documentation for session clearing code

### ISSUE THREAD

**Issue by hlascelles** [plataformatec/devise#3828]
We're seeing issues signing out a user using `sign_out`, and we could do with some improved Devise code comments.

The method `sign_out` goes through [this line](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/sign_in_out.rb#L61) in `sign_in_out.rb` calling `warden.raw_session.inspect`. 

Why is it doing this `inspect` call?

It seems very suspicious that a side-effect free (?) method call to `inspect` should have a concrete outcome on the sign out process. The provided comment _# Without this inspect here. The session does not clear_ is quite opaque.

(As it happens, for us, that then calls `actionpack-4.2.4/lib/action_dispatch/request/session.rb line 144` and eventually crashes with a `WeakRef::RefError: Invalid Reference - probably recycled`. We are at a loss to explain where this WeakRef is coming from. It only happens on Rails 4.2, not 3.2 that we're upgrading from, both Ruby 2.2.3. If anyone can shed light on that, that would be great).

Can we get better documentation on what that `inspect` is trying to achieve? 

Thanks!

**Comment by josevalim** [comment]
The Rails session was lazily loaded and, at some point, if the session was not correctly loaded before sign out, it would not effectively sign you out, it would just ignore the instruction to clear the session. The line above forces the Rails session to be loaded because inspect was one of the many commands that would trigger it. I think the clear_session bug was long fixed though, but I can't pinpoint the exact rails version.

**Comment by hlascelles** [comment]
In the spirit of sharing information that [others may find useful](https://xkcd.com/979/), it's worth reporting that we did track down this error. It was (almost unbelievably) [the ruby racer](https://rubygems.org/gems/therubyracer/versions/0.12.2) V8 Javascript parsing library. 

A report of the class hierarchy yielded this:

```
self.class.ancestors = [ActionDispatch::Request::Session, Object, PP::ObjectMixin, V8::Conversion::Object, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```

And sure enough the `V8::Conversion::Object` interloper was causing session objects to be unsafely garbage collected.
