### ISSUE TITLE
Repo needs new maintainers

### ISSUE THREAD

**Issue by Tectract** [plataformatec/devise#3834]
I believe this FOSS project is not in good hands. It appears very lazily coded and badly documented in sections and the maintainers appear hostile to suggestions for improvement.

**Comment by rubyrider** [comment]
If you found it badly coded why not coming up with a best solution instead? people are creating pr regularly and contributing themselves. If you found documentation problem please come up with your some contribution in documentation. At least write down what is your proposal. So many people are around to help you to come up! Devise is a very old gem and the maintainers are quite friendly to its users. So, please, lets come up with our contribution if we found anything wrong or not expected.

**Comment by erichkist** [comment]
@Tectract I believe you could open a PR with the the code and documentation improvements. Feel free to send your suggestion to help the project. :blush:

**Comment by Tectract** [comment]
I'm just trolling you at this point, but seriously. The documentation sucks and the mesage interface is bad.

**Comment by Tectract** [comment]
I don't have time to fix everyone elses software also. Write it yourself. Do better.

**Comment by acadavid** [comment]
@Tectract Please, stop your "trolling" nonsense, you are making smart and good-hearted people waste their precious time dealing with your negligence and idiocy.

**Comment by rbishop** [comment]
@Tectract take a break.

**Comment by Tectract** [comment]
When people contribute to my FOSS repos, I support the hell out of them even if they are angry. I'm delighted just for their attention. You guys are spoiled.

**Comment by gerred** [comment]
@Tectract You don't have any of your own repos that are actually being used, so this is just fantasy on your end.

**Comment by Tectract** [comment]
gerred you write crapware with garbage docs. I make your yearly salary in a week.

**Comment by PragTob** [comment]
@Tectract thanks for the troll (not), please find a warm source of empathy and kindness within yourself for your own good and the good of others. You're not doing anyone any good here.

**Comment by rebyn** [comment]
@Tectract you need a break, and a hug. And please stop dragging people down like this. It's very very not nice.

**Comment by josevalim** [comment]
Unfortunately I am out of the computer and only have access to email.
Please do not feed the troll. Instead, report him to GitHub due to his
attitude in previous and in this particular issue, where he assumes his
main purpose is harassing.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Fernan2** [comment]
Didn't know that nice feature of Github's reporting abuses! 
https://github.com/contact?report=Tectract

So nice!

**Comment by Tectract** [comment]
You guys are so petty.

**Comment by gvaughn** [comment]
reported

**Comment by GusGA** [comment]
@Tectract 
![No](http://41.media.tumblr.com/56a5dc4cf2229c3dad60a1576b41b73a/tumblr_mvm5kdx0Xq1rmlbxho1_400.jpg)

**Comment by gerred** [comment]
Reported. :boom:

**Comment by Tectract** [comment]
Gerred I have reported you.

I get it, you guys disagree with my opinion that this FOSS repo needs new maintainers, but I think this thread sort of proves my point.

**Comment by Ptico** [comment]
Free software does not mean that someone should do things you need for free. Contribute or GTFO
