### ISSUE TITLE
allow duplicate email if authentication_keys is not email

### ISSUE THREAD

**Issue by u007** [plataformatec/devise#3836]
hi,

is it possible to do modify validates uniqueness of email to also check
if authentication_keys is set to email only?

there are cases where some user may use same email, but have different login.
but this will effect reset password

thanks

**Comment by josevalim** [comment]
Just don't use the :validatable module from your app. Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
