### ISSUE TITLE
InvalidAuthenticityToken after Devise login/logout in another tab

### ISSUE THREAD

**Issue by antonkoh** [plataformatec/devise#3838]
I have some problems with the InvalidAuthenticityToken exception when changing user authentication state in different tabs.

My app is quite simple. In fact, just a basic learning app for my studies. https://github.com/antonkoh/railsrep/tree/master/lesson17/my_app

It uses Devise gem for authentication:

 <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

 <%= link_to "Sign in", new_user_session_path %>
protect_from_forgery is set to :exception as it is a browser app, nothing API related yet.

I do have <%= csrf_meta_tags %> specified in my layout.

The problem is reproduced in many different ways. Just a couple general examples:

On tab A I open a form to add/edit a post as an anonymous user.
On tab B I sign in as any user.
Back on tab A I try to add the post Result: InvalidAuthenticityToken
or

On tab A I open a list of posts as a signed-in user.
On tab B I sign out.
Back on tab A I try to destroy a post. Result: InvalidAuthenticityToken
I have introduced my own means to make sure that certain actions are available to certain signed-in users, but I don't even get to see them in action because of this exception. Is it supposed to work this way, just throwing itself at any PATCH request from an unrefreshed page after user authentication state change? Will my application become less secure if I change forgery protection mode to null_session or reset_session?

Thank you very much

**Comment by josevalim** [comment]
>  Will my application become less secure if I change forgery protection mode to null_session or reset_session?

If you do this, then when you post on as the signed out user, it will sign the other tab out. There isn't much escape from this unfortunately. You could set `config.clean_up_csrf_token_on_authentication = false` but that will make you vulnerable to some attacks. Namely, if someone can fixate a session, while they can't control your whole session, they will have the CSRF token which could allow them to perform some actions (although they would never see the result). For example, if this attack existed on Twitter, they could tweet things in your name, although they would never steal any information.

**Comment by antonkoh** [comment]
@josevalim I am more interested in the opposite situation (see the 1st case described).
Why do the patch-requests fail if I SIGN IN on the other tab (not sign out)? Is this expected behavior?

**Comment by josevalim** [comment]
Yes, it is expected behaviour, otherwise you are vulnerable to CSRF fixation attacks, which I tried to explain in my previous comment.

**Comment by antonkoh** [comment]
@josevalim Thank you.
