### ISSUE TITLE
Email only sign up issues

### ISSUE THREAD

**Issue by ThibaudDenolle** [plataformatec/devise#3839]
Hi,

I'm using devise 3.5.2 and rails 4.2.1
I followed the Email-Only-Sign-Up but there is something I don't understand in the flow of informations.

I've updated my views/devise/registrations/new.html.erb file and request only an email to open an account.

I didn't touched my confirmations_instructions.html.erb mailer but updated the routes as mentioned and overwrite the Devise ConfirmationController as well (I used the Rails 4, Devise 3 code), and the User model.

I can create an account without a password from my updated views/devise/registrations/new.html.erb, I receive my untouched confirmations_instructions mail and when I click on the link I reach /users/confirmation?confirmation_token=xxxxx and it is processed by my ConfirmationsController#show method which is still a little bit complicated for my skills level.

I would expect to arrive on the new views/devise/confirmations/show.html.erb file that I've created who would retain my token and allow my user to set their password. The submit button would confirm my user.

Instead of that, then token I sent directly, my user is confirmed and I land on my login page.

here are my routes:

user_confirmation          POST   /users/confirmation(.:format)           confirmations#create
new_user_confirmation GET    /users/confirmation/new(.:format)     confirmations#new
                                      GET    /users/confirmation(.:format)             confirmations#show
confirm                          PATCH  /confirm(.:format)                            confirmations#confirm

the custom ConfirmationController is a copy paste of the wiki page, the views are customised but should not compromised the whole process. My routes.rb file has been updated just as mentioned, like my User model where I added the password_match? and password_required? methods (there's was only my devise module declaration and few has_many has_one relationships...).

If someone can help me ^^

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
