### ISSUE TITLE
Security Vulnerability: `remember_user_token`

### ISSUE THREAD

**Issue by bonds0097** [plataformatec/devise#3840]
I would like to report a vulnerability regarding the way `remember_user_token` is generated. What would be the best way to do so, directly in this ticket?

**Comment by josevalim** [comment]
Hello @bonds0097! Could you please e-mail us at: opensource@plataformatec.com.br?

Thank you for getting in touch and asking the best way to proceed!

**Comment by reedloden** [comment]
Perhaps the one-line mention of security under https://github.com/plataformatec/devise#bug-reports could be brought out to its own section so people notice it? Even better would be to have a proper vulnerability handling policy (maybe under SECURITY.md so it's easily noticed).

**Comment by josevalim** [comment]
Will do @reedloden. Thank you folks.
