### ISSUE TITLE
Update Columns Instead of Save in Trackable

### ISSUE THREAD

**Issue by hallmatt** [plataformatec/devise#3841]
Should this be Update Columns instead of Save? Callbacks on a user model seem to fire every time a user is signed in / logged out.

https://github.com/plataformatec/devise/blob/master/lib/devise/models/trackable.rb#L33

**Comment by josevalim** [comment]
We won't change because someone may be relying on this behaviour and due to ORM compatibility. The answer though is: avoid putting logic in callbacks. :) Thank you!

**Comment by hallmatt** [comment]
Thanks for the response! I'll stay away from the to-use or not-to-use callback debate...that could take us hours :)

Since the tracking works behind-the-scenes, I'd hope that logic would be as minimal and unobtrusive as possible (utilizing an update columns approach). A save call is pretty intrusive and probably best used when a user truly triggers a save. I believe warden provides functionality for developers that might want to utilize a sign in / sign out hook. Devise is great because you guys continue to make improvements and enhancements, even if additional adjustments are necessary to the apps that utilize the gem.

Thanks for a great gem!
