### ISSUE TITLE
Downcase on localized resource name (devise_error_messages!)

### ISSUE THREAD

**Issue by mbusch** [plataformatec/devise#3843]
The [Devise helper for error messages](https://github.com/plataformatec/devise/blob/master/app/helpers/devise_helper.rb#L14) implements a localization logic that isn't applicable for all languages (e.g. German). A call of `.downcase` overwrites the spelling that has taken place and is managed within the localization files.

In my opinion it might be better to remove the `.downcase` call from that helper method. Otherwise [solutions like this](http://stackoverflow.com/a/16173331/2384950) getting promoted.

**Comment by josevalim** [comment]
You are right. Ideally, we should pass both downcased and non downcased value. On the other hand, changing the message right now would be backwards incompatible. :(

**Comment by mbusch** [comment]
Then at least we have it tracked here - maybe that's a minor change for a new major release ;-)

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you think this is still relevant, please open a pull request with the implementation mentioned above.

Thank you!
