### ISSUE TITLE
Alternate login controller

### ISSUE THREAD

**Issue by bsylvain** [plataformatec/devise#3844]
Is it possible to create a secondary session controller  to allow a App to give a different layout to user trying to authenticate?

What i want to do is to create a special Login for when the user is authenticating for Doorkeeper.

I created a special  view using this article from the Wiki :https://github.com/plataformatec/devise/wiki/How-To:-Display-a-custom-sign_in-form-anywhere-in-your-app 

But after a succesful login, the user is redirected to the app root instead of being redirected to the original client app.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
