### ISSUE TITLE
Hyphenated instead of underscored routes

### ISSUE THREAD

**Issue by bsgreenb** [plataformatec/devise#3845]
By default, Devise ships with routes that have underscores in them like `sign_in`.

It's more conventional to use a dash instead of an underscore to seperate words in URLs, so I recommend default be changed

http://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

**Comment by josevalim** [comment]
We are following rails conventions on the matter, so we don't have plans to change it on Devise. It would also be very backwards incompatible. :) thank you anyway!

**Comment by paulmwatson** [comment]
Very old I know but just wanted to say I also would prefer dashes/hyphens to underscores in user URLs e.g. `/users/sign-up` rather than `/users/sign_up`. The internal details like `users#sign_up` shouldn't be a factor for end users even if Rails does it.

For now I'm just remapping in routes.rb.
