### ISSUE TITLE
Devise isn't being able to apply for authentication of all routes from a Mountable Engine and make public only a few Engine routes

### ISSUE THREAD

**Issue by maurymmarques** [plataformatec/devise#3850]
I'm not sure but this seems a Devise issue because I have not found a solution.

If I set the following code on my `mainapp/config/routes.rb`, all routes will require authentication and I will not be able to use `before_action :authenticate_user!, except: [:mypublic_method]` in my controller.

```ruby
	Rails.application.routes.draw do
		devise_for :users
	
		authenticate :user do
			mount Myengine::Engine, at: '/myengine'
		end
	end	
```

Rails seems to need the mounted routes to be able to see the engine through URLs.

If I set the following code on my `mainapp/config/routes.rb`, all routes will be public, but I want to make pulbic only the methods that I wish.

```ruby
	Rails.application.routes.draw do
		devise_for :users
	
		mount Myengine::Engine, at: '/myengine' 
	end	
```
	
What can I do to make public/accessible `mypublic_method` (vendor/engines/myengine/app/controllers/myengine/mycontroller_controller.rb) using `authenticate :user `?
		
		
p.s. the same question in another way http://stackoverflow.com/questions/32642681/how-can-i-avoid-devise-from-requires-authentication-from-within-an-engine

- ruby 2.2.3p173
- Rails 4.2.5
- Devise 3.5.3
- Warden 1.2.4
- OrmAdapter 0.5.0

Thank you.

**Comment by josevalim** [comment]
If you apply it at the router level, you can't "cancel" it in the controller because by the time you reach the controller the router code has already ran.

**Comment by maurymmarques** [comment]
Thank you. But how can I solve that?

**Comment by josevalim** [comment]
Don't do the authentication in your router. Do in the controllers
exclusively.

On Sunday, December 13, 2015, Maury M. Marques <notifications@github.com>
wrote:

> Thank you. But how can I solve that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/devise/issues/3850#issuecomment-164247081>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by maurymmarques** [comment]
Can you illustrate it?
