### ISSUE TITLE
module included for no reason

### ISSUE THREAD

**Issue by betesh** [plataformatec/devise#3852]
Unless I'm missing something, DateHelper is not necessary here: https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L43

Since the only method that seems to use it in that module is time_ago_in_words, which is called on  `Devise::TimeInflector` and not on `self`.  Can we safely remote the ` include ActionView::Helpers::DateHelper` from devise/confirmable.rb?

**Comment by josevalim** [comment]
Agreed. Can you please send a PR?

**Comment by josevalim** [comment]
Thank you, closing in favor of the PR.
