### ISSUE TITLE
Custom remote devise authentication

### ISSUE THREAD

**Issue by clubbavi** [plataformatec/devise#3860]
I am using Rails 4.2 & Ruby 2.2 app with devise 3.5.2. We don't have any database(external through APIs). Currenty we are using custom devise Remote Authentication.

In devise.rb:
```
    config.warden do |manager|
       manager.strategies.add(:remote, Devise::Strategies::RemoteAuthenticatable)
       manager.default_strategies(:scope => :user).unshift :remote
    end
    Devise.add_module :remote_authenticatable, :controller => :sessions, :route => { :session => :routes }
```
But now due to some requirements, we have to use custom session controller & a custom method to sign up & directly login.

How to call the remote authentication from this custom method?

In remote_authentication.rb:
```
    module Devise
        module Strategies
          class RemoteAuthenticatable < Authenticatable
            def authenticate!
              auth_params = authentication
              if validate(resource){ resource.remote_authentication(auth_params) }
                success!(resource)
              end
            end
          end
        end
    end
```
Thanks.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
My suggestion would be to move the shared logic to a common place you can invoke both from the controller and the strategy. Better than coupling them.
