### ISSUE TITLE
Send e-mail notification to user on email change

### ISSUE THREAD

**Issue by jurre** [plataformatec/devise#3862]
The latest version of devise (3.5.3) adds support for [notifying users of a password change](https://github.com/plataformatec/devise/pull/3642), which is a great addition, I've been doing this manually up until now.

Another thing that I am still doing manually, and is also considered best security practice, is notifying a users old email address when an accounts email has been changed. This has been proposed before (https://github.com/plataformatec/devise/issues/3691) and was marked as out of scope for Devise. Maybe with the latest change to (optionally) send a notification on password change, you might reconsider this feature request.

I'd be happy to send a PR if this is wanted.

**Comment by tomdev** [comment]
+1 for email notification on the old email address regarding the email change. From a security standpoint this is really good to have and I'd advocate more sites to use this.

@josevalim Can you elaborate why think this is out of scope for Devise (#3691)? Or was that regarding the ability to cancel the change?

**Comment by lucianosousa** [comment]
I think it's the same issue I've here.

My problem is about confirmation email when I change it. In devise higher than 3.5.3 confirmation email is not sent anymore.

It's a devise problem between version 3.5.3 and 3.5.4.

My test suit broke after this upgrade.
You can see this here:

passing: https://travis-ci.org/call4paperz/call4paperz/builds/109015545
broken: https://travis-ci.org/call4paperz/call4paperz/builds/109017932

the testing is not passing anymore is:
https://github.com/call4paperz/call4paperz/blob/feature/security-updates/spec/controllers/profiles_controller_spec.rb#L37

**Comment by mapreal19** [comment]
+1 for this too

**Comment by lucianosousa** [comment]
@carlosantoniodasilva any update here?

**Comment by lucianosousa** [comment]
can you guys confirm if this commit: https://github.com/plataformatec/devise/commit/1d57169c7bd12977a6697a5a06cda265442bb5c8

solve this problem?

tks

**Comment by jurre** [comment]
It looks like this sends an email when updating the email address from `nil`, but it wouldn't send an email when changing it from a previous valid email address?

**Comment by marcosanfilippo** [comment]
Any update? How to send email to previous email on email change?

**Comment by carlosantoniodasilva** [comment]
@marcosanfilippo please check #4455 for the new feature/option to enable that.
