### ISSUE TITLE
Question: passwordless functionality planned or alternative?

### ISSUE THREAD

**Issue by SpacyRicochet** [plataformatec/devise#3863]
We're interested in implementing a passwordless user authentication system, just to give your users one less thing to remember. 

Does Devise have something like this functionality planned? Or if not, are there any Rails modules or tools that do have this?

**Comment by josevalim** [comment]
No, we don't  have anything planned. About options, your best option is to ask the mailing list.

**Comment by SpacyRicochet** [comment]
Thanks :)
