### ISSUE TITLE
rails5 / rspec / capybara

### ISSUE THREAD

**Issue by bbnnt** [plataformatec/devise#3870]
Updated the config as explained in the readme recently;
devise gem is on master branch.

Problems occurring when running features tests with spec and capybara, with anything involving devise (redirects to new session path for protected urls, direct access to the new session path, etc)

Not sure it is tied, but there's this first warning when tests are run :

```
DEPRECATION WARNING: [...] will be removed from Devise 4.1.
Please use the `permit` method on your sanitizer `initialize` method.
class UserParams < Devise::ParameterSanitizer
    def initialize(*)
      super
      permit(:sign_in, keys: [:key1, :key2, :key3])
    end
end
(called from deprecate_instance_method_sanitization [...] parameter_sanitizer.rb:195
```

this file exists in controllers/concerns as `user_params.rb`, apparently not loaded here. when hitting devise pages with a problem browser, logging in, etc... those warnings aren't appearing in the console.

when a specific scenario is run, having devise urls, it keeps returning an error.
for example, `visit "/users/sign_in"` returns `wrong number of arguments (0 for 1..2)`

first two errors lines :
`# /xxx/ruby-2.2.2/bundler/gems/devise-643144584684/lib/devise/test_helpers.rb:48:in sign_in'`
`# /xxx/gems/ruby-2.2.2/bundler/gems/devise-643144584684/lib/devise/parameter_sanitizer.rb:74:in sanitize'`

Hope this issue fits here, could get relevant clarifications

**Comment by lucasmazza** [comment]
@bbnnt can you please post your custom sanitizer implementation (or whatever is in on `concerns/user_params.rb` as you mentioned)? A full stacktrace could also help.

Thanks!

**Comment by bbnnt** [comment]
Thanks !
So... well; while getting back at it, I gave it a try and removed `include Devise::TestHelpers` from the concerned spec file. Turns out the problems disappeared.

```
require'rails_helper'
#include Devise::TestHelpers
feature 'Admin sites' do
  before :each do
    user           = create(:user)
    visit           "/users/sign_in"
    fill_in         'Email',    with: user.email
    fill_in         'Password', with: user.password
    click_button    'Log in'
  end
  scenario "User is redirected to sites#new and creates one after first login" do
    visit root_path(locale: I18n.locale)
    expect(page).to have_content 'test'
  end
end
```

Sorry  for asking if that was obvious; I just based my question on a config that was working on 4.2.4.
Can't tell why this was not required anymore and was causing this problem

Here (https://gist.github.com/bbnnt/d687b12588c1a284b491) was the full trace when include `Devise::TestHelpers` was present

Best

**Comment by lucasmazza** [comment]
@bbnnt the issue seems to be that you are including the test helpers in a global scope, and it affects the methods from other classes outside of your test cases - include it inside your `feature` block (which is the top level class) and it should work as expected.
