### ISSUE TITLE
remember_token not in migration file

### ISSUE THREAD

**Issue by karlingen** [plataformatec/devise#3872]
Shouldn't the `remember_token` column be present in the generated migration file when running `rails generate devise User` ?

**Comment by kiddrew** [comment]
Why was this closed?

**Comment by karlingen** [comment]
Because I noticed that devise changed their way of handeling these tokens.
:)
If you dig in the code you'll notice that the token is being generated from
values already present in the users table.

**Comment by kiddrew** [comment]
Ah, I see.  The documentation on this could be better.  I upgraded my Devise version and all of a sudden had the `authenticable_salt returned nil for the #{self.class.name} model.` error.
