### ISSUE TITLE
WIKI ISSUE: Check if the user is logged-in in a request spec

### ISSUE THREAD

**Issue by ProGM** [plataformatec/devise#3876]
I was trying to check if the user is logged in a request spec.

https://github.com/plataformatec/devise/wiki/How-To:-sign-in-user-in-Request-type-specs-(specs-tagged-with-type:-:request)

In the notes is stated that:

> I have still not figured out how to assert Warden has successfully logged in the user like we can do in a Devise controller spec by asserting expect(subject.current_user).to_not be_nil. If anybody knows a way to do it please share.

So I tried to find a solution. Here's what I obtained:

```ruby
...
sign_in(user)
expect(request.env['action_controller.instance'].current_user).to_not be_nil
...
```

Please check if this works for you and please update the wiki!

**Comment by nashby** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
