### ISSUE TITLE
Readme.md unclear on the consequences of including Devise TestHelpers outside of controller tests

### ISSUE THREAD

**Issue by dcmorse** [plataformatec/devise#3881]
I have found two reasons why people include Devise TestHelpers. One is that they want to to use sign_in and sign_out methods. The second is that people want to get rid of "undefined method `authenticate?' for nil:NilClass" errors, as documented [on StackOverflow] (http://stackoverflow.com/questions/4308094/all-ruby-tests-raising-undefined-method-authenticate-for-nilnilclass).

I am having such errors while testing my views. I followed the doc in the [Devise Readme.md] (https://github.com/plataformatec/devise/blob/master/README.md#test-helpers), namely adding

    RSpec.configure do |config|
      config.include Devise::TestHelpers, type: :controller
    end

This does not fix my error, and why would it? It's not a controller test. 
By shortening the configuration to 

    RSpec.configure do |config|
      config.include Devise::TestHelpers
    end

it does fix my error, but the README.md hints darkly:

> There are two things that are important to keep in mind:
> 
> These helpers are not going to work for integration tests driven by Capybara or Webrat. They are meant to be used with functional tests only. Instead, fill in the form or explicitly set the user in session;

Does this mean "don't use Devise::TestHelpers unless you're only testing controllers", or does it mean "don't use *sign_in* and *sign_out* unless you're testing your controller". If it's the first, then my problem is solved. If it's the second, then I still have a problem. I think Readme.md could be clearer on this point.

**Comment by josevalim** [comment]
It will be fine for controllers and views tests, it won't  be fine for integration tests.

**Comment by dcmorse** [comment]
So...I can include TestHelpers, just so long as I don't call into the module, with e.g. *sign_in*.

**Comment by josevalim** [comment]
You may be able to include it, but you definitely should not. There is no guarantee including it only won't introduce errors in future versions.
