### ISSUE TITLE
Current_user Value Is nil

### ISSUE THREAD

**Issue by Gauravdhandre** [plataformatec/devise#3884]
Entering the username and password give the current_user value nil

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Gauravdhandre** [comment]
I am just freasher and having 2 month of experience in ROR so cant actually understand what you trying to say.
this is my code
![user](https://cloud.githubusercontent.com/assets/16300277/12079767/6b6c8c64-b26b-11e5-96e5-41ae7a4f1ce7.png)
![user1](https://cloud.githubusercontent.com/assets/16300277/12079768/6b6fac64-b26b-11e5-8a34-23f3499764bd.png)
![reply](https://cloud.githubusercontent.com/assets/16300277/12079773/8f1ae908-b26b-11e5-99e9-950965f1c159.png)
