### ISSUE TITLE
Issues with Devise and subdomain session sharing.

### ISSUE THREAD

**Issue by jasonsilberman** [plataformatec/devise#3886]
I have an app with multiple sudomains and I would like a user's state (logged in/out) to be shared across those subdomains.

I have set my session store up like this:
```
config.session_store :cookie_store, :key => '_app_name_session', :domain => '.name.app', :tld_length => 2
```

However this does not seem to be doing anything as when I inspect the session in Chrome, it is called the `_app_session`.

How can I setup Devise to work using sessions that will work with all of the different sub domains?

Thanks

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
