### ISSUE TITLE
uninitialized constant Session

### ISSUE THREAD

**Issue by Gauravdhandre** [plataformatec/devise#3888]
I created a sample application.
Added devise in it, it works fine.
Then added cancan gem into it.
Created an ability class. define some permissions.
Then added line
load_and_authorize_resource

to the Application Controller, after that when i go to the page
http://localhost:3000/users/sign_in  it gave the following error,

NameError in Devise/sessionsController#new
uninitialized constant Session

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Gauravdhandre** [comment]
I am new in ROR , i just have 2 month of experience so i dont understand what exactly you saying to me,
but i can show you my code. is it ok for you.

**Comment by aisen0921** [comment]
@Gauravdhandre 
I meet the same problem now, do you solved the problem?

**Comment by Guistoff081** [comment]
heyy, how do you solved the problem???
