### ISSUE TITLE
Make confirmation_period_expired? a public method

### ISSUE THREAD

**Issue by monfresh** [plataformatec/devise#3889]
Hi. Would you be open to a PR that made `confirmation_period_expired?` a public method? Here is a scenario where it might be useful to make it public:

In our app, we allow users to register in multiple steps. In the first step, they just enter an email address. Then, they need to click on the confirmation link in the email that they receive. Once they click the link, they are prompted to enter their password and password confirmation.

In order to provide a helpful user experience, we check whether the token is expired at the moment they click the confirmation link, so that they don't waste time trying to enter a password and password confirmation, only to find out afterwards that their token was expired.

In order to do that, we need to check whether the confirmation period has expired, and so we are duplicating the method in our User model. It would be great if we could just use the Devise method without having to define it again in our model.

Thoughts?

**Comment by josevalim** [comment]
confirmation_period_expired? is going to be changed soon to a way it would be completely irrelevant to what you are proposing. That's because confirmation_period_expired? should apply to a particular email/token and not to the current model as a whole. :)

**Comment by elliotlarson** [comment]
Just tried to reach for this method and realized it was protected.  It would be great if this were public.  I'd like to display a message to the user if they haven't confirmed an email update and the expiration period for confirming hasn't expired.

**Comment by dleve123** [comment]
+1 to exposing this method as public API.

My use-case is slightly different than the one @monfresh detailed above:

We are gradually introducing email confirmation to our application. One of our desired features is to display a UI inviting users to confirm their email, if they:

- haven't already started the process, and
-  if it's possible for them to complete that process (aka their current token is valid), and
-  if they aren't already email-confirmed.

Effectively, it would be valuable to ask "does this user have an active confirmation email/invitation?"

I _believe_ this would be sufficiently expressed by some public method which builds off `confirmation_period_expired?`. Maybe something like:

```ruby
def active_confirmation_attempt?
  !confirmed? && !confirmation_period_expired?
end
```

Is there an existing API that accomplishes a similar goal here? Would Devise be interested in exposing either/both of `confirmation_period_expired?` and `active_confirmation_attempt?` (naming clearly pending).

cc @josevalim

**Comment by carlosantoniodasilva** [comment]
Say you sent them the confirmation email, they haven't confirmed, and the time has passed, wouldn't you want to say they still need to confirm? Does the UI need to be different there? I don't know the underlying needs, but I'd try to keep that as generic as possible.

If it's a non-negotiable requirement, and you must call that publicly, just make it public in your own model then, e.g.:

```
class User
  devise ...
  public :confirmation_period_expired?
end
```

There's no need to make it public by default in devise. Thanks.

**Comment by elliotlarson** [comment]
Hm.  I think the point of making it public is that we can rely on the API not changing, right?  The fact that it's protected means it's not intended to be used outside of Devise, which makes me hesitant.

**Comment by dleve123** [comment]
@carlosantoniodasilva Just to close the loop here: The solution that I ended up implementing involved adding a new method to our `User` model which called `confirmation_period_expired?` (very similar to your recommendation above), so the fact that `confirmation_period_expired?` isn't public API didn't end up leading to less idiomatic/desirable code.

With that said, I do think this internal feature of Devise is incredibly useful, so I still advocate for promoting this method to public API to further show off all that Devise has to offer :) 

Thanks for all the work y'all put into Devise!
