### ISSUE TITLE
How to browse the Wiki only for articles, relevant to the latest version of Devise

### ISSUE THREAD

**Issue by AlexVPopov** [plataformatec/devise#3890]
I know this is probably a GitHub issue and not a Devise issue, but there are a ton of Wiki pages, which are out-dated. Is there a way to have the Wiki display search result that still work? If not - is it allowed to add a flag at the top of the Wiki page, which alerts the reader, that the information is outdated?

**Comment by josevalim** [comment]
The wiki is maintained by the community so you are free to change things in any way. If you try something out and it does not work, leaving up a note at the top with the date and versions would probably help the next person. I don't think it is something we can automate though.
