### ISSUE TITLE
Login at /users/sign_in not working, but /users/sign_up does

### ISSUE THREAD

**Issue by actuallymentor** [plataformatec/devise#3892]
Thanks for making this gem, it's great :)

For some reason I can't get it to work as it should. When signing in through /users/sign_in the page simply reloads and does nothing. This is true for correct and incorrect login details. The page simply refreshes and user_signed_in? returns false.

Sign_up however does work. Through there the database entries are created and user_signed_in? returns true for that session.

I followed the getting started and am quite confident I am using devise in a very standard use case. is there a way to debug this?

**Comment by josevalim** [comment]
It may be something related with the account activity. You have configured it for not considering fresh user accounts active or something of sorts? Did you do any configuration? Other than that, ensure you showing the flash messages, it should also say the actual reason.

**Comment by actuallymentor** [comment]
Hmm, somehow it works now. Is there any chance that using 11111111 as a password could cause an issue?

**Comment by josevalim** [comment]
No, that should not have been the issue. :)
