### ISSUE TITLE
Consider providing a method to decrypt the secret tokens

### ISSUE THREAD

**Issue by monfresh** [plataformatec/devise#3894]
Currently, secret tokens (such as the `reset_password_token`) are passed in directly to the Devise Mailer as one of the arguments. This goes against the best practice of not passing in any sensitive arguments to a mailer, or a background job. Because of this, the token will be exposed in Rails and Active Job logs.

Sure, you can change your Rails debug level to `warn`, but that's just masking the problem. If you need to change the level temporarily to troubleshoot, the sensitive info is still exposed. The point is that sensitive info should never be present in mailer or Active Job logs, regardless of the debug level.

One way to do that is to only pass in the User object to the mailer, and then inside the mailer, retrieve the token by decrypting it. So, instead of this:
```ruby
def reset_password_instructions(record, token, opts = {})
  @token = token
  devise_mail(record, :reset_password_instructions, opts)
end
```
it would be something like this:
```ruby
def reset_password_instructions(record, opts = {})
  @token = record.reset_password_token
  devise_mail(record, :reset_password_instructions, opts)
end
```
Is it already possible to decrypt the token in this way? If not, what do you think about doing something like the [attr_encrypted](https://github.com/attr-encrypted/attr_encrypted) gem?

**Comment by josevalim** [comment]
If you pass the whole record then you run into issues the record may not be serializable by those same structures. One work around is to pass the id, fetch it in the job, and then do the token.

However, honestly, I think this is working around the problem. As your problem describes quite well, they are the root cause. They are the ones mindlessly logging everything. I would rather find a way to fix those. That not being possible, you can pass IDs around.

**Comment by monfresh** [comment]
I don't think Rails is mindlessly logging everything. It is the programmer's responsibility to make sure sensitive arguments are not passed directly to a mailer or a background job. I just realized that the solution is easier than what I originally thought. 

Like you said, the token generation should happen inside the mailer. I was able to do it by modifying `#send_reset_password_instructions` so that it only calls the mailer, and then made `#set_reset_password_token` a public method so that it can be called from inside the mailer.

```ruby
# lib/devise/models/recoverable.rb
def send_reset_password_instructions
  send_devise_notification(:reset_password_instructions, {})
end

def set_reset_password_token
  raw, enc = Devise.token_generator.generate(self.class, :reset_password_token)

  self.reset_password_token   = enc
  self.reset_password_sent_at = Time.now.utc
  self.save(validate: false)
  raw
end
```

```ruby
# app/mailers/devise/mailer.rb
def reset_password_instructions(record, options = {})
  @token = record.set_reset_password_token

  devise_mail(record, :reset_password_instructions)
end
```

What do you think of this solution?

**Comment by josevalim** [comment]
> I don't think Rails is mindlessly logging everything. It is the programmer's responsibility to make sure sensitive arguments are not passed directly to a mailer or a background job.

Because? :)

Anyway, I don't agree with your solution conceptually because now the mailer is saving models only to workaround the fact it should not receive sensitive data (and again, only because of logging) but it should work fine.

**Comment by monfresh** [comment]
Good point. I agree that it's not the mailer's job to save the model.

However, I still think this is a valid issue. The problem is not just with Active Job logs. The secret token can also be exposed in the default Resque logs, if you're using that to process the emails, for example. 

Another scenario where this sensitive information could be exposed is if you enable capturing job arguments in New Relic's Sidekiq instrumentation: https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/sidekiq-instrumentation.

The point is that if the secret token is never passed to the job, then the risk of exposing the raw token is eliminated in all the different places where it could be exposed. One way to make sure the real token is not exposed is to use something like https://github.com/wuputah/sidekiq-encryptor, although I haven't tested it yet. However, I think that adds too much overhead if the encryption is only needed for one particular job. I think it's better if jobs never receive sensitive arguments in the first place.

**Comment by monfresh** [comment]
I submitted a pull request to filter Active Job logs: https://github.com/rails/rails/pull/23031
