### ISSUE TITLE
update_without_password isn't working

### ISSUE THREAD

**Issue by abhinaykumar** [plataformatec/devise#3895]
I have followed Instructions from here https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password but clearly its not working. Does anyone knows how to fix it. 
Password doesn't change  on update, also it doesnt throws error when password and password confirmation field is different but the same is working when i remove update_without_password method from controller.

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by abhinaykumar** [comment]
Yep, thanks will update wiki as soon as i get a fix to it.

**Comment by abhinaykumar** [comment]
OK, my bad...I didnt knew the whole idea behind with/ without password. Its working as it should be :)

**Comment by josevalim** [comment]
Glad you figured it out! :D
