### ISSUE TITLE
Devise logout isn't working when certain js files are included in application.js

### ISSUE THREAD

**Issue by pbssubhash** [plataformatec/devise#3897]
Hi, 
I'm using the latest version of devise and rails 4.2.4. 
I've my home page 
> public/index.html

which contains heavy javascript. But when I load it from some other page, it doesn't load with all the effects. So included 
> $(document).on('page:load', ready);
> <script src="/js/modernizr-2.6.2.min.js"></script>
> <script src="/js/main.js"></script>

in application.js file.
But then 
Logout 
><%= link_to "Logout",destroy_user_session_path, method: :delete %>

doesn't work! It gets rendered as GET /users/sign_out.

When I remove those links from application.js, it works fine.

Any workaround for this issue? 

Thanks.

**Comment by josevalim** [comment]
You are probably missing your javascript files that convert those links into actual posts with delete. Other than that,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
