### ISSUE TITLE
uninitialized constant Devise::Encryptors

### ISSUE THREAD

**Issue by cjk** [plataformatec/devise#39]
Wanted to give devise a try instead of authlogic.

I set everything up as desribed in the README, but when trying to start the server or even trying "rake db:migrate" I get the following error:

"uninitialized constant Devise::Encryptors"

Details:

...
rake aborted!
uninitialized constant Devise::Encryptors
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:440:in `load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:80:in`const_missing'
/home/cjk/work/hot/hotrails/vendor/gems/devise-0.5.5/lib/devise.rb:57
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
...

I use devise 0.5.5 and latest version of warden.

Thanks!

**Comment by jrgns** [comment]
For anyone seeing the `NameError: uninitialized constant Warden` error:

I was seeing the same issue in a Sinatra app. I was defining a new strategy in a file called `lib/warden.rb`. When doing a `require warden` from `spec_helper.rb`, it actually included the file in `lib`, not the gem, causing the issue described.

As a workaround I just renamed the `lib/warden.rb` file.
