### ISSUE TITLE
xhr? method called in in FailureApp#http_auth?

### ISSUE THREAD

**Issue by amitfriedman12** [plataformatec/devise#3902]
xhr? which is an alias for the method xml_http_request?  is called [here](https://github.com/plataformatec/devise/blob/dd5de829c944dd955e4b35074c60798c3ad4b947/lib/devise/failure_app.rb#L177) on a request object.

This is the rails [ActionController source code definition of xml_http_request?](http://apidock.com/rails/ActionController/Request/xml_http_request%3F)
```
def xml_http_request?
  !(@env['HTTP_X_REQUESTED_WITH'] !~ /XMLHttpRequest/i)
end
```
(This will always return a boolean)
Note the minor yet crucial difference with the rails [ActionDispatch source code definition of xml_http_request?](http://apidock.com/rails/ActionDispatch/Request/xml_http_request%3F)
```
def xml_http_request?
  @env['HTTP_X_REQUESTED_WITH'] =~ /XMLHttpRequest/
end
```
(This will either return nil or the index of the first regex match)

I made a failing json login request to the server (wrong email or password) which lead me to the FailureApp class.
When I manually run:
```
 !(request.env['HTTP_X_REQUESTED_WITH'] !~ /XMLHttpRequest/i)
```
I get true, as I should, since my json request contains the HTTP_X_REQUESTED_WITH header with the 'XMLHttpRequest' string value.

However when I run request.xhr? I get the value of 0 (this is of course the index of the first  regex match).
This leads me to conclude that the ActionDispatch#xhr? is  being invoked here.
0 evaluates to false, which is a bug since my json request is indeed an xhr request and so calling request.xhr? should return true.
This is really a confusing rails issue, but I suggest that Devise fix how they handle the result of the .xhr? method, since 0 should technically be evaluated to true (a match is found).
I am using Ruby 2.1.0p0, Rails 4.2.0, Devise 3.5.1.

Let me know if I should make a pull request to fix this minor issue.
Thanks

**Comment by josevalim** [comment]
0 does not evaluate to false in Ruby. It is working as expected. :) If there is a bug, it is elsewhere.

**Comment by amitfriedman12** [comment]
Oops! That is correct. Sorry, and thanks for expedient response (:
