### ISSUE TITLE
Devise 3.5.4, Rails 4.2.5 — No error messages on incorrect login.

### ISSUE THREAD

**Issue by vesuvius** [plataformatec/devise#3906]
Hello,

I get no error message on incorrect login (when no such email in the DB or wrong / empty password).
I checked the resource.errors hash and it stays empty after submitting the form.

But when I run (and only if I run) resource.valid? before invoking devise_error_messages! (see the code bellow), resource.errors returns :email=>["has already been taken"], :password=>["can't be blank"] which doesn't make sense.

.alert.alert-danger.margin-bottom-0
  %p{ style: "color: red" }
    - resource.valid?
    = devise_error_messages!

Signup, invitations, password resets, etc. work just fine.

Please help.

Regards!
Ivo

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
