### ISSUE TITLE
Case-insensitive Authentication

### ISSUE THREAD

**Issue by CodeMeister** [plataformatec/devise#3908]
With `config.case_insensitive_keys = [ :email ]` set in the initialisation file, the user's email is correctly downcased before saving.

However, when I try to sign-in using an uppercase version of the email address if fails to find the record.

Am I wrong in expecting devise to downcase the input email before searching?  I can't see anywhere in the code where this happens.

**Comment by josevalim** [comment]
I have just given this a try and it is working as expected. login is also downcased.  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
