### ISSUE TITLE
Issues with 3.5.4 and rememberable?

### ISSUE THREAD

**Issue by JamesHarrison** [plataformatec/devise#3909]
After upgrading from 3.5.3 to 3.5.4 in a Rails (4.2.5) app, checking the "remember me" checkbox no longer seems to actually cause the session to persist beyond the configured timeout (90 minutes).

remember_expires_at looks like it's being set correctly, along with remember_created_at, but users are getting the "session expired" message after 90 minutes of inactivity, not the configured 2 weeks of remember-me time.

Additionally, if you log in with Devise, all other Devise sessions for that user appear to become invalid. This means users authenticating on mobile will log out their desktop session, and vice versa.

The above behaviour changes haven't been documented anywhere, so I assume they're unintended - but if they are intended, this should be documented, and ideally options given to restore previous behaviour. At the least, this is a pretty major change for a point release.

**Comment by josevalim** [comment]
I will look into the session timedout issue. I can't reproduce the multiple log in though. Can you provide a simple application that reproduces it?

**Comment by josevalim** [comment]
@JamesHarrison I have fixed the timeout issue on the 3-stable branch. Could you give it a try? I am waiting on information on how to reproduce the multiple login issue. As soon as those are fixed I will do a new release. :)

**Comment by JamesHarrison** [comment]
Thanks - the timeout fix looks to have worked. Will try and verify the multiple login issue again/get a reproduction done.

**Comment by reedloden** [comment]
This is affecting us, too, so would appreciate a release with the fix. :) @josevalim

**Comment by josevalim** [comment]
Beautiful, cutting a new release now. :)

**Comment by josevalim** [comment]
3.5.5 is out :)
