### ISSUE TITLE
3.5.5 caused issue with remember me cookie

### ISSUE THREAD

**Issue by ohadco** [plataformatec/devise#3914]
Getting this for users that has remember me:
  ArgumentError (comparison of String with Time failed): 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:144:in `>' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:144:in   `serialize_from_cookie_with_or_without_record' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:113:in `serialize_from_cookie' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/strategies/rememberable.rb:20:in `authenticate!' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/strategies/base.rb:53:in `_run!' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:358:in `block in _run_strategies_for' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `each' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `_run_strategies_for' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:323:in `_perform_authentication' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:104:in `authenticate' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:114:in `authenticate?' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/app/controllers/devise_controller.rb:103:in `require_no_authentication' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:144:in `>' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:144:in `serialize_from_cookie_with_or_without_record' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/models/rememberable.rb:113:in `serialize_from_cookie' 
    vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/lib/devise/strategies/rememberable.rb:20:in `authenticate!' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/strategies/base.rb:53:in `_run!' 
    vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:358:in `block in _run_strategies_for' 
  vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `each' 
  vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `_run_strategies_for' 
  vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:323:in `_perform_authentication' 
  vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:104:in `authenticate' 
  vendor/bundle/ruby/1.9.1/gems/warden-1.2.4/lib/warden/proxy.rb:114:in `authenticate?' 
  vendor/bundle/ruby/1.9.1/gems/devise-3.5.5/app/controllers/devise_controller.rb:103:in `require_no_authentication' 

Any suggestion?

**Comment by josevalim** [comment]
Just for curiosity: if you clear up your cookies, does it still happen?

**Comment by ohadco** [comment]
When I clear my cookies it's working again (error is gone).

**Comment by josevalim** [comment]
Ok. If the error comes back, please try the `3-stable` branch. We have pushed a fix there.
