### ISSUE TITLE
Problem "ArgumentError at /***/password comparison of Time with TimeLord::Period failed" 

### ISSUE THREAD

**Issue by wellington1993** [plataformatec/devise#3915]
"Problem ArgumentError at /***/password comparison of Time with TimeLord::Period failed"

I have this message error after configured ":recoverable" (password recovery) in the models.

The password is changed, but this message is displayed after submitted the password change form

It's possible skip this message?

![captura de tela de 2016-01-26 13 47 11](https://cloud.githubusercontent.com/assets/6920053/12586002/9b06a500-c435-11e5-935e-d50128bec8d0.png)

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
