### ISSUE TITLE
:registerable and creating users by admin

### ISSUE THREAD

**Issue by ghost** [plataformatec/devise#392]
Hi!

I know that :registerable is used for self-registering users, but what is the reason
behind denying creating users by admin? (with :registerable enabled it prepends a filter to the begin of chain, that requires NO authentication)

vendor/gems/devise/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]

In my application I have a need to create users both by admin and by themselves.
So I wonder, could it be rather transferred to the developer level (whether or not to require authentication for creating users), than hardcode it in the gem?

And what the workarounds may be in this case?

**Comment by BKSpurgeon** [comment]
@korobkov Hi Andrey did you manage to find a solution to this problem. I am wanting the same thing: (i) I want admin to be able to create new users while logged in. In fact, I would like admins only, to be able to create users.

do you have any code/advice on this point?
