### ISSUE TITLE
Devise Integration Test with Capybara cannot find route helpers in Rails 5

### ISSUE THREAD

**Issue by JuanitoFatas** [plataformatec/devise#3922]
Hello! 

I am trying to write a Integration Test with [Capybara](https://github.com/jnicklas/capybara/commit/3f5c36f), Devise ffe9d6d4, and Rails 5.0.0.beta1.1.

The test:

```ruby
require 'test_helper'

class RootTest < ActionDispatch::IntegrationTest
  test 'root' do
    visit root_path
  end
end
```

`test/test_helper.rb`:

```ruby
require 'minitest/autorun'

ENV["RAILS_ENV"] = 'test'
require File.expand_path('../../config/environment', __FILE__)
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rails/test_help'

require "capybara/rails"

class ActionDispatch::IntegrationTest
  include Capybara::DSL

  # https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara
  include Warden::Test::Helpers
  Warden.test_mode!
end
```

If you run this test will result in:

```
Run options: --seed 45019

# Running:

E

NameError: undefined local variable or method `root_path' for #<RootTest:0x007f942b6f0d58>
    test/integration/root_test.rb:9:in `block in <class:RootTest>'

bin/rails test test/integration/root_test.rb:8



Finished in 0.011911s, 83.9568 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

I found if we remove the [warden test helpers](https://github.com/hassox/warden/blob/master/lib/warden/test/helpers.rb):

```
include Warden::Test::Helpers
```

then the test passed.

Something I am missing to fix this? Thanks in advance! 

--

I set up a [minimal app](https://github.com/JuanitoFatas/devise-integration-test) if you want to reproduce:

```
git clone https://github.com/JuanitoFatas/devise-integration-test
cd devise-integration-test && bin/setup && bin/rails test
```

--

This issue is found when [trying to upgrade devise 3.5.3 to 4.0.0.pre.dev with a Rails 5 app](https://github.com/codetriage/codetriage/pull/439/). You can see a more realistic failure at this build: https://travis-ci.org/codetriage/codetriage/builds/105609754.

**Comment by lucasmazza** [comment]
Sorry for the delay here - closing as it was an issue with a bogus warden release (codetriage/codetriage@823df04175fa733f90203c1805d669f12cff7460)
