### ISSUE TITLE
Support for jruby

### ISSUE THREAD

**Issue by ckgagan** [plataformatec/devise#3930]
When will devise support jruby 9.0.5.0?

**Comment by lucasmazza** [comment]
we don't officially support it on our build matrix but I hope it should be fairly compatible with jruby - do you have any specific issues with devise on jruby right now?

**Comment by ckgagan** [comment]
@lucasmazza : I am not having any issue with divise on jruby for now in development environment.

I am just concerned with the information in ReadMe of the repo which says "**Thread-safety support on JRuby is in progress**.".  If it's compatible with jruby then I think it must be mentioned in documentation.

**Comment by georgeguimaraes** [comment]
I've updated the docs. Devise should already be thread-safe on JRuby as well.
Tks.
