### ISSUE TITLE
Clarify README regarding location of `include Devise::TestHelpers`

### ISSUE THREAD

**Issue by cartrdgeengineering** [plataformatec/devise#3937]
I spent hours in frustration googling various Devise and Warden error messages I was getting while running tests for a Rails project, and it turns out the issue is that I had added the line `include Devise::TestHelpers` to the bottom of `ActiveSupport::TestCase` (the class which is by default already reopened in test_helper.rb), rather than reopening `ActionController::TestCase` and adding it there.

And my investigation into google results revealed that I am far from the only person who made this mistake. I found a number of other instances, and a lot of people seemed to going down rabbit holes and following false leads trying to figure out why Devise testing wasn't working as it's supposed to. It's apparently an easy mistake to make.

I think it would be good to explicitly state in the README that this mixin should _not_ be included `ActiveSupport::TestCase`. It's too easy to overlook that the README is showing `ActionController::TestCase` instead.

**Comment by SimonDKnight** [comment]
Hey, I am happy to look into that and will get back to you asap.

**Comment by SimonDKnight** [comment]
Fixed and made PR https://github.com/plataformatec/devise/pull/3941

**Comment by georgeguimaraes** [comment]
PR merged, gonna close this issue.
Tks for your report @cartrdgeengineering!

**Comment by cartrdgeengineering** [comment]
Wow, impressive response time! Thank you!
