### ISSUE TITLE
Shared links with -v flag

### ISSUE THREAD

**Issue by lachlanjc** [plataformatec/devise#3939]
I used the `-v` flag to generate the views I needed from Devise, like this:

`rails generate devise:views -v registrations sessions`

And in my `User` model, I only require some of the modules:

```rb
devise :database_authenticatable, :registerable,                               
       :recoverable, :rememberable, :trackable, :validatable
```

However, in the `devise/shared/links` partial, Devise included the links for Confirmable, Lockable, and Omniauthable:

```
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
```

While these links will never show up (since there aren't any controllers for them), I think it would be better if Devise did not generate them in the first place since they're not enabled for my only Devise model and I didn't ask for those views to be generated.

**Comment by lucasmazza** [comment]
> I think it would be better if Devise did not generate them in the first place since they're not enabled for my only Devise model and I didn't ask for those views to be generated.

Doing so would bring extra complexity to the generators, and snippets like these are meant to be updated/replaced by the developer if they want it to rather than be production ready views. Also, doing so would break the default behavior of enabling those links in case we enable any of these modules in our `User` model as it happens when using Devise with the built in views.

**Comment by lachlanjc** [comment]
Totally understand that @lucasmazza — just wanted to bring it up. Thanks for the thoughtful response!
