### ISSUE TITLE
html2haml wiki out of date

### ISSUE THREAD

**Issue by archonic** [plataformatec/devise#3940]
https://github.com/plataformatec/devise/wiki/How-To:-Create-Haml-and-Slim-Views

Instructions in the wiki are giving me 

    `method_missing': undefined method `this' for #<Gem::Specification:0x3fc5c9420968 haml-4.0.7`

Stackoverflow to the rescue:
http://stackoverflow.com/a/15676955/1686604

**Comment by nashby** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
