### ISSUE TITLE
Trying to redirect to login page on session timout

### ISSUE THREAD

**Issue by rnt363** [plataformatec/devise#3942]
Right now when the user session times out and the user tries to interact with the page, I get two 401 Unauthorized errors in the console. I would like it to redirect to the login page instead. 

I found with some digging that I can create my own custom failure app and override redirect_url to have it always redirect. This is what I have:

in /config/initializers/devise.rb

 require "custom_timeout_redirect"
  
  config.warden do |manager|
    manager.failure_app = CustomTimeoutRedirect
  end

in custom_timeout_redirect.rb:

class CustomTimeoutRedirect < Devise::FailureApp
  def redirect_url
      puts 'TRYING TO REDIRECT TO THE HOMEPAAAAAAAAAAAAAAAAAAGE'
      puts scope_url
      scope_url
    end
    scope_url
 end

This code is not run when the session times out. What's more, I've attempted to override the redirect method as well, and it seems that it isn't being invoked on session timeout either. 

Could someone steer me in the right direction here? I've read this solution to this problem on the web enough to where I'm thinking I'm just being dumb.

Thanks!

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
