### ISSUE TITLE
Using Devise for a 'headless' authentication service

### ISSUE THREAD

**Issue by alexbunardzic** [plataformatec/devise#3944]
I am building an authentication service in Rails. The idea is to offer an authentication end point that will accept email address and password and will then authenticate the request and return authentication token to the calling client. I've decided to use Devise as the solid authentication backbone, but am having issues when trying to authenticate via the service end point.

I have created a user with email address 'example@gmail.com' and password 'foobar123'. I am using curl to test the service:

```
curl -X POST -H "Content-Type: application/json" -d '{"email":"example@gmail.com","password":"foobar123"}' http://localhost:3000/users/sign_in
```

The above request fails with the following error:

```
Started POST "/users/sign_in" for ::1 at 2016-02-10 08:23:22 -0800
Processing by Devise::SessionsController#create as */*
  Parameters: {"email"=>"example@gmail.com", "password"=>"[FILTERED]", "session"=>{"email"=>"example@gmail.com", "password"=>"[FILTERED]"}}
Completed 401 Unauthorized in 5ms (ActiveRecord: 0.0ms)
```

In my users_controller.rb I have defined the create method:

```ruby 
 def create
  	user = User.new
  	if user.save
  	  render json: :user, status: 201, location: user
  	else
  	  render json: { errors: :user.errors }, status: 422
  	end
  end
```

Because this is a 'headless' back-end service, I have modified my application_controller.rb:

`protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }`

so that it only responds to JSON.

My sessions_controller.rb has this create method:

```ruby
 def create
  	user_password = params[:session][:password]
  	user_email = params[:session][:email]
  	user = user_email.present? && User.find_by(email: user_email)
  	if user.valid_password? user_password
  	  sign_in user, store: false
  	  user.generate_authentication_token!
  	  user.save
  	  render json: user, status :200, location user
  	else
  	  render json: { errors: "Invalid email or password" }, status: 422
  	end
end
```

Not sure what am I doing wrong to cause the 401 error?

Thanks for any help.

**Comment by alexbunardzic** [comment]
Apologies for not being able to indent code samples above - I've tried everything, but the 'Insert code' formatter wouldn't work properly.

**Comment by lucasmazza** [comment]
A wild guess would be that your `SessionsController` is requiring an authenticated user through the `authenticate_user` callback somehow, maybe inheriting it from a base controller, but we can't be sure about that without the full implementation or a sample app.

I'm closing this one as it seems to be a question rather than an issue. Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by alexbunardzic** [comment]
Thanks, and also apologies for using inappropriate venue to ask for assistance.
