### ISSUE TITLE
4.0.0.rc1 PG::UndefinedColumn: ERROR: column "password" of relation "users" does not exist

### ISSUE THREAD

**Issue by NZGlitch** [plataformatec/devise#3947]
After upgrading to devise 4.0.0.rc1 I get:

PG::UndefinedColumn: ERROR: column "password" of relation "users" does not exist LINE 1: INSERT INTO "users" ("email", "password", "encrypted_passwor...

Any ideas why this is happening?

This does not happen in 3.5.3 or earlier.

**Comment by jlocke2** [comment]
I am having this same problem.

@NZGlitch I created a password attribute in the DB for users as a temporary solution.  Devise always sets this to nil and creates the proper encrypted password, so it is still doing some sort of processing before saving.  Haven't been able to find the fix to this yet though.  Have you made any progress on this?

**Comment by svoynow** [comment]
I think this may be related to this bug:
https://github.com/rails/rails/issues/18407
as this was added to `lib/models/database_authenticatable.rb` at 2024fca4dfa3323070c3477e262b8422cadf6a42

```
      def password=(new_password)
        attribute_will_change! 'password'
        @password = new_password
        self.encrypted_password = password_digest(@password) if @password.present?
      end
```

So upgrading Rails might work (although I realize that isn't always feasible).
Can anybody weigh in on what (if any) bug adding `attribute_will_change` was supposed to fix?

**Comment by ulissesalmeida** [comment]
@svoynow `attribute_will_change` is supposed to track any change on `password` attribute. I'm not sure if we are checking for `password_change?`.

Like you said, it was a rails bug. Updating your rails app it may be fixed.

I'm closing this issue.
