### ISSUE TITLE
email and password validation message duplicating after rails upgrade to 4.1.14

### ISSUE THREAD

**Issue by Vipinmantri** [plataformatec/devise#3949]
I have upgraded rails version 4.0.12 to 4.1.14. While running test cases(or validating object through rails console), I could see same validation message twice for an email and password.

Failure:
UserTest#test_valid_email_address
Minitest::Assertion: Email xcvkktt should be invalid.
Expected: "is invalid"
Actual: "is invalid; is invalid

Environment:
rails: 4.1.14,
ruby: 2.1.6

Gems:
gem 'devise',
gem 'devise_ldap_authenticatable',
gem 'devise_security_extension',
gem 'rails_email_validator'

Dependancies: minitest (5.8.4)

And also my user model is associated to person model:
belongs_to :person, :autosave => true
And these validation messages is appended to person model also.

Any ideas why these is happening?

**Comment by SimonDKnight** [comment]
I will look into this and get back to you asap with an answer.

**Comment by Vipinmantri** [comment]
Thanks Simon

**Comment by ulissesalmeida** [comment]
@SimonDKnight @Vipinmantri Any news on this issues? This issue still happening? Which Devise version are you using?
