### ISSUE TITLE
Devise doesn't let me signup using username and a blank email

### ISSUE THREAD

**Issue by ankghost0912** [plataformatec/devise#3951]
Seeing the instructions [here](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address), I set up devise as my authentication module. However, upon accessing the signup form and filling in the fields, I get the error `username is invalid` and the server logs show the transaction to roll back citing `user_exists` (but the database is currently empty). Apparently, devise is running it's own authentication. 

If it's of any importance, I leave my email field blank .

**Comment by josevalim** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
