### ISSUE TITLE
encripted password are not saved in rails 5

### ISSUE THREAD

**Issue by arunnattarayan** [plataformatec/devise#3953]
i have using brand new rails 5 beta 2 version, i have used `plataformatec/devise', branch: 'master'` . so i can sign_up a new user it will not through any errors on my side, but the `encrypted_password` column stored as `NULL` so i cant login again.

**Comment by xw19** [comment]
I have tried to use devise branch 'master' with rails 5.0.0.beta2 it works perfectly

**Comment by georgeguimaraes** [comment]
@arunnattarayan  Can you please provide a sample application that reproduces the error?

**Comment by leonardoprg** [comment]
@georgeguimaraes 
I created a executable script test to help you guys reproduce errors

@arunnattarayan 

please, try use this script to simulate

https://gist.github.com/leonardoprg/a6be19c70bd9fd032d10

**Comment by georgeguimaraes** [comment]
I've just tested rails 5 beta 2 and devise 4.0.0.rc1.
I couldn't reproduce the error.
