### ISSUE TITLE
Active Admin and the Apartment gem

### ISSUE THREAD

**Issue by jasper502** [plataformatec/devise#3955]
I am trying to add Active Admin to my multi-tenant app (with the  Apartment gem).  I have Devise running on the main app under 'User' and added 'AdminUser' to Active Admin.  Devise works fine for both but fails when I try to use Apartment in Active Admin.

Here is my current StackExchange post on this before I narrowed down the issue to Devise: http://stackoverflow.com/questions/35378248/switching-apartment-tenants-in-active-admin

If I disable Devise my tenant switching logic works fine.  If I turn Devise back on the first tenant switch works then after that Devise throws 401 unauthorized errors.  The only think I can troubleshoot so far is that you actually do not get logged out.  You have to manually enter the logout URL to force a logout to actually login again otherwise logging in just fails over and over again.

This is beyond my expertise to troubleshoot further so any suggestions would be appreciated.

**Comment by leonardoprg** [comment]
@jasper502  can you provide a gem's  version or Gemfile.lock ? 

I will try to reproduce it locally

**Comment by jasper502** [comment]
I added my Gemfile.lock to my Gist: https://gist.github.com/jasper502/8fd16c31ee26667c5a16

I still have disabled Devise for now in AA and just added some basic HTTP AUTH.  It would be nice to get it back up and running.

**Comment by georgeguimaraes** [comment]
@leonardoprg Did you get to reproduce it?

**Comment by ulissesalmeida** [comment]
@jasper502 Any news on this issue?

**Comment by jasper502** [comment]
Nope... still have Devise disabled and using basic http auth.  Have not had the time to look at it again lately.
