### ISSUE TITLE
Won't let user login 

### ISSUE THREAD

**Issue by tkaboris** [plataformatec/devise#3956]
I get some complaints that sometimes users can't login even though they were able to login previously. I am using 3.5.2 version. Is there any ideas to why?

**Comment by tkaboris** [comment]
Was this issue resolved with current release?

**Comment by leonardoprg** [comment]
@tkaboris 

can you provide more details? sample app? log's?

it's a bit weird, We are using devise 3.5.4, and no problems here.

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
