### ISSUE TITLE
Executable test script to help with devise issues

### ISSUE THREAD

**Issue by leonardoprg** [plataformatec/devise#3958]
Hey Guys,

When fixing a issue on rails, I saw the rails guys has a nice executable script to share the tests/impressions (when open a new issue for example).

I created a new one for devise, please let me know if is it good for you guys, and if you guys wanna I open a PR about the contributing guide (specifying to before open a new issue try reproduce the behavior at executable test script)

ps: I know it has a little trick with test and controller, I'm trying to understand why.

[https://gist.github.com/leonardoprg/a6be19c70bd9fd032d10](https://gist.github.com/leonardoprg/a6be19c70bd9fd032d10)

just run ruby test.rb

Regards,

**Comment by georgeguimaraes** [comment]
Seems cool! I'll give it a try.

**Comment by ulissesalmeida** [comment]
@leonardoprg This is an amazing idea. \o/

I've seen in your gist that you are using the `ActionController::TestCase`, but in Devise test cases usually test with `ActionDispatch::IntegrationTest`. Do you think worth to update it? 

Feel free to open a PR. Would be very helpful to report issues. :)
