### ISSUE TITLE
rails beta 5.0.0.beta2 current_user gone after login

### ISSUE THREAD

**Issue by u007** [plataformatec/devise#3959]
hi,

ive a session controller extended from devise session controller,
when i log current_user, it contains current user, but after redirect,
current_user is nil
what could be the issue?
using devise 4.0.0.rc1

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by u007** [comment]
hi, i found the issues here

https://github.com/rails/activerecord-session_store/issues/70
