### ISSUE TITLE
Do not expose secured routes when paranoid

### ISSUE THREAD

**Issue by obduk** [plataformatec/devise#3964]
I think when paranoid is turn on, when a user is unauthenticated a 404 error should be returned instead of redirecting to the login page.

Without this, attackers can at least discover what routes exist without having a login. When doing various security audits this has been a recommended practice.

As it can be a hindrance for users, I think it should not be on by default.

**Comment by obduk** [comment]
For the time being I added a custom failure app to achieve this, I don't know if there is a better way of doing it? https://github.com/obduk/cms/commit/23b392a6511a5a27206758f1859559d5fc62e8b7

**Comment by josevalim** [comment]
I would say a custom failure app is exactly the way to go here. We will keep an eye open and see if other users request this feature before adding it to Devise.

**Comment by lucasmazza** [comment]
Isn't the `authenticated` constraint macro fit for something like this? https://github.com/plataformatec/devise/blob/342304375946ca11608516eae80f78dbaae059d5/lib/devise/rails/routes.rb#L294-L316

**Comment by obduk** [comment]
Looking at it I don't think constraints could hide all routes (as some only authenticated depending on the database record fetched). I think it could also lead to a messy routes file.
