### ISSUE TITLE
minimum_password_length not accessible from registrations/edit view

### ISSUE THREAD

**Issue by Yanchek99** [plataformatec/devise#3967]
This may be a feature request but I was wondering what the reason behind removing the @minimum_password_length variable from the edit registrations view? 

 I think it is still beneficial to prompt the end user of the minimum password length when changing their password.  Would be nice if I could display the same message used in the registrations/new view.

**Comment by ulissesalmeida** [comment]
Hi @Yanchek99 ! I don't know when it was removed. Do you know or remember which version it was removed?

I'm totally ok to bring these variables to edit/update actions and show it in some way on the edit form view. Do you want to open pull request with feature proposal?

**Comment by lucasmazza** [comment]
Chased by #4068
