### ISSUE TITLE
remember_user_token doesn't stay after user signout if config sets to false

### ISSUE THREAD

**Issue by ahmad19** [plataformatec/devise#3970]
Hi, 
I'm using `rails 4.2`, `devise-3.5.6` and `warden-1.2.6`.

In the config `devise.rb`, i tried to set 
`config.expire_all_remember_me_on_sign_out = false` in order to retain `remember_user_token` cookie after user sign-out. But it get destroyed after sign-out. 
Please confirm if this is a bug or not ?

**Comment by ulissesalmeida** [comment]
@ahmad19 Thank you for your report. Is a bug and is fixed on Devise `3.5.7`.

**Comment by ulissesalmeida** [comment]
Related PR: https://github.com/plataformatec/devise/pull/4039
