### ISSUE TITLE
Devise failed_attempts (lockable) doesn't get incremented.

### ISSUE THREAD

**Issue by sebastianzillessen** [plataformatec/devise#3971]
Hi,

I have this simple rspec test on one of my devise models:

````
    it "should allow 10 login attemps with wrong password and then block the account" do
      10.times do |i|
        post :create, {account: {email: user.email, password: 'random nonsense'}}
        user.reload.failed_attempts.should eq i+1
        flash[:alert].should eq I18n.t("devise.failure.invalid", :email => user.email)
      end
      post :create, {account: {email: user.email, password: 'random nonsense'}}
      flash[:alert].should eq I18n.t("devise.failure.locked", :email => user.email)
    end
````

but unfortunately the failed_attempts doesn't get incremented, although the login fails.

````
Failure/Error:         user.reload.failed_attempts.should eq i+1
      
       expected: 2
            got: 1
       
````

It seems to be any issue with the rSpec environment, as it works perfectly when I'm testing it manually in the browser.

Anything I can do to fix this?

**Comment by georgeguimaraes** [comment]
Did you check the initial value of `failed_attempts`? I think it's `0` and then it gets incremented to `1`.

**Comment by sebastianzillessen** [comment]
Yeah, it is 0 at the beginning, but shouldn't it increase further?

**Comment by georgeguimaraes** [comment]
But where does `i` come from?

**Comment by georgeguimaraes** [comment]
If you print the `failed_attempts`, is it increasing?

**Comment by sebastianzillessen** [comment]
Sorry, of course it is the loop variable, I didn't copy everything probably 😄 

If I print them, they stay at "1" for all 10 loops.

**Comment by georgeguimaraes** [comment]
I'll give it a try. I'll let you know the results.

**Comment by sebastianzillessen** [comment]
Any updates on it?

**Comment by sebastianzillessen** [comment]
@georgeguimaraes ?

**Comment by trendwithin** [comment]
@sebastianzillessen I was having a similar issue and saw this post in my search.  I now have a Capybara test that works and increments.  It might work as a substitute in your situation.

	require "test_helper"

	feature "User Sign In" do
	  def setup
	    @new_user = User.new(email: 'sign_in_test@example.com', password: 'password', password_confirmation: 'password')
	    @new_user.confirm
	    @new_user.save
	  end
	  
    scenario 'Lockable account after 20 failed tries' do
	    visit new_user_session_path
	    20.times do
	      fill_in 'user_login', with: @new_user.email
	      fill_in 'Password', with: 'password123'
	      click_button 'Log in'
	      @new_user.reload
	      puts @new_user.failed_attempts
	    end
        assert_equal 20, @new_user.failed_attempts
	    fill_in 'user_login', with: @new_user.email
	    fill_in 'Password', with: 'password'
	    click_button 'Log in'
	    page.must_have_content 'Your account is locked.'
      end
    end

**Comment by ulissesalmeida** [comment]
@trendwithin  Thanks.

@sebastianzillessen I'm closing this issue. Feel free to reopen if the problem persist and you have more information.
