### ISSUE TITLE
Devise.email_regexp doesn't detect some wrong emails addresses

### ISSUE THREAD

**Issue by pedramteymoori** [plataformatec/devise#3975]
In our project, sometimes we get `Net::SMTPServerBusy: 401 4.1.3 Bad recipient address syntax`.
After check, we find out that the email was like 'foo@bar..foo' and 'Devise.email_regexp' detects it as a correct email address.

I think we shoud change Devise email regexp from `/\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/` to something like `/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i` as shown [here](http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_format_of).

I can fix this if you confirm.

Ruby : 2.2.3
Rails : 4.2.5
Devise : 3.5.6
Thanks.

**Comment by josevalim** [comment]
That's on purpose. :) Doing correct e-mail validation is actually quite complex and it would allow things like `foo@213.43.23.49` which a lot of people don't want. So we keep a single one on purpose, feel free to change if you want to. You can also consult previous issues open for this exact reason to see previous discussions. THank you!

**Comment by pedramteymoori** [comment]
Thanks for your answer :)
