### ISSUE TITLE
Improve wiki page: How To: Create a guest user

### ISSUE THREAD

**Issue by lksv** [plataformatec/devise#3976]
Thank you for super gem and perfect docs and wiki.

I suggest (and please review) the improvement of setting Guest User. The [wiki page](https://github.com/plataformatec/devise/wiki/How-To:-Create-a-guest-user) recommends how to set a helper function `current_or_guest_user`. And usage of  `logging_in` which handles the copying data form guest_user to current_user.

Then there is a section:

> If you use this logging_in function and write the code it needs, you must customize the create action in both the sessions controller and the registrations controller by calling current_or_guest_user after super.

It seems to me too complex change. I think that there is a more simple solution: call logging_in function each time (`before_filter :logging_in`) and use the following code:

     def logging_in
       # do nothing if not logged in or no guest session
       return unless user_signed_in? and session[:guest_user_id]

       # put business logic here
       # ...

       # remove guest sessin and Guest User from AR
       if session[:guest_user_id]
         begin
           User.find(:guest_user_id).destroy
           rescue ActiveRecord::RecordNotFound
         end
         session[:guest_user_id] = nil
       end
     end

**Comment by carlosantoniodasilva** [comment]
The wiki is maintained by the community, so you should be able to edit and improve it however you'd like. :)

Thank you!

**Comment by lksv** [comment]
Thanks @carlosantoniodasilva , good to know. But, I cannot change it directly without review. What to do in this case?
