### ISSUE TITLE
Cannot update params when use warden.authenticate in devise

### ISSUE THREAD

**Issue by syter** [plataformatec/devise#3978]
Hi,
I have upgrade my rails from 3.2.8 to rails 4, also devise is upgrade from 2.1.2 to 3.5.6 and warden from 1.2.3 to 1.2.6.
I found an issue that I don't know what it should belongs to devise or warden.

Before I call 
`resource = warden.authenticate(:scope => resource_name, :recall => "#{controller_path}#new")` 
I update params value like below:
   `params[:admin] = Hash.new
    params[:admin][:email] = params[:email]
    params[:admin][:password] = params[:password]`

But when I print params in proxy.rb, the function def authenticate(*args)
the params is still the original, there are no any admin in it.

The issue is not happened when I use the old system.
And because of this issue, I cannot authenticate admin successfully.

Is there any configuration or any other things I missed?

Hope ur answers,
Thank u.

**Comment by syter** [comment]
Here is my part of code and logs:
controllers.rb

    params[:admin] = Hash.new
    params[:admin][:email] = params[:email]
    params[:admin][:password] = params[:password]
    params[:password] = '11111111111111'
    # authenticate with warden
    p '===================================='
    p params
    p warden
    resource = warden.authenticate(:scope => resource_name, :recall => "#{controller_path}#new")
    p params
    p '===================================='

proxy.rb

    def authenticate(*args)
      p 'sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss'
      p params
      params[:password] = '111111111'
      p params
      p 'sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss'
      user, _opts = _perform_authentication(*args)
      user
    end

logs:
"===================================="
{"email"=>"syter@xxxx.com", "password"=>"11111111111111", "controller"=>"admin_sessions", "action"=>"create", "version"=>"v1", "format"=>"json", "admin"=>{"email"=>"syter@xxxx.com", "password"=>"xxxxxxxx"}}
Warden::Proxy:70145506030260 @config={:default_scope=>:admin, :scope_defaults=>{}, :default_strategies=>{:admin=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007f980f873e18>}
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
{"email"=>"syter@xxxx.com", "password"=>"xxxxxxxx", "controller"=>"admin_sessions", "action"=>"create", "version"=>"v1", "format"=>"json"}
{"email"=>"syter@xxxx.com", "password"=>"111111111", "controller"=>"admin_sessions", "action"=>"create", "version"=>"v1", "format"=>"json"}
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
{"email"=>"syter@xxxx.com", "password"=>"111111111", "controller"=>"admin_sessions", "action"=>"create", "version"=>"v1", "format"=>"json"}
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
{"email"=>"syter@xxxx.com", "password"=>"11111111111111", "controller"=>"admin_sessions", "action"=>"create", "version"=>"v1", "format"=>"json", "admin"=>{"email"=>"syter@xxxx.com", "password"=>"xxxxxxxx"}}
"===================================="

It seems there are two params, one is in controller, one is in warden.

**Comment by syter** [comment]
I aslo created question in stackoverflow : http://stackoverflow.com/questions/35727602/cannot-update-params-when-use-warden-authenticate-in-devise

**Comment by ulissesalmeida** [comment]
@syter I think the reason you can't update the params and `Warden` use them because the `params` on Rails controller is now a different object of the `params` that `Warden` uses. I think this changed has come with Rails strong parameters.

* The `env` came from a middleware pass to [`Warden::Proxy`](https://github.com/hassox/warden/blob/906edf86c6c31be917a921097031b89361d022e8/lib/warden/manager.rb#L33), then it passed to a strategy.
* The `Warden::Strategy::Base` [uses](https://github.com/hassox/warden/blob/906edf86c6c31be917a921097031b89361d022e8/lib/warden/strategies/base.rb#L40) the `Warden::Mixins::Common`
* The method `params` [use](https://github.com/hassox/warden/blob/906edf86c6c31be917a921097031b89361d022e8/lib/warden/mixins/common.rb#L18) the env from a request

I think you may need to change your variables in a different context.

**Comment by ulissesalmeida** [comment]
I think it is not a Devise issue, feel free to reopen if you have some evidence that is from Devise.
