### ISSUE TITLE
confirmable by administrator

### ISSUE THREAD

**Issue by mrdinghy** [plataformatec/devise#3982]
It would be really nice to have a Devise setup option so that when users register it sends a "thank you for registering, you will be approved by admin and notified".  This email will be cc'ed to one or more admins to notify that someone has registered. The new user remains unconfirmed.

Admin goes into users list and can approve (confirm) or disapprove user registration. 

If approved new user will be sent the normal Confirmation email with a link to logon  for the first time. 

If not approved a "dear John" email is sent saying user was not approved ..."contact admin for clarification". 

I am having trouble setting this up. If i can't send a "Welcome you have to be approved" email then I could live with no email going out but the user to remain unconfirmed until admin approves. When this happens then the normal Confirmation email can be sent to new user. 

i see code for this like 
```
user = User.new
user.skip_confirmation!
```
but i have no idea where this is placed. I only have` show `and` index `methods in the `users_controller.rb` file. In the `user.rb `model i tried entering a new initialize method to overwrite the Devise engine but that did not work. 

Any pointers on how to make this behave like i need it to. Or at least to move the confirmation email to manually enabled by admin after registration. 
Thanks much

**Comment by ulissesalmeida** [comment]
@mrdinghy You may want to add the `skip_confirmation!` on your `create` controller action for your users sign up. You may want to add a date time column , like `admin_confirmed_at` for your User model to store when the admin has confirmed that user. Then you may add this new flag to check users permissions in your app.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
