### ISSUE TITLE
rails 5 with devise_omniauth_callback

### ISSUE THREAD

**Issue by u007** [plataformatec/devise#3983]
im getting this error,

W, [2016-03-07T01:08:19.779204 #12853]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 5.1. (called from devise_omniauth_callback at /usr/local/rvm/gems/ruby-2.2.4/bundler/gems/devise-342304375946/lib/devise/rails/routes.rb:452)

i tried comment off my omniauth, it still persists with this error?
what is the new way to implement omniauth with devise?

thank you

**Comment by u007** [comment]
thank you :+1:

**Comment by u007** [comment]
hi, im seing new error when i called:
user_omniauth_authorize_path(:facebook)

it was previously working on my rails 4, but due to latest bundle update from github, it throws:
undefined method `user_omniauth_authorize_path' for ... (in the view file)

**Comment by lucasmazza** [comment]
@u007 thanks for the report - and sorry about that. Those helpers aren't generated anymore, and we should do something like `user_facebook_authorize_path` instead - I'll see if we can push a deprecation warning instead of `NoMethodError`.

**Comment by sunki** [comment]
The proper helper is `user_facebook_omniauth_authorize_path`
