### ISSUE TITLE
Generator for User creates almost empty class on Mongoid and rails 5.0

### ISSUE THREAD

**Issue by Startouf** [plataformatec/devise#3986]
Running `rails g devise User` should create a User class model and fill it with useful devise fields. But after running that generator script, my User class is dead empty

```

class User

  include Mongoid::Document





end
```

The empty lines and the output of the console (the two insert on user.rb) seem to say that something went wrong

```
PS C:\Dev\MyApp> rails g devise User
      invoke  mongoid
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml
      insert    app/models/user.rb
      insert    app/models/user.rb
       route  devise_for :users
PS C:\Dev\MyApp>
```

The other files seem to have been generated/modified normally. Only a problem with the User class.

May be useful

* Rails 5.0.0beta3
* Devise 4.0.0rc1 (revision 342304375946ca11608516eae80f78dbaae059d5)
* Mongoid 6.0.0 (MONGOID-4218-rails-5)
* Windows 8.1 & Powershell
* ruby 2.2.4p230

**Comment by lucasmazza** [comment]
We currently don't support Mongoid 6 as there isn't any released version with Rails 5 support and the required changes for it to support Rails 5 haven't landed on `mongodb/mongoid`.

Devise seems to works as expected with Mongoid 5 (although our test suite doesn't use it, see #3855), and there isn't much we can do without a proper version of Mongoid to work with.
