### ISSUE TITLE
Out of the box JSON compatibility

### ISSUE THREAD

**Issue by nomanurrehman** [plataformatec/devise#3987]
If this has been brought up before, please do point me in the right direction.

I am trying to make Devise work purely on JSON and the default setup does not seem to support it.

I have jumped into customization and started with the registration controller.

Here is my code.

```ruby
class Users::RegistrationsController < Devise::RegistrationsController

  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  respond_to :json

  private

  def json_request?
    request.format.json?
  end

end
```

Everything works fine but I do not get an error if the request is missing the `password_confirmation` parameter.

I did something similar with the confirmations controller. In that case, if a request is missing an email,  I get an error but if I add one, the response is empty `{}` and no errors are thrown. The database record is not modified as well.

Am I correct to assume Devise is not supposed to work as a pure JSON solution?

I would be happy to customize it and submit a pull request if that is the case.

**Comment by ybur-yug** [comment]
It seems like [this](https://github.com/lynndylanhurley/devise_token_auth) might be a good answer for what you are doing @nomanurrehman. I've used this technique (though not the gem specifically) in several JSON-API projects and had no problems.

**Comment by nomanurrehman** [comment]
@ybur-yug 

Thanks.

Using a different gem still does not answer my question, though I do understand that the gem you have pointed me to is also a customization of devise.

I am more interested in knowing if there is a way using Devise purely to be sure before I move forward with the customization.

**Comment by ybur-yug** [comment]
@nomanurrehman If you peruse the source, it largely is a wrapper of devise that removes a lot of the boilerplate work for you. Utilizing what it does under the hood would solve your problem exactly I think.

**Comment by ulissesalmeida** [comment]
@nomanurrehman Devise controllers were build to work as a server side application that's render HTML. If you need a different solution, you may need to customize the controller by yourself or use a gem like @ybur-yug mentioned.

I think we are not planning to deliver out of the box solution like that for now. Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
