### ISSUE TITLE
Sql UPDATE Failed  User. "id" is missing

### ISSUE THREAD

**Issue by pyralis** [plataformatec/devise#3988]
`Failed to prepare sql UPDATE userds SET current_sign_in_at = ?, last_sign_in_at = ?, sign_in_count = ?, updated_at = ? WHERE userds. = 11 due to: Token = was not valid.`

So I'm not sure where to go to look into where the sql is being generated for this but when I try to login as a user, it gives the error above and on a test machine with the same controllers and routes it populates the "userds"."id" portion... the user in this case being user 11. Any ideas on what maybe causing this?

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by ulissesalmeida** [comment]
@pyralis I'm closing this issue. Feel free to reopen when you have more information in how to reproduce the problem. You can create Devise test case, provide a sample application that reproduces the error or even use the template mentioned above.
