### ISSUE TITLE
custom strategies headers not honored

### ISSUE THREAD

**Issue by tux-mind** [plataformatec/devise#3989]
The following test fail with:
- devise 3.5.6
- warden 1.2.6
- rails 4.2.5.2

``` ruby
# test/controllers/custom_strategy_test.rb
require 'test_helper'
require 'ostruct'
require 'warden/strategies/base'
require 'devise/test_helpers'

class CustomStrategyController < ActionController::Base
  def new
    warden.authenticate!(:custom_strategy)
  end
end

class CustomStrategy < Warden::Strategies::Base
  def authenticate!
    headers 'X-FOO' => 'BAR'

    success! nil
  end
end

class CustomStrategyTest < ActionController::TestCase
  tests CustomStrategyController

  include Devise::TestHelpers

  setup do
    # added since I have no rails_app sample, just a test
    Rails.application.routes.draw do
      get "/custom_strategy/new"
    end
    Warden::Strategies.add(:custom_strategy, CustomStrategy)
  end

  teardown do
    Warden::Strategies._strategies.delete(:custom_strategy)
  end

  test 'custom strategy can return custom headers' do
    ret = get :new

    # check the saved response headers as well.
    assert_equal response.headers['X-FOO'], 'BAR'
  end
end
```

I'm working on a workaround...

**Comment by tux-mind** [comment]
a possible workaround:

```ruby
class ApplicationController < ActionController::API
  include CanCan::ControllerAdditions

  def initialize
    super
    Warden::Manager.after_authentication do |user, auth, opts|
      response.header.merge! auth.headers
    end
  end
end
```

**Comment by ulissesalmeida** [comment]
@tux-mind Thank for your report.

Reading the code you have shown, I'm not sure if it is a Devise issue. I think it is more related to `Warden` itself. Could you give more information why it is related to Devise?

**Comment by tux-mind** [comment]
As far as I remember warden set the headers correctly, it's up to devise to
bind up those headers to the final ones.

Thank you for the whole stuff, I hope that this will make devise better :)
Il 19 apr 2016 4:46 PM, "Ulisses Almeida" <notifications@github.com> ha
scritto:

**Comment by ulissesalmeida** [comment]
@tux-mind I'll take a look on it.

**Comment by tegon** [comment]
I'm closing this since it has been here for a long time and I don't know if it's still relevant.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
