### ISSUE TITLE
Handling language change and stored_location_for

### ISSUE THREAD

**Issue by pmichna** [plataformatec/devise#3990]
In ApplicationController I have:

```
def after_sign_in_path_for(resource)
  stored_location_for(resource) || home_path
end
```
It works fine until I change locale in sign_in page. Locale depends on url.

Example:

1. I try to access restricted page `localhost:3000/en-GB/something`
2. I am redirected to login page `localhost:3000/en-GB/users/sign_in`.
3. On login page I change the language and the current url changes to `localhost:3000/fr-FR/users/sign_in`.
4. After successful sign in I get back to the restricted page but with original locale: `localhost:3000/en-GB/something`.

I know the problem is that stored location is set before redirecting to login page when trying to access restricted page.

Is there a clean way to handle this situation? One option that comes to my mind is customizing Devise sessions controller. I could somehow manipulate stored location by modifying the url's string. However, this looks very dirty.

**Comment by lucasmazza** [comment]
> One option that comes to my mind is customizing Devise sessions controller. I could somehow manipulate stored location by modifying the url's string. However, this looks very dirty.

One alternative I can think of is to change the url's String when you change the current language, so whatever is stored gets updated to match the new locale - other than that I can't think of any new way to handle this on Devise's side since it stores the raw pathnames for the visited URLs.

**Comment by pmichna** [comment]
I don't know whether I understand correctly. What do you mean by changing the url's String? Isn't it what I'm already doing? `localhost:3000/en-GB/users/sign_in` changes to `localhost:3000/fr-FR/users/sign_in` when I change language.

**Comment by lucasmazza** [comment]
@pmichna I meant to change the URL that was stored by `store_location_for` inside the session, before the locale change.
