### ISSUE TITLE
Extending remember me expiration enabled by default.

### ISSUE THREAD

**Issue by jjoos** [plataformatec/devise#3994]
This commit c92996646aba2d25b2c3e235fe0c4f1a84b70d24 unwillingly enabled extending the remember me period for our application. (Devise 3.5.6)

I added this to our models to disable the behaviour:
```
private :extend_remember_period=
```

and removed (which was the default value for this config):
```
config.extend_remember_period = false
```

What would be the best way to do this in a way that will be the supported in future versions?

**Comment by jjoos** [comment]
Also needed to add a bit of extra monkey patching to our already existing monkey patch related to #3950 to get this working.
```diff
--- a/config/initializers/devise_remember_me_monkey_patch.rb
+++ b/config/initializers/devise_remember_me_monkey_patch.rb
@@ -1,42 +1,50 @@
 module Devise
   module Models
     module Rememberable
       # TODO: Keep track of this issue and remove monkey patch when resolved
       # https://github.com/plataformatec/devise/issues/3950
 
       def remember_me!(*)
         return unless remember_token.blank?
 
         self.remember_token = self.class.remember_token
         self.remember_created_at = Time.now.utc
         save(validate: false) if self.changed?
       end
+
+      # Make sure it returns the original generated_at timestamp of the token
+      module ClassMethods
+        # Create the cookie key using the record id and remember_token
+        def serialize_into_cookie(record)
+          [record.to_key, record.rememberable_value, record.remember_created_at.utc.to_f.to_s]
+        end
+      end
     end
   end
 end
```

**Comment by josevalim** [comment]
Hi @jjoos, I think there is some confusion here because that commit is not supposed to extend the remember me period. Maybe it is the monkey patch from #3950 affecting it? I have posted an alternative monkey patch, please let me know how it goes. Thank you.

**Comment by jjoos** [comment]
Sorry I thought `Devise::Strategies::Rememberable#extend_remember_me_period` had something to do with it since it always gets called and looking at some historic commits 2e43944567deb0b376e764e2362613e886c3e4f7 7029a5aaa88fcee9a9bf25a63d0105ad97728d08 I presumed it's purpose is to update `remember_created_at` on the resource? But it seems it doesn't do that anymore.

> because that commit is not supposed to extend the remember me period

c92996646aba2d25b2c3e235fe0c4f1a84b70d24, changes the `serialize_into_cookie` to always return `Time.now` as the `generated_at`. Which looking at the check in `Devise::Models::Rememberable#remember_me?`:

```ruby
        # The token is only valid if:
        # 1. we have a date
        # 2. the current time does not pass the expiry period
        # 3. the record has a remember_created_at date
        # 4. the token date is bigger than the remember_created_at
        # 5. the token matches
        generated_at.is_a?(Time) &&
         (self.class.remember_for.ago < generated_at) &&
         (generated_at > (remember_created_at || Time.now).utc) &&
         Devise.secure_compare(rememberable_value, token)
```

Effectively extends the remember_me token, right? The generated only needs to be bigger then`remember_created_at`, not `generated at < (remember_created_at.utc + self.class.remember_for)`

Btw I also ran into an issue with this comparison in `Devise::Models::Rememberable#remember_me?`:
`(generated_at > (remember_created_at || Time.now).utc)` it relies on the fact that you constantly return an updated `generated_at` in the token, if we're not updating those values all the time per monkey patch for #3950. It's starting to randomly fail due to some serialization issues (probably some precision is lost). I 'fixed' that by changing it to `(generated_at.utc.to_i >= remember_created_at.utc.to_i) &&`

Current monkey patch:
```ruby
module Devise
  module Models
    module Rememberable
      # TODO: Keep track of this issue and remove monkey patch when resolved
      # https://github.com/plataformatec/devise/issues/3950

      def remember_me!(*)
        return unless remember_token.blank?

        self.remember_token = self.class.remember_token
        self.remember_created_at = Time.now.utc
        save(validate: false) if self.changed?
      end

      def remember_me?(token, generated_at)
        # TODO: Normalize the JSON type coercion along with the Timeoutable hook
        # in a single place https://github.com/plataformatec/devise/blob/ffe9d6d406e79108cf32a2c6a1d0b3828849c40b/lib/devise/hooks/timeoutable.rb#L14-L18
        if generated_at.is_a?(String)
          generated_at = time_from_json(generated_at)
        end

        # The token is only valid if:
        # 1. we have a date
        # 2. the current time does not pass the expiry period
        # 3. the record has a remember_created_at date
        # 4. the token date is bigger than the remember_created_at
        # 5. the token matches
        generated_at.is_a?(Time) &&
         (self.class.remember_for.ago < generated_at) &&
         (generated_at.utc.to_i >= remember_created_at.utc.to_i) &&
         Devise.secure_compare(rememberable_value, token)
      end

      # Make sure it returns the original generated_at timestamp of the token
      module ClassMethods
        # Create the cookie key using the record id and remember_token
        def serialize_into_cookie(record)
          [record.to_key, record.rememberable_value, record.remember_created_at.utc.to_f.to_s]
        end
      end
    end
  end
end
```

**Comment by josevalim** [comment]
Oh, you are right. This line of code: https://github.com/plataformatec/devise/blob/master/lib/devise/strategies/rememberable.rb#L28 should only be called if extend_remember_me is set. This means we should not deprecate this config and instead check for it there. The `extend_remember_me_period` method in that class is also completely meaningless now. Can you please try such changes and let us know?

**Comment by jjoos** [comment]
I'll create a proper pull request for you tomorrow!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by ulissesalmeida** [comment]
@jjoos Any news about this issue? Have you tried the @josevalim  suggestions?
