### ISSUE TITLE
Moving unconfirmed_email to email with a bypass on update

### ISSUE THREAD

**Issue by bl4ckdu5t** [plataformatec/devise#3996]
I have a Oauth authentication option where I don't want users to require confirmation for use. I created an extra step for users to store their email address to allow use of multiple social identities with an account. The problem is when the email is taken it gets stored in `unconfirmed_email` even with `skip_confirmation` method used. Is there a way to prevent email from going to `unconfirmed_email` and getting stored in `email` on update?

**Comment by ulissesalmeida** [comment]
@bl4ckdu5t 

If you don't wat e-mail confirmation, you can set in your `config/initializers/devise.rb`:

```
config.reconfirmable = false
```

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
