### ISSUE TITLE
Devise::email_regexp rejects unusual but valid email

### ISSUE THREAD

**Issue by kimgb** [plataformatec/devise#3997]
"example@tt" =~ Devise.email_regexp
    # => nil

Compare to: http://isemail.info/example%40tt

I figure the intent of the `Devise::email_regexp` is to conduct _minimal_ validation, and it should "first do no harm". Note the above `@tt` address is an example of a TLD that [does, in fact, have MX records on it](http://serverfault.com/questions/721927/can-you-have-an-email-address-with-only-the-top-level-domain-as-the-domain-part). Dominic Sayers on isemail.info also [reports encountering an in-use email on the Ukrainian `@ua` TLD](http://isemail.info/#comment-294596693).

Do I misunderstand the spec of the Devise default behaviour here?

**Comment by josevalim** [comment]
Good catch, please send a PR? :)

**Comment by kimgb** [comment]
Will do

**Comment by ulissesalmeida** [comment]
Done in #4001
