### ISSUE TITLE
Error: `router_name` is undefined for Devise.mappings

### ISSUE THREAD

**Issue by PedroVinicius** [plataformatec/devise#3998]
I'm building a rails app that needs sign_in and sign_up form be showed into a bootstrap modal. I followed a tutorial I saw in the Devise's wiki in order to show the login form from anywhere. My code is so:

**config/routes.rb**
`devise_for :users`

**app/controllers/application_controller**
  ```ruby
  def resource_name
    :user
  end\

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  helper_method :resource_name, :resource, :devise_mapping
```

When I try call this:

**app/views/layouts/_auth_form.html.erb**
```ruby
<%= form_for(resource, as: resource_name, url: session_path(:users)) do |f| %>
  
<% end %>
```

I'm receiving this error:

`undefined method 'router_name' for nil:NilClass`

I found nothing about this error. What I'm doing wrong?

**Comment by ulissesalmeida** [comment]
@PedroVinicius 
Thank you for your report.

Which wiki tutorial are you using? Could you provide the link for us?

Could you please provide more information?
Like for example: 
* Rails version
* Devise version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application that reproduces the error.

Best

**Comment by ulissesalmeida** [comment]
@PedroVinicius I'm closing this issue. Feel free to reopen when you have more information in how to reproduce the problem. You can create Devise test case or provide a sample application that reproduces the error.
