### ISSUE TITLE
Unable to create separated tables for each user logged in

### ISSUE THREAD

**Issue by JaeggerFrank** [plataformatec/devise#4002]
Hello Guys.

I `ve been trying to create a new table for each user. When  a test user logs in, he can see all the data from the table that belongs to another user. I tried checking the documentation but I didnˆt found nothing

Maybe I `m posting this on the wrong place , but I really need some help. The application will look like a online shop, where anyone can put their products in their own dashboard, separately. Each user will have its own dashboard.

Best regards

Pedro

**Comment by shakycode** [comment]
I don't think is a devise issue. The behavior of your app can be accomplished with Rails ActiveRecord and some creative use of associations. You might want to post your question on StackOverflow.

**Comment by JaeggerFrank** [comment]
@shakycode Thank you!
