### ISSUE TITLE
When generate a new devise resource creates a migration file without the .rb extension 

### ISSUE THREAD

**Issue by nerionavea** [plataformatec/devise#4009]
**Versions:**
Rails 4.0.13
Warden 1.2.6
Devise 3.0.4

When I use the generate command, it's creates all the files perfectly but creates the migrations file without '.rb' extension. 

e.g. 

```
 rails generate devise user
      invoke  active_record
      create    db/migrate/20160325132848_devise_create_users
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml
      insert    app/models/user.rb
       route  devise_for :users

```

**Comment by lucasmazza** [comment]
Fixed in https://github.com/plataformatec/devise/commit/e57b672e90c661ed44aafa28f9fd37242fb76026, please update Devise to `3.2.3` or greater.
