### ISSUE TITLE
nginx host name+devise redirect uri

### ISSUE THREAD

**Issue by ror6ax** [plataformatec/devise#4011]
My rails app is served by nginx. The location name in nginx is `backend`.

My login uri ends up being `redirect_uri=http%3A%2F%2Fbackend%2Fusers%2Fauth%2Ffacebook%2Fcallback` which is obviously not matching my site's URL in whitelisted urls. 

There has to be some config option for setting this.
Is there one?

**Comment by lucasmazza** [comment]
The probable cause for this is bad nginx configuration, where it doesn't set the real host when proxying the request back to your Rails app. Setting it through `proxy_set_header Host $host` might fix it, like in the following config snippet:

```
upstream backend {
  server 127.0.0.1:5000;
}

server {
  server_name foobar.com;

  location / {
    proxy_set_header Host $host; # <-- Add this
    proxy_pass http://backend;
  }
}
```

Closing this as it isn't a real issue with Devise.
