### ISSUE TITLE
Change your password (email issue)

### ISSUE THREAD

**Issue by EkoZape** [plataformatec/devise#4012]
I have put the link to let user change their password, and i have try to change the email to an existing email in the database and that work. So, i have two same email in the database, and the authentification was with email. How i can disable email change with Devise to avoid duplicate email?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by EkoZape** [comment]
This is an issue in my mind. If user can change their email for an existing email in the database, that make two duplicate email in the database.
