### ISSUE TITLE
Rspec: User is authenticated but the request is redirected

### ISSUE THREAD

**Issue by mttn** [plataformatec/devise#4015]
Hi I have an issue with the following spec(both tests are failing). 

```ruby
let(:assigned_post) { assigns(:post) }

describe 'GET #new' do
  before { get :new }

  context 'authenticated', login_user do

    it 'assigns a instance of post' do
      expect(assigned_post).to be_a_kind_of Post
    end
      
    it { is_expected.to render_template :new }

  end
end
```

After debugging I can confirm that the user is logged in:

```ruby
subject.current_user
=> #<User:0x007ffac0cf4c80 ...>

subject.user_signed_in?
=> true
```

But the request will redirect to the the new user session path.

```ruby
expect(subject).to redirect_to new_user_session_path
=> true
```

With manual sign in to the user interface - everything is working as expected. So I think I run a test env problem
Is this known by you guys?

Some additional foo:
```ruby
module ControllerMacros
  def login_user
    before(:each) do
      @request.env["devise.mapping"] = Devise.mappings[:user]
      sign_in FactoryGirl.create(:user)
    end
  end
end
```

```ruby
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @post = Post.new
  end
end
```

**Comment by ulissesalmeida** [comment]
@mttn Hi! I think you can't use `login_user` in rspec `context`. [Look](http://www.rubydoc.info/gems/rspec-core/RSpec/Core/ExampleGroup#context-class_method).

Your `before` is doing a `get` before the login happens.

The `login_user` should be in your test example. For example, you do something like this:

```ruby
it 'assigns an instance of post' do
   login_user
   get :new
   expect(assigned_post).to be_a_kind_of Post
 end
```

I'm closing this issue. Feel free to open if you can reproduce that is a Devise error.

Best

**Comment by mttn** [comment]
This was not the problem - I can use `login_user` in rspec `context`. There was a runtime issue in my local env.
