### ISSUE TITLE
OmniAuth - Validate email only without provider

### ISSUE THREAD

**Issue by personstays** [plataformatec/devise#4018]
Hi, I have a problem with validating the duplicate email address. With OmniAuth, it always include provider with email. I checked my console and saw this:
`SELECT COUNT(*) FROM "users" WHERE "users"."provider" = $1 AND "users"."email" = $2  [["provider", "email"], ["email", "xxxxx@gmail.com"]]`

What I want is to exclude provider:
`SELECT COUNT(*) FROM "users" WHERE "users"."email" = $1  [["email", "xxxxx@gmail.com"]]`

My condition is that I logged in with Facebook (OmniAuth) first. Then I tried to sign up with email address: xxxxx@gmail.com and password: xxxxxxxxxx. With above query, it passed the validation since in my db the provider is "facebook" not "email". And I got this error: "ERROR: duplicate key value violates unique constraint"

Thanks!

**Comment by josevalim** [comment]
you need to change your DB constraints then to consider unique the provider-email combo. In general,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
