### ISSUE TITLE
No logout routes unless module `database_authenticatable` is used

### ISSUE THREAD

**Issue by bdares** [plataformatec/devise#4020]
I want to use devise for user management, with only omniauth providers.  

If I remove the `database_authenticatable` module, I lose the `sign_out` route, and users cannot log out from my app.  

I think that `sign_out` should be provided as part of the base `devise`.

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by josevalim** [comment]
I believe we add the sign out in latest Devise versions. If not, it is easy to add your own.

**Comment by bdares** [comment]
Ruby: 2.3.0
Rails: 4.2.6
Devise: 3.5.6
Warden: 1.2.6

Repro Steps:

* `rails generate devise:install`
* `rails generate devise user`
* `rake db:migrate`
* `rake routes` and note `user_session` paths (including `sign_in` and `sign_out`)
* Change `User` model `devise` call param and remove `:database_authenticatable`
* `rake routes` and note that `user_session` paths are no longer present.

**Comment by iexus** [comment]
Can confirm I am experiencing the same problems. Routes are not created for my user if I remove database_authenticatable but am using my own custom auth. I have added my own routes for sign in/out however I get the error that I am missing session_path.

Not sure how the correct way is to get devise to generate these paths / helpers when not using database_authenticatable.

**Comment by z3ugma** [comment]
@artur-beljajev in this example, are you creating a custom model and a custom strategy in your local Rails app at `app/models/id_card_authenticatable`? `require`ing that model and strategy isn't working because the files aren't there on `devise (4.7.1)`

**Comment by artur-beljajev** [comment]
@z3ugma They are defined in the app itself https://github.com/internetee/registry/tree/master/lib/devise.
