### ISSUE TITLE
How to allow User account update even if not confirmed

### ISSUE THREAD

**Issue by Kumamon38** [plataformatec/devise#4024]
Hi,
Is there any way to allow User account update (email, username, password) without being confirmed yet? Devise/Warden responds with "You have to confirm your email address before continuing.". I want the user to be able to change the email if it was wrong, and resend the confirmation email.
I would add that I don't want to use allow_unconfirmed_access_for as it is not the point here.
Thanks for your suggestions :)

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
