### ISSUE TITLE
Devise routes not showing up in rails engine

### ISSUE THREAD

**Issue by JasonMannon** [plataformatec/devise#4026]
I’m having trouble using Devise with my Rails engine. 

I followed the devise wiki here [Devise Wiki](https://github.com/plataformatec/devise/wiki/How-To:-Use-devise-inside-a-mountable-engine) But my devise routes are not showing up.

 Here’s a gist of the code. https://gist.github.com/anonymous/f4619e18a09199e52ee58fdfeabc36a6

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
