### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by Rodrigora** [plataformatec/devise#4027]
Hey Guys!

I've created a new extension for devise, [devise-verifiable](https://github.com/Rodrigora/devise-verifiable).

I had to implement a sign up process which required a second step. In this step, user have to fill
some extra information and the app uses an 3rd-party service to verify his identity.

I think this module could be useful for other apps. Could you add it to extension list?

Thanks!

**Comment by josevalim** [comment]
Thank you Rodrigo. Which extensions list are you referring to?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Rodrigora** [comment]
This: https://github.com/plataformatec/devise/wiki/Extensions

I just saw that I have permission to edit it. Can I?

**Comment by josevalim** [comment]
Yes! Please do edit it (and close this issue once you do) :)

On Friday, April 8, 2016, Rodrigo <notifications@github.com> wrote:

> This: https://github.com/plataformatec/devise/wiki/Extensions
>
> I just saw that I have permission to edit it. Can I?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/devise/issues/4027#issuecomment-207128423>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
