### ISSUE TITLE
Registration Form with Nested Models

### ISSUE THREAD

**Issue by harshamv** [plataformatec/devise#4037]
I have the following models

    members(id, name, company_id)
    companies(id, name, ...)

Now when i signup using devise model - `members` i want to create a record in the `companies` model and update `company_id` in the `members` model.

Can i build the company in the signup for like below

    class Brands::Members::RegistrationsController < Devise::RegistrationsController
      before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    
      # GET /resource/sign_up
      def new
        build_resource({})
        resource.build_company
        respond_with self.resource
      end
    end

**Members Model**

    class Member < ActiveRecord::Base
      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable and :omniauthable
      devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable
    
      acts_as_paranoid
      attr_accessor :company_name
    
      # Associations
      belongs_to :company
    
      accepts_nested_attributes_for :company
    end

**Company Model**

    class Company < ActiveRecord::Base
      extend FriendlyId
      # friendly_id :name, use: :slugged
      acts_as_paranoid
    
      @company_type = %w(agency brand)
    
      # Associations
      has_many :members, dependent: :destroy
      has_many :brands, dependent: :destroy
    end

Signup Form

    <h2>Sign up</h2>
    
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
    
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, value: 'Harha MV' %>
      </div>
    
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, value: 'harsha@mink7.com' %>
      </div>
    
      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off", value: 'harsha' %>
      </div>
    
      <h4>Enter your company details</h4>
      <%= f.fields_for :company do |fc| %>
        <div class="field">
          <%= fc.label :name %><br />
          <%= fc.text_field :name, value: 'Mink7' %>
        </div>
    
      <% end %>
    
      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
    
    <%= render "brands/members/shared/links" %>

***Error***

    NoMethodError at /members
    
    undefined method `' for #<Company:0x007f99fc7e5638>
    
    method_missing
    activemodel (4.2.5.2) lib/active_model/attribute_methods.rb
    
        def method_missing(method, *args, &block)
          if respond_to_without_attributes?(method, true)
            super
          else
            match = match_attribute_method?(method.to_s)
            match ? attribute_missing(match, *args, &block) : super
          end
        end

**Comment by ulissesalmeida** [comment]
Hey @harshamv thank you for your report. But I can't see why this is a Devise issue.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Is important to give more information in evidence the error using Devise. You provide a sample an application or create a test case. You can read our [CONTRIBUTING](https://github.com/plataformatec/devise/blob/master/CONTRIBUTING.md) file to more information on how to report an issue.

I'm closing this issue, feel free to reopen when you have evidence that is a Devise issue.
