### ISSUE TITLE
Email only sign up!

### ISSUE THREAD

**Issue by aryalsan** [plataformatec/devise#4040]
I followed the steps as suggested for the Email only sign up!, Every thing works fine but after I click the confirmation email link, it doesn't render the #show view besides it flash the "Email confirmation successful message". Is this an error or the Bug....

**Comment by jgrant29** [comment]
I'm not sure what versions you are using, but I had a similar problem using Rails 4 and Devise 3.1+.  The solution lies within the [these instructions](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation).  But theres a bug, depending on what versions you are using, you'll need to combine a controllers.  

Here's a gist of my work around https://gist.github.com/jgrant29/35f3c4b26a084010150bd40aa3460a2d
