### ISSUE TITLE
Confirmable should always update its sent_at timestamp when sending a new token.

### ISSUE THREAD

**Issue by bsodmike** [plataformatec/devise#4042]
When requesting for confirmation instructions to be sent after the fact, I noticed `confirmation_sent_at` [wasn't being updated](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L234..L236), although a new token is generated as long as the confirmation period is still valid.

Given the naming of the `confirmation_sent_at`, this is somewhat misleading.  I also suggest a new token is issued for each request, but some may feel this could make it confusing for users?

```ruby
        # Generates a new random token for confirmation, and stores
        # the time this token is being generated in confirmation_sent_at
        def generate_confirmation_token           
          unless confirmation_period_expired? 
            raw, _ = Devise.token_generator.generate(self.class, :confirmation_token)
            self.confirmation_token = @raw_confirmation_token = raw
            self.confirmation_sent_at = Time.now.utc
          end
        end
```

or

```ruby
        # Generates a new random token for confirmation, and stores
        # the time this token is being generated in confirmation_sent_at
        def generate_confirmation_token
          if self.confirmation_token
            if !confirmation_period_expired?
              @raw_confirmation_token = self.confirmation_token
            else
              raw, _ = Devise.token_generator.generate(self.class, :confirmation_token)
              self.confirmation_token = @raw_confirmation_token = raw
            end
            self.confirmation_sent_at = Time.now.utc
          end
        end
```

Thoughts?

**Comment by josevalim** [comment]
@bsodmike yes, we agree it is poorly named but we cannot change its behaviour as it means someone would be able to always renew the token and use the website without ever confirming their account.

On the other hand, renaming the token would be cause of backwards incompatible changes and we don't think they are worth it. IIRC, this misconception is documented in the source code. Thank you!

**Comment by bsodmike** [comment]
@josevalim Oops! Having had a look through the source, I realise that `confirmation_sent_at` is critical for lots of Confirmable's mechanisms.

Apologies, as this issue was incorrectly titled - I should have instead proposed to add a new column `reconfirmation_instructions_sent_at`.  I was creating a spec to ensure that the reconfirmation mailer had been sent out and having not looked at the source completely I assumed (1) that once the reconfirmation instructions were sent, each time a new token would be generated and (2) the sent_at column would be updated each time.

Having pry'd in I realised both my assumptions were incorrect and instead took this approach,

```ruby
      scenario 'Requesting for confirmation instructions' do
        expect {
          visit '/admin'
          click_link "Didn't receive confirmation instructions?"

          fill_in 'Email', with: admin.email
          click_button 'Resend confirmation instructions'
        }.to change { ActionMailer::Base.deliveries.size }.by(1)
      end
```

If we were to add `reconfirmation_instructions_sent_at` it may also be worth adding `reconfirmation_instructions_sent_count`.
