### ISSUE TITLE
Documentation: Upgrading to 4.0

### ISSUE THREAD

**Issue by DannyBen** [plataformatec/devise#4047]
Hi,

I have just did `bundle update`, and got Devise 4, which caused my tests to fail - probably due to all the deprecation warnings that are displayed during the capybara tests, or something similar.

Although I can probably follow the instructions in the deprecation warnings / changelog - it would be beneficial to all I think if there was a wiki guide ([here](https://github.com/plataformatec/devise/wiki/How-Tos)) to describe upgrade steps to 4.x.

**Comment by ulissesalmeida** [comment]
@DannyBen This is a good idea. Please, let us know the steps you have done to upgrade to `4.0.x`. We can use this information to create the documentation. Feel free to start the documentation on the wiki too. Also if you know any blog post with a upgrade tutorial we can link there too. :)

**Comment by DannyBen** [comment]
Would love to help with the doc, only now I am still in the "need help" side of the fence. Current road block for me was outlined in #4048

**Comment by lucasmazza** [comment]
Closing this as #4048 was closed. Ideally the deprecations and changelong should be enough to help the 4.0 upgrade, but there are some integration/bad setup cases that we can't foresee and I rather deal with them through different issues (as we did with a few issues were found by other developers) and hopefully we can provide better warning and CHANGELOG steps for the next releases of Devise.

**Comment by DannyBen** [comment]
Fair enough, thanks a lot.
