### ISSUE TITLE
Devise 4: unkown colum 'password'

### ISSUE THREAD

**Issue by sepastian** [plataformatec/devise#4049]
After updating to Devise 4 just now, I can no longer do

`User.new(email: 'a@b.c', password: 'testtest', password_confirmation: 'testtest').save!`

The above line will fail, because column `password ` does not exist.

After switching back to `< 4`, everything works as expected.

What changed? This should be documented!

**Comment by ulissesalmeida** [comment]
@sepastian Devise 4 now support Rails 5 and method to track the attribute password changes was added.  Are you using Ruby on Rails? Which version of Rails are you using? I think it was a Rails bug that it tried to insert all non-persisted attributes on database. You may want to update your Rails minor version together.

**Comment by sepastian** [comment]
Thanks @ulissesalmeida!

I was using `rails-4.2.0` together with `devise-4.0.0`.

After updating to `rails-4.2.6`, everything works as expected, i.e. I again can do:

`User.new(email: 'a@b.c', password: 'testtest', password_confirmation: 'testtest').save!`
