### ISSUE TITLE
Editing layouts for specific actions is counter-intuitive

### ISSUE THREAD

**Issue by amingilani** [plataformatec/devise#4054]
If I want to currently chage the layout for `user/registrations#edit` to `dashboard`, I have to add this to the `config`:

```
config.to_prepare do
    Devise::SessionsController.layout proc{ |controller| action_name == 'edit' ? "dashboard"   : "application" }
end
```

This is counter-intuitive. The right way is to edit it like any other controller:

```
  def edit
    super
    render layout: 'dashboard'
  end
```
Which currently gives fails with `AbstractController::DoubleRenderError` because the super probably renders with default in the code. At the very least a helper function should be included to override the default.

**Comment by amingilani** [comment]
I found a better way, do this:

```
class User::RegistrationsController < Devise::RegistrationsController
  layout 'dashboard', only: [:edit]
  ...
end
```

Feel free to add this to the documentation! It's better than the methods described!

**Comment by ulissesalmeida** [comment]
@amingilani Thank you for the suggestion. Do you remember where did you see these other methods to change the layout?

**Comment by amingilani** [comment]
In the wiki.. sighh, I should've edited that directly. I just realized.

**Comment by amingilani** [comment]
Done, [here](https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts)

**Comment by ulissesalmeida** [comment]
@amingilani Awesome! ❤️ 💛 💙 💜 💚
