### ISSUE TITLE
Cannot keep session only in some ios safari browser

### ISSUE THREAD

**Issue by yoshi42662** [plataformatec/devise#4056]
## Overview

I'm using devise and having trouble with the session.
In my iPhone using safari browser, I can keep session even when closing the tab and terminate the safari app with double pushing home button and flip the safari app.

In the login page, remember me param is always set to be true in the hidden field and I have session kept even when I close the tab and terminate the app.

However I got a report that after logged in, some users cannot keep session when they close the tab and terminate safari app.

I need help and thanks for your tips.

**Comment by pranav7** [comment]
@yoshi42662 How did you fix this issue?

**Comment by yangez** [comment]
Yeah - we're getting this too. Anyone know of a fix for this?

**Comment by pranav7** [comment]
@yangez I was able to identify why this was happening for us. Since I had removed `remember_me` from the form, it wasn't being set while creating the session. A simple fix might be to hardcode it so that it's always true.

**Comment by akshay-soni** [comment]
@yogeshjain999 
You could try setting `expire_at` option in `Rails.application.config.session_store`. 
iOS safari does not save a session cookie on the persistent storage if there is no expiry date. iOS resets in-app cookies after 24hours and which lead to deletion of those which are without the expiry
