### ISSUE TITLE
where to set secret_key without tripping deprecation warnings

### ISSUE THREAD

**Issue by mcr** [plataformatec/devise#4059]
The devise secret_key should be set differently in development/test, and production, and I think that the production key should kept out of github.  So initializing it from config/environments/production.rb would seem to make sense, with that file being stored on production machines only via capistrano's mechanisms for doing this.

A naive method would add this to environments/*.rb:

    Devise.setup do |config|
      config.secret_key = 'something'
    end

this runs afoul of the deprecation warnings, since it sets up the configuration without all the things that later on are loaded from config/initializers/devise.rb.   Short of throwing in a require into initializers/devise.rb to load another file.

Is there some way to store this in config/secrets.yml, for instance?

**Comment by ulissesalmeida** [comment]
@mcr 
I think you can use env variable, for example:

```ruby
config.secret_key = ENV['DEVISE_SECRET_KEY']
```

Or you can take a look at the [Rails custom configuration](http://guides.rubyonrails.org/configuring.html#custom-configuration). There's awesome tips in how proper set your custom configurations. You can do something like this:

```ruby
config.secret_key = Rails.configuration.x.devise.secret_key
```

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
