### ISSUE TITLE
Asynchronous email job cannot find user

### ISSUE THREAD

**Issue by allenwq** [plataformatec/devise#4062]
I get an exception of 
`ActiveJob::DeserializationError:  Error while trying to deserialize arguments: Couldn't find User with 'id'=xxx` while trying to follow the README to let the devise send email asynchronously. 
https://github.com/plataformatec/devise#activejob-integration

I think this is because `send_on_create_confirmation_instructions` is called `after_create`, and emails are sent before user is persisted.

**Comment by betesh** [comment]
Duplicates #3550
