### ISSUE TITLE
4.0.1 -  private method `permit' called for #<Devise::ParameterSanitizer:...>

### ISSUE THREAD

**Issue by Bogadon** [plataformatec/devise#4065]
Have updated from 3.5 to 4.0.1, I began getting deprecation warnings:

> DEPRECATION WARNING: [Devise] Changing the sanitized parameters through "Devise::ParameterSanitizer#for(account_update) is deprecated and it will be removed from Devise 4.1.
> Please use the `permit` method:

But, after updating in line with the warning/API readme, I get:

> NoMethodError:
>        private method `permit' called for #<Devise::ParameterSanitizer:0x000000106111c8>
>        Did you mean?  print

**Comment by ulissesalmeida** [comment]
@Bogadon Thank you for the report. Could you show some use case example code? With the example, we have more information to know what's going on.

Maybe this section on [README](https://github.com/plataformatec/devise#strong-parameters) helps you.

**Comment by Bogadon** [comment]
I believe this was caused by an error on my part using the parallel test suite. 4.0.1 seems to work fine now.

Apologies.

**Comment by ulissesalmeida** [comment]
Thanks for the feedback!
