### ISSUE TITLE
Devise in seprated table

### ISSUE THREAD

**Issue by waghanza** [plataformatec/devise#4070]
Hi,

I'm using `rails` **5** (*beta4*).

I use an external database for `devise` => only ACL.

When I try to start my server , I have

~~~ruby
/home/xxxxx/.gem/ruby/gems/activerecord-5.0.0.beta4/lib/active_record/dynamic_matchers.rb:21:in `method_missing': undefined method `devise' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
~~~

Here is my **devise** model

~~~ruby
class User < ApplicationRecord
  establish_connection :acl
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end
~~~

I have this behavior only on **development** env.

Is anyone using an external database for `devise` ?

PS : This works on rails 4

**Comment by ulissesalmeida** [comment]
Thank you for your report.

Could you please provide more information?
Like for example: 
* Devise version

Will be even more helpful if you provide a sample application that reproduces the error.

Best

**Comment by waghanza** [comment]
I'm using **devise** `4.01`

**Comment by waghanza** [comment]
fixed, I have remove devise **initializer**

* just created a new rails app
* generated a new initializer
* copy it it my rails app directory
