### ISSUE TITLE
'Password can't be blank' error because the model has a 'password' column

### ISSUE THREAD

**Issue by echan00** [plataformatec/devise#4074]
I've been trying to debug this issue all day. I finally realized that devise keeps saying the password is blank because my User model has a 'password' field. I need to keep this password field because another web app also accesses this database. 

What do to?

`Started POST "/users" for ::1 at 2016-04-29 21:12:56 -0700
Processing by RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"qZwB3YFyeNtD94myhcQZtX/lZewiVPtZJ5veXid/GgW2ASh3LI1hcI/iBSeHvD2cat84E76SedCxL0hm3z2haw==", "user"=>{"email"=>"erik@rocketclub.co", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
   (0.2ms)  BEGIN
  User Exists (0.4ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'erik@rocketclub.co' LIMIT 1
   (0.2ms)  ROLLBACK`

**Comment by ulissesalmeida** [comment]
@echan00 You may not want to use the `validatable` feature and do your custom validations depending on the context. There are some alternatives like conditional validations of Rails or forms objects.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. You can read our [CONTRIBUTING](https://github.com/plataformatec/devise/blob/master/CONTRIBUTING.md) file to more information on how to report an issue.
