### ISSUE TITLE
How to redirect back to custom sign up page with resources when error occur.

### ISSUE THREAD

**Issue by samsoft00** [plataformatec/devise#4077]
I've been trying to solve this for couples of days now but no head way.. i've custom sign up page for both Vendor and Couple, see below
```
  devise_for :users, :controllers => { registrations: "registrations" }
  devise_scope :user do
    match 'vendor/sign_up', to: 'registrations#new', user: {user_type: 'vendor'}, via: [:get]
    match 'wedding/sign_up', to: 'wedding/registrations#new', user: {user_type: 'wedding'}, via: [:get]
  end
```
So, when user attempt to sign up on whatever page and when error occur, i want the page to redirect back to requested page with resources. i try to manipulate it but it doesn't work
```
  def create
    build_resource(sign_up_params)
    
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource, :location => wedding_sign_up_path
    end
  end
```
I'm new to ruby on rails, please help on how to achieve this.
Thanks

**Comment by ulissesalmeida** [comment]
If you want just a `redirect`, you may want to replace `respond_with` in your code for `redirect_to` helper of Rails.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. You can read our [CONTRIBUTING](https://github.com/plataformatec/devise/blob/master/CONTRIBUTING.md) file to more information on how to report an issue.
