### ISSUE TITLE
Rails 4 testing controller spec ,devise helper sign_in doesn't work

### ISSUE THREAD

**Issue by violentr** [plataformatec/devise#4082]
I have Rails 4.2.6, rspec 3.3.0, devise 3.5.8 and i have trouble to test my controller specs always getting error saying ("expected the response to have a success status code (2xx) but it was 401") Later when i try different spec I am always getting failure message ("Your account is not enabled yet !"), any ideas ?, any help much appreciated ,
Please check details on [StackOverflow](http://stackoverflow.com/questions/37008290/rails-4-testing-controller-spec-devise-helper-sign-in-doesnt-work)

**Comment by ulissesalmeida** [comment]
Hi @violentr ! I've tried to find any message code on Devise related to `Your account is not enabled yet` and didn't find. I think this message may be related with your application code.

I think it's not a Devise issue, the StackOverflow question you have created is the proper place. Feel free to reopen if you find a evidence that is a Devise issue, providing a sample application or a test case that reproduces the problem.
