### ISSUE TITLE
require_no_authentication does not use local set in prepend_before_action in ApplicationController

### ISSUE THREAD

**Issue by ploomans** [plataformatec/devise#4084]
I set the language of my rails app in the ApplicationController via prepend_before_action :set_locale

However, the devise messages don't use the local languages set in the ApplicationController because Devise's SessionController is using prepend_before_filter :require_no_authentication, :only => [ :new, :create ]

The require_no_authentication will be executed before :set_locale that I put as prepend_before_action in ApplicationController because SessionController inherit from ApplicationController

Right now I have no idea how I should try to overriding require_no_authentication method without changing the devise code.

Any suggestions on how to make require_no_authentication use a local I can dynamically set in the ApplicationController?

I see this is a bug, because the I18n.t function in require_no_authentication will not use the correct local. However I don't see an easy clean/quick workaround and therefore can't propose myself adjustments to the Devise code

**Comment by lucasmazza** [comment]
You can override `require_no_authentication` on your controllers and call your `set_locale` method before calling `super`.

```ruby
def require_no_authentication
  set_locale
  super
end
```
