### ISSUE TITLE
undefined method `to_adapter' when using Devise.token_generator.generate(@user, :reset_password_token)

### ISSUE THREAD

**Issue by BobWalsh** [plataformatec/devise#4088]
devise 4.1.0, rails 4.2.4, ruby 2.2.1"

Need to generate a reset token to send to an external api used to deliver emails to our users. Here's the code:

```
@user = current_user
    raw_token, hashed_token = Devise.token_generator.generate(@user, :reset_password_token)
    @user.reset_password_token = hashed_token
@user.reset_password_sent_at = Time.now.utc
    @user.save(validate: false)
```

and the error hits on the line 
```
raw_token, hashed_token = Devise.token_generator.generate(@user, :reset_password_token)
NoMethodError: undefined method `to_adapter' for #<User:0x007fafa9771b30>
````

What am I doing wrong to generate a valid reset token?

**Comment by lucasmazza** [comment]
`TokenGenerator#generate` expects a class (`User`) and not an instance (`@user`) as its first argument.

 Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
