### ISSUE TITLE
Conditional Route on sign_out using Devise with Rails

### ISSUE THREAD

**Issue by Faisal-nfl** [plataformatec/devise#4090]
I am working on an app in which there is a model **User** with roles **member** and **Admin**.

As per requirement, I have to made two separate login pages for Admin and Member.

`with http://localhost:3000/admin/admin_login`

it goes to admin login page and with

`http://localhost:3000/users/sign_in`

it goes to member login page. Just after login I route them according to their roles to Admin panel or simple website for members.

But at time of logout both goes to  `http://localhost:3000`

but I want admin to go to `http://localhost:3000/admin/admin_login`, 
while `http://localhost:3000` is fine for member's logout.

Is there a way to see User's Role at time of Sign_out and route them accordingly.

**Comment by lucasmazza** [comment]
Currently `after_sign_out_path_for` receives only the `resource_name` and not the signed out `resource` object, so looks like this isn't easily possible now :( 

Any patches to make it support the resource instance instead (thus making the method flexible enough for scenarios like that) will be much appreciated.

**Comment by Faisal-nfl** [comment]
May I Override sign_out of Devise and than do it.
Is that possible?

**Comment by lucasmazza** [comment]
Yeah, that could work if you load the resource and follow through the original logic.

**Comment by Faisal-nfl** [comment]
Another thing, Does Devise clear all sessions on Sign_out?
