### ISSUE TITLE
"Invalid Login or password." is grammatically incorrect

### ISSUE THREAD

**Issue by connorshea** [plataformatec/devise#4095]
This was changed in PR #4014 and released with 4.1.0.

With an incorrect password the user sees "Invalid Login or password." "Login" shouldn't be capitalized in this case, as it's not a proper noun and isn't at the beginning of the sentence.

This is because of the following i18n string:

``` yaml
invalid: "Invalid %{authentication_keys} or password."
```
#4014 "humanized" the `authentication_keys` variable, thus causing this issue.

**Comment by connorshea** [comment]
I'm not sure how this should be resolved, different languages will have different requirements with regards to capitalization.

**Comment by ulissesalmeida** [comment]
Before `4.1` the keys was not "humanized", and we have something like `email or password`.
With the humanized version we have now something like `E-mail or password`.
If we keep this way, the `password` is not consistent with `E-mail`.
I think we should provide a nice default for the english language.

For other idioms, they can simply change the entire message of the `yml` file of the specific language with their specific rules. Without rely on `authentication_keys`.

```
invalid: "The idiom custom message here"
```

**Comment by connorshea** [comment]
@ulissesalmeida I think I'm not following, are you saying we should not humanize them for English, or we should replace it with our own message that doesn't include `authentication_keys`?

**Comment by ulissesalmeida** [comment]
@connorshea I think we should humanize them for English since it is the Devise default(downcasing the keys). For other languages that do not follow this default, I think they should change in their application for a proper translation that's doesn't include the `authentication_keys`.

**Comment by crawfoal** [comment]
@ulissesalmeida Are there still plans to change this back to using all lowercase (but keeping the humanize change)?

**Comment by bernardogalindo** [comment]
I think humanize authentication keys is good for English but why `password` is not part of ?

**Comment by tegon** [comment]
@crawfoal @bernardogalindo We can follow with the downcase solution (keeping the humazine attribute). If someone is willing to open a PR for this, I'd be happy to accept it.

**Comment by tegon** [comment]
Closed via https://github.com/plataformatec/devise/pull/4834
