### ISSUE TITLE
Looking for a feature and how it works

### ISSUE THREAD

**Issue by bsylvain** [plataformatec/devise#4097]
I have found the following message in an issue : 
https://github.com/plataformatec/devise/issues/1285#issuecomment-2530297

I would like to be able to have two different controllers for the same user model (normal login and doorkeeper login) but I do not know how this feature work. Where can I find explanations about it, or an example?

**Comment by ulissesalmeida** [comment]
@bsylvain You may want to take a look at [devise-doorkeeper](https://github.com/betterup/devise-doorkeeper) gem or the [doorkeeper devise wki](https://github.com/doorkeeper-gem/doorkeeper/wiki/Example-Applications).

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
