### ISSUE TITLE
Edit password form in non-devise view

### ISSUE THREAD

**Issue by chrisvel** [plataformatec/devise#4102]
I want to be able to "embed" or render the edit password template into another page and be able to change my password there. The problem is that the next step of the edit process, takes me to the devise registrations edit view instead of staying in the page. Is something like this possible at all?

**Comment by jyunderwood** [comment]
You might want to look in to creating a custom controller and action. Check out solution #3 in this wiki page: https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password

**Comment by ulissesalmeida** [comment]
Thank you @jyunderwood 

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
