### ISSUE TITLE
sign_in process is unclear

### ISSUE THREAD

**Issue by Sashkan** [plataformatec/devise#4107]
Hi,

I'm implementing a token system to allow a user to validate its account. Basically, all it does it send a mail with a link to a welcome page, where my user can set his password. 

On form submission, 

- the new password is set (works fine)
- user gets signed in (seems to be working)
- he gets redirected to his profile page (doesn't work)

Code is pretty straightforward : 
```
    puts sign_in :user, @user
    redirect_to brand_path(@user.profile)
```

For some reason, the redirection occurs, but my user gets signed out in the process (instead of getting to the profile page, Pundit raises an error, saying that I have no current_user)

Did I miss something ?

**Comment by ulissesalmeida** [comment]
I'm not sure if it is a Devise issue.

Could you please provide more information?
Like for example: 
* Rails version
* Devise version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application or a test case that reproduces the error.

Best

**Comment by ulissesalmeida** [comment]
I'm closing this issue. Feel free to reopen when you have more information in how to reproduce the problem. You can create Devise test case or provide a sample application that reproduces the error.
