### ISSUE TITLE
uninitialized constant ActionController::API::RackDelegation

### ISSUE THREAD

**Issue by leonardofaria** [plataformatec/devise#4108]
I'm setting up a rails-api project using Devise for authentication and I got stuck here:

	rails-api g devise:install
	/Users/leonardo/.rvm/gems/ruby-2.2.2/gems/rails-api-0.4.0/lib/rails-api/action_controller/api.rb:131:in `<class:API>': uninitialized constant ActionController::API::RackDelegation (NameError)
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/rails-api-0.4.0/lib/rails-api/action_controller/api.rb:85:in `<module:ActionController>'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/rails-api-0.4.0/lib/rails-api/action_controller/api.rb:5:in `<top (required)>'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/rails-api-0.4.0/lib/rails-api.rb:3:in `require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/rails-api-0.4.0/lib/rails-api.rb:3:in `<top (required)>'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
		from /Users/leonardo/Dropbox/Sites/petlog-api/config/application.rb:7:in `<top (required)>'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
		from /Users/leonardo/.rvm/gems/ruby-2.2.2/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
		from /Users/leonardo/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /Users/leonardo/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from -e:1:in `<main>'

I'm currently using Rails 5.0.0.rc1 and my Devise version is 4.1.0 (`gem 'devise', '~> 4.0'`)

Any suggestions here? 

Thanks

**Comment by lucasmazza** [comment]
From your backtrace, the error is coming from `rails-api` and not Devise.

**Comment by vedant1811** [comment]
@leonardofaria I am getting the same error: https://github.com/rails-api/rails-api/issues/218
How did you fix yours?

**Comment by leonardofaria** [comment]
@vedant1811 i was using an outdated rails-api version.
