### ISSUE TITLE
Extra checks for devise sign in, based on user provided params

### ISSUE THREAD

**Issue by divya1c** [plataformatec/devise#4109]
Hi! 

I have a relation between a user and a district model, as in, every user belongs to a district. So, every user table contains a district_id. During login, i want the user to also input the district name and check that the district name provided by the user tallies with user.district.district_name.

I am using devise for authentication. I know that I can add an extra column to my user table called district_name and add that column to the authentication keys. Is there any other way of doing this without having to add this column?

Thanks!

**Comment by divya1c** [comment]
While researching about this, I came across custom strategies. But, I understand that only any one of the strategies have to be valid for the user to be able to login. But, I need both my custom strategy (checking district name) and database autheticable (for checking password) to pass for authentication. Is there a way of doing that? Or should I make a custom strategy and copy database authenticable along with my strategy into it? Thanks!

**Comment by ulissesalmeida** [comment]
Hi! I think both options you've mentioned are valid. There's another possibility, you can customize the `find_for_authentication` in your [model](https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L241). You also you may need setup the [request keys](https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L18) and permit the new params on the controller.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
