### ISSUE TITLE
login field systematically autofilled by browsers with email

### ISSUE THREAD

**Issue by arnaudbouffard** [plataformatec/devise#4110]
Our www.covoitici.fr webapp uses (French) mobile phone numbers (06 XX XX XX XX or 07 XX XX XX XX) as main login for our users.

We have client-side JS which makes typing anything else thant numbers in the signin login field impossible. However browser autofills manage to fill in this field with emails before ou validation JS kicks in, and shoots the http request to our server.

Any way devise could indicate browser autofills that main login is not an email?

**Comment by ulissesalmeida** [comment]
I think what you need is configure your form views, take a look a this [guide](https://github.com/plataformatec/devise#configuring-views).

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
