### ISSUE TITLE
PG undefinedtable error relation users does not exist

### ISSUE THREAD

**Issue by MCodyB** [plataformatec/devise#4111]
rails 4.2, devise 3.4.1

When running `rake db:schema:load`
I got this error
`ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist`
I figured out a painless workaround, which I wrote in this SO answer:

http://stackoverflow.com/a/37219181/2167965

>I know specifically omniauthable is a problem, but maybe others as well.
For me, what was happening is that devise is reading the User model to see what you have as arguments for devise (the class method i.e. devise :database_authenticatable, :registerable #etc)
But, it will read the whole file and if this isn't a new project it might get tripped up by other class methods relying on other things (in my case it was the friendly_id gem, and then an alias_method
The answer was to comment out the User model except for the devise lines(s) * and rake db:schema:load should run fine.
   * otherwise I got this error:
    ArgumentError: Mapping omniauth_callbacks on a resource that is not omniauthable Please add devise :omniauthable to the User model

It's not that complicated so I think it contains all the info needed to reproduce

**Comment by ulissesalmeida** [comment]
Devise `3.4.1` is not longer supported anymore. Could you please try with Devise `3.5` or `4.1` please?

**Comment by MCodyB** [comment]
Yeah, just tried both (3.5.9, 4.1.1) and both failed in exactly the same way as before.

**Comment by ulissesalmeida** [comment]
@MCodyB Thanks for the feedback.
