### ISSUE TITLE
Hello, i've an issue with RackDelegation.

### ISSUE THREAD

**Issue by nmiloserdov** [plataformatec/devise#4113]
I'm using rails 5 in my project. When i added devise i'd an notification `DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead.` It's shows when i use commands like "rake", "rails". The main error is happened when i'm starting rails server. Below the trace of error. Thank you.

> => Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:9:in `<class:FailureApp>': uninitialized constant ActionController::RackDelegation (NameError)
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:8:in `<module:Devise>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/failure_app.rb:3:in `<top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:122:in `default_failure_app'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:67:in `initialize'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `new'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `add_mapping'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:238:in `block in devise_for'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `devise_for'
	from /Users/nick/work/bb-parser/config/routes.rb:5:in `block in <top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/nick/work/bb-parser/config/routes.rb:3:in `<top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `run'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application.rb:350:in `initialize!'
	from /Users/nick/work/bb-parser/config/environment.rb:5:in `<top (required)>'
	from /Users/nick/work/bb-parser/config.ru:3:in `block in <main>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /Users/nick/work/bb-parser/config.ru:in `new'
	from /Users/nick/work/bb-parser/config.ru:in `<main>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:58:in `app'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:136:in `log_to_stdout'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:76:in `start'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/nick/work/bb-parser/bin/rails:9:in `require'
	from /Users/nick/work/bb-parser/bin/rails:9:in `<top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nick/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nick/work/bb-parser/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by ulissesalmeida** [comment]
@nmiloserdov Thank you for your report.

Could you please provide more information?
Like for example: 
* Devise version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application that reproduces the error.

Best

**Comment by nmiloserdov** [comment]
@ulissesalmeida Of course.
My gem file contains:
`gem 'rails', '>= 5.0.0.beta3', '< 5.1'
 gem 'devise'`.
I'd run `$ bundle`, `$ rails generate devise:install`, when i'd create the model by command `$ rails generate devise adminUser`, after i run '$ bundle exec rake db:migrate`, and this is throw the error `uninitialized constant ActionController::RackDelegation` about my row `devise_for :admin_users` in `config/routes.rb`. I decided to cheat :) and comment this line, and run the migration again. After these actions i've this error.

**Comment by nmiloserdov** [comment]
My solution is add this line in Gemfile:
 `gem 'devise', github: 'twalpole/devise', branch: 'rails5'`
It's add devise support for rails 5.
Thank you.

**Comment by ulissesalmeida** [comment]
@nmiloserdov Wow :scream:. I think Devise 4.1.1 should be Rails 5 compatible. Could you try this Devise version?

**Comment by nmiloserdov** [comment]
@ulissesalmeida I'm did not notice, that *twalpole* is foreign repository :) 
I update my Gemfile with *gem 'devise', '4.1.1'*, and it works fine, thank you.
