### ISSUE TITLE
Soft Delete and proper error handling

### ISSUE THREAD

**Issue by tiagoovieira** [plataformatec/devise#4114]
I followed your [guide to soft delete users](https://github.com/plataformatec/devise/wiki/How-to:-Soft-delete-a-user-when-user-deletes-account), but it seems to me that it reduces the `User.count`, is that correct?

My problem is when a user creates and then deletes an account, and then a totally different user, tries to create an account with the same email as the user with the deleted account, it returns a 500 error, with an error `ActiveRecord::RecordNotUnique PG::UniqueViolation` 

How do I rescue this error and present a error message like "Email is already taken"?

**Comment by ulissesalmeida** [comment]
For the problem you've described I think you can do this options:

* One option is to remove the database unique constraint. Maybe you have put a unique constraint on the `email` column, but you now you have the possibility to have two records at the same time on the table, one soft deleted and a new fresh one.
* Rewrite the sign-up controller action, to permit a user reactivated a soft deleted account. You can keep the database constraint and add your code of reactivation.

As you can see, each approach depends on of your application rules. I'm sure there're others ways you can explore.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by tiagoovieira** [comment]
@ulissesalmeida thnks for the feedback, I opened up a question in [stackoverflow](http://stackoverflow.com/questions/37173672/devise-omniauth-soft-delete) but didn't got answers yet and I was hoping to see a lot of examples and cases similar to mine
