### ISSUE TITLE
Validate additional field when login

### ISSUE THREAD

**Issue by emmanuelmillionaer** [plataformatec/devise#4116]
In the session controller, I also permit passing a code in the params:

```ruby
before_filter :configure_permitted_parameters

def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in).push(:code)
end
```

When somebody tries to login I would like to check for the correctness of the code. 
And redirect him back with errors if its not correct. I tried to yield `create` with:

```ruby
def create
  super do |resource|
     resource.errors[:base] << "You must have a Sunday in the time range!" if params["user"]["code"] != "test_code"
  end
end
```

It seems not to work, because the `yield` takes place after the user is logged in https://github.com/plataformatec/devise/blob/aa3f64976fd886b25e40dfc6043aa7b151145f94/app/controllers/devise/sessions_controller.rb#L20 

<b>How can I check if the `code` is correct, and only if the code is correct, sign in the user? Thanks!</b>

**Comment by ulissesalmeida** [comment]
@emmanuelmillionaer 

I think you should do something like:

```ruby

def create
  if params["user"]["code"] != "test_code"
    resource.errors[:base] << "You must have a Sunday in the time range!"
    # maybe a redirect or render a failure page
  else
    super
  end
end
```

This is jus an example, you can customize to your application needs. Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
