### ISSUE TITLE
How To: Set up devise as a single user system

### ISSUE THREAD

**Issue by jtlindsey** [plataformatec/devise#4120]
Hello, I just followed the instructions to make my site a single user system:
https://github.com/plataformatec/devise/wiki/How-To:-Set-up-devise-as-a-single-user-system

But I can't edit my registration information anymore (like my email, or display name) from the edit_user_registration_path link. It redirects home.

**Comment by jtlindsey** [comment]
Note: In the meantime, I've configured the user edit action to allow a user to edit their information. It looks a little hackish. The commit for the changes I made are here: https://github.com/jtlindsey/EasySWFSender/commit/a9ccf926a5710fadafba863e8f10c350a3dd867f

**Comment by ulissesalmeida** [comment]
@jtlindsey Maybe the `before_action :one_user_registered?` is affecting all the registrations actions.

I've updated the wiki, would be better just filter only the create and new actions. For example:

```
 before_action :one_user_registered?, only: [:new, :create]
```
