### ISSUE TITLE
Clarify Rails version requirement in change-log

### ISSUE THREAD

**Issue by paulmenzel** [plataformatec/devise#4122]
The `README` says that only Rails 4.2 and onwards are supported since Devise 4.0.

> Devise 4.0 works with Rails 4.2 onwards.

Reading `CHANGELOG.md`, I can only find that Rails 4.0 is not supported anymore.

> Devise no longer supports Rails 3.2 and 4.0.

Could you please clarify if Rails 4.1 is supported by Devise 4.0?

**Comment by lucasmazza** [comment]
4.1 is still supported - I've fixed the README on 53f6785, thanks.
