### ISSUE TITLE
deprecation error with devise_token_auth

### ISSUE THREAD

**Issue by yovasx2** [plataformatec/devise#4123]
I'm using Devise Token Auth gem and, everytime I run my test suite in Rails 4.2.5 app, I'm getting this deprecation warning from Devise:

DEPRECATION WARNING: [Devise] config.email_regexp will have a new default on Devise 4.1 To keep the current behavior please set in your config/initializers/devise.rb the following:

```
Devise.setup do |config|
   config.email_regexp = /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/
end
```

If you want to use the new default:

```
Devise.setup do |config|
   config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
end
```

(called from block in tsort_each at /usr/local/lib/ruby/2.2.0/tsort.rb:226)
I've already added config/initializers/devise.rb file manually and have set email_regex as suggested by the message above, but the annoying message persists.

How can I disable this message?

**Comment by ulissesalmeida** [comment]
@yovasx2 That's weird, are you calling `Devise.setup` in others places of your application? Maybe some gem are you using? If you update your Devise to `4.1.1` the message will stop anyway.

**Comment by yovasx2** [comment]
i just send the message to log as I answered [here](http://stackoverflow.com/questions/37240629/how-to-get-rid-of-email-regex-message-on-devise)

**Comment by diiq** [comment]
I had the same problem. 

(Context: brand-spankin' new rails (4.2.6) app, only a few hours old; everything is still very much default.)

I wouldn't suggest sending all deprecation warnings to the log, as @yovasx2 suggests. That seems like a bad solution -- you might miss other, important deprecations :)

The bleeding-edge of devise_token_auth gem supports Devise 4.1 as of a few weeks ago. Others with this issue might also try changing their Gemfile to read

```
gem "devise_token_auth", github: "lynndylanhurley/devise_token_auth"
dem "devise", "~>4.1.1"
```

until the next release of devise_token_auth comes out.

--------

Regarding the actual bug: 

It appears that the deprecation warning is triggered before any initializers have been loaded or run -- if I put a print statement at the top of `config/initializers/devise.rb`, it doesn't appear until after the warning.

**Comment by evertonts** [comment]
yovasx2  Any news on this issue?
