### ISSUE TITLE
Connection reset by peer - SSL_connect during reset password

### ISSUE THREAD

**Issue by hendranata** [plataformatec/devise#4124]
i am not really sure what happen with my code.
when i do reset password from devise,
it is showing us "something when wrong" in the production mode.

here is the production log:

Devise::Mailer#reset_password_instructions: processed outbound mail in 93.9ms
I, [2016-05-20T23:32:34.202065 #20986]  INFO -- :
Sent mail to hendranatas@yahoo.com (1066.0ms)
D, [2016-05-20T23:32:34.202166 #20986] DEBUG -- : Date: Fri, 20 May 2016 23:32:33 +0700^M
From: please-change-me-at-config-initializers-devise@example.com^M
Reply-To: please-change-me-at-config-initializers-devise@example.com^M
To: hendranatas@yahoo.com^M
Message-ID: <573f3c21220a9_51fa806cf4449f7@globalway-HP-Pro-3330-MT.mail>^M
Subject: Instruksi penggantian password^M
Mime-Version: 1.0^M
Content-Type: text/html;^M
 charset=UTF-8^M
Content-Transfer-Encoding: base64^M
^M
LS0tLS0tLS0tLS0tLS0tLS0tLS0tIEJBSEFTQSBJTkRPTkVTSUEgLS0tLS0t^M
LS0tLS0tLS0tLS0tLS0tLQoKPHA+SGFsbyBoZW5kcmFuYXRhc0B5YWhvby5j^M
b20hPC9wPgoKPHA+U2VzZW9yYW5nIHRlbGFoIG1lbWludGEgdW50dWsgcGVy^M
Z2FudGlhbiBwYXNzd29yZC4gQW5kYSBkYXBhdCBtZWxha3VrYW55YSBkZW5n^M
YW4ga2xpayBsaW5rIGJlcmlrdXQgaW5pLjwvcD4KCjxwPjxhIGhyZWY9Imh0^M
dHA6Ly8xODAuMjUwLjE2OS4xNzAvdXNlcnMvcGFzc3dvcmQvZWRpdD9yZXNl^M
dF9wYXNzd29yZF90b2tlbj1qdGFyUVFicHVydko4UldMTm5zeiI+UnViYWgg^M
UGFzc3dvcmQgU2F5YTwvYT48L3A+Cgo8cD5KaWthIGFuZGEgdGlkYWsgbWVt^M
aW50YSBwZXJ1YmFoYW4gcGFzc3dvcmQsIHNpbGFoa2FuIGFiYWlrYW4gZW1h^M
aWwgaW5pLjwvcD4KPHA+UGFzc3dvcmQgYW5kYSB0aWRhayBha2FuIGJlcnVi^M
YWggc2VsYW1hIGJlbHVtIGFuZGEgcmVzZXQgZGVuZ2FuIGNhcmEga2xpayBs^M
aW5rIGRpYXRhcy48L3A+CjxwPlRlcmltYWthc2loPC9wPgoKLS0tLS0tLS0t^M
LS0tLS0tLS0tLS0tLS0tLS0gQ0hJTkVTRSAtLS0tLS0tLS0tLS0tLS0tLS0t^M
LS0tLS0tLS0KCjxwPuaCqOWlvSBoZW5kcmFuYXRhc0B5YWhvby5jb20hPC9w^M
PgoKPHA+5pyJ5Lq655Sz6KuL5L+u5pS55a+G56K8LiDoq4vmjInku6XkuIvn^M
moTpgKPntZDntrLlnYA6PC9wPgoKPHA+PGEgaHJlZj0iaHR0cDovLzE4MC4y^M
NTAuMTY5LjE3MC91c2Vycy9wYXNzd29yZC9lZGl0P3Jlc2V0X3Bhc3N3b3Jk^M
X3Rva2VuPWp0YXJRUWJwdXJ2SjhSV0xObnN6Ij7kv67mlLnmiJHnmoTlr4bn^M
orw8L2E+PC9wPgoKPHA+5aaC5p6c5oKo5rKS5pyJ6KaB5rGC5L+u5pS55a+G^M
56K8LCDoq4vmgqjlv73nlaXmraTkv6EuPC9wPgoKPHA+5Zyo5oKo6YKE5rKS^M
6bue5Lul5LiK57ay5Z2ALCDmgqjnmoTlr4bnorzkuI3mnIPooqvkv67mlLkg^M
LiDorJ3orJ08L3A+^M

I, [2016-05-20T23:32:34.202397 #20986]  INFO -- : Completed 500 Internal Server Error in 1360ms (ActiveRecord: 7.1ms)
F, [2016-05-20T23:32:34.203734 #20986] FATAL -- :
Errno::ECONNRESET (Connection reset by peer - SSL_connect):
  /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:587:in `connect'
  /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:587:in `tlsconnect'
  /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:564:in `do_start'
  /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
  mail (2.6.3) lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
  mail (2.6.3) lib/mail/message.rb:2141:in `do_delivery'

anyone can help? i am using gmail smtp and it works in my local computer
but it does not working in server.

i have tried production mode in my local computer also work well..

**Comment by mariowise** [comment]
What is that **please-change-me-at-config-initializers-devise@example.com** doing there? I believe you need to configure your **config/initializers/devise.rb** with the propper mail address.

    config.mailer_sender = 'you-real-email@gmail.com'

**Comment by ulissesalmeida** [comment]
@mariowise Thank you! ❤️ 

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by eagleeye2020** [comment]
Did setting the config.mailer_sender help?

Couldn't we set a better error message?
