### ISSUE TITLE
Devise relation with other application

### ISSUE THREAD

**Issue by alex-lairan** [plataformatec/devise#4128]
Hi everyone ! 

I work on a web application who use an existing database used by 2 other applications, one on Java the other on PHP. 

And I want to know how to make Letruk working with this database without edit both applications.

If this needed to edit the database, what I need to do with my two others applications?

Thank for you're help ! :)

**Comment by shakycode** [comment]
Hi, can you provide a bit more context as to what you're trying to accomplish?

**Comment by alex-lairan** [comment]
I have an database for multiple application, one use PHP, the second use Java, but, how I can add a new application on Ruby on Rails with Devise without modify the PHP and Java application?

**Comment by alex-lairan** [comment]
It's work with different password. 

But how to set Devise to use especially MD5 with the environment key?

**Comment by lucasmazza** [comment]
@alex-lairan if you want to make Devise encrypt passwords using the same logic as your existing applications, you should take a look on https://github.com/plataformatec/devise-encryptable and probably implement your own encryptor class using your application(s) specific logic.
