### ISSUE TITLE
Redirect loop after resetting password

### ISSUE THREAD

**Issue by chintanparikh** [plataformatec/devise#4131]
Hi all -

I've been stuck on this problem for a while. Devise goes into a redirect loop after resetting the password. I know why, but I'm not sure exactly what's causing it.

I'll explain what I've done so far and then post code. 
- After the password is reset, devise redirects the user to `app/dashboard#index`, where I have `before_action :authenticate_user!`. 
- My configuration sets  `config.sign_in_after_reset_password = false`, so the user isn't authenticated (note that this still happens if I change that to true) . 
- It redirects to `app/sessions#new`. 
- Here, the parent devise controller calls `require_no_authentication` and inside that method, `warden.authenticated?(resource_name)` returns true. 
- This is the root of my issue, and  I can't figure out why warden thinks my user is already authenticated. Anyway, so because warden thinks I'm already authenticated, it redirects to (you guessed it) `app/dashboard#index` and the whole cycle repeats.

Also, when I go to visit the sign-in page after this, I get the same redirect loop. But when I clear my cookies (and most importantly my session-id), it gets fixed.

I'm on Rails 5.0.0.rc1, Ruby 2.3.1 and Devise 4.1.0

Here's all the relevant code:

app/sessions_controller.rb

``` ruby
class App::SessionsController < Devise::SessionsController
  respond_to :html

  before_action :ensure_params_exist, only: [:create]

  def new
    super
  end

end
```

app/dashboards_controller.rb

``` ruby
class App::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @deal_stats = current_user.deal_stats
    @recently_updated_files = current_user.recently_updated_files
    @deals_behind_schedule = current_user.displayed_deals.behind_schedule
    @deals_nearing_completion = current_user.displayed_deals.nearing_completion
  end
end
```

application_controller.rb

``` ruby
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_action :verify_authenticity_token
  before_action      :set_authenticate_params

  # user role validate
  def authenticate_user!
    if current_user.blank?
      respond_to do |format|
        format.html { redirect_to new_app_user_session_path }
        format.json { unauthorized_response(401) }
      end

    end
  end

  def ensure_params_exist(object)
    if params[object].blank?
      error_response(["object related parameters not found."])
    end
  end

  def set_authenticate_params
    if params[:organization_id].blank?
      if !params[:organization].blank? and !params[:organization][:id].blank?
        params[:organization_id] = params[:organization][:id]
      end
      if !params[:deal].blank? and !params[:deal][:organization_id].blank?
        params[:organization_id] = params[:deal][:organization_id]
      end
    end
  end
end

```

config/initializers/devise.rb

``` ruby
Devise.setup do |config|
  config.secret_key = HIDDEN
  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
  require 'devise/orm/active_record'

  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 11
  config.reconfirmable = true
  config.expire_all_remember_me_on_sign_out = true
  config.password_length = 6..128
  config.email_regexp = /\A[^@]+@[^@]+\z/

  config.reset_password_within = 6.hours
  config.sign_in_after_reset_password = false
  config.sign_out_via = :delete
end
```

Sorry for the massive code dump! I would greatly appreciate any help.

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?
