### ISSUE TITLE
Redirect without locale after authorization failed

### ISSUE THREAD

**Issue by BrahimDa** [plataformatec/devise#4132]
Hi guys,

I'm creating a Multi-language application and i want to localize devise views, actually all works greatly except  this scenario:

1. The user is not logged in
2. He try to access the admin dashboard with locale, ex: `http:/example.com/fr/admin/`
3. devise redirect him to log-in page, but he loose the specified locale (**fr**), the view is on the default locale, ex: http:/example.com/**en**/admin/sign-in

Any help please.

nb: i'm using **rails 5.0.0.rc1** and **devise (4.1.1)**

**Comment by basiszwo** [comment]
As I have no idea what your application is doing I can only guess but I think you are 

* either not setting the locale properly before running into your authentication hook
* and / or you do not pass the locale properly. 

You may have a look at the [rails i18n guide](http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-url-params). I can image that `default_url_options` is your friend.

From what I see in my apps (rails rc1 and devise edge) this is not a devise issue.

**Comment by BrahimDa** [comment]
@basiszwo , thnx a lot, the issue is in my code, fixed it work now.

Sorry, about that
