### ISSUE TITLE
Wrong number of arguments (0 for 1) when creating new user 

### ISSUE THREAD

**Issue by LizBayardelle** [plataformatec/devise#4134]
I recently installed the devise gem on my rails app and am getting a strange error when I try to register a user. The sessions#new and users#new pages appear without issue, but when I try to create a new user I get this:

ArgumentError at /users
wrong number of arguments (0 for 1)
Called on activesupport (4.2.5) lib/active_support/callbacks.rb 

on the first line beginning with lambda:

 def make_lambda(filter)
    case filter
    when Symbol
      lambda { |target, _, &blk| target.send filter, &blk }
    when String
      l = eval "lambda { |value| #{filter} }"
      lambda { |target, value| target.instance_exec(value, &l) }
    when Conditionals::Value then filter
    when ::Proc

Any ideas what could be causing this?

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?
