### ISSUE TITLE
Devise authentication error after sign in

### ISSUE THREAD

**Issue by NiteshKaradwall** [plataformatec/devise#4135]
I am using rails 4.2.6 and devise 3.4.1

I have a User signing in properly and that gets properly redirected to the after_sign_in route that is dashboard controller. but which authorizes the User right after

Completed 401 Unauthorized in 1ms

I saw #3059 about this issue but I have "Rails.application.config.session_store :active_record_store, key: 'key_name', domain: :all" setting into session_store.rb file. 

sign_in_count gets properly incremented every time sign_in redirects.

Any help is much appreciated.

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?
