### ISSUE TITLE
How to make devise.html.erb yield into application.html.erb layout?

### ISSUE THREAD

**Issue by pedroadame** [plataformatec/devise#4137]
As is. Written `devise.html.erb` and all my application layout is gone because it only loads the Devise one.

**Comment by pedroadame** [comment]
So far this is a little workaround:

1. Rename `devise.html.erb` to `_devise.html.erb`
2. Add the following in `application.html.erb`

```
<% if devise_controller? %>
    <%= render 'layouts/devise' %>
<% else %>
    <%= yield %>
<% end %>
```
And have a `<%= yield %>` line on your `_devise.html.erb`

**Comment by mariowise** [comment]
I'm not sure if I understand your question, what I usually do is to have a layout for devise or public content, and another for application interior. In the `application_controller.rb` you can do

    layout :layout_by_resource

    def layout_by_resource
      if devise_controller?
        "public" # or devise in your case
      else
        "application"
      end
    end

This will apply the `public.html.erb` layout to all devise views, and `application.html.erb` to the rest. Basically it is similar to what you have now, but I believe it is better to have those definitions in a controller. Also with completely separated layouts, you can include different styles and have different designs in each one. Let me know if this helps. Regards.

**Comment by basiszwo** [comment]
Also there is a [nice wiki page about using custom layouts](https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts)

**Comment by pedroadame** [comment]
Hi @mariowise, the thing I wanted to do is:
When not using devise
application_layout -> yielded content from templates
When using devise
application_layout -> devise_layout -> yielded content

Also, @basiszwo this is not shown in the wiki.

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
