### ISSUE TITLE
Should add reset_session

### ISSUE THREAD

**Issue by Xosmond** [plataformatec/devise#4141]
Question to devise developers, do you do "reset_session" when creating or destroying sessions? or should i added manually?

**Comment by lucasmazza** [comment]
Devise doesn't resets the entire session, only a set of session entries scoped by Devise/Warden.

If you need to do something like that you should do it on your own.

**Comment by tien-do-hanko** [comment]
> Question to devise developers, do you do "reset_session" when creating or destroying sessions? or should i added manually?

Here is a good reference for your case:
[Reset Session](https://makandracards.com/makandra/53562-devise-invalidating-all-sessions-for-a-user
 )
