### ISSUE TITLE
Callback to override Lockable required

### ISSUE THREAD

**Issue by veera** [plataformatec/devise#4142]
Can devise enable/disable `Lockable` module functionality based on specific condition. Basically looking for `lockable_required?` method on `Lockable` module which can be overridden based on certain conditions. 
Similar method available on `Confirmation` module - `confirmation_required?`
http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Confirmable#confirmation_required%3F-instance_method

**Comment by lucasmazza** [comment]
@veera hey, that sounds useful! Feel free to send a Pull Request adding the `lockable_required?` hook.
