### ISSUE TITLE
sign_in method not works on a post request

### ISSUE THREAD

**Issue by chemzqm** [plataformatec/devise#4144]
I'm using rails 4 and devise 3.5.2, the login code looks like below:
```
  def token_login
    auth_token = AuthToken.find_by(token: params[:auth_token])
    if auth_token
      @user = auth_token.user
      sign_in(:user, @user)
      render template: '/api/user'
    else
      return render_error API_ERROR_INVALID_KEY, "invalid token"
    end
  end
```
It works well if I call this method with get request, but `sign_in` would have no effect (without any error thrown) if I call this method with AJAX post request, is devise designed to work like this or I'm missing something?

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by chemzqm** [comment]
The reason is from `protect_from_forgery with: :null_session` from rails, it will remove any cookie from the response.
