### ISSUE TITLE
How to add superadmin in addition to admin user?

### ISSUE THREAD

**Issue by BKSpurgeon** [plataformatec/devise#4147]
### Questions

Regarding this page: https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role

* Any ideas on how to add a super admin user in addition to admin user?

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
