### ISSUE TITLE
Filter parameters in Mailer logging?

### ISSUE THREAD

**Issue by irstacks** [plataformatec/devise#4149]
I'm working with _attr_encrypted_ to encrypt my `User.email`, and have successfully moved my Devise `authentication_key` to another attribute. However, I'm still seeing legible email addresses in the Mailer logs. Is there any way to get them out of there?

I'm filtering my logs like so in the standard Rails __filtered_parameter_logging.rb__ initializer -- 
```
# Configure sensitive parameters which will be filtered from the log file.
Rails.application.config.filter_parameters += [:email, :password, :admin_secret, :access_token]
```

My logs are being successfully filtered otherwise. 

Any ideas?

**Comment by lucasmazza** [comment]
@irstacks sadly that's more of a Rails issue than Devise's - the whole logging infrastructure is from Rails and as far as I remember the `filter_parameters` config is only applied to HTTP requests and not to the ActionMailer/ActiveJob logging - maybe the patch from #4140 could help but I haven't tested that.

I'm closing this as it isn't something we can fix on Devise sides.
