### ISSUE TITLE
Getting “error simple_form [not found]” 

### ISSUE THREAD

**Issue by neohunter** [plataformatec/devise#4150]
I've installed devise

On my Gemfile

```
gem 'simple_form'
gem 'devise'
```

i have both simple_form.rb and devise.rb on my initializer folder,

when I run rails g devise:views i got this error:

```
   error  simple_form [not found]
  invoke  erb
```

and the views are not copied.

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by BandanaPandey** [comment]
Firstly run  this  (rails g simple_form:install) and than try to run (rails g devise:views)

**Comment by evertonts** [comment]
@neohunter @BandanaPandey Any news on this issue? I tried to generate the view in a clean rails app with rails 5.0.1, devise 4.20 and simple form 3.4.0 and didn't get the error.
