### ISSUE TITLE
Create User from Java application and Login using UI built in Rails

### ISSUE THREAD

**Issue by railstesta** [plataformatec/devise#4151]
Hi,
I have a case to create users and its data from Java and allow them to login through Rails. In Rails app, I am using Devise. Not able to login with user created by Java as Encryption is not correct.
Is there any guide to use similar password encryption used by Devise which Java app can use to encrypt passwords ?

Thanks

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
