### ISSUE TITLE
For how long time the login/session data is kept on the database?

### ISSUE THREAD

**Issue by acrolink** [plataformatec/devise#4152]
I am trying to make some Restful calls to devise protected areas of my Rails app via c#. My plan is like this:

1) Within c# to call [GET] /users/sing_in
2) locate & store the csrf-token
3) using the csrf-token to actually login with email & password to [POST] /users/sign_in
4) make authenticated calls to the Rails server

I guess this is the most secure manner to achieve this goal. My question, for how long time the session data is available at the database? Do old sessions get deleted automatically after some time? How to configure that?

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
