### ISSUE TITLE
Is this the appropriate way to sign in to a devise protected Rails app from a c# application?

### ISSUE THREAD

**Issue by acrolink** [plataformatec/devise#4154]
I have implemented the following method to achieve the above mentioned goal:

1) Within c# call [GET] /users/sing_in
2) locate & store the csrf-token, store cookie and use it in following steps
3) use the csrf-token to actually login with email & password to [POST] /users/sign_in
4) make authenticated calls to the Rails server using the stored cookie

Is this the correct way to do it? Is this secure? Are there any shorter / alternative methods? Thanks.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
