### ISSUE TITLE
error while doing your tutorial Integrate Flash Messages with Devise and Bootstrap

### ISSUE THREAD

**Issue by shaunstanislaus** [plataformatec/devise#4155]
https://github.com/plataformatec/devise/wiki/How-To:-Integrate-I18n-Flash-Messages-with-Devise-and-Bootstrap

I Followed everything in the wiki page, but it says that the resources is not defined. 
any idea how to resolve this? or where this resource is defined?

<img width="1440" alt="screen shot 2016-06-19 at 10 38 32" src="https://cloud.githubusercontent.com/assets/1703530/16174855/280db506-360a-11e6-8806-acebf02d9942.png">

**Comment by lucasmazza** [comment]
The `devise_error_messages!` will only work for Devise specific controller actions, not on app specific ones like `HomeController#index` - you can implement your own helper/partial logic for this accessing your `current_user` directly instead.

 The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
