### ISSUE TITLE
authenticatable vs authenticable

### ISSUE THREAD

**Issue by machty** [plataformatec/devise#4157]
I might be wrong but I think there's a typo/inconsistency in whether `authenticable` / `authenticATable` is used. In particular I don't think this test actually tests the right thing:

https://github.com/plataformatec/devise/blob/9caf07dd4f7036168c423d335f53ae8a212eba18/test/models/rememberable_test.rb#L102-L114

also, this error message is misleading:

https://github.com/plataformatec/devise/blob/9caf07dd4f7036168c423d335f53ae8a212eba18/lib/devise/models/rememberable.rb#L77

**Comment by lucasmazza** [comment]
Thanks for noticing 🙈 .

Fixed on fe10a5b.
