### ISSUE TITLE
Testing successful login with Devise

### ISSUE THREAD

**Issue by mjswartz** [plataformatec/devise#4162]
I'm trying to go through Michael Hartl's RoR tutorial, but it's my third time through the thing and now I'm trying to implement Devise instead of the home rolled authentication in the tutorial. As you can imagine, this is a little bit painful, mainly due to the test driven development in the RoR tutorial not mixing well with Devise. My current hang up is that I can't seem to successfully test a successful login. I have the website up on localhost, so I know the login works, but my test is still failing for some reason. Here's the integration test snippet

```
    def setup
      @user = users(:michael)
    end

    ...

    test "login with valid information" do
      get user_session_path
      assert_equal 200, status
      post user_session_path, 'user[email]' => @user.email, 'user[password]' => "password" 
      follow_redirect!
      assert_equal 200, status
      assert_select "a[href=?]", user_session_path, count: 0 # THIS LINE FAILS
      assert_select "a[href=?]", destroy_user_session_path
      assert_select "a[href=?]", user_path(@user)
    end
```

The error I get is 

```
    FAIL["test_login_with_valid_information", UsersLoginTest, 2016-06-19 11:06:18 -0400]
    test_login_with_valid_information#UsersLoginTest (1466348778.61s)
          Expected exactly 0 elements matching "a[href="/users/sign_in"]", found 1..
          Expected: 0
            Actual: 1
```

The login bar up at the top switches from `Sign in` to `Account`, so it looks like the test isn't getting the user in the setup block successfully signed in. Another, possibly unrelated, issue is that in another test I have, I try the same exact login method with `post user_session_path...` and then check that `current_user` is not null with `assert_not current_user.nil?`, but I get the error 

`    NameError: undefined local variable or method 'current_user' for #<UsersLoginTest:0x00557f81155648>`

I've looked around and made sure that I have the correct lines of `devise_for :users` in my routes.rb file. I'm pretty sure It's not able to access `current_user` because somehow I don't have my integration test able to access resources in Devise. Those are my two problems! Any help would be greatly appreciated.

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by minhdanh** [comment]
Same problem here
