### ISSUE TITLE
Logout link not displaying instead error shown..

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4167]
My code in view is 
`<% if user_signed_in ? %>
	<div class="pull-right"><%= link_to('Logout', destroy_user_session_path, :method => :get) %>  </div>
	<% end %>`

used method get because I have changed to get in config>initialize>devise.rb file. Error shown is following.

`C:/Users/pradeep/Desktop/userperm/app/views/layouts/application.html.erb:14: syntax error, unexpected ';', expecting ':' ...iv class="pull-right">'.freeze;@output_buffer.append=( link_... ... ^ C:/Users/pradeep/Desktop/userperm/app/views/layouts/application.html.erb:45: syntax error, unexpected keyword_ensure, expecting end-of-input

Rails.root: C:/Users/pradeep/Desktop/userperm

Application Trace | Framework Trace | Full Trace
app/views/layouts/application.html.erb:14: syntax error, unexpected ';', expecting ':'
app/views/layouts/application.html.erb:45: syntax error, unexpected keyword_ensure, expecting end-of-input`

**But there is no ; symbol**

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
