### ISSUE TITLE
can not modify css style from view and not see how to do from css file (where to put which file please ?)

### ISSUE THREAD

**Issue by jerome-diver** [plataformatec/devise#4170]
from this haml part of code view of edit registration devise view:
https://gist.github.com/jerome-diver/424543757705487fc4856988f53dab16
haml_options failed to show me text in black color.
Also, i read and re-read the readme for devise, but never find where to put/modify the css file for devise may care of the presentation i would like to have. Could you please tell me how i can do for be able to modify the style of the content please (i use dark style for my pages... and default color of devise is unusable in this situation) ?
thank you for this information.

**Comment by josevalim** [comment]
you should copy devise views to your application using the command shown in the readme and then edit them in whatever way you want.

Also, Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by jerome-diver** [comment]
Your answer is to quick, because you forget to look at what i done allready, because i do make customized view (and see them show me customization). BUT: (please, take time to read me first)

in line 47 and 53, html_options for style "color: black" has to make color of text in black... it does not.
Also, i not understand where to put a css file to be read and care by devise.

https://gist.github.com/jerome-diver/7d1383df791cdea619bf769433badb04

thank you for take a little bit more time to check things, something looks not normal here.
