### ISSUE TITLE
How to modify look from CSS files ?

### ISSUE THREAD

**Issue by jerome-diver** [plataformatec/devise#4172]
i do make customized view (and see them show me customization). BUT: (please, take time to read me first before answer, it may need information or target on a problem)

in line 47 and 53 from file pasted here, html_options for style "color: black" has to make color of text in black... and it does not.
Also, i not understand where to put a css file to be read and care by devise (please, don't talk me about customize view... again, i just know about that, it is not my question to...).

https://gist.github.com/jerome-diver/7d1383df791cdea619bf769433badb04

something looks not normal here and i think i can use CSS file, but i don't know how to (i failed to) make them working.
Thank you for provide an help.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
