### ISSUE TITLE
Check current user before login.

### ISSUE THREAD

**Issue by rahul8sharma** [plataformatec/devise#4173]
How to check current user before login. Simply I want to call my method before login. Suppose I have two different - 2 login form and I am already login from first login form and when I will log in from another login form then it will check user already logged in or not. I want to create a custom method which will call before login.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
