### ISSUE TITLE
Lock accounts after too many password edit attempts

### ISSUE THREAD

**Issue by Gasparila** [plataformatec/devise#4174]
The `lockable` module gives a great tool to lock accounts after too many sign in attempts, and it would be  nice to have a similar feature to limit password change attempts. This would prevent a brute force attack to guess a users password in the event that an attacker compromised a victim's session.

**Comment by lucasmazza** [comment]
Thanks for the nice feature request, but this behavior sounds like something that would fit nicely into a gem of its own, similar to some of the http://github.com/phatworx/devise_security_extension modules.
