### ISSUE TITLE
Rails 5 Release

### ISSUE THREAD

**Issue by pratik60** [plataformatec/devise#4176]
Hey

With Rails 5 release, can we now release a new version with the devise master as that is directly compatible with rails 5?

**Comment by acrolink** [comment]
I have just updated to Rails 5. I am getting this error when I try to access a protected resource (view):

```
NoMethodError in Devise::Sessions#new
Showing /srv/rails/my_app/app/views/devise/sessions/new.html.erb where line #3 raised:

undefined method `session_path' for #<#<Class:0x0000000a633a08>:0x00000002011510>
Did you mean?  session
```

**Comment by lucasmazza** [comment]
`4.2.0` was released with the latest controller test patch for Rails 5. Enjoy!

**Comment by jasnow** [comment]
Thanks
