### ISSUE TITLE
Confirm user after one user has successfully reset his/her password?

### ISSUE THREAD

**Issue by ypxing** [plataformatec/devise#4177]
I got one scenario that user may reset their password before confirming their account.
Should we confirm that user once the password has been successfully updated by adding ```resource.confirm! if confirmable?(resource)``` to ```PasswordsController#update```?

```
  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      resource.confirm! if confirmable?(resource) # new line here
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:notice, flash_message)
        sign_in(resource_name, resource)
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end
```

**Comment by josevalim** [comment]
No. We were used to do it but it became a security issue. Please check the CHANGELOG and announcements. Also,  please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
