### ISSUE TITLE
Controller testing requires more dancing than what the documentation suggests

### ISSUE THREAD

**Issue by trejkaz** [plataformatec/devise#4178]
I was reading this page:

https://github.com/plataformatec/devise/wiki/How-To:-Stub-authentication-in-controller-specs

It suggests mocking warden and controller. But I find that for me, `request.env['warden']` is nil, so even with this setup code, every test fails.

A hint somewhere else suggested to use `Warden::Test::Mock`, but even that wasn't enough, and the bare minimum it appears I can get away with is as follows:

    class ActionController::TestCase
      include Devise::TestHelpers
      include Warden::Test::Mock

      setup do
        request.env['devise.mapping'] = Devise.mappings[:users]
        request.env['warden'] = warden     # <= had to explicitly set into environment here!
      end

      def logged_in(user)
        warden.stubs(:authenticate!).returns(user)
        @controller.stubs(:current_user).returns(user)
      end
    end

I know I could probably just edit the wiki myself, but I thought I'd run it through as an issue first in case there is a better way.

**Comment by lucasmazza** [comment]
Have you seen our [`Testing`](https://github.com/plataformatec/devise#test-helpers) section on the README? It's probably a more suitable guide for dealing with tests and we need to update/remove that wiki page.

I'm closing this one as it isn't an issue with the codebase.

**Comment by trejkaz** [comment]
I had seen the readme as well, but reading that didn't get my tests to pass, and searching for more information was how I found the Wiki page.

Looking at the readme again, though, request.env['warden'] appears to be missing from that as well.

**Comment by trejkaz** [comment]
Okay, after giving the non-mocking way another shot, I have eventually got the tests passing again, but only after employing another hack which I believe I should not have to be performing. Here's the situation.

Up in the test helper:

    class ActionController::TestCase
      include Devise::Test::ControllerHelpers
      setup do
        request.env['devise.mapping'] = Devise.mappings[:users]
      end
    end

We have one test which sets up the user who is about to login and this is the only test which fails. Its setup is as follows:

      setup do
        user = User.create!(name: 'Admin User', email: 'admin@example.com',
                                 password: 'password', password_confirmation: 'password')
        user.roles << roles(:administrator)
        sign_in user
      end

Then one of the tests, I'll use the most trivial one:

      test "viewing index page" do
        get :index

        assert_response 200
      end

This fails with response being 302 instead of 200, because it's trying to redirect to the login page.

If I do this instead:

      setup do
        user = User.create!(name: 'Admin User', email: 'admin@example.com',
                                 password: 'password', password_confirmation: 'password')
        user.roles << roles(:administrator)

        #HACK: Pull down a new copy of the user, because sign_in doesn't work
        #       with the one we already have!
        user = User.where(id: user.id).first

        sign_in user
      end

Now the test passes. I don't understand why I have to pull a new copy of the user to sign in, but I assume that the instance I had just created was poisoned somehow. Maybe this could also explain why after resetting the password on the real site, I get booted out of the site instead of being signed in, but I'm not really sure if that's the same issue yet.
