### ISSUE TITLE
Could not change user's password

### ISSUE THREAD

**Issue by ignatbagaev** [plataformatec/devise#4179]
Hello!

It seems like I found some unexpected behavior with changing password when profile editing does not require current password to be provided.

I implemented an alternative solution from [here](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password).

Now when I'm trying to change user's password it redirects me to root with message _'Your account has been updated successfully.'_ even with invalid password and password confirmation (either when there is password but no confirmation or when 'password confirmation' is not the same as 'password'). But in real password is not being changed. I could not change password even if provided password and confirmation are correct. 
You can check the code [here](https://github.com/ignatbagaev/tasks). Rails v-4.2.6, Devise v-3.4.1

Sorry for my broken English.
Regards, Ignat

**Comment by vietntframgia** [comment]
You used updating user without password. So, i think password wasn't changed in this case. Please insert password field in permit line. Ex:  `params[:user].permit(:first_name, :last_name, :address, :password)`

**Comment by ignatbagaev** [comment]
@vietntframgia thanks for your reply.
That's my fail. I get it.
I looked at the [docs](http://www.rubydoc.info/github/plataformatec/devise/Devise%2FModels%2FDatabaseAuthenticatable%3Aupdate_without_password) now and it says that `update_without_password` method never allows a change to the current password.
Don't you think that Wiki is little bit confusing and it would be better to notice about this effect?
