### ISSUE TITLE
Password reset link not invalidated after login

### ISSUE THREAD

**Issue by Gasparila** [plataformatec/devise#4184]
The password reset link is not invalidated after a successful login. I don't know if you care to fix it or not, but I wanted to point that out as it differs from how most (all?) sites I have used behave. To reproduce:

1) Request a password reset link to your account
2) Login after requesting the link
3) The password reset link that was generated will not be invalidated and you can still use it

**Comment by daveshah** [comment]
@Gasparila what version of devise are you using? We just tested with our team here and @jonahrr confirmed we weren't seeing this.

**Comment by jonahrr** [comment]
Just confirmed we're not having this problem on 4.2.0 either

**Comment by Gasparila** [comment]
Interesting... We are running 3.5.10. I am going to assume there is a misconfiguration on our end and will investigate further. Thanks for responding quickly
