### ISSUE TITLE
Flash message when not authenticated suggests signing up even if you can't

### ISSUE THREAD

**Issue by trejkaz** [plataformatec/devise#4188]
When I visit my app and it wants you to login, I see this flash message:

"You need to sign in or sign up before continuing."

Which is fine, but we didn't turn on registrations, so the user can't actually sign up. :)

I can fix this locally by hacking my localised strings file though, so it's a pretty minor issue. I'm changing my copy to say "login" too, for terminology consistency.

**Comment by lucasmazza** [comment]
Yes, in this case you should extend the i18n entries and change the flash message to something that's suitable for your app.
