### ISSUE TITLE
ControllerHelpers giving error NoMethodError: undefined method `env' for nil:NilClass

### ISSUE THREAD

**Issue by dericcain** [plataformatec/devise#4191]
I am using devise for authentication and when running tests on my controller, using the devise ControllerHelpers, I am getting the error:

`NoMethodError: undefined method env for nil:NilClass`

... for each test.

Here is the top of my `tasks_controller_test.rb`

```ruby
require 'test_helper'

class TasksControllerTest < ActionDispatch::IntegrationTest

  include Devise::Test::ControllerHelpers

  setup do
    @task = tasks(:one)
  end
```

Now, if I remove the `include Devise::Test::ControllerHelpers` the test runs fine. Any ideas why this is happening?

![screenshot 2016-07-12 12 43 06](https://cloud.githubusercontent.com/assets/9561913/16777207/3b8c91d4-482e-11e6-9809-3b6f3407e0e2.png)

**Comment by lucasmazza** [comment]
@dericcain controller tests should inherit from `ActionController::TestCase`, not `ActionDispatch::IntegrationTest`. `IntegrationTest` is the superclass for integration tests that don't have direct access to the controller stack

**Comment by dericcain** [comment]
@lucasmazza Thanks!!! The controller test was created when I used the rails command line and inherited the previous class by default.

**Comment by jstewart** [comment]
I wonder why this is closed, when `ActionController::TestCase` is [deprecated](https://github.com/rails/rails/commit/f42ac6a06880bfc02857ab71758214ad7867c22f)? Going forward, controller tests will inherit from `ActionDispatch::IntegrationTest`, not `ActionController::TestCase`.

**Comment by jstewart** [comment]
Never mind, I just saw the updated README that describes how to include test helpers in `ActionDispatch::IntegrationTest` tests.

**Comment by Thomas-lee-2014** [comment]
Did you got it ?
I've got the error too!
`
E

Error:
ArticlesControllerTest#test_should_create_article:
NoMethodError: undefined method `env' for nil:NilClass



bin/rails test test/controllers/articles_controller_test.rb:20
`

**Comment by Thomas-lee-2014** [comment]
Did you got it ?
I've got the error too!
```
E

Error:
ArticlesControllerTest#test_should_create_article:
NoMethodError: undefined method `env' for nil:NilClass

bin/rails test test/controllers/articles_controller_test.rb:20
```

**Comment by hartator** [comment]
I am getting the same error on last Rails and Devise.

```
bin/rails test test/controllers/admin/users_controller_test.rb:27

Error:
Admin::UsersControllerTest#test_should_get_new:
NoMethodError: undefined method `env' for nil:NilClass
```

```
class Admin::UsersControllerTest < ActionDispatch::IntegrationTest

  include Devise::Test::ControllerHelpers

  setup do
    @admin_user = User.create email: "valid@email.com", password: "Password456!", admin: true
    sign_in @admin_user
  end

```

Switching from ` ActionDispatch::IntegrationTest` to `ActionController::TestCase` fixes the issue but it's not ideal as it's breaking url helpers in plus of being deprecated.

**Comment by arusa** [comment]
This documentation seems to be deprecated:
https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-(and-RSpec)

But as jstewart mentioned you find the correct solution in the README.md:
https://github.com/plataformatec/devise#controller-tests
