### ISSUE TITLE
before/after action on devise actions

### ISSUE THREAD

**Issue by jonatasrancan** [plataformatec/devise#4195]
Hey guys, is there a way to run a custom before/after filters on devise controllers?
For example if I want to run somenthing before/after the user log in.
What I did was this:
```ruby
class SessionsController < Devise::SessionsController
   after_action :my_method, only: :create
end
```

I created this new controller only to call the filter.

**Comment by lucasmazza** [comment]
@jonatasrancan yes, the custom controller is required for this - you can either use `after/before_action` callbacks or override the actions and hook your app specific code around with `super` or a block.

**Comment by jonatasrancan** [comment]
ok, thx @lucasmazza .
