### ISSUE TITLE
After upgrade to Rails 5, cannot use User.first or User.find

### ISSUE THREAD

**Issue by floydj** [plataformatec/devise#4196]
After upgrading my app to Rails 5, I get the following with either method call:

```
irb(main):001:0> User.first
ArgumentError: wrong number of arguments (given 0, expected 1)
	from /Users/jasonfloyd/.gem/ruby/2.3.0/gems/devise-4.2.0/lib/devise/models/database_authenticatable.rb:146:in `password_digest'
	from /Users/jasonfloyd/.gem/ruby/2.3.0/gems/activemodel-5.0.0/lib/active_model/serialization.rb:135:in `block in serializable_hash'
```

Everything in the app itself seems to work ok, but I can't access a User object from the console.

Ideas on what's going on here? This occurs on OSX and Ubuntu.

**Comment by lucasmazza** [comment]
@floydj sounds like something similar to #4192 - do your model has a `password_digest` column?

**Comment by floydj** [comment]
@lucasmazza Yes, it does. And removing it fixed the problem. Not sure I would have found it by searching closed issues, but I should have tried!  Thanks much!
