### ISSUE TITLE
How to add custom field to registration form and permiting field params so that  it is automatically saved in database ?

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4201]
I have a field user[role_id] in my form for user sign up form. 
I have added param :role_id in 
'protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:role_id])
   end
'
but while registering user role_id has not been inserted into database. Please help

**Comment by lucasmazza** [comment]
Have you updated your registration form to send the `role_id` as a parameter of the request?

**Comment by prdpspkt** [comment]
I'm new to ruby on rails. I have this field in form 
`<div class="form-group">
    <select class="form-control" name="user[role_id]">
    <%@roles.each do |role| %>
    <option value="<%=role.id%>"><%=role.name %></option>
    <%end%>
    </select>`
I'm using rails 5.0

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by prdpspkt** [comment]
I found it was not an issue with devise but with myself. Sorry for spoiling your time. I did It myself. Thank you very much for your timely response.

**Comment by COConsulting** [comment]
Can you provide the answer that you found for others who may be having a similar issue?

**Comment by adrienlille** [comment]
@prdpspkt I am having the exact same issue, what did you do wrong? I am probably doing the ame mistake

**Comment by jesyontop01** [comment]
i was able to resolve the issue by following
https://github.com/plataformatec/devise . The section of strong parameter
will help

**Comment by sebastienrombaut** [comment]
This worked for me, i wanted to add a first_name and last_name for registration
```
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end
```
