### ISSUE TITLE
Devise ORM/ODM Adapter for Dynamoid

### ISSUE THREAD

**Issue by gizipp** [plataformatec/devise#4202]
Have checked in https://github.com/plataformatec/devise/tree/master/lib/devise/orm looks like Devise only support `:active_record` and `:mongoid` only.

It would be nice if Devise + AWS DynamoDB could works together. Is there any way to support `:dynamoid` adapter?

ps: already asked in [stackoverflow](http://stackoverflow.com/questions/37847263/devise-orm-odm-adapter-for-dynamoid-rails-dynamodb-devise) but no clue

**Comment by lucasmazza** [comment]
@gizipp we have no plans on adding builtin support for other ORMs other than ActiveRecord or Mongoid. We recommend creating a new bridge gem (if it doesn't exist yet) like devise-mongo_mapper or devise-sequel. :)
