### ISSUE TITLE
NoMethodError after upgrading to Rails 5 

### ISSUE THREAD

**Issue by jamessteininger** [plataformatec/devise#4203]
I am developing on Nitrous.io and recently upgraded my Rails 4 app to Rails 5 to take advantage of the new Action Cable features. 

Here is my Gemfile:
```
ruby '2.3.1'

gem 'rails', '5.0.0.rc2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0' 
gem "fog"
gem 'bootstrap-sass'
gem 'jasny-bootstrap-rails'
gem 'devise', :github => 'plataformatec/devise', :branch => 'master' 
gem "Ziggeo"
gem "chartkick"
gem 'groupdate'
gem 'paperclip', :git=> 'https://github.com/thoughtbot/paperclip', :ref => '523bd46c768226893f23889079a7aa9c73b57d68'
gem 'aws-sdk' 
gem "font-awesome-rails"
gem 'high_voltage'
gem 'auto_html', '1.6.4'
gem 'bootswatch-rails'
gem 'pg'
gem 'redis', '~> 3.0'
gem 'sendgrid'
gem 'simple_form' 
gem 'puma', '3.1'
group :development, :test do
  gem 'byebug'
end
group :development do 
  gem 'spring'
  gem 'foreman'
  gem 'hub', :require=>nil
  gem 'rails_layout'
end 
group :production do
  gem 'rails_12factor'
end
```
And when I go to a new user signup path:

NoMethodError in Devise::SessionsController#new
undefined method `for' for #<Devise::ParameterSanitizer:0x007faab4211130>

And it references:
```
 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
```

After much Google-fu I still have yet to find a solution for my particular issue. 

Any help would be much appreciated!

**Comment by simpl1g** [comment]
There is note in readme
https://github.com/plataformatec/devise#strong-parameters

**Comment by lucasmazza** [comment]
@jamessteininger the Parameter Sanitizer API has changed - please see the README (link above by @simpl1g) for the new API.

**Comment by jamessteininger** [comment]
Thank you so much @simpl1g and @lucasmazza this is exactly what I needed, I'm not sure how I didn't stumble upon this sooner.
