### ISSUE TITLE
Rails "config.relative_url_root" not taken into account

### ISSUE THREAD

**Issue by schopenhauer** [plataformatec/devise#4205]
Devise routes don't seem to take into account the `config.relative_url_root` parameter set in a Rails app (config/environments/production.rb). All links automatically prepend the relative URL, but Devise forms still redirect to the initial root folder.

**Comment by cmar** [comment]
I'm dealing with a similar issue with a Rails 5 app. I used a scope in routes.rb. It works except for  an authorize redirect. Because the default [FailureApp takes relative_url_root into account](https://github.com/plataformatec/devise/blob/4-1-stable/lib/devise/failure_app.rb#L147),  so you get a double root url when redirected, example `/myapp/myapp/users/sign_in`

## routes.rb
```
  scope '/myapp' do
    devise_for :users, path: 'users'
  end
```

## Scoped Routes
```bash
                  Prefix Verb   URI Pattern                              Controller#Action
        new_user_session GET    /myapp/users/sign_in(.:format)        devise/sessions#new
            user_session POST   /myapp/users/sign_in(.:format)        devise/sessions#create
    destroy_user_session DELETE /myapp/users/sign_out(.:format)       devise/sessions#destroy
           user_password POST   /myapp/users/password(.:format)       devise/passwords#create
       new_user_password GET    /myapp/users/password/new(.:format)   devise/passwords#new
      edit_user_password GET    /myapp/users/password/edit(.:format)  devise/passwords#edit
                         PATCH  /myapp/users/password(.:format)       devise/passwords#update
                         PUT    /myapp/users/password(.:format)       devise/passwords#update
cancel_user_registration GET    /myapp/users/cancel(.:format)         devise/registrations#cancel
       user_registration POST   /myapp/users(.:format)                devise/registrations#create
   new_user_registration GET    /myapp/users/sign_up(.:format)        devise/registrations#new
  edit_user_registration GET    /myapp/users/edit(.:format)           devise/registrations#edit
                         PATCH  /myapp/users(.:format)                devise/registrations#update
                         PUT    /myapp/users(.:format)                devise/registrations#update
                         DELETE /myapp/users(.:format)                devise/registrations#destroy
```

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by array42** [comment]
http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root
Sample should be simple: just deploy to a subdirectory.

**Comment by Hellfar** [comment]
I made a new issue, since this one has been closed and lack of informations and I grouped it with an other issue which, I believe is from the same problem. I think they both are what @schopenhauer and @cmar are talking about.
[4917](https://github.com/plataformatec/devise/issues/4917)
