### ISSUE TITLE
AzureActiveDirectory OmniAuth strategy yields "Not found. Authentication passthru." after clicking 'Sign in with AzureActiveDirectory'

### ISSUE THREAD

**Issue by dlcmh** [plataformatec/devise#4208]
Gemfile:

``` ruby
ruby '2.3.1'
gem 'rails', '4.2.6'
gem 'omniauth-azure-activedirectory'
```

models/user.rb:

``` ruby
devise :database_authenticatable,
       :recoverable, :rememberable, :trackable, :validatable,
       :omniauthable, omniauth_providers: [:azure_activedirectory]
```

config/initializers/devise.rb:

``` ruby
Devise.setup do |config|
  config.mailer_sender = 'no-reply@example.com'
  require 'devise/orm/active_record'
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 11
  config.reconfirmable = true
  config.expire_all_remember_me_on_sign_out = true
  config.password_length = 6..128
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
  config.reset_password_within = 6.hours
  config.sign_out_via = :delete
  config.omniauth :azure_activedirectory,
                  '12345678-b919-47b4-ae68-076346a7f1e1',
                  'example.com'
end
```

`rake routes`:

```
rake routes
                                       Prefix Verb     URI Pattern                                                             Controller#Action
                             new_user_session GET      /users/sign_in(.:format)                                                devise/sessions#new
                                 user_session POST     /users/sign_in(.:format)                                                devise/sessions#create
                         destroy_user_session DELETE   /users/sign_out(.:format)                                               devise/sessions#destroy
user_azure_activedirectory_omniauth_authorize GET|POST /users/auth/azure_activedirectory(.:format)                             devise/omniauth_callbacks#passthru
 user_azure_activedirectory_omniauth_callback GET|POST /users/auth/azure_activedirectory/callback(.:format)                    devise/omniauth_callbacks#azure_activedirectory
```

Clicking on the auto-generated 'Sign in with AzureActiveDirectory' link @ `http://localhost:3000/users/sign_in` brings me to `http://localhost:3000/users/auth/azure_activedirectory` which displays the message "Not found. Authentication passthru."

However, if I manually change the URL in the browser to **remove the underscore** and navigate to `http://localhost:3000/users/auth/azureactivedirectory`, I'm brought to the Azure AD sign in page.

Looking at the path samples in https://github.com/AzureAD/omniauth-azure-activedirectory, the authorisation, callback & failure paths omit the underscore - e.g. `/auth/azureactivedirectory`, `/auth/azureactivedirectory/callback` and `/auth/azureactivedirectory/failure`.

Is some code in the Devise/OmniAuth/omniauth-azure-activedirectory gems automatically replacing the hyphen in the `:azure_activedirectory` strategy with an underscore, which then results in the 'passthru` error?

Is there a way to override the 'auth/azure_activedirectory' path fragment to have it be 'auth/azureactivedirectory'?

Thanks for any help!

**Comment by ylecuyer** [comment]
I removed the _ from the omniauth_providers and from the OmniauthController and it seems to work

**Comment by dlcmh** [comment]
Yes, removing the underscore was what I ended up doing too.

**Comment by ynagasundeep** [comment]
> Yes, removing the underscore was what I ended up doing too.

it is not working for me
