### ISSUE TITLE
Creating empty record

### ISSUE THREAD

**Issue by rockandruby** [plataformatec/devise#4210]
Hi, all -
It'd be awesome to have an ability to create empty records manually with devise without deleting unique indexes for email etc. Because now I have to generate a random email for guest user whom I want to save in db. If you have already a solution for that case pls advise.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
