### ISSUE TITLE
Rails 5 renderer and devise

### ISSUE THREAD

**Issue by leonardoprg** [plataformatec/devise#4212]
Hello guys,

I would like to ask if you guys know a problem related to `render view outside the action`  and devise.

The problem for me is, I have a callback on the model that uses `render` to render a view.
On the view it call's `current_user` method.

Devise raise an error told me it's not possible to found `Warden`.
Taking a look on the internet, I saw some possible solutions for the problem,

my question is, what is the best approach for that?
set the `request.env` manually?

Regards,

**Comment by lucasmazza** [comment]
> set the request.env manually?

Probably yes - we don't have any short term suggestions/patches to improve this, but one thing you could do is change your view/partial to receive the `current_user` as an assigned variable instead of relying on the `current_user` method, so you can pass the instance to the `render` call.

**Comment by leonardoprg** [comment]
Ok,

the suggestion sounds good for now.

Thanks for answer.
