### ISSUE TITLE
Devise generated url contains dot instead of slash ? 

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4213]
`#Devise for user login management
gem 'devise', '~> 4.2.0'`

`#routes.erb
 devise_for :users, controllers: {
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }`

`user_path(user)` gives rise to `users.1' instead of 'users/1' why ?

**Comment by lucasmazza** [comment]
@prdpspkt Most of Devise routes are singular routes, so doing `user_path(user)` says that `user` is the request format, like `.js` or `.html` - you don't need to pass the resource to use these routes.

**Comment by prdpspkt** [comment]
Thank you very much.
