### ISSUE TITLE
Manually encrypt passwords for user ?

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4216]
Is there any method based in devise gem that encrypts password which can be decoded by devise while login? 
This will help to make users created by admins only after user registration closed by removing :registrable. You can suggest if any other way to make registration available for admin only.

Thank you very much in Advance.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
