### ISSUE TITLE
Fix documentation around the devise_parameter_sanitizer.permit(:sign_up) method

### ISSUE THREAD

**Issue by attilagyorffy** [plataformatec/devise#4219]
When using the method described in the source docs, adding additional fields to a sign up action raises an `private method permit called for #<Devise::ParameterSanitizer>` error:

```ruby
devise_parameter_sanitizer.permit(:sign_up) do |user|
  user.permit(:last_name, :first_name)
end
```

I am not sure what is the recommended way to avoid this, but I ended up appending the necessary keys to the following:

```ruby
devise_parameter_sanitizer.for(:sign_up) << :last_name
```

I could have created a pull request already with patches to the inline documentation but I'm not sure what is the recommended way to do so. Just trying to capture this in case this helps anyone in the future.

**Comment by lucasmazza** [comment]
@attilagyorffy This failure means that you are using an older version of Devise with the new API. Please refer to the docs for the version that you are using or update your installation to use newer Devise releases.
