### ISSUE TITLE
Devise confirm questions

### ISSUE THREAD

**Issue by r3id** [plataformatec/devise#4222]
I am using Devise in my Rails app and am sending out emails for email confirmation, password reset, and password change advisory. 

- I would like to know how I would pass in a different image into each of these emails so that I don't need to pass a load of HTML to the layout. Ideally, I would like to pass the image over to the layout if that is at all possible, maybe I need to do this in the controller?

- How would I go about sending out a different email if a user is only updating their existing email? Currently, devise sends the same confirmation email.

- Finally, how would I go about sending a welcome email once they have initially confirmed their account, and not if they are only updating their email?

All help would be much appreciated, thanks 😄

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
