### ISSUE TITLE
Custom layout defined in application.rb has no effects

### ISSUE THREAD

**Issue by Javix** [plataformatec/devise#4227]
I tried to implement a custom layout for Devise mailer views as explained in [wiki](https://github.com/plataformatec/devise/wiki/How-To%3a-Create-custom-layouts):
```ruby
config.to_prepare do
  Devise::Mailer.layout "mailer"
end
```
but does not seem to work.
I created `mailer.html.slim` in `views/layouts/` folder. This layout works fine in other mailer layouts.
Looking in the terminal output, I can see the required stylesheet loaded:
```html
Message-ID: <579c7d9025e33_10eb3fcd288f539c265e0@serge-mac.local.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html>
  <head>
    <meta content=3D"text/html; charset=3DUTF-8" http-equiv=3D"Content-Ty=
pe" />
    <link rel=3D"stylesheet" media=3D"screen" href=3D"/assets/user_mailer=
.self-ad08338d880c8e609296a98e118b4e0414c1fde2369b5c35ec7bfecdca751881.cs=
s?body=3D1" />
    <link href=3D"https://fonts.googleapis.com/css?family=3DOpen+Sans:bol=
d" rel=3D"stylesheet" />
    <link href=3D"https://fonts.googleapis.com/css?family=3DOpen+Sans:lig=
ht" rel=3D"stylesheet" />
  </head>
...
```
So I believe that the layout is loaded but not its CSS. What am I doing wrong ?
Reproduced on:
- OS X
- devise 3.5.2
- rails 4.2.5
- roadie-rails 1.0

**Comment by abhinaykumar** [comment]
Hey @Javix not sure if the same config applies for rails 4.x as well, it says 
> You can also set the layout for specific Devise controllers using a callback in config/environment.rb (rails 2) or config/application.rb (rails 3)

try calling layout in `YourController` or `ApplicationController`. hope that helps.

**Comment by Javix** [comment]
@abhinaykumar thank you for the response. As I said, I need it for my mailer which has nothing to do with controllers.

**Comment by abhinaykumar** [comment]
Yeah actually that's the recommended way to configure custom Mailer layout. 
https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer

**Comment by abhinaykumar** [comment]
@Javix Did it worked?

**Comment by Javix** [comment]
@abhinaykumar Sure it did. I was just asking if there was a way to declare just a layout without subclassing the `Devise::Mailer` module.

**Comment by abhinaykumar** [comment]
@Javix I think it wont be possible without extending `Devise::Mailer` , at least I am not aware of such way of achieving the same.

**Comment by dup2** [comment]
You might try 

     config.parent_mailer = 'MyMailer'

This works at least for 3.5.5

**Comment by Javix** [comment]
@dup2 Thanks a lot, it worked for me, `devise 3.5.2`.
