### ISSUE TITLE
Don't send confirmation email when sign-up?

### ISSUE THREAD

**Issue by 1c7** [plataformatec/devise#4228]
I want let user confirm their email, so I add confirmable into migration and model.
__but I don't want send email during sign-up process__
__I want let user manually send confirm email by click a button__

I can't find offcial document about how to disable email sending during sign-up
and I have try several solution from StackOverflow and Google.

not working, 
Still send email everytime when I signup
![image](https://cloud.githubusercontent.com/assets/1804755/17270320/72ad43e4-5692-11e6-82e1-3e5a3dfb2ed7.png)

rails  4.2.6
devise 4.2.0

Thanks :)

**Comment by abhinaykumar** [comment]
Have you tried calling this method in your `Model`?
```ruby
def send_confirmation_notification?
  false
end
```

**Comment by 1c7** [comment]
@abevoelker 
Thanks for comment  
I already remove relate code, I decide to do email confirmation myself.
because seem like if use devise, and want send email in background, there are no easy way to do it.

**Comment by abhinaykumar** [comment]
@1c7 Not sure where exactly you are facing issue cause Devise has very straight forward way of sending email notifications. for example in your case you want to send a confirmation email when user clicks a button. once they do, you can use `Devise::Mailer.confirmation_instructions(@user).deliver_later` to shoot confirmation email. they have recently merged this feature where you can simply send email in the background using `deliver_later`. Thats great you wrote your own solution but may be that's not DRY in a sense that `Devise` already has simple answer to it.

**Comment by 1c7** [comment]
@abhinaykumar  Thanks for long reply, very helpful.

**Comment by petrbela** [comment]
> @1c7 Have you tried overriding this method in your `Model`?
> 
> ```ruby
> def send_confirmation_notification?
>   false
> end
> ```
> 
> link to method: [plataformatec/devise:lib/devise/models/confirmable.rb@`master`#L158](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L158) [](/plataformatec/devise/blob/HEAD@{2016-07-31T17:07:37Z}/lib/devise/models/confirmable.rb#L158)

While you can certainly override this method, the officially documented/recommended way of skipping sending a confirmation email during signup is by calling `user.skip_confirmation_notification!` before saving the user.
