### ISSUE TITLE
Error message is not shown when the password token is expired

### ISSUE THREAD

**Issue by aitizazk** [plataformatec/devise#4229]
When the password token is expired in `PasswordController` update method then the condition `resource.errors.empty?` is false and in the else block there is no flash messages set. 

I overrided the method like this
```
ActiveAdmin::Devise::PasswordsController.class_eval do
  def update
    super
    if resource.errors.any?
      flash[:error] = resource.errors.full_messages.to_sentence
    end
  end
end

```
but it show error in next request. and flash.now doesn't even show any error. 

btw I am using this in ActiveAdmin

**Comment by abhinaykumar** [comment]
Not sure if this will solve your issue but some people suggested on stackoverflow to use this format 
```ruby
redirect_to({action: :index}, notice: 'my flash message')
```
when flash message is needed. see if it works.
reference: http://stackoverflow.com/a/8171144/2545197

**Comment by aitizazk** [comment]
I fixed it by overriding the update method and passing it a block.

```
def update
  super do |resource|
    if resource.errors.any?
      flash[:notice] = resource.errors.full_messages.to_sentence
    end
  end
end
```

**Comment by abhinaykumar** [comment]
@aitizazk hey man you might want to close the issue if its resolved.
