### ISSUE TITLE
undefined method `user_omniauth_authorize_path'

### ISSUE THREAD

**Issue by carlosguerreroo** [plataformatec/devise#4230]
Hi I just updated devise to  4.2.0 (I used to have  3.5.2) and now Im getting this error 
```
undefined method `user_omniauth_authorize_path'
```

**Comment by PabloVallejo** [comment]
I've updated omniauth-facebook from 3.0.0 to 4.0.0 and devise to 4.2.0 and I'm getting the same error:

```
undefined method `user_omniauth_authorize_path'
```

**Comment by tikh** [comment]
You need to use `user_ facebook_omniauth_authorize_path` after upgrading Devise. See `rake routes`.
