### ISSUE TITLE
User getting signed out when accessing a Rails engine

### ISSUE THREAD

**Issue by nikhilm492** [plataformatec/devise#4231]
Ruby version: 2.3.1
Rails: 5.0.0

We have an app which uses sidekiq monitoring (a Rails engine) described in routes.rb as follows:

authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
end

But accessing the '/sidekiq' page logs the user out of devise by creating a new session.

This used to work for us when we were using Rails 4.2 a few weeks back and it still does with Rails 4.2

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?
