### ISSUE TITLE
  # config.allow_unconfirmed_access_for = 2.days

### ISSUE THREAD

**Issue by qx** [plataformatec/devise#4232]
[How-To:-Add-:confirmable-to-Users](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users) follow this link , `allow_unconfirmed_access_for `not work, user always could login no matter how long ,  `devise (4.2.0) ` `rails 4.2.7`

**Comment by abhinaykumar** [comment]
@qx can you please add link to your repository?, may be i can look at it and figure out whats happening.
Also, I think you should be asking this question on StackOverflow with Devise & Rails tag that would be much more helpful.

**Comment by qx** [comment]
@abhinaykumar tested again ,it worked without changing, and still don't know why,maybe I missed something.
Thanks for reply,
