### ISSUE TITLE
How do I use Devise without database(active record) for SNS login ?

### ISSUE THREAD

**Issue by Samemura** [plataformatec/devise#4233]
In many cases, I create Rails app without active record for user, just only authenticate with SNS(Twitter, etc).

In this case, I would like to use devise with omniauth to be  easier.
E.g. 
Omniauth : Login with Twitter.
Devise: handle Omniauth callback and session. Twitter auth data(uid, name, etc) would be stored into session.

Can someone let me know how it achieve ?

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
