### ISSUE TITLE
Password reset token invalid - because checking for user.email=null

### ISSUE THREAD

**Issue by btrscott** [plataformatec/devise#4236]
On a password reset, the following sql is being generated:

SELECT  `users`.\* FROM `users` WHERE `users`.`reset_password_token` = 'a7f938feeb6949c3af0de0ad10dd893e1d28a51722993c6c64d1f6c58aab4263' AND `users`.`email` IS NULL  ORDER BY `users`.`id` ASC LIMIT 1

Can anyone imagine why it's looking for email that is null; which is obviously not true since the email is the username itself?

Of course it comes up empty and therefore it declares the token invalid.  I'm also looking to see if there is an interaction with another gem that is inserting that sql clause.

**Comment by prdpspkt** [comment]
Please note the parameters you  are sending form form and parameters you are allowing during update.

**Comment by btrscott** [comment]
Here's the development log

Started GET "/users/password/edit?reset_password_token=[FILTERED]" for ::1 at 2016-08-04 18:55:28 -0400
Processing by Devise::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]"}
  Rendered devise/shared/_links.erb (0.4ms)
  Rendered devise/passwords/edit.html.erb within layouts/application (8.4ms)
  Rendered layouts/_navigation.html.haml (1.6ms)
  Rendered layouts/_messages.html.haml (0.2ms)
Completed 200 OK in 452ms (Views: 448.7ms | ActiveRecord: 0.0ms)


Started PUT "/users/password" for ::1 at 2016-08-04 18:55:35 -0400
Processing by Devise::PasswordsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"rymTH8papAPZ8x/UsEHADQHHJKiKCWUgrTEu4nQTGi+Se/C+0Gs2g/SXKqQTca9n1NbdEW4tE8Xn3sLX1Gs+Ow==", "user"=>{"reset_password_token"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Change my password"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`reset_password_token` = 'a7f938feeb6949c3af0de0ad10dd893e1d28a51722993c6c64d1f6c58aab4263' AND `users`.`email` IS NULL  ORDER BY `users`.`id` ASC LIMIT 1
  Rendered devise/shared/_links.erb (0.6ms)
  Rendered devise/passwords/edit.html.erb within layouts/application (10.0ms)
  Rendered layouts/_navigation.html.haml (1.8ms)
  Rendered layouts/_messages.html.haml (0.2ms)
Completed 200 OK in 562ms (Views: 536.3ms | ActiveRecord: 0.4ms)

**Comment by prdpspkt** [comment]
Are you usng built in controllers or creating a new controller and view for this ?

**Comment by btrscott** [comment]
Built in controllers.  I added a few fields so I changed the strong parameters definitions.  I generated the views to customize them but have not done so yet.

```
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end
```

```
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registrable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_create :send_wait_for_approval_mail

  def full_name
    return nil if [:first_name, :last_name].all? {|i| self.send(i).blank?}
    out = [first_name, last_name].reject(&:blank?).join(' ')
  end

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  def send_wait_for_approval_mail
    begin
      AdminMailer.new_user_waiting_for_approval(self).deliver_now
    rescue Exception => e
      logger.info "Could not send admin wait for approval email. "+e.message
    end
  end
  
  def send_been_approved_mail
    begin
      AdminMailer.new_user_has_been_approved(self).deliver_now
    rescue Exception => e
      logger.info "Could not send you've been approved email. "+e.message
    end
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsie recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end
  
end

```

[devise views.zip](https://github.com/plataformatec/devise/files/403995/devise.views.zip)

[Gemfile.lock.txt](https://github.com/plataformatec/devise/files/403997/Gemfile.lock.txt)

[user migrations.zip](https://github.com/plataformatec/devise/files/404011/user.migrations.zip)

The initializers
[devise copy.rb.txt](https://github.com/plataformatec/devise/files/404020/devise.copy.rb.txt)
[devise_async copy.rb.txt](https://github.com/plataformatec/devise/files/404021/devise_async.copy.rb.txt)

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by btrscott** [comment]
Is there a private place I can send the entire app if I cannot isolate a subset that shows the error?
