### ISSUE TITLE
Devise secures all routes by default?

### ISSUE THREAD

**Issue by Corstiaan84** [plataformatec/devise#4237]
Hi,

Is it normal behaviour for Devise to authenticate ALL request to ALL routes after install? I have just installed Devise and not yet set a single `before_action :authenticate_user!` but every requests send me to the signin view.

I have also installed the `simple_token_authentication` gem.

Any idea what could be wrong? I cant share any code because I have non! :-)

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
