### ISSUE TITLE
"Devise.secret_key was not set" isn't required in development env?

### ISSUE THREAD

**Issue by jianbo** [plataformatec/devise#4239]
I am getting this error on our NEW staging when the config.secret_key is not set in devise.rb, but it works in development environment without setting it, is that intend? So only development not requiring config.secret_key?

For some reason our OLD staging worked fine as well without config.secret_key, any idea?

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
