### ISSUE TITLE
ERROR — : undefined method `hide_action' for DeviseController:Class (NoMethodError)

### ISSUE THREAD

**Issue by marvindanig** [plataformatec/devise#4240]
I'm at updating my rails app to gem 'rails', '>= 5.0.0.rc2', '< 5.1'.

After successfully installing the new gemset, on restarting unicorn server I get the following error:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/admin/projects/RoR/bubblin/config/application.rb:7)
E, [2016-08-04T11:46:27.890562 #10907] ERROR -- : undefined method `hide_action' for DeviseController:Class (NoMethodError)
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-3.4.1/app/controllers/devise_controller.rb:9:in `<class:DeviseController>'
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-3.4.1/app/controllers/devise_controller.rb:2:in `<top (required)>'
Is there a different branch of the devise gem that works correctly or do we have to monkey patch it and tell:

```
Is there another branch or a patch that works on rails 5 without using `hide_action` method? 

Question asked here: http://stackoverflow.com/questions/38772433/error-undefined-method-hide-action-for-devisecontrollerclass-nomethoder

**Comment by lucasmazza** [comment]
@marvindanig please use Devise 4.0.0 or greater with Rails 5. You can check the [CHANGELOG](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md) for more details on upgrading from Devise 3.
