### ISSUE TITLE
Email is blank error after password reset

### ISSUE THREAD

**Issue by dsarhadian** [plataformatec/devise#4241]
I'm trying to use the reset password functionality but I seem to be running into some issues. The email sends to the user and I'm able to click the password reset link. When I put in the new password and the confirmation password, it takes me to the password reset initiation page with the error "Email can't be blank." 

I'm not sure what to do

Here are the routes.db, devise.rb, and my custom users_controller.rb file. The custom users_controller is not being used for the actual password reset functionality, but the initiation is done through my custom users controller.

https://gist.github.com/dsarhadian/66d86c143627d30026980fe06fe94ea6

Any help is appreciated.

**Comment by sivagollapalli** [comment]
@dsarhadian Just now I checked with latest devise version `4.2` and rails version `4.2.5`. It works fine for me. The only diff. I noticed that I used devise controllers for password reset functionality . Could you please provide devise version and the rails version? So that I can cross check?

**Comment by dsarhadian** [comment]
@sivagollapalli Sure I'm using Rails 4.2.6 and Devise 4.2.0. I'm also using Devise controllers for the actual password reset functionality. The only part that differs is that my custom User's controller just initiates the password reset email.

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by nashby** [comment]
Closing this for now. @dsarhadian feel free to send sample app that reproduces this issue and we\ll try to help you. Thanks!
