### ISSUE TITLE
Devise 4.2.0 and rails-observers generates circular dependency

### ISSUE THREAD

**Issue by tigris** [plataformatec/devise#4242]
I was using devise 4.1.1 and decided to upgrade to 4.2.0

Upon upgrade, I get the following error. https://gist.github.com/tigris/ddc14d23703b23cd806a7eb39561abd4

Firstly I confirmed that going back to 4.1.1 worked, which it did. Next I tried going through the stack trace seeing where a conflict might be. I thought it odd that the rails-observers gem was being referenced in there, so I decided to take that out of my app temporarily.

Sure enough, as soon as I took rails-observers out of my Gemfile, and removed the 1 line of setup it needs from application.rb, then devise 4.2.0 was working fine.

**Comment by lucasmazza** [comment]
@rafaelfranca this one seems to be a conflict due on the `ActiveSupport.on_load` hooks due the change we did on Devise, do you have any idea on what we can do (either on devise or on rails-observers side)?

**Comment by rafaelfranca** [comment]
@tigris could you try rails-observers master? We already changed that part of the code and I believe it is already fixed.

**Comment by tigris** [comment]
I can confirm rails-observers 0.1.3.alpha fixes this.

**Comment by lucasmazza** [comment]
Awesome 😄 I'm closing this one.
