### ISSUE TITLE
Sign Up integrated test failed in devise 4.2,worked in 3.5.1

### ISSUE THREAD

**Issue by qx** [plataformatec/devise#4243]
[Here is repo](https://github.com/qx/devise_capybara) just test for devise test
```
  1) User registers with valid details
     Failure/Error: raise EmailSpec::CouldNotFindEmailError, "Could not find email #{error} in the mailbox for #{current_email_address}. \n Found the following emails:\n\n #{all_emails.to_s}"
     
     EmailSpec::CouldNotFindEmailError:
       Could not find email with subject "Confirmation instructions" in the mailbox for tester@example.tld. 
        Found the following emails:
     
        []

```

**Comment by lucasmazza** [comment]
@qx for you to test confirmation emails when using transactional tests on Rails 4 you need to add the `test_after_commit` gem when using Devise 4.1 - we moved the `after_create` callbacks to `after_commit` ones - here's the [note about on our CHANGELOG](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#410).
