### ISSUE TITLE
Devise 4.2.0 On Rails 5.0.0 - Not Permitting :email or :name

### ISSUE THREAD

**Issue by NorCalDavid** [plataformatec/devise#4244]
I have an existing application that I wanted to upgrade to Rails 5 since I have other applications running Rails 5 with similar configurations.  When I upgrade to Rails 5.0.0 the :email and :name values are not permitted.  I went to review the previous application configuration and realized that it was running on Rails 5.0.0.rc2. I upgraded second application to Rails 5.0.0 and received the same exact error.  When I went back to the existing application and changed to Rails 5.0.0.rc2 it works again.  Is there a configuration change that I need to account for to upgrade to Rails 5.0.0.

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
