### ISSUE TITLE
Nomethod Error on rails5 omniauth-facebook

### ISSUE THREAD

**Issue by kbsc332** [plataformatec/devise#4246]
i got on error when i click user_facebook_omniauth_authorize_path

-Error Message-
NoMethodError (undefined method `persisted?' for nil:NilClass):

app/controllers/users/omniauth_callbacks_controller.rb:7:in `facebook'

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
