### ISSUE TITLE
Limited number of fields displayed for user records in rails console

### ISSUE THREAD

**Issue by RogerE** [plataformatec/devise#4249]
After upgrading to Devise 4.2.0 when displaying a user record in the rails console, for instance by running 'User.first', we are only seeing 'id', 'email', 'created_at', 'updated_at' and the custom fields we have added ourself. So for instance 'encrypted_password' is not displayed, but we can still access it directly eg. 'User.first.encrypted_password'.

We're on Rails 4.2.7, upgraded from 4.1.1.

**Comment by sivagollapalli** [comment]
Issue persists only with `4.2` only. On `4.1` it displays all fields. I am using rails `4.2.5` and mongoid `5`

**Comment by j3ck** [comment]
👍

**Comment by lucasmazza** [comment]
This was added on #4140 to prevent sensitive data to leak on exceptions or log messages that use the record instance directly.
