### ISSUE TITLE
Get current_user inside initializer file

### ISSUE THREAD

**Issue by nurbs999** [plataformatec/devise#4251]
This is more a feature request than a bug. To lock doorkeepers OAuth endpoints I added this to my doorkeeper initializer file

    admin_authenticator do
      redirect_to(root_url) unless session["warden.user.user.key"]
        if session["warden.user.user.key"]
          current_user = User.find_by_id(session["warden.user.user.key"][0][0])
          if current_user
            current_user.admin? || redirect_to(root_url)
          end
        end
      end
    end

I don't think that this is very secure since one could just create a cookie and test every User id. My question is this: Is there a better way inside an initializer file to determine whether a user is really logged in? 'current_user' is not available inside initializer files.

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
