### ISSUE TITLE
Limiting user login instance.

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4252]
Devise allows to login user from multiple browser same time. Is there is any method to limit this. Suppose I have  2 Organizations as  clients and I want not more than 5 simultaneous login for one organization and 10 simultaneous login for another. How do I achieve this ? I search over internet and no suitable method found. Please help. Thanks in advance.

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
