### ISSUE TITLE
Cannot add addition fields to the users. Get an error undefined method.

### ISSUE THREAD

**Issue by ecroow** [plataformatec/devise#4253]
Hello!

As the title says, I get an error undefined method when I try to add a column to the user.

Ruby - 2.3 Rails - 4.2.5 I'm using c9 as a cloud IDE.

What I do is to first: "rails g migration AddFieldsToUsers" 

Then I add that into the DB:

 class AddFieldsToUsers < ActiveRecord::Migration
  def change
    add_column :users, :username, :string
    add_column :users, :current_goals, :text
    add_column :users, :achieved_goals, :text
  end
end

I run "rake db:migrate"

I create a registration_controller.rb

class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:current_goals, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

I add that into the routes: "devise_for :users, :controllers => { registrations: 'registrations' }"

I add the appropriate fields to the views, and when I open up the "users/edit" page, I get this error: 
undefined method `current_goals' for #<User:0x00000004e892f8>
Did you mean?  current_password

I've tried this twice on two projects, and I got the same error.

Thank you for your time!

**Comment by lucasmazza** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by ecroow** [comment]
Hello! 

Thank you for your response, but I've already fixed the problem, by deleting the database and creating a new migration.
