### ISSUE TITLE
How to run devise by ActiveResource ( RESTFUL API ) instead of ActiveRecord

### ISSUE THREAD

**Issue by astrung** [plataformatec/devise#4254]
By default, using ActiveRecord in rails , we save data into database.
But in my case , instead of save into database , i need to create a request to a RESTFUl webservice , so i need to use ActiveResource instead of ActiveRecord in Model.
But when i replace ActiveRecord by ActiveResource in Model , i get this error :
 
**_Uncaught exception: undefined method `devise' for User:Class_**

My model code : 
`class User < ActiveResource::Base`
  `self.site = "http://127.0.0.1:5000"`
  `# Include default devise modules. Others available are:`
  `# :confirmable, :lockable, :timeoutable and :omniauthable`
  `devise :database_authenticatable, :registerable,`
         `:recoverable, :rememberable, :trackable, :validatable`
`end`

How can i use Devise with ActiveResource ?

**Comment by astrung** [comment]
How can i do it ? Or can i find other gem which can do it ??

**Comment by lucasmazza** [comment]
Would be necessary for someone to implement a `devise-activeresource` plugin to plug Devise into Active Resource, similar to how we integrate with [Active Record](https://github.com/plataformatec/devise/blob/master/lib/devise/orm/active_record.rb) and [Mongoid](https://github.com/plataformatec/devise/blob/master/lib/devise/orm/mongoid.rb), to include the Devise modules on your models and cover any missing API (like how we use `orm_adapter` for that), but that's is currently out of the scope for `devise` to handle by default.
