### ISSUE TITLE
Admin Support

### ISSUE THREAD

**Issue by babind** [plataformatec/devise#4256]
Is there a provision for this gem to support facility like 
   If a admin user login into your system and he/she can create as many users as he/she wants ,then the users(normal user) can sign in through the admin created credential ... when i look at the database there is boolean field to be user that means anyone can be admin . However , i want one system admin who can manage create users as normal crud and thus created user can login in using the credential given by admin ?

**Comment by lucasmazza** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
