### ISSUE TITLE
Calling a function after timeout before sign_out calls.

### ISSUE THREAD

**Issue by prdpspkt** [plataformatec/devise#4257]
I searched over internet but couldn't find if there is any method that is called when timeout occurs and the method is override-able. Please help.

**Comment by lucasmazza** [comment]
No, there isn't. We could either implement a method call inside the `timeoutable` hook (Pull Requests welcome 😄 ), or you could implement a custom `FailureApp` that does app specific behavior when warden throws a `: timeout`.
