### ISSUE TITLE
Devise 4.2.0  Browser sends GET request on page reload after unsuccessful form submission.

### ISSUE THREAD

**Issue by ibarchenkov** [plataformatec/devise#4258]
With Rails 5 and default devise routing settings after unsuccessful form submission on /users/sign_up I'm being redirected to /users path. After that I reload the page in my browser and it sends GET request to /users path and receives 'No route matches [GET] "/password"'.
With Rails 4 and Devise 3 a browser sends POST request performing form resubmission as I expect.
Any suggestions how to make things work as it used to be? Thanks in advance.

**Comment by ubik86** [comment]
I had the same effects as you @ibarchenkov. After page reload on unsuccessful sign_up  devise/registrations#create it redirect to no route users#index.  It looks like bug. 

```console
Routing Error
No route matches [GET] "/users"
```

<img width="1124" alt="devise reload sign_up" src="https://cloud.githubusercontent.com/assets/165675/17995491/7ffb68c0-6b62-11e6-8d91-d51ab097cd0d.png">


I used temporary workaround in /config/routes.rb :

```ruby
devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'},
```

after unsuccessful sign_up and reload will redirect you to root_path.

**Comment by tegon** [comment]
Closing in favor of #4573
