### ISSUE TITLE
Invalid email addresses are showing as valid

### ISSUE THREAD

**Issue by jeffblake** [plataformatec/devise#4268]
I'm using the `validatable` module Some examples:

vicente.xxxxxx@gmail.com)
mailto:martyn.xxxxx@thetimes.co.uk

And some special characters:

�osvaldobukovski@hotmail.com

Are being allowed through.

**Comment by theRealNG** [comment]
Facing the same issue. Using devise 4.2 and emails ids such as `abc@abc,com`, `abc@abc.com,` & `abc@abc.com.` are all returning as valid.

**Comment by Guitaronin** [comment]
Just ran into this.  Looks like the new default regex only validates that the domain doesn't contain "@" or "\s".  The old regex didn't validate against space chars. :(

You can set your own regex in config/initializers/devise.rb with:
`config.email_regexp = /\A[^@\s]+@([^@\s\.]+\.)+[^@\s\.]+\z/`

The above is a hybrid of the old and new defaults (rejects commas and spaces).

**Comment by nashby** [comment]
Yeah, if you need some more strict validation on email you can redefine it in config. See full answer here https://github.com/plataformatec/devise/issues/3820
