### ISSUE TITLE
rails generate devise:install

### ISSUE THREAD

**Issue by carlosalan** [plataformatec/devise#4269]
Hi,

I'm using rails 5 with devise 4.2.0.

I have this problem

```bash
$ rails generate devise:install
Could not find orm_adapter-0.5.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by sivagollapalli** [comment]
@carlosalan  Just now I checked with new rails 5 app and latest devise version. It works well.  Might be I missing something. Could you share `Gemfile` and `Gemfile.lock` to cross check?

**Comment by prdpspkt** [comment]
Running the command `gem install orm_adapter -v 0.5.0` solves the problem

**Comment by carlosalan** [comment]
@prdpspkt It worked thanks!
@sivagollapalli thanks!
