### ISSUE TITLE
Could not cleanly terminate all actors after devise:install

### ISSUE THREAD

**Issue by CharlieHawker** [plataformatec/devise#4270]
Hi,

Not sure what's causing this, but just done `rails g devise:install` on a Rails 5.0.0.1 repository (using devise 4.2.0) I'm working on, and, in addition to the usual output regarding needing to set up mailer options etc, I get the following output:

```
E, [2016-08-24T17:44:35.246531 #56232] ERROR -- : Couldn't cleanly terminate all actors in 2 seconds!
```

Not sure if this should be cause for concern...

**Comment by lucasmazza** [comment]
@CharlieHawker that output is generated by Celluloid - please see celluloid/celluloid#696 and other related tickets on t eh celluloid repo.
