### ISSUE TITLE
Session not properly terminated after sign out. 

### ISSUE THREAD

**Issue by pbssubhash** [plataformatec/devise#4272]
Hey, In my application, when the user is logged in, I capture the cookies and paste them to clipboard. I logout silently and then again when I replay the request with the previous cookie importing them from clipboard, I'm logged in. 
P.S. Using EDITTHISCOOKIE Addon on chrome. 

I'm not sure if this effects all the devise versions or just mine, How can I patch it? I want the session to be invalidated and even if the cookie is used, I don't want the user to be logged in. It's a security issue. 

Thanks.

**Comment by TylerRockwell** [comment]
I can confirm Devise 4.2.0 is vulnerable to the cookie replay attack mentioned above.

The current manual implementation is to create an additional field on the `User` model called something like `current_user_session_id`. When the user logs in, copy the session cookie to `current_user_session_id`, and validate it on any page that requires authentication. Once the user logs out, delete the cookie from `current_user_session_id` so the session is _really_ destroyed and that cookie may never be used again.

**Comment by josevalim** [comment]
You should choose another session store besides the cookie store. That's a direct consequence of using the cookie store and if you pick another store such issues won't happen.

**Comment by dkniffin** [comment]
@josevalim Any chance you have an example of how to do that? I can't seem to find much documentation on using other session stores.

**Comment by mrusa** [comment]
@dkniffin In case you didn't found anything yet, this could be what you've been looking for https://github.com/rails/activerecord-session_store
