### ISSUE TITLE
Does Devise 4.2 disable sending emails on test environment?

### ISSUE THREAD

**Issue by mmhan** [plataformatec/devise#4281]
I was trying to update my devise gem to 4.2, and I found a failing feature in my cucumber tests.

I am using email_spec to view the content of the email sent and there doesn't seem to be any mail sent at all. 

I also couldn't find the email in the logs too.

If it's not the default behavior, I will continue to furnish this issue. Just checking before digging deeper.

**Comment by lucasmazza** [comment]
We don't have any email delivery changes on 4.2 - check if it might be something regarding your Action Mailer / Active Job configuration on test environment that might be affecting your test code.

**Comment by aceunreal** [comment]
@mmhan I'm having the exact same issue. How did you resolve it?

Cheers
