### ISSUE TITLE
Switching locales with url_for(locale: "en") on devise pages loads wrong devise scope when using multiple devise models.

### ISSUE THREAD

**Issue by michaelshmitty** [plataformatec/devise#4282]
**Situation**
A rails application with two locales ('en' and 'nl').
Devise on two models: Client and User.
A link in the application layout that allows you to switch locales on any page.
This link is generated in a helper method like so:
`link_to("EN", url_for(locale: "en"))`
(and vice versa for link to the NL version of the page).
Switching locales works as expected on every non-devise page in the application.

**Problem**
On any devise related page (sign up, sign in, forgot password, etc.) it always generates the url to the first devise scope declared in the routes.rb file. In my case `devise_for :user`.
This means that when I am on the English `/en/clients/sign_in` page, the locale switch link points to the Dutch `/nl/users/sign_in` page instead of the Dutch `/nl/clients/sign_in` page.

When I change the order of the devise_for calls in the routes.rb file, the problem reverses: the locale links on any user related devise page incorrectly brings you to the `/clients/...` devise pages.

Inspecting `devise_mapping` on the page shows that it does know of the correct scope.

I post this issue after scouring the web for an hour or so. Does anyone understand what is going on here and possibly have a solution?

Many thanks!

**Comment by michaelshmitty** [comment]
Interesting:
The problem disappears when I override the sessions controller for each Devise model (e.g. `devise_for :clients, controllers: { sessions: "clients/sessions" } with a simple blank clients/sessions_controller.rb that inherits from Devise::SessionsController.

Could it be that somewhere at the time of the call to url_for(), the application does not know of the current resource_name and just uses the default one?

**Comment by goalaleo** [comment]
I am facing the same issue. On /users/sign_in changing the locale with a link also changes url to /admins/sign_in, and device_for :admins is defined first.

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
