### ISSUE TITLE
Rails 5 custom devise controller not working 

### ISSUE THREAD

**Issue by naveen1336** [plataformatec/devise#4286]
server log:

Started GET "/users/sign_up" for 127.0.0.1 at 
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".\* FROM "schema_migrations"
Processing by RegistrationsController#new as HTML
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 46ms (ActiveRecord: 0.9ms)

my custom controller:

class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end
  def create
    # add custom create logic here
    super
  end

  def update
    super
  end
end 

Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

end

**Comment by ethirajsrinivasan** [comment]
@naveen1336  @SuTran  can you please provide a sample application

**Comment by iamfree-com** [comment]
Sorry a bit late to reply. This is how it worked my ways
"config/routes.rb"
Rails.application.routes.draw do
devise_for :users, :controllers => {: registrations => "users/registrations" }
 
end


"users/registrations_conroller.rb"

class Users:: RegistrationsController < Devise::SessionsController

   
end
