### ISSUE TITLE
Rails 5 email is always unpermitted in custom controller

### ISSUE THREAD

**Issue by ryotakurashiki** [plataformatec/devise#4288]
Started POST "/admins" for ::1 at 2016-09-11 21:36:37 +0900
Processing by Admins::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"zEoZyN3Y9rUlYX0jP2qK2pnd3zKqJyGdS5qAwH2yA+7C2MwrtHds/iXXp8OZ+7PmdBzndmG92vy/wV2kvxDf5w==", "admin"=>{"email"=>"email@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
Unpermitted parameter: email

**Comment by ethirajsrinivasan** [comment]
@ryotakurashiki  can you please provide sample application
