### ISSUE TITLE
add scope for confirmed accounts

### ISSUE THREAD

**Issue by klyonrad** [plataformatec/devise#4290]
small feature request:

I think it would be nice, if devise provided this kind of scope for the models:

`scope :confirmed, where('confirmed_at IS NOT NULL')`

**Comment by sivagollapalli** [comment]
+1. @lucasmazza let me know your suggestions. I would like to add this.

**Comment by georgeguimaraes** [comment]
Since you can add the scope on your model, I'm closing this issue.
