### ISSUE TITLE
Refactoring: do not mutate warden config

### ISSUE THREAD

**Issue by HoneyryderChuck** [plataformatec/devise#4291]
I've been experimenting with exposing the middleware of a rails app into a a rack URL Map, and I've been having some issues with it in general, and particularly with devise. Here is the summary of them which could be the subject of some internal refactoring:
## limit access to warden config

Regarding the [block passed to the warden manager](https://github.com/plataformatec/devise/blob/master/lib/devise/rails.rb#L9-L11), it will mutate the `Devise.warden_config` global variable each time the block is run. In a normal rails app (the standard approach) this will happen only once, but if I pass the middleware to other apps, the block will be run multiple times, also after the failure app has been set (which happens when the rails routes are initialized). The block 2nd run will therefore reset the `Devise.warden_config` variable. This can be mitigated by doing:

``` ruby
    config.app_middleware.use Warden::Manager do |config|
      Devise.warden_config ||= config
    end
```

as it is done with `Devise.secret_key` a few lines below. 
## always use `Devise.warden_config` in the devise warden middleware

None of this will matter if the [manager is always initialized with a new set of options](https://github.com/hassox/warden/blob/master/lib/warden/manager.rb#L21). I think this could be solved by making Devise have its own manager, by subclassing the warden manager:

``` ruby
class Devise::Manager < Warden::Manager
  attr_reader :config
  def initialize
     super
     @config = Devise.warden_config
  end
end

# on lib/devise.rb
  mattr_accessor :warden_config
  @@warden_config = Warden::Config.new

# on lib/devise/rails.rb
config.app_middleware.use Devise::Manager

```

Most of this is (it seems) private API, so the breaking impact would be low. The short-term benefits would be arguably low, as currently there is no way to use Rails middleware in pure Rack apps. The benefit would be less global variable mutations in the source code. The main benefit is however unachievable without rails "shareable" middlewares, so I'll accept if this conflict makes this refactoring useless.

**Comment by tegon** [comment]
Hello, @HoneyryderChuck thanks for your suggestions.
Those are interesting points, but as you said the refactor won't be much useful for us. Specially considering the fact that `devise` only supports `Rails`. Even if we do this you might have other problems to make it run without it.

Thanks again!
