### ISSUE TITLE
Multiple user models with single login page, single sign up page?

### ISSUE THREAD

**Issue by raintears** [plataformatec/devise#4293]
I'm trying to do that but it became a mess. Is that possible?

Right now, I have one devise User model, and I have these 3 models: Employer, Candidate and Admin. They all inherit from User. User has fields like email, password, type and some rememberable, confirmable stuffs.

I can do a single sign in page with that because of the User type field. But I can't do a single sign up page. Is there something I need to overwrite here? Please help!

Also, I'm using oauth. It's now written at the User model but I only want to use that for Candidate and not the other 2 models. Is that possible?

Thanks!

Update:
I guess I have to supply new instances of @employer and @candidate to my sign up page so this is what I did in registration controller:

def new
super
@candidate = Candidate.new
@employer = Employer.new
end

Is this the right way? How can I pass in 2 resource to one signup page?

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
