### ISSUE TITLE
sign_out don't work with link_to but when use button_to it works!

### ISSUE THREAD

**Issue by dariubs** [plataformatec/devise#4294]
In one of my rails app sign_out don't work with link_to but when use button_to it works!
I find button_to the solution in [this link](http://stackoverflow.com/questions/26861539/logout-does-not-working-in-production-environment) but I don't understand!
Anybody know why this problem is happening with devise?

**Comment by carlosantoniodasilva** [comment]
`button_to` creates an actual html form with a `_method` hidden field, which will tell rails what to do. `link_to` will rely on the javascript ujs library to handle the click on the link and create a form that is then submitted.

So basically `button_to` will work without the js ujs library, and `link_to` requires it - if you don't have it `link_to` won't work. I hope that helps.
