### ISSUE TITLE
valid_for_authentication? always returning true

### ISSUE THREAD

**Issue by chrisokamoto** [plataformatec/devise#4295]
I'm facing a problem when trying to log into the system that even if I try to login with the wrong credentials the method "valid_for_authentication?" returns true. 

I opened this question on StackOverflow but couldn't resolve it yet: http://stackoverflow.com/questions/39479779/lockable-devise?noredirect=1#comment66279201_39479779

Can anybody help me?

**Comment by penguinpowernz** [comment]
@chrisokamoto how did you fix it!?
