### ISSUE TITLE
Handling confirmation_token invalid for old confirmation token

### ISSUE THREAD

**Issue by arun-manthani** [plataformatec/devise#4297]
![Uploading confirmation_token_error.png…]()
When user first registers/Sign up a confirmation token is generated and need to confirm his account from email works absolutely fine.

Case2: When user requests "Resend Confirmation instructions" again, new confirmation token will be generated and sent to mail.

However, when user clicks on old confirmation token mail instead of new... it says "Confirmation token is invalid". 

Can i know how better we can handle it further..

**Comment by avinoth** [comment]
@arun-manthani It is meant to be, to have one valid confirmation token at a time. On requesting new token, old one is overwritten on the DB.

> Can i know how better we can handle it further..

You mean to handle multiple confirmation tokens or the error message that the user sees when they click the old link?

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
