### ISSUE TITLE
password reset token expires before the configured time period

### ISSUE THREAD

**Issue by anadimisra** [plataformatec/devise#4298]
Rails Version: 5.0.0.1
Devise Version: 4.2

In my devise.rb file I define lifetime for password token to be 6 hours

```
  # Time interval you can reset your password with a reset password key.
  # Don't put a too small interval or your users won't have the time to
  # change their passwords.
  config.reset_password_within = 6.hours
```

When I opt for password reset through the Forgot Password link, I can see the timestamp and token generated

```
postgres=> select reset_password_token, reset_password_sent_at from users where email='email@gmail.com';
                       reset_password_token                       |   reset_password_sent_at
------------------------------------------------------------------+----------------------------
 89f51bce1bc6b495c16a50b015d03897d0520a8b58c300a5deef16b2c45cac82 | 2016-09-16 21:18:01.322362
```

Recoverable is enabled too 

```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :timeoutable
end
```

Active record and application timezone are both set to 'Asia/Kolkata' but when I click on the link delivered in email and try changing password (which is within minutes of the email delivered) the password change fails with message 

Reset password token has expired, please request a new one

**Comment by avinoth** [comment]
Your code looks fine, Did you restart the application after changing the configuration?

**Comment by anadimisra** [comment]
Yup I did!

**Comment by nashby** [comment]
@anadimisra hey, do you still have this issue? That's the code that check time interval https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/models/recoverable.rb#L72. Can you please check what values of `reset_password_sent_at.utc` and `self.class.reset_password_within.ago.utc`?

**Comment by shirjeel-alam** [comment]
Rails: 4.1.6, Devise: 3.5.10
Facing same issue i.e. reset_password_sent_at becomes nil when I reload the user model or query for the user again.

**Comment by sushant12** [comment]
facing the same issue

**Comment by anadimisra** [comment]
@nashby sorry for the delay, I'll look into this right away and update the thread

**Comment by ukolovda** [comment]
I have same trouble. I have real value in database, but in model reset_password_sent_at always is nil.
I override method in User model:
```
  def reset_password_period_valid?
    reset_password_sent_at.nil? || super
  end
```

**Comment by tegon** [comment]
Can someone provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by ukolovda** [comment]
@tegon, after I updated to latest Devise and Devise_invitable (and remove devise-async), error gone.

**Comment by tegon** [comment]
@ukolovda Ok, thank you!
