### ISSUE TITLE
Sanitizing request parameters for bad data

### ISSUE THREAD

**Issue by jeffjo** [plataformatec/devise#4303]
Hello, I would like to sanitize any request parameters (eg email, password, etc.) before Devise authenticates the user. Specifically, I'd like to strip any null bytes since this is causing the pg gem to throw an exception. What is the best way to do this? I've looked in the BaseSantizer code, but AFAICT, this class is used to configure the names of the parameters that Devise accepts and I don't think it allows you to modify the values in any way.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
