### ISSUE TITLE
After User Logged in when the admin inactive the user in devise

### ISSUE THREAD

**Issue by mahi06** [plataformatec/devise#4305]
After use successfully logged in and his doing his operations but the admin inactivated the user,the session will expire and goes to login page.Is this is possible in devise

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by mahi06** [comment]
I tried in StackOverflow also but i couldn't any solution please help me
