### ISSUE TITLE
Allow users to edit without password (password doesn't persists)

### ISSUE THREAD

**Issue by Pedroknoll** [plataformatec/devise#4308]
Hello,

I'm new to the Rails so, probably, I'm forgeting something here.

**Rails version: 5.0.0.1 
Devise version: 4.2.0** 

I'm using a custom controller to user scope.

```
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :sign_up_params, only: [:create]
 before_action :account_update_params, only: [:update]

  protected

  def sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :cpf])
  end

  def account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :cpf, :birth_date, :phone, :gender])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end
```
The routes

```
    Rails.application.routes.draw do
    devise_for :users, controllers: { sessions: 'users/sessions'},
        skip: :registrations
            devise_scope :user do
                resource :registration,
                    only: [:new, :create, :edit, :update],
                    path: 'users',
                    path_names: { new: 'sign_up' },
                    controller: 'users/registrations',
                    as: :user_registration do
                        get :cancel
                    end
            end
      end
```

Everything was working until include the **update_resource(resource, params)** method to the controller and remove the **current_password field** at the view, as suggested https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password

After this change I can edit every additional fields (first_name, last_name...etc) except the password. The password change doesn't persists. Any idea?

**Comment by Shwetakale** [comment]
@Pedroknoll You don't want the password to be changed right? Because as per documentation it will allow every field to be edited except ```email``` and ```password``` and this is what you are getting.

Is there something which you want to point out and I am missing?

**Comment by Pedroknoll** [comment]
Hello @Shwetakale ,

I want to allow the users to change the password and e-mail.

With that method the user can change the e-mail by e-mail confirmation, but I can't change their password. 

So, what is the best approach to permit user to change both e-mail and password without require the current password. Any idea?

**Comment by Shwetakale** [comment]
@Pedroknoll I think after changing email if you are sending confirmation link then that link should point to reset password route so from there user will change the password and log in . Check this [link]    (https://github.com/plataformatec/devise/blob/master/lib/devise/models/recoverable.rb). Hope this helps.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
