### ISSUE TITLE
after_sign_in_path_for reloads session#new

### ISSUE THREAD

**Issue by alexanderritola** [plataformatec/devise#4313]
In order to get `after_sign_in_path_for` to work as expected, I've needed to override `session#create` like this, without this override, upon successful sign in, the `session#new` template is reloaded along with a successful login flash notification.

```ruby
class Users::SessionsController < Devise::SessionsController
 # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_to do |format|
      format.html { redirect_to after_sign_in_path_for(resource) }
    end
    #respond_with resource, location: after_sign_in_path_for(resource)
  end
end
```

I'm not really sure how to debug this to figure out exactly what's going wrong in my application but I think I definitely shouldn't be needing to do this. 

Any help would be greatly appreciated!

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
