### ISSUE TITLE
Devise model

### ISSUE THREAD

**Issue by Edwardzyc** [plataformatec/devise#4314]
Models no longer get populated by some of the devise fields(such as encrypted password)

Is this documented behaviour?

**Comment by ethirajsrinivasan** [comment]
@Edwardzyc  can you ellaborate on the issue

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
