### ISSUE TITLE
have current_user return a NullObject

### ISSUE THREAD

**Issue by tansaku** [plataformatec/devise#4317]
Has anyone thought about having the devise `current_user` method return a NullObject rather than nil?

I see a related SO post:

http://stackoverflow.com/questions/27169260/guest-user-for-devise-using-null-object-pattern

I was just seeing that a nil `current_user` is at the source of a lot of checks we are doing in our rails code, and I wonder if `current_user` might be made a little more confident a la:

http://stackoverflow.com/questions/16077115/rails-replacing-try-with-the-null-object-pattern

**Comment by josevalim** [comment]
There are no plans for such although you can change it as you wish in your apps.

**Comment by tansaku** [comment]
aha https://forum.upcase.com/t/null-object-pattern-with-devise/1684/6 looks good with:

```
  def current_user
    if devise_controller?
      @current_user = super
    else
      @current_user ||= super || AnonymousUser.new
    end
  end
```
would it make sense to build such a thing into devise?

**Comment by tansaku** [comment]
ah posted across you - no plans - thanks @josevalim
