### ISSUE TITLE
Getting "Session Expired" JSON for non-Authed API Endpoints

### ISSUE THREAD

**Issue by bisrael** [plataformatec/devise#4319]
I have a routes setup that's basically:

``` ruby
Application.routes.draw do
  devise_for :users, class_name: "Admin::User"
  root to: 'root#index'

  namespace :api, defaults: { format: :json } do
    # some resources here like:
    resources :images, only: [:show]
  end

  authenticate :user do
    scope :admin do
      # several admin pages like:
      resources :images, only: [:index, :create, :show], defaults: { format: 'json' }
    end
  end
end
```

So the first time I hit an endpoint like `/api/images/20.json` after my admin session has expired, I get a `Your session has expired` JSON response.

I do not expect this, I expect the `:api` namespace to never look at the session information.

I added `skip_before_action :authenticate_user!` to my `Api::ImagesController` but it did not solve the issue.

What else am I missing?

Thanks!

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
