### ISSUE TITLE
Connection reset by peer when trying to reset password through Devise

### ISSUE THREAD

**Issue by nathantech2005** [plataformatec/devise#4320]
It must be a server issue because these settings are working fine in production.

Sorry. I found another duplicate issue. It didn't show up in the search.
https://github.com/plataformatec/devise/issues/4124

I am using Rails 5.

I think it has to do with my mailer config. The error still happens if I remove the mailer smtp settings.
# devise mailer

  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
  config.action_mailer.delivery_method = :smtp
  # care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_caching = false
  config.action_mailer.smtp_settings = {
      :address              => "smtp.zoho.com",
      :port                 => 587,
      :domain               => "zoho.com",
      :user_name            => "admin@eyehawk.io",
      :password             => "xxxxxxxxxxx",
      :authentication       => :plain,
      :enable_starttls_auto => true
  }

Ruby Version 2.3.1

Errno::ECONNRESET in Devise::PasswordsController#create

around line 178

```
if @rbuffer.empty?
  return sysread_nonblock(maxlen, buf, exception: exception)
end
ret = consume_rbuff(maxlen)
if buf
```

Stack trace is pointing to SSL as the cause.

/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in`read_nonblock'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:154:in `rbuf_fill'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:136:in`readuntil'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:946:in`recv_response'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:932:in `block in getok'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:956:in`critical'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:930:in `getok'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:924:in`quit'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:617:in `do_finish'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:524:in`ensure in start'
/Users/nathansire/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:524:in `start'

**Comment by tegon** [comment]
This error happens when SMTP server drops the connection. Are you SMTP settings setup corrected?
I'm closing this because we reserve the issues tracker for issues only. Please ask a question on StackOverflow - there more people will be able to help you.
Thanks!
