### ISSUE TITLE
Could not find generator 'devise:install'. Maybe you meant 'assets', 'generator' or 'coffee:assets'

### ISSUE THREAD

**Issue by nelsonlho** [plataformatec/devise#4322]
I added  gem 'devise' to the gemfile, then ran "bundle installed"
when I ran  rails g devise:install, the following message appeared:

Could not find generator 'devise:install'. Maybe you meant 'assets', 'generator' or 'coffee:assets'

Any ideas?

**Comment by ja7rodal** [comment]
bundle install not installed

**Comment by nashby** [comment]
Yeah, looks like you didn't install gem properly. If you did we need sample app that reproduces this issue to help you. Thanks!

**Comment by jaspertomas** [comment]
Just putting it here coz this solution is so hard to find
https://github.com/plataformatec/devise/issues/4594
In rails 5, please try to run 
spring stop 
before you run
rails generate devise:install

**Comment by pradhumnsharma** [comment]
Thanks @jaspertomas your option worked for me in rails 5.2

**Comment by devijonnalagadda** [comment]
I got the same error but nothing works for me

**Comment by cristian-programmer** [comment]
> I got the same error but nothing works for me

the same happens to me
