### ISSUE TITLE
How can we find a user by reset_password_token field value using devise gem

### ISSUE THREAD

**Issue by Imran-Haider313** [plataformatec/devise#4323]
While resetting password in ruby on rails using devise , we have reset_password_token value coming in parameters . but no email . so can any one guide me that how can we get email with the reset_password_token . My intension for this query is simple that i want to perform some more functionality on that email holder before resetting password . although i know that i can get the email just after resetting password through 
    self.resource = resource_class.reset_password_by_token(resource_params)
but i want resource value before email . Note: i tried to put reset_password_token value in where clause but seems like devise performs some encoding / decoding algo before fetching resource using token . thanks

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
