### ISSUE TITLE
function cubiq_login_init ()

### ISSUE THREAD

**Issue by giak3** [plataformatec/devise#4324]
Hi,
I have a wordpress blog and i would need to redirect the user to a specific page after he filled and submited his username and and email in the registration page. Can anyone help me, please? :(
I attached a .txt with the code.
[Cubiq.txt](https://github.com/plataformatec/devise/files/517806/Cubiq.txt)

Thanks a lot.

Giak

**Comment by Shwetakale** [comment]
@giak3 You can use ```after_sign_in_path_for``` method to redirect the user to a specific page after successful authentication. Write this method in application_controller so will be applicable for every request.

**Comment by giak3** [comment]
I am sorry, I am new with all of this. Where can i find application_controller?
Thanks

**Comment by Shwetakale** [comment]
@giak3 You are using devise with rails right?

**Comment by giak3** [comment]
Actually I bought a theme for wordpress and found the code in the function.php file:D

**Comment by Shwetakale** [comment]
@giak3 Devise gem is for ```rails``` not for ```php```. You need to find some other library for ```php```.

**Comment by giak3** [comment]
Sorry, I do not understand. The code I attached is not for php?

**Comment by nashby** [comment]
@giak3 yeah, you're missing something. Devise is for Rails framework. @Shwetakale thanks for helping out!
