### ISSUE TITLE
Send alert and notice through MDL Snackbar

### ISSUE THREAD

**Issue by Allanramirez1** [plataformatec/devise#4325]
Hi, I am building a Ruby on Rails web app, and I want to integrate devise, I am using this gem, and in front-end Material Design Lite. 

The space where snackbar is going to show up is on the bottom of my master layout. The code in Javascript to show the snackbar is this:

var snackbarContainer = document.querySelector('#demo-snackbar-example');
var data = {
      message: 'Hi, I am a Snackbar',
      timeout: 2000,
      actionHandler: handler,
      actionText: 'Undo'
    };
    snackbarContainer.MaterialSnackbar.showSnackbar(data);`

![screen](https://cloud.githubusercontent.com/assets/15525993/19217810/0f458fc2-8da2-11e6-9d76-e7b8335c9147.png)

Please help.

**Comment by Spharian** [comment]
Hi,

Not sure it has anything to do with the Devise gem, or I misunderstood your problem. Can you bring some precisions and maybe host a sample, then we can see it live?

**Comment by Allanramirez1** [comment]
I solved it... This is the code on _messages layout, then render on master layout.

```
<div id="demo-snackbar-example" class="mdl-js-snackbar mdl-snackbar">
      <div class="mdl-snackbar__text"></div>
      <button class="mdl-snackbar__action" type="button"></button>
    </div>

<% if notice %>

  <script type="text/javascript">

  $(window).load(function () {
    var snackbarContainer = document.getElementById('demo-snackbar-example');
    var data = {
    message: '<%= notice %>',
    timeout: 2000
    };
    snackbarContainer.MaterialSnackbar.showSnackbar(data);
});


    </script>

  <% end %>

  <% if alert %>

  <script type="text/javascript">
  $(window).load(function () {
  var snackbarContainer = document.getElementById('demo-snackbar-example');
  var data = {
  message: '<%= alert %>',
  timeout: 2000
  };
  snackbarContainer.MaterialSnackbar.showSnackbar(data);
  });
    </script>

  <% end %>

```
