### ISSUE TITLE
current_user eager load

### ISSUE THREAD

**Issue by Spharian** [plataformatec/devise#4326]
Hi!

I wonder how I can Eager Load on `current_user`. I don't want a global Eager Load or anything like that, I just need to Eager Load for a single action in my application.

The only solution I found:
`@current_user = User.includes([{ comments: :guest }]).find(current_user.id)`

But, of course, it makes 2 queries to find the user: 1 for `current_user`, 1 for `User...find(id)`

Any idea on this?

Regards,

Spharian

**Comment by Shwetakale** [comment]
@Spharian This is the right solution and though there will be 2 queries I think because of query caching 2nd query will not hit database so this will be the performance gain for you.

**Comment by Spharian** [comment]
@Shwetakale Indeed, it's using cache if I reproduce the exact same query:

`@current_user = User.includes([{ comments: :guest }]).order(:id).find(current_user.id)`

Thanks.

**Comment by baranyeni** [comment]
I think you may try to use joins instead includes.
