### ISSUE TITLE
Multiple Devise Models resource_name and resource error

### ISSUE THREAD

**Issue by hamzaaltaf** [plataformatec/devise#4327]
I am using multiple devise models  , I want one User1 to sign in using email and password while user2 using a unique ID that is generated by user1.  I was following this link to setup the sign in using an ID.
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

but as I changed my views I noticed that i have edited model2 views it is giving me this error
**undefined method `login' for Model1:0x007f2a914d0d10** although in the form i am passing resouce2 and resource_name2 in the login form , then why is it saying undefined method login for Model1 why not model2?

**here is my model2**

```
attr_accessor :login
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:authentication_keys => [:login]
```

This is applicationhelper

```
`def resource_name
:user1
end

def resource
@resource ||= Model1.new
end
def resource_name1
  :user2
end

def resource1
  @resource ||= Model2.new
end`
```

and lastly this is my login form for model 2

```
<%= form_for(resource1, as: resource_name1, url: session_path(resource_name1)) do |f| %>      

            <!--showing fields-->
            <div class="row">
              <div class="col-xs-offset-1 col-xs-6 field">
                 <p><%= f.label :login %><br />
                <%= f.text_field :login ,class: 'form-control' ></p>
              </div>  
            </div>

            <div class="row">
              <div class="col-xs-offset-1 col-xs-6 field">
              </div>  
            </div>

            <div class="row">
              <div class="col-xs-offset-1 col-xs-6">
                <% if devise_mapping.rememberable? -%>
                    <div class="field">
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me %>
                    </div>
                </div>
              <% end -%>  
            </div>
```

**Comment by Shwetakale** [comment]
@hamzaaltaf Where did you override this view? As per my guess you have added it in ```seesions/new.html.erb``` and as seesions_controller and views will be shared by both and you don't have ```login``` field in model1 so you are getting this error.

**Comment by Shwetakale** [comment]
@hamzaaltaf  I am not sure whether this is correct way or not but you need to check class of the resource on view and as per class need to write view code.

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
