### ISSUE TITLE
Route problem after sign up failure

### ISSUE THREAD

**Issue by hossamk** [plataformatec/devise#4328]
When invalid data are entered in the sign up form `GET users/sign_up`, the form posts to user_registration route which is `POST /users`.

This changes the URL to `/users` so if you refreshed the page it will send a request to `GET /users` which doesn't exist.

**Comment by Shwetakale** [comment]
@hossamk I don't think this is issue with devise. If you see [here](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L32) ```respond_with``` method of ```rails``` is used. Which will render action [new](http://edgeapi.rubyonrails.org/classes/ActionController/Responder.html). I created another controller and used ```respond_with``` method and got same behavior on error. So I think we need to check how ```rails``` handle this. Thoughts?

**Comment by hossamk** [comment]
@Shwetakale Right! I got the same issue with a new controller as well.
The problem is that when we make a POST request, the URL changes to the create action's route, and rendering another view in `respond_with` wont affect the URL.
so I think routes should be modified?
For example, in the sign in, the new action is `GET /users/sign_in` and the create action is the `POST /users/sign_in`.
as a result the URL wont change. So, If we used `GET /users/sign_up`, and `POST /users/sign_up`, we wont have this problem. What do you think?

**Comment by Shwetakale** [comment]
@hossamk hmm for ```sign_in``` and ```PasswordController``` devise is doing that

**Comment by hossamk** [comment]
@Shwetakale So why doesn't Devise use the same approach with `sign_up` actions to avoid this?

**Comment by nashby** [comment]
@hossamk hey, you can easily change routes if you need some custom behaviour. See examples here https://github.com/plataformatec/devise/wiki/How-To:-Change-Default-Sign_up---Registration-Path-with-Custom-Path
