### ISSUE TITLE
Subdomain authentication

### ISSUE THREAD

**Issue by Frank004** [plataformatec/devise#4330]
How can I use this code if the Subdomain column is in company
And User belongs_to :company 
```":subdomain => warden_conditions[:subdomain]"```

```
# app/models/user.rb
class User < ActiveRecord::Base
  def self.find_for_authentication(warden_conditions)
    where(:email => warden_conditions[:email], :subdomain => warden_conditions[:subdomain]).first
  end
end
```

maybe something like this

``` self.company.subdomain == warden_conditions[:subdomain]```

**Comment by Shwetakale** [comment]
@Frank004 Which ORM (database) you are using? If you are using ```ActiveRecord``` you can achieve above using following query

    joins(:company).where(email: warden_conditions[:email], companies: {subdomain: warden_conditions[:subdomain]}).first

but if you are using ```Mongoid``` then you need to fire 2 queries as it does not support ```joins```.

**Comment by Frank004** [comment]
Thank you @Shwetakale  and yes I'm using ```AR```
