### ISSUE TITLE
Recoverable#reset_password allows setting empty passwords

### ISSUE THREAD

**Issue by capicue** [plataformatec/devise#4333]
The following request bypasses password validations and results in a user with an empty password. (Specifically this happens when the password and password_confirmation fields are missing and not just empty strings.)
```
PUT users/password
params: {
  user: {
    reset_password_token: "correct_token"
  }
}
```

For reference, the current check to determine if passwords should be validated is
```ruby
module Devise::Models::Validatable
  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end
end
```

**Comment by ethirajsrinivasan** [comment]
@capicue Can you provide more details on the issue.When is it happening?

**Comment by capicue** [comment]
My confusion was in the fact that `user.reset_password("", "")` results in errors on the model, but `user.reset_password(nil, nil)` does not. I have since realized that the latter does not actually reset the password and my above concerns are not valid.

Closing this issue. Sorry to bother!
