### ISSUE TITLE
Using OmniAuth without other authentications throws `undefined method password`

### ISSUE THREAD

**Issue by DEfusion** [plataformatec/devise#4334]
I followed the instructions here: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#using-omniauth-without-other-authentications

I removed `:database_authenticatable` from my `User` class and then I get an error saying `undefined method 'password'` on the `first_or_create` call.

```
def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.name = auth.info.name
    end
  end
```

If I don't do those things everything works as expected.

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
