### ISSUE TITLE
Adds confirmable 

### ISSUE THREAD

**Issue by jimboqu** [plataformatec/devise#4335]
Hi there

I'm having a problem with the migration for adding :confirmable to users. 

I'm using Rails 5 and when I try to migrate it is showing the following error:

`SQLite3::SQLException: no such function: NOW: UPDATE users SET confirmed_at = NOW()`

Many thanks for taking a look at this.

Jimboqu

**Comment by ethirajsrinivasan** [comment]
@jimboqu  can you please provide sample application

**Comment by jimboqu** [comment]
Yes, here you go. Thanks for taking a look.

[emo.zip](https://github.com/plataformatec/devise/files/550864/emo.zip)

**Comment by nashby** [comment]
@jimboqu hey, it even says in your migration file:

```
# Use :date('now') instead of :NOW when using SQLite.
# => execute("UPDATE users SET confirmed_at = date('now')")
```

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
