### ISSUE TITLE
Add an option to prevent IP saving on trackable

### ISSUE THREAD

**Issue by scan** [plataformatec/devise#4336]
We like to use `trackable` to have information about if and when a user has logged in before. However, there are some privacy concerns regarding the automatic saving of the user's IP address. Right now `trackable` does not provide any mechanism to prevent recording the IP address.

For now we override the method in our user class:

```ruby
  def update_tracked_fields(request)
    old_current, new_current = self.current_sign_in_at, Time.now.utc
    self.last_sign_in_at     = old_current || new_current
    self.current_sign_in_at  = new_current

    self.last_sign_in_ip     = nil
    self.current_sign_in_ip  = nil

    self.sign_in_count ||= 0
    self.sign_in_count += 1
  end
```

However, it would be nice to have a configuration option to disable this feature properly.

**Comment by ethirajsrinivasan** [comment]
@josevalim  @lucasmazza do you think the configuration mentioned above is a good feature to add on

**Comment by lucasmazza** [comment]
@ethirajsrinivasan I don't think a config is worth for this case - developers can override the `update_tracked_fields` on their models and remove the assignment of the `last_sign_in_ip`/`current_sign_in_ip` attributes on their own.
