### ISSUE TITLE
BCrypt::Errors::InvalidHash - invalid hash occurs after upgrade from 3.2.18 to 4.2.6 version

### ISSUE THREAD

**Issue by jvkiran** [plataformatec/devise#4341]
BCrypt::Errors::InvalidHash - invalid hash  
bcrypt (3.1.11) lib/bcrypt/password.rb:60:in `initialize'
  devise (4.2.0) lib/devise/encryptor.rb:14:in`compare'
  devise (4.2.0) lib/devise/models/database_authenticatable.rb:45:in `valid_password?'
  app/controllers/users/sessions_controller.rb:33:in`create'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'

This error occurs when devise upgrade from 3.2.18 to 4.2.6, problem with 3.2.18 app users login.

Devise 2.1.2 in rails 3.2.18 version, Devise 4.2.6 in rails 4.2.6 version

**Comment by ethirajsrinivasan** [comment]
@jvkiran a sample application with the bug would be of great help
