### ISSUE TITLE
rails 5 capybara spec 

### ISSUE THREAD

**Issue by kivanio** [plataformatec/devise#4342]
Hi,

I am migrating an app to rails 5 and I got this error from my specs for a custom devise controller:
<pre>
1) User confirmations 
     Failure/Error: skip_before_action :require_no_authentication
     
     ArgumentError:
       Before process_action callback :require_no_authentication has not been defined
     # ./app/controllers/confirmations_controller.rb:4:in `<class:ConfirmationsController>'
     # ./app/controllers/confirmations_controller.rb:1:in `<top (required)>'
     # ./spec/features/user_confirmations_spec.rb:7:in `block (3 levels) in <top (required)>'
</pre>

After researches I found out that something changed at rails 5 and that's why it fails now.

If I comment both lines, specs works, but it is not the behavior I want.
<pre>
  #skip_before_action :require_no_authentication
  #skip_before_action :authenticate_user!
</pre>

What have I missed?

reference: https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
code sample:
<pre>
# gems
gem 'rails',                      '5.0.0.1'
gem 'devise',                     '4.2.0'

# custom controller
class ConfirmationsController < Devise::ConfirmationsController
  skip_before_action :require_no_authentication
  skip_before_action :authenticate_user!

  # PUT /resource/confirmation
  def update
#     do things
  end  
end

# capybara
require 'capybara/rspec'
require 'capybara/rails'
require 'capybara/poltergeist'

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, timeout: 60)
end

Capybara.javascript_driver = :poltergeist
Capybara.default_max_wait_time = 5

RSpec.configure do |config|
  config.include Capybara::DSL, file_path: %r{\bspec/features/}
end

# devise
RSpec.configure do |config|
  config.include Devise::Test::ControllerHelpers, type: :controller
end

# spec
require 'rails_helper'

RSpec.describe 'ConfirmationsController' do
  context 'confirmations' do
    it do
      visit new_user_confirmation_path
      expect(page).to have_content 'E-mail...'
      expect(page).to have_link 'Return...'
    end
  end
end
</pre>

**Comment by nashby** [comment]
@kivanio hey! It's known issue with rails 5. See https://github.com/plataformatec/devise/issues/4207

**Comment by kivanio** [comment]
thank you @nashby
