### ISSUE TITLE
Confirmations controller create action is not used

### ISSUE THREAD

**Issue by aurimus** [plataformatec/devise#4345]
To reproduce:
Override the Confirmations Controller like so:
```
class Users::ConfirmationsController < Devise::ConfirmationsController

  def create
    byebug
  end

end
```

And in routes:
```
devise_for :users, controllers: { 
  passwords: 'users/passwords', 
  sessions: 'users/sessions',
  confirmations: 'users/confirmations',
}
```

The overriding works with other models. But the create action in confirmations controller is never called. I put a lot of byebug statements all around the Gem itself, and it seems even the original create action is not called, but the email is sent anyway. I am using sidekiq for delayed emails. The only place that is run seems to the mailer:

```
def confirmation_instructions(record, token, opts={})
  byebug # <- it does stop here
  @token = token
  devise_mail(record, :confirmation_instructions, opts)
end
```

But when I check the stack trace, it looks like it's called from some labda function.

So it seems that devise isn't using ConfirmationsController create action or other actions, wonder if this is by design?

**Comment by nashby** [comment]
@aurimus it's used for "Resend confirmation instructions" feature: https://github.com/plataformatec/devise/blob/master/app/views/devise/confirmations/new.html.erb

**Comment by aurimus** [comment]
What about send confirmation instructions then?

**Comment by nashby** [comment]
@aurimus don't think there's an action for that. It's done as callback https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L48

**Comment by aurimus** [comment]
@nashby  Doesn't it look like a design flaw? .. when I override confirmations controller I expect to be able to change what kind of email is sent or do some kind of other changes.

**Comment by aurimus** [comment]
@nashby there's also a callback for reconfirmations instructions just biside the one you linked, how come reconfirmations is still using the controller action and confirmations is not?
