### ISSUE TITLE
Method Not Allowed config.assets.prefix = ""

### ISSUE THREAD

**Issue by richpeck** [plataformatec/devise#4348]
I wanted to remove "/assets" from the asset path, so set:

```
#config/application.rb
config.assets.prefix = ""
```

This works with the assets, but as soon as I send any data to Devise (`login POST` / `logout DELETE`), it just replies with `Method Not Allowed`. It works perfectly in production, and found `config.assets.compile = false` to be the key to getting it to work.

I am wondering whether there is any fix for this? I know it sounds trivial but I just wanted to see.

**Comment by tegon** [comment]
Hi @richpeck, thanks for your report.
Could you provide us a simple app with the mentioned problem? That would be very helpful in order to track down what is happening.
Thanks again!

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!
