### ISSUE TITLE
[little change] redundant code in the method "active_for_authentication?"

### ISSUE THREAD

**Issue by Naggi-Goishi** [plataformatec/devise#4350]
The method, "active_for_authentication?," in confirmable.rb is defined like below
```ruby 
      def active_for_authentication?
        super && (!confirmation_required? || confirmed? || confirmation_period_valid?)
      end
```
And the expressions,` !confirmation_required?` and `confirmed?` are the same as `confirmation_required?` is defined like below.
```ruby 
        def confirmation_required?
          !confirmed?
        end
```

So I suggest to remove `!confirmation_required?` from `active_for_authentication?`

so `active_for_athentication? ` method can be shorter.

```ruby 
      def active_for_authentication?
        super && ( confirmed? || confirmation_period_valid?)
      end
```

**Comment by josevalim** [comment]
The reason both are called is because developers can change confirmation_required? and then there is no guarantee they are the same. So I believe the code should remain as is, thank you.
