### ISSUE TITLE
Devise Problem with iOs

### ISSUE THREAD

**Issue by xpiero** [plataformatec/devise#4354]
I wan't to know if devise have any compatibility issues with iOs

I have an android and web clients using retrofit that work perfectly but my iOs client is giving me "Authorized Users Only", I presume, after doing batch requests.

I've tried using Swift 2 native NSURLRequests and Alamofire but I'm still recieving the error message.

The API was built using Devise 3.5.10, Devise Token Auth 0.1.32.beta5, Ruby 2.3.1 and Rails 4.2.7.1 using token authentication. But I'm storing and sending the token in every request, so the token isn't the cause.

**Comment by georgeguimaraes** [comment]
It doesn't seem to be a Devise issue.
