### ISSUE TITLE
The sign_out method on Devise::Controllers does not work.

### ISSUE THREAD

**Issue by kikikiblue** [plataformatec/devise#4358]
I want to know how I can make specific user(not current_user) sign_out?
I want to retrieve a role from a user and make him sign out.
I saw this http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Controllers/SignInOut#sign_out-instance_method and maked this code.
```
def kick_admin
  user = User.find params[:user_id]
  user.admin = false
  user.save
  sign_out user #want to kick him. 
end
```
But it does not make that user sign out but make me(current_user) signed out.
What is the right way to use the sign_out method?
I could not find any solution from Stackoverflow.com so I opened the issued.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by kikikiblue** [comment]
Yes I read the guide but I opened this issue because the sign_out method of Devise is not working. on Devise document, it explains that sign_out method is for "Sign out a given user or scope", but it does not sign out a given user. I checked stackoverflow.com but same question with me was not solved yet. Thank you for your fast response anyway.

**Comment by josevalim** [comment]
You cannot sign another user out like that because the information is stored in their cookies. What you need to do is to have a filter in your admin sections that checks the user is still an admin whenever he tries to access an admin page and then act accordingly.

**Comment by kikikiblue** [comment]
Now I understood. Thank you.
