### ISSUE TITLE
Microsoft Edge, devise not working 401 not authorized

### ISSUE THREAD

**Issue by Rubytastic2** [plataformatec/devise#4360]
Whenever using M$ Edge browser login does not work, it throws a 401.
Just regular devise and simple_Form forms with no jquery at all (disabled for now )

It works fine in Internet Exploder

Only Edge is causing problems. 
Is this a known issue or has anyone came across this?

**Comment by evertonts** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by clownf** [comment]
I also have this problem, and now I have to write my own user authentication system

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!
