### ISSUE TITLE
Problem in aliasing `current_user` in Rails 5

### ISSUE THREAD

**Issue by tenshiAMD** [plataformatec/devise#4363]
devise: 4.20
cancancan: 1.15.0

I have a devise model `Employee` since I also use `cancancan` method `can?` in views that requires `current_user`, I need to alias `current_employee` into `current_user` so that `cancancan` will be able to read it properly.

`alias current_user current_employee`

It seems working fine at first when I added the code on the `application_controller`. Suddenly, when I restarted my rails server an error occurs:

> `<class:ApplicationController>': undefined method `current_employee' for class `ApplicationController' (NameError)

But when I rewrite the `alias` into these:

```
def current_user
    @current_employee ||= current_employee
end
```

This workaround works properly. What's the problem in aliasing?

**Comment by ristovskiv** [comment]
To be honest, I can't really reproduce your error. If I understand correctly you are trying to make an alias of the `current_employee` method with the name `current_user`? 
The alias that I'm creating doesn't throw any errors.

    alias current_user current_employee

Then I can use `current_user` instead of `current_employee`

**Comment by ristovskiv** [comment]
There is something that I've just remembered, have you tried aliasing with:

    alias_method :current_user, :current_employee

There is a very important difference between `alias` and `alias_method` and how they treat `self` , but the strange thing here is that you actually get a NameError on the `current_employee` method, which is really strange.

**Comment by tenshiAMD** [comment]
I still got the same error. In using the workaround below: 😢 

`alias_method` :current_user, :current_employee

**Comment by velichkoStoev** [comment]
Hello, @tenshiAMD 

I have a though but I'm not completely sure it's a reasonable one.

I think the problem is that you are trying to create an alias to a method which is not loaded yet.
The ApplicationController is loaded first and after that the Devise helpers are added. That means that when the code `alias current_user current_employee` is executed the `current_employee` method is not loaded yet. That's why you are getting a NameError. On the other side, `alias_method` is evaluated at run time.

`alias_method` is used in [CanCan docs](https://github.com/ryanb/cancan/wiki/changing-defaults) too.

**Comment by tenshiAMD** [comment]
@velichkoStoev Yeah that's the reason why it's not detected. It's strange and weird though, my ApplicationController looks somewhat like this:

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_employee!
end
```

And inserted `alias current_user current_employee` after the `before_action :authenticate_employee!`. Like this:

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_employee!
  alias_method :current_user, :current_employee
end

Still the error keeps on occurring. 😞

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
