### ISSUE TITLE
ArgumentError in Devise::Registrations#new ( wrong number of arguments (given 1, expected 0) )

### ISSUE THREAD

**Issue by riksof-zain** [plataformatec/devise#4365]
NOTE: Please help me with this http://stackoverflow.com/questions/40887726/argumenterror-in-deviseregistrationsnew :(

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
