### ISSUE TITLE
Incorrect email validation

### ISSUE THREAD

**Issue by dunyakirkali** [plataformatec/devise#4372]
Recently we have realized that emails in the following format `abs.@isp.com` are validated as true with Devise 3.4.1 since it uses this `/\A[^@\s]+@[^@\s]+\z/` regex.

The `.` sign followed by an `@` is actually an invalid email and should not go through the validation

**Comment by nashby** [comment]
It is just a simple check on purpose. Feel free to restrict it as you wish by setting `Devise.email_regexp`. The best way to validate an email is by sending it a confirmation e-mail, the regexp is mostly for usability purposes to avoid silly mistakes from the user side.

**Comment by dunyakirkali** [comment]
@nashby shouldn't that be handled more smoothly in devise? If ever a user record is created using an invalid email sending of the confirmation mail would raise an exception, wouldn't it?

**Comment by paulmwatson** [comment]
The default regex prevents basic sending errors. You can trap for mail sending failures yourself, that seems out of scope for Devise.
