### ISSUE TITLE
I want to set the array to strongparameter of devise

### ISSUE THREAD

**Issue by sagaekeiga** [plataformatec/devise#4373]
Can not set array to strongparameter. I am using acts-as-taggable-on.

source

【application_controller.rb】

```
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :shopname, :image])
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit({skills_list: []}, :email, :password, :password_confirmation)
    end
  end
```

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
