### ISSUE TITLE
Rails 5 + sending devise email via sidekiq

### ISSUE THREAD

**Issue by sahilchopra** [plataformatec/devise#4374]
Hi 

I am using sidekiq to send devise email. But getting following error

ActiveJob::SerializationError (Unsupported argument type: User):
  
app/models/user.rb:70:in `send_devise_notification'

Code is:
application.rb
config.active_job.queue_adapter = :sidekiq

User.rb
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end

![error](https://cloud.githubusercontent.com/assets/5656320/21042454/5ab0cd32-be17-11e6-8d01-1cda905c13fc.png)

Let me know if i am missing any thing. Thanks

**Comment by alaouy** [comment]
@sahilchopra Symbol is not a supported argument type for jobs because some implementations don't work with it (Sidekiq and resque)

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by lalit-nga** [comment]
I have not any got solution regarding same. Can someone provide me some links for same?
