### ISSUE TITLE
Why `sign_in(:user, user)` not working for ajax requests?

### ISSUE THREAD

**Issue by larryzhao** [plataformatec/devise#4379]
I am trying to sign in a user in an ajax request:

```
def create
  if user.valid_password?(password)
      sign_in(:user, user, { :event => :authentication })
      ...
  end 
end
```

I could see that after `sign_in`, `user_id` is serialized to session, but in the next request, I lost it again, why is that? How could I sign in a user via ajax request?

Thank you very much. I am using Device 3.5.9

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by larryzhao** [comment]
@josevalim Thx
