### ISSUE TITLE
Devise ignoring default_url_options in Rails 5

### ISSUE THREAD

**Issue by noctivityinc** [plataformatec/devise#4380]
I am using devise 4.2.0 with Rails 5 and having issues with the password reset emails.  Im running Rails in API mode and the API is running on ```api.myserver.dev:300```  Im consuming this API in a website running on ```myserver.dev:3000.``` I have no problem with this to date.

Since the API app doesn't render any public views, I want the password reset emails to send the user to my website, where I will (somehow) validate the password_reset_token and then let the valid user reset their password, however, I can't seem to set the URL in the reset emails to myserver.dev:3000 - it's always defaulting to the api.myserver.dev:3001 host and port.

I have the following in both my test.rb and development.rb files:
  
    config.action_mailer.default_url_options = { host: 'myserver.dev', port: 3000 }

Does anyone have a clue on how to fix this?

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?
