### ISSUE TITLE
Handle data URIs in store_location_for

### ISSUE THREAD

**Issue by olivierlacan** [plataformatec/devise#4384]
Currently since `store_location_for` assumes the successfully parsed URI has a non-nil `path`, it causes the following exception when dealing with [data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs):

```ruby
store_location_for :user, "data:text/plain;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4="
NoMethodError: undefined method `sub' for nil:NilClass
.../devise-3.5.10/lib/devise/controllers/store_location.rb:38:in `store_location_for'
```

Would you accept a PR that addresses this? 

One potential solution would be to replace: 

```ruby
path = [uri.path.sub(/\A\/+/, '/'), uri.query].compact.join('?')
```

With:

```ruby
[uri.path && path.sub(/\A\/+/, '/'), uri.query].compact.join('?')
```

Since Data URIs don't contain a path, they'll simply return an empty string as do absolute URIs currently.

**Comment by tegon** [comment]
Hi @olivierlacan, thanks for your suggestion.
I'm curious, what's your use case for this?

**Comment by olivierlacan** [comment]
@tegon It's been so long I honestly don't remember but I've managed to survive without this feature so let's close it.

**Comment by tegon** [comment]
@olivierlacan Ok, sorry for the late response. If you run into it again, please feel free the open a new issue.
Thanks!
