### ISSUE TITLE
Devise with Sendgrid API

### ISSUE THREAD

**Issue by RichardGrossman** [plataformatec/devise#4385]
All help I have found for using Devise with Sendgrid is based around the SMTP method.

Is there a step-by-step setup for using Devise with the the Sendgrid API?

It would be great to have a single known-to-work approach rather than patching together pieces of a possible solution.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
