### ISSUE TITLE
Allow admin to add users

### ISSUE THREAD

**Issue by RichardGrossman** [plataformatec/devise#4387]
Tried this:
How To: Manage users through a CRUD interface

But still getting password blank error on save.

**Comment by RichardGrossman** [comment]
REQUEST: Devise add a config option that allows a normal route and controller for the User model.

Until then, this hack works by going all around Rails and around Devise.

**routes**
      post 'savenew', to: 'users#savenew'

**controller:**

    def savenew
     rawsql = "insert into users (name,email, created_at,updated_at) values ('#         
        {user_params[:name]}', '#{user_params[:email]}',now(), now())"
                sql = rawsql
            ActiveRecord::Base.connection.execute(sql)
            redirect_to action: 'index'
    end


**new.html.erb**

    <%= form_for modelname, :url => {:action => "savenew"} do |f| %>

**Comment by RichardGrossman** [comment]
See on the wiki:

https://github.com/plataformatec/devise/wiki/How-to-manage-users-with-a-standard-Rails-controller-using-a-somewhat-CRUDE-HACK-that-WORKS!

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by RichardGrossman** [comment]
Seems like this is an issue.

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?
