### ISSUE TITLE
Unable to confirm account since 'confirmed_at' attribute is nil

### ISSUE THREAD

**Issue by siva-prasad12** [plataformatec/devise#4388]
**Rails - "3.2.22.5"
Devise - "3.4.1"**

Before we have not configured confirmable for one of the model and just integrated to the particular model added 
Step1: devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, **:confirmable**

Step2: Added columns
**# Confirmable
    add_column :customers, :confirmation_token, :string
    add_column :customers, :confirmed_at, :datetime
    add_column :customers, :confirmation_sent_at, :datetime
    add_column :customers, :unconfirmed_email, :string**

After all this integration i am generating mail with the link but i am unable to confirm when i click that link it is redirecting to application index page and confirmed_at column is not updated so i am unable to confirm . 

I am facing this issue from past one week so could any one can help me to fix this please.

Thank You

**Comment by FloHeinle** [comment]
Can you post the corresponding logs?
I tried to create an example app, but i didn't get rails 3.2.22.5 to work. 
Can you create an example app which reproduces this error?

Bests

**Comment by siva-prasad12** [comment]
Hello Flo ,

i am unable to find any exception in log . we have integrated devise gem for two active records  (users and customers) for customers we have configured with confirmable and confirmable token in the link sent to mail is different from which it is generated. once we are tryning to confirm it redirecting to user login without updating to the customer confimed at column. I have integrated working product. please flo i am struggling from last 15 days to fix it ..


Thank You

**Comment by FloHeinle** [comment]
Can you post your log file?

**Comment by siva-prasad12** [comment]
**After Sign Up**

 SmartMiles Load (0.3ms)  SELECT `smart_miles`.* FROM `smart_miles` LIMIT 1
  Rendered /home/shivaprasad/.rvm/gems/ruby-1.9.3-p551/gems/devise-3.4.1/app/views/devise/mailer/confirmation_instructions.html.erb (1.0ms)

Sent mail to xxxxxx@gamil.com (4247.5ms)
Date: Tue, 03 Jan 2017 19:34:30 +0530
From: aaaa@com.com
Reply-To: yyyyy@gmail.com
To: admin2222@gamil.com
Message-ID: <586baf6e8bc66_10913fe934a871d871942@Shivaprasad-TS.mail>
Subject: es-Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome xxxxx@gamil.com!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://lvh.me:3000/customers/confirmation?confirmation_token=CgyjWdELJ7QUPX2GTgoX">Confirm my account</a></p>

**After clicking the confirmation link**

 Started GET "/customers/confirmation?confirmation_token=CgyjWdELJ7QUPX2GTgoX%22" for 127.0.0.1 at 2017-01-03 19:36:22 +0530
Processing by Devise::ConfirmationsController#show as HTML
  Parameters: {"confirmation_token"=>"CgyjWdELJ7QUPX2GTgoX\""}
"127.0.0.1" - Started PID: 4241 => Received "GET" to "http://www.orange.lvh.me:3000/customers/confirmation?confirmation_token=CgyjWdELJ7QUPX2GTgoX%22" at 2017-01-03 19:36:23 +0530.
  Travel Load (0.2ms)  SELECT `travels`.* FROM `travels` LIMIT 1
  SQL (0.1ms)  SELECT name FROM `travels` 
   (0.2ms)  SELECT DATABASE() as db
  TravelPref Load (0.2ms)  SELECT `travel_prefs`.* FROM `travel_prefs` LIMIT 1
  CACHE (0.0ms)  SELECT `travel_prefs`.* FROM `travel_prefs` LIMIT 1
  TravelPref Loaded  From Identity Map (id: 1)
Redirected to http://www.orange.lvh.me:3000/account/signin
Filter chain halted as :login_required rendered or redirected
"127.0.0.1" - Completed in 16.751552ms PID: 4241 => Received "GET" to "http://www.orange.lvh.me:3000/customers/confirmation?confirmation_token=CgyjWdELJ7QUPX2GTgoX%22" at 2017-01-03 19:36:23 +0530.

**Customer row itself is deleted from database after confirming.**

**Comment by FloHeinle** [comment]
The token in the confirmation link is always different, that's OK.

For me it looks like that your authentication doesn't allow this call and redirects.
`Filter chain halted as :login_required rendered or redirected`
And there is no customer loaded form the db.

Usually your log should look like this:
```
Started GET "/users/confirmation?confirmation_token=s_ZxfeF_GnU4TNfp5jiB" for 127.0.0.1 at 2017-01-03 15:46:21 +0100
Processing by Devise::ConfirmationsController#show as HTML
  Parameters: {"confirmation_token"=>"s_ZxfeF_GnU4TNfp5jiB"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."confirmation_token" = '06b4f7e8049654d45cf24479b1c493748cf5a0e7b0035f6a639477766045377b' LIMIT 1
   (0.0ms)  begin transaction
   (0.7ms)  UPDATE "users" SET "confirmation_token" = NULL, "confirmed_at" = '2017-01-03 14:46:21.663307', "updated_at" = '2017-01-03 14:46:21.663757' WHERE "users"."id" = 3
   (42.4ms)  commit transaction
Redirected to http://localhost:3000/users/sign_in
```

Check if your user are allowed to access this route

**Comment by siva-prasad12** [comment]
After adding below code also it is redirecting account/signin rather than customers/sign_in

`class CustomersController < Devise::SessionsController
	 skip_before_filter :login_required`

code goes here
`end`

**Comment by siva-prasad12** [comment]
Hi Flo,

i have just overriding the after_confirmation_path_for method of Devise::ConfirmationsController. it working fine.

Create a new confirmations_controller.rb in app/controllers directory:

class ConfirmationsController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    your_new_after_confirmation_path
  end

end
In config/routes.rb, add this line so that Devise will use your custom ConfirmationsController. This assumes Devise operates on users table (you may edit to match yours).

devise_for :users, controllers: { confirmations: 'confirmations' }
