### ISSUE TITLE
Custom Devise Layout in Application.rb has no effect

### ISSUE THREAD

**Issue by mastertechrv** [plataformatec/devise#4390]
I created custom views for both
 ```users/passwords/new```  & ```users/passwords/edit```
Those layouts are in ```/views/layouts/new_password``` & ```/views/layouts/edit_password```

I read the wiki page **[Here](https://github.com/plataformatec/devise/wiki/How-To%3A-Create-custom-layouts#individual-controller)**

I added this per instructions on the link above in the application.rb

```
config.to_prepare do
        Devise::SessionsController.layout "login_window"
        Devise::PasswordsController.layout 'new_password', only: [:new]
        Devise::PasswordsController.layout "edit_password", only: [:edit]
end
```

Here is a gist of application.rb **[Here](https://gist.github.com/mastertechrv/61152461d0181f79197113c1f84d6cbd)**

I also have custom scoped views enabled in devise.rb

It always defaults back to ```views/users/passwords/new```

Any Ideas?

**Comment by georgeguimaraes** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
