### ISSUE TITLE
How to change the generate token by 10 characters from Devise::Models::Confirmable#generate_confirmation_token

### ISSUE THREAD

**Issue by memoxmrdl** [plataformatec/devise#4393]
Hi,

How to change the generate token from here https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L245 it is generate with 10 characters and I wan't it with 20 characters. I trying to change overwriten the method but it isn't working.

thanks

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
