### ISSUE TITLE
Reconfirmable = true causes error on sign up with email (Devise v4.x.x)

### ISSUE THREAD

**Issue by wmantegna** [plataformatec/devise#4394]
I'm experimenting with Devise & omniauth, and am having issues with Reconfirmable. I've added the `unconfirmed_email` column to my database, but when I sign up via email, I get the following error after filling out the form on _~/users/sign_up_ and clicking "Sign Up":

> Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

Upon further investigation, I see both a User & and an Identity (omniauth) record, which is good. However,`User.unconfirmed_email` is `nil`, even though the email address has yet to be confirmed. `User.email` contains the email address I supplied, and I found using the rails console to add the supplied email to the `unconfirmed_email` field fixes the problem. After doing that, I can reload the page without error.

Here's my sandbox application: [rails-omniauth-test](https://github.com/wmantegna/rails-omniauth-test)

**Comment by nashby** [comment]
@wmantegna all you need is to setup `config.action_mailer.default_url_options`. See README for more info. Since code fails on this step `unconfirmed_email` is never set. I tried to set that option in your test app and everything worked. Cheers!

**Comment by wmantegna** [comment]
Thanks! I set up the setting and it works now!
