### ISSUE TITLE
stack level too deep during test (rails 5.0.0.1, devise 4.2.0)

### ISSUE THREAD

**Issue by mr-koww** [plataformatec/devise#4395]
Hello! When I run this test:
```
describe 'GET /new' do
    context 'when user not login' do
      it 'redirect to login path' do
        get :new
        expect(response).to redirect_to login_path
      end
    end
end
```
it crushes with error 'stack level too deep' (loop redirect)
But when I run app in browser it work great!

**Comment by evertonts** [comment]
@mr-koww Could you provide a sample application that reproduces the error?
