### ISSUE TITLE
Sessions Controller sends session cookie in response for destroy_user_session_path - (4.2.0)

### ISSUE THREAD

**Issue by ademars94** [plataformatec/devise#4396]
When terminating a session with `sessions_controller#destroy`, I am getting the user's session cookie back in the response.  I am fairly certain this is not the desired behavior of Devise, but if I am wrong I would like to know why.  Please let me know!

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
