### ISSUE TITLE
Not getting fb users required public_information

### ISSUE THREAD

**Issue by nasirshamshadsynnapps** [plataformatec/devise#4398]
Hi, 
I'm using omniauth-facebook and devise to allow my website users to register themselves using their Facebook account. Though users are being registered but the full public information I'm asking to fetch is not returned in `request.env["omniauth.auth"]`.

Here are my configuration steps.
In Gemfile => `gem 'omniauth-facebook'`
In `devise.rb` I am requesting these scopes and user fields as defined in [omniauth-facebook](https://github.com/mkdynamic/omniauth-facebook) gem github page

`config.omniauth :facebook, 'MY_APP_ID', 'MY_FB_APP_SECRET', scope: 'email,public_profile, user_likes,user_education_history, user_about_me,user_birthday,user_hometown,user_friends', info_fields: 'email,id,name,first_name,last_name,age_range,link,gender,timezone,updated_time,verified,friends,hometown,location,birthday,education,work,likes', callback_url: http://localhost:3000/users/auth/facebook/callback", secure_image_url: true, image_size: 'large'`

But in response I'm only getting following fields in **request.env["omniauth.auth"].**

--- !ruby/hash:OmniAuth::AuthHash
provider: facebook
uid: 'XXXXXXXXXXXXXXXXXXXXXXXXX'
info: !ruby/hash:OmniAuth::AuthHash::InfoHash
  email: xxxx@gmail.com
  name: OK  
  first_name: OK
  last_name: OK
  image: https://graph.facebook.com/v2.6/xxxxxxxxxxxxxxxxx/picture?type=large
  urls: !ruby/hash:OmniAuth::AuthHash    
  	Facebook: https://www.facebook.com/app_scoped_user_id/xxxxxxxxxxxxxxxxx/
  	verified: true
  	credentials: !ruby/hash:OmniAuth::AuthHash  
  	token: LONG TOKEN STRING.............  
  	expires_at: 1489836756  
  	expires: true
  	extra: !ruby/hash:OmniAuth::AuthHash 
  		raw_info: !ruby/hash:OmniAuth::AuthHash    
  			email: xxxx@gmail.com    
  			id: 'xxxxxxxxxxxxxxxxx'    
  			name: OK    
  			first_name: OK    
  			last_name: OK    
  			age_range: !ruby/hash:OmniAuth::AuthHash      
  			min: 21    
  			link: https://www.facebook.com/app_scoped_user_id/xxxxxxxxxxxxxxxxx/    
  			gender: male    
  			timezone: 5    
  			updated_time: '2017-01-16T14:57:38+0000'    
  			verified: true    
  			friends: !ruby/hash:OmniAuth::AuthHash      
  				data:      
  					- !ruby/hash:OmniAuth::AuthHash        
  						name: 1st Mutual Friend        
  						id: 'xxxxxxxxxxxxxxxx'      
  					- !ruby/hash:OmniAuth::AuthHash
  					  name: 2nd Mutual Friend        
  					  id: 'xxxxxxxxxxxxxxxxx'
  					  summary: 
  					  !ruby/hash:OmniAuth::AuthHash        
  					  	total_count: 239

This is clearly missing **_education,hometown,location,birthday,education,work,likes_**
PLEASE help me if I'm doing something wrong or I need to do something else?
Thanks.

**EDIT 1 - A THOUGHT** 
This might be the case that I'm not being able to generate a token with full permissions from users. I've provided APP_ID AND SECRET in devise.rb and asked permission in scope: .... 
Does this procedure generate ACCESS_TOKEN which is then returned in request.env["omniauth.auth"]?

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
