### ISSUE TITLE
Devise 3.2.4 - config.expire_auth_token_on_timeout not working.

### ISSUE THREAD

**Issue by 23ranjan** [plataformatec/devise#4400]
Hi, 

We are using Devise 3.2.4 with Rails 3.2.13.

Here is my user model 
`  devise :database_authenticatable, :async , :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :timeoutable`

While `config.timeout_in` is working fine but on setting
`config.expire_auth_token_on_timeout = true` the auth token doesn't expire.

Any idea what I am missing here ?

~Ranjan

**Comment by evertonts** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by 23ranjan** [comment]
Hi @evertonts  

I researched a lot and I guess this feature of expiring auth token on timeout is removed?

Ranjan

**Comment by evertonts** [comment]
@23ranjan Yep, seem like it was removed on #3672
