### ISSUE TITLE
Allow admin to change user's password

### ISSUE THREAD

**Issue by alex3o0** [plataformatec/devise#4401]
I want to allow to my admin user to change user's passwords via PUT /auth/password and everything goes nice except for passwords_controller is using the current login id for do the update and I need can change it with any user id.

**Comment by SofaKing18** [comment]
User.find(:id).update(password:'example',password_confirmation:'example')

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
