### ISSUE TITLE
devise email smtp return Errno::ECONNRESET: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by hendranata** [plataformatec/devise#4402]
i still curious why..
this problem was not occur couple months ago.
but now has a problem.
we do not doing anything obviously.

we use devise for login and send email.
but the problem now email is not working.
if we see from the log report.
here is meesage:

Errno::ECONNRESET: Connection reset by peer - SSL_connect

i am not sure why...but when we try to run in localhost..it is working fine..
development and production configuration are the same.

we suspect the problem is curl and openssl version.. even we have update , problem still the same

any idea?

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
