### ISSUE TITLE
Can't limit Omniauth to POST requests

### ISSUE THREAD

**Issue by evanhammer** [plataformatec/devise#4404]
I'm using Devise with Omniauth. It doesn't seem possible to restrict the initial user auth requests to POST's. Is it?

Currently I'm testing manually adding the routes with GET requests, but I'm getting 404's.

my routes.rb:
```rb
  devise_for :users, only: '', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    # only handle GET
    get 'users/auth/:provider', to: 'users/omniauth_callbacks#passthru', as: :user_omniauth_authorize
  end
```

I'm getting this in my rails logs:
```
Started GET "/users/auth/facebook" for 127.0.0.1 at 2017-01-19 19:18:56 -0500
Processing by Users::OmniauthCallbacksController#passthru as HTML
  Parameters: {"provider"=>"facebook"}
Rendering 404: Not Found
```

**Comment by evertonts** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
