### ISSUE TITLE
email/password combination locked to device

### ISSUE THREAD

**Issue by Kostronor** [plataformatec/devise#4407]
In [my current project](https://github.com/Kostronor/globalcorp) I use devise for authentification. I currently require no mailer at all and have disabled all emails from devise (I do not require confirmation f.e.)

Users can login with as an anonymous user with [this function](https://github.com/Kostronor/globalcorp/blob/develop/app/controllers/welcome_controller.rb#L32) and later change their email and password.

Email/Password change is devise default and works, but when using a different device/browser, then it tells that the combination is wrong.

Is there something locking this to the browser or did I miss something?

**Comment by tegon** [comment]
That's no code that locks an account for a browser. It can be another problem with the code. I'd recommend that you open a question on StackOverflow, there a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
