### ISSUE TITLE
Suggestion for Wiki

### ISSUE THREAD

**Issue by aisflat439** [plataformatec/devise#4408]
Hi I'd like to help with a wiki article, if others think it's necessary. I've spent the better part of the last 3 days trying to have sign in with Facebook and Google for a site. You can see the commit history below.

https://github.com/aisflat439/collegepro-report-maker

Because of the mention in the documentation about Multiple Oath Models I ended up down a rabbit hole that I didn't really need to go down, wasting some time. I then struggled mightily with the difference between oauth and oauth2 in my routes and config. 

If someone more experienced than myself is willing to look over a tutorial for setting up sign in with facebook and google, and the community thinks it would be helpful, I'd be happy to try to do so.

**Comment by aisflat439** [comment]
Also the error `Not found. Authentication passthru`, found https://github.com/plataformatec/devise/blob/master/app/controllers/devise/omniauth_callbacks_controller.rb in the passthru method isn't really helpful. I'd be happy to help address that if there is someone who would be willing to look over my work.

**Comment by georgeguimaraes** [comment]
Hi, you can have a better feedback on your proposal if you ask the mailing list and/or StackOverflow, where a wider community will be watching. 

We reserve the issues tracker for issues only (and only a handful of people look into the issue tracker).
