### ISSUE TITLE
Page redirects to /users after /users/sign_up failure

### ISSUE THREAD

**Issue by shiladitya-bits** [plataformatec/devise#4410]
With my default devise configuration, when sign up fails due to some reason (e.g. email already taken), it redirects to /users instead of the same path /users/sign_up. Any leads into how I can debug this?
I tried to override `after_sign_up_fails_path_for(resource) ` in my application controller, but it is not getting called.

My application is using devise 3.2.4 on rails 3.2.13

**Comment by georgeguimaraes** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
