### ISSUE TITLE
Sad path to Linkedin OAuth controller

### ISSUE THREAD

**Issue by celsoMartins** [plataformatec/devise#4412]
Hi. First of all, thanks for the amazing job you guys are doing on devise. This GEM is wonderful.

Second of all, I would like to test when the user clicks in the cancel button in the authorization page:

http://jmp.sh/NgefJdv

and the devise flow goes to the `OmniauthCallbacksController`

http://jmp.sh/NatJTEa

How could I force the rspec to send the flow to this route?

this is the scenario I'm trying to test:

```
    context 'when the user deny the access' do
      it 'redirects to the new login session' do
        get :linkedin
        expect(response).to redirect_to new_user_session_path
      end
    end
```

Thanks in advance.

**Comment by georgeguimaraes** [comment]
Thanks Celso for the compliments! :heart:

 Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
