### ISSUE TITLE
in rails 5, g devise MODEL ignores primary_key_type: :uuid

### ISSUE THREAD

**Issue by jpwynn** [plataformatec/devise#4413]
If Rails is configured to use :uuid as the primary key for all tables, eg if config/application.rb contains:

    config.generators do |g|
        # use uuid for all tables
      g.orm :active_record, primary_key_type: :uuid
    end 

`rails g devise MODEL` still creates a migration for the model with integer primary key, but probably ought to add the uuid column type for the id instead.

**Comment by georgeguimaraes** [comment]
This should be a good addition to the devise's generator. I'd accept a PR.

**Comment by filip373** [comment]
I've opened a pull request with the required changes. It seems to work fine, take a look at #4426

**Comment by saroar** [comment]
hey its still does not work i try
