### ISSUE TITLE
Can't reset password: Devise.token_generator.digest() creates non existent token.

### ISSUE THREAD

**Issue by timbaas** [plataformatec/devise#4415]
Hi,

I'm on Rails 4.2.0 and Devise 4.2.0.

The mailer sends a reset password link with:
`reset_password_token=08ea10d120056afce973efa69fb746d2d698eb4c333a6d1c7a71dd30223f56b8`.

I've seen the logs and it tries to find a User with:
`WHERE `users`.`reset_password_token` = '7885ec7113186078e9b9c49819865964390a8c01081f4bbb1b3a8fa050bb0a0b'`

I've been through the source and saw:
`Devise.token_generator.digest(self, :reset_password_token, original_token )`

When I replace it with the variables in my case the problem is clear:
`Devise.token_generator.digest(self, :reset_password_token, '08ea10d120056afce973efa69fb746d2d698eb4c333a6d1c7a71dd30223f56b8')`

It returns: `7885ec7113186078e9b9c49819865964390a8c01081f4bbb1b3a8fa050bb0a0b`

But that token isn't in my database, the token send in the e-mail is.

Any advise?

**Comment by timbaas** [comment]
Digging a bit further, I saw that `set_reset_password_token ` was creating two versions of the token.

The mailer templates, which are overwritten in my case, was sending the `reset_password_token` instead of `@token`.

**Comment by jesperronn** [comment]
Thanks for taking the time to explain the actual solution @timbaas. The exact same thing happened to me 👍
