### ISSUE TITLE
バリデーションに引っかかる下書きで公開するボタンを押すと、上に複製するボタンがでてしまう問題。

### ISSUE THREAD

**Issue by keigo0331** [plataformatec/devise#4417]
- タイトルが入力されていないなど、公開するときのバリデーションに引っかかる記事で起こる。
- 記事が不正だと、rescueでupdate処理が中止されるが、Viewがrenderされるタイミングでは、公開するボタンを押したことにより一時的にpublished状態と判定される。

**Comment by georgeguimaraes** [comment]
I'm sorry 、 わたしの にほんご わ じょうす じゃ ない。╮(╯_╰)╭
