### ISSUE TITLE
Rails 5 api app fails on users/sign_out, undefined method respond_to

### ISSUE THREAD

**Issue by ksnyder** [plataformatec/devise#4418]
I generated a new Rails 5.0.1 app with the --api flag (also skipped ActionCable, Spockets and Javascript, if that matters).  With Devise 4.2, the sign out action has this problem:

Started DELETE "/users/sign_out" for ::1 at 2017-01-31 08:15:31 -0800
Processing by SessionsController#destroy as JSON
  Parameters: {"session"=>{}}
Completed 500 Internal Server Error in 23ms (ActiveRecord: 0.0ms)
NoMethodError (undefined method 'respond_to' for #<SessionsController:0x007f8b7c308d10>
Did you mean?  respond_to?
               respond_with
               responder
               responder?
               responder=):
  
devise (4.2.0) app/controllers/devise/sessions_controller.rb:76:in 'respond_to_on_destroy'
devise (4.2.0) app/controllers/devise/sessions_controller.rb:63:in 'verify_signed_out_user'

**Comment by georgeguimaraes** [comment]
Devise was meant to be used with normal Rails controllers. 
There has been discussion on previous issues about using Devise with Rails API, like https://github.com/plataformatec/devise/issues/4275

**Comment by Darkside73** [comment]
I think you should override default ```destroy``` method implementation in your own ```SessionsController```
