### ISSUE TITLE
Devise sessions controller #create yields only on success

### ISSUE THREAD

**Issue by riggy** [plataformatec/devise#4419]
Hey!

I haven't found this issue anywhere (only about registrations, which is resolved), so I'm posting.

I'm currently working on a functionality, which logs all kinds of stuff, including login failures, user lockouts etc. I know there's a possiblity to simply override, for example `#lock_access!` method from `Lockable` module, but that isn't the best scenario for me. I'm also logging stuff like ip address, current session id, for debugging purposes. And those are not easily obtainable on model level (too much dirty hacks), while it's easy peasy in controller.

It would be wonderful if method would yield on failed login as well - could save me a lot of trouble. Currently it happens only upon successful login, which in my opinion is not a complete functionality?

What do you guys think? Does it make sense?

**Comment by georgeguimaraes** [comment]
You'd probably need to write (or overwrite) Devise's SessionController to code all the features you need.

There has been some discussions in the past about it. Please search the closed issues and/or StackOverflow for possible insights. 

AFAIK, there's no easy way to do it with vanilla Devise.
