### ISSUE TITLE
Requets features : add more fields to model User

### ISSUE THREAD

**Issue by EnziinSystem** [plataformatec/devise#4420]
Please add fields to default 

class AddColumnsToUser < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :name, :string
    add_column :users, :provider, :string
    add_column :users, :uid, :string
    add_column :users, :image, :string
    add_column :users, :address, :string
    add_column :users, :address2, :string
    add_column :users, :city, :string
    add_column :users, :state, :string
    add_column :users, :country, :string
    add_column :users, :zipcode, :string
    add_column :users, :phone, :string
  end
end

Thanks.

**Comment by josevalim** [comment]
You are free to add those in your own migrations.
