### ISSUE TITLE
Logged in Devise but not on warden

### ISSUE THREAD

**Issue by Xosmond** [plataformatec/devise#4421]
I have a problem on rails with actionable, i trying to access to user via warden on "app/channels/application_cable/connection.rb" with:

`env['warden'].user`

But im logged in because i have authenticated myself and  im on a page served by a controller that has `before_action :authenticate_user!`.

Why is this happening?

PD: I have notice that `env['warden'].user` on the controller is getting the user. But i need that on the Connection class of ActionCable.

Complete code:

```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verfied_user
    end

    protected

    def find_verfied_user
      # We can just access Warden directly to find out if the user is logged in or not
      # Using Warden directly will give us access to that as it's what Devise uses internally for authentication
      if current_user = env['warden'].user
        current_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

**Comment by Xosmond** [comment]
I was using a multi tenant system so i had to change to the correct tenant.

**Comment by K1N5L4Y3R** [comment]
@Xosmond could you please elaborate on what you did to solve your issue? I have only managed to solve this by using something like `cookies.encrypted[:_appname_session]["warden.user.user.key"][0][0]` and not `env['warden'].user`

**Comment by K1N5L4Y3R** [comment]
Nevermind, I think I just needed to set `config.default_scope = :user` in config/initializers/devise.rb since I had another Devise model and it was picking that one instead of user.
