### ISSUE TITLE
manually sign in and keep session

### ISSUE THREAD

**Issue by anklos** [plataformatec/devise#4423]
Hi there,

I need to manually sign in a user, and keep the logged in session when user goes to other pages.

I have tried:

```
warden.set_user user
sign_in :user, user
```

It can sign in the user, but cannot keep the session if browsing other pages.

It should be a popular question, however I cannot find any good answer online. Thanks a lot in advance.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
