### ISSUE TITLE
UncaughtThrowError warden

### ISSUE THREAD

**Issue by Fattouh92** [plataformatec/devise#4427]
i keep getting this error in active job connection in this line
`current_user = env['warden'].user`
i have module timeoutable enabled, I feel this error happens when a timeout happens and it slows down the entire app

**Comment by tegon** [comment]
You need to give us more information on how to reproduce this issue, otherwise, there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!

**Comment by vanboom** [comment]
Same error here, but under this scenario:

Rails 5.2.4.5 production with config.public_file_server = true
Attempt to access a file in public/uploads that does not exist, e.g. https://my.server.com/public/uploads/file_not_exist.png
This results in the UncaughtThrowError in Rack application...

Top two items from the backtrace...

...warden-1.2.9/lib/warden/proxy.rb:134 in authenticate!
...devise-4.7.3/lib/devise/controllers/helpers.rb:118 in `authenticate_client!`
I am still investigating - any tips much appreciated.
