### ISSUE TITLE
Can't "sign_in" with overridden Devise SessionController

### ISSUE THREAD

**Issue by marcosanfilippo** [plataformatec/devise#4431]
Hi, I'm working on Rails 5 application (api only), I use Devise for the `User` model, overridden at `mobile/auth/users`. I can use only few actions of controllers, for example I can `sign_up` via `cURL` but I can't `sign_in`, I don't know why. Here there's the example:

Controller: `sessions: 'mobile/auth/users/sessions'`

Overriding example:

    def create
        super
    end

Request:

    curl -H 'Content-Type: application/json' -X POST http://api.test.com:3000/mobile/users/sign_in -d '{"user" : { "email" : "user@example.com", "password" : "1234567890"}}'

Error: `401 Unauthorized`

Body: `{"error":"You need to sign in or sign up before continuing."}`

I'm trying to sign_in and I'm already signed up with correct confirmation, why with controller overriding nothing works? In normal application with views all goes well.

Thank you!

**Comment by tibomogul** [comment]
I have a Rails 5 API/Ember-CLI-Rails app with Devise/token authentication and Cancan authorization.

What I do is yield the user object to generate the JSON response with the authentication token
```ruby
def create
  super do |user|
    # create the data hash here from info in user object
    render json: data, status: 201
  end
end
```

**Comment by marcosanfilippo** [comment]
@tibomogul Thank you for your reply, I finally found the error, is about namespacing! I had:
`namespace: 'mobile' do`
`devise_for :users`
`end`

with

`namespace: 'web' do`
`devise_for :users`
`end`

I did this because I need to override controllers and distinguish between mobile authentication and web authentication. Now, with rails module and scope, how can I do this? It doesn't work if I use scope instead of namespace because of overlapped resources (Prefix).
Should I define each routes by hand, for each controller? What's the best way for overriding more times the devise controllers?

**Comment by marcosanfilippo** [comment]
@tibomogul thank you for your time. I found the error and is regarded on session. How devise stores session by default? I know that a cookie is set but if I use cURL with -b option, the same error is returned: `401 Unauthorized`. Why? Same subdomain, I use only `api.test.com`. There's a way to override devise session handing?

**Comment by tibomogul** [comment]
afaik you shouldn't really be relying on sessions since you are interacting with your server via API. You should use the login to get an authentication token, and then use that token in subsequent requests to the server. In my case I supply the token through the headers.

**Comment by marcosanfilippo** [comment]
I solved overriding the `before_filter` with custom authentication for sessiona handling. The same Devise logic for API and 'Web' session is heavy.
