### ISSUE TITLE
ParameterSanitizerPermit Stopped Working

### ISSUE THREAD

**Issue by cooldesigns** [plataformatec/devise#4432]
this code abow was working absolutely smooth, but i don't know what happaned, it's just stopped working.
I put this method in RegistrationsController < DeviseController OR ApplicationController
Nothing change, also i tried do |user_params| block.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:country, :currency, :language])
  end
Console log: Unpermitted parameters: country, currency, language
I fetch the devise from github master branch.

**Comment by alcidesjunior** [comment]
I'm also having the same problem. Does anyone know the solution?
I'm doing the same steps.

**Comment by nagaroni** [comment]
@likelazyeyes can you post what params you received on controller when you submit the form?

PS: sorry for my english...

**Comment by ahmad19** [comment]
@likelazyeyes You need to write your method like this:
```
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [...])
end
```

**Comment by alcidesjunior** [comment]
Someone can help me, please?
I'm using:
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:user, keys: [:photo])
end

But don't work. I'm using paperclip to up my file.... I need add a new parameter to record on database..... How to solve this?

**Comment by ahmad19** [comment]
@alcidesjunior I have mentioned the solution above. Also, I think this is the place to report a **bug** for devise. Use StackOverflow to get your problems solved.

**Comment by likelazyeyes** [comment]
I don't know what happened it is working now. Why???

**Comment by sutherland007** [comment]
I had the same problem but I've found [this article](http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html) which uses this method:
```
def configure_sign_up_params
   params.require(:user).permit(:your, :single, :params)
end
```
And it worked perfectly fine for me. If you are still looking for a solution.

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
