### ISSUE TITLE
Devise controller does not refresh parameter during testing

### ISSUE THREAD

**Issue by thethirduniverse** [plataformatec/devise#4435]
Currently, `@devise_parameter_sanitizer` is initialized only once (lazily). Therefore `@devise_parameter_sanitizer` will not be updated even if `params` is updated. This can lead to unexpected behavior during testing.

Is this the expected behavior? If not, I'm happy to provide a pull request to fix it.

I am using Rails 5.0.1, Devise 4.2.0. Thanks!

Controller Code:
```
class RegistrationsController < Devise::RegistrationsController
  def create
    super do
      puts 'params email is: '
      puts params['user']['email']
      puts 'resource email is: '
      puts resource.email
      puts ''
    end
  end
end
```

Test Code:
```
require 'test_helper'

class RegistrationsControllerTest < ActionController::TestCase
  include Devise::Test::ControllerHelpers

  setup do
    @request.env['devise.mapping'] = Devise.mappings[:user]
  end

  test 'registration controller can handle different params' do
    post :create, xhr: true, params: {
      'user[email]': 'email1@example.com',
      'user[password]': 'longenough',
      'user[password_confimation]': 'longenough',
    }

    post :create, xhr: true, params: {
      'user[email]': 'email2@example.com',
      'user[password]': 'longenough',
      'user[password_confimation]': 'longenough',
    }
  end
end
```

Result:
```
params email is: 
email1@example.com
resource email is: 
email1@example.com

params email is: 
email2@example.com
resource email is: 
email1@example.com
```

Link to project:
https://drive.google.com/open?id=0B9nidrJzI6p9a1B5aVFTaktpeGc

**Comment by tegon** [comment]
Hi @thethirduniverse, thanks for your report.
I'm not sure what behavior are you expecting here. Could you provide us a failing test case?
You can use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb) for this.

Thank you!

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
