### ISSUE TITLE
Devise ActionController Cannot redirect to nil!

### ISSUE THREAD

**Issue by romlacerda** [plataformatec/devise#4437]
Guys, i got a problem:

When i reset my password (Forgot Your Password?) i got an email with the right instructions. Ok, it works fine!

The problem is: i can reset my password (and the new password works fine), but when i click on "Change Password" button, this is what happens:

_ActionController::ActionControllerError in Devise::PasswordsController#edit
Cannot redirect to nil!_

**Log:**

Started GET "/users/password/edit?reset_password_token=[FILTERED]" for 10.0.2.2 at 2017-02-21 03:51:31 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]"}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 528 ORDER BY `users`.`id` ASC LIMIT 1[0m
Redirected to 
Completed 500 Internal Server Error in 18ms (ActiveRecord: 0.5ms)

What should i do?

**Comment by rahul8sharma** [comment]
Modify your config/environments/development.rb

class Application < Rails::Application
  config.web_console.whitelisted_ips = '10.0.2.2'
end

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
