### ISSUE TITLE
Require subset of users to use SSO

### ISSUE THREAD

**Issue by abezzub** [plataformatec/devise#4450]
There are 2 ways to sign in on the product I am working on: one is with login/password and the other one is through SSO. Does Devise support a way to force some users to only use SSO? They should not be able to sign in with login/password. 

I can make changes to every controller that deals with sign in manually, but I'd like to find an easier solution if it exists. I know about `active_for_authentication?`, but it doesn't take any parameters, so there is no way to know what method user is using to sign in.

**Comment by fro** [comment]
Hi @abezzub,
May I ask you how you have implemented SSO? If any, what gem do you use?

**Comment by abezzub** [comment]
I use omniauth and omniauth-saml

**Comment by fro** [comment]
Thank you.

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
