### ISSUE TITLE
when i let users sign in with either email address or username, and they go to edit their email address, the form displays their username

### ISSUE THREAD

**Issue by genlighten** [plataformatec/devise#4452]
I've followed the guidelines in the Wiki for allowing my users to log in with either username or email address. It works great, but I notice that for some users, when they go to my custom form for editing their email address (not devise/registrations/edit.html.erb, but another view I've created) their username is displayed in the email field for the form.

I'm using simple_form, so the form helper code looks like this:

<%= f.input :email, required: true, autofocus: true %>

Any ideas what might be causing this behavior or suggestions for how to fix it?

Thanks,

--Dean

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
