### ISSUE TITLE
Devise does not return Bad Request for Unpermitted Parameters

### ISSUE THREAD

**Issue by johnson-yeap** [plataformatec/devise#4453]
Hi, 

Why does devise not returning 400 Bad Request for unpermitted parameter, but 401 Unauthorized instead. 
What's the design paradigm?

Is there a way to customized the return to include Bad Request for Rails strong parameters?

**Comment by betesh** [comment]
Which controllers are you referring to?  ones that inherit from DeviseController?  Or ones that require an authenticated user?

**Comment by johnson-yeap** [comment]
The one that inherits from DeviseController.

I am trying to build an API for user authentication. 

When the API calls contains typo like "paswod" instead of "password", 
I wish to override Devise behavior to return 401 Bad Request.

![screenshot from 2017-03-25 22-32-15](https://cloud.githubusercontent.com/assets/6791060/24323067/01871b02-11ab-11e7-9a1b-267bc9f96c0b.png)

**Comment by betesh** [comment]
What is `ActionController::Parameters.action_on_unpermitted_parameters` set to for your application?

**Comment by tegon** [comment]
Hello @johnson-yeap, thanks for your report.
Are you overriding the default sessions controller? If so, can you provide the code here?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
