### ISSUE TITLE
Deprecated Thread_safe gem

### ISSUE THREAD

**Issue by epinault** [plataformatec/devise#4459]
Per the gem description at https://github.com/ruby-concurrency/thread_safe

NOTE: This gem is DEPRECATED. Devise still uses it but it should really be using concurrent-ruby

Is there a plan to fix this in the near term?

**Comment by lucasmazza** [comment]
@epinault thread_safe is not a direct dependency of Devise, but it is comes from active_support 4.x. Update your app and the dependency should be gone, as Rails has moved to use concurrent-ruby instead.
