### ISSUE TITLE
Rails 5, Jquery and Devise

### ISSUE THREAD

**Issue by hacktorious** [plataformatec/devise#4460]
I've created additional fields on the Devise customer user registration page. I was originally using the rails 5 date_field. However, I've discovered this is not compatible with FF or IE. I am now in the process of switching to jquery datepicker via the 'jquery-ui-rails' gem.

The gem is working, the calendar pops up and the field is filled with the correct date. The jquery library requires the rails text_field to be used instead of the date_field.

The problem comes in when you try to save the field. The form is obviously sending the field as a string, and rails doesn't know what to do with it so it just ignores it and doesn't save it in the database. The database field is a DateTime.

**Comment by denniss** [comment]
You probably need to manually parse the `DateTime` string. I think you can do something like

```
user.your_date_time_field = DateTime.parse(params[:your_date_time_param_key]
user.save!
```

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
