### ISSUE TITLE
assets precompile failed

### ISSUE THREAD

**Issue by u007** [plataformatec/devise#4469]
Hi,

ive checked a post from 2014 with similar issue, but i couldnt find a solution with it.
i realize it attempt to load routes which causes it to load User model and causing error because it tries to connect to the database.
when i commented out the devise routes in the route file, it works fine.

using:

railties-5.0.0.rc2
devise 4.0.3

thank you

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
