### ISSUE TITLE
Not compatible with Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by jonhue** [plataformatec/devise#4472]
```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
devise (>= 4.2.1, ~> 4.2) x86-mingw32 was resolved to 4.2.1, which depends
on
      railties (< 5.1, >= 4.1.0) x86-mingw32

rails (~> 5.1.0.rc1) x86-mingw32 was resolved to 5.1.0.rc1, which depends on
      railties (= 5.1.0.rc1) x86-mingw32
```

Output after running `bundle update`

**Comment by renchap** [comment]
Related to #4444

**Comment by jasnow** [comment]
Also needed for Rails 5.2.0.alpha.

**Comment by ilovemysillybanana** [comment]
I am also experiencing this issue, switching down to version 5.0.1 resolved it for me though. I'm using windows if that matters.

**Comment by jonhue** [comment]
@ilovemysillybanana Just reference `gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'` in your Gemfile, a fix for this issue has been merged.
