### ISSUE TITLE
Does Devise render views by name only?

### ISSUE THREAD

**Issue by JustLey** [plataformatec/devise#4476]
I was coding an application and tried to make the sign up process return errors with AJAX (to update the current view). After a while I decided not to do it and reverted every change I made in that direction but I forgot to remove create.js.erb under devise/views/registrations (my overriding folder of default Devise views)

When I went to test it, I got an HTML rendered with the contents of create.js.erb.

Is this default behaviour? I have not override RegistrationsController to respond to js nor does my initializer consider :js a navigational format, but it seems that Devise uses create.js.erb anyway but rendering it to HTML. Shouldn't it use create.js.erb only if the controller responded to :js?

**Comment by tegon** [comment]
Hello @JustLey, thanks for your report.
We're using [`respond_with`](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/app/controllers/devise/registrations_controller.rb#L25) to render the create action with a fallback for [HTML](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/app/controllers/devise_controller.rb#L18).
What are you sending in your `Accept` header?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
