### ISSUE TITLE
Unable to put a definite time interval on devise reset password

### ISSUE THREAD

**Issue by DhawalSawla** [plataformatec/devise#4481]
Unable to use this config command. 
config.reset_password_within = 6.hours
This does not work. The user can reset his password through the link provided in the email even after 2 days.

**Comment by Talha5** [comment]
where are you putting this ? should be in devlopment/production.rb

**Comment by pachonk** [comment]
To specify, the devise initializer.

**Comment by DhawalSawla** [comment]
Yes, I am specifying in devise.rb. But its not working.

**Comment by tegon** [comment]
Hello thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
You can also use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
