### ISSUE TITLE
Uniqueness validator for email does not account for case_insensitive_keys config

### ISSUE THREAD

**Issue by etrepum** [plataformatec/devise#4482]
https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L30

```ruby
validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
```

Not familiar enough with the code base to know precisely what code to use to pull that setting out of the config, but this is causing an inefficient table scan to be used since we use a unique index on `LOWER(email)` in our db.

**Comment by etrepum** [comment]
This is a workaround that can be included after calling the devise class method:

```ruby
  _validators[:email].each do |v|
    next unless v.is_a?(::ActiveRecord::Validations::UniquenessValidator)
    v.instance_variable_set(
      :@options,
      v.options.merge(case_sensitive: false).freeze
    )
  end
```

**Comment by saper** [comment]
Just a question: LOWER(email) makes email addresses case insensitive, but I think they are not...

**Comment by etrepum** [comment]
In theory the local part (before the @) of an email address is case sensitive, but in practice it is case insensitive everywhere.

**Comment by tegon** [comment]
Hello @etrepum, thanks for your report.
The `Validatable` model provides some default validations that might be useful to most common use cases. Not everyone might want to use `case_sensitive: false` like you need.
In case you have to change the validations you can always remove the `:validatable` option on your model and write the validations that best suits your requirements.

Thank you!
