### ISSUE TITLE
Question: Crash when user disallows cookies?

### ISSUE THREAD

**Issue by geraldhiller** [plataformatec/devise#4485]
Hi, just a quick question.

I got this error in my app today: registrations#create (NoMethodError) "undefined method `user_url' and had to dig a bit to reproduce it.

I finally managed to reproduce it by setting my chrome to block sites from setting any kind of data. With these setting, the registration request produces this error: http://take.ms/HHYG2

However, I can't imagine that devise would simply crash if the user disallows site data. So I am assuming it is a configuration problem. Before I dig around in my app, I wanted to ask if this is a known issue.

Thanks for your help!

**Comment by tegon** [comment]
Hello @geraldhiller, thanks for your report.
I don't know exactly what would happen, but I assume Devise won't work correctly if you're using cookies for Rails' session store.
Also,  the rememberable module relies on cookies to work.

Are you using cookies for session storage?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
