### ISSUE TITLE
No route matches [GET] "/users/sign_out"

### ISSUE THREAD

**Issue by kinsbrunner** [plataformatec/devise#4486]
Hi guys,

I have been struggling for hours with this error which happens when having a link_to for destroying the session. For some reason, a GET is being sent instead of a DELETE action which makes this error happen.

Some points to highlight:
- Rails version 5.0.2, Devise 4.2.1, jquery-rails 4.3.1
- Yes, I have included the method: :delete (`<%= link_to 'Exit', destroy_user_session_path, method: :delete %>`)
- Yes, Routes file is set correctly (destroy_user_session DELETE /users/sign_out(.:format)                                    devise/sessions#destroy)
- Yes, on my application.html.erb I have already included the following lines:
```
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
```
- My application.js file looks as the following:
```
//= require jquery2
//= require jquery_ujs
//= require dataTables/jquery.dataTables
//= require dataTables/extras/dataTables.responsive
//= require turbolinks
//= require tether
//= require bootstrap-sprockets
//= require_tree .
```
- No, I am not willing to switch the Devise initializer to sign out via :get instead of :delete, I believe that's not "nice".
- If switching from link_to into button_to, it perfectlly works which makes me understand this issue is related to JS/jQuery topics.
- Everything was working fine until I added a theme

Not sure whether this could be related to the version of a gem (already played using previous versions of jQuery, Devise, etc)

Kindly let me know your ideas.
Thanks and regards.
Alejandro.

**Comment by kinsbrunner** [comment]
Let me add something weird which I am seeing through Console:

```
Started DELETE "/users/sign_out" for 10.0.2.2 at 2017-04-04 00:59:51 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::SessionsController#destroy as HTML
  Parameters: {"authenticity_token"=>"bImblK3CLXPXMpBaJNm1opywnGWm+DABf2rBRjAuzC5dJJenf8aPgEHln/pT6dQCqexTOIbrMKgYpCVyel8D8w=="}
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
Redirected to http://localhost:3030/
Completed 302 Found in 7ms (ActiveRecord: 0.8ms)

Started GET "/" for 10.0.2.2 at 2017-04-04 00:59:51 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by DashboardsController#index as HTML
  Rendering dashboards/index.html.erb within layouts/application
  Rendered dashboards/index.html.erb within layouts/application (0.5ms)
Started GET "/users/signo_out" for 10.0.2.2 at 2017-04-04 00:59:52 +0000
Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

ActionController::RoutingError (No route matches [GET] "/logout"):
```

What it sounds weird to me is that it first triggers the DELETE to the correct "place", then a GET to "/" and, finally, the GET to "users/signo_out" which generates the error.

Hope this helps to find the issue as I am not being able to solve it.

**Comment by kinsbrunner** [comment]
Guys,
Just tried removing all the theme JS and started adding them back until I found the piece of js which was changing <a> controls.
This is definitely not a gem related bug so I am closing the issue.
Regards.
Alejandro.

**Comment by laurenmacam** [comment]
In my case the problem occurred because I'm not using jquery on the project

**Comment by mittalyashu** [comment]
Still facing the same problem (and I am not even using js)

**Comment by Nechitadi** [comment]
hey, @kinsbrunner , did you manage to solve this problem? I have the same issue and I'm can't figure out what's the problem

**Comment by jorgearimitsu** [comment]
This feature only works with [jquery-ujs](https://github.com/rails/jquery-ujs)
> makes non-GET requests from hyperlinks.

**Comment by julianguyen** [comment]
Is there any way to get this working without having to use jQuery?

**Comment by tegon** [comment]
By default the sign out route uses the [DELETE](https://github.com/plataformatec/devise/blob/master/lib/generators/templates/devise.rb#L257) HTTP method. You can either make an ajax yourself - without the help of jQuery - or change the Devise configuration to accept sign out as a GET request.
```ruby
Devise.setup do |config|
  # The default HTTP method used to sign out a resource. Default is :delete.
  config.sign_out_via = :get
end

**Comment by jorgearimitsu** [comment]
> Is there any way to get this working without having to use jQuery?

You can use the button_to helper and style the button if you need.

**Comment by fahrulrizall** [comment]
> > Is there any way to get this working without having to use jQuery?
> 
> You can use the button_to helper and style the button if you need.
> 
> `<%= button_to 'Exit', destroy_user_session_path, method: :delete %>`

hi Jorge, it's worked
Thanks

**Comment by 1234dev** [comment]
Having the same problem. Why's it gotta be like that? `<%= link_to "Logg ut", destroy_user_session_path, method: :destroy %>` and `devise_for :users` is the default setup you get when installing Devise.

**Comment by 1234dev** [comment]
Having the same problem here. My app is not using any JS and `config.sign_out_via = :get` doesn't make any difference.

@kinsbrunner shouldn't this issue be reopened?

**Comment by binyamindavid** [comment]
Can you reopen this issue?

**Comment by carlosantoniodasilva** [comment]
Can you provide a sample application that reproduces the issue? If we can confirm it's reproducible in a sample app, we can reopen and investigate further. Thanks.

**Comment by binyamindavid** [comment]
I found that issue. In rails 6, I had include jquery and popper.js 

```
const { environment } = require('@rails/webpacker')

const webpack = require('webpack')
environment.plugins.append(
  'Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    Popper: ['popper.js', 'default']
  })
)


module.exports = environment
```

This fixed the problem.

**Comment by PrincetonAfeez** [comment]
Tegon;s solution worked for me

Devise.setup do |config|
  # The default HTTP method used to sign out a resource. Default is :delete.
  config.sign_out_via = :get
end

**Comment by jose-Abel** [comment]
> Is there any way to get this working without having to use jQuery?

I fixed this by installing the gem "rails-ujs" and going into app/assets/javascripts/application.js and adding this code:
//= require rails-ujs

Hope this helps anyone dealing with this error

**Comment by aadikrs** [comment]
Dont know if someone still has this issue but i did a combination of 2 solutions:
i changed HTTP default :delete to :get (by @tegon )
`
Devise.setup do |config|
  # The default HTTP method used to sign out a resource. Default is :delete.
  config.sign_out_via = :get
end
`
and
i used the rails-ujs gem as well as a safety net since i was in a time crunch to deploy (by @jose-Abel )

**Comment by shiccorama** [comment]
> <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
>     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

Thank you so much, you saved my day ...
