### ISSUE TITLE
HOBA auth extension

### ISSUE THREAD

**Issue by aledalgrande** [plataformatec/devise#4490]
Hi,
thinking of writing an extension to support [HOBA](https://tools.ietf.org/html/rfc7486). Do you have any documentation on extension development? Anybody working on the same?

**Comment by tegon** [comment]
Hi @aledalgrande!
Unfortunately, we do not. Maybe you can get around by looking at some of these extensions: https://github.com/plataformatec/devise/wiki/Extensions.
Maybe you could add a Wiki page here with some instructions when you're done. We would appreciate that.

Thank you!
