### ISSUE TITLE
getting random "Authorized users only." when uploading multiple files at once.

### ISSUE THREAD

**Issue by m2omou** [plataformatec/devise#4493]
This only happen when I am trying to upload 15, 20 files at the time. And I don't know if this is due to the timeout. But most of the api response is 200. But some fail and return "Authorized users only.".

But I am always still logged in ? Any idea ? Also this seems to happen only in production mode.

Thank you.

![image](https://cloud.githubusercontent.com/assets/4422555/24691101/49328472-1986-11e7-9060-0aff7932e32c.png)

**Comment by tegon** [comment]
Hello @m2omou, thanks for your report.
This issue is probably with another part of your application since Devise does not have built-in authorization.
