### ISSUE TITLE
Validation preventions

### ISSUE THREAD

**Issue by 127** [plataformatec/devise#4494]
Looks like model cross references sometimes do prevent registration:
Got 
```
class User < ApplicationRecord
  before_save :setup_role, :setup_account

  belongs_to :account
  has_and_belongs_to_many :roles

  def setup_role
    if self.role_ids.empty?
      self.role_ids = [2]
    end
  end

  def setup_account
    if self.invited_by_id != nil
      self.account = self.invited_by.account
    elsif self.account_id == nil
      self.account = Account.create('number'=>Random.new.rand(0..999999999))
    end
  end

  devise :invitable, :database_authenticatable, :registerable, :confirmable, :lockable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :twitter]
end
```
Looks like it fails to save  because Accound and Roles have ```has_many :users``` and ```has_and_belongs_to_many :users```

It worked always and I don't even know when it began to fail as far as it dosn't return error (just always returns smth like ```SELECT 1 AS one FROM `users` WHERE `users` .`email` = BINARY 'mail@mail.com' LIMIT 1 ``` and redirects to registration without error or flash + code 200).

Can be fixed with bypassing validations:
```
  before_validation :setup_role, on: :create
  before_validation :setup_account, on: :create
```

Is it ok? Or a bug?

**Comment by tegon** [comment]
It seems like its an issue with the callbacks. By taking a quick look, maybe the`User` is invalid, and in that case, the `before_save` will never be called. Reference: http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html.

Anyway, please use StackOverflow for this kind of questions or help requests. There a wider community will be able to help you. We reserve the issues tracker for issues only.
If you're able to isolate the issue in a clean application and find out that it is indeed a bug, please open another issue.

Thank you!
