### ISSUE TITLE
protecte_attributes file problem

### ISSUE THREAD

**Issue by djnilo** [plataformatec/devise#4495]
Issues with the protected_attributes file No file to use fix this problem if any of the forum can help me please thanks

Bundler could not find compatible versions for gem "activemodel": In snapshot (Gemfile.lock): activemodel (= 5.0.2)

In Gemfile: protected_attributes x86-mingw32 was resolved to 1.1.3, which depends on activemodel (< 5.0, >= 4.0.1) x86-mingw32

rails (~> 5.0.2) x86-mingw32 was resolved to 5.0.2, which depends on
  activemodel (= 5.0.2) x86-mingw32

rails (~> 5.0.2) x86-mingw32 was resolved to 5.0.2, which depends on
  activemodel (= 5.0.2) x86-mingw32

web-console (>= 3.3.0) x86-mingw32 was resolved to 3.5.0, which depends on
  activemodel (>= 5.0) x86-mingw32

**Comment by rafaelfranca** [comment]
Seems that you are using `protected_attributes` with Rails 5 but `protected_attributes` does not support Rails 5.

**Comment by djnilo** [comment]
rafaelfranca
How to solve my problem i am newbie in ruy rails could you help me please thanks

**Comment by rafaelfranca** [comment]
Is this a new rails application? If yes, to solve your problem you just need to remove `protected_attributes` gem.

**Comment by djnilo** [comment]
Thanks for replying but remove protected_attributes gem.
And I have to install it to work

**Comment by rafaelfranca** [comment]
You can't install this gem in Rails 5. It doesn't work. If you really need to install this gem you will have to use Rails 4.2.

Why do you need to install it?

**Comment by djnilo** [comment]
Sorry, I installed the version that you comment please, I have windows 7

C: \ project> rails -v
Rails 5.0.2

C: \ project> ruby -v
Ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
