### ISSUE TITLE
gem 'devise', github: "plataformatec/devise"

### ISSUE THREAD

**Issue by djnilo** [plataformatec/devise#4496]
Problem installing gem validations
Gem 'devise', github: "platformtec / devise"

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clon
e+%22https+%2F%2Fgithub.com%2Fplataformatec%2Fdevise.git%22+%22C+%2FRuby22%2Flib
%2Fruby%2Fgems%2F2.2.0%2Fcache%2Fbundler%2Fgit%2Fdevise-50267758d0a51b37ae44e96a
013aa7bb489e3552%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:

**Comment by rafaelfranca** [comment]
Thank you for the report. Seems you have an issue with bundler. Please open an issue in their issue https://github.com/bundler/bundler/issues
