### ISSUE TITLE
Refresh /users/edit after update fails

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [plataformatec/devise#4508]
Hello,

This is not a big issue, but I thought of giving you an alert.
If the user try and fails to update his account in the /users/edit, he gets redirected to /users/. 
If he refresh the page he will get a Routing Error, but if he submits no error will be found.

A solution was provided hear. 

http://stackoverflow.com/questions/29049002/why-does-devise-me-redirect-me-to-users-instead-of-users-edit-when-my-account#29050529

Thanks a lot and if this is not relevant feel free to close the issue 
Sorry and Amazing Software
Best Regards
Fabrizio Bertoglio

**Comment by tegon** [comment]
Closing in favor of #4573
