### ISSUE TITLE
Rails 5.1 and the Devise gemspec

### ISSUE THREAD

**Issue by noelrappin** [plataformatec/devise#4510]
The devise gem spec reads

`s.add_dependency("railties", ">= 4.1.0", "< 5.1")` 

Now that Rails 5.1 is out, a bundle install of a Rails 5.1 app installs Devise 1.5.4 instead of the current version.

**Comment by Obversity** [comment]
Same problem here.

**Comment by imKota** [comment]
+

**Comment by imKota** [comment]
@noelrappin maybe [my fix?](https://github.com/plataformatec/devise/issues/4511)

**Comment by Obversity** [comment]
Looks like #4444 will fix it.

**Comment by kernow** [comment]
There is a more up to date PR https://github.com/plataformatec/devise/pull/4512 that should fix this issue

**Comment by rafaelfranca** [comment]
Can you try the master branch? It should be fixed there.
