### ISSUE TITLE
Support Railties v5.1.0 ?

### ISSUE THREAD

**Issue by ahmed-taj** [plataformatec/devise#4515]
Hello, I wonder what makes Devise incompatible with Rails version 5.1.0.

I get this error when I try to install the latest Devise with Rails 5.1.0:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    devise (~> 4.2.1) was resolved to 4.2.1, which depends on
      railties (< 5.1, >= 4.1.0)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      railties (= 5.1.0)
```

**Comment by dsander** [comment]
The master branch is compatible with Rails 5.1, however the latest commits introduced a bug. For me this version works: 
```ruby
gem 'devise', github: 'plataformatec/devise', ref: '83002017'
```

**Comment by rafaelfranca** [comment]
Yeah, it is supported on master.
