### ISSUE TITLE
Devise 4.0 does not work install on Rails 5.1.0

### ISSUE THREAD

**Issue by snood1205** [plataformatec/devise#4518]
Because Devise relies on railsties (< 5.1), and with Rails 5.1.0's version of railsties being 5.1.0, Devise cannot install on Rails 5.1.0.

**Comment by juanmanuelramallo** [comment]
The same here!

**Comment by h-michael** [comment]
@snood1205 @juanmanuelramallo 
#4515 here is same issue.

**Comment by juanmanuelramallo** [comment]
Yep, thank you @h-michael. I had to use these lines in my gemfile in order to make it work:
```gem 'devise', github: 'plataformatec/devise'
gem 'erubis'```

**Comment by rafaelfranca** [comment]
For now you can use the master branch. The release will be made in the week

**Comment by josephecombs** [comment]
Elastic Beanstalk users like myself can't point Gemfiles to github repositories (and the custom configuration required to make it work is more than I am able to pursue.  I do wish they would support this), so this is definitely painful and the sooner a new release gets made, the better.

**Comment by ZombieHarvester** [comment]
@josephecombs It's actually pretty easy to teach EB to get gems from github, all you need is to install git on the server

just add `.ebextensions/packages.config` file to the root of your project with 
```
packages:
  yum:
    git: []
```

Fellow Elastic Beanstalk user

**Comment by josephecombs** [comment]
Yeah I did that and it did not work

**Comment by josephecombs** [comment]
Eventually, in elasticbeanstalk, after multiple rebuildings of my environment, pointing the gem at github worked.  Make sure your Gemfile.lock doesn't refer to 1.5.4 in any way (no clue how that point version was getting into Gemfile.lock AT ALL.  Could be a problem with bundler?  I have no idea)

**Comment by sethdeckard** [comment]
@josephecombs Bundler probably picked that earlier version when during update because it had more loosely (or perhaps undefined) dependencies than newer versions of the gem, so it was attempting to find the "best match". If your Gemfile didn't specify any version requirements for devise then this would have been the expected behavior even though it is a much older version of the gem.

**Comment by henderea** [comment]
From what I could tell, 1.5.4 was the newest version of devise that didn't conflict with rails 5.1.  I think if you don't define a version requirement for devise, it will use 1.5.4 because anything newer specifies a maximum version on some gem rails also uses, and that maximum version restriction prevents it from accepting rails 5.1.

**Comment by josephecombs** [comment]
That's a good call @henderea. I am now encountering an issue running rails console on the Elastic Beanstalk instance due to "...[... dot git] not yet checked out. Run `bundle install` first.", then I run that and get a permissions issue.

My quick hack is to chmod -R 777 the /var/app/current directory and install the gem from github as ec2-user and try running rails console again.  I will report back here when that is done.

Please make a point release so I can stop doing this stuff.

**Comment by maxexcloo** [comment]
Any news on this?

**Comment by twe4ked** [comment]
5 days ago:

> For now you can use the master branch. The release will be made in the week

**Comment by josephecombs** [comment]
wow! thanks @twe4ked! I didn't see that message from the gem maintainer, here in this thread!

**Comment by vincentwoo** [comment]
@rafaelfranca any news on cutting a new release?

**Comment by dannytatom** [comment]
Any update? I need to use a gem that depends on devise, so not really practical to fork that and make it depend on master then my project depend on my fork.

**Comment by mvz** [comment]
@dannytatom have you tried adding devise to your Gemfile as well and have that point to devise master? IME, something like that should work, since the devise master branch still has version 4.2.1.

**Comment by dannytatom** [comment]
@mvz yea, but the other gem ([devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth)) has explicit version requirement on devise. so if i add devise to my gemfile (pointing to master), then it, it will complain about version mismatch.

**Comment by mvz** [comment]
@dannytatom wow, that gem has a really paranoid version requirement, essentially not even trusting Devise to do a sane 4.2.2 version. In any case, does it work if you point to devise commit a62faa2c8258ba1c35fe84e147f42c35eccccb8a? That one still has the 4.2.1 version number.

**Comment by josephecombs** [comment]
please cut a point release

**Comment by snood1205** [comment]
Can someone please just fix this. This has been blowing up my GH notifications and I'd close the issue but it's not resolved.

**Comment by jmfederico** [comment]
Anything missing for a release to be made?
If help is needed, please let us know.

Really needing this release.

**Comment by rafaelfranca** [comment]
We need people to test the master branch. @lucasmazza is going to release since I don't have access.

**Comment by lucasmazza** [comment]
@rafaelfranca you have release permissions now 😎 

The only block for me is https://github.com/plataformatec/devise/issues/4531, so if anyone can re-test master with Mongoid we are only a `rake release` away from 4.3.0.

**Comment by hk-dd** [comment]
The problem still remains on my PC (Windows 7):
I just updated rails 5.0.2 => 5.1.1, then 'bundle install', then devise is downgraded 4.2.1 => 1.5.4

**Comment by mvz** [comment]
@hk-dd that is to be expected, since this ticket is still open. As you can see in the comments above, release of version 4.3.0 fixing this is imminent. Until then, please also find the instructions in e.g. https://github.com/plataformatec/devise/issues/4518#issuecomment-298623103 for a workaround.

**Comment by josephecombs** [comment]
Please cut a point release.

**Comment by lucasmazza** [comment]
> Broken code is in production RIGHT NOW.

Nope. You can always point your Gemfile to the git repo and go with it while the code isn't on rubygems, so there's no reason to be so mad about code that you get for free.

Anyhow, 4.3.0 is out.

**Comment by deivid-rodriguez** [comment]
Thanks @lucasmazza! :heart: :tada:

**Comment by dannytatom** [comment]
🙏

**Comment by jmfederico** [comment]
Thank to all the developers!

**Comment by damien-roche** [comment]
We love you :heart:
