### ISSUE TITLE
devise sign up with same email  

### ISSUE THREAD

**Issue by netmoleCBA** [plataformatec/devise#4520]
hello there ,
some of my users tryed to re-register  and form dies on 500 and  
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

logs on attached  gist 

https://gist.github.com/netmoleCBA/241bd2a9ec7e907ff31c8f3847f0a133

**Comment by Deckluhm** [comment]
The error tells you there is something wrong with your translation:
```
ActionView::Template::Error (translation data {:one=>"%{resource} nebyl uložen kvůli chybě:", :other=>"%{resource} nebyl uložen kvůli %{count} chybám:"} can not be used with :count => 2)
```
If that doesn't help you solve your issue, please provide more info as stated in the [bug report guide](https://github.com/plataformatec/devise/wiki/Bug-reports).
Additional info we are looking for here are Devise version and more code (corresponding view mainly).

**Comment by netmoleCBA** [comment]
well i am  use  rails 5 with devise from rubygems   
i am use czech translatation  
template and gem file added to  gist

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
