### ISSUE TITLE
Filter chain halted as :require_no_authentication rendered or redirected

### ISSUE THREAD

**Issue by netmoleCBA** [plataformatec/devise#4524]
Hello there , i find strange error  while i am register user 
when i am use firefox  it stops  at 
Filter chain halted as :require_no_authentication rendered or redirected
when i am register using  google chrome  registration proceed and all works 
can anyone help me or suggest me 

> 
> I, [2017-05-03T10:00:11.999772 #8986]  INFO -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e] Started GET "/users/sign_up" for 192.168.2.127 at 2017-05-03 10:00:11 +0200
> I, [2017-05-03T10:00:12.000211 #8986]  INFO -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e] Processing by RegistrationsController#new as HTML
> D, [2017-05-03T10:00:12.001428 #8986] DEBUG -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e]   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 25], ["LIMIT", 1]]
> I, [2017-05-03T10:00:12.002172 #8986]  INFO -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e] Redirected to http://192.168.100.3/
> I, [2017-05-03T10:00:12.002294 #8986]  INFO -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e] Filter chain halted as :require_no_authentication rendered or redirected
> I, [2017-05-03T10:00:12.002424 #8986]  INFO -- : [00c3cf36-b1c3-4f51-bbe3-7df10cea696e] Completed 302 Found in 2ms (ActiveRecord: 0.3ms)
> I, [2017-05-03T10:00:12.095431 #8986]  INFO -- : [19d88b11-0575-4bd1-a54c-a1ba3b9ec7e9] Started GET "/" for 192.168.2.127 at 2017-05-03 10:00:12 +0200
> I, [2017-05-03T10:00:12.095876 #8986]  INFO -- : [19d88b11-0575-4bd1-a54c-a1ba3b9ec7e9] Processing by EventsController#index as HTML
> D, [2017-05-03T10:00:12.097210 #8986] DEBUG -- : [19d88b11-0575-4bd1-a54c-a1ba3b9ec7e9]   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 25], ["LIMIT", 1]]
> I, [2017-05-03T10:00:12.097693 #8986]  INFO -- : [19d88b11-0575-4bd1-a54c-a1ba3b9ec7e9] Redirected to http://192.168.100.3/home/auth
> I, [2017-05-03T10:00:12.097876 #8986]  INFO -- : [19d88b11-0575-4bd1-a54c-a1ba3b9ec7e9] Completed 302 Found in 2ms (ActiveRecord: 0.3ms)
> I, [2017-05-03T10:00:12.132839 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098] Started GET "/home/auth" for 192.168.2.127 at 2017-05-03 10:00:12 +0200
> I, [2017-05-03T10:00:12.133540 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098] Processing by HomeController#auth as HTML
> D, [2017-05-03T10:00:12.135100 #8986] DEBUG -- : [98ea764d-b01c-4234-bbeb-aac911a60098]   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 25], ["LIMIT", 1]]
> I, [2017-05-03T10:00:12.135844 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098]   Rendering home/auth.html.erb within layouts/application
> I, [2017-05-03T10:00:12.136110 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098]   Rendered home/auth.html.erb within layouts/application (0.1ms)
> I, [2017-05-03T10:00:12.136895 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098]   Rendered shared/_header.html.erb (0.2ms)
> I, [2017-05-03T10:00:12.137164 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098]   Rendered shared/_flash_messages.html.erb (0.0ms)
> I, [2017-05-03T10:00:12.137449 #8986]  INFO -- : [98ea764d-b01c-4234-bbeb-aac911a60098] Completed 200 OK in 4ms (Views: 1.8ms | ActiveRecord: 0.4ms)

**Comment by damel** [comment]
If you currently signed in, the devise does not allow some action like sign up for a new users. You can try to overriding methods which comes from Devise::RegistrationsController: `prepend_before_action :require_no_authentication, only: :cancel` instead of `prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]`.

**Comment by netmoleCBA** [comment]
summary  
vivaldi and google chrome  works without error
Internet explorer ends  in endless loop 
let me share Gist with files from my project  
https://gist.github.com/netmoleCBA/94137abb75484548912ee23ee64a3d58
as i realy dont know  where is my error

**Comment by netmoleCBA** [comment]
my mistake i am used  redirect to :back  in root path controller  
now i am testing my new code and if it works i am close this issue

**Comment by tegon** [comment]
Closing this since it looks it was already solved.

**Comment by mices** [comment]
> my mistake i am used redirect to :back in root path controller now i am testing my new code and if it works i am close this issue

there's no `redirect to` you'll get undefined method 'to'
