### ISSUE TITLE
Push Rails 5.1 Compatible version to rubygems

### ISSUE THREAD

**Issue by rrosen** [plataformatec/devise#4525]
Thanks for merging #4512 and making the gemspec compatible with Rails 5.1.  I've followed the advice there and referenced `gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'` in my Gemfile.  

Would it be possible to get a new version pushed to rubygems?  Then we could take out the reference to the master branch from our Gemfiles.

**Comment by Deckluhm** [comment]
https://github.com/plataformatec/devise/issues/4518#issuecomment-298213971
