### ISSUE TITLE
Custom methods to work with turboboost

### ISSUE THREAD

**Issue by jonhue** [plataformatec/devise#4532]
Turboboost requires a method (create/update) to execute a method in case of an error like so:

```ruby
def create
  @post = Post.new(post_params)
  if @post.save
    flash[:notice] = 'Post was successfully created.'
    redirect_to @post
  else
    respond_to do |format|
      format.html { render :new }
      format.js { render_turboboost_errors_for(@post) }
    end
  end
end
```

Is there a way I can extend the devise methods for sessions/registrations/... to respond in such a way?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
