### ISSUE TITLE
What is "email_in_database" and how to use it?

### ISSUE THREAD

**Issue by Zhomart** [plataformatec/devise#4533]
I'm getting error using devise on master branch.

Rails 5.1
Ruby 2.4.1

**Comment by lucasmazza** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Zhomart** [comment]
Sorry about that. 

I've just searched in devise. I see `email_in_database` is used here https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L260

But cannot find where it's defined.

**Comment by rafaelfranca** [comment]
In Rails. It was named `email_was` before Rails 5.1.
