### ISSUE TITLE
Revert an unconfirmed email change

### ISSUE THREAD

**Issue by tuliren** [plataformatec/devise#4535]
If a user changes her email from `old@email.com` to `new@email.com`, and before she confirms the new address, she'd like to revert the change, currently it seems that `devise` cannot do that out of the box.

Do you think it is valid to support this feature? Either the `confirmable_controller#create` can detect this case and set `unconfirmed_email` to `nil`, or there is a new action that explicitly revert the pending email change.

Sorry if this has already been discussed before. I have search through the wiki and issues with keywords like "email", "change", "revert" and "cancel", and could not find any existing one.

**Comment by deneuxa** [comment]
+1 for this problem

**Comment by tegon** [comment]
Hello thanks for your request.
We don't have plans to support this for now, so although I know it's not ideal, you probably will have to override this code to add your custom behavior.
If this became a popular feature request, we could think about supporting in a next version.

Thank you!

**Comment by tuliren** [comment]
Got it. Thank you.
