### ISSUE TITLE
Question: where is 'devise-4.2.0/app/controllers' added to `$LOAD_PATH`

### ISSUE THREAD

**Issue by flanker** [plataformatec/devise#4537]
I can see when you require devise, the lib directory will be added into `$LOAD_PATH`. (most gems will do like this).

But I couldn't find where the code adds `devise-4.2.0/app/controllers` into `$LOAD_PATH`. (So the rails could find the devise built controllers)

Thanks in advanced.

**Comment by lucasmazza** [comment]
@flanker we don't require or push anything to `$LOAD_PATH` manually, but defining the [`Devise::Engine`](https://github.com/plataformatec/devise/blob/079ed3b6f8b671acde2dd630d28d21adb010fb3a/lib/devise/rails.rb) class as a subclass of `Rails::Engine` makes Rails load controllers/models/assets/etc from gems as if they were in the application themselves. I can't pinpoint the exact code from Rails that does that but it's how it works :)

**Comment by flanker** [comment]
@lucasmazza Thanks a lot for your reply. I will check the relevant code then.
