### ISSUE TITLE
Downcase authentication_keys in translations

### ISSUE THREAD

**Issue by emmanuelmillionaer** [plataformatec/devise#4538]
Hi community, thanks for this great gem! 🙂 

I'm wondering why the `authentication_keys` in my translations are shown with uppercase:
e.g.

 `en.devise.failure.invalid: "Invalid %{authentication_keys} or password." `

renders as:

![bildschirmfoto 2017-05-16 um 13 59 12](https://cloud.githubusercontent.com/assets/3428184/26105297/b014d33a-3a41-11e7-8c6e-23784719f290.png)

 Is there a way to downcase the `authentication_keys`? 🙂   Thanks for your help! 💯

**Comment by daniel-rikowski** [comment]
To answer your "why" part: 
Devise calls the Rails method `human_attribute_name` for each attribute. This translates the attribute or - if no translation exists - calls `humanize` on the attribute name, which convers the first character to upper case.

See https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L104 and https://github.com/rails/rails/blob/master/activemodel/lib/active_model/translation.rb#L62

In this specific case it's rather unfortunate, but I doubt it's worth to change this (imho)


To fix it you could either monkey-patch `FailureApp` or - if `email` is your only authencation key - you could just change the translation:

en.devise.failure.invalid: "Invalid email or password."

**Comment by emmanuelmillionaer** [comment]
@daniel-rikowski thanks for this in-depth explanation 👍 

It helped me a lot that you pointed out the related devise code parts.

I will go with with the easy solution of changing the translation to: `"Invalid email or password."`

Have a nice day! 💯

**Comment by rubenochiavone** [comment]
Hi there, I faced this issue and found this thread. I know this is an old thread but I think that it could be fixed at this gem:

https://github.com/heartcombo/devise/blob/master/lib/devise/failure_app.rb#L106

```diff
-        keys = (auth_keys.respond_to?(:keys) ? auth_keys.keys : auth_keys).map { |key| scope_class.human_attribute_name(key) }
+        keys = (auth_keys.respond_to?(:keys) ? auth_keys.keys : auth_keys).map { |key| scope_class.human_attribute_name(key).downcase }
```

WDYT?

**Comment by collimarco** [comment]
I think that it makes sense to call `downcase`, I don't know why this has not been fixed

**Comment by daniel-rikowski** [comment]
@rubenochiavone 

That would help with most languages, but it would break German and Luxembourgish where all nouns are capitalized: 

For example the (correct) German message:

`Ungültige E-Mail-Adresse oder Kennwort`

would look like this (which is incorrect):

`Ungültige e-mail-adresse oder Kennwort`

Perhaps a separate interpolated variable could be used:

```ruby
options[:authentication_keys] = keys.join(I18n.t(:"support.array.words_connector"))
options[:authentication_keys_lc] = options[:authentication_keys].downcase
```

And then use it like this:

```yaml
en.devise.failure.invalid: "Invalid %{authentication_keys_lc} or password." 
de.devise.failure.invalid: "Ungültige %{authentication_keys} oder Kennwort." 
```

Or something similar.
