### ISSUE TITLE
Devise 3.5 Bug

### ISSUE THREAD

**Issue by WriteCodeEveryday** [plataformatec/devise#4539]
I know that devise 3.5 is old and probably not supported but I just want someone to confirm I'm not insane, because this is really surprising to me.

I have a client User table with the following configurations.

`devise  :database_authenticatable, :lockable,
          :timeoutable, :recoverable, :trackable, :encryptable`

I'm using the default lockable settings.

> config.lock_strategy = :failed_attempts
> 
> config.unlock_keys = [ :username ]
> 
> config.unlock_strategy = :both
> 
> config.maximum_attempts = 10
> 
> config.unlock_in = 1.hour

Here's the issue, someone gets locked out and they receive the unlock email immediately. There is no 1 hour unlock period, just lock, email and unlock all within a few minutes. 

Is there any issue with the :both unlock strategy under Devise 3.5 that could cause unlock emails to be delivered immediately, and if so, what is the recommended minimum version to fix this?

**Comment by kiskoza** [comment]
Hello!

This is the expected behaviour

```
:time  = Re-enables login after a certain amount of time (see :unlock_in below)
```

From the default [config file](https://github.com/plataformatec/devise/blob/321fe1d13b172c7160bce9fd083d526cb4900fcc/lib/generators/templates/devise.rb#L173-L185) for devise 3.5

**Comment by WriteCodeEveryday** [comment]
Right, but :both implies that you get both :time and :email. 

`:both  = Enables both strategies`

I know I don't speak English natively, but I think that's pretty explicit to me.

**Comment by kiskoza** [comment]
It doesn't work like a ban (like you cannot unlock your account in the next one hour).

The workflow is something like this: you lock your account, time passes by, then your account will be unlocked after 1 hour. If you enable the email startegy it means they have to wait 1 hour OR unlock their account via e-mail.

**Comment by WriteCodeEveryday** [comment]
Oh, so it's not inclusive.

Sorry, I'm a total derp. I thought it was ":both" means wait one hour, deliver the email, click the email and unlock.

**Comment by WriteCodeEveryday** [comment]
My concerns have been properly addressed in this issue, and as such, I am closing it.
