### ISSUE TITLE
InvalidAuthenticityToken while loggin_in when using guest user feature

### ISSUE THREAD

**Issue by p29892p** [plataformatec/devise#4541]
Hi There,

I've been facing a InvalidAuthenticityToken error when logging into my application using normal login functionality. I've added guest user feature by following below article.

https://github.com/plataformatec/devise/wiki/How-To:-Create-a-guest-user

Everything is working well and issue coming when i tried to login to application using email and password.
If the credentials are wrong it is showing invalid credentials message, but when credentials are correct  InvalidAuthenticityToken exception is coming. Can some please help me to resolve this.

Thanks in advance.

**Comment by peeyushsingla** [comment]
@p29892p sample application to reproduce bug?

**Comment by tegon** [comment]
Seems like the [CSRF](http://guides.rubyonrails.org/security.html#cross-site-request-forgery-csrf) header/parameter is [missing or the value is wrong](http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html). 

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
