### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by streeturchin** [plataformatec/devise#4543]
Is there any plans to make adding custom fields to registration/sign in part of the gem by default. This would be a great addition, although there are ways to do it fairly easily it would be great if it was part of the gem (to avoid gem update related issues )

**Comment by rafaelfranca** [comment]
Thank you for the request. This gem permit you to extend any behavior overriding the views and extending the controllers.

You can use those features to customize which fields you want in the registration and sign in process similar with what is done in this guide in the wiki page https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address.

Apart from those supported ways, we don't plan to add any other.

**Comment by streeturchin** [comment]
thank you
