### ISSUE TITLE
Readme error: rake (not rails) db:migrate

### ISSUE THREAD

**Issue by bperlik** [plataformatec/devise#4545]
Next, check the MODEL for any additional configuration options you might want to add, such as confirmable or lockable. If you add an option, be sure to inspect the migration file (created by the generator if your ORM supports them) and uncomment the appropriate section. For example, if you add the confirmable option in the model, you’ll need to uncomment the Confirmable section in the migration.
Then run rails db:migrate

Should be "Then run rake db:migrate

**Comment by peeyushsingla** [comment]
@bperlik as per latest rails release command has changed from `rake db:migrate` to `rails db:migrate` Refference:- 

> The very first migration related bin/rails task you will use will probably be rails db:migrate. In its most basic form it just runs the change or up method for all the migrations that have not yet been run. If there are no such migrations, it exits. It will run these migrations in order based on the date of the migration.

[Running Ruby on Rails Migration](http://guides.rubyonrails.org/active_record_migrations.html#running-migrations)

**Comment by professorNim** [comment]
@peeyushsingla agreed for latest release, however not everyone updates to the most stable release as it comes out. Maybe include the syntax for current release and previous releases for a time, unless the developer decides to opt out of supporting previous releases. Just my 2 cents...

**Comment by tegon** [comment]
I understand the confusion, but indeed our README matches the latest Rails version, that's why we're using the new syntax.
Thanks.
