### ISSUE TITLE
Two omniauth strategies with same name.

### ISSUE THREAD

**Issue by ronaldoooo** [plataformatec/devise#4546]
I implemented two omniauth method, one called 'open_wechat', another called 'wechat'. One thing to tell, they are for two different platforms.
```ruby
      def find_strategy
        ::OmniAuth.strategies.find do |strategy_class|
          strategy_class.to_s =~ /#{::OmniAuth::Utils.camelize(strategy_name)}$/ ||
            strategy_class.default_options[:name] == strategy_name
        end
      end

```

Look at lib/devise/omniauth/config.rb line 30. The code get confused here. The 'wechat' strategy will match the 'open_wechat' stratety, and then return the 'OpenWechat' class.

I fix this problem by monkey patch the method. However, why use regular match here? Is there any strategy that has to be matched with regular expression other than '=='?

**Comment by ronaldoooo** [comment]
link here.
https://github.com/plataformatec/devise/blob/master/lib/devise/omniauth/config.rb#L30

**Comment by ClaudioCarmeli** [comment]
Hi @ronaldoooo not exactly 'on topic' but What place did you go to to get the keys for WeChat? I have been trying for a while but I am afraid I might have been using the wrong website / url.

**Comment by tegon** [comment]
Hello @ronaldoooo, thanks for your report.

> why use regular match here? Is there any strategy that has to be matched with regular expression other than '=='?

Unfortunately, I don't have an answer for this question :/
This code is really old, and I'm afraid many people may be reeling on this regular expression match already. So although I know it's not ideal, you're better off overriding this on your application code.

Thanks again!
