### ISSUE TITLE
params nested inside "registration" instead of "user"

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [plataformatec/devise#4551]
I'm doing a simple backbone #save and this is what's firing:

Processing by Devise::RegistrationsController#create as JSON
  Parameters: {"email"=>"123@123.com", "password"=>"[FILTERED]", "registration"=>{"email"=>"123@123.com", "password"=>"[FILTERED]"}}

since devise is looking for default_params under "user"=> I'm getting a 422 because email and password can't be blank.

where and why are my params being nested inside registration?

**Comment by peeyushsingla** [comment]
@Jascha-Sundaresan can you share sample application?

**Comment by Jascha-Sundaresan** [comment]
I circumvented this problem by relying on window.fetch to send the exact payload I wanted.
