### ISSUE TITLE
use jquery-ui dialog with devise failed on production (ok on development)

### ISSUE THREAD

**Issue by jerome-diver** [plataformatec/devise#4553]
i do use a jquery-ui dialog and some coffeescript files for use authentication from devise.
All works fine on development, but failed on production.
i use own controller (same as explain on github devise repo) and views... add route devise_for, etc...
i absolutly don't know how to make rake compile devise coffee files...

**Comment by rubyrider** [comment]
What is the server log when you post the request ?

**Comment by jerome-diver** [comment]
hi @rubyrider ,
this is my log/production.log end of file (only this line show an error)

`F, [2017-06-08T10:48:44.247239 #14763] FATAL -- : 
NoMethodError (private method `permit' called for #<Devise::ParameterSanitizer:0x00000005ab0950>
Did you mean?  print):  app/controllers/application_controller.rb:19:in `configure_permitted_parameters'
`
here is my application_controller file:
https://ptpb.pw/Jbjz

**Comment by jerome-diver** [comment]
or maybe i should ask a different way more understandable:
on rails-4.2.8, how to include .coffee script from app/views/devise/sessions/*.coffee to be generate in assets ?

**Comment by tegon** [comment]
@jerome-diver Did you manage to find a solution then or is this still relevant?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
