### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/users")

### ISSUE THREAD

**Issue by krunalbabaria** [plataformatec/devise#4556]
Hello,

  I have configured devise 4.3.1 with rails 5.1.1. But i have facing one problem.
  The scenario is that.
   **Step 1** click on sign up button at that time it will redirect to "http://localhost:3000/users/sign_up" 
   **Step 2** click on submit button without fill any value.
   **Step 3** It will redirect to ""http://localhost:3000/users".
   **Step 4** in url ""http://localhost:3000/users" at that time do Hard Refresh.
   **Step 5** It gives error link "No route matches [GET] "/users".
  
 Please update me ASAP.

**routes.rb**

  

 _Rails.application.routes.draw do
         devise_for :users , :controllers => { sessions: 'users/sessions', registrations: 'users/registrations' }
        get 'home/index'
        root to: "home#index"
   end_

**Comment by matheussilvasantos** [comment]
That is normal because there is no route for GET / users.
You can customize the devise controller to redirect back to / users / sign_up or create a route for GET / users.
