### ISSUE TITLE
Typo in Wiki example code

### ISSUE THREAD

**Issue by RaykPlatzek** [plataformatec/devise#4557]
In your OmniAuth: Overview Wiki example code it says:

 if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]

shouldn't this be: 

 if data == session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]

**Comment by znz** [comment]
I think it is not typo.
Did you try your code?

**Comment by RaykPlatzek** [comment]
@znz  you are right. My mistake :-)
