### ISSUE TITLE
Multiple devise routes for the same model

### ISSUE THREAD

**Issue by adityashedge** [plataformatec/devise#4560]
I need to have separate URLs for user login and business login with prefixes `/users` and `/business` respectively. There is just one model which devise should use i.e. the `User` model.

Something like this.
```ruby
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', password_expired: 'password_expired', passwords: 'passwords' } do
    get 'sign_in' => 'devise/sessions#new', :as => :new_session
    get 'sign_up' => 'devise/registrations#new', as => :new_registration
  end

  namespace :business do
    devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', password_expired: 'password_expired', passwords: 'passwords' } do
      get 'sign_in' => 'devise/sessions#new', :as => :new_session
      get 'sign_up' => 'devise/registrations#new', as => :new_registration
    end
  end
```

How can this be done with devise? I am facing the following issues.
1) Sign Up i.e `Devise::RegistrationsController` uses `respond_with resource` which ends up changing the URL to `/users` in the `create` action when saving the `User` fails.
2) `Devise.sign_out_all_scopes = true` doesn't log out the user from all the scopes.
3) Multiple `Devise.mappings.keys`(`=> [:user, :business_user]`) creates issues with sign in and sign out such as failed sign in, even with correct credentials.

Can someone help me out please and correct me if I'm going wrong somewhere?
Thank you in advance.

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
