### ISSUE TITLE
Devise shows different errors in paranoid mode when email exists and not exists

### ISSUE THREAD

**Issue by printercu** [plataformatec/devise#4568]
Hi!

When email exist and wrong password is given, it shows `devise.failure.invalid` error. But when email is not registered, it shows `devise.failure.not_found_in_database `.

Should this be fixed?

**Comment by tegon** [comment]
Hi @printercu, thanks for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
