### ISSUE TITLE
Confirmable with Mongoid sending multiple confirmation emails

### ISSUE THREAD

**Issue by Hitabis** [plataformatec/devise#4571]
While using [mongoid](https://github.com/mongodb/mongoid) in conjunction with devise's _confirmable_ module I am receiving the confirmation instructions email every time I save my user object.
The confirmation link in all emails is identical and is being sent even after I have confirmed the user's email address.

**Environment**
Rails        5.1.1
Devise    4.3.0
Mongoid 6.2.0

**Comment by pnock** [comment]
Take a look at https://github.com/plataformatec/devise/pull/4159 and https://github.com/plataformatec/devise/pull/4160. This may be a duplicate of those.

**Comment by tegon** [comment]
@Hitabis Can you confirm if your issue is the same as the mentioned above?
Are you using the gem `mongoid-paperclip` in your project too?

**Comment by Hitabis** [comment]
@tegon yes we are using `mongoid-paperclip`.

**Comment by tegon** [comment]
Ok, thank you!
I'm closing this in favor of #4160.
