### ISSUE TITLE
Custom logic in controllers on error

### ISSUE THREAD

**Issue by LeoAdamek** [plataformatec/devise#4572]
I've implemented some custom logic in my registrations controller to add some associated records when the user is created.

My devise class is `User` and the associated record type is `Account` , `User` `belongs_to :account`

In `RegistraitonsController#new` I have:

````ruby
def new
  super do |resource|
    resource.account = Account.new
  end
end
````

In `RegistrationsController#create` I have some tracking code so sign-ups can be measured

````ruby
def create
  super do |resource|
    add_tracking_data_for_signup
  end
end
````

However, this code is what gets called on a successful record creation, if there is an error inside of `super`, then devise tries to render the `users/registrations/new` view, however because `resource.account` now does not exist, this view fails to render.

How can I ensure that on error in `#create` `resource.account` is re-initialized properly?

**Comment by LeoAdamek** [comment]
Anyone able to help me out on this one?

**Comment by vaibhavmdhoke** [comment]
```
class RegistrationsController < Devise::RegistrationsController
 def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    resource.reload if resource.persisted?
    if resource.persisted?
      // after save logic   
    else   
      // error logic
    end 
end  
 
```

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
