### ISSUE TITLE
The email validations (uniqueness and regexp) is not working with client_side_validations

### ISSUE THREAD

**Issue by salmagomaa** [plataformatec/devise#4574]
Version of Devise: 4.3.0
Version of ClientSideValidations: 9.3.3
Version of Rails: 5.1.1
User model:
```
class User < ApplicationRecord

include DeviseAsync

devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable, :confirmable

end
```
The template form code:
```
<%= form_for(resource, as: resource_name,
url: registration_path(resource_name),
turboboost: true,
validate: true,
html: {id: "register-form-id"}) do |f| %>

<%= f.email_field :email, class: "form-control", validate: true %>

<% end %>

```

Result:
On blurring the email's input field, an error only shown if it is empty but if it already existed or if it has invalid format, no error is shown. I need the client_side_validations to be shown for all cases of the email errors, any help please??

**Comment by tegon** [comment]
I'm closing this because it seems like it was fixed in the `client_side_validations`. Please reopen if necessary.

Thanks
