### ISSUE TITLE
Overriding value of params in SessionsController

### ISSUE THREAD

**Issue by ChunAllen** [plataformatec/devise#4575]
Hi I would like to modify the value of the password params on my controller. Currently here's my controller:
```
class Api::V1::SessionsController < Devise::SessionsController

   before_action :override_password, on: :create

   private

   def override_password
      params[:user][:password]  = "the value I want"
   end

end
```

but when I log in I'm still getting the value that I'm receiving from the URL (API request)
Can anyone tell me how to override an attribute in params

**Comment by ChunAllen** [comment]
I already overridden the params using this 
`request.params[:user][:password] = "The value I want"`

I believe Devise doesn't allow to directly manipulate the password thru params without the request method

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only
