### ISSUE TITLE
User controller

### ISSUE THREAD

**Issue by BryanSingh** [plataformatec/devise#4578]
When I create the devise controllers, I have 

> app/controllers/users/registrations_controller.rb

 and with the class header

> class Users::RegistrationsController < Devise::RegistrationsController

I have also tried with

> class RegistrationsController < Devise::RegistrationsController

 but I keep getting the error

> ActionController::RoutingError at /users/sign_up : uninitialized constant RegistrationsController

**Comment by pavankoushik22** [comment]
I think you have problem with routing file
once go to routes.rb and check whether your routes for devise updated or not 
it should be like  " `devise_for :users, :controllers => { :registrations => 'users/registrations' }` " instead of 
"`devise_for `:users`"

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only
