### ISSUE TITLE
Send confirmation instructions on other email.

### ISSUE THREAD

**Issue by asnad** [plataformatec/devise#4579]
I have two email fields in my model "email" and "representative_email" I want to send confirmation instructions email on "representative_email" (if present or not nil) rather than "email" how can I do it efficiently. Note I'm not using devise_multi_email gem and I will be able to sign in with "email" field.

**Comment by ahmad19** [comment]
This platform is only for the issues or bugs found in the devise gem. [Stackoverflow](http://stackoverflow.com/) would be a better place for your question to be answered.

**Comment by asnad** [comment]
I was able to do this and answered to my own answer  [here](https://stackoverflow.com/questions/44898156/confirmation-instruction-on-other-email-with-devisel)
