### ISSUE TITLE
Rails 5.1 vs sendgrid

### ISSUE THREAD

**Issue by maxgronlund** [plataformatec/devise#4581]
I'm deploying on Heroku
I have configured email and it works for my rails app but not for devise.
The project is available on github https://github.com/maxgronlund/samso
In the config/initializers/devise.rb I have tried to configure Devise to use 'ApplicationMailer'  without any luck
```
config.parent_mailer = 'ApplicationMailer'
```

In the config/initializers I have also tried to configure Devise to use 'ActionMailer::Base' without any luck
```
config.parent_mailer = 'ActionMailer::Base'
````
The response from the server is 'Completed 401 Unauthorized '

Notice! The problem is only for devise, not for other emails

**Comment by tegon** [comment]
Hi @maxgronlund, thanks for your report.
If you're getting a 401, please check your mailer configuration.

We ask that you use StackOverflow for questions/help in the future. There a wider community will be able to help you. 

We reserve the issues tracker for issues only. Thank you!
