### ISSUE TITLE
Multiple Devise Model Sign Out Issue

### ISSUE THREAD

**Issue by crispincornett** [plataformatec/devise#4582]
When following the Wiki article on How To Setup Multiple Devise User Models, found here:
[How to Setup Multiple Devise User Models](https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models)

Upon implementing the Accessible concern that is described in Step 6 and including it in the user/sessions and admin/sessions controllers, I am no longer able to log out of either the User or the Admin scope, but get redirected to whichever path is defined in the `check_user` function.

I've changed the Accessible before_action to exclude the destroy action, like so:

```ruby
included do
  before_action :check_user, except: [:destroy]
end
```

Is there a better way to handle this issue?  Or maybe I did something wrong in my original implementation?

Regardless, the wiki article should be updated to address this issue.

This is using Rails 5.1.2 and Devise 4.3.0.

**Comment by tegon** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
