### ISSUE TITLE
"NoMethodError in Devise::SessionsController#create" when using customised ldap_authenticatable for the user model

### ISSUE THREAD

**Issue by jeffreyyong** [plataformatec/devise#4587]
I am using my own `devise :ldap_authenticatable` in the User model. During the login process, it all works fine when I put in the correct credentials.

However, I get "NoMethodError in Devise::SessionsController#create" when the wrong credentials are entered. I am wondering why the create method of the SessionsController can't be found when wrong credentials are inputted?

**Comment by tegon** [comment]
Hello @jeffreyyong, please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
