### ISSUE TITLE
undefined method `failure_app' for nil:NilClass

### ISSUE THREAD

**Issue by avatarr** [plataformatec/devise#4593]
Hi, Thank for great gem I like it 

Let me explain about my problem. I created custom controller login follow this [link](https://github.com/plataformatec/devise#configuring-controllers), every think woking fine

I implemented custom login logic by read many tutorials on the internet then I finish by 

```ruby
  def create
    user = User.find_by(email: params[:api_v1_user][:email])
    return invalid_login_attempt unless user

    if user.valid_password?(params[:api_v1_user][:password])
      auth_token = user.generate_auth_token
      sign_in(:user, user)
      render :json=> {:success=>true, :auth_token=>user.token}
      return
    end

    invalid_login_attempt
  end
```

A problem occurred  when `sign_in(:user, user)` executed and I got `undefined method 'failure_app' for nil:NilClass`. I'm not sure I missed config something, Any suggestion? 

Information: 
Rails 5.0.4
devise (4.3.0, 4.2.0)

Thank you

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by dongtong** [comment]
@tegon Please do not close this issue individually. If you can not resolve it, please open it.
