### ISSUE TITLE
Devise 4.3.0 does not work install on Rails 5.1.2

### ISSUE THREAD

**Issue by BimaPanduW** [plataformatec/devise#4594]
I've tried to perform
`rails generate devise:install`
but i got this 
```
Running via Spring preloader in process 5177
Could not find generator 'devise:install'. Maybe you meant 'assets', 'generator' or 'coffee:assets'
Run `rails generate --help` for more options.
```
any way to solve this problem?

**Comment by rafaelfranca** [comment]
please try to run `spring stop` after adding devise to your Gemfile

**Comment by BimaPanduW** [comment]
this problem was solved. I forgot to add `gem 'device'` in gemfile

**Comment by arun2github** [comment]
I am getting this issue please help
$ rails g device:install
/usr/local/lib/ruby/2.7.0/x86_64-linux/stringio.so: warning: already initialized constant StringIO::VERSION
Running via Spring preloader in process 6989
Could not find generator 'device:install'. 
Run `rails generate --help` for more options.
.....
i tried spring stop but didnot work.
