### ISSUE TITLE
`signed_in?` is not supposed to run auth hooks, but does

### ISSUE THREAD

**Issue by machty** [plataformatec/devise#4599]
I'm encountering an issue in my test suite where I can't run `admin_user_signed_in?` or `signed_in?(:admin_user)` without it running warden authentication hooks that are messing some things up.

I believe the problem is that Devise is calling `warden.authenticate?` when it _should_ be calling `warden.authenticated?`. See this Warden documentation [here](https://github.com/hassox/warden/blob/fa24dcbf34022d85dce8db51dd11bbbe5a6fddcc/lib/warden/proxy.rb#L109-L118) for the difference between these methods, which I believe confirms my hunch.

**Comment by tegon** [comment]
Hello @machty, thank you for the report.
What's your use case for this?
Can you provide us a sample of the test you're writing?

**Comment by machty** [comment]
It's been a long time I've lost some of the context; I really wish I'd been more descriptive in the original issue.

Basically, you want to check if a user is signed in without running authentication hooks. I don't remember why running the authentication hooks was a problem, but I believe it was causing exceptions to be raised and redirects to happen when all I wanted to do was provide additional data in a JSON response _if_ a certain user type was present.

One thing I left out in this description is [this code](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/controllers/sign_in_out.rb#L6) which explicitly mentions that it "Does not run authentication hooks." but unfortunately its implementation calls [`warden.authenticate?`](https://github.com/hassox/warden/blob/fa24dcbf34022d85dce8db51dd11bbbe5a6fddcc/lib/warden/proxy.rb#L109-L118) which according to the docs explicitly _does_ run authentication hooks.

My hunch is that a lot of people are probably (and accidentally?) relying on the current behavior of running auth hooks that maybe it's too late to change, in which case 1) the docs should probably be fixed and 2) some Devise API should be provided to check if a user is present without running the hooks.

**Comment by tegon** [comment]
I see. Your comments make sense.
I think that for now, we can change the docs on the code, but we have to think more carefully about adding a new API.
@machty are you willing to send us a pull request for this change?

**Comment by machty** [comment]
PR: #4733

**Comment by tegon** [comment]
Closed via #4733
