### ISSUE TITLE
Unable to Register Users on beginners tutorial web app

### ISSUE THREAD

**Issue by awoo100-zh** [plataformatec/devise#4601]
I am new to Ruby on Rails and trying the devise authentication gem using the [tutorial](http://12devs.co.uk/articles/writing-a-web-application-with-ruby-on-rails/). I have successfully set up all of the components and just having a problem to register my user.

I am having an issue where I am unable to add a user through my newly created website and directly through rails console. When I attempting to register a User using the default interface on the website I get an error message "User doesn't exist", and the user is not created. The same thing occurs when using the rails console User.create() command (it executes a "Select 1 from User where email_address='xx@xx.com' [[LIMIT=1]]" then rolls back the create function when it can't find it).

I've tried manually adding the row in the database and it works with no issues, however the Register command still fails.

I've tried dropping the database and recreating it using rails db:migrate. 

I did a search for the text "User Must Exist" (the error message I'm getting in the WFE) and I cannot find it anywhere on my system nor Github, so I have no idea how the error message is generated (I've looked in the locales/*.yml files), and in fact through the rest of my PC. 

I thought it would be an error with the routing (for some reason routing to User#login rather than User#register), however after attempting to register using the same e-mail that was created manually in the database, I now get two errors 1. That e-mail address is already taken, 2. The User must exist... 

Perhaps there is some exception handling that is assuming that my exception is related to "User Must Exist", masking the actual exception that is occurring.

Any help would be greatly appreciated.

Environment:
rbenv v2.4.1
bundler v1.15.3
rails v5.1.2
Sqllite3 v3.16.0

**Comment by awoo100-zh** [comment]
Okay, I figured out the problem. It was a Foreign Key Issue. I had intended to add a relationship to say that the User should have 0 or more Bookmarks stored in the database using the following code:

`has_many :bookmarks
belongs_to :user`

By default, it assumes the relationship is a 1-to-many relationship, and when you try to create a user using the Ruby Model, without adding any bookmarks, it throws an error (that really isn't that helpful). To make the model work correctly you need to change:

`belongs_to: user` to `belongs_to :user, optional: true`

So it turns out that this is a super simple fix. I did think about this being the issue earlier, but thought it would be pretty dumb to assume all foreign key constraints/relationships have to be non-empty by default.

Should I close the issue, or perhaps we could improve the error messages to help developers? Or could we make the `optional:` setting default to `true`. Keen to get your thoughts on the best course of action, and also happy to contribute!

**Comment by tegon** [comment]
Hi @awoo100-zh, glad you found the solution.
This is indeed the default behavior in Rails 5, so you have to manually add this `optional` to your models. The error messages are also coming from Rails, so there's not much we can do.
In the future, if you have some questions or need help, we ask that you please use StackOverflow. 
There a wider community will be able to help you.

Thank you!
