### ISSUE TITLE
is there a way to keep devise sessions with multiple databases? (multitennant)

### ISSUE THREAD

**Issue by jordanlance** [plataformatec/devise#4602]
_Currently we have a multitennant application that runs multiple databases.
The problem is we have different user roles for each database for example:_

Organisations => organisation_development
Teacher => teacher_development

When logging in simultanious on different browsers with devise it breaks and looses the current_organisation since we have switched to another database this seems logic. 
But im not have been able to work around or resolve this issue.
Could anyone please share a solution on how to resolve this?

```
PG::UndefinedTable: ERROR: relation "organisations" does not exist LINE 1: SELECT "organisations".* FROM "organisations" WHERE "organi... ^ : SELECT "organisations".* FROM "organisations" WHERE "organisations"."id" = $1 ORDER BY "organisations"."id" ASC LIMIT $2
```

current_organisation.class.name.downcase
becomes to **no longer exists** because it tries to load the organisations table that is no longer there since we are on a complete different database now.

> Is there a way to make devise keep the current_<organisation/user/etc> values 

``` 
#<ActiveRecord::StatementInvalid: PG::UndefinedTable:
 ERROR:  relation "organisations" does not exist
```

**Comment by jordanlance** [comment]
The only possible solution I can come up with is using a single table for **all** users/organisations/teachers/whatever.  1 single database that is getting connected to for each devise model.

I have spend **some days** investigating this issue hope someone from the Devise team can share some thougts on a possible solution.

**Comment by jordanlance** [comment]
Nobody any thoughts on this?

How about a custom warden authentication that stores the user session data in a seperate table, then using a UserAuth rails model for authorization in Devise and use a reguler User model for getting the related data from the user like user_profile.  UserAuth model would only use the email and password + devise columns

Would above be a solution that would work?

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
