### ISSUE TITLE
Devise confirmable with reconfirmable is not sending first confirmation email

### ISSUE THREAD

**Issue by apellizzn** [plataformatec/devise#4611]
I am using devise confirmable with reconfirmable option enabled.
When i create the user for the first time `reconfirmable` is copying the `email` value to `unconfirmed_email` and setting `email` to `nil`.

After the user creation the following hook is called https://github.com/plataformatec/devise/blob/71fc5b351a8e8473733b0ca29d60c06e43a0efe1/lib/devise/models/confirmable.rb#L50

But it will never send the confirmation email since its guard will always return false
```
def send_confirmation_notification?
  confirmation_required? && !@skip_confirmation_notification && self.email.present?
end
```
due to the fact that the `email` has just been copied to `unconfirmed_email`.

Am i missing something or is this an issue ?

**Comment by apellizzn** [comment]
I guess the problem was caused by an `afrer_create` which was updating my model

**Comment by codebycliff** [comment]
I ran into this and it was in fact an `after_create` callback that was the issue for me. Just thought I'd mention it for any future readers.
