### ISSUE TITLE
RegistrationsController#edit does not respect Accept type

### ISSUE THREAD

**Issue by timscott** [plataformatec/devise#4615]
[RegistrationsController#edit](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L38) renders a view without respect to the Accept type. Unless I'm missing something, it should be:

```ruby
def edit
  respond_with resource
end
```

With this change, it will serve JSON when requested, which is useful in the case of using Devise in an API, for example.

If correct, I'm happy to make a PR.

**Comment by tegon** [comment]
Looks like this change is ok, but I don't know if I missing something 🤔 
@rafaelfranca @feliperenan WDYT?

**Comment by feliperenan** [comment]
I think is ok too. 

PS: We already use `respond_with resource` in the new action.

https://github.com/plataformatec/devise/blob/451ba5362b84ff18a31ea1b3251137128a6b1beb/app/controllers/devise/registrations_controller.rb#L10

**Comment by rafaelfranca** [comment]
`edit` actions usually doesn't make sense in API requests. It is a navigational action, to render a form to edit the user.

In APIs you should be accessing the `show` action to get the user response and making the request to the `update` action.

That said I think the registration controller should either keep its actual behavior or respond with a 406 when asked for anything that is not a HTML.

**Comment by tegon** [comment]
Makes sense, the current behavior stays the same and I'm going to close this issue.
Thanks!

**Comment by carlosantoniodasilva** [comment]
Just happened to hit this randomly.... We should 406 on that action for non-HTML responses, rather than 500, much like the other actions would.
