### ISSUE TITLE
restrict users to logging in from certain IP address (possibly a range of IP addresses)

### ISSUE THREAD

**Issue by ssnyder** [plataformatec/devise#4620]
I may have a requirement that certain users log in from a certain range of IP addresses in addition to the password requirement that we already have.  

I have not been able to find a reasonable way to do this from looking at the Wiki (I'm a non-Ruby dev who inherited a existing Ruby project to maintain and develop - while learning Ruby :) ).  I am still using Rails 3/Devise 2.2.8 (and cancan) if that matters.  I'm also in the process of preparing to update from Rails 3 to Rails 4, so I am starting the process of updating all of the misc. gems as well if that makes a difference.

Any help/pointers would be appreciated.

Thanks,
Sharon

**Comment by tibomogul** [comment]
You can override the create action of sessions controller (this would be documented in the wiki or readme), call super and perform the checking of your IP white list there.

**Comment by ssnyder** [comment]
Thanks - I'll give that a shot!
