### ISSUE TITLE
Weird things happen when user asks for reset-password before he confirmed.

### ISSUE THREAD

**Issue by nadavb** [plataformatec/devise#4625]
When user asks for a password reset before he confirmed the email address, what happens is that he gets to the pick-a-password screen, and in this screen for some reason the passwords-match enforcement does not occur. He can choose two different password, without appropriate error messages.

In addition, I think it would be wise to block users from being able to reset-password before they confirm, and if they try to send them the confirmation email instead.

**Comment by rietta** [comment]
Does the password get set?

**Comment by nadavb** [comment]
Don't know, it needs to be checked.

**Comment by cross-p6** [comment]
I can't speak to the password match not being enforced, but I do not believe that confirmation is a requirement of password resets. Confirmable is an opt-in module.

**Comment by tegon** [comment]
@nadavb Can you provide a test case for this?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
