### ISSUE TITLE
undefined local variable or method `flash' for Devise::OmniauthCallbacksController when use devise with Rails 5 + api

### ISSUE THREAD

**Issue by dungho-agilityio** [plataformatec/devise#4626]
I am building a Rails-API using Omniauth-gitlab and Devise. However when logging in with gitlab I am presented with the error:
undefined local variable or method `flash' for Devise::OmniauthCallbacksController line 9

**Comment by dhilt** [comment]
@dungho-agilityio Possibly this relates to https://github.com/plataformatec/devise/issues/4275... there are some workarounds.

**Comment by tegon** [comment]
Hello @dungho-agilityio, thanks for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
