### ISSUE TITLE
conditional :validatable option?

### ISSUE THREAD

**Issue by ojsdude** [plataformatec/devise#4629]
I have added devise to a site that I am working on that has quite a lot of different forms for users.
The problem that I have is that the `:validatable` option is being a bit aggressive and running on any form across the sites, meaning that on a form that I am asking a user for their email it will complain about the email already being taken. I would like to know if there is a nice way to run the devise validation ONLY for the devise forms? The only solution I can find (that I am about to try now) is to run the validation manually and add checks to only run it on devise forms (https://stackoverflow.com/a/24678462). I think it would be nice if there was a way to be able to specify which pages/forms this `uniqueness` check is run. I have looked on StackOverflow for a better answer, but the one I have linked to seems the best at the moment. Please tell me if I am wrong and this is already available, but I personally think that it would be a good ability to have.
Thanks in advance!

**Comment by tegon** [comment]
Hello @ojsdude, thanks for your suggestion.
It looks like you have a very specific use case here. In this case, I think it's better to follow the approach of the SO question you sent above and remove the `validatable` module from your model.
That way you can have more control of when and which validations you need to run.

Thanks!
