### ISSUE TITLE
Devise confirmable automatically sends out email on user update

### ISSUE THREAD

**Issue by trandoanhung1991** [plataformatec/devise#4631]
We just finished an ETL of old data to our brand new web app. I went to mass update a non-devise field in my User model and to my horror, confirmable start sending out emails. Worse, they're from our staging server.

What may be triggering this problem?

EDIT: It seems like for some reason some of the users are being flagged as requiring reconfirmation. What are the criteria for this?

**Comment by vaibhavmdhoke** [comment]
Can you share what are the fields that are updated & the version of the gem you are using?

**Comment by trandoanhung1991** [comment]
We migrated over email, encrypted_password is empty due cause we want to force users to reset password anyway, created_at and updated_at.

**Comment by tegon** [comment]
@trandoanhung1991 If you are using the `reconfirmable` option, this is the default behavior when the email changes.
One alternative is to update your records using methods that skip the callbacks, like `update_attribute` or `update_columns`, for example.
