### ISSUE TITLE
How to move from encryptor: bcrypt to encryptor: authlogic_sha512 ?

### ISSUE THREAD

**Issue by farhad-tarapore** [plataformatec/devise#4632]
I tried changing devise.rb to use authlogic_sha512. Added a method in my SessionsController class which validates existing bcrypt password, changes it to sha512 and puts it back in the 'encrypted_password' field in the Users table in DB.

However, if I sign out and sign in again, I get an error 
`BCrypt::Errors::InvalidHash: invalid hash`

Even on rails console, 

`> u.valid_password?('123456')`
`BCrypt::Errors::InvalidHash: invalid hash`

And

`> u.password_digest`
`NoMethodError: protected method `password_digest' called for #<User:0x007ff17dfcef38>`

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
