### ISSUE TITLE
Add `autocomplete="email"` to email fields

### ISSUE THREAD

**Issue by MikeRogers0** [plataformatec/devise#4635]
I'd really like to add [autocomplete="email"](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill#email) to fields where we've requested users emails such as:
 - [confirmations/new.html.erb](https://github.com/plataformatec/devise/blob/master/app/views/devise/confirmations/new.html.erb#L8)
 - [registrations/new.html.erb](https://github.com/plataformatec/devise/blob/master/app/views/devise/registrations/new.html.erb#L8)
 - [sessions/new.html.erb](https://github.com/plataformatec/devise/blob/master/app/views/devise/sessions/new.html.erb#L6)
 - [unlocks/new.html.erb](https://github.com/plataformatec/devise/blob/master/app/views/devise/unlocks/new.html.erb#L8)
 - [passwords/new.html.erb](https://github.com/plataformatec/devise/blob/master/app/views/devise/passwords/new.html.erb#L8)

This will autofill the email fields with an email address saved to the browser, but also encourage developers to look into other autofill options. What do you think? (If you like it, I'm happy to PR :) )

**Comment by rafaelfranca** [comment]
Please open the PR. Closing since this is a feature request. Thanks
