### ISSUE TITLE
Rails routing using devise and subdomain constraint

### ISSUE THREAD

**Issue by pradyumna2905** [plataformatec/devise#4637]
Looked at 5 Google search pages before asking it here. Excuse me if this is a repeated Q.

I am trying to route root to devise sign in path under a `subdomain` constraint.
My `config/routes.rb` look something like this

```
Rails.application.routes.draw 
  constraints subdomain: 'admin' do
    devise_scope :admin do
      root to: 'devise/sessions#new'

      # here I override devise routes
    end
  end

  root to: 'pages#homepage'

  # rest of the routes  
end
```

I am getting the error `Could not find devise mapping for path "/".`

Any suggestions as to how I route to root path in a subdomain with devise scope?

Thanks

**Comment by richhollis** [comment]
I have the same problem - if I remove the constraint then it works.

**Comment by tegon** [comment]
Hi @pradyumna2905, thank you for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by richhollis** [comment]
Hi @tegon - is Rails 3.2 still supported by Devise? I've checked and the issue I had was with a 3.2 app (3-2-stable). If it is then I can try and reproduce the issue. Thanks.

**Comment by tegon** [comment]
@richhollis only for security issues. This doesn't happen on the latest version?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
