### ISSUE TITLE
No route matches [GET] "/models/sign_out"

### ISSUE THREAD

**Issue by mittalyashu** [plataformatec/devise#4638]
Getting this error.

![image](https://user-images.githubusercontent.com/29014463/30266450-0c5d79f4-96fd-11e7-9627-7c869205b460.png)

Even I have tried this in routes

````
devise_for :models do
     get '/models/sign_out' => 'devise/sessions#destroy'
end
```

*(I know, this is not the right place to post this type of issue. But I have searched every where and tried every method, found on the internet.)*

**Comment by Arslan-Ali-Butt** [comment]
It's the issue with the type of the request - URL is fine.

In the routes show on your screenshot, the HTTP verb to be used is `DELETE`, while you are using `GET` HTTP verb to sign out a user.

**Comment by mittalyashu** [comment]
I have tried using `DELETE` also, but it didn't work.

![image](https://user-images.githubusercontent.com/29014463/30314748-595f3f2c-97bf-11e7-8fe8-a498879dcd16.png)

**Comment by Arslan-Ali-Butt** [comment]
No, you don't need to write `delete` here. Show me where you are calling this link in your code, the code to sign out.

**Comment by mittalyashu** [comment]
![image](https://user-images.githubusercontent.com/29014463/30340750-3703ec5a-9811-11e7-81ca-e884ef31a430.png)

**Comment by toddsiegel** [comment]
That _should_ be a template error since you have `:method: :delete` in the `link_to`. You want `method: :delete`.

Remove the `delete` from your routes.rb. `devise_for :models` should be enough. Also verify that `$ rake routes` has the route
```
destroy_model_session DELETE /models/sign_out(.:format)                       devise/sessions#destroy`
```

**Comment by rafaelfranca** [comment]
All the information provided should help you to fix the issue. If it doesn't please create an example application reproducing the bug

**Comment by mittalyashu** [comment]
I have followed as @toddsiegel mentioned. But still on the same problem.

Create a [repo](https://github.com/mittalyashu/integrating-devise) for the same.

**Comment by rafaelfranca** [comment]
Ah. Just saw the problem. You need to make sure the application.js is included in your page otherwise the rails-ujs JavaScript framework will not be included and Rails will not be able to make the request using the DELETE method.

**Comment by mittalyashu** [comment]
Thanks. That's work for me.
