### ISSUE TITLE
Can't find translation key for 'Sign out' or 'Log out' ?

### ISSUE THREAD

**Issue by viktorsmari** [plataformatec/devise#4639]
I want to have a 'Log out' or 'Sign out' button, but I cannot find the translation key for it.

Does it not exist?

Should it not exist here under sessions: 
https://github.com/tigrish/devise-i18n/blob/master/rails/locales/en.yml#L106

**Comment by luchillo17** [comment]
What happened to this? still can't find the `Log out` translation or equivalent.

**Comment by viktorsmari** [comment]
I don't remember why I closed the issue, I'll reopen.

It's weird that 'Sign out' is not supported, but 'Signed out successfully' is supported :thinking: 

https://github.com/heartcombo/devise/blob/c82e4cf47b02002b2fd7ca31d441cf1043fc634c/config/locales/en.yml#L50

**Comment by viktorsmari** [comment]
I thought so too.

I personally think it should be added, because then the community at `tigrish/devise-i18n` could provide translations for it in **multiple** languages.

I have had to provide these strings manually in multiple projects, and it would save a lot of time if it was provided.
I know we can say this about many translation strings, but these 2 are essential :nerd_face:

**Comment by luchillo17** [comment]
I agree too, these 2 come hand in hand, as soon as we use Devise, we're bound to use Logout somewhere.

**Comment by carlosantoniodasilva** [comment]
Just to make sure I understand what you are discussing here: that Devise does not provide a link to sign out anywhere? Or is it just about the translation key?

**Comment by viktorsmari** [comment]
We are mainly missing the `sign_out` key, which would be super useful to have (most apps need one :nerd_face: )

And we guessed that the reason **why** it's not in this repo, is that it's not used anywhere in the scaffolds that Devise provides.
I personally don't care that Devise does not provide the link in the scaffolds, I usually add it myself in the header dropdown.

**Comment by luchillo17** [comment]
@carlosantoniodasilva Yes that's exactly it, Devise does provide the URL/route to `log_out`, but the scaffold views don't make use of it, the developer has to make use of it on its application views (with a link and a translation to match in a header or a side menu in a drawer), and that translation it's so widely used than providing it in the Devise I18n along with the sign_in one would help >= 90% of those that implement Devise with I18n.
