### ISSUE TITLE
Confirmations not sending email

### ISSUE THREAD

**Issue by coderubyonrails** [plataformatec/devise#4640]
I have ':confirmations' module enabled in User model and all the necessary column migration done. When I register new user from registration new page, confirmation email is not sent but when I do "didn't receive confirmation instructions" and request confirmation link from confirmation new page, I get confirmation link email. I'm using "postmark-rails gem" for mail service in my app. and devise version is 4.3.0. I tried switching and trying in all environments but no receiving confirmation link in new user create/registration but get link in confirmations/create.

**Comment by vaibhavmdhoke** [comment]
@coderubyonrails Can you share your User model, development.rb devise.rb & devise migration for the same?

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
