### ISSUE TITLE
undefined method `users_url' for #<Devise::RegistrationsController:0x007f8b8aba2670> Did you mean? user_session_url

### ISSUE THREAD

**Issue by twyststar** [plataformatec/devise#4642]
**undefined method `users_url' for #<Devise::RegistrationsController:0x007f8b8aba2670> Did you mean? user_session_url**

I am getting this error when I try to sign up a new user. This is a project I have not touched in a month, but (I know how silly this sounds!) it was working as far as I knew on my last commit.  

This is the code it shows: 

if options.empty?
              recipient.send(method, *args)
            else
              recipient.send(method, *args, options)
            end

-which I can't locate in my files. 

Here is the full stack trace: 

actionpack (5.1.2) lib/action_dispatch/routing/polymorphic_routes.rb:230:in `polymorphic_method'
actionpack (5.1.2) lib/action_dispatch/routing/polymorphic_routes.rb:114:in `polymorphic_url'
actionpack (5.1.2) lib/action_dispatch/routing/url_for.rb:184:in `full_url_for'
actionpack (5.1.2) lib/action_dispatch/routing/url_for.rb:167:in `url_for'
actionpack (5.1.2) lib/action_controller/metal/redirecting.rb:105:in `_compute_redirect_to_location'
actionpack (5.1.2) lib/action_controller/metal/redirecting.rb:61:in `redirect_to'
actionpack (5.1.2) lib/action_controller/metal/flash.rb:57:in `redirect_to'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:64:in `block in redirect_to'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:63:in `redirect_to'
responders (2.4.0) lib/action_controller/responder.rb:145:in `redirect_to'
responders (2.4.0) lib/action_controller/responder.rb:205:in `navigation_behavior'
responders (2.4.0) lib/action_controller/responder.rb:172:in `rescue in to_html'
responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
devise (4.3.0) app/controllers/devise/registrations_controller.rb:32:in `create'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
/usr/local/lib/ruby/gems/2.4.0/bundler/gems/remotipart-cd653ddc43bb/lib/remotipart/middleware.rb:32:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"AZUYUhbrhRo6DesPeqAmJZld5pZA2E5H8X6+q3N4cAM8CuLwFwVaf1Fnpo2GCBybZLNv37zSpztsFRGzWFyfWw==",
 "user"=>{"email"=>"bob@bob.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"},
 "commit"=>"Sign up"}
Toggle session dump
Toggle env dump
Response

Headers:

None
x
>>   

Please let me know what other info you need. 

Thanks

**Comment by twyststar** [comment]
Problem solved. I had it set up to create a profile upon user creation, and a uniqueness validator was failing in the profile creation.

**Comment by AlvaroSN** [comment]
And how do you fix that?

**Comment by achin07** [comment]
How'd you fix it? Could tell it briefly? I am stuck and also got a deadline!

**Comment by mvpxtech** [comment]
What is the solution on the current devise + rails 7?

**Comment by rakadon1** [comment]
> How'd you fix it? Could tell it briefly? I am stuck and also got a deadline!

did you solve this issue?

**Comment by 0jonjo** [comment]
> What is the solution on the current devise + rails 7?

I found the answer here: https://stackoverflow.com/questions/71352499/attempting-to-register-a-user-on-my-devise-app-causes-undefined-method-user-url
