### ISSUE TITLE
Circular 'accepts_nested_attributes_for' between User and other model sends out duplicate emails

### ISSUE THREAD

**Issue by saurabhlodha** [plataformatec/devise#4644]
I am using `devise 4.3.0` for authentication and use `User` as the devise model. I have another model `Employee` which `has_one User`. I use the `EmployeesController` to update it's user records.

Employee

    class Employee < ApplicationRecord
      has_one :user, inverse_of: :employee, dependent: :nullify
      accepts_nested_attributes_for :user
    end

 User

    class User < ApplicationRecord
      devise :database_authenticatable, :confirmable, :lockable,
        :recoverable, :rememberable, :trackable, :validatable

      belongs_to :employee, optional: true, inverse_of: :user, dependent: :destroy
      accepts_nested_attributes_for :employee
    end

I have enabled change email notification in devise `config.send_email_changed_notification = true`. When I am updating the user email, I am receiving duplicate `Email Changed` notification. This issue arrises from the fact that both the models have `accepts_nested_attributes_for` for the other.

**Comment by vaibhavmdhoke** [comment]
@saurabhlodha  I don't think this is due to accepted_nested_attribites, I have checked the with & without adding accepts_nested_attributes_for . Two mail triggering is the default functionality of Devise in confirmable module, you can have a closer look into the  [send_email_change_notification](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L306)

**Comment by tegon** [comment]
Hello @saurabhlodha, thanks for your report.
I tested here and only one email was sent, as expected.
Are you overriding Devise controllers? 
Are you using Mongoid?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
