### ISSUE TITLE
Schould :recoverable unlock :lockable ? 

### ISSUE THREAD

**Issue by philister** [plataformatec/devise#4646]
Hi.
When using :lockable and :recoverable, and a user gets locked because of too many attempts. Should he get unlocked when resetting his password via recoverable?

Thank and regards, Phil

**Comment by cross-p6** [comment]
I really see this as a domain-level decision. More secure systems may want locked accounts to need admin intervention.

The hooks are there to do this yourself.

**Comment by rafaelfranca** [comment]
Agree with @cross-p6. Thank you for the issue
