### ISSUE TITLE
Ajax - Signin Not working

### ISSUE THREAD

**Issue by gameroster-us** [plataformatec/devise#4652]
Started POST "/users/sign_in" for 127.0.0.1 at 2017-09-26 17:25:15 +0530
Processing by User::SessionsController#create as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Fozvt4xIkxj+IuOZg56YU6/LBHGuAbjVbjE+xN8CcixZ+rf/mvzIT71pW2tB/6DstQ0KgYufG9e2sKKGbpBRKQ==", "user"=>{"email"=>"test@gmail.com", "password"=>"[FILTERED]"}, "button"=>""}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["email", "test@gmail.com"]]
Completed 401 Unauthorized in 4ms (ActiveRecord: 0.4ms)

I want to call create.js.erb but always ingnored

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
