### ISSUE TITLE
BUG: Unconfirmed used created with FactoryGirl is not recognized by Devise

### ISSUE THREAD

**Issue by marcosanfilippo** [plataformatec/devise#4659]
Hello, I'm working with login and user must confirm their email.

By creating User with the HTML form, Devise works and deny login for who hasn't confirmed email.
But in testing, if I create an user with `FactoryGirl` or by `rails console`, even if `user.confirmed?` is `false`, Devise recognize it as true and my test fails!

Here the example:

    @unconfirmed_user = FactoryGirl.build(:entity_user_unconfirmed)
    @unconfirmed_user.save!

While the Factory is:

    factory :entity_user_unconfirmed, class: 'Entity::User' do
        @p =  Faker::Internet.password
        email { Faker::Internet.email }
        password @p
        password_confirmation @p 
    end

And the Rspec test...

```
Auth::Mobile::Users::Sessions Sessions (sign in): unconfirmed but valid user provided
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :no_content (204)
     # ./spec/requests/auth/mobile/users/auth_mobile_users_sessions_spec.rb:50:in `block (3 levels) in <top (required)>'

Finished in 1.23 seconds (files took 2.28 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/requests/auth/mobile/users/auth_mobile_users_sessions_spec.rb:31 # Auth::Mobile::Users::Sessions Sessions (sign in): unconfirmed but valid user provided
```
The `204 - No Content` in my API set means that the session was created. **WRONG!!!**
Where's the problem? 
Thanks.

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by marcosanfilippo** [comment]
It's hard for me now. I'm very busy. I'll try otherwise I'll share all details.

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
