### ISSUE TITLE
Scoped views only work with .erb files

### ISSUE THREAD

**Issue by lsarni** [plataformatec/devise#4660]
I was using scoped views and I had transform the views using this [how to](https://github.com/plataformatec/devise/wiki/How-To:-Create-Haml-and-Slim-Views) to `.html.haml` and made some modifications on them depending on the model needs.

But when I went to the route it ignored my custom views:

```
Processing by Users::RegistrationsController#new as HTML
  Rendering C:/Ruby24/lib/ruby/gems/2.4.0/gems/devise-4.3.0/app/views/devise/registrations/new.html.erb within layouts/application
  Rendered C:/Ruby24/lib/ruby/gems/2.4.0/gems/devise-4.3.0/app/views/devise/shared/_links.html.erb (1.0ms)
  Rendered C:/Ruby24/lib/ruby/gems/2.4.0/gems/devise-4.3.0/app/views/devise/registrations/new.html.erb within layouts/application (54.6ms)
Completed 200 OK in 478ms (Views: 455.0ms | ActiveRecord: 4.0ms)

```

I couldn't find anything wrong with my implementation of multiple models.
As soon as I generated the views again with `rails generate devise:views users` getting `.html.erb` files scoped views started working again.

```
Started GET "/users/sign_up" for 127.0.0.1 at 2017-09-30 17:52:57 -0300
Processing by Users::RegistrationsController#new as HTML
  Rendering users/registrations/new.html.erb within layouts/application
  Rendered users/shared/_links.html.erb (0.5ms)
  Rendered users/registrations/new.html.erb within layouts/application (16.1ms)
Completed 200 OK in 165ms (Views: 163.2ms | ActiveRecord: 0.0ms)
```
I tried using slim instead but they were ignored too.
It would be great if it could work with haml and slim too.

**Comment by darrenterhune** [comment]
Probably a better place for this would be SOF.

Do you have haml or slim gems installed and configured when your generating your views and booting the rails app? Either of those gems would need to be installed before .haml or .slim view templates would render.
