### ISSUE TITLE
Documentation Suggestion: Getting started -  show config change that needs to made to send out emails

### ISSUE THREAD

**Issue by architapatelis** [plataformatec/devise#4664]
In the [devise documentation](http://www.rubydoc.info/github/plataformatec/devise/) under the Getting Started section, there are instructions for setting up the default URL options. And that's great, but along with that I think that there should be instructions to change the boolean value from `false` to `true` for the following Ruby code:

 in `config/environment/development.rb` file:
```ruby 
  config.action_mailer.raise_delivery_errors = false 
```

I am a student, and I when I was using the devise gem for my project, I couldn't send out confirmation emails to my users when they sign up for my app, that is until I changed the value to `true`. Judging by this [stackoverflow post](https://stackoverflow.com/questions/6993245/rails-devise-send-mail) it seems to me that others are having the same problem. I know this is a Rails side configuration, but to students or first time users this might not be obvious, they might just think it's a devise thing. In my opinion documentation for this will help.

**Comment by darrenterhune** [comment]
That config does not setup rails to send emails, please read http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration for more information.

There are a ton of ways to send emails with rails, thus I don't think changing the readme is a good suggestion. A wiki page might be a better place for that kind of thing with an example e.g. `:letter_opener`.

@rafaelfranca this could be closed I think
