### ISSUE TITLE
Use custom encryptor, not work auto sign_in after sign up

### ISSUE THREAD

**Issue by mr-koww** [plataformatec/devise#4665]
I user rails 5.1.3 && devise 4.3.0
When I use custom encryptor (phpass) 
(use this article https://github.com/plataformatec/devise/wiki/How-To:-Create-a-custom-encryptor)
and try auto sign_in in RegistrationsController not work (**method self.compare in module Encryptors not calling**). But sign_in in SessionsController work nice!

https://gist.github.com/mr-koww/769ec6bc9238eec28d087a0e60bac244

**Comment by tegon** [comment]
Hello @mr-koww, thanks for your report.
Unfortunately, I'm not sure if the Wiki article is up to date since this is maintained by the community.
So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
Thanks!
