### ISSUE TITLE
Login with Turbolinks and remote form

### ISSUE THREAD

**Issue by rience** [plataformatec/devise#4666]
I couldn't find anywhere a tutorial or some SO answer to this problem. Basically I'd like to
- have form to use `remote: true` (so it's javascript request)
- and render some JS on failure

However, when I do that - Devise session's controller responds with

```
You need to sign in or sign up before continuing.
```

And then browser tries to evaulate this as JS code.

How can I write JS for such response?

**Comment by ricardoruwer** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
