### ISSUE TITLE
Devise confirmable sends confirmation instructions even when email update fails in begin rescue block (ActiveRecord::RecordNotUnique)

### ISSUE THREAD

**Issue by donboli** [plataformatec/devise#4676]
I'm currently working with devise 4.3.0. 
I would like to prevent user.update(email: new_email) from sending the reconfirmation email, when it fails due to email uniqueness constraints. 
Whenever I **don't rescue** the ActiveRecord::RecordNotUnique exception, the behavior is as expected (it doesn't send a confirmation email). But when I **do rescue** the exception, the email somehow gets send anyways.

Here's an example code:
```
begin
  user.update(email: already_used_email) # <-- this should not send the confirmation email since it fails
rescue ActiveRecord::RecordNotUnique
   # handle exception
end
```

Is this a bug or intended? How can I achieve the desired behavior?

Thanks in advance!

**Comment by tegon** [comment]
Hi @donboli, thanks for your report.
Would you mind sends us a simple app that demonstrates the issue, or maybe add a failing test case on a pull request?
That would help us to find out what is happening.

Thank you.

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!
