### ISSUE TITLE
NoMethodError in Devise::Sessions#new

### ISSUE THREAD

**Issue by ibf321** [plataformatec/devise#4685]
mbs/app/views/devise/sessions/new.html.erb where line #21 raised:

undefined method `login' for #<User:0x00000006e2bef8>

```
`        <div class="form-group">
            <div class="input-group">
                <%= f.text_field :login, autofocus: true, placeholder: "Usuário", class: "form-control" %>
            </div>
          </div>
          <div class="form-group">`
`
```

**Comment by nashby** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
