### ISSUE TITLE
Double Quotes used in the DeviseHelper

### ISSUE THREAD

**Issue by anoobbava** [plataformatec/devise#4689]
Hi,
when I traverse through the code, it is found that in devise_helper.rb used double quotes to return. I think as per Rubocop we need to use the single quotes,  As per "rubocop prefer single-quoted strings when you don't need string interpolation", made a PR for this issue #4688

**Comment by rafaelfranca** [comment]
https://github.com/plataformatec/devise/pull/4688#issuecomment-342037373
