### ISSUE TITLE
password_reset_token is invallid, digesting the token makes it un-findable

### ISSUE THREAD

**Issue by jovanmaric** [plataformatec/devise#4695]
Both on the startup app I am working on, as a newly generated app give the same error on the ```PasswordsController#update``` action: ```reset_password_token is invalid```. The following logs are created when the render page is re-rendered because of the failure.

```
Started PUT "/gebruikers/wachtwoord" for 127.0.0.1 at 2017-11-06 22:43:40 +0100
Processing by Devise::PasswordsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Db7WVRTS/VQKKFMmLt2n/ZJKBkfFM2kO+v/5XOpA97wfLQ7D5LQtSNk/mYp7UGFHg2E616EW5TPGlkVMBEE4ZQ==", "user"=>{"reset_password_token"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Verander mijn wachtwoord", "locale"=>"nl"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["reset_password_token", "448eef3cc236e927e262911d95ca62011136e87959e5de61283bdba4e1ffcc59"], ["LIMIT", 1]]
  Rendering devise/passwords/edit.html.erb within layouts/application
  Rendered devise/shared/_error_messages.html.erb (1.0ms)
  Rendered devise/passwords/edit.html.erb within layouts/application (10.5ms)
  Rendered layouts/_navigation.html.erb (4.1ms)
  Rendered layouts/_header.html.erb (7.7ms)
  Rendered layouts/_flash.html.erb (0.9ms)
  Rendered layouts/_footer.html.erb (2.9ms)
Completed 200 OK in 160ms (Views: 140.4ms | ActiveRecord: 0.6ms)
```
When checking out the users reset_password_token in the database I got: ```fbd388b6673e1c64b40031116f1cd25ad4d19523700d2a4ca930041730a3d892```, which does not comply with the reset_password_token in the above logs. 

That made me dig around the devise gem a little bit and this made me stumble upon the following code in ```lib/devise/models/recoverable.rb```:

```
        def reset_password_by_token(attributes={})
          original_token       = attributes[:reset_password_token]
          reset_password_token = Devise.token_generator.digest(self, :reset_password_token, original_token)

          recoverable = find_or_initialize_with_error_by(:reset_password_token, reset_password_token)

          if recoverable.persisted?
            if recoverable.reset_password_period_valid?
              recoverable.reset_password(attributes[:password], attributes[:password_confirmation])
            else
              recoverable.errors.add(:reset_password_token, :expired)
            end
          end

          recoverable.reset_password_token = original_token if recoverable.reset_password_token.present?
          recoverable
        end
```
here the original token is first digested, and then used to look for the resource (in my case User) with the ```find_or_initialize_with_error_by``` method. However there does not exist any reset_password_token with the newly digested reset_password_token, and the recoverable model returns a non-persisted model, which lets the password_reset behaviour fail. However, Passing original_token into the ```find_or_initialize_with_error_by``` method does return the proper resource model. 

So I checked out how this was done in ```lib/devise/models/confirmable.rb``` under the ```confirm_by_token``` method and noticed the TODO:

```
        def confirm_by_token(confirmation_token)
          confirmable = find_first_by_auth_conditions(confirmation_token: confirmation_token)
          unless confirmable
            confirmation_digest = Devise.token_generator.digest(self, :confirmation_token, confirmation_token)
            confirmable = find_or_initialize_with_error_by(:confirmation_token, confirmation_digest)
          end

          # TODO: replace above lines with
          # confirmable = find_or_initialize_with_error_by(:confirmation_token, confirmation_token)
          # after enough time has passed that Devise clients do not use digested tokens

          confirmable.confirm if confirmable.persisted?
          confirmable
        end
```
Could the not functioning function in ```lib/devise/models/recoverable.rb``` be some kind of regression bug and are more people having this problem?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jovanmaric** [comment]
it took longer than expected: https://github.com/jovanmaric/devise_test

**Comment by christophertfoo** [comment]
I ran into the same issue when upgrading a really old app to a newer version of Devise.  The issue was in the mailer view override where they were passing `@resource.reset_password_token` as the `reset_password_token` URL parameter (the digested token) when it should have been `@token` (the non-digested token).

For example, in your sample application try changing [Line 6 of app/views/devise/mailer/reset_password_instructions.html.erb](https://github.com/jovanmaric/devise_test/blob/41d363d150062a33423ec6259ba221caf8f4d89e/app/views/devise/mailer/reset_password_instructions.html.erb#L6) to:
```ruby
<p><%= link_to t('.action'), edit_password_url(@resource, reset_password_token: @token) %></p>
```

**Comment by tegon** [comment]
Indeed, the view on the sample app looks like an old version - it was changed here: https://github.com/plataformatec/devise/commit/143794d701bcd7b8c900c5bb8a216026c3c68afc#diff-de6f63b24abbd2f34401479bd4aa1eb3.
@jovanmaric Did you generated the views using an older version of devise? Can you confirm that it works by changing the parameter as shown above?

**Comment by jovanmaric** [comment]
Yes it works, thanks @tegon, @christophertfoo and @rafaelfranca! I'm not quite sure why the old views were generated. I do remember very faintly that I used `devise-bootstrap-views` to generate the views in some project, I presume it was this one :speak_no_evil:. Anyhow thanks a lot!

**Comment by adamakhtar** [comment]
I'm having a very similar problem to jovanmaric and as the last comment was only hours ago I'm going to comment here.

I'm on Devise 3.5.10 and in my reset_password_instructions.html.erb I have a link like this

```
link_to 'Edit Password', edit_password_url(@resource, reset_password_token: @token, locale: "en")
```

This renders the following link in the delivered email:

http://localhost:3000/en/company_users/password/edit?reset_password_token=xxxxxblahblahblah

The locale part is to force the reset form to display in english (The email has instructions in both Japanese and English with associated reset links). 

In my routes I have this scope 

```
scope "(:locale)", locale: /en|ja/ do
    devise_for :company_users .... 
    ...
end
```

When the user tries to reset their password however, they get an invalid token error. After adding logging it appears devise was returning a non-persisted mode just like jovanmaric stated. 

When I remove the locale from the url password reset seems to work fine. 

Can anyone see an obvious error?
