### ISSUE TITLE
E-mail enumeration defense - discussion

### ISSUE THREAD

**Issue by rietta** [plataformatec/devise#4697]
I'm able and willing to work on this and issue a pull request on this, but wanted to discuss the idea first.

## Problem: E-mail Enumeration on Signup

Under the current design, Devise makes it possible to determine if an e-mail address is a user on the system. [Paranoid mode](https://github.com/plataformatec/devise/wiki/How-To:-Using-paranoid-mode,-avoid-user-enumeration-on-registerable) helps in many places but does not appear to keep you from being told that an e-mail is already in use on signup..

### Option 1: Multi-step Signup
In paranoid mode, break the signup process into steps. 
The user first enters the e-mail address and then is told to check his or her e-mail to follow the link. Only by following the link back from the e-mail will lead to the next step in account signup, prompting for the password, and then other information customized for the site.

This mitigates the threat because just like with the password reset, entering a valid email that is not yours only presents a notice to go check ones e-mail. The status of an e-mail being a user or not being a user is not leaked.

### Option 2: Fail Signup with Message to Check Confirmation
Let the user enter the desired e-mail and password as now, but do not show any error messages about the e-mail being taken or not. Upon submission, tell the user to simply go check his or her e-mail for confirmation.  The same message is shown if the new account is added or if that e-mail already exists and the submission was a no-op.

**Comment by tegon** [comment]
Hello @rietta, thanks for your request.
Beforehand I want to ask: a captcha or a request throttle on signup aren't sufficient for your use case?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
