### ISSUE TITLE
Gem devise :  undefined local variable or method `config' for main:Object

### ISSUE THREAD

**Issue by OliDelv** [plataformatec/devise#4698]
Hello,

I am trying to migrate an application to a new server.
When I start the application, I get an error in the log :

> [ E 2017-11-15 09:10:51.5205 1004/T53 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/xxxxx/site/xxxxx_rails: An error occurred while starting up the preloader.
  Error ID: f8c40999
  Error details saved to: /tmp/passenger-error-yWsTEa.html
  Message from application: There was an error while trying to load the gem 'devise'.
Gem Load Error is: undefined local variable or method `config' for main:Object
Backtrace for gem load error is:
/home/xxxxx/.gemls/ruby/2.2.0/gems/devise-3.5.10/lib/devise.rb:499:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:81:in `require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:76:in `each'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:65:in `each'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:65:in `require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler.rb:114:in `require'
/home/xxxxx/site/xxxxx_rails/config/application.rb:7:in `<top (required)>'
/home/xxxxx/site/xxxxx_rails/config/environment.rb:2:in `require'
/home/xxxxx/site/xxxxx_rails/config/environment.rb:2:in `<top (required)>'
config.ru:3:in `require'
config.ru:3:in `block in <main>'
/home/xxxxx/.gemls/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/home/xxxxx/.gemls/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:110:in `eval'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
/usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:80:in `block (2 levels) in require'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:76:in `each'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:76:in `block in require'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:65:in `each'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler/runtime.rb:65:in `require'
  /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/bundler.rb:114:in `require'
  /home/xxxxx/site/xxxxx_rails/config/application.rb:7:in `<top (required)>'
  /home/xxxxx/site/xxxxx_rails/config/environment.rb:2:in `require'
  /home/xxxxx/site/xxxxx_rails/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/xxxxx/.gemls/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /home/xxxxx/.gemls/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.2.3/gems/passenger-5.1.11/src/helper-scripts/rack-preloader.rb:29:in `<main>'

<

Versions are :
>[xxxxx@offer xxxxx_rails]$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
[xxxxx@offer xxxxx_rails]$ rails -v
Expected string default value for '--rc'; got false (boolean)
Rails 4.2.6
[xxxxx@offer xxxxx_rails]$ bundle install | grep devise
Using devise 3.5.10<

Thanks for your help.

**Comment by ricardoruwer** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
