### ISSUE TITLE
Support for other background processing?

### ISSUE THREAD

**Issue by julien51** [plataformatec/devise#4702]
Hi! Our app is deployed on AWS Beanstalk... and we use `active_elastic_job` to handle our offline jobs.
We also use Devise and we would love to be able to also use `active_elastic_job` to send email asynchronously, but it looks like this is not currently supported by Devise. Any reason why only Resque, Sidekiq and Delayed::Job are supported?

Any guideline on how to add other background processing?

**Comment by rafaelfranca** [comment]
Devise supports any background processing that Rails supports to send email. You only need to configure Rails correctly to be able to do so.

See https://github.com/plataformatec/devise/blob/88e9a85d6a796a41f4dcf2528ed6d5f48916b5fd/README.md#activejob-integration and http://guides.rubyonrails.org/active_job_basics.html#setting-the-backend
