### ISSUE TITLE
FactoryGirl factory not generated, marked as `error` in output

### ISSUE THREAD

**Issue by febeling** [plataformatec/devise#4708]
## Environment

- Ruby **2.3.3p222**
- Rails **5.0.6**
- Devise **4.3.0**

## Current behavior

Devise generate fails to generate a factory for FactoryGirl. This is likely due to the recent renaming of the package to FactoryBot. See https://github.com/thoughtbot/factory_bot/blob/master/NAME.md#project-naming-history.

```
$ rails generate devise CustomerUser                                                                                              [11:09:48]
      invoke  active_record
      create    db/migrate/20171127103651_devise_create_customer_users.rb
      create    app/models/application_record.rb
      create    app/models/customer_user.rb
      invoke    rspec
      create      spec/models/customer_user_spec.rb
      error      factory_girl [not found]       # <----------------------
      insert    app/models/customer_user.rb
       route  devise_for :customer_users
```

## Expected behavior

To generate a factory with factory_bot, which is used in this said project.

**Comment by feliperenan** [comment]
Hi @febeling. I tried to reproduce the error but I couldn't. I think the Devise does not have any reference to `FactoryBot/FactoryGirl`, strange this error 🤔 . Anyway, you can see my output below:

![image](https://user-images.githubusercontent.com/27698968/33289030-49db1b12-d3a5-11e7-847f-fffd3e9faa5b.png)

Could you send us an example to reproduce the error?

**Comment by febeling** [comment]
@feliperenan - I found an outdated generator configuration in `config/application.rb`, which has been the culprit apparently. Sorry for the noise, and thanks for your quick response anyway!

**Comment by febeling** [comment]
For future people searching for this, this is the outdated config that can cause this error:
```ruby 
config.generators do |generate|
   generate.fixture_replacement :factory_girl, dir: "spec/factories"
end
```

**Comment by TImPDaley** [comment]
Post script : change old "factory_girl" to the new "factory_bot" (assuming you upgraded) and it all works

**Comment by amitk** [comment]
This issue can arise even when you are using "factory_bot" with rails, so to solve it use [factory_bot_rails gem](https://github.com/thoughtbot/factory_bot_rails)
