### ISSUE TITLE
Can't run generator on Rails 5.2.0.beta1

### ISSUE THREAD

**Issue by jcoyne** [plataformatec/devise#4709]
```
    generate  devise

      invoke  active_record

      create    db/migrate/20171128000517_devise_create_users.rb

Could not find "model.rb" in any of your source paths. Your current source paths are: 

/home/travis/.rvm/gems/ruby-2.4.2/gems/activerecord-5.2.0.beta1/lib/rails/generators/active_record/model/templates

```

## Environment

- Ruby **2.4.2**
- Rails **5.2.0.beta1**
- Devise **4.3.0**

## Current behavior
Gives an error running the generator

## Expected behavior
No error, `app/models/user.rb` is generated.

**Comment by rafaelfranca** [comment]
I just tried it with Rails 5.2.0.beta2 and it seems to be working fine. Could you try again?

**Comment by jcoyne** [comment]
for some reason this was happening when my bundle was resolving thor to 0.18.1 (which is really old).  This error doesn't occur with a modern version of thor.
