### ISSUE TITLE
Using prepend_before_action :authenticate_user!

### ISSUE THREAD

**Issue by collimarco** [plataformatec/devise#4713]
All your examples use `before_action :authenticate_user!`.  I have a scenario where it would be useful to use `prepend_before_action :authenticate_user!`. Is it safe to use `prepend_before_action` or it will break Devise? I am not talking about my application design: it's a question about Devise design.

**Comment by collimarco** [comment]
After some reasoning, probably using  `prepend_before_action` is **not safe**. 
For example if you protect from forgery by making the session null and Devise `authenticate_user!` is called before clearing the session, then you successfully authenticate the user, whereas the authentication should have failed and the session ignored.
If I am right, then you should probably document this dangerous behavior somewhere.

**Comment by gencer** [comment]
@collimarco, I was going to tell you exact same thing. However, I wasn't too sure so I did not replied back.

As you said, `prepend_before_action` and `before_action` has a different use cases. `prepend_*` does what it says. It just add your definition at index zero. Devise will execute your method _before executing its own core part_. This is **not recommended for safety** and also for life-cycle. But, If you have something unique in your mind and think that executing that definition at very beginning of request then it is safe to use prepend in some cases.

Hence, `before_action` will "**append**" just after _all necessary core actions_ which is recommended way for safety.

**Comment by tegon** [comment]
Is probably better to stick with `before_action` indeed. I'm closing this since it's not actually an issue, if you have more questions, please use StackOverflow, because there a wider community will be able to help.
Thank you!
