### ISSUE TITLE
 I can not update user information by devise - "Current password can't be blank"

### ISSUE THREAD

**Issue by Emerson2017** [plataformatec/devise#4714]
I know that this same problem has been much debated here and several other places. But I still have not got something that solved my problem.

Whenever I try to update something from my user, comes the same error: "Current password can not be blank".
If anyone could give me a light, I would gladly. please

**Comment by tegon** [comment]
If you're using the `Devise::RegistrationsController#update` action, it will assume that you're [updating the password too](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L95).
You can take a look at the [Wiki](https://github.com/plataformatec/devise/wiki/How-To%3A-Allow-users-to-edit-their-account-without-providing-a-password) for some workarounds made by the community, but if you don't want to update the pthehe password, I'd recommend you to create another controller and simply call `#update` on your model.
