### ISSUE TITLE
ActionController::InvalidAuthenticityToken in Users::SessionsController#create after sign_out(@user)

### ISSUE THREAD

**Issue by vladi160** [plataformatec/devise#4715]
I have app which uses Ajax to authenticate user and after that it checks is the user blocked (blocked column in the users table) and if it is, it execute method sign_out(@user). It works fine with the first request, but if user tries to authenticate again there is an error `ActionController::InvalidAuthenticityToken in Users::SessionsController#create`. I have set globally headers for CSRF token like this:
`$(document).ajaxSend(function(e, xhr, options) {
  var token = $("meta[name='csrf-token']").attr("content");
   xhr.setRequestHeader("X-CSRF-Token", token);
 });`
In the SessionsController create action:
`	def create	
		if warden.authenticate(:scope => resource_name)
			if current_user.blocked
				sign_out(@user)
				return render json: {blocked: true}
			else
				return render json:{success: true}
			end
		else
			return render json: {error: true}
		end
	end`

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
