### ISSUE TITLE
# character appended to URL after logging in via omniauth

### ISSUE THREAD

**Issue by humphreybc** [plataformatec/devise#4716]
## Environment

- Chrome 62
- Ruby 2.4.1
- Rails 5.1
- Devise 4.3

## What happens

A # character is appended to the end of the URL after authenticating with Google using [omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2/) 0.4.1. It only happens when using Devise omniauth, and not when logging in with email & password. The # is not being added to the location HTTP header by Google.

In our case, we redirect to /projects after authentication so the result is a # on the end of our URL, like `http://localhost:3000/projects#` or `https://dovetailapp.com/projects#` on production.

Here are some relevant code snippets:

### config/initializers/devise.rb

```ruby
...
config.omniauth :google_oauth2, Figaro.env.google_client_id, Figaro.env.google_client_secret, { name: 'google', prompt: 'select_account' }
...
```

### config/routes.rb

```ruby
...
root 'pages#home'

devise_for :users, controllers: { confirmations: 'confirmations',
                                  invitations: 'invitations',
                                  omniauth_callbacks: 'omniauth_callbacks',
                                  passwords: 'passwords',
                                  registrations: 'registrations',
                                  sessions: 'sessions' }
...
```

### app/controllers/pages_controller.rb

```ruby
class PagesController < ApplicationController
  layout 'website'

  def home
    redirect_to(projects_path) if user_signed_in?
    redirect_to(new_user_invitation_path) if admin_signed_in?
  end
end
```

### app/controllers/omniauth_callbacks_controller.rb

This method handles both creating an account and logging in via Google.

```ruby
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'website'

  def google
    url = request.env['REQUEST_URI']
    params = Rack::Utils.parse_query URI(url).query
    data = request.env['omniauth.auth'].info
    name = data['name']
    email = data['email']

    user = User.find_by(email: email)

    if user.nil?
      user = User.from_omniauth(name, email)
      sign_in_and_redirect user, event: :authentication
      return
    end

    sign_in_and_redirect user, event: :authentication
  end
end
```

## app/controllers/sessions_controller.rb

```ruby
class SessionsController < Devise::SessionsController
  layout 'website'

  def create
    super
    flash.delete('notice')
  end
end
```

**Comment by tegon** [comment]
Hello @humphreybc, thanks for your report.
Does this cause some issue in your application?

**Comment by humphreybc** [comment]
@tegon So it looks like it's possibly a security feature of Chrome, although I can't find much documentation online. I can't reproduce this in Firefox.

**Comment by tegon** [comment]
@humphreybc Got it. 
I'm going to close this since it isn't breaking anything.
If you figure out that Devise is indeed adding this, we are willing to accept a pull request to address it.

Thank you!
