### ISSUE TITLE
Cannot install on Rails 5.1.4

### ISSUE THREAD

**Issue by criztovyl** [plataformatec/devise#4721]
## Environment

- Ruby **ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]**
- Rails **5.1.4**
- Devise **4.3.0** (master too)

## Current behavior

```
$ rails generate devise:install
/var/lib/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/http/response.rb:89:in `<class:Response>': undefined method `cache_control' for class `ActionDispatch::Response' (NameError)
```
[Full Log](https://gist.github.com/criztovyl/fb447ae5b4e33f3d4ecb056bcd046171)

## Expected behavior

*`rails generate` works*

**Comment by tegon** [comment]
Hello @criztovyl, thanks for your report.
I tried here, and everything worked as expected.
By looking at your full log, it seems like you haven't added Devise to your `Gemfile`, is that correct? Does the error persist if you install the gem by including it in the `Gemfile`?

**Comment by criztovyl** [comment]
I tried it with devise in the Gemfile, but it did not work either, will try again and post a log :)

**Comment by criztovyl** [comment]
[Log with devise in `Gemfile`](https://gist.github.com/criztovyl/573d1772158ece1c13de6261dab89ce7).

**Comment by tegon** [comment]
This seems really odd, it doesn't look like a Devise issue at all since the stack trace doesn't event hit our generator.
Question: are you able to run other generators in your application?
I've found a similar issue of yours here: https://github.com/Shopify/shopify_app/issues/347

Also, if you run `rails console` in your application, which is the result of this?
```rb
ActionDispatch::Response.new
```

**Comment by criztovyl** [comment]
A simple `rails console` already fails; this really seems not to be an issue with devise.

Sorry. :)

**Comment by tegon** [comment]
No problem, I'm glad you figured out!
