### ISSUE TITLE
Rememberable: User.serialize_from_cookie returns nil

### ISSUE THREAD

**Issue by geetotes** [plataformatec/devise#4726]
## Environment

- Ruby 2.3.3
- Rails 5.1.4
- Devise 4.3.0

## Current behavior
I am trying to enable the rememberable option on an app that uses Devise and DeviseTokenAuth. Currently, it looks like the rememberable cookie returns `nil` when read by `serialize_from_cookie`. I think this is what is blocking rememberable from working correctly.

Here is my sign-in controller:
```
module Overrides
  class SessionsController < DeviseTokenAuth::SessionsController
    include Devise::Controllers::Rememberable

    def create
        # snip.... (@resource is the user I want to sign-in)
        @client_id = is_mobile_app_client && request.headers['client'] ? request.headers['client'] : SecureRandom.urlsafe_base64(nil, false)
        @token     = SecureRandom.urlsafe_base64(nil, false)

        @resource.tokens[@client_id] = {
          token: BCrypt::Password.create(@token),
          expiry: (Time.now + DeviseTokenAuth.token_lifespan).to_i
        }
        @resource.save

        sign_in(:user, @resource, store: false, bypass: false)

        if params[:remember_me] == true
          remember_me(@resource)
        end
    end
```
I can see `remember_me(@resource)` initializes a nice `remember_user_token` on the client side. However, when this token is read, the result is always `nil`. The token looks like this:
```
(byebug) request.cookies['remember_user_token']
"W1s2XSwiJFAkQkFiVGZlTjhBRWRYZDZXNzNGcnZ0Y2I1UjIiLCIxNTEzMzY2NDg3LjgxMzg4NjYiXQ==--5b5cfd57ca3c908ad4cdda20c643147c11cb9852"
```
However, when I call `User.serialize_from_cookie` and pass that token, it returns nil. Calling `User.serialize_into_cookie` gives me a cookie that looks different (the user I'm looking at, "t9", is already signed in):
```
(byebug) User.serialize_into_cookie(User.find_by(username: 't9'))
  CACHE User Load (0.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`username` = 't9' LIMIT 1  [["username", "t9"], ["LIMIT", 1]]
[[6], "$P$BAbTfeN8AEdXd6W73Frvtcb5R2", "1513369743.638756"]
```
Even calling `User.serialize_from_cookie` on that cookie returns nil! The top of my user model looks like this:
```
class User < ApplicationRecord
  acts_as_paranoid

  devise :rememberable, :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,
         :omniauthable, :lockable, :confirmable,
         :omniauth_providers => [:facebook, :twitter]

  include DeviseTokenAuth::Concerns::User
```

## Expected behavior

I should be able to run `User.serialize_from_cookie` on my `remember_user_token` and get a valid user.

**Comment by tegon** [comment]
Hello @geetotes, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by geetotes** [comment]
@tegon Unfortunately, I can't provide a sample application. But I was able to solve my issue with manually serializing/serializing the cookies -- I had forgotten that they are signed when saved to the client.
