### ISSUE TITLE
Email password instruction issue

### ISSUE THREAD

**Issue by Atalaa** [plataformatec/devise#4728]
## Environment

- Rails 4.2.5
- Devise 4.3

## Current behavior

The sent password instruction doesn't work.
I enter my email adress and click on "sent me reset password instruction" then i did not receive the email instructions.

I tried a few times.

**Comment by tegon** [comment]
Hi @Atalaa, thanks for your report.
I've just tested with a newly created Rails 4.2 application and everything is working as expected.
Do you get any errors? How is your mailer configuration?
It's important to remember that you have to set your mailer URL options in the environment configuration, e.g `config/environments/development.rb`:
```rb
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
```
You can also use the `letter_opener` gem to open the emails on the browser (the issue may be with your mailer configuration).

**Comment by Atalaa** [comment]
Hi @tegon , you meant you received an email password instruction in development.rb file ?
Because i set it up like you and i did not received any email.
I read online that its because C9 block this to avoid spammed message and my teacher online said it should works in production if i write host: 'yourappname.herokuapp.com'

How come it works for you in environment ?

Here my code in development file:
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

**Comment by tegon** [comment]
Yep, but I tested used the [`letter_opener` gem ](https://github.com/ryanb/letter_opener) which open the emails on the browser to use in development.
If you want to actually receive the email in your inbox you have to configure the mailer in your Rails application.

**Comment by tegon** [comment]
I'm closing this since it looks like an issue with the Rails mailer configuration.
Feel free to open a new issue with all the information requested in the template if this still happens.

Thank you!

**Comment by Atalaa** [comment]
For those who are going to encounter the same problem, it was a conflict between the gemfile and the gemgile.lock .
The stock_quote version I updated in the gemfile was not the same as the one that existed in the gemfile.lock .
So you had to manually go to gemfile.lock and put the same version as the gemfile. That's all
