### ISSUE TITLE
NoMethodError in Stocks#index 

### ISSUE THREAD

**Issue by Atalaa** [plataformatec/devise#4729]
I am doing a web app and at some point i get this issue
NoMethodError in Stocks#index 

It supposed to display something AFTER "rescue StandardError" but instead it display this red page error

## Environment

    Rails 4.2.5
    Devise 4.3

**Comment by tegon** [comment]
Devise doesn't have a `StocksController`, this is most likely an error on your application.

Please use StackOverflow for questions/help like this in the future. 
There a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
