### ISSUE TITLE
Support web standards:  routes like "users/sign_in" should be "users/sign-in"

### ISSUE THREAD

**Issue by KelseyDH** [plataformatec/devise#4732]
This is not a bug that's breaking anything, but it's generally recognized that URL routes [should be constructed using hyphens, rather than underscores.](http://www.ecreativeim.com/blog/2011/03/seo-basics-hyphen-or-underscore-for-seo-urls/)

## Current behavior

GET users/sign_in

## Expected behavior

GET users/sign-in

-----------

Devise's default URL behaviour confused other developers when consuming our API, who are used to having all URL routes delineated by hyphens rather than underscore.

Since changing devise's default URL routes to hyphens now from underscores could lead to many breaking API changes, I'm wondering if it would make sense to have devise alias both "sign_in" and "sign-in" as valid URL routes for devise to standardize with commonly accepted practice.

Thoughts?

**Comment by tegon** [comment]
@KelseyDH You're right, this is a breaking change, so I suggest you override these routes paths in your application for now, as suggested here: https://github.com/plataformatec/devise/wiki/How-To:-Change-Default-Sign_up---Registration-Path-with-Custom-Path

Thank you.
