### ISSUE TITLE
Devise.paranoid should be set separately for lockable vs. others

### ISSUE THREAD

**Issue by johnnyshields** [plataformatec/devise#4734]
In my use case I want to use paranoid for password reset and resend unlock instructions but NOT for the account locked after X attempts.

**Comment by tegon** [comment]
Hello @johnnyshields, thanks for your request.
We don't have plans to support this for now, so although I know it's not ideal, you probably will have to override this code to add your custom behavior.
If this became a popular feature request, we could think about supporting in a next version.

Thank you!
