### ISSUE TITLE
Syntax error on Ruby 2.5.0

### ISSUE THREAD

**Issue by lucianosousa** [plataformatec/devise#4736]
I'm trying to update the call4paperz for the new Ruby 2.5.0 and received this error:

```
SyntaxError (/Users/lucianosousa/.rvm/gems/ruby-2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end
...ion only: [:create, :destroy] { request.env["devise.skip_tim...
...                              ^
/Users/lucianosousa/.rvm/gems/ruby-2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }
```
when goes to `/users/sign_in`

I've replaced the `{}` to `do/end` block and works fine.

Code is available here https://github.com/call4paperz/call4paperz/pull/236 to take a look

**Comment by johnpaulashenfelter** [comment]
Verified. Same problem here in our Ruby 2.5/Rails 5.1.4/Devise 4.3.0 app.

**Comment by Tolchi** [comment]
Verified. Same in Ruby 2.5.0/Rails 5.0.6/Devise 4.3.0

**Comment by tpitale** [comment]
Fixed in Master https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L7 via https://github.com/plataformatec/devise/issues/4719

**Comment by tmikoss** [comment]
Seeing that it's been fixed in master for some time now, could we ask for a release?

**Comment by lucianosousa** [comment]
Looks like it's fixed. Let's wait for a new release

**Comment by arturtr** [comment]
Release patched gem version, please. Many developers update ruby yesterday. Many of them use device.

First step - trying `bundle update`.

**Comment by jrochkind** [comment]
@lucianosousa any idea how long we'll be waiting?

**Comment by lucianosousa** [comment]
@arturtr latest devise release is 4.3.0 from May. no difference `bundle update` in this specific case.
@jrochkind no idea, waiting here. what I can suggest you is to point your devise gem (inside `Gemfile`) to this repo

**Comment by jrochkind** [comment]
I will probably "monkey-patch" it locally rather than point to an unrelased git sha. 

Are there currently maintainers for this gem?

**Comment by doolin** [comment]
@jrochkind That's what I'm doing. bundle open ftw

**Comment by tegon** [comment]
Hi everyone, version 4.4.0 is out: https://rubygems.org/gems/devise/versions/4.4.0
