### ISSUE TITLE
destroy_user_session syntax error unexpected '}', , expecting keyword_end ..."devise.skip_timeout"] = true } ... ^

### ISSUE THREAD

**Issue by clay-f** [plataformatec/devise#4738]
ruby 2.5.0
rails 5.1.4
devise 4.3.0

I'm click link user `sign out` browser report errror

this link code ` <%= link_to 'Sign out',  destroy_user_session_path, method: :delete, class: "dropdown-item" %>`

<img width="1266" alt="screen shot 2017-12-27 at 22 16 54" src="https://user-images.githubusercontent.com/16079417/34383924-b787d1ee-eb53-11e7-8753-35adf2650840.png">

**Comment by doolin** [comment]
This was found and fixed months ago when the Devise team checked the prelease version of Ruby 2.5.0.

While the fix has been in master for quite some time, the Devise team does not want to release the fix yet.

You will need to either not use Ruby 2.5.0, or you will need to use Devise from master, until the Devise team decides to release the fix. You could also fork Devise, fix it yourself, and use your own version. Actually, you could also just fix it in your locally installed gem, which is probably what I'm going to do.

But your best bet, if you don't know how to do any of the above fixes,  is probably to not use Ruby 2.5.0 until the Devise team decides to release the fix.

**Comment by clay-f** [comment]
OK, thanks

**Comment by marnen** [comment]
Looks like there's a release now.
