### ISSUE TITLE
sign_out(:user) does nothing in production

### ISSUE THREAD

**Issue by emirkin** [plataformatec/devise#4745]
I have a strange issue processing signout for a user. In my flow, I have a GET that leads to my controller executing `sign_out :user`. This works fine in development (`localhost:3000`) but does not work in production where the app runs under an actual domain name. By "does not work", I mean it does not delete the session cookie in the user's browser. I am not sure if this is a Devise issue, but I am at a loss about what could be causing this.

## Environment
```
    rails (5.0.6)
    devise (4.4.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
```

This appears to be similar to https://github.com/plataformatec/devise/issues/3031, although that issue has long been closed.

**Comment by emirkin** [comment]
New information - `session.delete("warden.user.user.key")` does not work either. Perhaps the issue is in the session store.

**Comment by emirkin** [comment]
I ended up using `https://github.com/rails/activerecord-session_store` as the fix.

**Comment by tegon** [comment]
Hi @emirkin, thanks for your report.
You're storing the session in your database, right?
So can I close this issue?

Thanks.

**Comment by emirkin** [comment]
Correct.
