### ISSUE TITLE
4.4.0 Re renders sign in screen after successful sign in.

### ISSUE THREAD

**Issue by JonRowe** [plataformatec/devise#4746]
## Environment

- Ruby 2.4.5
- Rails 4.2
- Devise 4.4.0

## Current behaviour

After successful sign in, the sign in screen is shown with a `must contain a number or symbol` error message for password, despite password containing number and symbol, and despite user being signed in.

## Expected behaviour

User is redirected to admin root.

**Comment by JonRowe** [comment]
This appears to be caused by a custom validation on my end, which is run and not cleared when the user is logged in.

**Comment by tegon** [comment]
Duplicate of #4742
