### ISSUE TITLE
How to test sign_up with RSpec ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [plataformatec/devise#4747]
rails (5.1.4)
    devise (4.3.0)
    devise_token_auth (0.1.42)
    ruby (2.4.0p0)
    RSpec 3.7
        - rspec-core 3.7.0
        - rspec-expectations 3.7.0
        - rspec-mocks 3.7.0
        - rspec-rails 3.7.1
        - rspec-support 3.7.0

I'm using `DeviseTokenAuth` for rails api app, then I tried to test `RegistrationsController` in `Devise` after overriding it, when I wanna test create action with `RSpec` I got this error even after I follow the wiki page [How-To:-Test-controllers-with-Rails-3-and-4-(and-RSpec)][2]

the error is 

    1) Api::V1::Customers::RegistrationsController Post#create creates a new customer
     Failure/Error: expect(response).to have_http_status(:created)
       expected the response to have status code :created (201) but it was :unprocessable_entity (422)

where the `log/test.log` file got this:

    Processing by Api::V1::Customers::RegistrationsController#create as HTML
    Parameters: {"customer"=>{"confirmed_at"=>"2018-01-08", "email"=>"ggg@mail.com", "first_name"=>"first_name", "last_name"=>"last_name", "mobile_phone_number"=>"12933485123", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "telephone_number"=>"123412341234"}}
    Unpermitted parameter: :customer
    Filter chain halted as :validate_sign_up_params rendered or redirected
    Completed 422 Unprocessable Entity in 2ms (Views: 0.2ms | ActiveRecord: 0.0ms)[1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m

and my `registrations_spec.rb_controller_spec.rb`

    require 'rails_helper'

    RSpec.describe Api::V1::Customers::RegistrationsController, type: :controller do
      let(:customer) { FactoryBot.create(:customer) }

      before :each do
          request.env['devise.mapping'] = Devise.mappings[:api_v1_customer]
      end

      describe "Post#create" do
          it 'creates a new customer' do
              post :create, params: { customer: attributes_for(:customer) }
              expect(response).to have_http_status(:created)
          end
      end
    end

and my `RegistrationsController`

    class Api::V1::Customers::RegistrationsController < DeviseTokenAuth::RegistrationsController
      before_action :configure_sign_up_params, only: [:create]
      before_action :configure_account_update_params, only: [:update]

      def create
         super
      end

      protected

      def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name,:mobile_phone_number,:telephone_number])
      end

      def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,:mobile_phone_number,:telephone_number])
      end
  
    end

and my `FactoryBot` file for `Customer`

    FactoryBot.define do
      factory :customer do
          first_name "first_name"
          last_name "last_name"
          email "ggg@mail.com"
          password "12341234"
          password_confirmation "12341234"
          confirmed_at Date.today
          telephone_number "123412341234"
          mobile_phone_number "12933485123"
      end
    end

Is there anything wrong with this code ?

  [1]: https://stackoverflow.com/questions/35013635/filter-chain-halted-as-validate-sign-up-params-rendered-or-redirected-devise
  [2]: https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-(and-RSpec)

**Comment by tegon** [comment]
From your log `Unpermitted parameter: :customer` I think you have to permit the `customer` parameter. Seems like you're only permitting the `customer` nested parameters, like `first_name` and `last_name`.

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!

**Comment by Mohammed-Eliass** [comment]
I don't need to permit a nested parameters and this how I sent the data from `Postman`

    {
	    "email":"email@mail.com",
	    "password":"password",
	    "password_confirmation":"password",
	    "first_name": "first_name",
	    "last_name": "last_name",
	    "telephone_number": "telephone_number",
	    "mobile_phone_number": "mobile_phone_number"
    }

Fyi, I used stackoverflow to the same question and no one answered me!

**Comment by tegon** [comment]
But in your test you're doing `post :create, params: { customer: attributes_for(:customer) }`, and your logs show: `{"customer"=>{"confirmed_at"=>"2018-01-08", "email"=>"ggg@mail.com", "first_name"=>"first_name", "last_name"=>"last_name", "mobile_phone_number"=>"12933485123", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "telephone_number"=>"123412341234"}}`

I think your test should be:
`post :create, params: attributes_for(:customer)`

**Comment by Mohammed-Eliass** [comment]
Thanks mate, and sorry if I waste your time! :)
