### ISSUE TITLE
Registration if email already exist 

### ISSUE THREAD

**Issue by Mesnet** [plataformatec/devise#4751]
I've a variable registered(boolean) in my table User. Because when a connected user want to use an Email, if this email is not existing into the table User, a new line is created in the Users (only with the variable email, and registered = false). So I would like that when a user registers, he will not be blocked if(email exist && registered == false). In this case, the password will be replaced, and the variable registered change to true.

I would like to run something like that :

```
def create     
  @user_registred = User.find(email: params[user: :email])     
  if @user_registred.any?       
    if @user_registred.registred == false         
      @user = User.update(params[:user])       
    else          
      notice: "Email already taked"       
    end     
  else       
    @user = User.new(params[:user])     
  end   
end
```

**Comment by tegon** [comment]
Hello, @Mesnet.
Sorry, I don't think I understood what you want. You can override the `create` action of the `RegistrationsController` to implement your custom behavior.
