### ISSUE TITLE
Need to require 'devise' in my_engine.rb

### ISSUE THREAD

**Issue by sshakil** [plataformatec/devise#4755]
For instructions on: https://github.com/plataformatec/devise/wiki/How-To:-Use-devise-inside-a-mountable-engine, we need to add `require 'devise'` first thing in the lib/my_engine.rb file, before doing a `rails generate devise MODEL`, otherwise there's an error.

**Comment by tegon** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back.

Thank you!
