### ISSUE TITLE
Firebase Facebook login

### ISSUE THREAD

**Issue by tuxtux59** [plataformatec/devise#4756]
## Environment

- Ruby **2.3.1p112**
- Rails **4.2.6**
- Devise **4.0.3**

## Current behavior
Hi,
By default my users log with their email & password and I use firebase for several things and I'm trying to integrate facebook login using firebase for web users.
The problem is that I don't understand if facebook datas retrieve by firebase for the user are OmniAuth compatible.
And I don't know which key could be used to force my server to log the user using these retrieved params!

Have you some clues to help me in this dark path?

Thanks

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
