### ISSUE TITLE
#check_captcha method flash message errors

### ISSUE THREAD

**Issue by hidroo** [plataformatec/devise#4757]
I am using this here solution:
https://github.com/plataformatec/devise/wiki/How-To:-Use-Recaptcha-with-Devise

for registration.

The problem is that verify_recaptcha adds the error in flash[:recaptcha_error], not in flash[:notice]. 

This generates a problem when the resource is valid, but the captcha is not. Because the device controller checks if there is a flash[:notice], and if not it sets one that says "User has been successfully created.". And thus I have two flashes, one that says that the captcha is not valid and another that says that the resource has been created (It is not been created.)

My workaround is:
`flash[:notice] = flash[:recaptcha_error]`
        `flash.delete(:recaptcha_error)`

Is there a better solution? Is there a way to tell devise that my resource does not have any errors, but is not ok and thus not saved?

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
