### ISSUE TITLE
[4.4.1] Errno::EACCES: Permission denied @ rb_sysopen -

### ISSUE THREAD

**Issue by francesco-loreti** [plataformatec/devise#4761]
## Environment

- Ruby 2.4
- Rails 5.2.beta2
- Devise 4.4.1

## Error:
`Installing devise 4.4.1 (was 4.4.0)
Errno::EACCES: Permission denied @ rb_sysopen -
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/devise.png
An error occurred while installing devise (4.4.1), and Bundler cannot continue.
Make sure that `gem install devise -v '4.4.1'` succeeds before bundling.`

**Comment by tegon** [comment]
Hello @francesco-loreti, thanks for your report.
This doesn't look like an issue with devise. The error message implies that you might need to change the permissions of your gems directory.

Thanks.
