### ISSUE TITLE
Which argument devise is expecting?

### ISSUE THREAD

**Issue by dcalixto** [plataformatec/devise#4762]
## After trying to overwrite the authenticate_user! With the code below
the gem complain about a argument.
so which argument is expecting?

```
def authenticate_user!
    if self.request.format.html?
      super
    elsif self.request.format.json?
      if self.request.parameters["controller"].start_with?("devise")
        super
      else
        if user_signed_in?
          # use the default if already signed in
          super
        else
          redirect_to root_path
        end
      end
    end
  end
```

## Environment

- Ruby **[2.5]**
- Rails **[5.1]**
- Devise **[4.4]**

## Current behavior

> ArgumentError in Devise::RegistrationsController#edit wrong number of arguments (given 1, expected 0) Extracted source (around line #20):

## Expected behavior
Not complain about the argument

**Comment by rafaelfranca** [comment]
It is a argument called `options` with default to `{}` https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/controllers/helpers.rb#L116

**Comment by dcalixto** [comment]
@rafaelfranca   thank you!
