### ISSUE TITLE
Use same string on failed login regardless of whether account exists when in paranoid mode

### ISSUE THREAD

**Issue by JasonBarnabe** [plataformatec/devise#4763]
Previously reported in #4568. devise is using `devise.failure.invalid` when you attempt to log in with an existing identifier but a wrong password, while it uses `devise.failure.not_found_in_database` when the identifier does not exist. In the default `en.yml` provided by devise, these strings are the same, but if you are using a different localization file, they may not be (see https://github.com/tigrish/devise-i18n/issues/223).

If you have enabled paranoid mode, the same localization key should be used for both cases.

**Comment by tegon** [comment]
I haven't understood what the problem was on the previous issue, but now I do 😅 . Thanks, @JasonBarnabe.
This change seems reasonable to me, but I think we would have to do it in a major version since it isn't backward compatible.
Would you be willing to work on this?

**Comment by tegon** [comment]
Closed via https://github.com/plataformatec/devise/pull/4854
