### ISSUE TITLE
Rails API - Password Reset Route

### ISSUE THREAD

**Issue by mfaorlkzus** [plataformatec/devise#4764]
Hello guys, I ask the issue here, because nobody could answer my question on Stackoverflow and the Wiki also can't help me with my problem.

I have a Rails API, that uses the Devise gem to manage users. Now I want to implement a password-reset feature, so that a user can get an email with a link to a frontend page where he can set a new password for his account.
I configured the mailer and created a custom controller action for my Customerclass, which looks like this:

    def self.reset_password(email)
        @admin = Customer.find_by_email(email)
        if @customer.present?
            @customer.send_reset_password_instructions
            return {"status": "email sent"}
        else
            return {"status": "error"}
        end
    end

I receive the email with the link and a reset_password_token from devise. Works like a charm. The problem I'm facing now, is that I don't know which address the request for setting the new password has to go to. I figured out, that a PUT /customer/password should be the correct route(?), but when I send my request to this address:

    PUT /customer/password
    {"customer": {"new_password": "abcdefg", "new_password_confirmation": "abcdefg", "reset_password_token": "siafhw78fcbt7rb8ag987gb9wagew"}}

...I get the following error code:

    RESPONSE:
    {
      "status": 406,
      "error": "Not Acceptable",
      "exception": "#<ActionController::UnknownFormat: ActionController::UnknownFormat>",
      "traces": {
        "Application Trace": [],
        "Framework Trace": [
          {
            "id": 0,
            "trace": "responders (2.4.0) lib/action_controller/respond_with.rb:213:in `respond_with'"
          },
          {
            "id": 1,
            "trace": "devise (4.3.0) app/controllers/devise/passwords_controller.rb:47:in `update'"
          },
          {
            "id": 2,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"
          },
          {
            "id": 3,
            "trace": "actionpack (5.0.6) lib/abstract_controller/base.rb:188:in `process_action'"
          },
          {
            "id": 4,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/rendering.rb:30:in `process_action'"
          },
          {
            "id": 5,
            "trace": "actionpack (5.0.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"
          },
          {
            "id": 6,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'"
          },
          {
            "id": 7,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'"
          },
          {
            "id": 8,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"
          },
          {
            "id": 9,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'"
          },
          {
            "id": 10,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'"
          },
          {
            "id": 11,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"
          },
          {
            "id": 12,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"
          },
          {
            "id": 13,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'"
          },
          {
            "id": 14,
            "trace": "actionpack (5.0.6) lib/abstract_controller/callbacks.rb:19:in `process_action'"
          },
          {
            "id": 15,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/rescue.rb:20:in `process_action'"
          },
          {
            "id": 16,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"
          },
          {
            "id": 17,
            "trace": "activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'"
          },
          {
            "id": 18,
            "trace": "activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"
          },
          {
            "id": 19,
            "trace": "activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'"
          },
          {
            "id": 20,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"
          },
          {
            "id": 21,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"
          },
          {
            "id": 22,
            "trace": "activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"
          },
          {
            "id": 23,
            "trace": "actionpack (5.0.6) lib/abstract_controller/base.rb:126:in `process'"
          },
          {
            "id": 24,
            "trace": "actionview (5.0.6) lib/action_view/rendering.rb:30:in `process'"
          },
          {
            "id": 25,
            "trace": "actionpack (5.0.6) lib/action_controller/metal.rb:190:in `dispatch'"
          },
          {
            "id": 26,
            "trace": "actionpack (5.0.6) lib/action_controller/metal.rb:262:in `dispatch'"
          },
          {
            "id": 27,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"
          },
          {
            "id": 28,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:32:in `serve'"
          },
          {
            "id": 29,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'"
          },
          {
            "id": 30,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `call'"
          },
          {
            "id": 31,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'"
          },
          {
            "id": 32,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'"
          },
          {
            "id": 33,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'"
          },
          {
            "id": 34,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'"
          },
          {
            "id": 35,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'"
          },
          {
            "id": 36,
            "trace": "warden (1.2.7) lib/warden/manager.rb:36:in `block in call'"
          },
          {
            "id": 37,
            "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `catch'"
          },
          {
            "id": 38,
            "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `call'"
          },
          {
            "id": 39,
            "trace": "rack (2.0.3) lib/rack/etag.rb:25:in `call'"
          },
          {
            "id": 40,
            "trace": "rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'"
          },
          {
            "id": 41,
            "trace": "rack (2.0.3) lib/rack/head.rb:12:in `call'"
          },
          {
            "id": 42,
            "trace": "activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'"
          },
          {
            "id": 43,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"
          },
          {
            "id": 44,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"
          },
          {
            "id": 45,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"
          },
          {
            "id": 46,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'"
          },
          {
            "id": 47,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"
          },
          {
            "id": 48,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
          },
          {
            "id": 49,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
          },
          {
            "id": 50,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"
          },
          {
            "id": 51,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
          },
          {
            "id": 52,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'"
          },
          {
            "id": 53,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'"
          },
          {
            "id": 54,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
          },
          {
            "id": 55,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'"
          },
          {
            "id": 56,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'"
          },
          {
            "id": 57,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'"
          },
          {
            "id": 58,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'"
          },
          {
            "id": 59,
            "trace": "rack (2.0.3) lib/rack/runtime.rb:22:in `call'"
          },
          {
            "id": 60,
            "trace": "activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
          },
          {
            "id": 61,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
          },
          {
            "id": 62,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'"
          },
          {
            "id": 63,
            "trace": "rack (2.0.3) lib/rack/sendfile.rb:111:in `call'"
          },
          {
            "id": 64,
            "trace": "rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'"
          },
          {
            "id": 65,
            "trace": "railties (5.0.6) lib/rails/engine.rb:522:in `call'"
          },
          {
            "id": 66,
            "trace": "puma (3.10.0) lib/puma/configuration.rb:225:in `call'"
          },
          {
            "id": 67,
            "trace": "puma (3.10.0) lib/puma/server.rb:605:in `handle_request'"
          },
          {
            "id": 68,
            "trace": "puma (3.10.0) lib/puma/server.rb:437:in `process_client'"
          },
          {
            "id": 69,
            "trace": "puma (3.10.0) lib/puma/server.rb:301:in `block in run'"
          },
          {
            "id": 70,
            "trace": "puma (3.10.0) lib/puma/thread_pool.rb:120:in `call'"
          },
          {
            "id": 71,
            "trace": "puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
          }
        ],
        "Full Trace": [
          {
            "id": 0,
            "trace": "responders (2.4.0) lib/action_controller/respond_with.rb:213:in `respond_with'"
          },
          {
            "id": 1,
            "trace": "devise (4.3.0) app/controllers/devise/passwords_controller.rb:47:in `update'"
          },
          {
            "id": 2,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"
          },
          {
            "id": 3,
            "trace": "actionpack (5.0.6) lib/abstract_controller/base.rb:188:in `process_action'"
          },
          {
            "id": 4,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/rendering.rb:30:in `process_action'"
          },
          {
            "id": 5,
            "trace": "actionpack (5.0.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"
          },
          {
            "id": 6,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'"
          },
          {
            "id": 7,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:126:in `call'"
          },
          {
            "id": 8,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"
          },
          {
            "id": 9,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'"
          },
          {
            "id": 10,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:455:in `call'"
          },
          {
            "id": 11,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"
          },
          {
            "id": 12,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"
          },
          {
            "id": 13,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'"
          },
          {
            "id": 14,
            "trace": "actionpack (5.0.6) lib/abstract_controller/callbacks.rb:19:in `process_action'"
          },
          {
            "id": 15,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/rescue.rb:20:in `process_action'"
          },
          {
            "id": 16,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"
          },
          {
            "id": 17,
            "trace": "activesupport (5.0.6) lib/active_support/notifications.rb:164:in `block in instrument'"
          },
          {
            "id": 18,
            "trace": "activesupport (5.0.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"
          },
          {
            "id": 19,
            "trace": "activesupport (5.0.6) lib/active_support/notifications.rb:164:in `instrument'"
          },
          {
            "id": 20,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"
          },
          {
            "id": 21,
            "trace": "actionpack (5.0.6) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"
          },
          {
            "id": 22,
            "trace": "activerecord (5.0.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"
          },
          {
            "id": 23,
            "trace": "actionpack (5.0.6) lib/abstract_controller/base.rb:126:in `process'"
          },
          {
            "id": 24,
            "trace": "actionview (5.0.6) lib/action_view/rendering.rb:30:in `process'"
          },
          {
            "id": 25,
            "trace": "actionpack (5.0.6) lib/action_controller/metal.rb:190:in `dispatch'"
          },
          {
            "id": 26,
            "trace": "actionpack (5.0.6) lib/action_controller/metal.rb:262:in `dispatch'"
          },
          {
            "id": 27,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"
          },
          {
            "id": 28,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:32:in `serve'"
          },
          {
            "id": 29,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'"
          },
          {
            "id": 30,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `call'"
          },
          {
            "id": 31,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'"
          },
          {
            "id": 32,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'"
          },
          {
            "id": 33,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'"
          },
          {
            "id": 34,
            "trace": "actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'"
          },
          {
            "id": 35,
            "trace": "actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'"
          },
          {
            "id": 36,
            "trace": "warden (1.2.7) lib/warden/manager.rb:36:in `block in call'"
          },
          {
            "id": 37,
            "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `catch'"
          },
          {
            "id": 38,
            "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `call'"
          },
          {
            "id": 39,
            "trace": "rack (2.0.3) lib/rack/etag.rb:25:in `call'"
          },
          {
            "id": 40,
            "trace": "rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'"
          },
          {
            "id": 41,
            "trace": "rack (2.0.3) lib/rack/head.rb:12:in `call'"
          },
          {
            "id": 42,
            "trace": "activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'"
          },
          {
            "id": 43,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"
          },
          {
            "id": 44,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"
          },
          {
            "id": 45,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"
          },
          {
            "id": 46,
            "trace": "activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'"
          },
          {
            "id": 47,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"
          },
          {
            "id": 48,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
          },
          {
            "id": 49,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
          },
          {
            "id": 50,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"
          },
          {
            "id": 51,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
          },
          {
            "id": 52,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'"
          },
          {
            "id": 53,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'"
          },
          {
            "id": 54,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
          },
          {
            "id": 55,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'"
          },
          {
            "id": 56,
            "trace": "activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'"
          },
          {
            "id": 57,
            "trace": "railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'"
          },
          {
            "id": 58,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'"
          },
          {
            "id": 59,
            "trace": "rack (2.0.3) lib/rack/runtime.rb:22:in `call'"
          },
          {
            "id": 60,
            "trace": "activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
          },
          {
            "id": 61,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
          },
          {
            "id": 62,
            "trace": "actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'"
          },
          {
            "id": 63,
            "trace": "rack (2.0.3) lib/rack/sendfile.rb:111:in `call'"
          },
          {
            "id": 64,
            "trace": "rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'"
          },
          {
            "id": 65,
            "trace": "railties (5.0.6) lib/rails/engine.rb:522:in `call'"
          },
          {
            "id": 66,
            "trace": "puma (3.10.0) lib/puma/configuration.rb:225:in `call'"
          },
          {
            "id": 67,
            "trace": "puma (3.10.0) lib/puma/server.rb:605:in `handle_request'"
          },
          {
            "id": 68,
            "trace": "puma (3.10.0) lib/puma/server.rb:437:in `process_client'"
          },
          {
            "id": 69,
            "trace": "puma (3.10.0) lib/puma/server.rb:301:in `block in run'"
          },
          {
            "id": 70,
            "trace": "puma (3.10.0) lib/puma/thread_pool.rb:120:in `call'"
          },
          {
            "id": 71,
            "trace": "puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
          }
        ]
      }
    }

So the error should be within Devices PasswordController#update, which looks like this:

    def update
        self.resource = resource_class.reset_password_by_token(resource_params)
        yield resource if block_given?
    
        if resource.errors.empty?
          resource.unlock_access! if unlockable?(resource)
          if Devise.sign_in_after_reset_password
            flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
            set_flash_message!(:notice, flash_message)
            sign_in(resource_name, resource)
          else
            set_flash_message!(:notice, :updated_not_active)
          end
          respond_with resource, location: after_resetting_password_path_for(resource)
        else
          set_minimum_password_length
          respond_with resource
        end
    end

And this is the part where I'm stuck. I can't figure out if the format of the request is wrong, if I'm maybe calling the wrong route or if it's because I have three user classes, which all use devise. Or maybe it's a completely different problem.
The wiki is not helpful for APIs and as I said in the beginning: sorry if this is not an issue, but I can't find any documentation on routes to reset password in APIs.

**I would really appreciate your feedback - thanks in advance**

**Comment by oamado** [comment]
https://github.com/plataformatec/devise/wiki/API-Mode-Compatibility-Guide
