### ISSUE TITLE
Devise error with ruby version 2.5.0

### ISSUE THREAD

**Issue by PolymathWhiz** [plataformatec/devise#4766]
<img width="683" alt="screen shot 2018-01-27 at 4 42 18 pm" src="https://user-images.githubusercontent.com/15127667/35474091-21166a18-0381-11e8-9269-0d084a1b8b8a.png">

**Comment by tegon** [comment]
This was fixed in version 4.4.0, please update to get the fix. Thanks!

**Comment by PolymathWhiz** [comment]
I am running the latest version of devise. Is it possible it's from the ruby version?

**Comment by PolymathWhiz** [comment]
I downgraded my ruby to 2.4.1 and it works perfectly

**Comment by tegon** [comment]
Your screenshot is showing the older version, you can see master version here https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L7. It was fixed on this PR: https://github.com/plataformatec/devise/pull/4668
So probably you don't have the version >= 4.4. How is your Gemfile.lock?

**Comment by PolymathWhiz** [comment]
oh, yeah! My gemfile.lock shows devise is running 4.3.0
