### ISSUE TITLE
Please deploy new 3-stable release for fix ruby 2.5.0 issues

### ISSUE THREAD

**Issue by halida** [plataformatec/devise#4771]
There is a grammar fix for ruby 2.5.0:
https://github.com/plataformatec/devise/commit/53957d921b01e993222def6c051901bb4cbe4be9#commitcomment-27226770

3-stable have this commit, but didn't deploy to new version, please create one to fix this, Thanks.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Like I explained in https://github.com/plataformatec/devise/pull/4749#issuecomment-356366226. 3-stable is not under maintenance anymore, so we are not going to do a new release. If you want to keep using you can point your project to the 3-stable branch.
