### ISSUE TITLE
Devise sign_in TestHelper doesn't trigger Warden after_set_user callback

### ISSUE THREAD

**Issue by userrails** [plataformatec/devise#4781]
## Environment

- Ruby **ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16] **
- Rails **Rails 4.2.7**
- Devise **3.5.10**

## Current behavior

```ruby
Warden::Manager.after_set_user except: :fetch do |user, warden, _|
  UserSession.deactivate(warden.raw_session['auth_id'])
  warden.raw_session['auth_id'] = user.activate_session(
    ip: warden.request.ip,
    user_agent: warden.request.user_agent
  )
end

# After fetching a user from the session, we check that the session is marked
# as active for that user. If it’s not we log the user out.
Warden::Manager.after_fetch do |user, warden, _|
  unless user.session_active?(warden.raw_session['auth_id'])
    warden.logout
    throw :warden, message: :unauthenticated
  end
end
```
- I have customized `Warden::Manager.after_set_user` to set server side session which I can later invalidate if user logout from the application. And it is working as expected if I login to the web application.

**problem**

- I am using `Devise::Test::ControllerHelpers` to use Devise `sign_in` method. The problem here is, this sign_in() method doesn't trigger `Warden::Manager.after_set_user` callback.
- But `Warden::Manager.after_fetch` is triggering if I put a breakpoint in both callbacks.
- I see [devise sign_in](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/sign_in_out.rb#L50) method is using `warden.set_user` method but [sign_in test helper](https://github.com/plataformatec/devise/blob/master/lib/devise/test/controller_helpers.rb#L79) is not.

## Expected behavior

- When I call `sign_in :user` in my test case, it should trigger [Warden::Manager.after_set_user](https://github.com/hassox/warden/wiki/Callbacks#after_set_user) callback.

**Comment by userrails** [comment]
> Important: you should not test Warden specific behavior (like callbacks)
> using `Devise::Test::ControllerHelpers` since it is a stub of the actual
> behavior. Such callbacks should be tested in your integration suite instead.

I have found this **Important** message in the source code: https://github.com/plataformatec/devise/blob/master/lib/devise/test/controller_helpers.rb#L23. 

But now that I have thousands of test cases relying on this behavior, if anyone can help me solve this that would be great.

**Comment by tegon** [comment]
Hello @userrails, thanks for your report.

As you noticed, we run warden in test mode, so this is an expected behavior. I'm not sure what path you should follow. You can abstract the logic to another object and test this object in isolation, or maybe create integration test as the code's comments suggest.

Thanks.
