### ISSUE TITLE
Random csrf failure with omniauthable

### ISSUE THREAD

**Issue by jean-francois-labbe** [plataformatec/devise#4801]
## Environment

- Ruby **2.5.0**
- Rails **5.1.5**
- Devise **4.4.1**

## Current behavior
I'm using `:omniauthable` with Gitlab as a provider so gem versions are:
omniauth: **1.8.1**
omniauth-gitlab: **1.0.3**
omniauth-oauth2: **1.5.0**

I currently have random success at my login attempts. When it fails I have a `Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`

here are Rails logs with a successful attempt followed by a failure just after.

```
Started GET "/users/auth/gitlab" for 127.0.0.1 at 2018-03-12 11:24:04 +0100
I, [2018-03-12T11:24:04.735698 #18853]  INFO -- omniauth: (gitlab) Request phase initiated.
Started GET "/users/auth/gitlab/callback?code=18b35ed6162ce19f24b4b48636d3708c2d6f1d3cb151d3741ca713c05c1237d9&state=5e27ef770d6241110a4e4fdd5eb477018ed48fa1fc51e31b" for 127.0.0.1 at 2018-03-12 11:24:06 +0100
I, [2018-03-12T11:24:06.785922 #18853]  INFO -- omniauth: (gitlab) Callback phase initiated.
Processing by Users::OmniauthCallbacksController#gitlab as HTML
  Parameters: {"code"=>"18b35ed6162ce19f24b4b48636d3708c2d6f1d3cb151d3741ca713c05c1237d9", "state"=>"5e27ef770d6241110a4e4fdd5eb477018ed48fa1fc51e31b"}
  User Load (2.8ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2 ORDER BY "users"."id" ASC LIMIT $3  [["provider", "gitlab"], ["uid", "2"], ["LIMIT", 1]]
  Visit Load (4.0ms)  SELECT  "visits".* FROM "visits" WHERE "visits"."visit_token" = $1 ORDER BY "visits"."id" ASC LIMIT $2  [["visit_token", "944638cb-a7b4-4cea-bcd3-7be9c861d3e6"], ["LIMIT", 1]]
  User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 425211171], ["LIMIT", 1]]
Redirected to http://localhost:3000/dashboard/index
Completed 302 Found in 60ms (ActiveRecord: 9.9ms)

Started GET "/users/auth/gitlab" for 127.0.0.1 at 2018-03-12 11:24:32 +0100
I, [2018-03-12T11:24:32.596123 #18853]  INFO -- omniauth: (gitlab) Request phase initiated.
Started GET "/users/auth/gitlab/callback?code=9f431c35c6b45e1ecfdbfb7837f4fd92ee16fbe97c629637c6064a5aafca8e6a&state=0b5cfd681574e2d766717118b5d7f8c37141b364c217bc4a" for 127.0.0.1 at 2018-03-12 11:24:34 +0100
I, [2018-03-12T11:24:34.511692 #18853]  INFO -- omniauth: (gitlab) Callback phase initiated.
E, [2018-03-12T11:24:34.515092 #18853] ERROR -- omniauth: (gitlab) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"code"=>"9f431c35c6b45e1ecfdbfb7837f4fd92ee16fbe97c629637c6064a5aafca8e6a", "state"=>"0b5cfd681574e2d766717118b5d7f8c37141b364c217bc4a"}
Redirected to http://localhost:3000/
Completed 302 Found in 3ms (ActiveRecord: 0.0ms)
```

## Expected behavior

I expect the sign in with omniauth to work everytime.

I have no idea why this is happening. 
I tried to change protect_from_forgery but didn't change anything. 
This is hard for me to debug as sometimes it's working sometimes not.

**Comment by tegon** [comment]
Hello @jean-francois-labbe, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
You can also use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by jean-francois-labbe** [comment]
I will try to provide you one.

**Comment by rafaelfranca** [comment]
Is your browser by any chance Safari?

**Comment by jean-francois-labbe** [comment]
Nope it's chrome, and I have the same issue with firefox.

I have a better understanding now. I can login into my application when doing the following:

* Go to site login page
* Clean site cookies
* Click on login with gitlab
* Authorize the login on gitlab page
* Then I'm back in my application and logged in

But if I do:

* Go to site login page
* **Clean site cookies**
* Click on login with gitlab
* Authorize the login on gitlab page
* Then I'm back in my site and logged in
* **Sign out**
* Click on login with gitlab
* Authorize the login on gitlab page
* Then I'm back on the site login page with the csrf issue.

So now I think this is an issue with cookies.
When I have no cookies it's working, but when I already have a cookie that may be invalid du to application upgrade or after a sign out then I cannot login

**Comment by jean-francois-labbe** [comment]
I have found the issue.

I had this: `<li><%= link_to 'Sign in with Gitlab', user_gitlab_omniauth_authorize_path, data: { turbolinks: 'false' } %></li>`

And by removing this `data: { turbolinks: 'false' }` I got it working as before.

What I don't understand is that it was working correctly before. Turbolinks went from **5.0.1** to **5.1.0**

Anyhow it's fixed.
