### ISSUE TITLE
Missing template layouts/devise for haml ext

### ISSUE THREAD

**Issue by rockandruby** [plataformatec/devise#4814]
ruby 2.4.1
devise 4.4.3
rails 5.1.5
In initializers/devise.rb
`Rails.application.config.to_prepare do
  Devise::RegistrationsController.layout proc { |controller| user_signed_in? ? "application" : "devise" }
  Devise::SessionsController.layout proc { |controller| user_signed_in? ? "application" : "devise" }
  # And/or Sessions, Confirmations, Unlocks, Passwords
end`
I have view/layouts/devise.html.haml but get above error.Tried all variants of adding custom layout but error the same.

**Comment by ahujasushant** [comment]
you need to manually install it.
by typing in the command, rails g isntall devise::views.
did you do?

**Comment by rockandruby** [comment]
@ahujasushant sure I did, but this generator doesn't create layout. Also it works if I user pure html or erb extensions but not haml

**Comment by rockandruby** [comment]
damn, I forgot that haml isn't native rails ext. Sorry)
