### ISSUE TITLE
recoverable feature request : multiple or possibly persistent reset tokens

### ISSUE THREAD

**Issue by stevecrozz** [plataformatec/devise#4817]
## Environment

- ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
- Rails 5.0.1
- Devise 4.2.0

## Current behavior

When users initiate the password reset flow using recoverable, the password reset token is re-generated each time. This is fine when the user reliably uses the most recent token. But we are seeing cases where users request multiple resets (possibly due to email delivery delays). And sometimes users try to use an older reset token which results in a frustrating experience and support calls.

## Expected behavior

It would be nice if some number of reset tokens could be stored, each with its own expiration so that users who arrive with a correct reset token could still complete the process as long as the given token has not expired. Alternatively, although not quite as awesome, might be to not regenerate the reset token as long as the previous one has not expired.

I could potentially volunteer myself to make this change if there's some agreement on what to do.

**Comment by tegon** [comment]
We don't do this for security reasons. Take a look at #4653 for more information.

**Comment by stevecrozz** [comment]
I took a look, but I'm not convinced. Is there any room for more discussion on this? As a starting point, I took a look at how amazon.com does password resets and they do allow you to use prior tokens when resetting your password. I didn't explore too deeply into how long they last, but you can use tokens prior to the most recent one...

**Comment by stevecrozz** [comment]
@tegon 

Sure. From reading the discussion in #4653, the security concern seems to be mainly about regenerating new tokens each time. I'm not sure what the specific concern is with that, but for the moment, if we assume that's a valid concern, then I think we can still discuss a solution where we continue to generate new tokens each time one is requested, but also accept some number of previous tokens as long as they haven't expired.

What I'm imagining is a scenario where we have some number (maybe configurable) of tokens that we store that each have their own expiration time. We continue to generate a new token when the user requests a recovery. As long as they provide one that we have that hasn't expired, then we should allow them to continue.
