### ISSUE TITLE
Controller duplicating data

### ISSUE THREAD

**Issue by ngw** [plataformatec/devise#4825]
## Environment

- Ruby 2.4.3
- Rails 5.1.4
- Devise 3.5.1

## Current behavior

First of all, I'm not sure if this is a bug or my code is the problem, I've tried to ask on Stackoverflow (https://stackoverflow.com/questions/49361613/form-for-devise-action-controller-duplicating-data) (but I didn't receive even a comment, and the behavior is definitely very odd.
I'm building a form with Elm, I'll leave the code out because I don't think it's relevant, enough to say that it submits some Json to a Devise action: I've actually checked with the browser and the Json submitted is:

    {
      "user": {
        "type":"designer",
        "role":"designer",
        "first_name":"dsfdsfsd",
        "last_name":"dsdsfds",
        "email":"dfsddfs@kdsfjfgkd",
        "password":"fdsfdfsdfds"
      }
    }

This is the action I'm sending the Json to:

    class Users::RegistrationsController < Devise::RegistrationsController
      before_action :configure_sign_up_params, only: [:create]

      def create
        puts params.inspect
        super
      end

      def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:type, :role, :first_name, :last_name])
      end
    end

And here is what I'm receiving:

    Processing by Users::RegistrationsController#create as JSON
    11:02:06 web.1     |   Parameters: {"user"=>{"type"=>"designer", "role"=>"designer", "first_name"=>"sdadas", "last_name"=>"asdasda", "email"=>"sadasad@fsdfd", "password"=>"[FILTERED]"}, "registration"=>{"user"=>{"type"=>"designer", "role"=>"designer", "first_name"=>"sdadas", "last_name"=>"asdasda", "email"=>"sadasad@fsdfd", "password"=>"[FILTERED]"}}

If I generate the Json using "regitration" : {} the duplication disappears (???)

## Expected behavior

I would expect to receive only the "user" hash as in the Json the action is receiving, it looks like there's some kind of before_filter that takes the "user" hash and duplicates it in "registration" for no real reason.

**Comment by tegon** [comment]
This is a rails behavior. It can be turned off by setting `config.wrap_parameters = false` in the initializer.

Related resources:
https://stackoverflow.com/a/27673892/3840858
http://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html
http://guides.rubyonrails.org/action_controller_overview.html#parameters
