### ISSUE TITLE
Documentation confirmation - subdomains and case insensitive emails

### ISSUE THREAD

**Issue by jufemaiz** [plataformatec/devise#4830]
## Background

We are working through the ability to get a user without worrying about the case of their email, hence necessitating the use of the `find_for_authentication` method. This is as per recommended approach (ref: https://github.com/plataformatec/devise/wiki/How-To:-Use-case-insensitive-emails )

## Environment

- Ruby 2.3.7
- Rails 4.2.1
- Devise 4.3.0

## Current behavior

Documentation at https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain suggests the following overloading of the `find_for_authentication` method:

```
# app/models/user.rb
class User < ActiveRecord::Base
  def self.find_for_authentication(warden_conditions)
    where(:email => warden_conditions[:email], :subdomain => warden_conditions[:subdomain]).first
  end
end
```

This then prevents the use of `find_for_authentication` enforcing the configuration of case_insensitive_keys and whitespace stripping through the devise configuration `config/initializers/devise.rb` (ref: https://github.com/plataformatec/devise/blob/v4.3.0/lib/devise/models/authenticatable.rb#L262 )

## Desired direction

The original documentation is approaching five years old.

* Is the original methodology still appropriate (ref: https://github.com/plataformatec/devise/wiki/How-to:-Scope-login-to-subdomain/755b0ba66dcf55edf4607aa9f3e0bf02a331c43e when it first came in)?
* If not, can I be advised on refs to when it was outdated to keep the docs up to date?

## Other notes

We have now implemented this as:

```
class User
  class << self
    def find_for_authentication(tainted_conditions)
      tainted_conditions = { subdomain: '' }.merge(tainted_conditions)
      super
    end
  end
end
```

**Comment by tegon** [comment]
Hello @jufemaiz, thanks for your report.

The Wiki is maintained by the community, which means those articles are solutions that worked for some users in the past, and like you said, they can be outdated.
I didn't understand exactly what is your question. Do you wanna know how to have case-insensitive emails, or do you wanna know how to use devise with other authentication keys (like `subdomain`)?

**Comment by jufemaiz** [comment]
Yep @lancecarlson I'd like to ensure the best practice documentation is up to date for others!

**Comment by tegon** [comment]
But why do you need to override `find_for_authentication`?

**Comment by jufemaiz** [comment]
@tegon thanks for asking. As per the original question, we are using devise with scoping based on an account subdomain, which caused issues with the find_for_authentication methodology.

**Comment by tegon** [comment]
@lancecarlson @jufemaiz I'm not sure if the snippet still works. The community maintains the wiki, so someone else wrote that code and shared because it worked for them.
If you want help on how to do this, I recommend opening a question on StackOverflow. There more people will be able to help you - personally, I've never used Devise with subdomains. 
We try to keep only issues here. 

Thank you!

**Comment by jufemaiz** [comment]
@tegon I was trying to get a confirmation so that I could update the docs…
