### ISSUE TITLE
Rails routing using devise and subdomain constraint (bis)

### ISSUE THREAD

**Issue by sowenjub** [plataformatec/devise#4839]
This is a follow-up on a [closed issue](https://github.com/plataformatec/devise/issues/4637), providing a demo app to reproduce it (see the app's [README.md](https://github.com/sowenjub/authenticated_subdomain/blob/master/README.md) for installation instructions).

## Environment

- Ruby **2.5.1**
- Rails **5.2.0.rc2**
- Devise **4.4.3**

Demo app: https://github.com/sowenjub/authenticated_subdomain

## Behavior

Mixing a subdomain constraint with devises's `authenticate` constraint should work, but doesn't.

```
Rails.application.routes.draw do
  devise_for :users
  constraints subdomain: 'admin' do
    authenticate :user, lambda { |u| u.admin? } do
      root to: 'users#index'  # => NOT OK, user is redirected to sign_in
    end
  end
  constraints subdomain: 'unauthadmin' do
    get '/users', to: 'users#index'  # => OK, proves the subdomain constraints works
  end
  authenticate :user, lambda { |u| u.admin? } do
    get '/auth_users', to: 'users#index'  # => OK, proves authenticate works when it's alone
  end
  get '/unscoped_users', to: 'users#index'  # => OK
  root to: 'home#index'
end
```

**Comment by tegon** [comment]
Hey @sowenjub, thanks for creating the sample app, it really helps us a lot.

I don't know if I did something wrong, but I tried to follow your steps but I couldn't get the error:

![authenticated-subdomain](https://user-images.githubusercontent.com/3727827/38760934-8ca396a8-3f44-11e8-834d-9fd7bae34acc.gif)

Can you point me if I did something differently?

**Comment by sowenjub** [comment]
@tegon Can you try with a different port + an incognito window?
I find that the first time I click on the top link (This link should work), I'm redirected to the sign in page, but then if I enter my credentials and sign in again, that link now works fine.
Also, from that point, if I sign out and sign back in, it still works.
But if I sign out, clear my browsing data, and sign in again, then the link stops working.

I added a sign out link to the repo. Didn't had back links, I just use the back button of the browser and reload the page just to be sure.

**Comment by sowenjub** [comment]
Hey @tegon, did you get another chance to test using the instructions above?

**Comment by tegon** [comment]
@sowenjub not yet, I've just returned from my vacations. I'll try to take a look again this week.
But by reading your last comment:
> I find that the first time I click on the top link (This link should work), I'm redirected to the sign in page, but then if I enter my credentials and sign in again, that link now works fine.

This could be a cookie-related issue, I mean, cookies are created for a specific domain, and maybe the cookie isn't valid for the other domain. (I'm justing raising an concern here, I haven't looked at this closer yet).

**Comment by sowenjub** [comment]
@tegon I think you're right, the idea crossed my mind but I haven't had a chance to test it either. You can put this issue on hold and I'll report back when I find time to test it.

**Comment by tegon** [comment]
I've tested here again and seems like that's the case.
When I access "This link should work", that's how the cookies look like:
<img width="1279" alt="screen shot 2018-05-11 at 10 03 43" src="https://user-images.githubusercontent.com/3727827/39925615-b89899d8-5502-11e8-8687-f63c935211fe.png">
When I access "This one does":
<img width="1280" alt="screen shot 2018-05-11 at 10 05 23" src="https://user-images.githubusercontent.com/3727827/39925665-dfec6366-5502-11e8-87c0-f09a63c29ecf.png">
When I access the other links:
<img width="1280" alt="screen shot 2018-05-11 at 10 06 13" src="https://user-images.githubusercontent.com/3727827/39925687-f8069494-5502-11e8-8c8f-063cd14868bf.png">

To fix this you need to create a cookie that accepts a subdomain. You can do this by creating a file named `config/initializers/session_store.rb` with the following content:
```ruby
Rails.application.config.session_store :cookie_store,
  key: '_authenticated_subdomain_session', domain: '.lvh.me'
```

Please let me know if that works for you.

**Comment by tegon** [comment]
Hello @sowenjub, did you get a chance to test this?

**Comment by sowenjub** [comment]
@tegon Yes ! Sorry, that was it, it works perfectly. Thanks again for your help.
