### ISSUE TITLE
uninitialized constant CustomFailure (NameError) on CustomFailure

### ISSUE THREAD

**Issue by dcalixto** [plataformatec/devise#4850]
after added the 
```
class CustomFailure < Devise::FailureApp
    def redirect_url
       new_user_registration_url
    end

    # You need to override respond to eliminate recall
    def respond
      if http_auth?
        http_auth
      else
        redirect
      end
    end
  end
```
and the 

```
config.warden do |manager|
    manager.failure_app = CustomFailure
  end
```

started this NameError issue

```
from /home/daniel/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise-4.4.1/lib/devise.rb:484:in `block in configure_warden!'
/home/daniel/jetx/config/initializers/devise.rb:28:in `block (2 levels) in <top (required)>': uninitialized constant CustomFailure (NameError)
```

So i tried to  require 'devise', and did not fixed either. so, someone has any hint in this issue?

## Environment

- Ruby 2.5.0
- Rails 5.1.4
- Devise 4.4.1

**Comment by mirceadaniel** [comment]
Hi. Have you managed to solve this? If so, can you please provide the solution?

**Comment by ckrampanis-vates** [comment]
i have same problem .. any idea ?

**Comment by carlosantoniodasilva** [comment]
If your custom app lives in the lib/ folder you need to require it. And make sure you stop/restart spring otherwise it won't pick up the change.

**Comment by EmanuelFirmino** [comment]
i have the same problem... I fix it moving 'CustomFailure.rb' into 'lib' directory, instead 'lib/tasks'.
