### ISSUE TITLE
Timeout based on last_sign_in

### ISSUE THREAD

**Issue by rafaellima** [plataformatec/devise#4852]
## What I'm trying to achieve
Have a timeout regardless of the user's activity.

## Current behavior

Devise makes it possible to configure a timeout, which you can set how long it is going to last via the`timeout_in` parameter. The [logic behind it](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/hooks/timeoutable.rb#L14) though uses a value called `last_access` which (I believe) is set everytime the user executes an acion on the system.

## Expected behavior

Add another attribute into the devise configuration to allow this value based on the user `last_sign_in_at` attribute, making it possible to decide which behavior we want. 

By doing it we can expect the timeout to happen regardless of the user idle timeout.

**Comment by tegon** [comment]
Hello @rafaellima, thanks for your request.
We don't have plans to support this for now, so although I know it's not ideal, you probably will have to override this code to add your custom behavior.
If this became a popular feature request, we could think about supporting in a next version.

Thank you!
