### ISSUE TITLE
Can’t log in to perform tests

### ISSUE THREAD

**Issue by M5oul** [plataformatec/devise#4855]
## Environment
- Ruby 2.4.1
- Rails 5.1.2
- Devise 4.4.3

## Current behavior
I would like to test features inside the app with MiniTest.
Do to so, I need to be able to log in the app.

After creating and confirming a user account, I tried [test helpers](https://github.com/plataformatec/devise#test-helpers), [How To: Testcontrollers](https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-(and-RSpec)), and [Warden helpers](http://www.rubydoc.info/github/hassox/warden/Warden/Test/Helpers), and my own solution:
```ruby
def login(email = "em@il", password = "password")
    post "/users/sign_in", :params => { :user => { :email => email, :password => password } }
end
```
but, none of them works.

If I try to `get` pages from within the app, I always get redirected to `/users/sign_in`.

## Expected behavior
- Be able to log in the app from tests.

**Comment by rafaelfranca** [comment]
What is the superclass of your controller?

**Comment by M5oul** [comment]
This is  `ActionDispatch::IntegrationTest`.

**Comment by rafaelfranca** [comment]
Have you tried https://github.com/plataformatec/devise#integration-tests?

**Comment by M5oul** [comment]
Yes, but I have an `NoMethodError: undefined method 'users'`.

**Comment by M5oul** [comment]
Ok, I have been able to log in with my solution.
I had an issue with something else. I don't know what it is.
Thanks anyway.
