### ISSUE TITLE
How to convert UTC DateTime to Milliseconds in Ruby on rails

### ISSUE THREAD

**Issue by kirubakaran89** [plataformatec/devise#4856]
Hi 
  How to convert UTC  DateTime to Milliseconds or ticks in Ruby on rails,below attached sample code getting UTC DateTime
date =DateTime.now.utc
# 2018-05-01 14:42:28 UTC
I want that above DateTime to milliseconds

**Comment by lancecarlson** [comment]
This is not relevant to devise or even rails specifically. A quick google search I found this:

https://stackoverflow.com/questions/13148888/how-to-get-the-current-time-as-13-digit-integer-in-ruby

```ruby
DateTime.now.strftime('%Q')
```

Not sure what the implications are for UTC, but you will have to research that yourself.
