### ISSUE TITLE
BCrypt::Errors::InvalidHash: invalid hash

### ISSUE THREAD

**Issue by thooams** [plataformatec/devise#4861]
## Environment

- Ruby **2.5.1**
- Rails **5.2.1**
- Devise **4.4.3**

I want to create a simple user into the seed file. Before this code worked. :( 

## Current behavior

    User.create!(email: 'john@doe.com', password: 'abép*éb«be', password_confirmation: 'abép*éb«be')
    =>  BCrypt::Errors::InvalidHash: invalid hash

## Expected behavior

    User.create!(email: 'john@doe.com', password: 'abép*éb«be', password_confirmation: 'abép*éb«be')
    =>  <User.....>

**Comment by zachsmith** [comment]
Same issue

* Ruby: 2.5.1
* Rails: 5.1.6
* Devise: 4.4.3

**Comment by zachsmith** [comment]
For me, this seems to have something to do with bcrypt and not devise. I haven't figured our the issue yet but have narrowed it down and what I'm seeing is not a devise bug.

**Comment by zachsmith** [comment]
My issue is related to the Fedora 28 upgrade. It is being tracked here:

https://github.com/codahale/bcrypt-ruby/issues/170

and here:

https://github.com/codahale/bcrypt-ruby/issues/165

**Comment by swobspace** [comment]
bcrypt 3.1.12 solved this issue for me on Fedora 28, ruby 2.4, rails 5.1.6.

**Comment by thooams** [comment]
Yes !

**Comment by francescor** [comment]
bcrypt 3.1.12 solves the issue in Fedora 29, too
thanks

**Comment by karlwilbur** [comment]
I had the same message with Ubuntu 20.04, Ruby 2.3.3, Rails 4.2.7.1, Bcrypt 3.1.10. I was getting the message when running `rspec`. I upgraded to Bcrypt 3.1.13 and not `rspec` runs just fine.

**Comment by him-wtag** [comment]
I am getting the issue 
`BCrypt::Errors::InvalidHash in Devise::SessionsController`
- Ruby 2.7.1
- Rails 6.0.3
- Devise 4.7.2

**Comment by him-wtag** [comment]
I am getting the issue 
`BCrypt::Errors::InvalidHash in Devise::SessionsController`

- Ruby 2.7.1
- Rails 6.0.3
- Devise 4.7.2
- Bcrypt 3.1.14
- OS : Pop OS 20.04 LTS

Help Please!

**Comment by viniciusgati** [comment]
> I am getting the issue
> `BCrypt::Errors::InvalidHash in Devise::SessionsController`
> 
> * Ruby 2.7.1
> * Rails 6.0.3
> * Devise 4.7.2
> * Bcrypt 3.1.14
> * OS : Pop OS 20.04 LTS
> 
> Help Please!

gem 'bcrypt', '~> 3.1.13' works for me

**Comment by oLeVanNinh** [comment]
For ubuntu 20.04 I get the same problem with  `Bcrypt  3.1.11` and after run `gem update bcrypt`, my problem was solved and version of `Bcrypt` now is 3.1.15

**Comment by 1990eam** [comment]
Ubuntu 20.04.1 same issue (Rails 5.2.1 Ruby 2.6.5).

Fix: setting BCrypt to 3.1.15 manually in the Gemfile and running bundle install (by default Bcrypt updates to 3.1.14 which didn't work).

**Comment by carlosantoniodasilva** [comment]
Thanks everyone. It seems clear that the issue/error is not coming from Devise itself, and apparently upgrading BCrypt normally does the trick.

If anyone is able to reproduce this consistently on Devise itself, please let us know.

**Comment by josephdpurcell** [comment]
I ran into this. I upgraded bcrypt from 3.1.11 to 3.1.16 and it resolved the error. My previous password didn't work, I had to reset it.

**Comment by ponny** [comment]
Started getting this in production for two users trying to create an account using Devise(4.8.0)/Bcrypt (3.1.16).  Don't know what they entered because it's filtered in the logs.  Any ideas what could cause it?

**Comment by ponny** [comment]
Still happening here infrequently.  4 days ago and 3 weeks ago.

**Comment by alexeevit** [comment]
I received this error today in my Github Actions pipeline. The user model has a length validation with maximum 512.

However, it perfectly works on my Macbook.

```
Failure/Error: user = build(:user, password: 'a' * 513)

     BCrypt::Errors::InvalidHash:
       invalid hash
```

```
rails (6.1.4.4)
bcrypt (3.1.16)
activemodel (6.1.4.4)
```

**Comment by bharteesahare** [comment]
If you use ruby-2.3.1 and use rails -4.2.4

You can below  command in the bash.
**bundle update bcrypt**

**Comment by karthiik2000** [comment]
ERROR["test_login_without_remembering", #<Minitest::Reporters::Suite:0x00007fdde82f5da0 @name="UsersLoginTest">, 0.15993969900000593]
 test_login_without_remembering#UsersLoginTest (0.16s)
BCrypt::Errors::InvalidHash:         BCrypt::Errors::InvalidHash: invalid hash
            app/controllers/sessions_controller.rb:6:in `create'
            test/test_helper.rb:29:in `log_in_as'
            test/integration/users_login_test.rb:43:in `block in <class:UsersLoginTest>'

please fix that issue

**Comment by pkilpo** [comment]
ubuntu 22.04
ruby 2.3.3
rails 5.0.7
bcrypt 3.1.11 nor latest 3.1.20 do not work. 

Setting database seed user with active record 5:
RAILS_ENV=production rails console
Loading production environment (Rails 5.0.7)
2.3.3 :002 > User.create!({email: 'superuser@example.com', password: '*XXXXYYYYY*', confirmed_at: DateTime.current, role: R          ole.find_by_name!('superuser'), dont_send_instructions: true})
  Role Load (0.3ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 LIMIT $2  [["name", "superuser"], ["LIMIT", 1]]
BCrypt::Errors::InvalidHash: invalid hash
        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:60:in `initialize'

        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `create'
        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/devise-4.4.3/lib/devise/encryptor.rb:11:in `digest'
        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/devise-4.4.3/lib/devise/models/database_authenticatable.rb:167:in `pa          ssword_digest'
        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/devise-4.4.3/lib/devise/models/database_authenticatable.rb:47:in `pas          sword='
        from /home/xxx-sso/.rvm/gems/ruby-2.3.3/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:46:in `pub          lic_send'
