### ISSUE TITLE
How to add another parameter to validate a user?

### ISSUE THREAD

**Issue by newfylox** [plataformatec/devise#4862]
Hi guys,

I'm looking for a simple solution to add another parameter with `email` to register a user or find a user. Right now `find_resource` is only using `email` but I would like to do something like this
```ruby
where(email: my_email, my_param: my_other_param)
```
so it would be a `where` clause on `email` AND `my_param` for every calls (register, login, logout, etc.)

I don't want to override all the controllers or copy a whole file from your gem because I want to be sure that every time I update your gem, I stay up to date.

Thanks!

**Comment by tegon** [comment]
I didn't understand exactly what you need to do, but it seems like you're looking to override `#find_for_authentication` https://github.com/plataformatec/devise/blob/c9a2d0654e9fc1aaebe6f99ef6fbc55c55a91fdd/lib/devise/models/authenticatable.rb#L271
