### ISSUE TITLE
Error 500 for ruby 2.5 .

### ISSUE THREAD

**Issue by AbhijithRavindran** [plataformatec/devise#4865]
- Ruby **[2.5.0]**
- Rails **[5.2]**
- Devise Latest

Log:

- Showing syntax error in sessions controller.
- 500 Error

Result:

- Redirected to error page.

Solution:
Revert back to ruby 2.4.2

What exactly is the issue ? Does devise support ruby 2.5 ??

**Comment by nashby** [comment]
Ruby 2.5 is supported.  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
