### ISSUE TITLE
LoadError in Devise::RegistrationsController#create 

### ISSUE THREAD

**Issue by ashutoshpith** [plataformatec/devise#4866]
cannot load such file -- bcrypt_ext

    raise Bootsnap::LoadPathCac

he::CoreExt.make_load_error(path)
  rescue Bootsnap::LoadPathCache::ReturnFalse
    return false
  rescue Bootsnap::LoadPathCache::FallbackScan

![screenshot 92](https://user-images.githubusercontent.com/31169310/39699959-1bfecf2a-5219-11e8-84de-a4046af19a8b.png)

**Comment by tegon** [comment]
Hello @ashutoshpith, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
You can also use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by ashutoshpith** [comment]
I'm using rails 5.2 nd on applying devise it raise an error for bcrypt_ext ...after changing version of bcrypt ...It arise for all for other project to...is devise compatible with rails 5.2 or not??

**Comment by tegon** [comment]
Yep, I've just tested with a newly created Rails 5.2 application and it worked, that's why I asked for an application that reproduces the issue. Here's the one I created:
[test-5.2.zip](https://github.com/plataformatec/devise/files/2002433/test-5.2.zip)

**Comment by ashutoshpith** [comment]
Here is the fie which creating the issuse
[Socop.zip](https://github.com/plataformatec/devise/files/2006541/Socop.zip)

**Comment by tegon** [comment]
I've tested here and haven't got any errors. Here's a gif of a new signup:
![load-error](https://user-images.githubusercontent.com/3727827/40085527-2cb72494-5871-11e8-8963-60d9b8c61c60.gif)
This seems like a gem installation issue. One thing that I had to change in your application is that the `.ruby-version` file had one version (`2.2.6`) and `Gemfile` had another (`2.3.3`). I've changed them to use the same version. 
I suggest you try to do that and maybe purge your gems and do a clean install.

**Comment by ashutoshpith** [comment]
I've made a new app and have the same .ruby-version and gemfile i.e ( 2.3.3 ) but it again shows the same error cause that "cannot load such file -- bcrypt_ext"
[Arsenal-1.0.0.zip](https://github.com/plataformatec/devise/files/2006992/Arsenal-1.0.0.zip)

**Comment by ashutoshpith** [comment]
I did reinstall the ruby on rails but it causes the same error...I used devise in lower version of rails and it works fine

**Comment by ashutoshpith** [comment]
![screenshot 100](https://user-images.githubusercontent.com/31169310/40113399-f9ea2dd4-5926-11e8-9b98-9eac7d5d625a.png)
every time it shows devise error and cannot load bcrypt_ext error

**Comment by tegon** [comment]
Seems like a bcrypt issue with Windows. I did a search here and found somethings:

https://github.com/codahale/bcrypt-ruby/issues/142
https://github.com/codahale/bcrypt-ruby/issues/128
https://stackoverflow.com/questions/41621029/cannot-load-such-file-bcrypt-ext?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
https://github.com/codahale/bcrypt-ruby/issues/149
https://stackoverflow.com/questions/46434362/cannot-load-such-file-bcrypt-ext-loaderror-on-windows?rq=1
