### ISSUE TITLE
Undefined callback

### ISSUE THREAD

**Issue by ceochronos** [plataformatec/devise#4867]
## Environment

- Ruby **2.5.0**
- Rails **5.1.6**
- Devise **4.4.3**

## Current behavior

After upgrading from rails 4.2.3 with devise 4.2.1 to rails 5.1.6 with devise 4.4.3 app does not start in development mode.

log says:

```
/usr/local/rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:712:in `block (2 levels) in skip_callback': After create callback :send_on_create_confirmation_instructions has not been defined (ArgumentError)
```

User.rb
```
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  # ...

  skip_callback :create, :after, :send_on_create_confirmation_instructions
  skip_callback :update, :after, :send_password_change_notification

  # ...
```

## Expected behavior

Application should start or print deprecated messages.

**Comment by tegon** [comment]
Seems like your application was falling into the `mongoid` version here: https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L55

For `active record` the callback should be `after_commit`. Previously, we verified this using `respond_to?(:after_commit)`, but we had an issue where the `paperclip` gem was defining this callback for `mongoid`, so we changed the conditional on #4302 (v4.4.0) and #4752 (v4.4.1).

You can also skip the callback by calling the `skip_confirmation_notification!` method https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L161-L163
