### ISSUE TITLE
Is it necessary to return an email as well in the Headers?

### ISSUE THREAD

**Issue by gotoAndBliss** [plataformatec/devise#4870]
Just a general philosophical question, but I see it's required to send both the token *and* the email.

Why the email as well? Wouldn't the token be unique for every class item?

**Comment by tegon** [comment]
Can you be more specific? Are you talking about password recovery?

**Comment by tegon** [comment]
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!
