### ISSUE TITLE
bypass_sign_in without active_for_authentication? callback

### ISSUE THREAD

**Issue by vishalTatvaSoft** [plataformatec/devise#4877]
## Environment

- Ruby **[ruby 2.4.2p198]**
- Rails **[5.1.4]**
- Devise **[4.3.0]**

## Current behavior

I have functionality of inactive account in my application for handling this i override `active_for_authentication?` method as below

    def active_for_authentication?
      super && activated?
    end
    
But In my application super admin can also directly login in to other user account, whether it is active or not active 

    bypass_sign_in(User.find(resource.id))

I used above method for by pass sign in, it allows me to directly sign in only for activated user, when i login for non activated user it goes in infinite loop .

## Expected behavior

Any solutions to over come this issue or don't run `active_for_authentication?` callback when `bypass_sign_in`?

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!

**Comment by Kani999** [comment]
> ## Environment
> * Ruby **[ruby 2.4.2p198]**
> * Rails **[5.1.4]**
> * Devise **[4.3.0]**
> 
> ## Current behavior
> I have functionality of inactive account in my application for handling this i override `active_for_authentication?` method as below
> 
> ```
> def active_for_authentication?
>   super && activated?
> end
> ```
> But In my application super admin can also directly login in to other user account, whether it is active or not active
> 
> ```
> bypass_sign_in(User.find(resource.id))
> ```
> I used above method for by pass sign in, it allows me to directly sign in only for activated user, when i login for non activated user it goes in infinite loop .
> 
> ## Expected behavior
> Any solutions to over come this issue or don't run `active_for_authentication?` callback when `bypass_sign_in`?

@vishalTatvaSoft 
Did you resolve this issue?

**Comment by vishalTatvaSoft** [comment]
@Kani999  Yes i did

**Comment by aksharj** [comment]
@vishalTatvaSoft can you please share your solution?
