### ISSUE TITLE
Unexpected password  confirmation validator behaviour

### ISSUE THREAD

**Issue by gullhead** [plataformatec/devise#4881]
## Environment

- Ruby **[ruby 2.5.1p57 (2018-03-29 revision 63029)]**
- Rails **[5.2.0]**
- Devise **[4.4.3]**

## Current behavior

While regestering  submit password and password  confirmation fields with blank values password  confirmation doesn't show 'can't be blank' error

## Expected behavior
Expected to get the same error as on main password field.

![failures_test_user_with_blank_fields](https://user-images.githubusercontent.com/39587548/40539332-19c264bc-601d-11e8-81b1-fc7db72d98b8.png)

**Comment by tegon** [comment]
We use Rails [`validates_confirmation_of` validator](https://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_confirmation_of) and this is its default behavior.
IMO, it's ok to keep as it is, by the time you fill the `password` field you'll get a `can't be blank` error for `password_confirmation` too.
