### ISSUE TITLE
Any chance for a 3.5.11 release?

### ISSUE THREAD

**Issue by jagthedrummer** [plataformatec/devise#4883]
Hey y'all, I was just hoping we might see a release for 3.5.11 to pick up some bug fixes that are already in the 3-stable branch. Thanks in advance!

## Environment

- Ruby 2.5.1
- Rails 4.2.10
- Devise 3.5.10

## Current behavior

Syntax errors that were fixed in the 3-stable branch here: https://github.com/plataformatec/devise/commit/bddf051bfb4213114a3531708ccd68729c4ecef9

## Expected behavior

No syntax errors.

**Comment by tegon** [comment]
Version 3 is not under maintenance anymore. We accepted the patch so it's possible to install it from GitHub but we don't intend to release a version for it. https://github.com/plataformatec/devise/pull/4749#issuecomment-356366226
