### ISSUE TITLE
Omniauth Facebook example

### ISSUE THREAD

**Issue by clst** [plataformatec/devise#4890]
The wiki here: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#facebook-example

The example uses: `if @user.persisted?` but the example code in the model uses `where(provider: auth.provider, uid: auth.uid).first_or_create`. That way the `@user` is always inserted.

Was the intended function `first_or_initialize`? Or am I missing something?  
That confused me a bit. The guide is great and really easy to follow otherwise! :+1:

**Comment by tegon** [comment]
Hello @clst,

The wiki is maintained by the community, so I'm not sure if the code is correct or not. If it's wrong, feel free to update it with the right instructions. Although `#first_or_create` can fail if validations don't pass.

Thank you!
