### ISSUE TITLE
Incorrect HTTP status in log files with devise 4.4.1

### ISSUE THREAD

**Issue by FX-HAO** [plataformatec/devise#4896]
## Environment

- Ruby **[2.4.1]**
- Rails **[5.1.4]**
- Devise **[4.4.1]**

## Current behavior

I upgraded my gems several weeks ago. I just typed `bundle upgrade` unconsciously. Then I found that when I raised an uncaught error, `Completed 401 Unauthorized` appeared in log files, it should be `Completed 500 Internal Server Error`. But the HTTP status client received is the correct `500 Internal Server Error`. I downgraded the gems one by one. Finally I found that when I downgraded devise to the original `4.3.0`, the problem goes away. And when I upgraded it to `4.4.1`, the problem appeared.
## Expected behavior

Instead of `Completed 401 Unauthorized`, it should be `Completed 500 Internal Server Error` in log files when errors occur.

**Comment by FX-HAO** [comment]
And I can reproduce the problem in a new Rails program.

**Comment by feliperenan** [comment]
Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.

**Comment by FX-HAO** [comment]
I created a new program, which only includes `devise 4.4.1`.
```
git clone git@github.com:FX-HAO/devise_demo.git
cd devise_demo
bin/rails server
```
Then run `curl 127.0.0.1:3000`, you will see `Completed 401 Unauthorized` in the console.
Honestly, it's a serious bug.

**Comment by tegon** [comment]
@FX-HAO This was broken in https://github.com/plataformatec/devise/pull/4375, but it was reversed in  [4.4.2](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#442---2018-03-15).
If you update it's going to work.
