### ISSUE TITLE
No route matches {:controller=>"devise/welcome"} from issue 471

### ISSUE THREAD

**Issue by fcioffi** [plataformatec/devise#490]
Hi guys,

I'm developing an application and i use devise :D but I've found a bug (maybe)

Created a model User with devise and views
Created a controller welcome with standard action index

Inserted this code in application.html.erb:
<%= link_to t('Home'), :controller => "welcome" %>

Inserted this in ApplicationController:
before_filter :authenticate_user!

When I try to navigate in my app with browser I have this error:
No route matches {:controller=>"devise/welcome"}

Temporary solution for me is to change code in view with:
<%= link_to t('Home'), :controller => "/welcome" %>

**Comment by zirexba** [comment]
I also fix the issue putting '/' in front of controller name sample:  '/single'
