### ISSUE TITLE
Add header in devise_mail

### ISSUE THREAD

**Issue by pcmanprogrammeur** [plataformatec/devise#4901]
Hi all,

I want to add a header when i send a devise_mail but it does not work :

```
opts["X-Mailin-Tag"] = "registration"
devise_mail(record, :registration, opts)
```
The problem is that the X-Mailin-Tag is not send.

Do you have any idea to do this please ?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
