### ISSUE TITLE
Any plans on releasing new 3.x version to rubygems?

### ISSUE THREAD

**Issue by vfonic** [plataformatec/devise#4907]
I just updated my app to ruby 2.5 and found out there's an issue when using ruby 2.5 and devise 3.x. I've updated to the latest available 3.x version `3.5.10`, but the issue is still there.

I see there's a fix available on `3-stable` branch. Are there any plans to have these fixes pushed to rubygems?

Thanks! ❤️

**Comment by rafaelfranca** [comment]
No. The version 3 is not under maintenance anymore. https://github.com/plataformatec/devise/pull/4749#issuecomment-356366226

**Comment by vfonic** [comment]
Thanks for reply. I'm just curious why would you backport the fix (it's on `3-stable` branch right now), but there's no release version v3. Is this a common approach usually?
