### ISSUE TITLE
rails API - blank page rendered on sign in page

### ISSUE THREAD

**Issue by jacek213** [plataformatec/devise#4922]
## Environment

- Ruby 2.5.1
- Rails 5.1.6
- Devise 4.4.3

## Current behavior
Issue happens when using rails in api mode.
After creating a model and going to /users/sign_in page a blank page is returned from server, instead of login form.

No error is thrown. If this is by design, there should be thrown to inform the developer, that devise views do not work when in api mode.

I'm using a rails in api mode and need only a single devise view for the sign in page to login into rails admin. Can that be achieved?

**Comment by rrs94** [comment]
Hi, I don't think this is an issue with devise, the idea of using rails in api mode is to remove the view mode, if you want to have some views in your application along with some api functionality, [this](https://stackoverflow.com/questions/38366501/rails-5-api-only-app-with-home-page) post may have the answer your looking for.

**Comment by tegon** [comment]
Hey @jacek213, like @rrs94 said, Rails API is not meant to be used with HTML views.
You can probably do something to work around it, but it's not a devise issue, so I'm going to close this.
Thanks!
