### ISSUE TITLE
Missing comma at end of line 19 in views/devise/registrations/edit.html.erb

### ISSUE THREAD

**Issue by ckashby** [plataformatec/devise#4931]
<%= f.input :password,
                        hint: "leave it blank if you don't want to change it",
                        required: false   ## , ## missing ##

**Comment by colinross** [comment]
I believe he is referencing https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/lib/generators/templates/simple_form_for/registrations/edit.html.erb#L15
