### ISSUE TITLE
wrong number of arguments (given 10, expected 2) 

### ISSUE THREAD

**Issue by hamzaaltaf** [plataformatec/devise#4963]
devise (4.2.0) lib/devise/models/authenticatable.rb:228:in `serialize_from_session'
## Environment

- Ruby 2.3.3
- Rails 4.2
- Devise 4.2.0

This is the error I am getting , someone please help, I have looked everywhere for the solution but cant find one

**Comment by sivagollapalli** [comment]
@hamzaaltaf Could you provide an example that reproduces this issue?

**Comment by gporpino** [comment]
I have the same problem. 

I just installed devise gem and try to login user.
