### ISSUE TITLE
Easy to accidentally log plaintext passwords

### ISSUE THREAD

**Issue by JacobEvelyn** [plataformatec/devise#4967]
## Environment

- Ruby **2.5.1**
- Rails **5.2.1**
- Devise **4.5.0**

## Current behavior

If I override Devise controllers with this behavior:

```ruby
# routes.rb
Rails.application.routes.draw do
  devise_for :users, module: :devise_override
  ...
```

```ruby
# devise_override/sessions_controller.rb
module DeviseOverride
  class SessionsController < Devise::SessionsController
    before_action :new_before_action, only: [:new]

    private

    def new_before_action
      # Our app wants some param to be present, maybe for example
      # a `:redirect_to` param that we can use on successful sign-in.
      if !params[:some_param]
        redirect_to request.params.merge(some_param: true)
      end
    end
  end
end
```

Then if a `:database_authenticatable` user enters the wrong password while trying to log in, the `POST create` action will render `new` but this code will redirect them to `new` with all of the params, *including their plaintext username and password*, now as a part of the URL. That in turn makes it easy for this URL to end up in server logs, as well as third-party tools like Google Analytics, etc.

## Expected behavior

I understand that a developer ideally would not write code that does something like this, but Devise could also help by making it more difficult to make this mistake. For this reason, I'm a bit surprised that Devise doesn't filter out parameters in `Rails.application.config.filter_parameters` from `params` before rendering the `new` page.

Would there be interest in making that behavior change (something like in `database_authenticatable.rb`, once the password comparison is made it's deleted from `params`), possibly under an optional configuration option? Or is this considered outside of Devise's scope?

**Comment by rafaelfranca** [comment]
Thank you for the issue.

This is outside the scope of devise. This is a programming error. You should not send your password in a get request as parameters. Devise can't protect you from doing that. You must be aware of the security implication of the code you write. We provide people safe defaults, but if you go outside of those defaults you are in your own.

**Comment by honigc** [comment]
@rafaelfranca The before_action that makes the problematic redirect is attached to the `new` action, which is a GET. It makes complete sense that programmers need to be careful not to send passwords as part of GET requests, but I think the issue being described is that the password is _already in the params of a GET request_, as proven by the fact that it's available in params in a before_action on a GET request.

If I were a programmer unfamiliar with the internals of Devise, I could see myself being surprised that, after a failed login, the `GET new` action has access to the exact same params that were originally sent from the end user to the `POST create` action. Redirects in Rails do not preserve params like this, and it's not immediately clear from Devise docs that this flow will behave differently.

While Devise clearly can't protect programmers from themselves all the time, this seems like a case in which a mistake can be made even by a careful programmer, and it might be reasonable for Devise to help prevent that. Maybe just adding something to the docs would be enough.
