### ISSUE TITLE
Security issue with translations at login

### ISSUE THREAD

**Issue by gloaec** [plataformatec/devise#4972]
## Environment

- Ruby **2.3.1**
- Rails **5.2.1**
- Devise **4.5.0**

## Current behavior

Just noticed that there is 2 similar error messages thrown on failed login attempt :

- `devise.failure.invalid: "Invalid %{authentication_keys} or password."`
- `devise.failure.not_found_in_database: "Invalid %{authentication_keys} or password."`

But in french for instance, the two messages are different : 

- `devise.failure.invalid: "Email ou mot de passe incorrect."`
- `devise.failure.not_found_in_database: "Email ou mot de passe invalide."`

I also noticed that the error that is thrown on failed login depends on the field that is wrong :

    user = users(:valid)
    user.skip_confirmation!
    user.save!

    post api_sign_in_url, params: {
      user: {
        login: "good_login",
        password: "wrong_password",
      }
    }
    assert_response :unauthorized
    assert_equal json_response['error'], I18n.t(:"devise.failure.invalid")

    post api_sign_in_url, params: {
      user: {
        login: "wrong_login",
        password: "good_password",
      }
    }
    assert_response :unauthorized
    assert_equal json_response['error'], I18n.t(:"devise.failure.not_found_in_database")

This behavior, depending on the language that is used, gives the user the possibility to guess part of the credentials that exist in the database. Therefore, I think this might be a security issue.

## Expected behavior

The message thrown on failed login attempt should be the same, regardless of the information that is correct in the login form. The message `not_found_in_database` should not exist.

**Comment by gloaec** [comment]
I guess i have to use the `paranoid` mode  to get rid of this behavior :

    config.paranoid = true

Then, I just think it should be the default setting.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Yes, you need to use the paranoid mode if that is what you want. We can't change the default easily given people may be relying on that behavior.
