### ISSUE TITLE
Add Ruby 2.5.0 syntax fix to an older version of devise

### ISSUE THREAD

**Issue by vlatkapavisic** [plataformatec/devise#4976]
## Environment

- Ruby **[2.5.3]**
- Rails **[4.2.7]**
- Devise **[3.5.10]**

## Issue

Hello, I'm doing an upgrade of Ruby to 2.5.3 because of a security issue. The devise version used in my app (3.5.10) has a syntax error when used with Ruby 2.5.3 : https://github.com/plataformatec/devise/commit/1009096172f2cbc86bcd54d053c89a09be67fb9f

As bumping Ruby and Devise at the same time is a bit risky, I thought of forking devise 3.5.10. 
But that's not a long-term solution and I'd have to upgrade devise at some point but I have other dependency priorities currently. 

Is it possible to make a PR that fixes this syntax error for devise 3.5.10?

Thanks!

**Comment by tegon** [comment]
Version 3 is not under maintenance anymore. The commit was, however, [merged](https://github.com/plataformatec/devise/pull/4749) at the `3-stable` branch, so you can change your Gemfile to use it directly from GitHub and it should work.
```ruby
gem 'devise', github: 'plataformatec/devise', branch: '3-stable'
```
