### ISSUE TITLE
uninitialized constant Unlock when unlocking account from email

### ISSUE THREAD

**Issue by adrianDY** [plataformatec/devise#4978]
## Environment

- Ruby **1.9.3**
- Rails **3.2.17**
- Devise **2.2.7**

## Current behavior
When a user is locked out as a result of X failed attempts, they receive an email with a link to reset their password. The link is generated ` unlock_url(@resource, :unlock_token => @resource.unlock_token) %>`
Clicking on the link leads to the following page `http://example.com/users/unlock?unlock_token=TOKEN` but shows this error:

> NameError in Devise::UnlocksController#show
> uninitialized constant Unlock
> Rails.root: /Users/user/workspace/adm-server
> 
> Application Trace | Framework Trace | Full Trace
> config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'
> 

## Expected behavior

The user will unlock their account. This has been the case in the past. Recently it stopped working, we are not sure why

**Comment by tegon** [comment]
Hi @adrianDY, thanks for the issue.

This looks like an autoload issue - ruby is not finding the `Unlock` constant. This is more likely to be related to your environment. Also, we haven't made any updates to version `2.*` (it's not supported anymore).
If you can send us a sample application that reproduces this issue in the latest version we'll definitely look into it.

Thanks.
