### ISSUE TITLE
Use the EMAIL_REGEXP provided by Ruby for email validation

### ISSUE THREAD

**Issue by collimarco** [plataformatec/devise#4986]
Currently Devise has a very basic email validation that only checks for the existence of `@`.

This creates unexpected errors when you export / sync your data with other services.

The **Ruby standard library** provides a regexp for email validation which is based on **RFC6068**.

I think that Devise should use that as the default regex:

```
config.email_regexp = URI::MailTo::EMAIL_REGEXP
```

**Comment by rafaelfranca** [comment]
Thank you for the issue.

While it may make sense this also is a change in behavior that we think it is not worth. Even that regular expression is partial and may not work for some cases so we prefer to keep the current regexp as the default.

Also see https://github.com/plataformatec/devise/issues/4980

**Comment by uqbaxcorebit** [comment]
@collimarco thanks!
