### ISSUE TITLE
When make redirect in regstertion controller not working 

### ISSUE THREAD

**Issue by mr3abd** [plataformatec/devise#4990]
i try to use 

`sign_in_and_redirect phone_verifications_path`

and use 

`redirect_to phone_verifications_path`

both not working 

I want to make redirect when user make an account redirect to a verification page 

how to make a redirect in controller devise

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!

**Comment by mr3abd** [comment]
@tegon  

but that issue ! 

not  say how to do it 

it's not working !!!! 
as that issue !

**Comment by tegon** [comment]
Ok, it looked like you're asking for help on how to do it.

Either way it's not clear what the issue is or how you're calling that method (which Rails/Ruby/Devise versions you're using, if you're overhang a Devise controller and so on). I'm reopening the issue but you have to provide us more information on how to reproduce the issue, or a sample application so that we can understand better what's happening.

**Comment by mr3abd** [comment]
Ok , 
in ` Devise::RegistrationsController`

when put 
 ```
 def create
    super
    if @host.save
     redirect_to phone_verifications_path
     return
   end
  end
```

I see error 
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

and I use return in my code 

and when making my code 

I've same issue have same message error

**Comment by tegon** [comment]
So, to be clear, you want to redirect to `phone_verifications_path` after a signup, right?
If that's the case you have to override the `#after_sign_up_path_for` method:
```ruby
def after_sign_up_path_for(_resource)
  phone_verifications_path
end

**Comment by mr3abd** [comment]
Thanks :)
