### ISSUE TITLE
Old email in after_confirmation hook when reconfirming

### ISSUE THREAD

**Issue by matthias-g** [plataformatec/devise#4994]
After confirming a user the [`after_confirmation`](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L329) hook is called. When using `reconfirmable` this method is also called after a new email has been confirmed. In such a case it would be useful to get access to the old and new email in the  `after_confirmation` hook to allow for additional logic.

What do you think of adding parameters `new_email, old_email` to `after_confirmation`?
When confirming an updated email these parameters would be set to the new and the old email and when performing the first confirmation `old_email` could be nil.

Maybe `new_email` can also be left out as it is redundant because it can be accessed through `self.email`.

It seems to me like a small change without effects on backward compatiblity. If you agree to the change, I would submit a PR.

**Comment by tegon** [comment]
Hello @matthias-g, can you explain better what's your use case for this?

I think it might be possible to use [`#saved_changes`](
https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-saved_changes) or [`#previous_changes`](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-previous_changes) to achieve what you want.

**Comment by matthias-g** [comment]
My use case is that I have two models (`User` for users and `Subscription` for newsletter subscriptions) which both store email addresses. They are independent in the sense that for one email address a user can exist without a subscription or a subscription without a user. However, when both exist and a user changes their email address, a subscription for the same email address should be changed as well.

I found that `around_update` and `self.email_was if self.email_changed?` can also be used instead of the `after_confirmation` hook. So, I don't see a need for the change anymore.

Thank you for the hints!
