### ISSUE TITLE
Could not find generator 'devise:install'.

### ISSUE THREAD

**Issue by devijonnalagadda** [plataformatec/devise#5004]
I have included gem 'devise' in my gem file. I ran bundle install The devise was installed successfully but when i executing rails g devise:install

It's generating an error as Could not find generator 'devise:install'. Maybe you meant 'test_unit:job', 'assets' or 'generator' Run rails generate --help for more options.

I tried many solutions but nothing worked for me.

I have tried spring stop before rails g devise:install and also tried to delete gemfile.lock.
When I delete gemfile.lock, bundle install is giving error
bundle install
Traceback (most recent call last):
	3: from /Users/devi/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
	2: from /Users/devi/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	1: from /Users/devi/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
/Users/devi/.rvm/gems/ruby-2.5.3/bin/bundle:23:in `load': cannot load such file -- /Users/devi/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle (LoadError)
Someone help me out from this problem

**Comment by tegon** [comment]
This looks like a local installation of bundler/devise issue. Specially if you can't run bundle install now.
I'd say to check your rvm installation - maybe do it again.

Also, please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
