### ISSUE TITLE
"-" (or "_") not included in link by some email clients

### ISSUE THREAD

**Issue by rymai** [plataformatec/devise#501]
Hey,

We had this problem some times today:

when the last character of a generated token is "-" (dash) or "_" (underscore), some email clients don't include those chars in the links generated (in text/plain emails, of course).

So, I think it would be safer not to include "-", "+", "=", "_", "/" at all in Devise.friendly_token.

I did a commit if you want to check it out: http://github.com/rymai/devise/commit/1deb8ea58cb75a9590b036a29c0c535783d8db66

Thanks

**Comment by vincentwoo** [comment]
I just saw a password reset token issued with a dash at the end. Can we reopen this issue?
