### ISSUE TITLE
allow_params_authentication! authenticates the user too

### ISSUE THREAD

**Issue by abdelbk** [plataformatec/devise#5013]
I'm facing the same issue described here https://github.com/plataformatec/devise/issues/4285.

I'm running the 4.5.0 of Devise.

Basically, the user is authenticated even when overriding the create method. I don't know if it's the intended behavior, but allow_params_authentication! prevents any authentication customizations.

I can skip this action, but I do believe that there is a deeper issue. The allow_params_authentication! does more than what its name describes.

**Comment by abdelbk** [comment]
My code is roughly similar to this

```ruby
class SessionsController < Devise::SessionsController
  def create
    # Rails.logger.info user_signed_in? returns true before running the create method
    # Custom authentication logic which gets the user by email and verify the password
  end
end
```
The issue is that the current_user is set before entering the `create` method. So to debug, I listed all the before_action callbacks which are ran before the `create` method. I found that the `allow_params_authentication!` causes the authentication of the user. I can't tell you why because, as you said, it just sets an env variable.

Adding `skip_before_action allow_params_authentication!` makes the issue disappear.

I hope I've been clear.

**Comment by abdelbk** [comment]
Thank you for your response. The issue is also discussed here https://github.com/plataformatec/devise/issues/4951. It's all clear now.

**Comment by JanBussieck** [comment]
Is someone already working on this? If not I'm happy to open an PR in the next couple of days.

**Comment by tegon** [comment]
@JanBussieck Not yet, feel free to grab it.

**Comment by vincentwoo** [comment]
yo @tegon are you gonna fix this

**Comment by mracos** [comment]
Closed via https://github.com/plataformatec/devise/commit/4be9389dcb791b063825b4996df8d04cbf7e0e89

**Comment by jtjobe** [comment]
I see that a PR has been made to fix this issue a while ago...but it has not been merged into master....but rather to branch `5-rc` which I assume is a v5 release candidate?

Any ideas when that branch / v5 might be released?
