### ISSUE TITLE
The order when encrypted password is updated is wrong and needs to be fixed

### ISSUE THREAD

**Issue by krtschmr** [plataformatec/devise#5016]
```
[12] pry(main)> user.valid_password?('12345678')
=> true
[13] pry(main)> user.password = "aaaaa"
[14] pry(main)> user.valid_password?('12345678')
=> false
```

this is broken behavior and a wrong chain of events.

the fix would be easy as following

```
def password=(new_password)
    @password = new_password
  end

  before_save :set_encrypted_password, if: ->{ password.present? }

  def set_encrypted_password
    self.encrypted_password = password_digest(@password)
  end

```

resulting in 
```

[2] pry(main)> user.valid_password?('12345678') => true
[3] pry(main)> user.password = "aaaaaaaa"
[4] pry(main)> user.valid_password?('12345678') => true
[5] pry(main)> user.save
[6] pry(main)> user.valid_password?('12345678') => false
[7] pry(main)> user.valid_password?('aaaaaaaa') => true



```

**Comment by tegon** [comment]
@krtschmr Can you explain why this is the wrong behavior? The way I see it, it looks ok: you changed the password so it's not valid anymore.

If this is causing weird behavior in your application it would be good to share what you're trying to do.

Thanks.

**Comment by krtschmr** [comment]
`update_with_password` won't work on the password itself. that's clearly a bug, isn't?

**Comment by tegon** [comment]
I don't get it. If you changed the password, it will consider the new one as the current password.
Why would you want to change the password and then later try to update the password using the old one?

Just to make sure we are on the same page, you're saying that the following should work, right?
```ruby
irb(main):002:0> u = User.first
  User Load (1.9ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<User id: 2, email: "bruce@wayne.com", created_at: "2019-01-30 12:50:45", updated_at: "2019-01-30 13:03:57">
irb(main):003:0> u.valid_password?("123123")
=> true
irb(main):004:0> u.password = "123456"
=> "123456"
irb(main):005:0> u.update_with_password(current_password: "123123", password: "abcdefg")
=> false
````

Whereas in order to work, the `current_password` should be `123456` (changed in line 3). Is that correct?

**Comment by krtschmr** [comment]
i'll recheck an let you know. initially i made my own `upate_with_password` method as i wasn't aware of that one. maybe my monkeypatching killed the behavior of the real one.

**Comment by theshashiverma** [comment]
@krtschmr @tegon @brynary @indirect @lancecarlson  please have  a look on this https://github.com/plataformatec/devise/issues/5017

**Comment by tegon** [comment]
@krtschmr Were you able to check this out again?

**Comment by krtschmr** [comment]
@tegon  i most likely monkey patched my devise to death and caused sideeffect or so. it's working right now. i'll close this.
