### ISSUE TITLE
Authentication issue with spree

### ISSUE THREAD

**Issue by theshashiverma** [plataformatec/devise#5020]
I am creating an admin template and I am giving an e-commerce section in the template. Firstly I build the project using ROR then I add auth using Devise and now I have added the e-commerce section using Spree. And for that, I Followed https://github.com/spree/spree
and when I use this command `rails g spree:auth:install` it removes all the config settings of devise.rb that I have made for the devise (i followed this for devise setup https://www.sitepoint.com/devise-authentication-in-depth/) and remains only one line `Devise.secret_key = " key value "`
This is what I have done till now.
Now I login to my Template using devise and then I go to the spree and then I create another user there in spree by login link and I get successfully login and when I log out from the spree it log me out through my template also and the login page of my template is shown, I know its same path for both the logout , but how can i differentiate it..? and when I am logging in spree as user , i get logged in but it flash message "Authorization failed"
Please help me, Thank you

**Comment by theshashiverma** [comment]
Can anyone response on this ??

**Comment by tegon** [comment]
Hello @theshashiverma,

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
