### ISSUE TITLE
devise allow wrong email id to sign up(abc@def).

### ISSUE THREAD

**Issue by theshashiverma** [plataformatec/devise#5023]
## Environment

- Ruby **[2.3.8]**
- Rails **[5.2.2]**
- Devise **[4.6.0]**

hello,

So when I use `abc@def` email address to signup, It gets signed up. But, how this could be possible? Maybe I am wrong. Thank you.

## Edit

I just checked the gorails.com website, and tried to signup with this email id abc@def and I successfully signed up. But it's not a proper email id. Please enlighten me.

**Comment by jmstfv** [comment]
Default email regex that is used in Devise doesn't cover all cases. (See #3820, #4268). To quote a line from the config file:

> It simply asserts that one (and only one) @ exists in the given string.

 If you want to allow valid email addresses, change `config.email_regexp` in config/initializers/devise.rb to:
  `config.email_regexp = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i`

**Comment by feliperenan** [comment]
Hello @theshashiverma, thanks for the issue report. 

Yeah, the regex used by Devise doesn't cover all cases - it's just a regex with a minimal validation. If you want something more complex you should change it in your application.

Thanks :)
