### ISSUE TITLE
Why are we assigning the unhashed password?

### ISSUE THREAD

**Issue by salqadri** [plataformatec/devise#5024]
https://github.com/plataformatec/devise/blob/d1571627b78399b55b76c400a78c4a3f367dad2c/lib/devise/models/database_authenticatable.rb#L62

What's going on here exactly? Why do we have @password anyway, and if we do, why is it being assigned to the user password rather than the hashed password?

**Comment by rafaelfranca** [comment]
It is to be used by validations on top of the original password not the hashed value. This value is only in memory and it is unset as soon the hashed password is sent to the database.
