### ISSUE TITLE
The word 'encrypted_password' raises red flags; time to rename?

### ISSUE THREAD

**Issue by salqadri** [plataformatec/devise#5025]
https://github.com/plataformatec/devise/blob/d1571627b78399b55b76c400a78c4a3f367dad2c/lib/devise/models/database_authenticatable.rb#L59

The word 'encrypted_password' is quite problematic. You should never encrypt a password. Granted it sounds like you guys are not really encrypting anymore and keeping the name for legacy reasons, but this name shows up in our database and raises major compliance concerns. The words 'encrypt' and 'password' should never go together. Please fix!

**Comment by rafaelfranca** [comment]
Sorry, renaming this is not worth the trouble since it will break different authentication methods and applications. Thank you for the suggestion tough.

**Comment by leogiertz** [comment]
@salqadri What kind of compliance issues?

**Comment by salqadri** [comment]
Security / Privacy compliance. It should never be possible to 'decrypt' a password, and if our database field is called 'encrypted_password' that raises serious flags.
