### ISSUE TITLE
Vulnerability Report : No CSRF Protection here

### ISSUE THREAD

**Issue by fozi6044** [plataformatec/devise#5026]
Hi Team,

I am a security Researcher and I found this vulnerability on your website.

Vulnerability: No CSRF Protection here

So here I will show you how CSRF protection is needed or capture code is a need in Password Reset form. So here is the POST request which I captured through the burp. I will send it to the repeater. I will flood a lot of new passwords through multiple clicks.

Regards, 
Muhammad Fauzan

**Comment by feliperenan** [comment]
Hi @fozi6044, I didn't understand your issue since CSRF is a feature provided by Rails. If you found a security issue into Devise, please send the report to: opensource@plataformatec.com.br and don't open an issue to not expose users that use Devise.

Thanks.

**Comment by fozi6044** [comment]
OKAY , Any bounty for me ???

**Comment by tegon** [comment]
It's not clear right now what the issue is (since Rails has CSRF protection built-in). Like @feliperenan mentioned above, please send us an email with the details of the issue.

**Comment by fozi6044** [comment]
okay i am sending you a video as a proof
