### ISSUE TITLE
Reset password token can't be blank.

### ISSUE THREAD

**Issue by ramaboo-deliv** [plataformatec/devise#5030]
## Environment

- Ruby 2.6.1
- Rails 5.2.2
- Devise 4.6.1

## Current behavior

I can't for the life of me get the reset_password_token to show up in the form. I am unsure if this is a devise issue or a simple_form issue or a rails issue:

Form I changed from hidden to normal text field. As you can see the value is blank even though its in the url:
<img width="798" alt="screen shot 2019-02-21 at 5 47 44 pm" src="https://user-images.githubusercontent.com/32721566/53214480-a3a6de00-3601-11e9-8f4c-497037587743.png">

it's also in the resource object:
<img width="785" alt="screen shot 2019-02-21 at 5 48 20 pm" src="https://user-images.githubusercontent.com/32721566/53214504-b9b49e80-3601-11e9-986b-0e4a5fca3d91.png">

here is my view code:
<img width="999" alt="screen shot 2019-02-21 at 5 50 06 pm" src="https://user-images.githubusercontent.com/32721566/53214513-c0431600-3601-11e9-82ea-6fb25580ef30.png">

None of my code is particularly strange. 
I tested it with a normal rails form and got the code to show up which makes me think maybe its a simple_form issue but I copied the code directly from the simple form generator.
<img width="945" alt="screen shot 2019-02-21 at 6 12 08 pm" src="https://user-images.githubusercontent.com/32721566/53215182-5a0bc280-3604-11e9-9be3-c7ed63830462.png">

# user.rb
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable

# routes.rb
devise_for :users
resources :users

## Expected behavior
I'd expect to see the reset_password_token.

**Comment by feliperenan** [comment]
Close in favor https://github.com/plataformatec/simple_form/issues/1642#issuecomment-466397234
