### ISSUE TITLE
NoMethodError: undefined method `setup' for Devise:Module

### ISSUE THREAD

**Issue by vishaltps** [plataformatec/devise#5053]
## Environment

- Ruby **[1.9.3p547]**
- Rails **[3.2.22.5]**
- Devise **[3.0.4]**

## Current behavior

When i try to run any rake or rails command, i am getting below error

> 
> rake aborted!
> NoMethodError: undefined method `setup' for Devise:Module
> /home/tatva/sites/Quotiful-API-master/config/initializers/devise.rb:3:in `<top (required)>'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `block in load'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `each'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `block in <class:Engine>'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
> /home/tatva/sites/Quotiful-API-master/config/environment.rb:5:in `<top (required)>'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/railties-3.2.22.5/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/bin/ruby_executable_hooks:24:in `eval'
> /home/tatva/.rvm/gems/ruby-1.9.3-p547@quotiful/bin/ruby_executable_hooks:24:in `<main>'
> Tasks: TOP => db:migrate => environment
> (See full trace by running task with --trace)
> 

## Expected behavior

Why i am getting this error. is this version issue of devise? I don't want to upgrade devise version as it will effect whole project.

Please help me to resolve this issue. Thanks in advance.

**Comment by mracos** [comment]
I tried to reproduce the error using [a fresh application](https://github.com/plataformatec/devise/files/3036219/app.zip) with the same versions that you provided but had no luck with it.

> Environment
Ruby [1.9.3p547]
Rails [3.2.22.5]
Devise [3.0.4]

Could you please provide us a sample application that reproduces the issue in isolation?

Thanks.

**Comment by vishaltps** [comment]
@mracos Sorry but i can't provide source code. is there any other way to give you more information about this issue?

**Comment by mracos** [comment]
I'm not asking for source code @vishaltps 😅
More like a sample application that reproduces the error (think of a `rails new` and `rails g devise:install` plus code modifications that would reproduce the error)
Makes sense?

**Comment by saiqulhaq** [comment]
based on the source code https://github.com/plataformatec/devise/blob/d401147f68/lib/generators/templates/devise.rb

it should be fine

do you have 'devise' gem in your Gemfile?

**Comment by vishaltps** [comment]
Sorry it was not issue of devise gem, it was issue of version related to bundler
