### ISSUE TITLE
Error getting sign_in/signin route

### ISSUE THREAD

**Issue by sechix** [plataformatec/devise#5060]
## Pre-check

It is not working with subdomains. My app not found routes for sign_in or signin with this code:

  constraints(Subdomain) do
    devise_for :users, path: '', path_names: { sign_in: 'signin', sign_out: 'signout' }, controllers: { :registrations => 'registrations', passwords: "passwords", sessions: "sessions", invitations: "invitations"}
end

I have to add this in order to get the signin:
constraints(Subdomain) do
    devise_scope :user do
        get '/signin', to: 'devise/sessions#new'
        post '/signin', to: 'devise/sessions#new'
        get '/signout', to: 'devise/sessions#destroy'
        post '/signout', to: 'devise/sessions#destroy'
    end
end
## Environment

- Ruby **[2.3.0]**
- Rails **[4.2.5]**
- Devise **[3.4.0]**

#

**Comment by mracos** [comment]
Hi! Thanks for the issue report.

Could you please provide us a sample application or a clear set of steps that we would have to do that reproduces the issue in isolation?
That would help us find the issue.

Thanks.

**Comment by sechix** [comment]
Finally I solved. It was an app problem. Thanks

**Comment by mracos** [comment]
Awesome! Thx. 😄
