### ISSUE TITLE
Devise doesn't use scoped errors for scoped views

### ISSUE THREAD

**Issue by shobhitic** [plataformatec/devise#5066]
## Environment

- Ruby 2.6.2p47
- Rails 5.2.2.1
- Devise 4.6.1

## Current behavior

When I generate views for a `user` resource, they have the errors rendered as

```ruby
render "devise/shared/error_messages", resource: resource
```

in place of the

```ruby
render "users/shared/error_messages", resource: resource
```

as is the case with shared links.

## Expected behavior

Views should use the scoped view to render errors, changing all

```ruby
render "devise/shared/error_messages", resource: resource
```

to 

```ruby
render "users/shared/error_messages", resource: resource
```

for a user resource.

**Comment by shobhitic** [comment]
I've pinpointed the problem, and fixed it, can someone tell me how to test the changes?

**Comment by shobhitic** [comment]
I've submitted a PR a month ago. Can someone please review it so it can be merged?

**Comment by tegon** [comment]
@shobhitic Sorry about that, I was not able to review it yet but I'll try to do it soon.

**Comment by shobhitic** [comment]
@tegon can you please go through the review if you have time now? There's about 10 lines of changes!

**Comment by shobhitic** [comment]
Can someone please review the attached PR?

**Comment by tegon** [comment]
@shobhitic Sorry about that, I'm solving some other things I have pending here and haven't had the time to review this yet. But I'll do it as soon as I can.
