### ISSUE TITLE
Rails 6.0.0.rc1 breaks layout proc set in intializer

### ISSUE THREAD

**Issue by twistedjoe** [plataformatec/devise#5077]
## Environment

- Ruby 2.6.2
- Rails Rails 6.0.0.rc1
- Devise 4.6.2 and 4.6.1

I got this in my initializers:

```
  Devise::RegistrationsController.layout proc { |controller| user_signed_in? ? "subpages" : "public_pages" }
  Devise::SessionsController.layout proc { |controller| user_signed_in? ? "subpages" : "public_pages" }
  Devise::PasswordsController.layout proc { |controller| user_signed_in? ? "subpages" : "public_pages" }
```

On Rails 6.0.0.beta3 and prior this was working just fine. Rendering with the `subpages` layout and the `public_pages` layout when logged out.

Since 6.0.0.rc1 the proc does not seem to be executed at all. 
I added a print  to the proc. I see it in beta3 but not rc1

## Current behavior
  Devise::RegistrationsController.layout 
  Devise::SessionsController.layout 
  Devise::PasswordsController.layout 
procs are ignored

## Expected behavior
  Devise::RegistrationsController.layout 
  Devise::SessionsController.layout 
  Devise::PasswordsController.layout  

Should set the layout for the respective controller

**Comment by twistedjoe** [comment]
Setting the layout like this

```
  layout proc { |controller| user_signed_in? ? "subpages" : "public_pages" }
```
in the application controller still seems to work in 6.0.0.rc1

**Comment by rafaelfranca** [comment]
This is hardly an issue on devise given that method is a Rails method. Can you create an application reproducing the problem and open an issue on Rails. Thank you.
