### ISSUE TITLE
I tried the solution you posted but whenever I log out I still can't go to the login page.

### ISSUE THREAD

**Issue by ueharajohji** [plataformatec/devise#5078]
Hi @fatosmorina , I tried the solution you posted but whenever I log out I still can't go to the login page.

_Originally posted by @ueharajohji in https://github.com/plataformatec/devise/issues/3031#issuecomment-494133055_

**Comment by mracos** [comment]
I don't think I got what is the issue that you are facing.

If you could please open a new issue with some code explaining what you're trying to achieve and more info I think it would help me understand what is that you are trying to achieve.

Thanks!
