### ISSUE TITLE
Params for Mailer (Rails 5.2 ~)

### ISSUE THREAD

**Issue by Samemura** [plataformatec/devise#5079]
## Environment

- Ruby 2.6.2
- Rails 5.2.2.1
- Devise 4.6.1

## Current behavior

Since rails 5.2, ActionMailer::Base can use params method to be commonize normal controller. https://edgeguides.rubyonrails.org/action_mailer_basics.html#mailers-are-similar-to-controllers

It is also good for mailer preview to switch locale so I think it would be used in Devise gem as well.

Do we have a plan to implement this ??

**Comment by rafaelfranca** [comment]
Thank you for the issue. The devise mailer will not take advantage of the parameterized mailer because it has many different methods on the mailer that don't share the same parameters. Thank you for the suggestion.

**Comment by dmitry** [comment]
@rafaelfranca why it's not a good idea to make all the mailers in devise to work as parametrized (using `with` method for the passing parameters into the mailer actions)?

**Comment by rafaelsales** [comment]
@rafaelfranca I'm needing to access device mailer params in ApplicationMailer on before_action. It sounds like using the _new_ params would be the way to go.

**Comment by rafaelsales** [comment]
Use case:
```ruby
class ApplicationMailer < ActionMailer::Base
  before_action :configure_default_url_options

  layout 'mailer'

  private

  def configure_default_url_options
    default_url_options[:host] = params[:user].organization.host
  end
```

after_action is too late as the template will be rendered with the wrong url options.

**Comment by rafaelsales** [comment]
@rafaelfranca @carlosantoniodasilva   I'm needing to access devise mailer params in ApplicationMailer on before_action. It sounds like using the _new_ params would be the way to go. The after_action is too late as the template will be rendered with the wrong url options.

Use case:
```ruby
class ApplicationMailer < ActionMailer::Base
  before_action :configure_default_url_options

  layout 'mailer'

  private

  def configure_default_url_options
    default_url_options[:host] = params[:user].organization.host
  end
end
```

Is this something we could consider at this point?

**Comment by carlosantoniodasilva** [comment]
@rafaelsales would you be able to specialize the [`devise_mail`](https://github.com/heartcombo/devise/blob/8e2e3f6fda1ceabe2eff08cf34a6e663527c438b/lib/devise/mailers/helpers.rb#L17) method and call `super`?

e.g. something like this in your mailer:

```ruby
def devise_mail(record, *args, &block)
  default_url_options[:host] = record.organization.host
  super
end
```

I haven't looked into mailer params in a while, but iirc they'd require a rework on how all Devise mailers work, so it'd likely be a breaking change and/or one that's difficult to maintain backwards compatibility. But if the above works for you, I think we can call it a day there. :)
