### ISSUE TITLE
Override error message for API

### ISSUE THREAD

**Issue by kinsbrunner** [plataformatec/devise#5082]
Hi,

I am working on an API which is consumed by another technology. When creating an entity, I am using the create! which triggers an exception under failure and I am returning an array with all the error and parse it as desired on the screen.

However, I have overridden the registration controller as I need to use a Transaction block and create another entity prior to the User. When the other entity fails, it does not even get to creating the user (this is correct). When creating a User and getting an error, the other transaction gets correctly rollbacked BUT the issue comes in that I am getting the exception with a single message which contains  all the errors together instead of getting an array of errors.

I have tried changing my code by removing the bang operator on the create and returning User.errors which returns the errors on the desired way BUT, as there is no exception, the initial entity does not get rollbacked. I have also tried triggering the exception manually but that makes me return the single message which is what I do not want to happen.

Has someone experienced the same? Is there a way to override this behaviour?

Regards.
Alejandro.

**Comment by mracos** [comment]
Hi @kinsbrunner,

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

Thank you!
