### ISSUE TITLE
Can no longer set authenticated and unauthenticated root paths in Rails 6

### ISSUE THREAD

**Issue by phillipspc** [plataformatec/devise#5084]
The following code worked properly for me running 
Ruby 2.5.1
Rails 5.2.2.1
Devise 4.6.2

```ruby
  authenticated :user do
    root to: "transactions#index"
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
```

However, after upgrading to Rails 6.0.0.rc1 and Ruby 2.6.3 I get the following error:
`Invalid route name, already in use: 'root'  (ArgumentError)`

This would appear related to a change discussed [here](https://github.com/rails/rails/issues/34854) 

If this is no longer valid routing syntax in Rails 6, how would I go about doing the same thing? (Just need a standard, unauthenticated root route, and a separate authenticated one).

**Comment by hayesr** [comment]
I just ran into this too. I got things going again with this answer: https://github.com/rails/rails/issues/34854#issuecomment-451512232

So I have something along these lines:

```ruby
  authenticated :user do
    root to: 'dashboards#show', as: :authenticated_user_root
  end

  authenticated :admin do
    root to: 'admin/dashboards#index', as: :authenticated_admin_root
  end
```

**Comment by phillipspc** [comment]
@hayesr thanks for the reply. So in my case, instead of two different authenticated roots, I'm trying to do an authenticated one, and an unauthenticated one. You happen to have any idea how to do this?
(feel like I need an `unauthenticated` option or something)

**Comment by rafaelfranca** [comment]
You will need to name one of the routes because Rails doesn't allow two routes with the same name anymore. I'm closing this issue since it is not a devise issue. Thank you.
