### ISSUE TITLE
Steam-like 2FA

### ISSUE THREAD

**Issue by davidkrider** [plataformatec/devise#5096]
I know I'm asking for help here, and this is discouraged, but I tried StackOverflow, and can't get a nibble. Current project management would like to configure Devise for an email-based 2FA, like Steam and lots of banks do, with an emailed code. It seems to me that the same sort of thing could be accomplished by having Devise send out a confirmation on every login, but so far, in my own experimentation, that seems to be a chicken-and-egg problem. Again, please forgive me for this faux pas, but this is an extremely non-googleable setup. I can't find anything about it, despite it seeming like a fairly common pattern.

**Comment by jasnow** [comment]
Maybe: https://github.com/plataformatec/devise/wiki/Extensions and search for "factor"

**Comment by davidkrider** [comment]
I had found devise-two-factor, which only seems to support 3rd-party stuff, like Google authenticator. I missed two_factor_authentication, which turned out to be exactly what I needed! Thanks very much!
