### ISSUE TITLE
Sign in and out a user in Request type specs tuto not working anymore when integrating OmniAuth into Rails API

### ISSUE THREAD

**Issue by YassineDM** [plataformatec/devise#5105]
## Environment

- Ruby 2.6.2
- Rails 6.0.0.rc2
- Devise 4.6.2

## Current behavior

Il followed proposed [tuto](https://github.com/plataformatec/devise/wiki/How-To:-sign-in-and-out-a-user-in-Request-type-specs-(specs-tagged-with-type:-:request)) to sign in and out a user in Request type specs and it worked fine. It introduces this sign_in method:
```ruby
  def sign_in(resource)
    login_as(resource, scope: warden_scope(resource))
  end
```

But as I am trying integrating OmniAuth into a Rails API, I stumbled upon their [section](https://github.com/omniauth/omniauth#integrating-omniauth-into-your-rails-api) when they advise to add in application.rb:
```ruby
config.session_store :cookie_store, key: '_interslice_session'
config.middleware.use ActionDispatch::Cookies # Required for all session management
config.middleware.use ActionDispatch::Session::CookieStore, config.session_options
``` 

This seems to be causing the sign_in method to fail with this error message:
```
undefined method `[]=' for nil:NilClass
```

Commenting config lines makes it work again...
## Expected behavior

Ability to sign in user

**Comment by tegon** [comment]
Hello @YassineDM, thanks for your report.

The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back.

You shouldn't need to define the `sign_in` method, using the `Devise::Test::IntegrationHelpers` module should be enough.

Thank you!

**Comment by YassineDM** [comment]
Hi @tegon, thank you for your answer.
I found a solution to my problem thanks to @mrstif in this [issue](https://github.com/plataformatec/devise/issues/4696). By the way, I noticed that you already exchanged with him on the matter...
Here is his answer for the record:
> Apparently, in rails-api mode, the `ActionDispatch::Cookies` and `ActionDispatch::Session::CookieStore` middlewares are inserted in the end of the middleware stack, which doesn't occur in normal Rails mode.
> 
> Due to this, those middlewares are included after Warden::Manager which messes up something in request specs...
> 
> Therefore, this solved it:
> 
> ```
> Rails.application.config.middleware.insert_before Warden::Manager, ActionDispatch::Cookies
> Rails.application.config.middleware.insert_before Warden::Manager, ActionDispatch::Session::CookieStore
> ```

Also, you're right, I didn't need to define the sign_in method, using the Devise::Test::IntegrationHelpers module was indeed enough. Thx again!
