### ISSUE TITLE
New release for rails 6.0

### ISSUE THREAD

**Issue by zocoi** [plataformatec/devise#5119]
Now rails 6 is out, would you mind release a new gem version for it? Thanks

**Comment by connorshea** [comment]
In the mean time, you can use devise from git if you want to upgrade to Rails 6: `gem 'devise', git: 'https://github.com/plataformatec/devise'`

Would love to see a proper release, though :)

**Comment by DaniG2k** [comment]
Upgrading to Rails 6. If I use Devise `1.5.4` I get the following error when running `rails app:update`:

```
rails aborted!
NoMethodError: undefined method `alias_method_chain' for ActionDispatch::Routing::RouteSet:Class
Did you mean?  alias_method
```

The method call occurs in `devise-1.5.4/lib/devise/rails/routes.rb:14`

**Comment by MarcSteven** [comment]
@connorshea  I think you should add the description into the doc, thank for your sharing!

**Comment by RouL** [comment]
I agree. Now that rails 6 is out, there should be a proper release. While it might be possible to use devise directly from the master branch, it is hardly a scenario for a production environment.

**Comment by tegon** [comment]
I'll try to do a release today.

**Comment by MarcSteven** [comment]
@tegon  Thank you so much about it

**Comment by tegon** [comment]
I've released version `4.7.0`. Since some people were already running Devise from `master` with Rails 6 and the tests are passing, it should be ok.
But if you run into any trouble, feel free to open other issues. Thanks!

**Comment by connorshea** [comment]
Thanks!

**Comment by ssaunier** [comment]
Thank you very much!

**Comment by jasnow** [comment]
Verified

**Comment by tbcooney** [comment]
Oh good day! Thanks @tegon
