### ISSUE TITLE
Rails 6: rails generate devise:install hangs(master)

### ISSUE THREAD

**Issue by sanford** [plataformatec/devise#5120]
## Environment

- Ruby 2.6.3
- Rails 6.0 (release)
- Devise: master branch

## Current behavior

rails g devise:install   hangs 

If you add the '--skip-spring' flag to 'rails new' it appears you can get the devise generator to run after

## Expected behavior

Generators are run

**Comment by ssaunier** [comment]
I believe that's not something specific to Rails 6, in the past I had students hanged on that very command for Rails 4 and Rails 5. The trick I told them was to:

```bash
spring stop
```

And then relaunch the command.

**Comment by tegon** [comment]
Yeah, this really looks like a Spring issue.
I just run the generator with a newly created Rails 6 app and everything worked correctly.

**Comment by CornerstoneII** [comment]
> ```shell
> spring stop
> ```

Works like a charm!
