### ISSUE TITLE
sending email with temporary password in it

### ISSUE THREAD

**Issue by Nitesh9872** [plataformatec/devise#5124]
i am trying to use email only signup and send the temporary password to the email provided.
user can login using there temporary password .if they wish they can change it any time.

i am new to devise can anyone tell me how to do this?

**Comment by mracos** [comment]
Hi @Nitesh9872!

As @gurgelrenan said, please use StackOverflow and the likes for questions/help where a wider community will be able to help you. We reserve the issues tracker for issues only.

Thanks!
