### ISSUE TITLE
How to use the Omniauth developer strategy with Devise?

### ISSUE THREAD

**Issue by jamesla** [plataformatec/devise#5128]
I am trying to find some documentation on how to use the omniauth developer strategy with devise but I am unable to find any documentation on how to use it or any examples online of how to make it work. Is there any example project or documentation on this feature?

**Comment by mracos** [comment]
Hi @jamesla!

Please use StackOverflow and the likes for questions/help where a wider community will be able to help you. We reserve the issues tracker for issues only.

But maybe this page [(OmniAuth: Overview)](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview) in the wiki can help you.

Thanks!
