### ISSUE TITLE
url not put to browser link after running autotests on real device

### ISSUE THREAD

**Issue by dimit999** [plataformatec/devise#5129]
hello everyone.

I have issue: i run my autotests on iOS emulators - via appium + Xcode - works fine.

But when i connect a real device - I see that WebAgent works, open safari browser and nothing in the end.

Error:
E       selenium.common.exceptions.WebDriverException: Message: cannot create session safari-MOBILE on any hosts after 1 attempt(s), last host error was: An unknown server-side error occurred while processing the command. Original error: operation timed out

PS. "Trust" was select in Setting-General, + Safari -> Advanced: JavaScript, Web Inspectors are enabled

Can you help me how to fix it

**Comment by gurgelrenan** [comment]
Have you tried to use solutions like https://www.browsersync.io or https://ngrok.com ? They helps me a lot with this type of tests.

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
