### ISSUE TITLE
Rails Admin

### ISSUE THREAD

**Issue by Bdoom** [plataformatec/devise#5137]
## == Devise ==
  config.authenticate_with do
    warden.authenticate! scope: :user
  end
  config.current_user_method(&:current_user)

I have this setup with RailsAdmin, I'm wondering if I can also check if a boolean named "admin" on my user is true. I only want people to access /admin if they are logged in with devise, and also have the "admin" column in the database, set to true. How can I do this?

**Comment by tegon** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
