### ISSUE TITLE
Warden config is malformed while running tests with rack-test

### ISSUE THREAD

**Issue by adamtomecek** [plataformatec/devise#5138]
I have this simple controller spec

```ruby
RSpec.describe HomeController, type: :controller do
  it 'redirects to login page if user is not logged in' do
    get :index
    expect(response).to redirect_to new_user_session_path
  end
end
```

In like one in five runs of full test suite (never encountered this while running this single test), I encounter this error. This also breaks CI builds quite often.

```
Failure/Error: get :index
     
     NoMethodError:
       undefined method `call' for nil:NilClass
     # /usr/local/bundle/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:140:in `_process_unauthenticated'
     # /usr/local/bundle/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:118:in `_catch_warden'
     # /usr/local/bundle/gems/devise-4.7.1/lib/devise/test/controller_helpers.rb:35:in `process'
     # ./spec/controllers/home_controller_spec.rb:5:in `block (2 levels) in <top (required)>'
```

Where `Devise.warden_config[:failure_app]` is nil in `_process_unauthenticated`.

Full failing `Devise.warden_config` looks like this:
```
{:default_scope=>:default,
 :scope_defaults=>{},
 :default_strategies=>{},
 :intercept_401=>true}
```

While regular config is

```
{:default_scope=>:user,
 :scope_defaults=>{},
 :default_strategies=>{:user=>[:rememberable, :database_authenticatable]},
 :intercept_401=>false,
 :failure_app=>#<Devise::Delegator:0x00007fe5769f6a38>}
``` 

I'm not manipulating Warden config in my app whatsoever.

This can possibly be related to `rack-test` gem and `Rack::Attack` spec I've added as those are the only changes in my code since everything was working properly.

Ruby 2.6.2p47
Rails 5.2.3
Devise 4.7.1

**Comment by adamtomecek** [comment]
Just found out how to reproduce the error in the description.

This test, specially the part with creating new Rails app (Rack::Attack middleware does not matter here) is causing it in combination with the `POST` request. Running this before test in the description will 100 % reproduce the error.

```
RSpec.describe 'Test Spec' do
  include Rack::Test::Methods

  def app
    Class.new(Rails.application.class) do
      config.middleware.use Rack::Attack
    end
  end

  it 'does request' do
    post '/users/sign_in'
  end
end
```

Can this be Devise bug or is this more `rack-test` bug? Will try and create example app tomorrow.

**Comment by adamtomecek** [comment]
Here it is reproduced in new Rails 5.2.3 app https://github.com/adamtomecek/devise_rack_test_demo/blob/master/spec/controllers/home_controller_spec.rb

**Comment by mracos** [comment]
Hi @adamtomecek! Thanks for the detailed report. 💙

Will try to take a look into it. 😄

**Comment by mracos** [comment]
@adamtomecek It doesn't seem a devise issue to me.

I changed `def app` in your sample application to the following and the tests passed.
```ruby
def app
  Rack::Builder.new do
    # we can use rack attack here: `use Rack::Attack`
    run Rails.application
  end
end
```

So will close this issue but If you're still facing this please open a new one. 😄 
Thanks!

**Comment by adamtomecek** [comment]
Works like a charm. Thanks!
