### ISSUE TITLE
:require_no_authentication should get its own redirect_url helper

### ISSUE THREAD

**Issue by krtschmr** [plataformatec/devise#5150]
## Current behavior

if we are already authenticated, the `before_action :require_no_authentication` redirects us to the `after_sign_in_path_for`.

I feel this is slightly inflexible and we might consider changing it to `after_already_signed_in_path_for`. In that case, the developer can easy decide where to go, without replacing the whole method, just for a path change.

https://github.com/plataformatec/devise/blob/ffeb942699494170e943a9a61667948e8f6f5d01/app/controllers/devise_controller.rb#L116

**Comment by tegon** [comment]
> I feel this is slightly inflexible and we might consider changing it to after_already_signed_in_path_for. In that case, the developer can easy decide where to go, without replacing the whole method, just for a path change.

In this new case, the developer would also need to replace the whole method - i.e. `after_already_signed_in_path_for` - in order to supply the customized behavior, right?

**Comment by krtschmr** [comment]
> > I feel this is slightly inflexible and we might consider changing it to after_already_signed_in_path_for. In that case, the developer can easy decide where to go, without replacing the whole method, just for a path change.
> 
> In this new case, the developer would also need to replace the whole method - i.e. `after_already_signed_in_path_for` - in order to supply the customized behavior, right?

we could have it done in configuration but the reason why this is needed it the logical flow. 
after sign_in we send the user to some special place, and if he was logged in already we send him straight to the dashboard

to do so, we had to override `require_no_authentication` but with this feature it's just a small override of `after_already_signed_in_path_for`, or i extend it and it can be done via configuration

**Comment by tegon** [comment]
I see. Although I realize it's easier to solve your case with this new feature, it seems reasonably ok to override the method as it is today.
If this becomes a popular feature request, we can think about supporting in a next version.

Thank you!

**Comment by krtschmr** [comment]
@tegon  i have to disagree that we neglect this. we have a `after_sign_in` and `after_sign_out`. why not add a `already_signed_in`? 

it's the logical path to follow

**Comment by tegon** [comment]
I don't think they're all the same. The first two are related to actions that were performed - they have the `after_` prefix. That's not the case with `already_signed_in`.
But as I said, I would be willing to accept something like this if there's a bigger demand for it. Since most applications seem to be fine with only `after_sign_in_path`, I rather wait before including another configuration option.
