### ISSUE TITLE
Invalid Reset Password token Devise and rails 5.2 - Sometimes works

### ISSUE THREAD

**Issue by viveki2it** [plataformatec/devise#5164]
### Environment
Ruby ruby-2.5.3(RVM)
Rails 5.2.3
Devise 4.7.0
### Issue
I am using the **send_reset_password_instructions** method to send the forgot password instruction to resource email. Then I can get an email and try to reset password but sometimes used to get validation "Reset password token invalid" in only production URL. But, **a couple of retries should work**. It is very strange I did not find the exact issue and solution for this. Even I have tried with override below method **find_first_by_auth_conditions**. But, did not help. I guess the same issue without override passwords controller.

```
def self.find_first_by_auth_conditions warden_conditions
    conditions = warden_conditions.dup
    if (email = conditions.delete(:email)).present?
      where(email: email.downcase).first
    elsif conditions.has_key?(:reset_password_token)
      where(reset_password_token: conditions[:reset_password_token]).first
    end
  end  
```
I do not think send_reset_password_instructions is this issue. It is working fine in local. One thing I need to mention We are using the multiple APP servers. I am thinking is that the unencrypt reset password is not working with multiple APP servers.

**Thanks in advance!**

**Comment by tegon** [comment]
Hello @viveki2it, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
Another option is to use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by viveki2it** [comment]
Hi @tegon 

Please check below detailed information -> I guess, The issue with decrypt reset_password_token from the token as we get from email using with two app servers. But, when we get a request to one app server it is working fine but not another app server. Maybe, It is working fine from the which server generated reset password token encrypted. 

Email URL -> /users/password/edit?reset_password_token=tNw1nqXqAa6c8Y9yUkGg

APP Server 1 -> decrypted token with above token -> 6376d5b06682e8c0e627458a6a5654706c30a61ef19c1b2a985fbaa1aade1072

APP Server 2 -> decrypted token with above email token -> b1040564c63d8f3336bddc050f06a6e4b04c6df06718643f7b9bea050c02631a

When request sends to APP server 2 it will work fine because in the database this reset password token got saved. But, If request sends to the APP server 1 not working. I need a solution to seamless with any APP server. It might be an issue with encrypting or decrypt token within APP servers.

Thanks!

**Comment by tegon** [comment]
@viveki2it thanks for the information!

Can you check in both servers what `Devise.secret_key` returns (don't send them here though)? If they are different, that's probably the cause of the issue.

**Comment by viveki2it** [comment]
@tegon Yes, That was the issue and fixed that some hours back. Looks like it was working fine. Thanks!
