### ISSUE TITLE
The action 'twitter' could not be found for Devise::OmniauthCallbacksController

### ISSUE THREAD

**Issue by caioariede** [plataformatec/devise#615]
I am trying to implement Twitter oauth using omniauth branch, but when user is redirected I always get the error:

The action 'twitter' could not be found for Devise::OmniauthCallbacksController

I implemented and configured the callbacks as wiki says, but no way to get it to work.

**Comment by rk-panchal** [comment]
The action 'facebook' could not be found for Accounts::OmniauthCallbacksControlle

**Comment by moeabdol** [comment]
If you're following everything correctly, then it might be that you have mistakenly forgotten the 's' in callbacks. I know....I did this stupid mistake!
