### ISSUE TITLE
problems with callbacks routing for omniauth

### ISSUE THREAD

**Issue by holden** [plataformatec/devise#627]
Error: Started GET "/users/auth/facebook/callback?code=dd24b9963343fb0543b59b02-561810769%7CHnyoPUawYLSozy2tVyAFMiFRikE" for 127.0.0.1 at Fri Nov 05 09:28:23 +0100 2010

ActionController::RoutingError (uninitialized constant Users):

Using the latest branch for omniauth

  remote: git://github.com/plataformatec/devise
  revision: ab033ea986897c600658fc6f2245e1e7d7bfa514
  branch: omniauth

Followed the wiki for setting it up, everything worked up to handling the callback route,
have a standard devise install that works, changed the default devise route to:

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } and added the omniauth_callbacks controller...

 new_user_session GET    /users/sign_in(.:format)                              {:controller=>"devise/sessions", :action=>"new"}
                      user_session POST   /users/sign_in(.:format)                              {:controller=>"devise/sessions", :action=>"create"}
              destroy_user_session GET    /users/sign_out(.:format)                             {:controller=>"devise/sessions", :action=>"destroy"}
            user_omniauth_callback        /users/auth/:action/callback(.:format)                {:controller=>"users/omniauth_callbacks", :action=>/facebook|twitter/}
                     user_password POST   /users/password(.:format)                             {:controller=>"devise/passwords", :action=>"create"}
                 new_user_password GET    /users/password/new(.:format)                         {:controller=>"devise/passwords", :action=>"new"}
                edit_user_password GET    /users/password/edit(.:format)                        {:controller=>"devise/passwords", :action=>"edit"}
                     user_password PUT    /users/password(.:format)                             {:controller=>"devise/passwords", :action=>"update"}
          cancel_user_registration GET    /users/cancel(.:format)                               {:controller=>"devise/registrations", :action=>"cancel"}
                 user_registration POST   /users(.:format)                                      {:controller=>"devise/registrations", :action=>"create"}
             new_user_registration GET    /users/sign_up(.:format)                              {:controller=>"devise/registrations", :action=>"new"}
            edit_user_registration GET    /users/edit(.:format)                                 {:controller=>"devise/registrations", :action=>"edit"}
                 user_registration PUT    /users(.:format)                                      {:controller=>"devise/registrations", :action=>"update"}
                 user_registration DELETE /users(.:format)                                      {:controller=>"devise/registrations", :action=>"destroy"}

**Comment by MorganaTBorges** [comment]
I had the same problem! Thanks a lot
