### ISSUE TITLE
Cannot login using devise in production

### ISSUE THREAD

**Issue by envex** [plataformatec/devise#645]
Hello,

I have devise up and running perfectly on my localhost. As soon as I push it to the server and set to production, I can only login to the site when a new user is created.

If I try to login using an existing username/password, I'm given a "Invalid email or password." error.

If I log out of the newly created user, which is logged in, I can't log back in. Even if I try immediately.

Is there a step in devise that I'm missing when pushing to production?

Thanks,

Matt

**Comment by hcn1519** [comment]
Can anyboby tell me about this issue some more? I got same issue but rails devise's default setting is config.http_authenticatable = false
