### ISSUE TITLE
Could not find generator devise:install

### ISSUE THREAD

**Issue by bournenapster** [plataformatec/devise#753]
rails generate devise:install i ran it on terminal 

and i am getting this error

Could not find generator devise:install

**Comment by prakashhhhk** [comment]
worked like charm,,,... thanks

**Comment by mercypatin** [comment]
For me it's not working. I'm using rails 4.2.1 and I added the Gem "devise" to Gemfile, and bundle install ant when i put "rails generate devise:install " it says the same error...

**Comment by slavajacobson** [comment]
Same problem.

**Comment by tfantina** [comment]
Same problem I always get this: Could not find generator 'devise:install'. Maybe you meant 'assets', 'generator' or 'coffee:assets'
Run `rails generate --help` for more options.

**Comment by djnilo** [comment]
I fixed it by adding the following line to my Gemfile:

gem 'devise' 
After adding that line, I executed bundle install
http://stackoverflow.com/questions/24889925/cant-install-devise

**Comment by OvWO** [comment]
Double check that you saved the Gemfile after adding:
gem 'devise'

**Comment by jaspertomas** [comment]
https://github.com/plataformatec/devise/issues/4594
In rails 5, please try to run 
spring stop 
before you do
rails generate devise:install

**Comment by kfricks** [comment]
Make sure you're in the correct project within your code editor. It makes all the difference in the world!

**Comment by davidwparker** [comment]
Just a note for those Googling:
If you have it in our gemfile already and have bundle installed ok- check to make sure you don't have spring running: `ps aux | grep spring`.
If you do, you may need to kill the process- this keeps and uses existing rails processes to be faster in dev mode.
Killing that process allowed this to work for me.

**Comment by yasir-devsinc** [comment]
@bournenapster
Problem solved, thanks

**Comment by devHaitham481** [comment]
you can try to put this inside your `Gemfile` instead of just `gem 'devise'`
```
gem 'devise', github: 'ghiculescu/devise', branch: 'patch-2'
```

Re-run `bundle install` 

and then you can do `rails generate devise:install`
