### ISSUE TITLE
Add update_without_password to Devise

### ISSUE THREAD

**Issue by inkstak** [plataformatec/devise#801]
Hi,

I've read the following wiki : https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password-

> For obvious security reason, a user CANNOT modify his password when signed in

However, the use of the method :update_attributes on a resource will allow anyone to pass over such restrictions, when signed in.

<pre><code>resource.update_attributes :password => 'password', :password_confirmation => 'password'
 => true 
resource.valid_password? 'password'
 => true 
</code></pre>

So, I've started trying to fix this issue by doing the following stuff :

<pre><code>
  def update_attributes_with_password(params={})
    if !params[:password].nil?
      update_with_password(params)
    else
      update_attributes_without_password(params)
    end
  end
  alias_method_chain :update_attributes, :password

  # Update record attributes when :current_password matches, otherwise returns
  # error on :current_password. It also automatically rejects :password and
  # :password_confirmation if they are blank.
  def update_with_password(params={})
    current_password = params.delete(:current_password)

    #if params[:password].blank?
    #  params.delete(:password)
    #  params.delete(:password_confirmation) if params[:password_confirmation].blank?
    #end

    result = if valid_password?(current_password)
      update_attributes_without_password(params)
    else
      self.attributes = params
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end

    clean_up_passwords
    result
  end
</code></pre>

I'm not yet a senior on Ror and I just start playing with Devise (a great work btw, thanks) so feel free to comment or improve it in a more appropriate manner.

**Comment by grancondor** [comment]
update_without_password not work yet
