### ISSUE TITLE
Net::SMTPSyntaxError when sending confirmation (SOLVED!)

### ISSUE THREAD

**Issue by fourcolors** [plataformatec/devise#939]
Hi all, 

I'm setting up a new devise app and i moved my views to my app/views/users folder (don't know if that makes a difference. Also, my routes look like this. 

devise_for :users, :controllers => {:confirmations => "users/confirmations", :passwords => "users/passwords", :sessions => "users/sessions", :registrations => "users/registrations"} do
   get 'login', :to => 'users/sessions#new'
    post 'login', :to  => 'users/sessions#create'
    get 'sign_up', :to => 'users/registrations#new'
  end

Also i have a file in my initializers folder called setup_mail.rb with this in it. 

ActionMailer::Base.smtp_settings = {
  :address => 'smtp.sendgrid.net',
  :port => '25',
  :domain => '******_.com',
  :authentication => :plain, 
  :user_name => '**_**@gmail.com',
  :password => '********'
}

Ok so when I try to create a new account, I get this error 

Net::SMTPSyntaxError in Users/registrationsController#create

501 Syntax error

Rails.root: /Users/node/Projects/memorysunnew
Application Trace | Framework Trace | Full Trace

app/controllers/users/registrations_controller.rb:23:in `create'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"bPYLI31WdtxiTnfDy8fFImYbyaGB4BnifkBYWDRsG5Y=",
 "user"=>{"first_name"=>"joe",
 "last_name"=>"doe",
 "public_name"=>"jo",
 "email"=>"test@test.com",
 "password"=>"[FILTERED]",
 "password_confirmation"=>"[FILTERED]",
 "birthday(1i)"=>"1902",
 "birthday(2i)"=>"4",
 "birthday(3i)"=>"2",
 "gender"=>"Male",
 "terms"=>"1"},
 "commit"=>"Create"}

Show session dump

Show env dump
Response

Headers:

None

I"m not sure whats making this givine me a syntax error. I haven't changed anything inside of the project. This seems like a bug in devise? Or maybe i'm over looking something simple?

**Comment by fuggfuggfugg** [comment]
Putting it out there, I just encountered this error. In this case, the email of the user created was incorrect 'mailto:xxx@yyy.com'

**Comment by bransynluther** [comment]
YEESSSSS THANK YOU SO MUCH!!!! I was missing the ```sometext@``` before my ending domain.
