### ISSUE TITLE
Devise automatically logs off current user on password change

### ISSUE THREAD

**Issue by krzkrzkrz** [plataformatec/devise#971]
I am using 1.3.0.dev

Ive got an admin account which enables him to change other user's passwords. Every time this happens, Devise logs out the user. I don't understand why Devise needs to log out users whose passwords have been changed. Really strange behavior.

What is the recommended workaround / solution for this.

My code can be found here: https://gist.github.com/903366

A temporary solution I have come up with is:

```
def update
  @admin = Admin.find(params[:id])
  authorize! :manage, current_admin

  respond_to do |format|
    if @admin.update_attributes(params[:admin])
      sign_in(@admin, :bypass => true)
      format.html { redirect_to([:admin, @admin], :notice => 'Admin was successfully updated.') }
      format.xml  { head :ok }
    else
      format.html { render :action => "edit" }
      format.xml  { render :xml => @admin.errors, :status => :unprocessable_entity }
    end
  end
end
```

However, with above code, I am concerned that if I change an admins password who is logged on, it will force him to log off, if he is already logged in. Could be wrong here...

**Comment by albertnetymk** [comment]
> This feature was added exactly for such scenarios, an admin, when edits someones password, can be sure that the person will be signed out.

This is very reasonable. However, the current user (who made the password change) is logged out as well, which is a bit counter intuitive, IMO. BTW, I am using devise 4.1.1.
