### ISSUE TITLE
i18n mailer templates

### ISSUE THREAD

**Issue by plentz** [plataformatec/devise#973]
mailer templates aren't i18ned

**Comment by Erowlin** [comment]
Sorry to bump this 4 years later, but we still can't use I18n localized views with emails. Tried creating  a specialized view but it didn't work.

**Comment by rgpass** [comment]
Bumping this 1.5 years later. Has this been fixed?

**Comment by tegon** [comment]
@rgpass is the localized template option not working for you?

**Comment by rgpass** [comment]
The template strategy partially worked. I wanted to set the locale in the mailer rather than having to call `I18n.t('my-translation-call', locale: @resource.locale)`. I did this doing:

```ruby
# ./app/mailers/custom_devise_mailer.rb
class CustomDeviseMailer < Devise::Mailer
  def devise_mail(*args)
    user = args.first
    I18n.locale = user&.locale || I18n.default_locale
    super
  end
end
```

Now my views are much easier to read:

```haml
- content_for :subtitle, I18n.t('devise.unlocks.mail.subtitle')
%p= I18n.t('devise.unlocks.mail.instructions')
%center
  = link_to I18n.t('devise.unlocks.mail.button'), unlock_url(@resource, unlock_token: @token), class: 'btn btn-primary'
  %p
    = I18n.t('devise.unlocks.mail.note')
```

Thanks for the response!
